module HubSpotSDK
  module Models
    module Automation
      module Actions
        type callback_complete_params =
          { callback_id: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class CallbackCompleteParams < HubSpotSDK::Models::Automation::CallbackCompletionRequest
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def callback_id: -> String

          def callback_id=: (String _) -> String

          def initialize: (
            callback_id: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            callback_id: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
