module HubSpotSDK
  module Models
    module Automation
      module Actions
        type definition_get_params =
          { app_id: Integer, definition_id: String, archived: bool }
          & HubSpotSDK::Internal::Type::request_parameters

        class DefinitionGetParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor app_id: Integer

          attr_accessor definition_id: String

          attr_reader archived: bool?

          def archived=: (bool) -> bool

          def initialize: (
            app_id: Integer,
            definition_id: String,
            ?archived: bool,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            app_id: Integer,
            definition_id: String,
            archived: bool,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
