module HubspotSDK
  module Models
    module Automation
      module Actions
        type revision_list_params =
          { app_id: Integer, after: String, limit: Integer }
          & HubspotSDK::Internal::Type::request_parameters

        class RevisionListParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_accessor app_id: Integer

          attr_reader after: String?

          def after=: (String) -> String

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          def initialize: (
            app_id: Integer,
            ?after: String,
            ?limit: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            app_id: Integer,
            after: String,
            limit: Integer,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
