module HubSpotSDK
  module Models
    module Automation
      module Actions
        type revision_list_params =
          {
            app_id: Integer,
            definition_id: String,
            after: String,
            limit: Integer
          }
          & HubSpotSDK::Internal::Type::request_parameters

        class RevisionListParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor app_id: Integer

          attr_accessor definition_id: String

          attr_reader after: String?

          def after=: (String) -> String

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          def initialize: (
            app_id: Integer,
            definition_id: String,
            ?after: String,
            ?limit: Integer,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            app_id: Integer,
            definition_id: String,
            after: String,
            limit: Integer,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
