module HubspotSDK
  module Models
    module Cms
      module Blogs
        type angle =
          { units: HubspotSDK::Models::Cms::Blogs::Angle::units, value: Float }

        class Angle < HubspotSDK::Internal::Type::BaseModel
          attr_accessor units: HubspotSDK::Models::Cms::Blogs::Angle::units

          attr_accessor value: Float

          def initialize: (
            units: HubspotSDK::Models::Cms::Blogs::Angle::units,
            value: Float
          ) -> void

          def to_hash: -> {
            units: HubspotSDK::Models::Cms::Blogs::Angle::units,
            value: Float
          }

          type units = :deg | :grad | :rad | :turn

          module Units
            extend HubspotSDK::Internal::Type::Enum

            DEG: :deg
            GRAD: :grad
            RAD: :rad
            TURN: :turn

            def self?.values: -> ::Array[HubspotSDK::Models::Cms::Blogs::Angle::units]
          end
        end
      end
    end
  end
end
