module HubSpotSDK
  module Models
    module Cms
      module Blogs
        type batch_input_tag = { inputs: ::Array[HubSpotSDK::Cms::Blogs::Tag] }

        class BatchInputTag < HubSpotSDK::Internal::Type::BaseModel
          attr_accessor inputs: ::Array[HubSpotSDK::Cms::Blogs::Tag]

          def initialize: (inputs: ::Array[HubSpotSDK::Cms::Blogs::Tag]) -> void

          def to_hash: -> { inputs: ::Array[HubSpotSDK::Cms::Blogs::Tag] }
        end
      end
    end
  end
end
