module HubspotSDK
  module Models
    module Cms
      module Blogs
        type batch_response_blog_author_with_errors =
          {
            completed_at: Time,
            results: ::Array[HubspotSDK::Cms::Blogs::BlogAuthor],
            started_at: Time,
            status: HubspotSDK::Models::Cms::Blogs::BatchResponseBlogAuthorWithErrors::status,
            errors: ::Array[HubspotSDK::StandardError],
            links: ::Hash[Symbol, String],
            num_errors: Integer,
            requested_at: Time
          }

        class BatchResponseBlogAuthorWithErrors < HubspotSDK::Internal::Type::BaseModel
          attr_accessor completed_at: Time

          attr_accessor results: ::Array[HubspotSDK::Cms::Blogs::BlogAuthor]

          attr_accessor started_at: Time

          attr_accessor status: HubspotSDK::Models::Cms::Blogs::BatchResponseBlogAuthorWithErrors::status

          attr_reader errors: ::Array[HubspotSDK::StandardError]?

          def errors=: (
            ::Array[HubspotSDK::StandardError]
          ) -> ::Array[HubspotSDK::StandardError]

          attr_reader links: ::Hash[Symbol, String]?

          def links=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

          attr_reader num_errors: Integer?

          def num_errors=: (Integer) -> Integer

          attr_reader requested_at: Time?

          def requested_at=: (Time) -> Time

          def initialize: (
            completed_at: Time,
            results: ::Array[HubspotSDK::Cms::Blogs::BlogAuthor],
            started_at: Time,
            status: HubspotSDK::Models::Cms::Blogs::BatchResponseBlogAuthorWithErrors::status,
            ?errors: ::Array[HubspotSDK::StandardError],
            ?links: ::Hash[Symbol, String],
            ?num_errors: Integer,
            ?requested_at: Time
          ) -> void

          def to_hash: -> {
            completed_at: Time,
            results: ::Array[HubspotSDK::Cms::Blogs::BlogAuthor],
            started_at: Time,
            status: HubspotSDK::Models::Cms::Blogs::BatchResponseBlogAuthorWithErrors::status,
            errors: ::Array[HubspotSDK::StandardError],
            links: ::Hash[Symbol, String],
            num_errors: Integer,
            requested_at: Time
          }

          type status = :CANCELED | :COMPLETE | :PENDING | :PROCESSING

          module Status
            extend HubspotSDK::Internal::Type::Enum

            CANCELED: :CANCELED
            COMPLETE: :COMPLETE
            PENDING: :PENDING
            PROCESSING: :PROCESSING

            def self?.values: -> ::Array[HubspotSDK::Models::Cms::Blogs::BatchResponseBlogAuthorWithErrors::status]
          end
        end
      end
    end
  end
end
