module HubspotSDK
  module Models
    module Cms
      module Blogs
        type batch_response_tag_with_errors =
          {
            completed_at: Time,
            results: ::Array[HubspotSDK::Cms::Blogs::Tag],
            started_at: Time,
            status: HubspotSDK::Models::Cms::Blogs::BatchResponseTagWithErrors::status,
            errors: ::Array[HubspotSDK::StandardError],
            links: ::Hash[Symbol, String],
            num_errors: Integer,
            requested_at: Time
          }

        class BatchResponseTagWithErrors < HubspotSDK::Internal::Type::BaseModel
          attr_accessor completed_at: Time

          attr_accessor results: ::Array[HubspotSDK::Cms::Blogs::Tag]

          attr_accessor started_at: Time

          attr_accessor status: HubspotSDK::Models::Cms::Blogs::BatchResponseTagWithErrors::status

          attr_reader errors: ::Array[HubspotSDK::StandardError]?

          def errors=: (
            ::Array[HubspotSDK::StandardError]
          ) -> ::Array[HubspotSDK::StandardError]

          attr_reader links: ::Hash[Symbol, String]?

          def links=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

          attr_reader num_errors: Integer?

          def num_errors=: (Integer) -> Integer

          attr_reader requested_at: Time?

          def requested_at=: (Time) -> Time

          def initialize: (
            completed_at: Time,
            results: ::Array[HubspotSDK::Cms::Blogs::Tag],
            started_at: Time,
            status: HubspotSDK::Models::Cms::Blogs::BatchResponseTagWithErrors::status,
            ?errors: ::Array[HubspotSDK::StandardError],
            ?links: ::Hash[Symbol, String],
            ?num_errors: Integer,
            ?requested_at: Time
          ) -> void

          def to_hash: -> {
            completed_at: Time,
            results: ::Array[HubspotSDK::Cms::Blogs::Tag],
            started_at: Time,
            status: HubspotSDK::Models::Cms::Blogs::BatchResponseTagWithErrors::status,
            errors: ::Array[HubspotSDK::StandardError],
            links: ::Hash[Symbol, String],
            num_errors: Integer,
            requested_at: Time
          }

          type status = :PENDING | :PROCESSING | :CANCELED | :COMPLETE

          module Status
            extend HubspotSDK::Internal::Type::Enum

            PENDING: :PENDING
            PROCESSING: :PROCESSING
            CANCELED: :CANCELED
            COMPLETE: :COMPLETE

            def self?.values: -> ::Array[HubspotSDK::Models::Cms::Blogs::BatchResponseTagWithErrors::status]
          end
        end
      end
    end
  end
end
