module HubspotSDK
  module Models
    module Cms
      class BlogPost = Blogs::BlogPost

      module Blogs
        type blog_post =
          {
            id: String,
            ab_status: HubspotSDK::Models::Cms::Blogs::BlogPost::ab_status,
            ab_test_id: String,
            archived_at: Integer,
            archived_in_dashboard: bool,
            attached_stylesheets: ::Array[::Hash[Symbol, top]],
            author_name: String,
            blog_author_id: String,
            campaign: String,
            category_id: Integer,
            content_group_id: String,
            content_type_category: HubspotSDK::Models::Cms::Blogs::BlogPost::content_type_category,
            created: Time,
            created_by_id: String,
            currently_published: bool,
            current_state: HubspotSDK::Models::Cms::Blogs::BlogPost::current_state,
            domain: String,
            dynamic_page_data_source_id: String,
            dynamic_page_data_source_type: Integer,
            dynamic_page_hub_db_table_id: String,
            enable_domain_stylesheets: bool,
            enable_google_amp_output_override: bool,
            enable_layout_stylesheets: bool,
            featured_image: String,
            featured_image_alt_text: String,
            folder_id: String,
            footer_html: String,
            head_html: String,
            html_title: String,
            include_default_custom_css: bool,
            language: HubspotSDK::Models::Cms::Blogs::BlogPost::language,
            layout_sections: ::Hash[Symbol, HubspotSDK::Cms::LayoutSection],
            link_rel_canonical_url: String,
            mab_experiment_id: String,
            meta_description: String,
            name: String,
            page_expiry_date: Integer,
            page_expiry_enabled: bool,
            page_expiry_redirect_id: Integer,
            page_expiry_redirect_url: String,
            password: String,
            post_body: String,
            post_summary: String,
            public_access_rules: ::Array[top],
            public_access_rules_enabled: bool,
            publish_date: Time,
            publish_immediately: bool,
            rss_body: String,
            rss_summary: String,
            slug: String,
            state: String,
            tag_ids: ::Array[Integer],
            theme_settings_values: ::Hash[Symbol, top],
            translated_from_id: String,
            translations: ::Hash[Symbol, HubspotSDK::Cms::PagesContentLanguageVariation],
            updated: Time,
            updated_by_id: String,
            url: String,
            use_featured_image: bool,
            widget_containers: ::Hash[Symbol, top],
            widgets: ::Hash[Symbol, top]
          }

        class BlogPost < HubspotSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor ab_status: HubspotSDK::Models::Cms::Blogs::BlogPost::ab_status

          attr_accessor ab_test_id: String

          attr_accessor archived_at: Integer

          attr_accessor archived_in_dashboard: bool

          attr_accessor attached_stylesheets: ::Array[::Hash[Symbol, top]]

          attr_accessor author_name: String

          attr_accessor blog_author_id: String

          attr_accessor campaign: String

          attr_accessor category_id: Integer

          attr_accessor content_group_id: String

          attr_accessor content_type_category: HubspotSDK::Models::Cms::Blogs::BlogPost::content_type_category

          attr_accessor created: Time

          attr_accessor created_by_id: String

          attr_accessor currently_published: bool

          attr_accessor current_state: HubspotSDK::Models::Cms::Blogs::BlogPost::current_state

          attr_accessor domain: String

          attr_accessor dynamic_page_data_source_id: String

          attr_accessor dynamic_page_data_source_type: Integer

          attr_accessor dynamic_page_hub_db_table_id: String

          attr_accessor enable_domain_stylesheets: bool

          attr_accessor enable_google_amp_output_override: bool

          attr_accessor enable_layout_stylesheets: bool

          attr_accessor featured_image: String

          attr_accessor featured_image_alt_text: String

          attr_accessor folder_id: String

          attr_accessor footer_html: String

          attr_accessor head_html: String

          attr_accessor html_title: String

          attr_accessor include_default_custom_css: bool

          attr_accessor language: HubspotSDK::Models::Cms::Blogs::BlogPost::language

          attr_accessor layout_sections: ::Hash[Symbol, HubspotSDK::Cms::LayoutSection]

          attr_accessor link_rel_canonical_url: String

          attr_accessor mab_experiment_id: String

          attr_accessor meta_description: String

          attr_accessor name: String

          attr_accessor page_expiry_date: Integer

          attr_accessor page_expiry_enabled: bool

          attr_accessor page_expiry_redirect_id: Integer

          attr_accessor page_expiry_redirect_url: String

          attr_accessor password: String

          attr_accessor post_body: String

          attr_accessor post_summary: String

          attr_accessor public_access_rules: ::Array[top]

          attr_accessor public_access_rules_enabled: bool

          attr_accessor publish_date: Time

          attr_accessor publish_immediately: bool

          attr_accessor rss_body: String

          attr_accessor rss_summary: String

          attr_accessor slug: String

          attr_accessor state: String

          attr_accessor tag_ids: ::Array[Integer]

          attr_accessor theme_settings_values: ::Hash[Symbol, top]

          attr_accessor translated_from_id: String

          attr_accessor translations: ::Hash[Symbol, HubspotSDK::Cms::PagesContentLanguageVariation]

          attr_accessor updated: Time

          attr_accessor updated_by_id: String

          attr_accessor url: String

          attr_accessor use_featured_image: bool

          attr_accessor widget_containers: ::Hash[Symbol, top]

          attr_accessor widgets: ::Hash[Symbol, top]

          def initialize: (
            id: String,
            ab_status: HubspotSDK::Models::Cms::Blogs::BlogPost::ab_status,
            ab_test_id: String,
            archived_at: Integer,
            archived_in_dashboard: bool,
            attached_stylesheets: ::Array[::Hash[Symbol, top]],
            author_name: String,
            blog_author_id: String,
            campaign: String,
            category_id: Integer,
            content_group_id: String,
            content_type_category: HubspotSDK::Models::Cms::Blogs::BlogPost::content_type_category,
            created: Time,
            created_by_id: String,
            currently_published: bool,
            current_state: HubspotSDK::Models::Cms::Blogs::BlogPost::current_state,
            domain: String,
            dynamic_page_data_source_id: String,
            dynamic_page_data_source_type: Integer,
            dynamic_page_hub_db_table_id: String,
            enable_domain_stylesheets: bool,
            enable_google_amp_output_override: bool,
            enable_layout_stylesheets: bool,
            featured_image: String,
            featured_image_alt_text: String,
            folder_id: String,
            footer_html: String,
            head_html: String,
            html_title: String,
            include_default_custom_css: bool,
            language: HubspotSDK::Models::Cms::Blogs::BlogPost::language,
            layout_sections: ::Hash[Symbol, HubspotSDK::Cms::LayoutSection],
            link_rel_canonical_url: String,
            mab_experiment_id: String,
            meta_description: String,
            name: String,
            page_expiry_date: Integer,
            page_expiry_enabled: bool,
            page_expiry_redirect_id: Integer,
            page_expiry_redirect_url: String,
            password: String,
            post_body: String,
            post_summary: String,
            public_access_rules: ::Array[top],
            public_access_rules_enabled: bool,
            publish_date: Time,
            publish_immediately: bool,
            rss_body: String,
            rss_summary: String,
            slug: String,
            state: String,
            tag_ids: ::Array[Integer],
            theme_settings_values: ::Hash[Symbol, top],
            translated_from_id: String,
            translations: ::Hash[Symbol, HubspotSDK::Cms::PagesContentLanguageVariation],
            updated: Time,
            updated_by_id: String,
            url: String,
            use_featured_image: bool,
            widget_containers: ::Hash[Symbol, top],
            widgets: ::Hash[Symbol, top]
          ) -> void

          def to_hash: -> {
            id: String,
            ab_status: HubspotSDK::Models::Cms::Blogs::BlogPost::ab_status,
            ab_test_id: String,
            archived_at: Integer,
            archived_in_dashboard: bool,
            attached_stylesheets: ::Array[::Hash[Symbol, top]],
            author_name: String,
            blog_author_id: String,
            campaign: String,
            category_id: Integer,
            content_group_id: String,
            content_type_category: HubspotSDK::Models::Cms::Blogs::BlogPost::content_type_category,
            created: Time,
            created_by_id: String,
            currently_published: bool,
            current_state: HubspotSDK::Models::Cms::Blogs::BlogPost::current_state,
            domain: String,
            dynamic_page_data_source_id: String,
            dynamic_page_data_source_type: Integer,
            dynamic_page_hub_db_table_id: String,
            enable_domain_stylesheets: bool,
            enable_google_amp_output_override: bool,
            enable_layout_stylesheets: bool,
            featured_image: String,
            featured_image_alt_text: String,
            folder_id: String,
            footer_html: String,
            head_html: String,
            html_title: String,
            include_default_custom_css: bool,
            language: HubspotSDK::Models::Cms::Blogs::BlogPost::language,
            layout_sections: ::Hash[Symbol, HubspotSDK::Cms::LayoutSection],
            link_rel_canonical_url: String,
            mab_experiment_id: String,
            meta_description: String,
            name: String,
            page_expiry_date: Integer,
            page_expiry_enabled: bool,
            page_expiry_redirect_id: Integer,
            page_expiry_redirect_url: String,
            password: String,
            post_body: String,
            post_summary: String,
            public_access_rules: ::Array[top],
            public_access_rules_enabled: bool,
            publish_date: Time,
            publish_immediately: bool,
            rss_body: String,
            rss_summary: String,
            slug: String,
            state: String,
            tag_ids: ::Array[Integer],
            theme_settings_values: ::Hash[Symbol, top],
            translated_from_id: String,
            translations: ::Hash[Symbol, HubspotSDK::Cms::PagesContentLanguageVariation],
            updated: Time,
            updated_by_id: String,
            url: String,
            use_featured_image: bool,
            widget_containers: ::Hash[Symbol, top],
            widgets: ::Hash[Symbol, top]
          }

          type ab_status =
            :master
            | :variant
            | :loser_variant
            | :mab_master
            | :mab_variant
            | :automated_master
            | :automated_variant
            | :automated_loser_variant

          module AbStatus
            extend HubspotSDK::Internal::Type::Enum

            MASTER: :master
            VARIANT: :variant
            LOSER_VARIANT: :loser_variant
            MAB_MASTER: :mab_master
            MAB_VARIANT: :mab_variant
            AUTOMATED_MASTER: :automated_master
            AUTOMATED_VARIANT: :automated_variant
            AUTOMATED_LOSER_VARIANT: :automated_loser_variant

            def self?.values: -> ::Array[HubspotSDK::Models::Cms::Blogs::BlogPost::ab_status]
          end

          type content_type_category =
            :"0"
            | :"1"
            | :"2"
            | :"3"
            | :"4"
            | :"5"
            | :"6"
            | :"7"
            | :"8"
            | :"9"
            | :"10"
            | :"11"
            | :"12"
            | :"13"
            | :"14"
            | :"15"

          module ContentTypeCategory
            extend HubspotSDK::Internal::Type::Enum

            CONTENT_TYPE_CATEGORY_0: :"0"
            CONTENT_TYPE_CATEGORY_1: :"1"
            CONTENT_TYPE_CATEGORY_2: :"2"
            CONTENT_TYPE_CATEGORY_3: :"3"
            CONTENT_TYPE_CATEGORY_4: :"4"
            CONTENT_TYPE_CATEGORY_5: :"5"
            CONTENT_TYPE_CATEGORY_6: :"6"
            CONTENT_TYPE_CATEGORY_7: :"7"
            CONTENT_TYPE_CATEGORY_8: :"8"
            CONTENT_TYPE_CATEGORY_9: :"9"
            CONTENT_TYPE_CATEGORY_10: :"10"
            CONTENT_TYPE_CATEGORY_11: :"11"
            CONTENT_TYPE_CATEGORY_12: :"12"
            CONTENT_TYPE_CATEGORY_13: :"13"
            CONTENT_TYPE_CATEGORY_14: :"14"
            CONTENT_TYPE_CATEGORY_15: :"15"

            def self?.values: -> ::Array[HubspotSDK::Models::Cms::Blogs::BlogPost::content_type_category]
          end

          type current_state =
            :AUTOMATED
            | :AUTOMATED_DRAFT
            | :AUTOMATED_SENDING
            | :AUTOMATED_FOR_FORM
            | :AUTOMATED_FOR_FORM_BUFFER
            | :AUTOMATED_FOR_FORM_DRAFT
            | :AUTOMATED_FOR_FORM_LEGACY
            | :BLOG_EMAIL_DRAFT
            | :BLOG_EMAIL_PUBLISHED
            | :DRAFT
            | :DRAFT_AB
            | :DRAFT_AB_VARIANT
            | :ERROR
            | :LOSER_AB_VARIANT
            | :PAGE_STUB
            | :PRE_PROCESSING
            | :PROCESSING
            | :PUBLISHED
            | :PUBLISHED_AB
            | :PUBLISHED_AB_VARIANT
            | :PUBLISHED_OR_SCHEDULED
            | :RSS_TO_EMAIL_DRAFT
            | :RSS_TO_EMAIL_PUBLISHED
            | :SCHEDULED
            | :SCHEDULED_AB
            | :SCHEDULED_OR_PUBLISHED
            | :AUTOMATED_AB
            | :AUTOMATED_AB_VARIANT
            | :AUTOMATED_DRAFT_AB
            | :AUTOMATED_DRAFT_ABVARIANT
            | :AUTOMATED_LOSER_ABVARIANT

          module CurrentState
            extend HubspotSDK::Internal::Type::Enum

            AUTOMATED: :AUTOMATED
            AUTOMATED_DRAFT: :AUTOMATED_DRAFT
            AUTOMATED_SENDING: :AUTOMATED_SENDING
            AUTOMATED_FOR_FORM: :AUTOMATED_FOR_FORM
            AUTOMATED_FOR_FORM_BUFFER: :AUTOMATED_FOR_FORM_BUFFER
            AUTOMATED_FOR_FORM_DRAFT: :AUTOMATED_FOR_FORM_DRAFT
            AUTOMATED_FOR_FORM_LEGACY: :AUTOMATED_FOR_FORM_LEGACY
            BLOG_EMAIL_DRAFT: :BLOG_EMAIL_DRAFT
            BLOG_EMAIL_PUBLISHED: :BLOG_EMAIL_PUBLISHED
            DRAFT: :DRAFT
            DRAFT_AB: :DRAFT_AB
            DRAFT_AB_VARIANT: :DRAFT_AB_VARIANT
            ERROR: :ERROR
            LOSER_AB_VARIANT: :LOSER_AB_VARIANT
            PAGE_STUB: :PAGE_STUB
            PRE_PROCESSING: :PRE_PROCESSING
            PROCESSING: :PROCESSING
            PUBLISHED: :PUBLISHED
            PUBLISHED_AB: :PUBLISHED_AB
            PUBLISHED_AB_VARIANT: :PUBLISHED_AB_VARIANT
            PUBLISHED_OR_SCHEDULED: :PUBLISHED_OR_SCHEDULED
            RSS_TO_EMAIL_DRAFT: :RSS_TO_EMAIL_DRAFT
            RSS_TO_EMAIL_PUBLISHED: :RSS_TO_EMAIL_PUBLISHED
            SCHEDULED: :SCHEDULED
            SCHEDULED_AB: :SCHEDULED_AB
            SCHEDULED_OR_PUBLISHED: :SCHEDULED_OR_PUBLISHED
            AUTOMATED_AB: :AUTOMATED_AB
            AUTOMATED_AB_VARIANT: :AUTOMATED_AB_VARIANT
            AUTOMATED_DRAFT_AB: :AUTOMATED_DRAFT_AB
            AUTOMATED_DRAFT_ABVARIANT: :AUTOMATED_DRAFT_ABVARIANT
            AUTOMATED_LOSER_ABVARIANT: :AUTOMATED_LOSER_ABVARIANT

            def self?.values: -> ::Array[HubspotSDK::Models::Cms::Blogs::BlogPost::current_state]
          end

          type language =
            :af
            | :"af-na"
            | :"af-za"
            | :agq
            | :"agq-cm"
            | :ak
            | :"ak-gh"
            | :am
            | :"am-et"
            | :ar
            | :"ar-001"
            | :"ar-ae"
            | :"ar-bh"
            | :"ar-dj"
            | :"ar-dz"
            | :"ar-eg"
            | :"ar-eh"
            | :"ar-er"
            | :"ar-il"
            | :"ar-iq"
            | :"ar-jo"
            | :"ar-km"
            | :"ar-kw"
            | :"ar-lb"
            | :"ar-ly"
            | :"ar-ma"
            | :"ar-mr"
            | :"ar-om"
            | :"ar-ps"
            | :"ar-qa"
            | :"ar-sa"
            | :"ar-sd"
            | :"ar-so"
            | :"ar-ss"
            | :"ar-sy"
            | :"ar-td"
            | :"ar-tn"
            | :"ar-ye"
            | :as
            | :"as-in"
            | :asa
            | :"asa-tz"
            | :ast
            | :"ast-es"
            | :az
            | :"az-az"
            | :bas
            | :"bas-cm"
            | :be
            | :"be-by"
            | :bem
            | :"bem-zm"
            | :bez
            | :"bez-tz"
            | :bg
            | :"bg-bg"
            | :bm
            | :"bm-ml"
            | :bn
            | :"bn-bd"
            | :"bn-in"
            | :bo
            | :"bo-cn"
            | :"bo-in"
            | :br
            | :"br-fr"
            | :brx
            | :"brx-in"
            | :bs
            | :"bs-ba"
            | :ca
            | :"ca-ad"
            | :"ca-es"
            | :"ca-fr"
            | :"ca-it"
            | :ccp
            | :"ccp-bd"
            | :"ccp-in"
            | :ce
            | :"ce-ru"
            | :ceb
            | :"ceb-ph"
            | :cgg
            | :"cgg-ug"
            | :chr
            | :"chr-us"
            | :ckb
            | :"ckb-iq"
            | :"ckb-ir"
            | :cs
            | :"cs-cz"
            | :cu
            | :"cu-ru"
            | :cy
            | :"cy-gb"
            | :da
            | :"da-dk"
            | :"da-gl"
            | :dav
            | :"dav-ke"
            | :de
            | :"de-at"
            | :"de-be"
            | :"de-ch"
            | :"de-de"
            | :"de-gr"
            | :"de-it"
            | :"de-li"
            | :"de-lu"
            | :dje
            | :"dje-ne"
            | :doi
            | :"doi-in"
            | :dsb
            | :"dsb-de"
            | :dua
            | :"dua-cm"
            | :dyo
            | :"dyo-sn"
            | :dz
            | :"dz-bt"
            | :ebu
            | :"ebu-ke"
            | :ee
            | :"ee-gh"
            | :"ee-tg"
            | :el
            | :"el-cy"
            | :"el-gr"
            | :en
            | :"en-001"
            | :"en-150"
            | :"en-ae"
            | :"en-ag"
            | :"en-ai"
            | :"en-as"
            | :"en-at"
            | :"en-au"
            | :"en-bb"
            | :"en-be"
            | :"en-bi"
            | :"en-bm"
            | :"en-bs"
            | :"en-bw"
            | :"en-bz"
            | :"en-ca"
            | :"en-cc"
            | :"en-ch"
            | :"en-ck"
            | :"en-cm"
            | :"en-cn"
            | :"en-cx"
            | :"en-cy"
            | :"en-de"
            | :"en-dg"
            | :"en-dk"
            | :"en-dm"
            | :"en-ee"
            | :"en-er"
            | :"en-fr"
            | :"en-fi"
            | :"en-fj"
            | :"en-fk"
            | :"en-fm"
            | :"en-gb"
            | :"en-gd"
            | :"en-gg"
            | :"en-gh"
            | :"en-gi"
            | :"en-gm"
            | :"en-gu"
            | :"en-gy"
            | :"en-hk"
            | :"en-ie"
            | :"en-il"
            | :"en-im"
            | :"en-in"
            | :"en-io"
            | :"en-je"
            | :"en-jm"
            | :"en-ke"
            | :"en-ki"
            | :"en-kn"
            | :"en-ky"
            | :"en-lc"
            | :"en-lr"
            | :"en-ls"
            | :"en-lu"
            | :"en-mg"
            | :"en-mh"
            | :"en-mo"
            | :"en-mp"
            | :"en-ms"
            | :"en-mt"
            | :"en-mu"
            | :"en-mw"
            | :"en-mx"
            | :"en-my"
            | :"en-na"
            | :"en-nf"
            | :"en-ng"
            | :"en-nl"
            | :"en-nr"
            | :"en-nu"
            | :"en-nz"
            | :"en-pg"
            | :"en-ph"
            | :"en-pk"
            | :"en-pn"
            | :"en-pr"
            | :"en-pw"
            | :"en-rw"
            | :"en-sb"
            | :"en-sc"
            | :"en-sd"
            | :"en-se"
            | :"en-sg"
            | :"en-sh"
            | :"en-si"
            | :"en-sl"
            | :"en-ss"
            | :"en-sx"
            | :"en-sz"
            | :"en-tc"
            | :"en-tk"
            | :"en-to"
            | :"en-tt"
            | :"en-tv"
            | :"en-tz"
            | :"en-ug"
            | :"en-um"
            | :"en-us"
            | :"en-vc"
            | :"en-vg"
            | :"en-vi"
            | :"en-vu"
            | :"en-ws"
            | :"en-za"
            | :"en-zm"
            | :"en-zw"
            | :eo
            | :"eo-001"
            | :es
            | :"es-419"
            | :"es-ar"
            | :"es-bo"
            | :"es-br"
            | :"es-bz"
            | :"es-cl"
            | :"es-co"
            | :"es-cr"
            | :"es-cu"
            | :"es-do"
            | :"es-ea"
            | :"es-ec"
            | :"es-es"
            | :"es-gq"
            | :"es-gt"
            | :"es-hn"
            | :"es-ic"
            | :"es-mx"
            | :"es-ni"
            | :"es-pa"
            | :"es-pe"
            | :"es-ph"
            | :"es-pr"
            | :"es-py"
            | :"es-sv"
            | :"es-us"
            | :"es-uy"
            | :"es-ve"
            | :et
            | :"et-ee"
            | :eu
            | :"eu-es"
            | :ewo
            | :"ewo-cm"
            | :fa
            | :"fa-af"
            | :"fa-ir"
            | :ff
            | :"ff-bf"
            | :"ff-cm"
            | :"ff-gh"
            | :"ff-gm"
            | :"ff-gn"
            | :"ff-gw"
            | :"ff-lr"
            | :"ff-mr"
            | :"ff-ne"
            | :"ff-ng"
            | :"ff-sl"
            | :"ff-sn"
            | :fi
            | :"fi-fi"
            | :fil
            | :"fil-ph"
            | :fo
            | :"fo-dk"
            | :"fo-fo"
            | :fr
            | :"fr-be"
            | :"fr-bf"
            | :"fr-bi"
            | :"fr-bj"
            | :"fr-bl"
            | :"fr-ca"
            | :"fr-cd"
            | :"fr-cf"
            | :"fr-cg"
            | :"fr-ch"
            | :"fr-ci"
            | :"fr-cm"
            | :"fr-dj"
            | :"fr-dz"
            | :"fr-fr"
            | :"fr-ga"
            | :"fr-gf"
            | :"fr-gn"
            | :"fr-gp"
            | :"fr-gq"
            | :"fr-ht"
            | :"fr-km"
            | :"fr-lu"
            | :"fr-ma"
            | :"fr-mc"
            | :"fr-mf"
            | :"fr-mg"
            | :"fr-ml"
            | :"fr-mq"
            | :"fr-mr"
            | :"fr-mu"
            | :"fr-nc"
            | :"fr-ne"
            | :"fr-pf"
            | :"fr-pm"
            | :"fr-re"
            | :"fr-rw"
            | :"fr-sc"
            | :"fr-sn"
            | :"fr-sy"
            | :"fr-td"
            | :"fr-tg"
            | :"fr-tn"
            | :"fr-vu"
            | :"fr-wf"
            | :"fr-yt"
            | :fur
            | :"fur-it"
            | :fy
            | :"fy-nl"
            | :ga
            | :"ga-gb"
            | :"ga-ie"
            | :gd
            | :"gd-gb"
            | :gl
            | :"gl-es"
            | :gsw
            | :"gsw-ch"
            | :"gsw-fr"
            | :"gsw-li"
            | :gu
            | :"gu-in"
            | :guz
            | :"guz-ke"
            | :gv
            | :"gv-im"
            | :ha
            | :"ha-gh"
            | :"ha-ne"
            | :"ha-ng"
            | :haw
            | :"haw-us"
            | :he
            | :hi
            | :"hi-in"
            | :hr
            | :"hr-ba"
            | :"hr-hr"
            | :hsb
            | :"hsb-de"
            | :hu
            | :"hu-hu"
            | :hy
            | :"hy-am"
            | :ia
            | :"ia-001"
            | :id
            | :ig
            | :"ig-ng"
            | :ii
            | :"ii-cn"
            | :"id-id"
            | :is
            | :"is-is"
            | :it
            | :"it-ch"
            | :"it-it"
            | :"it-sm"
            | :"it-va"
            | :"he-il"
            | :ja
            | :"ja-jp"
            | :jgo
            | :"jgo-cm"
            | :yi
            | :"yi-001"
            | :jmc
            | :"jmc-tz"
            | :jv
            | :"jv-id"
            | :ka
            | :"ka-ge"
            | :kab
            | :"kab-dz"
            | :kam
            | :"kam-ke"
            | :kde
            | :"kde-tz"
            | :kea
            | :"kea-cv"
            | :khq
            | :"khq-ml"
            | :ki
            | :"ki-ke"
            | :kk
            | :"kk-kz"
            | :kkj
            | :"kkj-cm"
            | :kl
            | :"kl-gl"
            | :kln
            | :"kln-ke"
            | :km
            | :"km-kh"
            | :kn
            | :"kn-in"
            | :ko
            | :"ko-kp"
            | :"ko-kr"
            | :kok
            | :"kok-in"
            | :ks
            | :"ks-in"
            | :ksb
            | :"ksb-tz"
            | :ksf
            | :"ksf-cm"
            | :ksh
            | :"ksh-de"
            | :kw
            | :"kw-gb"
            | :ku
            | :"ku-tr"
            | :ky
            | :"ky-kg"
            | :lag
            | :"lag-tz"
            | :lb
            | :"lb-lu"
            | :lg
            | :"lg-ug"
            | :lkt
            | :"lkt-us"
            | :ln
            | :"ln-ao"
            | :"ln-cd"
            | :"ln-cf"
            | :"ln-cg"
            | :lo
            | :"lo-la"
            | :lrc
            | :"lrc-iq"
            | :"lrc-ir"
            | :lt
            | :"lt-lt"
            | :lu
            | :"lu-cd"
            | :luo
            | :"luo-ke"
            | :luy
            | :"luy-ke"
            | :lv
            | :"lv-lv"
            | :mai
            | :"mai-in"
            | :mas
            | :"mas-ke"
            | :"mas-tz"
            | :mer
            | :"mer-ke"
            | :mfe
            | :"mfe-mu"
            | :mg
            | :"mg-mg"
            | :mgh
            | :"mgh-mz"
            | :mgo
            | :"mgo-cm"
            | :mi
            | :"mi-nz"
            | :mk
            | :"mk-mk"
            | :ml
            | :"ml-in"
            | :mn
            | :"mn-mn"
            | :mni
            | :"mni-in"
            | :mr
            | :"mr-in"
            | :ms
            | :"ms-bn"
            | :"ms-id"
            | :"ms-my"
            | :"ms-sg"
            | :mt
            | :"mt-mt"
            | :mua
            | :"mua-cm"
            | :my
            | :"my-mm"
            | :mzn
            | :"mzn-ir"
            | :naq
            | :"naq-na"
            | :nb
            | :"nb-no"
            | :"nb-sj"
            | :nd
            | :"nd-zw"
            | :nds
            | :"nds-de"
            | :"nds-nl"
            | :ne
            | :"ne-in"
            | :"ne-np"
            | :nl
            | :"nl-aw"
            | :"nl-be"
            | :"nl-ch"
            | :"nl-bq"
            | :"nl-cw"
            | :"nl-lu"
            | :"nl-nl"
            | :"nl-sr"
            | :"nl-sx"
            | :nmg
            | :"nmg-cm"
            | :nn
            | :"nn-no"
            | :nnh
            | :"nnh-cm"
            | :no
            | :"no-no"
            | :nus
            | :"nus-ss"
            | :nyn
            | :"nyn-ug"
            | :om
            | :"om-et"
            | :"om-ke"
            | :or
            | :"or-in"
            | :os
            | :"os-ge"
            | :"os-ru"
            | :pa
            | :"pa-in"
            | :"pa-pk"
            | :pcm
            | :"pcm-ng"
            | :pl
            | :"pl-pl"
            | :prg
            | :"prg-001"
            | :ps
            | :"ps-af"
            | :"ps-pk"
            | :pt
            | :"pt-ao"
            | :"pt-br"
            | :"pt-ch"
            | :"pt-cv"
            | :"pt-gq"
            | :"pt-gw"
            | :"pt-lu"
            | :"pt-mo"
            | :"pt-mz"
            | :"pt-pt"
            | :"pt-st"
            | :"pt-tl"
            | :qu
            | :"qu-bo"
            | :"qu-ec"
            | :"qu-pe"
            | :rm
            | :"rm-ch"
            | :rn
            | :"rn-bi"
            | :ro
            | :"ro-md"
            | :"ro-ro"
            | :rof
            | :"rof-tz"
            | :ru
            | :"ru-by"
            | :"ru-kg"
            | :"ru-kz"
            | :"ru-md"
            | :"ru-ru"
            | :"ru-ua"
            | :rw
            | :"rw-rw"
            | :rwk
            | :"rwk-tz"
            | :sa
            | :"sa-in"
            | :sah
            | :"sah-ru"
            | :saq
            | :"saq-ke"
            | :sat
            | :"sat-in"
            | :sbp
            | :"sbp-tz"
            | :sd
            | :"sd-in"
            | :"sd-pk"
            | :se
            | :"se-fi"
            | :"se-no"
            | :"se-se"
            | :seh
            | :"seh-mz"
            | :ses
            | :"ses-ml"
            | :sg
            | :"sg-cf"
            | :shi
            | :"shi-ma"
            | :si
            | :"si-lk"
            | :sk
            | :"sk-sk"
            | :sl
            | :"sl-si"
            | :smn
            | :"smn-fi"
            | :sn
            | :"sn-zw"
            | :so
            | :"so-dj"
            | :"so-et"
            | :"so-ke"
            | :"so-so"
            | :sq
            | :"sq-al"
            | :"sq-mk"
            | :"sq-xk"
            | :sr
            | :"sr-ba"
            | :"sr-cs"
            | :"sr-me"
            | :"sr-rs"
            | :"sr-xk"
            | :su
            | :"su-id"
            | :sv
            | :"sv-ax"
            | :"sv-fi"
            | :"sv-se"
            | :sw
            | :"sw-cd"
            | :"sw-ke"
            | :"sw-tz"
            | :"sw-ug"
            | :sy
            | :ta
            | :"ta-in"
            | :"ta-lk"
            | :"ta-my"
            | :"ta-sg"
            | :te
            | :"te-in"
            | :teo
            | :"teo-ke"
            | :"teo-ug"
            | :tg
            | :"tg-tj"
            | :th
            | :"th-th"
            | :ti
            | :"ti-er"
            | :"ti-et"
            | :tk
            | :"tk-tm"
            | :tl
            | :to
            | :"to-to"
            | :tr
            | :"tr-cy"
            | :"tr-tr"
            | :tt
            | :"tt-ru"
            | :twq
            | :"twq-ne"
            | :tzm
            | :"tzm-ma"
            | :ug
            | :"ug-cn"
            | :uk
            | :"uk-ua"
            | :ur
            | :"ur-in"
            | :"ur-pk"
            | :uz
            | :"uz-af"
            | :"uz-uz"
            | :vai
            | :"vai-lr"
            | :vi
            | :"vi-vn"
            | :vo
            | :"vo-001"
            | :vun
            | :"vun-tz"
            | :wae
            | :"wae-ch"
            | :wo
            | :"wo-sn"
            | :xh
            | :"xh-za"
            | :xog
            | :"xog-ug"
            | :yav
            | :"yav-cm"
            | :yo
            | :"yo-bj"
            | :"yo-ng"
            | :yue
            | :"yue-cn"
            | :"yue-hk"
            | :zgh
            | :"zgh-ma"
            | :zh
            | :"zh-cn"
            | :"zh-hk"
            | :"zh-mo"
            | :"zh-sg"
            | :"zh-tw"
            | :"zh-hans"
            | :"zh-hant"
            | :zu
            | :"zu-za"

          module Language
            extend HubspotSDK::Internal::Type::Enum

            AF: :af
            AF_NA: :"af-na"
            AF_ZA: :"af-za"
            AGQ: :agq
            AGQ_CM: :"agq-cm"
            AK: :ak
            AK_GH: :"ak-gh"
            AM: :am
            AM_ET: :"am-et"
            AR: :ar
            AR_001: :"ar-001"
            AR_AE: :"ar-ae"
            AR_BH: :"ar-bh"
            AR_DJ: :"ar-dj"
            AR_DZ: :"ar-dz"
            AR_EG: :"ar-eg"
            AR_EH: :"ar-eh"
            AR_ER: :"ar-er"
            AR_IL: :"ar-il"
            AR_IQ: :"ar-iq"
            AR_JO: :"ar-jo"
            AR_KM: :"ar-km"
            AR_KW: :"ar-kw"
            AR_LB: :"ar-lb"
            AR_LY: :"ar-ly"
            AR_MA: :"ar-ma"
            AR_MR: :"ar-mr"
            AR_OM: :"ar-om"
            AR_PS: :"ar-ps"
            AR_QA: :"ar-qa"
            AR_SA: :"ar-sa"
            AR_SD: :"ar-sd"
            AR_SO: :"ar-so"
            AR_SS: :"ar-ss"
            AR_SY: :"ar-sy"
            AR_TD: :"ar-td"
            AR_TN: :"ar-tn"
            AR_YE: :"ar-ye"
            AS: :as
            AS_IN: :"as-in"
            ASA: :asa
            ASA_TZ: :"asa-tz"
            AST: :ast
            AST_ES: :"ast-es"
            AZ: :az
            AZ_AZ: :"az-az"
            BAS: :bas
            BAS_CM: :"bas-cm"
            BE: :be
            BE_BY: :"be-by"
            BEM: :bem
            BEM_ZM: :"bem-zm"
            BEZ: :bez
            BEZ_TZ: :"bez-tz"
            BG: :bg
            BG_BG: :"bg-bg"
            BM: :bm
            BM_ML: :"bm-ml"
            BN: :bn
            BN_BD: :"bn-bd"
            BN_IN: :"bn-in"
            BO: :bo
            BO_CN: :"bo-cn"
            BO_IN: :"bo-in"
            BR: :br
            BR_FR: :"br-fr"
            BRX: :brx
            BRX_IN: :"brx-in"
            BS: :bs
            BS_BA: :"bs-ba"
            CA: :ca
            CA_AD: :"ca-ad"
            CA_ES: :"ca-es"
            CA_FR: :"ca-fr"
            CA_IT: :"ca-it"
            CCP: :ccp
            CCP_BD: :"ccp-bd"
            CCP_IN: :"ccp-in"
            CE: :ce
            CE_RU: :"ce-ru"
            CEB: :ceb
            CEB_PH: :"ceb-ph"
            CGG: :cgg
            CGG_UG: :"cgg-ug"
            CHR: :chr
            CHR_US: :"chr-us"
            CKB: :ckb
            CKB_IQ: :"ckb-iq"
            CKB_IR: :"ckb-ir"
            CS: :cs
            CS_CZ: :"cs-cz"
            CU: :cu
            CU_RU: :"cu-ru"
            CY: :cy
            CY_GB: :"cy-gb"
            DA: :da
            DA_DK: :"da-dk"
            DA_GL: :"da-gl"
            DAV: :dav
            DAV_KE: :"dav-ke"
            DE: :de
            DE_AT: :"de-at"
            DE_BE: :"de-be"
            DE_CH: :"de-ch"
            DE_DE: :"de-de"
            DE_GR: :"de-gr"
            DE_IT: :"de-it"
            DE_LI: :"de-li"
            DE_LU: :"de-lu"
            DJE: :dje
            DJE_NE: :"dje-ne"
            DOI: :doi
            DOI_IN: :"doi-in"
            DSB: :dsb
            DSB_DE: :"dsb-de"
            DUA: :dua
            DUA_CM: :"dua-cm"
            DYO: :dyo
            DYO_SN: :"dyo-sn"
            DZ: :dz
            DZ_BT: :"dz-bt"
            EBU: :ebu
            EBU_KE: :"ebu-ke"
            EE: :ee
            EE_GH: :"ee-gh"
            EE_TG: :"ee-tg"
            EL: :el
            EL_CY: :"el-cy"
            EL_GR: :"el-gr"
            EN: :en
            EN_001: :"en-001"
            EN_150: :"en-150"
            EN_AE: :"en-ae"
            EN_AG: :"en-ag"
            EN_AI: :"en-ai"
            EN_AS: :"en-as"
            EN_AT: :"en-at"
            EN_AU: :"en-au"
            EN_BB: :"en-bb"
            EN_BE: :"en-be"
            EN_BI: :"en-bi"
            EN_BM: :"en-bm"
            EN_BS: :"en-bs"
            EN_BW: :"en-bw"
            EN_BZ: :"en-bz"
            EN_CA: :"en-ca"
            EN_CC: :"en-cc"
            EN_CH: :"en-ch"
            EN_CK: :"en-ck"
            EN_CM: :"en-cm"
            EN_CN: :"en-cn"
            EN_CX: :"en-cx"
            EN_CY: :"en-cy"
            EN_DE: :"en-de"
            EN_DG: :"en-dg"
            EN_DK: :"en-dk"
            EN_DM: :"en-dm"
            EN_EE: :"en-ee"
            EN_ER: :"en-er"
            EN_FR: :"en-fr"
            EN_FI: :"en-fi"
            EN_FJ: :"en-fj"
            EN_FK: :"en-fk"
            EN_FM: :"en-fm"
            EN_GB: :"en-gb"
            EN_GD: :"en-gd"
            EN_GG: :"en-gg"
            EN_GH: :"en-gh"
            EN_GI: :"en-gi"
            EN_GM: :"en-gm"
            EN_GU: :"en-gu"
            EN_GY: :"en-gy"
            EN_HK: :"en-hk"
            EN_IE: :"en-ie"
            EN_IL: :"en-il"
            EN_IM: :"en-im"
            EN_IN: :"en-in"
            EN_IO: :"en-io"
            EN_JE: :"en-je"
            EN_JM: :"en-jm"
            EN_KE: :"en-ke"
            EN_KI: :"en-ki"
            EN_KN: :"en-kn"
            EN_KY: :"en-ky"
            EN_LC: :"en-lc"
            EN_LR: :"en-lr"
            EN_LS: :"en-ls"
            EN_LU: :"en-lu"
            EN_MG: :"en-mg"
            EN_MH: :"en-mh"
            EN_MO: :"en-mo"
            EN_MP: :"en-mp"
            EN_MS: :"en-ms"
            EN_MT: :"en-mt"
            EN_MU: :"en-mu"
            EN_MW: :"en-mw"
            EN_MX: :"en-mx"
            EN_MY: :"en-my"
            EN_NA: :"en-na"
            EN_NF: :"en-nf"
            EN_NG: :"en-ng"
            EN_NL: :"en-nl"
            EN_NR: :"en-nr"
            EN_NU: :"en-nu"
            EN_NZ: :"en-nz"
            EN_PG: :"en-pg"
            EN_PH: :"en-ph"
            EN_PK: :"en-pk"
            EN_PN: :"en-pn"
            EN_PR: :"en-pr"
            EN_PW: :"en-pw"
            EN_RW: :"en-rw"
            EN_SB: :"en-sb"
            EN_SC: :"en-sc"
            EN_SD: :"en-sd"
            EN_SE: :"en-se"
            EN_SG: :"en-sg"
            EN_SH: :"en-sh"
            EN_SI: :"en-si"
            EN_SL: :"en-sl"
            EN_SS: :"en-ss"
            EN_SX: :"en-sx"
            EN_SZ: :"en-sz"
            EN_TC: :"en-tc"
            EN_TK: :"en-tk"
            EN_TO: :"en-to"
            EN_TT: :"en-tt"
            EN_TV: :"en-tv"
            EN_TZ: :"en-tz"
            EN_UG: :"en-ug"
            EN_UM: :"en-um"
            EN_US: :"en-us"
            EN_VC: :"en-vc"
            EN_VG: :"en-vg"
            EN_VI: :"en-vi"
            EN_VU: :"en-vu"
            EN_WS: :"en-ws"
            EN_ZA: :"en-za"
            EN_ZM: :"en-zm"
            EN_ZW: :"en-zw"
            EO: :eo
            EO_001: :"eo-001"
            ES: :es
            ES_419: :"es-419"
            ES_AR: :"es-ar"
            ES_BO: :"es-bo"
            ES_BR: :"es-br"
            ES_BZ: :"es-bz"
            ES_CL: :"es-cl"
            ES_CO: :"es-co"
            ES_CR: :"es-cr"
            ES_CU: :"es-cu"
            ES_DO: :"es-do"
            ES_EA: :"es-ea"
            ES_EC: :"es-ec"
            ES_ES: :"es-es"
            ES_GQ: :"es-gq"
            ES_GT: :"es-gt"
            ES_HN: :"es-hn"
            ES_IC: :"es-ic"
            ES_MX: :"es-mx"
            ES_NI: :"es-ni"
            ES_PA: :"es-pa"
            ES_PE: :"es-pe"
            ES_PH: :"es-ph"
            ES_PR: :"es-pr"
            ES_PY: :"es-py"
            ES_SV: :"es-sv"
            ES_US: :"es-us"
            ES_UY: :"es-uy"
            ES_VE: :"es-ve"
            ET: :et
            ET_EE: :"et-ee"
            EU: :eu
            EU_ES: :"eu-es"
            EWO: :ewo
            EWO_CM: :"ewo-cm"
            FA: :fa
            FA_AF: :"fa-af"
            FA_IR: :"fa-ir"
            FF: :ff
            FF_BF: :"ff-bf"
            FF_CM: :"ff-cm"
            FF_GH: :"ff-gh"
            FF_GM: :"ff-gm"
            FF_GN: :"ff-gn"
            FF_GW: :"ff-gw"
            FF_LR: :"ff-lr"
            FF_MR: :"ff-mr"
            FF_NE: :"ff-ne"
            FF_NG: :"ff-ng"
            FF_SL: :"ff-sl"
            FF_SN: :"ff-sn"
            FI: :fi
            FI_FI: :"fi-fi"
            FIL: :fil
            FIL_PH: :"fil-ph"
            FO: :fo
            FO_DK: :"fo-dk"
            FO_FO: :"fo-fo"
            FR: :fr
            FR_BE: :"fr-be"
            FR_BF: :"fr-bf"
            FR_BI: :"fr-bi"
            FR_BJ: :"fr-bj"
            FR_BL: :"fr-bl"
            FR_CA: :"fr-ca"
            FR_CD: :"fr-cd"
            FR_CF: :"fr-cf"
            FR_CG: :"fr-cg"
            FR_CH: :"fr-ch"
            FR_CI: :"fr-ci"
            FR_CM: :"fr-cm"
            FR_DJ: :"fr-dj"
            FR_DZ: :"fr-dz"
            FR_FR: :"fr-fr"
            FR_GA: :"fr-ga"
            FR_GF: :"fr-gf"
            FR_GN: :"fr-gn"
            FR_GP: :"fr-gp"
            FR_GQ: :"fr-gq"
            FR_HT: :"fr-ht"
            FR_KM: :"fr-km"
            FR_LU: :"fr-lu"
            FR_MA: :"fr-ma"
            FR_MC: :"fr-mc"
            FR_MF: :"fr-mf"
            FR_MG: :"fr-mg"
            FR_ML: :"fr-ml"
            FR_MQ: :"fr-mq"
            FR_MR: :"fr-mr"
            FR_MU: :"fr-mu"
            FR_NC: :"fr-nc"
            FR_NE: :"fr-ne"
            FR_PF: :"fr-pf"
            FR_PM: :"fr-pm"
            FR_RE: :"fr-re"
            FR_RW: :"fr-rw"
            FR_SC: :"fr-sc"
            FR_SN: :"fr-sn"
            FR_SY: :"fr-sy"
            FR_TD: :"fr-td"
            FR_TG: :"fr-tg"
            FR_TN: :"fr-tn"
            FR_VU: :"fr-vu"
            FR_WF: :"fr-wf"
            FR_YT: :"fr-yt"
            FUR: :fur
            FUR_IT: :"fur-it"
            FY: :fy
            FY_NL: :"fy-nl"
            GA: :ga
            GA_GB: :"ga-gb"
            GA_IE: :"ga-ie"
            GD: :gd
            GD_GB: :"gd-gb"
            GL: :gl
            GL_ES: :"gl-es"
            GSW: :gsw
            GSW_CH: :"gsw-ch"
            GSW_FR: :"gsw-fr"
            GSW_LI: :"gsw-li"
            GU: :gu
            GU_IN: :"gu-in"
            GUZ: :guz
            GUZ_KE: :"guz-ke"
            GV: :gv
            GV_IM: :"gv-im"
            HA: :ha
            HA_GH: :"ha-gh"
            HA_NE: :"ha-ne"
            HA_NG: :"ha-ng"
            HAW: :haw
            HAW_US: :"haw-us"
            HE: :he
            HI: :hi
            HI_IN: :"hi-in"
            HR: :hr
            HR_BA: :"hr-ba"
            HR_HR: :"hr-hr"
            HSB: :hsb
            HSB_DE: :"hsb-de"
            HU: :hu
            HU_HU: :"hu-hu"
            HY: :hy
            HY_AM: :"hy-am"
            IA: :ia
            IA_001: :"ia-001"
            ID: :id
            IG: :ig
            IG_NG: :"ig-ng"
            II: :ii
            II_CN: :"ii-cn"
            ID_ID: :"id-id"
            IS: :is
            IS_IS: :"is-is"
            IT: :it
            IT_CH: :"it-ch"
            IT_IT: :"it-it"
            IT_SM: :"it-sm"
            IT_VA: :"it-va"
            HE_IL: :"he-il"
            JA: :ja
            JA_JP: :"ja-jp"
            JGO: :jgo
            JGO_CM: :"jgo-cm"
            YI: :yi
            YI_001: :"yi-001"
            JMC: :jmc
            JMC_TZ: :"jmc-tz"
            JV: :jv
            JV_ID: :"jv-id"
            KA: :ka
            KA_GE: :"ka-ge"
            KAB: :kab
            KAB_DZ: :"kab-dz"
            KAM: :kam
            KAM_KE: :"kam-ke"
            KDE: :kde
            KDE_TZ: :"kde-tz"
            KEA: :kea
            KEA_CV: :"kea-cv"
            KHQ: :khq
            KHQ_ML: :"khq-ml"
            KI: :ki
            KI_KE: :"ki-ke"
            KK: :kk
            KK_KZ: :"kk-kz"
            KKJ: :kkj
            KKJ_CM: :"kkj-cm"
            KL: :kl
            KL_GL: :"kl-gl"
            KLN: :kln
            KLN_KE: :"kln-ke"
            KM: :km
            KM_KH: :"km-kh"
            KN: :kn
            KN_IN: :"kn-in"
            KO: :ko
            KO_KP: :"ko-kp"
            KO_KR: :"ko-kr"
            KOK: :kok
            KOK_IN: :"kok-in"
            KS: :ks
            KS_IN: :"ks-in"
            KSB: :ksb
            KSB_TZ: :"ksb-tz"
            KSF: :ksf
            KSF_CM: :"ksf-cm"
            KSH: :ksh
            KSH_DE: :"ksh-de"
            KW: :kw
            KW_GB: :"kw-gb"
            KU: :ku
            KU_TR: :"ku-tr"
            KY: :ky
            KY_KG: :"ky-kg"
            LAG: :lag
            LAG_TZ: :"lag-tz"
            LB: :lb
            LB_LU: :"lb-lu"
            LG: :lg
            LG_UG: :"lg-ug"
            LKT: :lkt
            LKT_US: :"lkt-us"
            LN: :ln
            LN_AO: :"ln-ao"
            LN_CD: :"ln-cd"
            LN_CF: :"ln-cf"
            LN_CG: :"ln-cg"
            LO: :lo
            LO_LA: :"lo-la"
            LRC: :lrc
            LRC_IQ: :"lrc-iq"
            LRC_IR: :"lrc-ir"
            LT: :lt
            LT_LT: :"lt-lt"
            LU: :lu
            LU_CD: :"lu-cd"
            LUO: :luo
            LUO_KE: :"luo-ke"
            LUY: :luy
            LUY_KE: :"luy-ke"
            LV: :lv
            LV_LV: :"lv-lv"
            MAI: :mai
            MAI_IN: :"mai-in"
            MAS: :mas
            MAS_KE: :"mas-ke"
            MAS_TZ: :"mas-tz"
            MER: :mer
            MER_KE: :"mer-ke"
            MFE: :mfe
            MFE_MU: :"mfe-mu"
            MG: :mg
            MG_MG: :"mg-mg"
            MGH: :mgh
            MGH_MZ: :"mgh-mz"
            MGO: :mgo
            MGO_CM: :"mgo-cm"
            MI: :mi
            MI_NZ: :"mi-nz"
            MK: :mk
            MK_MK: :"mk-mk"
            ML: :ml
            ML_IN: :"ml-in"
            MN: :mn
            MN_MN: :"mn-mn"
            MNI: :mni
            MNI_IN: :"mni-in"
            MR: :mr
            MR_IN: :"mr-in"
            MS: :ms
            MS_BN: :"ms-bn"
            MS_ID: :"ms-id"
            MS_MY: :"ms-my"
            MS_SG: :"ms-sg"
            MT: :mt
            MT_MT: :"mt-mt"
            MUA: :mua
            MUA_CM: :"mua-cm"
            MY: :my
            MY_MM: :"my-mm"
            MZN: :mzn
            MZN_IR: :"mzn-ir"
            NAQ: :naq
            NAQ_NA: :"naq-na"
            NB: :nb
            NB_NO: :"nb-no"
            NB_SJ: :"nb-sj"
            ND: :nd
            ND_ZW: :"nd-zw"
            NDS: :nds
            NDS_DE: :"nds-de"
            NDS_NL: :"nds-nl"
            NE: :ne
            NE_IN: :"ne-in"
            NE_NP: :"ne-np"
            NL: :nl
            NL_AW: :"nl-aw"
            NL_BE: :"nl-be"
            NL_CH: :"nl-ch"
            NL_BQ: :"nl-bq"
            NL_CW: :"nl-cw"
            NL_LU: :"nl-lu"
            NL_NL: :"nl-nl"
            NL_SR: :"nl-sr"
            NL_SX: :"nl-sx"
            NMG: :nmg
            NMG_CM: :"nmg-cm"
            NN: :nn
            NN_NO: :"nn-no"
            NNH: :nnh
            NNH_CM: :"nnh-cm"
            NO: :no
            NO_NO: :"no-no"
            NUS: :nus
            NUS_SS: :"nus-ss"
            NYN: :nyn
            NYN_UG: :"nyn-ug"
            OM: :om
            OM_ET: :"om-et"
            OM_KE: :"om-ke"
            OR: :or
            OR_IN: :"or-in"
            OS: :os
            OS_GE: :"os-ge"
            OS_RU: :"os-ru"
            PA: :pa
            PA_IN: :"pa-in"
            PA_PK: :"pa-pk"
            PCM: :pcm
            PCM_NG: :"pcm-ng"
            PL: :pl
            PL_PL: :"pl-pl"
            PRG: :prg
            PRG_001: :"prg-001"
            PS: :ps
            PS_AF: :"ps-af"
            PS_PK: :"ps-pk"
            PT: :pt
            PT_AO: :"pt-ao"
            PT_BR: :"pt-br"
            PT_CH: :"pt-ch"
            PT_CV: :"pt-cv"
            PT_GQ: :"pt-gq"
            PT_GW: :"pt-gw"
            PT_LU: :"pt-lu"
            PT_MO: :"pt-mo"
            PT_MZ: :"pt-mz"
            PT_PT: :"pt-pt"
            PT_ST: :"pt-st"
            PT_TL: :"pt-tl"
            QU: :qu
            QU_BO: :"qu-bo"
            QU_EC: :"qu-ec"
            QU_PE: :"qu-pe"
            RM: :rm
            RM_CH: :"rm-ch"
            RN: :rn
            RN_BI: :"rn-bi"
            RO: :ro
            RO_MD: :"ro-md"
            RO_RO: :"ro-ro"
            ROF: :rof
            ROF_TZ: :"rof-tz"
            RU: :ru
            RU_BY: :"ru-by"
            RU_KG: :"ru-kg"
            RU_KZ: :"ru-kz"
            RU_MD: :"ru-md"
            RU_RU: :"ru-ru"
            RU_UA: :"ru-ua"
            RW: :rw
            RW_RW: :"rw-rw"
            RWK: :rwk
            RWK_TZ: :"rwk-tz"
            SA: :sa
            SA_IN: :"sa-in"
            SAH: :sah
            SAH_RU: :"sah-ru"
            SAQ: :saq
            SAQ_KE: :"saq-ke"
            SAT: :sat
            SAT_IN: :"sat-in"
            SBP: :sbp
            SBP_TZ: :"sbp-tz"
            SD: :sd
            SD_IN: :"sd-in"
            SD_PK: :"sd-pk"
            SE: :se
            SE_FI: :"se-fi"
            SE_NO: :"se-no"
            SE_SE: :"se-se"
            SEH: :seh
            SEH_MZ: :"seh-mz"
            SES: :ses
            SES_ML: :"ses-ml"
            SG: :sg
            SG_CF: :"sg-cf"
            SHI: :shi
            SHI_MA: :"shi-ma"
            SI: :si
            SI_LK: :"si-lk"
            SK: :sk
            SK_SK: :"sk-sk"
            SL: :sl
            SL_SI: :"sl-si"
            SMN: :smn
            SMN_FI: :"smn-fi"
            SN: :sn
            SN_ZW: :"sn-zw"
            SO: :so
            SO_DJ: :"so-dj"
            SO_ET: :"so-et"
            SO_KE: :"so-ke"
            SO_SO: :"so-so"
            SQ: :sq
            SQ_AL: :"sq-al"
            SQ_MK: :"sq-mk"
            SQ_XK: :"sq-xk"
            SR: :sr
            SR_BA: :"sr-ba"
            SR_CS: :"sr-cs"
            SR_ME: :"sr-me"
            SR_RS: :"sr-rs"
            SR_XK: :"sr-xk"
            SU: :su
            SU_ID: :"su-id"
            SV: :sv
            SV_AX: :"sv-ax"
            SV_FI: :"sv-fi"
            SV_SE: :"sv-se"
            SW: :sw
            SW_CD: :"sw-cd"
            SW_KE: :"sw-ke"
            SW_TZ: :"sw-tz"
            SW_UG: :"sw-ug"
            SY: :sy
            TA: :ta
            TA_IN: :"ta-in"
            TA_LK: :"ta-lk"
            TA_MY: :"ta-my"
            TA_SG: :"ta-sg"
            TE: :te
            TE_IN: :"te-in"
            TEO: :teo
            TEO_KE: :"teo-ke"
            TEO_UG: :"teo-ug"
            TG: :tg
            TG_TJ: :"tg-tj"
            TH: :th
            TH_TH: :"th-th"
            TI: :ti
            TI_ER: :"ti-er"
            TI_ET: :"ti-et"
            TK: :tk
            TK_TM: :"tk-tm"
            TL: :tl
            TO: :to
            TO_TO: :"to-to"
            TR: :tr
            TR_CY: :"tr-cy"
            TR_TR: :"tr-tr"
            TT: :tt
            TT_RU: :"tt-ru"
            TWQ: :twq
            TWQ_NE: :"twq-ne"
            TZM: :tzm
            TZM_MA: :"tzm-ma"
            UG: :ug
            UG_CN: :"ug-cn"
            UK: :uk
            UK_UA: :"uk-ua"
            UR: :ur
            UR_IN: :"ur-in"
            UR_PK: :"ur-pk"
            UZ: :uz
            UZ_AF: :"uz-af"
            UZ_UZ: :"uz-uz"
            VAI: :vai
            VAI_LR: :"vai-lr"
            VI: :vi
            VI_VN: :"vi-vn"
            VO: :vo
            VO_001: :"vo-001"
            VUN: :vun
            VUN_TZ: :"vun-tz"
            WAE: :wae
            WAE_CH: :"wae-ch"
            WO: :wo
            WO_SN: :"wo-sn"
            XH: :xh
            XH_ZA: :"xh-za"
            XOG: :xog
            XOG_UG: :"xog-ug"
            YAV: :yav
            YAV_CM: :"yav-cm"
            YO: :yo
            YO_BJ: :"yo-bj"
            YO_NG: :"yo-ng"
            YUE: :yue
            YUE_CN: :"yue-cn"
            YUE_HK: :"yue-hk"
            ZGH: :zgh
            ZGH_MA: :"zgh-ma"
            ZH: :zh
            ZH_CN: :"zh-cn"
            ZH_HK: :"zh-hk"
            ZH_MO: :"zh-mo"
            ZH_SG: :"zh-sg"
            ZH_TW: :"zh-tw"
            ZH_HANS: :"zh-hans"
            ZH_HANT: :"zh-hant"
            ZU: :zu
            ZU_ZA: :"zu-za"

            def self?.values: -> ::Array[HubspotSDK::Models::Cms::Blogs::BlogPost::language]
          end
        end
      end
    end
  end
end
