module HubspotSDK
  module Models
    module Cms
      module Blogs
        type breakpoint_styles = { hidden: bool, margin: top, padding: top }

        class BreakpointStyles < HubspotSDK::Internal::Type::BaseModel
          attr_accessor hidden: bool

          attr_accessor margin: top

          attr_accessor padding: top

          def initialize: (hidden: bool, margin: top, padding: top) -> void

          def to_hash: -> { hidden: bool, margin: top, padding: top }
        end
      end
    end
  end
end
