module HubSpotSDK
  module Models
    module Cms
      module Blogs
        type collection_response_with_total_blog_author_forward_paging =
          {
            results: ::Array[HubSpotSDK::Cms::Blogs::BlogAuthor],
            total: Integer,
            paging: HubSpotSDK::ForwardPaging
          }

        class CollectionResponseWithTotalBlogAuthorForwardPaging < HubSpotSDK::Internal::Type::BaseModel
          attr_accessor results: ::Array[HubSpotSDK::Cms::Blogs::BlogAuthor]

          attr_accessor total: Integer

          attr_reader paging: HubSpotSDK::ForwardPaging?

          def paging=: (HubSpotSDK::ForwardPaging) -> HubSpotSDK::ForwardPaging

          def initialize: (
            results: ::Array[HubSpotSDK::Cms::Blogs::BlogAuthor],
            total: Integer,
            ?paging: HubSpotSDK::ForwardPaging
          ) -> void

          def to_hash: -> {
            results: ::Array[HubSpotSDK::Cms::Blogs::BlogAuthor],
            total: Integer,
            paging: HubSpotSDK::ForwardPaging
          }
        end
      end
    end
  end
end
