module HubSpotSDK
  module Models
    module Cms
      module Blogs
        type collection_response_with_total_blog_version =
          {
            results: ::Array[HubSpotSDK::Cms::Blogs::VersionBlog],
            total: Integer,
            paging: HubSpotSDK::Paging
          }

        class CollectionResponseWithTotalBlogVersion < HubSpotSDK::Internal::Type::BaseModel
          attr_accessor results: ::Array[HubSpotSDK::Cms::Blogs::VersionBlog]

          attr_accessor total: Integer

          attr_reader paging: HubSpotSDK::Paging?

          def paging=: (HubSpotSDK::Paging) -> HubSpotSDK::Paging

          def initialize: (
            results: ::Array[HubSpotSDK::Cms::Blogs::VersionBlog],
            total: Integer,
            ?paging: HubSpotSDK::Paging
          ) -> void

          def to_hash: -> {
            results: ::Array[HubSpotSDK::Cms::Blogs::VersionBlog],
            total: Integer,
            paging: HubSpotSDK::Paging
          }
        end
      end
    end
  end
end
