module HubspotSDK
  module Models
    module Cms
      module Blogs
        type collection_response_with_total_blog_author_forward_paging =
          {
            results: ::Array[HubspotSDK::Cms::Blogs::BlogAuthor],
            total: Integer,
            paging: HubspotSDK::ForwardPaging
          }

        class CollectionResponseWithTotalBlogAuthorForwardPaging < HubspotSDK::Internal::Type::BaseModel
          attr_accessor results: ::Array[HubspotSDK::Cms::Blogs::BlogAuthor]

          attr_accessor total: Integer

          attr_reader paging: HubspotSDK::ForwardPaging?

          def paging=: (HubspotSDK::ForwardPaging) -> HubspotSDK::ForwardPaging

          def initialize: (
            results: ::Array[HubspotSDK::Cms::Blogs::BlogAuthor],
            total: Integer,
            ?paging: HubspotSDK::ForwardPaging
          ) -> void

          def to_hash: -> {
            results: ::Array[HubspotSDK::Cms::Blogs::BlogAuthor],
            total: Integer,
            paging: HubspotSDK::ForwardPaging
          }
        end
      end
    end
  end
end
