module HubspotSDK
  module Models
    module Cms
      module Blogs
        type collection_response_with_total_version_blog_post =
          {
            results: ::Array[HubspotSDK::Cms::Blogs::VersionBlogPost],
            total: Integer,
            paging: HubspotSDK::Marketing::EmailsPaging
          }

        class CollectionResponseWithTotalVersionBlogPost < HubspotSDK::Internal::Type::BaseModel
          attr_accessor results: ::Array[HubspotSDK::Cms::Blogs::VersionBlogPost]

          attr_accessor total: Integer

          attr_reader paging: HubspotSDK::Marketing::EmailsPaging?

          def paging=: (
            HubspotSDK::Marketing::EmailsPaging
          ) -> HubspotSDK::Marketing::EmailsPaging

          def initialize: (
            results: ::Array[HubspotSDK::Cms::Blogs::VersionBlogPost],
            total: Integer,
            ?paging: HubspotSDK::Marketing::EmailsPaging
          ) -> void

          def to_hash: -> {
            results: ::Array[HubspotSDK::Cms::Blogs::VersionBlogPost],
            total: Integer,
            paging: HubspotSDK::Marketing::EmailsPaging
          }
        end
      end
    end
  end
end
