module HubspotSDK
  module Models
    module Cms
      module Blogs
        type content_clone_request_v_next = { id: String, clone_name: String }

        class ContentCloneRequestVNext < HubspotSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_reader clone_name: String?

          def clone_name=: (String) -> String

          def initialize: (id: String, ?clone_name: String) -> void

          def to_hash: -> { id: String, clone_name: String }
        end
      end
    end
  end
end
