module HubspotSDK
  module Models
    module Cms
      module Blogs
        type post_get_previous_versions_params =
          { after: String, before: String, limit: Integer }
          & HubspotSDK::Internal::Type::request_parameters

        class PostGetPreviousVersionsParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_reader after: String?

          def after=: (String) -> String

          attr_reader before: String?

          def before=: (String) -> String

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          def initialize: (
            ?after: String,
            ?before: String,
            ?limit: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            after: String,
            before: String,
            limit: Integer,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
