module HubspotSDK
  module Models
    module Cms
      module Blogs
        type rgba_color = { a: Float, b: Integer, g: Integer, r: Integer }

        class RgbaColor < HubspotSDK::Internal::Type::BaseModel
          attr_accessor a: Float

          attr_accessor b: Integer

          attr_accessor g: Integer

          attr_accessor r: Integer

          def initialize: (a: Float, b: Integer, g: Integer, r: Integer) -> void

          def to_hash: -> { a: Float, b: Integer, g: Integer, r: Integer }
        end
      end
    end
  end
end
