module HubspotSDK
  module Models
    module Cms
      module Blogs
        type row_meta_data =
          { css_class: String, styles: HubspotSDK::Cms::Blogs::Styles }

        class RowMetaData < HubspotSDK::Internal::Type::BaseModel
          attr_accessor css_class: String

          attr_accessor styles: HubspotSDK::Cms::Blogs::Styles

          def initialize: (
            css_class: String,
            styles: HubspotSDK::Cms::Blogs::Styles
          ) -> void

          def to_hash: -> {
            css_class: String,
            styles: HubspotSDK::Cms::Blogs::Styles
          }
        end
      end
    end
  end
end
