module HubspotSDK
  module Models
    module Cms
      module Blogs
        type styles =
          {
            background_color: HubspotSDK::Cms::Blogs::RgbaColor,
            background_gradient: HubspotSDK::Cms::Blogs::Gradient,
            background_image: HubspotSDK::Cms::Blogs::BackgroundImage,
            flexbox_positioning: HubspotSDK::Models::Cms::Blogs::Styles::flexbox_positioning,
            force_full_width_section: bool,
            max_width_section_centering: Integer,
            vertical_alignment: HubspotSDK::Models::Cms::Blogs::Styles::vertical_alignment,
            breakpoint_styles: ::Hash[Symbol, HubspotSDK::Cms::Blogs::BreakpointStyles]
          }

        class Styles < HubspotSDK::Internal::Type::BaseModel
          attr_accessor background_color: HubspotSDK::Cms::Blogs::RgbaColor

          attr_accessor background_gradient: HubspotSDK::Cms::Blogs::Gradient

          attr_accessor background_image: HubspotSDK::Cms::Blogs::BackgroundImage

          attr_accessor flexbox_positioning: HubspotSDK::Models::Cms::Blogs::Styles::flexbox_positioning

          attr_accessor force_full_width_section: bool

          attr_accessor max_width_section_centering: Integer

          attr_accessor vertical_alignment: HubspotSDK::Models::Cms::Blogs::Styles::vertical_alignment

          attr_reader breakpoint_styles: ::Hash[Symbol, HubspotSDK::Cms::Blogs::BreakpointStyles]?

          def breakpoint_styles=: (
            ::Hash[Symbol, HubspotSDK::Cms::Blogs::BreakpointStyles]
          ) -> ::Hash[Symbol, HubspotSDK::Cms::Blogs::BreakpointStyles]

          def initialize: (
            background_color: HubspotSDK::Cms::Blogs::RgbaColor,
            background_gradient: HubspotSDK::Cms::Blogs::Gradient,
            background_image: HubspotSDK::Cms::Blogs::BackgroundImage,
            flexbox_positioning: HubspotSDK::Models::Cms::Blogs::Styles::flexbox_positioning,
            force_full_width_section: bool,
            max_width_section_centering: Integer,
            vertical_alignment: HubspotSDK::Models::Cms::Blogs::Styles::vertical_alignment,
            ?breakpoint_styles: ::Hash[Symbol, HubspotSDK::Cms::Blogs::BreakpointStyles]
          ) -> void

          def to_hash: -> {
            background_color: HubspotSDK::Cms::Blogs::RgbaColor,
            background_gradient: HubspotSDK::Cms::Blogs::Gradient,
            background_image: HubspotSDK::Cms::Blogs::BackgroundImage,
            flexbox_positioning: HubspotSDK::Models::Cms::Blogs::Styles::flexbox_positioning,
            force_full_width_section: bool,
            max_width_section_centering: Integer,
            vertical_alignment: HubspotSDK::Models::Cms::Blogs::Styles::vertical_alignment,
            breakpoint_styles: ::Hash[Symbol, HubspotSDK::Cms::Blogs::BreakpointStyles]
          }

          type flexbox_positioning =
            :BOTTOM_CENTER
            | :BOTTOM_LEFT
            | :BOTTOM_RIGHT
            | :MIDDLE_CENTER
            | :MIDDLE_LEFT
            | :MIDDLE_RIGHT
            | :TOP_CENTER
            | :TOP_LEFT
            | :TOP_RIGHT

          module FlexboxPositioning
            extend HubspotSDK::Internal::Type::Enum

            BOTTOM_CENTER: :BOTTOM_CENTER
            BOTTOM_LEFT: :BOTTOM_LEFT
            BOTTOM_RIGHT: :BOTTOM_RIGHT
            MIDDLE_CENTER: :MIDDLE_CENTER
            MIDDLE_LEFT: :MIDDLE_LEFT
            MIDDLE_RIGHT: :MIDDLE_RIGHT
            TOP_CENTER: :TOP_CENTER
            TOP_LEFT: :TOP_LEFT
            TOP_RIGHT: :TOP_RIGHT

            def self?.values: -> ::Array[HubspotSDK::Models::Cms::Blogs::Styles::flexbox_positioning]
          end

          type vertical_alignment = :BOTTOM | :MIDDLE | :TOP

          module VerticalAlignment
            extend HubspotSDK::Internal::Type::Enum

            BOTTOM: :BOTTOM
            MIDDLE: :MIDDLE
            TOP: :TOP

            def self?.values: -> ::Array[HubspotSDK::Models::Cms::Blogs::Styles::vertical_alignment]
          end
        end
      end
    end
  end
end
