module HubspotSDK
  module Resources
    class Crm
      class Objects
        class Appointments
          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
