module HubSpotSDK
  module Resources
    class Crm
      class Objects
        class GoalTargets
          attr_reader batch: HubSpotSDK::Resources::Crm::Objects::GoalTargets::Batch

          def create: (
            associations: ::Array[HubSpotSDK::Crm::PublicAssociationsForObject],
            properties: ::Hash[Symbol, String],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::SimplePublicObject

          def update: (
            String goal_target_id,
            properties: ::Hash[Symbol, String],
            ?id_property: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::SimplePublicObject

          def list: (
            ?after: String,
            ?archived: bool,
            ?associations: ::Array[String],
            ?limit: Integer,
            ?properties: ::Array[String],
            ?properties_with_history: ::Array[String],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Crm::SimplePublicObjectWithAssociations]

          def delete: (
            String goal_target_id,
            ?request_options: HubSpotSDK::request_opts
          ) -> nil

          def get: (
            String goal_target_id,
            ?archived: bool,
            ?associations: ::Array[String],
            ?id_property: String,
            ?properties: ::Array[String],
            ?properties_with_history: ::Array[String],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::SimplePublicObjectWithAssociations

          def search: (
            after: String,
            filter_groups: ::Array[HubSpotSDK::Crm::FilterGroup],
            limit: Integer,
            properties: ::Array[String],
            sorts: ::Array[String],
            ?query: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::CollectionResponseWithTotalSimplePublicObject

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
