module HubSpotSDK
  module Resources
    class Crm
      class Properties
        class Batch
          def create: (
            String object_type,
            inputs: ::Array[HubSpotSDK::PropertyCreate],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::BatchResponseProperty

          def delete: (
            String object_type,
            inputs: ::Array[HubSpotSDK::PropertyName],
            ?request_options: HubSpotSDK::request_opts
          ) -> nil

          def get: (
            String object_type,
            archived: bool,
            data_sensitivity: HubSpotSDK::Models::BatchReadInputPropertyName::data_sensitivity,
            inputs: ::Array[HubSpotSDK::PropertyName],
            ?locale: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::BatchResponseProperty

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
