module HubSpotSDK
  module Resources
    class Crm
      class Properties
        class Groups
          def create: (
            String object_type,
            label: String,
            name: String,
            ?display_order: Integer,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::PropertyGroup

          def update: (
            String group_name,
            object_type: String,
            ?display_order: Integer,
            ?label: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::PropertyGroup

          def list: (
            String object_type,
            ?locale: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::CollectionResponsePropertyGroupNoPaging

          def delete: (
            String group_name,
            object_type: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> nil

          def get: (
            String group_name,
            object_type: String,
            ?locale: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::PropertyGroup

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
