module HubspotSDK
  module Models
    module Crm
      type api_collection_response_record_list_membership_no_paging =
        {
          results: ::Array[HubspotSDK::Crm::RecordListMembership],
          total: Integer
        }

      class APICollectionResponseRecordListMembershipNoPaging < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubspotSDK::Crm::RecordListMembership]

        attr_reader total: Integer?

        def total=: (Integer) -> Integer

        def initialize: (
          results: ::Array[HubspotSDK::Crm::RecordListMembership],
          ?total: Integer
        ) -> void

        def to_hash: -> {
          results: ::Array[HubspotSDK::Crm::RecordListMembership],
          total: Integer
        }
      end
    end
  end
end
