module HubSpotSDK
  module Models
    module Crm
      type api_collection_response_join_time_and_record_id =
        {
          results: ::Array[HubSpotSDK::Crm::JoinTimeAndRecordID],
          paging: HubSpotSDK::Paging,
          total: Integer
        }

      class APICollectionResponseJoinTimeAndRecordID < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Crm::JoinTimeAndRecordID]

        attr_reader paging: HubSpotSDK::Paging?

        def paging=: (HubSpotSDK::Paging) -> HubSpotSDK::Paging

        attr_reader total: Integer?

        def total=: (Integer) -> Integer

        def initialize: (
          results: ::Array[HubSpotSDK::Crm::JoinTimeAndRecordID],
          ?paging: HubSpotSDK::Paging,
          ?total: Integer
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Crm::JoinTimeAndRecordID],
          paging: HubSpotSDK::Paging,
          total: Integer
        }
      end
    end
  end
end
