module HubSpotSDK
  module Models
    module Crm
      type app_uninstall_uninstall_params =
        {  } & HubSpotSDK::Internal::Type::request_parameters

      class AppUninstallUninstallParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        def initialize: (?request_options: HubSpotSDK::request_opts) -> void

        def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
      end
    end
  end
end
