module HubspotSDK
  module Models
    module Crm
      type app_event_occurrence =
        {
          id: String,
          event_type_name: String,
          properties: ::Hash[Symbol, String],
          domain: String,
          email: String,
          extra_data: top,
          object_id_: String,
          object_type_fully_qualified_name: String,
          timeline_i_frame: HubspotSDK::Crm::TimelineEventIFrame,
          timestamp: Time,
          utk: String
        }

      class AppEventOccurrence < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor event_type_name: String

        attr_accessor properties: ::Hash[Symbol, String]

        attr_reader domain: String?

        def domain=: (String) -> String

        attr_reader email: String?

        def email=: (String) -> String

        attr_reader extra_data: top?

        def extra_data=: (top) -> top

        attr_reader object_id_: String?

        def object_id_=: (String) -> String

        attr_reader object_type_fully_qualified_name: String?

        def object_type_fully_qualified_name=: (String) -> String

        attr_reader timeline_i_frame: HubspotSDK::Crm::TimelineEventIFrame?

        def timeline_i_frame=: (
          HubspotSDK::Crm::TimelineEventIFrame
        ) -> HubspotSDK::Crm::TimelineEventIFrame

        attr_reader timestamp: Time?

        def timestamp=: (Time) -> Time

        attr_reader utk: String?

        def utk=: (String) -> String

        def initialize: (
          id: String,
          event_type_name: String,
          properties: ::Hash[Symbol, String],
          ?domain: String,
          ?email: String,
          ?extra_data: top,
          ?object_id_: String,
          ?object_type_fully_qualified_name: String,
          ?timeline_i_frame: HubspotSDK::Crm::TimelineEventIFrame,
          ?timestamp: Time,
          ?utk: String
        ) -> void

        def to_hash: -> {
          id: String,
          event_type_name: String,
          properties: ::Hash[Symbol, String],
          domain: String,
          email: String,
          extra_data: top,
          object_id_: String,
          object_type_fully_qualified_name: String,
          timeline_i_frame: HubspotSDK::Crm::TimelineEventIFrame,
          timestamp: Time,
          utk: String
        }
      end
    end
  end
end
