module HubSpotSDK
  module Models
    module Crm
      type association_request_high_usage_report_params =
        { user_id: Integer } & HubSpotSDK::Internal::Type::request_parameters

      class AssociationRequestHighUsageReportParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor user_id: Integer

        def initialize: (
          user_id: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          user_id: Integer,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
