module HubspotSDK
  module Models
    module Crm
      type association_label_limit_response =
        {
          all_labels: ::Array[String],
          from_object_type: HubspotSDK::Crm::Objects::ObjectsSchemasObjectTypeDefinition,
          limit: Integer,
          percentage: Float,
          to_object_type: HubspotSDK::Crm::Objects::ObjectsSchemasObjectTypeDefinition,
          usage: Integer
        }

      class AssociationLabelLimitResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor all_labels: ::Array[String]

        attr_accessor from_object_type: HubspotSDK::Crm::Objects::ObjectsSchemasObjectTypeDefinition

        attr_accessor limit: Integer

        attr_accessor percentage: Float

        attr_accessor to_object_type: HubspotSDK::Crm::Objects::ObjectsSchemasObjectTypeDefinition

        attr_accessor usage: Integer

        def initialize: (
          all_labels: ::Array[String],
          from_object_type: HubspotSDK::Crm::Objects::ObjectsSchemasObjectTypeDefinition,
          limit: Integer,
          percentage: Float,
          to_object_type: HubspotSDK::Crm::Objects::ObjectsSchemasObjectTypeDefinition,
          usage: Integer
        ) -> void

        def to_hash: -> {
          all_labels: ::Array[String],
          from_object_type: HubspotSDK::Crm::Objects::ObjectsSchemasObjectTypeDefinition,
          limit: Integer,
          percentage: Float,
          to_object_type: HubspotSDK::Crm::Objects::ObjectsSchemasObjectTypeDefinition,
          usage: Integer
        }
      end
    end
  end
end
