module HubSpotSDK
  module Models
    module Crm
      type association_spec_with_label =
        {
          category: HubSpotSDK::Models::Crm::AssociationSpecWithLabel::category,
          type_id: Integer,
          label: String
        }

      class AssociationSpecWithLabel < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor category: HubSpotSDK::Models::Crm::AssociationSpecWithLabel::category

        attr_accessor type_id: Integer

        attr_reader label: String?

        def label=: (String) -> String

        def initialize: (
          category: HubSpotSDK::Models::Crm::AssociationSpecWithLabel::category,
          type_id: Integer,
          ?label: String
        ) -> void

        def to_hash: -> {
          category: HubSpotSDK::Models::Crm::AssociationSpecWithLabel::category,
          type_id: Integer,
          label: String
        }

        type category =
          :HUBSPOT_DEFINED | :INTEGRATOR_DEFINED | :USER_DEFINED | :WORK

        module Category
          extend HubSpotSDK::Internal::Type::Enum

          HUBSPOT_DEFINED: :HUBSPOT_DEFINED
          INTEGRATOR_DEFINED: :INTEGRATOR_DEFINED
          USER_DEFINED: :USER_DEFINED
          WORK: :WORK

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::AssociationSpecWithLabel::category]
        end
      end
    end
  end
end
