module HubspotSDK
  module Models
    module Crm
      type batch_portal_entry =
        {
          flag_state: HubspotSDK::Models::Crm::BatchPortalEntry::flag_state,
          portal_id: Integer
        }

      class BatchPortalEntry < HubspotSDK::Internal::Type::BaseModel
        attr_accessor flag_state: HubspotSDK::Models::Crm::BatchPortalEntry::flag_state

        attr_accessor portal_id: Integer

        def initialize: (
          flag_state: HubspotSDK::Models::Crm::BatchPortalEntry::flag_state,
          portal_id: Integer
        ) -> void

        def to_hash: -> {
          flag_state: HubspotSDK::Models::Crm::BatchPortalEntry::flag_state,
          portal_id: Integer
        }

        type flag_state = :ABSENT | :OFF | :ON

        module FlagState
          extend HubspotSDK::Internal::Type::Enum

          ABSENT: :ABSENT
          OFF: :OFF
          ON: :ON

          def self?.values: -> ::Array[HubspotSDK::Models::Crm::BatchPortalEntry::flag_state]
        end
      end
    end
  end
end
