module HubSpotSDK
  module Models
    module Crm
      type batch_input_public_association_multi_archive =
        { inputs: ::Array[HubSpotSDK::Crm::PublicAssociationMultiArchive] }

      class BatchInputPublicAssociationMultiArchive < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubSpotSDK::Crm::PublicAssociationMultiArchive]

        def initialize: (
          inputs: ::Array[HubSpotSDK::Crm::PublicAssociationMultiArchive]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubSpotSDK::Crm::PublicAssociationMultiArchive]
        }
      end
    end
  end
end
