module HubspotSDK
  module Models
    module Crm
      type batch_input_simple_public_object_batch_input =
        { inputs: ::Array[HubspotSDK::Crm::SimplePublicObjectBatchInput] }

      class BatchInputSimplePublicObjectBatchInput < HubspotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubspotSDK::Crm::SimplePublicObjectBatchInput]

        def initialize: (
          inputs: ::Array[HubspotSDK::Crm::SimplePublicObjectBatchInput]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubspotSDK::Crm::SimplePublicObjectBatchInput]
        }
      end
    end
  end
end
