module HubspotSDK
  module Models
    module Crm
      type batch_response_simple_public_upsert_object =
        {
          completed_at: Time,
          results: ::Array[HubspotSDK::Crm::SimplePublicUpsertObject],
          started_at: Time,
          status: HubspotSDK::Models::Crm::BatchResponseSimplePublicUpsertObject::status,
          links: ::Hash[Symbol, String],
          requested_at: Time
        }

      class BatchResponseSimplePublicUpsertObject < HubspotSDK::Internal::Type::BaseModel
        attr_accessor completed_at: Time

        attr_accessor results: ::Array[HubspotSDK::Crm::SimplePublicUpsertObject]

        attr_accessor started_at: Time

        attr_accessor status: HubspotSDK::Models::Crm::BatchResponseSimplePublicUpsertObject::status

        attr_reader links: ::Hash[Symbol, String]?

        def links=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader requested_at: Time?

        def requested_at=: (Time) -> Time

        def initialize: (
          completed_at: Time,
          results: ::Array[HubspotSDK::Crm::SimplePublicUpsertObject],
          started_at: Time,
          status: HubspotSDK::Models::Crm::BatchResponseSimplePublicUpsertObject::status,
          ?links: ::Hash[Symbol, String],
          ?requested_at: Time
        ) -> void

        def to_hash: -> {
          completed_at: Time,
          results: ::Array[HubspotSDK::Crm::SimplePublicUpsertObject],
          started_at: Time,
          status: HubspotSDK::Models::Crm::BatchResponseSimplePublicUpsertObject::status,
          links: ::Hash[Symbol, String],
          requested_at: Time
        }

        type status = :CANCELED | :COMPLETE | :PENDING | :PROCESSING

        module Status
          extend HubspotSDK::Internal::Type::Enum

          CANCELED: :CANCELED
          COMPLETE: :COMPLETE
          PENDING: :PENDING
          PROCESSING: :PROCESSING

          def self?.values: -> ::Array[HubspotSDK::Models::Crm::BatchResponseSimplePublicUpsertObject::status]
        end
      end
    end
  end
end
