module HubspotSDK
  module Models
    module Crm
      type batch_input_public_default_association_multi_post =
        { inputs: ::Array[HubspotSDK::Crm::PublicDefaultAssociationMultiPost] }

      class BatchInputPublicDefaultAssociationMultiPost < HubspotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubspotSDK::Crm::PublicDefaultAssociationMultiPost]

        def initialize: (
          inputs: ::Array[HubspotSDK::Crm::PublicDefaultAssociationMultiPost]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubspotSDK::Crm::PublicDefaultAssociationMultiPost]
        }
      end
    end
  end
end
