module HubspotSDK
  module Models
    module CRM
      type batch_portal_entry =
        {
          flag_state: HubspotSDK::Models::CRM::BatchPortalEntry::flag_state,
          portal_id: Integer
        }

      class BatchPortalEntry < HubspotSDK::Internal::Type::BaseModel
        attr_accessor flag_state: HubspotSDK::Models::CRM::BatchPortalEntry::flag_state

        attr_accessor portal_id: Integer

        def initialize: (
          flag_state: HubspotSDK::Models::CRM::BatchPortalEntry::flag_state,
          portal_id: Integer
        ) -> void

        def to_hash: -> {
          flag_state: HubspotSDK::Models::CRM::BatchPortalEntry::flag_state,
          portal_id: Integer
        }

        type flag_state = :OFF | :ON | :ABSENT

        module FlagState
          extend HubspotSDK::Internal::Type::Enum

          OFF: :OFF
          ON: :ON
          ABSENT: :ABSENT

          def self?.values: -> ::Array[HubspotSDK::Models::CRM::BatchPortalEntry::flag_state]
        end
      end
    end
  end
end
