module HubspotSDK
  module Models
    module Crm
      type batch_input_public_association_spec =
        { inputs: ::Array[HubspotSDK::Crm::PublicAssociationSpec] }

      class BatchInputPublicAssociationSpec < HubspotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubspotSDK::Crm::PublicAssociationSpec]

        def initialize: (
          inputs: ::Array[HubspotSDK::Crm::PublicAssociationSpec]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubspotSDK::Crm::PublicAssociationSpec]
        }
      end
    end
  end
end
