module HubspotSDK
  module Models
    module CRM
      type calculated_property_limit_response =
        {
          by_object_type: ::Array[HubspotSDK::CRM::UsageForObjectType],
          overall_limit: Integer,
          overall_percentage: Float,
          overall_usage: Integer
        }

      class CalculatedPropertyLimitResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor by_object_type: ::Array[HubspotSDK::CRM::UsageForObjectType]

        attr_accessor overall_limit: Integer

        attr_accessor overall_percentage: Float

        attr_accessor overall_usage: Integer

        def initialize: (
          by_object_type: ::Array[HubspotSDK::CRM::UsageForObjectType],
          overall_limit: Integer,
          overall_percentage: Float,
          overall_usage: Integer
        ) -> void

        def to_hash: -> {
          by_object_type: ::Array[HubspotSDK::CRM::UsageForObjectType],
          overall_limit: Integer,
          overall_percentage: Float,
          overall_usage: Integer
        }
      end
    end
  end
end
