module HubSpotSDK
  module Models
    module Crm
      type collection_response_object_schema_no_paging =
        { results: ::Array[HubSpotSDK::Crm::ObjectSchema] }

      class CollectionResponseObjectSchemaNoPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Crm::ObjectSchema]

        def initialize: (
          results: ::Array[HubSpotSDK::Crm::ObjectSchema]
        ) -> void

        def to_hash: -> { results: ::Array[HubSpotSDK::Crm::ObjectSchema] }
      end
    end
  end
end
