module HubSpotSDK
  module Models
    module Crm
      type collection_response_public_association_definition_user_configuration_no_paging =
        {
          results: ::Array[HubSpotSDK::Crm::PublicAssociationDefinitionUserConfiguration]
        }

      class CollectionResponsePublicAssociationDefinitionUserConfigurationNoPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Crm::PublicAssociationDefinitionUserConfiguration]

        def initialize: (
          results: ::Array[HubSpotSDK::Crm::PublicAssociationDefinitionUserConfiguration]
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Crm::PublicAssociationDefinitionUserConfiguration]
        }
      end
    end
  end
end
