module HubSpotSDK
  module Models
    module Crm
      type collection_response_simple_public_object_with_associations_forward_paging =
        {
          results: ::Array[HubSpotSDK::Crm::SimplePublicObjectWithAssociations],
          paging: HubSpotSDK::ForwardPaging
        }

      class CollectionResponseSimplePublicObjectWithAssociationsForwardPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Crm::SimplePublicObjectWithAssociations]

        attr_reader paging: HubSpotSDK::ForwardPaging?

        def paging=: (HubSpotSDK::ForwardPaging) -> HubSpotSDK::ForwardPaging

        def initialize: (
          results: ::Array[HubSpotSDK::Crm::SimplePublicObjectWithAssociations],
          ?paging: HubSpotSDK::ForwardPaging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Crm::SimplePublicObjectWithAssociations],
          paging: HubSpotSDK::ForwardPaging
        }
      end
    end
  end
end
