module HubSpotSDK
  module Models
    module Crm
      type collection_response_public_property_validation_rule_map_no_paging =
        { results: ::Array[HubSpotSDK::Crm::PublicPropertyValidationRuleMap] }

      class CollectionResponsePublicPropertyValidationRuleMapNoPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Crm::PublicPropertyValidationRuleMap]

        def initialize: (
          results: ::Array[HubSpotSDK::Crm::PublicPropertyValidationRuleMap]
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Crm::PublicPropertyValidationRuleMap]
        }
      end
    end
  end
end
