module HubspotSDK
  module Models
    module CRM
      type collection_response_public_property_validation_rule_map_no_paging =
        { results: ::Array[HubspotSDK::CRM::PublicPropertyValidationRuleMap] }

      class CollectionResponsePublicPropertyValidationRuleMapNoPaging < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubspotSDK::CRM::PublicPropertyValidationRuleMap]

        def initialize: (
          results: ::Array[HubspotSDK::CRM::PublicPropertyValidationRuleMap]
        ) -> void

        def to_hash: -> {
          results: ::Array[HubspotSDK::CRM::PublicPropertyValidationRuleMap]
        }
      end
    end
  end
end
