module HubspotSDK
  module Models
    module CRM
      type collection_response_association_label_limit_response_no_paging =
        { results: ::Array[HubspotSDK::CRM::AssociationLabelLimitResponse] }

      class CollectionResponseAssociationLabelLimitResponseNoPaging < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubspotSDK::CRM::AssociationLabelLimitResponse]

        def initialize: (
          results: ::Array[HubspotSDK::CRM::AssociationLabelLimitResponse]
        ) -> void

        def to_hash: -> {
          results: ::Array[HubspotSDK::CRM::AssociationLabelLimitResponse]
        }
      end
    end
  end
end
