module HubspotSDK
  module Models
    module Crm
      type collection_response_property_group =
        {
          results: ::Array[HubspotSDK::Crm::PropertyGroup],
          paging: HubspotSDK::Marketing::Paging
        }

      class CollectionResponsePropertyGroup < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubspotSDK::Crm::PropertyGroup]

        attr_reader paging: HubspotSDK::Marketing::Paging?

        def paging=: (
          HubspotSDK::Marketing::Paging
        ) -> HubspotSDK::Marketing::Paging

        def initialize: (
          results: ::Array[HubspotSDK::Crm::PropertyGroup],
          ?paging: HubspotSDK::Marketing::Paging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubspotSDK::Crm::PropertyGroup],
          paging: HubspotSDK::Marketing::Paging
        }
      end
    end
  end
end
