module HubspotSDK
  module Models
    module Crm
      type collection_response_pipeline_stage_no_paging =
        { results: ::Array[HubspotSDK::Crm::PipelineStage] }

      class CollectionResponsePipelineStageNoPaging < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubspotSDK::Crm::PipelineStage]

        def initialize: (
          results: ::Array[HubspotSDK::Crm::PipelineStage]
        ) -> void

        def to_hash: -> { results: ::Array[HubspotSDK::Crm::PipelineStage] }
      end
    end
  end
end
