module HubspotSDK
  module Models
    module CRM
      type collection_response_property =
        {
          results: ::Array[HubspotSDK::Property],
          paging: HubspotSDK::Marketing::Paging
        }

      class CollectionResponseProperty < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubspotSDK::Property]

        attr_reader paging: HubspotSDK::Marketing::Paging?

        def paging=: (
          HubspotSDK::Marketing::Paging
        ) -> HubspotSDK::Marketing::Paging

        def initialize: (
          results: ::Array[HubspotSDK::Property],
          ?paging: HubspotSDK::Marketing::Paging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubspotSDK::Property],
          paging: HubspotSDK::Marketing::Paging
        }
      end
    end
  end
end
