module HubSpotSDK
  module Models
    module Crm
      type collection_response_association_label_limit_response_no_paging =
        { results: ::Array[HubSpotSDK::Crm::AssociationLabelLimitResponse] }

      class CollectionResponseAssociationLabelLimitResponseNoPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Crm::AssociationLabelLimitResponse]

        def initialize: (
          results: ::Array[HubSpotSDK::Crm::AssociationLabelLimitResponse]
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Crm::AssociationLabelLimitResponse]
        }
      end
    end
  end
end
