module HubSpotSDK
  module Models
    module Crm
      type collection_response_associated_id =
        {
          results: ::Array[HubSpotSDK::Crm::AssociatedID],
          paging: HubSpotSDK::Paging
        }

      class CollectionResponseAssociatedID < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Crm::AssociatedID]

        attr_reader paging: HubSpotSDK::Paging?

        def paging=: (HubSpotSDK::Paging) -> HubSpotSDK::Paging

        def initialize: (
          results: ::Array[HubSpotSDK::Crm::AssociatedID],
          ?paging: HubSpotSDK::Paging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Crm::AssociatedID],
          paging: HubSpotSDK::Paging
        }
      end
    end
  end
end
