module HubSpotSDK
  module Models
    module Crm
      type collection_response_public_import_error_forward_paging =
        {
          results: ::Array[HubSpotSDK::Crm::PublicImportError],
          paging: HubSpotSDK::ForwardPaging
        }

      class CollectionResponsePublicImportErrorForwardPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Crm::PublicImportError]

        attr_reader paging: HubSpotSDK::ForwardPaging?

        def paging=: (HubSpotSDK::ForwardPaging) -> HubSpotSDK::ForwardPaging

        def initialize: (
          results: ::Array[HubSpotSDK::Crm::PublicImportError],
          ?paging: HubSpotSDK::ForwardPaging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Crm::PublicImportError],
          paging: HubSpotSDK::ForwardPaging
        }
      end
    end
  end
end
