module HubSpotSDK
  module Models
    module Crm
      type collection_response_association_spec_with_label_no_paging =
        { results: ::Array[HubSpotSDK::Crm::AssociationSpecWithLabel] }

      class CollectionResponseAssociationSpecWithLabelNoPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Crm::AssociationSpecWithLabel]

        def initialize: (
          results: ::Array[HubSpotSDK::Crm::AssociationSpecWithLabel]
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Crm::AssociationSpecWithLabel]
        }
      end
    end
  end
end
