module HubSpotSDK
  module Models
    module Crm
      type collection_response_object_type_near_or_at_association_limit_no_paging =
        {
          results: ::Array[HubSpotSDK::Crm::ObjectTypeNearOrAtAssociationLimit]
        }

      class CollectionResponseObjectTypeNearOrAtAssociationLimitNoPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Crm::ObjectTypeNearOrAtAssociationLimit]

        def initialize: (
          results: ::Array[HubSpotSDK::Crm::ObjectTypeNearOrAtAssociationLimit]
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Crm::ObjectTypeNearOrAtAssociationLimit]
        }
      end
    end
  end
end
