module HubspotSDK
  module Models
    module Crm
      type created_response_property_group =
        {
          created_resource_id: String,
          entity: HubspotSDK::Crm::PropertyGroup,
          location: String
        }

      class CreatedResponsePropertyGroup < HubspotSDK::Internal::Type::BaseModel
        attr_accessor created_resource_id: String

        attr_accessor entity: HubspotSDK::Crm::PropertyGroup

        attr_reader location: String?

        def location=: (String) -> String

        def initialize: (
          created_resource_id: String,
          entity: HubspotSDK::Crm::PropertyGroup,
          ?location: String
        ) -> void

        def to_hash: -> {
          created_resource_id: String,
          entity: HubspotSDK::Crm::PropertyGroup,
          location: String
        }
      end
    end
  end
end
