module HubspotSDK
  module Models
    module CRM
      type created_response_simple_public_object =
        {
          created_resource_id: String,
          entity: HubspotSDK::CRM::SimplePublicObject,
          location: String
        }

      class CreatedResponseSimplePublicObject < HubspotSDK::Internal::Type::BaseModel
        attr_accessor created_resource_id: String

        attr_accessor entity: HubspotSDK::CRM::SimplePublicObject

        attr_reader location: String?

        def location=: (String) -> String

        def initialize: (
          created_resource_id: String,
          entity: HubspotSDK::CRM::SimplePublicObject,
          ?location: String
        ) -> void

        def to_hash: -> {
          created_resource_id: String,
          entity: HubspotSDK::CRM::SimplePublicObject,
          location: String
        }
      end
    end
  end
end
