module HubspotSDK
  module Models
    module Crm
      type custom_property_limit_response =
        {
          by_object_type: ::Array[HubspotSDK::Crm::LimitAndUsageForObjectType],
          overall_limit: Integer,
          overall_percentage: Float,
          overall_usage: Integer
        }

      class CustomPropertyLimitResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor by_object_type: ::Array[HubspotSDK::Crm::LimitAndUsageForObjectType]

        attr_accessor overall_limit: Integer

        attr_accessor overall_percentage: Float

        attr_accessor overall_usage: Integer

        def initialize: (
          by_object_type: ::Array[HubspotSDK::Crm::LimitAndUsageForObjectType],
          overall_limit: Integer,
          overall_percentage: Float,
          overall_usage: Integer
        ) -> void

        def to_hash: -> {
          by_object_type: ::Array[HubspotSDK::Crm::LimitAndUsageForObjectType],
          overall_limit: Integer,
          overall_percentage: Float,
          overall_usage: Integer
        }
      end
    end
  end
end
