module HubSpotSDK
  module Models
    module Crm
      type date_time =
        { date_only: bool, time_zone_shift: Integer, value: Integer }

      class DateTime < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor date_only: bool

        attr_accessor time_zone_shift: Integer

        attr_accessor value: Integer

        def initialize: (
          date_only: bool,
          time_zone_shift: Integer,
          value: Integer
        ) -> void

        def to_hash: -> {
          date_only: bool,
          time_zone_shift: Integer,
          value: Integer
        }
      end
    end
  end
end
