module HubSpotSDK
  module Models
    module Crm
      type deal_to_deal_splits =
        { id: String, splits: ::Array[HubSpotSDK::Crm::SimplePublicObject] }

      class DealToDealSplits < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor splits: ::Array[HubSpotSDK::Crm::SimplePublicObject]

        def initialize: (
          id: String,
          splits: ::Array[HubSpotSDK::Crm::SimplePublicObject]
        ) -> void

        def to_hash: -> {
          id: String,
          splits: ::Array[HubSpotSDK::Crm::SimplePublicObject]
        }
      end
    end
  end
end
