module HubSpotSDK
  module Models
    module Crm
      type filter_group = { filters: ::Array[HubSpotSDK::Crm::Filter] }

      class FilterGroup < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor filters: ::Array[HubSpotSDK::Crm::Filter]

        def initialize: (filters: ::Array[HubSpotSDK::Crm::Filter]) -> void

        def to_hash: -> { filters: ::Array[HubSpotSDK::Crm::Filter] }
      end
    end
  end
end
