module HubspotSDK
  module Models
    module Crm
      type flags_for_app_response = { flags_for_app: ::Array[String] }

      class FlagsForAppResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor flags_for_app: ::Array[String]

        def initialize: (flags_for_app: ::Array[String]) -> void

        def to_hash: -> { flags_for_app: ::Array[String] }
      end
    end
  end
end
