module HubSpotSDK
  module Models
    module Crm
      type flag_put_request =
        {
          default_state: HubSpotSDK::Models::Crm::FlagPutRequest::default_state,
          override_state: HubSpotSDK::Models::Crm::FlagPutRequest::override_state
        }

      class FlagPutRequest < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor default_state: HubSpotSDK::Models::Crm::FlagPutRequest::default_state

        attr_reader override_state: HubSpotSDK::Models::Crm::FlagPutRequest::override_state?

        def override_state=: (
          HubSpotSDK::Models::Crm::FlagPutRequest::override_state
        ) -> HubSpotSDK::Models::Crm::FlagPutRequest::override_state

        def initialize: (
          default_state: HubSpotSDK::Models::Crm::FlagPutRequest::default_state,
          ?override_state: HubSpotSDK::Models::Crm::FlagPutRequest::override_state
        ) -> void

        def to_hash: -> {
          default_state: HubSpotSDK::Models::Crm::FlagPutRequest::default_state,
          override_state: HubSpotSDK::Models::Crm::FlagPutRequest::override_state
        }

        type default_state = :ABSENT | :OFF | :ON

        module DefaultState
          extend HubSpotSDK::Internal::Type::Enum

          ABSENT: :ABSENT
          OFF: :OFF
          ON: :ON

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::FlagPutRequest::default_state]
        end

        type override_state = :ABSENT | :OFF | :ON

        module OverrideState
          extend HubSpotSDK::Internal::Type::Enum

          ABSENT: :ABSENT
          OFF: :OFF
          ON: :ON

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::FlagPutRequest::override_state]
        end
      end
    end
  end
end
