module HubSpotSDK
  module Models
    module Crm
      type flag_response =
        {
          app_id: Integer,
          default_state: HubSpotSDK::Models::Crm::FlagResponse::default_state,
          flag_name: String,
          override_state: HubSpotSDK::Models::Crm::FlagResponse::override_state
        }

      class FlagResponse < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor app_id: Integer

        attr_accessor default_state: HubSpotSDK::Models::Crm::FlagResponse::default_state

        attr_accessor flag_name: String

        attr_reader override_state: HubSpotSDK::Models::Crm::FlagResponse::override_state?

        def override_state=: (
          HubSpotSDK::Models::Crm::FlagResponse::override_state
        ) -> HubSpotSDK::Models::Crm::FlagResponse::override_state

        def initialize: (
          app_id: Integer,
          default_state: HubSpotSDK::Models::Crm::FlagResponse::default_state,
          flag_name: String,
          ?override_state: HubSpotSDK::Models::Crm::FlagResponse::override_state
        ) -> void

        def to_hash: -> {
          app_id: Integer,
          default_state: HubSpotSDK::Models::Crm::FlagResponse::default_state,
          flag_name: String,
          override_state: HubSpotSDK::Models::Crm::FlagResponse::override_state
        }

        type default_state = :ABSENT | :OFF | :ON

        module DefaultState
          extend HubSpotSDK::Internal::Type::Enum

          ABSENT: :ABSENT
          OFF: :OFF
          ON: :ON

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::FlagResponse::default_state]
        end

        type override_state = :ABSENT | :OFF | :ON

        module OverrideState
          extend HubSpotSDK::Internal::Type::Enum

          ABSENT: :ABSENT
          OFF: :OFF
          ON: :ON

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::FlagResponse::override_state]
        end
      end
    end
  end
end
