module HubSpotSDK
  module Models
    module Crm
      type import_create_params =
        { files: HubSpotSDK::Internal::file_input, import_request: String }
        & HubSpotSDK::Internal::Type::request_parameters

      class ImportCreateParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_reader files: HubSpotSDK::Internal::file_input?

        def files=: (
          HubSpotSDK::Internal::file_input
        ) -> HubSpotSDK::Internal::file_input

        attr_reader import_request: String?

        def import_request=: (String) -> String

        def initialize: (
          ?files: HubSpotSDK::Internal::file_input,
          ?import_request: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          files: HubSpotSDK::Internal::file_input,
          import_request: String,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
