module HubSpotSDK
  module Models
    module Crm
      type import_cancel_params =
        { import_id: Integer } & HubSpotSDK::Internal::Type::request_parameters

      class ImportCancelParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor import_id: Integer

        def initialize: (
          import_id: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          import_id: Integer,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
