module HubspotSDK
  module Models
    module Crm
      type join_time_and_record_id =
        { membership_timestamp: Time, record_id: String }

      class JoinTimeAndRecordID < HubspotSDK::Internal::Type::BaseModel
        attr_accessor membership_timestamp: Time

        attr_accessor record_id: String

        def initialize: (membership_timestamp: Time, record_id: String) -> void

        def to_hash: -> { membership_timestamp: Time, record_id: String }
      end
    end
  end
end
