module HubSpotSDK
  module Models
    module Crm
      type limit_get_custom_object_type_limits_params =
        {  } & HubSpotSDK::Internal::Type::request_parameters

      class LimitGetCustomObjectTypeLimitsParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        def initialize: (?request_options: HubSpotSDK::request_opts) -> void

        def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
      end
    end
  end
end
