module HubspotSDK
  module Models
    module CRM
      type limit_get_record_limits_params =
        {  } & HubspotSDK::Internal::Type::request_parameters

      class LimitGetRecordLimitsParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        def initialize: (?request_options: HubspotSDK::request_opts) -> void

        def to_hash: -> { request_options: HubspotSDK::RequestOptions }
      end
    end
  end
end
