module HubSpotSDK
  module Models
    module Crm
      type limit_get_association_label_limits_params =
        { from_object_type_id: String, to_object_type_id: String }
        & HubSpotSDK::Internal::Type::request_parameters

      class LimitGetAssociationLabelLimitsParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_reader from_object_type_id: String?

        def from_object_type_id=: (String) -> String

        attr_reader to_object_type_id: String?

        def to_object_type_id=: (String) -> String

        def initialize: (
          ?from_object_type_id: String,
          ?to_object_type_id: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          from_object_type_id: String,
          to_object_type_id: String,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
