module HubSpotSDK
  module Models
    module Crm
      type list_folder_fetch_response =
        { folder: HubSpotSDK::Crm::PublicListFolder }

      class ListFolderFetchResponse < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor folder: HubSpotSDK::Crm::PublicListFolder

        def initialize: (folder: HubSpotSDK::Crm::PublicListFolder) -> void

        def to_hash: -> { folder: HubSpotSDK::Crm::PublicListFolder }
      end
    end
  end
end
