module HubspotSDK
  module Models
    module CRM
      type list_create_request =
        {
          name: String,
          object_type_id: String,
          processing_type: String,
          custom_properties: ::Hash[Symbol, String],
          filter_branch: HubspotSDK::Models::CRM::ListCreateRequest::filter_branch,
          list_folder_id: Integer,
          list_permissions: HubspotSDK::CRM::PublicListPermissions,
          membership_settings: HubspotSDK::CRM::PublicMembershipSettings
        }

      class ListCreateRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor object_type_id: String

        attr_accessor processing_type: String

        attr_reader custom_properties: ::Hash[Symbol, String]?

        def custom_properties=: (
          ::Hash[Symbol, String]
        ) -> ::Hash[Symbol, String]

        attr_reader filter_branch: HubspotSDK::Models::CRM::ListCreateRequest::filter_branch?

        def filter_branch=: (
          HubspotSDK::Models::CRM::ListCreateRequest::filter_branch
        ) -> HubspotSDK::Models::CRM::ListCreateRequest::filter_branch

        attr_reader list_folder_id: Integer?

        def list_folder_id=: (Integer) -> Integer

        attr_reader list_permissions: HubspotSDK::CRM::PublicListPermissions?

        def list_permissions=: (
          HubspotSDK::CRM::PublicListPermissions
        ) -> HubspotSDK::CRM::PublicListPermissions

        attr_reader membership_settings: HubspotSDK::CRM::PublicMembershipSettings?

        def membership_settings=: (
          HubspotSDK::CRM::PublicMembershipSettings
        ) -> HubspotSDK::CRM::PublicMembershipSettings

        def initialize: (
          name: String,
          object_type_id: String,
          processing_type: String,
          ?custom_properties: ::Hash[Symbol, String],
          ?filter_branch: HubspotSDK::Models::CRM::ListCreateRequest::filter_branch,
          ?list_folder_id: Integer,
          ?list_permissions: HubspotSDK::CRM::PublicListPermissions,
          ?membership_settings: HubspotSDK::CRM::PublicMembershipSettings
        ) -> void

        def to_hash: -> {
          name: String,
          object_type_id: String,
          processing_type: String,
          custom_properties: ::Hash[Symbol, String],
          filter_branch: HubspotSDK::Models::CRM::ListCreateRequest::filter_branch,
          list_folder_id: Integer,
          list_permissions: HubspotSDK::CRM::PublicListPermissions,
          membership_settings: HubspotSDK::CRM::PublicMembershipSettings
        }

        type filter_branch =
          HubspotSDK::PublicOrFilterBranch
          | HubspotSDK::PublicAndFilterBranch
          | HubspotSDK::PublicNotAllFilterBranch
          | HubspotSDK::PublicNotAnyFilterBranch
          | HubspotSDK::PublicRestrictedFilterBranch
          | HubspotSDK::PublicUnifiedEventsFilterBranch
          | HubspotSDK::PublicPropertyAssociationFilterBranch
          | HubspotSDK::PublicAssociationFilterBranch

        module FilterBranch
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::CRM::ListCreateRequest::filter_branch]
        end
      end
    end
  end
end
