module HubspotSDK
  module Models
    module Crm
      type list_update_response =
        { updated_list: HubspotSDK::Crm::PublicObjectList }

      class ListUpdateResponse < HubspotSDK::Internal::Type::BaseModel
        attr_reader updated_list: HubspotSDK::Crm::PublicObjectList?

        def updated_list=: (
          HubspotSDK::Crm::PublicObjectList
        ) -> HubspotSDK::Crm::PublicObjectList

        def initialize: (
          ?updated_list: HubspotSDK::Crm::PublicObjectList
        ) -> void

        def to_hash: -> { updated_list: HubspotSDK::Crm::PublicObjectList }
      end
    end
  end
end
