module HubspotSDK
  module Models
    module Crm
      type list_list_folders_params =
        { folder_id: String } & HubspotSDK::Internal::Type::request_parameters

      class ListListFoldersParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_reader folder_id: String?

        def folder_id=: (String) -> String

        def initialize: (
          ?folder_id: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          folder_id: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
