module HubSpotSDK
  module Models
    module Crm
      type list_create_response = { list: HubSpotSDK::Crm::PublicObjectList }

      class ListCreateResponse < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor list: HubSpotSDK::Crm::PublicObjectList

        def initialize: (list: HubSpotSDK::Crm::PublicObjectList) -> void

        def to_hash: -> { list: HubSpotSDK::Crm::PublicObjectList }
      end
    end
  end
end
