module HubspotSDK
  module Models
    module CRM
      type list_folder_create_response =
        { folder: HubspotSDK::CRM::PublicListFolder }

      class ListFolderCreateResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor folder: HubspotSDK::CRM::PublicListFolder

        def initialize: (folder: HubspotSDK::CRM::PublicListFolder) -> void

        def to_hash: -> { folder: HubspotSDK::CRM::PublicListFolder }
      end
    end
  end
end
