module HubspotSDK
  module Models
    module Crm
      type list_update_list_filters_params =
        { list_id: String, enroll_objects_in_workflows: bool }
        & HubspotSDK::Internal::Type::request_parameters

      class ListUpdateListFiltersParams < HubspotSDK::Models::Crm::ListFilterUpdateRequest
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        def list_id: -> String

        def list_id=: (String _) -> String

        def enroll_objects_in_workflows: -> bool?

        def enroll_objects_in_workflows=: (bool _) -> bool

        def initialize: (
          list_id: String,
          ?enroll_objects_in_workflows: bool,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          list_id: String,
          enroll_objects_in_workflows: bool,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
