module HubspotSDK
  module Models
    module CRM
      type list_search_response =
        {
          has_more: bool,
          lists: ::Array[HubspotSDK::CRM::PublicObjectListSearchResult],
          offset: Integer,
          total: Integer
        }

      class ListSearchResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor has_more: bool

        attr_accessor lists: ::Array[HubspotSDK::CRM::PublicObjectListSearchResult]

        attr_accessor offset: Integer

        attr_accessor total: Integer

        def initialize: (
          has_more: bool,
          lists: ::Array[HubspotSDK::CRM::PublicObjectListSearchResult],
          offset: Integer,
          total: Integer
        ) -> void

        def to_hash: -> {
          has_more: bool,
          lists: ::Array[HubspotSDK::CRM::PublicObjectListSearchResult],
          offset: Integer,
          total: Integer
        }
      end
    end
  end
end
