module HubspotSDK
  module Models
    module Crm
      type list_move_request = { list_id: String, new_folder_id: String }

      class ListMoveRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor list_id: String

        attr_accessor new_folder_id: String

        def initialize: (list_id: String, new_folder_id: String) -> void

        def to_hash: -> { list_id: String, new_folder_id: String }
      end
    end
  end
end
