module HubSpotSDK
  module Models
    module Crm
      type list_get_params =
        { list_id: String, include_filters: bool }
        & HubSpotSDK::Internal::Type::request_parameters

      class ListGetParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor list_id: String

        attr_reader include_filters: bool?

        def include_filters=: (bool) -> bool

        def initialize: (
          list_id: String,
          ?include_filters: bool,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          list_id: String,
          include_filters: bool,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
