module HubspotSDK
  module Models
    module CRM
      type list_search_request =
        {
          additional_properties: ::Array[String],
          count: Integer,
          list_ids: ::Array[String],
          offset: Integer,
          processing_types: ::Array[String],
          query: String,
          sort: String
        }

      class ListSearchRequest < HubspotSDK::Internal::Type::BaseModel
        attr_reader additional_properties: ::Array[String]?

        def additional_properties=: (::Array[String]) -> ::Array[String]

        attr_reader count: Integer?

        def count=: (Integer) -> Integer

        attr_reader list_ids: ::Array[String]?

        def list_ids=: (::Array[String]) -> ::Array[String]

        attr_reader offset: Integer?

        def offset=: (Integer) -> Integer

        attr_reader processing_types: ::Array[String]?

        def processing_types=: (::Array[String]) -> ::Array[String]

        attr_reader query: String?

        def query=: (String) -> String

        attr_reader sort: String?

        def sort=: (String) -> String

        def initialize: (
          ?additional_properties: ::Array[String],
          ?count: Integer,
          ?list_ids: ::Array[String],
          ?offset: Integer,
          ?processing_types: ::Array[String],
          ?query: String,
          ?sort: String
        ) -> void

        def to_hash: -> {
          additional_properties: ::Array[String],
          count: Integer,
          list_ids: ::Array[String],
          offset: Integer,
          processing_types: ::Array[String],
          query: String,
          sort: String
        }
      end
    end
  end
end
