module HubspotSDK
  module Models
    module Crm
      type list_filter_update_request =
        {
          filter_branch: HubspotSDK::Models::Crm::ListFilterUpdateRequest::filter_branch
        }

      class ListFilterUpdateRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor filter_branch: HubspotSDK::Models::Crm::ListFilterUpdateRequest::filter_branch

        def initialize: (
          filter_branch: HubspotSDK::Models::Crm::ListFilterUpdateRequest::filter_branch
        ) -> void

        def to_hash: -> {
          filter_branch: HubspotSDK::Models::Crm::ListFilterUpdateRequest::filter_branch
        }

        type filter_branch =
          HubspotSDK::Crm::PublicOrFilterBranch
          | HubspotSDK::Crm::PublicAndFilterBranch
          | HubspotSDK::Crm::PublicNotAllFilterBranch
          | HubspotSDK::Crm::PublicNotAnyFilterBranch
          | HubspotSDK::Crm::PublicRestrictedFilterBranch
          | HubspotSDK::Crm::PublicUnifiedEventsFilterBranch
          | HubspotSDK::Crm::PublicPropertyAssociationFilterBranch
          | HubspotSDK::Crm::PublicAssociationFilterBranch

        module FilterBranch
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Crm::ListFilterUpdateRequest::filter_branch]
        end
      end
    end
  end
end
