module HubSpotSDK
  module Models
    module Crm
      type list_filter_update_request =
        {
          filter_branch: HubSpotSDK::Models::Crm::ListFilterUpdateRequest::filter_branch
        }

      class ListFilterUpdateRequest < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor filter_branch: HubSpotSDK::Models::Crm::ListFilterUpdateRequest::filter_branch

        def initialize: (
          filter_branch: HubSpotSDK::Models::Crm::ListFilterUpdateRequest::filter_branch
        ) -> void

        def to_hash: -> {
          filter_branch: HubSpotSDK::Models::Crm::ListFilterUpdateRequest::filter_branch
        }

        type filter_branch =
          HubSpotSDK::Crm::PublicOrFilterBranch
          | HubSpotSDK::Crm::PublicAndFilterBranch
          | HubSpotSDK::Crm::PublicNotAllFilterBranch
          | HubSpotSDK::Crm::PublicNotAnyFilterBranch
          | HubSpotSDK::Crm::PublicRestrictedFilterBranch
          | HubSpotSDK::Crm::PublicUnifiedEventsFilterBranch
          | HubSpotSDK::Crm::PublicPropertyAssociationFilterBranch
          | HubSpotSDK::Crm::PublicAssociationFilterBranch

        module FilterBranch
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Crm::ListFilterUpdateRequest::filter_branch]
        end
      end
    end
  end
end
