module HubSpotSDK
  module Models
    module Crm
      type list_list_folders_params =
        { folder_id: String } & HubSpotSDK::Internal::Type::request_parameters

      class ListListFoldersParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_reader folder_id: String?

        def folder_id=: (String) -> String

        def initialize: (
          ?folder_id: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          folder_id: String,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
