module HubspotSDK
  module Models
    module CRM
      type list_search_params =
        {  } & HubspotSDK::Internal::Type::request_parameters

      class ListSearchParams < HubspotSDK::Models::CRM::ListSearchRequest
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        def initialize: (?request_options: HubspotSDK::request_opts) -> void

        def to_hash: -> { request_options: HubspotSDK::RequestOptions }
      end
    end
  end
end
