module HubspotSDK
  module Models
    module Crm
      type list_get_record_memberships_params =
        { object_type_id: String, record_id: String }
        & HubspotSDK::Internal::Type::request_parameters

      class ListGetRecordMembershipsParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor object_type_id: String

        attr_accessor record_id: String

        def initialize: (
          object_type_id: String,
          record_id: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          object_type_id: String,
          record_id: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
