module HubSpotSDK
  module Models
    module Crm
      type list_get_size_and_edits_history_between_params =
        { list_id: String, end_date: String, start_date: String }
        & HubSpotSDK::Internal::Type::request_parameters

      class ListGetSizeAndEditsHistoryBetweenParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor list_id: String

        attr_reader end_date: String?

        def end_date=: (String) -> String

        attr_reader start_date: String?

        def start_date=: (String) -> String

        def initialize: (
          list_id: String,
          ?end_date: String,
          ?start_date: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          list_id: String,
          end_date: String,
          start_date: String,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
