module HubSpotSDK
  module Models
    module Crm
      type list_create_request =
        {
          name: String,
          object_type_id: String,
          processing_type: String,
          custom_properties: ::Hash[Symbol, String],
          filter_branch: HubSpotSDK::Models::Crm::ListCreateRequest::filter_branch,
          list_folder_id: Integer,
          list_permissions: HubSpotSDK::Crm::PublicListPermissions,
          membership_settings: HubSpotSDK::Crm::PublicMembershipSettings
        }

      class ListCreateRequest < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor object_type_id: String

        attr_accessor processing_type: String

        attr_reader custom_properties: ::Hash[Symbol, String]?

        def custom_properties=: (
          ::Hash[Symbol, String]
        ) -> ::Hash[Symbol, String]

        attr_reader filter_branch: HubSpotSDK::Models::Crm::ListCreateRequest::filter_branch?

        def filter_branch=: (
          HubSpotSDK::Models::Crm::ListCreateRequest::filter_branch
        ) -> HubSpotSDK::Models::Crm::ListCreateRequest::filter_branch

        attr_reader list_folder_id: Integer?

        def list_folder_id=: (Integer) -> Integer

        attr_reader list_permissions: HubSpotSDK::Crm::PublicListPermissions?

        def list_permissions=: (
          HubSpotSDK::Crm::PublicListPermissions
        ) -> HubSpotSDK::Crm::PublicListPermissions

        attr_reader membership_settings: HubSpotSDK::Crm::PublicMembershipSettings?

        def membership_settings=: (
          HubSpotSDK::Crm::PublicMembershipSettings
        ) -> HubSpotSDK::Crm::PublicMembershipSettings

        def initialize: (
          name: String,
          object_type_id: String,
          processing_type: String,
          ?custom_properties: ::Hash[Symbol, String],
          ?filter_branch: HubSpotSDK::Models::Crm::ListCreateRequest::filter_branch,
          ?list_folder_id: Integer,
          ?list_permissions: HubSpotSDK::Crm::PublicListPermissions,
          ?membership_settings: HubSpotSDK::Crm::PublicMembershipSettings
        ) -> void

        def to_hash: -> {
          name: String,
          object_type_id: String,
          processing_type: String,
          custom_properties: ::Hash[Symbol, String],
          filter_branch: HubSpotSDK::Models::Crm::ListCreateRequest::filter_branch,
          list_folder_id: Integer,
          list_permissions: HubSpotSDK::Crm::PublicListPermissions,
          membership_settings: HubSpotSDK::Crm::PublicMembershipSettings
        }

        type filter_branch =
          HubSpotSDK::Crm::PublicOrFilterBranch
          | HubSpotSDK::Crm::PublicAndFilterBranch
          | HubSpotSDK::Crm::PublicNotAllFilterBranch
          | HubSpotSDK::Crm::PublicNotAnyFilterBranch
          | HubSpotSDK::Crm::PublicRestrictedFilterBranch
          | HubSpotSDK::Crm::PublicUnifiedEventsFilterBranch
          | HubSpotSDK::Crm::PublicPropertyAssociationFilterBranch
          | HubSpotSDK::Crm::PublicAssociationFilterBranch

        module FilterBranch
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Crm::ListCreateRequest::filter_branch]
        end
      end
    end
  end
end
