module HubspotSDK
  module Models
    module Crm
      type list_fetch_response = { list: HubspotSDK::Crm::PublicObjectList }

      class ListFetchResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor list: HubspotSDK::Crm::PublicObjectList

        def initialize: (list: HubspotSDK::Crm::PublicObjectList) -> void

        def to_hash: -> { list: HubspotSDK::Crm::PublicObjectList }
      end
    end
  end
end
