module HubspotSDK
  module Models
    module Crm
      type memberships_update_response =
        {
          record_ids_missing: ::Array[String],
          record_ids_removed: ::Array[String],
          records_ids_added: ::Array[String]
        }

      class MembershipsUpdateResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor record_ids_missing: ::Array[String]

        attr_accessor record_ids_removed: ::Array[String]

        attr_accessor records_ids_added: ::Array[String]

        def initialize: (
          record_ids_missing: ::Array[String],
          record_ids_removed: ::Array[String],
          records_ids_added: ::Array[String]
        ) -> void

        def to_hash: -> {
          record_ids_missing: ::Array[String],
          record_ids_removed: ::Array[String],
          records_ids_added: ::Array[String]
        }
      end
    end
  end
end
