module HubspotSDK
  module Models
    module Crm
      type near_limit_record_sample =
        {
          label: String,
          object_id_: Integer,
          percentage: Float,
          usage: Integer
        }

      class NearLimitRecordSample < HubspotSDK::Internal::Type::BaseModel
        attr_accessor label: String

        attr_accessor object_id_: Integer

        attr_accessor percentage: Float

        attr_accessor usage: Integer

        def initialize: (
          label: String,
          object_id_: Integer,
          percentage: Float,
          usage: Integer
        ) -> void

        def to_hash: -> {
          label: String,
          object_id_: Integer,
          percentage: Float,
          usage: Integer
        }
      end
    end
  end
end
