module HubspotSDK
  module Models
    module Crm
      type object_schema_delete_association_params =
        { object_type: String, association_identifier: String }
        & HubspotSDK::Internal::Type::request_parameters

      class ObjectSchemaDeleteAssociationParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor object_type: String

        attr_accessor association_identifier: String

        def initialize: (
          object_type: String,
          association_identifier: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          object_type: String,
          association_identifier: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
