module HubspotSDK
  module Models
    module CRM
      type option_input =
        {
          hidden: bool,
          label: String,
          value: String,
          description: String,
          display_order: Integer
        }

      class OptionInput < HubspotSDK::Internal::Type::BaseModel
        attr_accessor hidden: bool

        attr_accessor label: String

        attr_accessor value: String

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader display_order: Integer?

        def display_order=: (Integer) -> Integer

        def initialize: (
          hidden: bool,
          label: String,
          value: String,
          ?description: String,
          ?display_order: Integer
        ) -> void

        def to_hash: -> {
          hidden: bool,
          label: String,
          value: String,
          description: String,
          display_order: Integer
        }
      end
    end
  end
end
