module HubspotSDK
  module Models
    module Crm
      type paging =
        { next_: HubspotSDK::NextPage, prev: HubspotSDK::Crm::PreviousPage }

      class Paging < HubspotSDK::Internal::Type::BaseModel
        attr_reader next_: HubspotSDK::NextPage?

        def next_=: (HubspotSDK::NextPage) -> HubspotSDK::NextPage

        attr_reader prev: HubspotSDK::Crm::PreviousPage?

        def prev=: (
          HubspotSDK::Crm::PreviousPage
        ) -> HubspotSDK::Crm::PreviousPage

        def initialize: (
          ?next_: HubspotSDK::NextPage,
          ?prev: HubspotSDK::Crm::PreviousPage
        ) -> void

        def to_hash: -> {
          next_: HubspotSDK::NextPage,
          prev: HubspotSDK::Crm::PreviousPage
        }
      end
    end
  end
end
