module HubspotSDK
  module Models
    module Crm
      type pause_subscription_request = { pause_reason: String }

      class PauseSubscriptionRequest < HubspotSDK::Internal::Type::BaseModel
        attr_reader pause_reason: String?

        def pause_reason=: (String) -> String

        def initialize: (?pause_reason: String) -> void

        def to_hash: -> { pause_reason: String }
      end
    end
  end
end
