module HubSpotSDK
  module Models
    module Crm
      type pipeline_stage_input =
        {
          display_order: Integer,
          label: String,
          metadata: ::Hash[Symbol, String],
          stage_id: String
        }

      class PipelineStageInput < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor display_order: Integer

        attr_accessor label: String

        attr_accessor metadata: ::Hash[Symbol, String]

        attr_reader stage_id: String?

        def stage_id=: (String) -> String

        def initialize: (
          display_order: Integer,
          label: String,
          metadata: ::Hash[Symbol, String],
          ?stage_id: String
        ) -> void

        def to_hash: -> {
          display_order: Integer,
          label: String,
          metadata: ::Hash[Symbol, String],
          stage_id: String
        }
      end
    end
  end
end
