module HubspotSDK
  module Models
    module Crm
      type pipeline_input =
        {
          display_order: Integer,
          label: String,
          stages: ::Array[HubspotSDK::Crm::PipelineStageInput],
          pipeline_id: String
        }

      class PipelineInput < HubspotSDK::Internal::Type::BaseModel
        attr_accessor display_order: Integer

        attr_accessor label: String

        attr_accessor stages: ::Array[HubspotSDK::Crm::PipelineStageInput]

        attr_reader pipeline_id: String?

        def pipeline_id=: (String) -> String

        def initialize: (
          display_order: Integer,
          label: String,
          stages: ::Array[HubspotSDK::Crm::PipelineStageInput],
          ?pipeline_id: String
        ) -> void

        def to_hash: -> {
          display_order: Integer,
          label: String,
          stages: ::Array[HubspotSDK::Crm::PipelineStageInput],
          pipeline_id: String
        }
      end
    end
  end
end
