module HubspotSDK
  module Models
    module Crm
      type pipeline_stage_replace_input =
        {
          display_order: Integer,
          label: String,
          metadata: ::Hash[Symbol, String]
        }

      class PipelineStageReplaceInput < HubspotSDK::Internal::Type::BaseModel
        attr_accessor display_order: Integer

        attr_accessor label: String

        attr_accessor metadata: ::Hash[Symbol, String]

        def initialize: (
          display_order: Integer,
          label: String,
          metadata: ::Hash[Symbol, String]
        ) -> void

        def to_hash: -> {
          display_order: Integer,
          label: String,
          metadata: ::Hash[Symbol, String]
        }
      end
    end
  end
end
