module HubSpotSDK
  module Models
    module Crm
      type pipeline_get_stage_params =
        { object_type: String, pipeline_id: String, stage_id: String }
        & HubSpotSDK::Internal::Type::request_parameters

      class PipelineGetStageParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor object_type: String

        attr_accessor pipeline_id: String

        attr_accessor stage_id: String

        def initialize: (
          object_type: String,
          pipeline_id: String,
          stage_id: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          object_type: String,
          pipeline_id: String,
          stage_id: String,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
