module HubspotSDK
  module Models
    module Crm
      type pipeline_list_params =
        { object_type: String } & HubspotSDK::Internal::Type::request_parameters

      class PipelineListParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor object_type: String

        def initialize: (
          object_type: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          object_type: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
