module HubSpotSDK
  module Models
    module Crm
      type pipeline_update_all_properties_params =
        {
          object_type: String,
          pipeline_id: String,
          validate_deal_stage_usages_before_delete: bool,
          validate_references_before_delete: bool
        }
        & HubSpotSDK::Internal::Type::request_parameters

      class PipelineUpdateAllPropertiesParams < HubSpotSDK::Models::Crm::PipelineReplaceInput
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        def object_type: -> String

        def object_type=: (String _) -> String

        def pipeline_id: -> String

        def pipeline_id=: (String _) -> String

        def validate_deal_stage_usages_before_delete: -> bool?

        def validate_deal_stage_usages_before_delete=: (bool _) -> bool

        def validate_references_before_delete: -> bool?

        def validate_references_before_delete=: (bool _) -> bool

        def initialize: (
          object_type: String,
          pipeline_id: String,
          ?validate_deal_stage_usages_before_delete: bool,
          ?validate_references_before_delete: bool,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          object_type: String,
          pipeline_id: String,
          validate_deal_stage_usages_before_delete: bool,
          validate_references_before_delete: bool,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
