module HubspotSDK
  module Models
    module CRM
      type pipeline_patch_input =
        { archived: bool, display_order: Integer, label: String }

      class PipelinePatchInput < HubspotSDK::Internal::Type::BaseModel
        attr_reader archived: bool?

        def archived=: (bool) -> bool

        attr_reader display_order: Integer?

        def display_order=: (Integer) -> Integer

        attr_reader label: String?

        def label=: (String) -> String

        def initialize: (
          ?archived: bool,
          ?display_order: Integer,
          ?label: String
        ) -> void

        def to_hash: -> {
          archived: bool,
          display_order: Integer,
          label: String
        }
      end
    end
  end
end
