module HubSpotSDK
  module Models
    module Crm
      type pipeline =
        {
          id: String,
          archived: bool,
          created_at: Time,
          display_order: Integer,
          label: String,
          stages: ::Array[HubSpotSDK::Crm::PipelineStage],
          updated_at: Time,
          archived_at: Time
        }

      class Pipeline < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor archived: bool

        attr_accessor created_at: Time

        attr_accessor display_order: Integer

        attr_accessor label: String

        attr_accessor stages: ::Array[HubSpotSDK::Crm::PipelineStage]

        attr_accessor updated_at: Time

        attr_reader archived_at: Time?

        def archived_at=: (Time) -> Time

        def initialize: (
          id: String,
          archived: bool,
          created_at: Time,
          display_order: Integer,
          label: String,
          stages: ::Array[HubSpotSDK::Crm::PipelineStage],
          updated_at: Time,
          ?archived_at: Time
        ) -> void

        def to_hash: -> {
          id: String,
          archived: bool,
          created_at: Time,
          display_order: Integer,
          label: String,
          stages: ::Array[HubSpotSDK::Crm::PipelineStage],
          updated_at: Time,
          archived_at: Time
        }
      end
    end
  end
end
