module HubspotSDK
  module Models
    module CRM
      type portal_flag_state_put_request =
        {
          flag_state: HubspotSDK::Models::CRM::PortalFlagStatePutRequest::flag_state
        }

      class PortalFlagStatePutRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor flag_state: HubspotSDK::Models::CRM::PortalFlagStatePutRequest::flag_state

        def initialize: (
          flag_state: HubspotSDK::Models::CRM::PortalFlagStatePutRequest::flag_state
        ) -> void

        def to_hash: -> {
          flag_state: HubspotSDK::Models::CRM::PortalFlagStatePutRequest::flag_state
        }

        type flag_state = :OFF | :ON | :ABSENT

        module FlagState
          extend HubspotSDK::Internal::Type::Enum

          OFF: :OFF
          ON: :ON
          ABSENT: :ABSENT

          def self?.values: -> ::Array[HubspotSDK::Models::CRM::PortalFlagStatePutRequest::flag_state]
        end
      end
    end
  end
end
