module HubspotSDK
  module Models
    module CRM
      type property_group =
        { archived: bool, display_order: Integer, label: String, name: String }

      class PropertyGroup < HubspotSDK::Internal::Type::BaseModel
        attr_accessor archived: bool

        attr_accessor display_order: Integer

        attr_accessor label: String

        attr_accessor name: String

        def initialize: (
          archived: bool,
          display_order: Integer,
          label: String,
          name: String
        ) -> void

        def to_hash: -> {
          archived: bool,
          display_order: Integer,
          label: String,
          name: String
        }
      end
    end
  end
end
