module HubSpotSDK
  module Models
    module Crm
      type public_property_filter =
        {
          filter_type: HubSpotSDK::Models::Crm::PublicPropertyFilter::filter_type,
          operation: HubSpotSDK::Models::Crm::PublicPropertyFilter::operation,
          property: String
        }

      class PublicPropertyFilter < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor filter_type: HubSpotSDK::Models::Crm::PublicPropertyFilter::filter_type

        attr_accessor operation: HubSpotSDK::Models::Crm::PublicPropertyFilter::operation

        attr_accessor property: String

        def initialize: (
          filter_type: HubSpotSDK::Models::Crm::PublicPropertyFilter::filter_type,
          operation: HubSpotSDK::Models::Crm::PublicPropertyFilter::operation,
          property: String
        ) -> void

        def to_hash: -> {
          filter_type: HubSpotSDK::Models::Crm::PublicPropertyFilter::filter_type,
          operation: HubSpotSDK::Models::Crm::PublicPropertyFilter::operation,
          property: String
        }

        type filter_type = :PROPERTY

        module FilterType
          extend HubSpotSDK::Internal::Type::Enum

          PROPERTY: :PROPERTY

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::PublicPropertyFilter::filter_type]
        end

        type operation =
          HubSpotSDK::Crm::PublicBoolPropertyOperation
          | HubSpotSDK::Crm::PublicNumberPropertyOperation
          | HubSpotSDK::Crm::PublicStringPropertyOperation
          | HubSpotSDK::Crm::PublicDateTimePropertyOperation
          | HubSpotSDK::Crm::PublicRangedDatePropertyOperation
          | HubSpotSDK::Crm::PublicComparativePropertyUpdatedOperation
          | HubSpotSDK::Crm::PublicComparativeDatePropertyOperation
          | HubSpotSDK::Crm::PublicRollingDateRangePropertyOperation
          | HubSpotSDK::Crm::PublicRollingPropertyUpdatedOperation
          | HubSpotSDK::Crm::PublicEnumerationPropertyOperation
          | HubSpotSDK::Crm::PublicAllPropertyTypesOperation
          | HubSpotSDK::Crm::PublicRangedNumberPropertyOperation
          | HubSpotSDK::Crm::PublicMultiStringPropertyOperation
          | HubSpotSDK::Crm::PublicDatePropertyOperation
          | HubSpotSDK::Crm::PublicCalendarDatePropertyOperation
          | HubSpotSDK::Crm::PublicTimePointOperation
          | HubSpotSDK::Crm::PublicRangedTimeOperation

        module Operation
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Crm::PublicPropertyFilter::operation]
        end
      end
    end
  end
end
