module HubSpotSDK
  module Models
    module Crm
      type public_all_history_refine_by =
        { type: HubSpotSDK::Models::Crm::PublicAllHistoryRefineBy::type_ }

      class PublicAllHistoryRefineBy < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor type: HubSpotSDK::Models::Crm::PublicAllHistoryRefineBy::type_

        def initialize: (
          type: HubSpotSDK::Models::Crm::PublicAllHistoryRefineBy::type_
        ) -> void

        def to_hash: -> {
          type: HubSpotSDK::Models::Crm::PublicAllHistoryRefineBy::type_
        }

        type type_ = :ALL_HISTORY

        module Type
          extend HubSpotSDK::Internal::Type::Enum

          ALL_HISTORY: :ALL_HISTORY

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::PublicAllHistoryRefineBy::type_]
        end
      end
    end
  end
end
