module HubSpotSDK
  module Models
    module Crm
      type public_deal_splits_create_request =
        { id: Integer, splits: ::Array[HubSpotSDK::Crm::PublicDealSplitInput] }

      class PublicDealSplitsCreateRequest < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: Integer

        attr_accessor splits: ::Array[HubSpotSDK::Crm::PublicDealSplitInput]

        def initialize: (
          id: Integer,
          splits: ::Array[HubSpotSDK::Crm::PublicDealSplitInput]
        ) -> void

        def to_hash: -> {
          id: Integer,
          splits: ::Array[HubSpotSDK::Crm::PublicDealSplitInput]
        }
      end
    end
  end
end
