module HubSpotSDK
  module Models
    module Crm
      type public_integration_event_filter =
        {
          event_type_id: Integer,
          filter_lines: ::Array[HubSpotSDK::Crm::PublicEventFilterMetadata],
          filter_type: HubSpotSDK::Models::Crm::PublicIntegrationEventFilter::filter_type
        }

      class PublicIntegrationEventFilter < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor event_type_id: Integer

        attr_accessor filter_lines: ::Array[HubSpotSDK::Crm::PublicEventFilterMetadata]

        attr_accessor filter_type: HubSpotSDK::Models::Crm::PublicIntegrationEventFilter::filter_type

        def initialize: (
          event_type_id: Integer,
          filter_lines: ::Array[HubSpotSDK::Crm::PublicEventFilterMetadata],
          filter_type: HubSpotSDK::Models::Crm::PublicIntegrationEventFilter::filter_type
        ) -> void

        def to_hash: -> {
          event_type_id: Integer,
          filter_lines: ::Array[HubSpotSDK::Crm::PublicEventFilterMetadata],
          filter_type: HubSpotSDK::Models::Crm::PublicIntegrationEventFilter::filter_type
        }

        type filter_type = :INTEGRATION_EVENT

        module FilterType
          extend HubSpotSDK::Internal::Type::Enum

          INTEGRATION_EVENT: :INTEGRATION_EVENT

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::PublicIntegrationEventFilter::filter_type]
        end
      end
    end
  end
end
