module HubspotSDK
  module Models
    module Crm
      type public_association_multi =
        {
          from: HubspotSDK::PublicObjectID,
          to: ::Array[HubspotSDK::Crm::AssociatedID],
          paging: HubspotSDK::Marketing::EmailsPaging
        }

      class PublicAssociationMulti < HubspotSDK::Internal::Type::BaseModel
        attr_accessor from: HubspotSDK::PublicObjectID

        attr_accessor to: ::Array[HubspotSDK::Crm::AssociatedID]

        attr_reader paging: HubspotSDK::Marketing::EmailsPaging?

        def paging=: (
          HubspotSDK::Marketing::EmailsPaging
        ) -> HubspotSDK::Marketing::EmailsPaging

        def initialize: (
          from: HubspotSDK::PublicObjectID,
          to: ::Array[HubspotSDK::Crm::AssociatedID],
          ?paging: HubspotSDK::Marketing::EmailsPaging
        ) -> void

        def to_hash: -> {
          from: HubspotSDK::PublicObjectID,
          to: ::Array[HubspotSDK::Crm::AssociatedID],
          paging: HubspotSDK::Marketing::EmailsPaging
        }
      end
    end
  end
end
