module HubspotSDK
  module Models
    module Crm
      type public_gdpr_delete_input =
        { object_id_: String, id_property: String }

      class PublicGdprDeleteInput < HubspotSDK::Internal::Type::BaseModel
        attr_accessor object_id_: String

        attr_reader id_property: String?

        def id_property=: (String) -> String

        def initialize: (object_id_: String, ?id_property: String) -> void

        def to_hash: -> { object_id_: String, id_property: String }
      end
    end
  end
end
