module HubSpotSDK
  module Models
    module Crm
      type public_campaign_influenced_filter =
        {
          campaign_id: String,
          filter_type: HubSpotSDK::Models::Crm::PublicCampaignInfluencedFilter::filter_type
        }

      class PublicCampaignInfluencedFilter < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor campaign_id: String

        attr_accessor filter_type: HubSpotSDK::Models::Crm::PublicCampaignInfluencedFilter::filter_type

        def initialize: (
          campaign_id: String,
          filter_type: HubSpotSDK::Models::Crm::PublicCampaignInfluencedFilter::filter_type
        ) -> void

        def to_hash: -> {
          campaign_id: String,
          filter_type: HubSpotSDK::Models::Crm::PublicCampaignInfluencedFilter::filter_type
        }

        type filter_type = :CAMPAIGN_INFLUENCED

        module FilterType
          extend HubSpotSDK::Internal::Type::Enum

          CAMPAIGN_INFLUENCED: :CAMPAIGN_INFLUENCED

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::PublicCampaignInfluencedFilter::filter_type]
        end
      end
    end
  end
end
