module HubspotSDK
  module Models
    module Crm
      type public_ads_search_filter =
        {
          ad_network: String,
          entity_type: String,
          filter_type: HubspotSDK::Models::Crm::PublicAdsSearchFilter::filter_type,
          operator: String,
          search_terms: ::Array[String],
          search_term_type: String
        }

      class PublicAdsSearchFilter < HubspotSDK::Internal::Type::BaseModel
        attr_accessor ad_network: String

        attr_accessor entity_type: String

        attr_accessor filter_type: HubspotSDK::Models::Crm::PublicAdsSearchFilter::filter_type

        attr_accessor operator: String

        attr_accessor search_terms: ::Array[String]

        attr_accessor search_term_type: String

        def initialize: (
          ad_network: String,
          entity_type: String,
          filter_type: HubspotSDK::Models::Crm::PublicAdsSearchFilter::filter_type,
          operator: String,
          search_terms: ::Array[String],
          search_term_type: String
        ) -> void

        def to_hash: -> {
          ad_network: String,
          entity_type: String,
          filter_type: HubspotSDK::Models::Crm::PublicAdsSearchFilter::filter_type,
          operator: String,
          search_terms: ::Array[String],
          search_term_type: String
        }

        type filter_type = :ADS_SEARCH

        module FilterType
          extend HubspotSDK::Internal::Type::Enum

          ADS_SEARCH: :ADS_SEARCH

          def self?.values: -> ::Array[HubspotSDK::Models::Crm::PublicAdsSearchFilter::filter_type]
        end
      end
    end
  end
end
