module HubSpotSDK
  module Models
    module Crm
      type public_association_multi_post =
        {
          from: HubSpotSDK::PublicObjectID,
          to: HubSpotSDK::PublicObjectID,
          types: ::Array[HubSpotSDK::AssociationSpec]
        }

      class PublicAssociationMultiPost < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor from: HubSpotSDK::PublicObjectID

        attr_accessor to: HubSpotSDK::PublicObjectID

        attr_accessor types: ::Array[HubSpotSDK::AssociationSpec]

        def initialize: (
          from: HubSpotSDK::PublicObjectID,
          to: HubSpotSDK::PublicObjectID,
          types: ::Array[HubSpotSDK::AssociationSpec]
        ) -> void

        def to_hash: -> {
          from: HubSpotSDK::PublicObjectID,
          to: HubSpotSDK::PublicObjectID,
          types: ::Array[HubSpotSDK::AssociationSpec]
        }
      end
    end
  end
end
