module HubspotSDK
  module Models
    module CRM
      type public_audit_info =
        {
          action: String,
          identifier: String,
          portal_id: Integer,
          from_user_id: Integer,
          message: String,
          raw_object: top,
          timestamp: Time
        }

      class PublicAuditInfo < HubspotSDK::Internal::Type::BaseModel
        attr_accessor action: String

        attr_accessor identifier: String

        attr_accessor portal_id: Integer

        attr_reader from_user_id: Integer?

        def from_user_id=: (Integer) -> Integer

        attr_reader message: String?

        def message=: (String) -> String

        attr_reader raw_object: top?

        def raw_object=: (top) -> top

        attr_reader timestamp: Time?

        def timestamp=: (Time) -> Time

        def initialize: (
          action: String,
          identifier: String,
          portal_id: Integer,
          ?from_user_id: Integer,
          ?message: String,
          ?raw_object: top,
          ?timestamp: Time
        ) -> void

        def to_hash: -> {
          action: String,
          identifier: String,
          portal_id: Integer,
          from_user_id: Integer,
          message: String,
          raw_object: top,
          timestamp: Time
        }
      end
    end
  end
end
