module HubSpotSDK
  module Models
    module Crm
      type public_default_association =
        {
          association_spec: HubSpotSDK::AssociationSpec,
          from: HubSpotSDK::PublicObjectID,
          to: HubSpotSDK::PublicObjectID
        }

      class PublicDefaultAssociation < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor association_spec: HubSpotSDK::AssociationSpec

        attr_accessor from: HubSpotSDK::PublicObjectID

        attr_accessor to: HubSpotSDK::PublicObjectID

        def initialize: (
          association_spec: HubSpotSDK::AssociationSpec,
          from: HubSpotSDK::PublicObjectID,
          to: HubSpotSDK::PublicObjectID
        ) -> void

        def to_hash: -> {
          association_spec: HubSpotSDK::AssociationSpec,
          from: HubSpotSDK::PublicObjectID,
          to: HubSpotSDK::PublicObjectID
        }
      end
    end
  end
end
