module HubspotSDK
  module Models
    module Crm
      type public_webinar_filter =
        {
          filter_type: HubspotSDK::Models::Crm::PublicWebinarFilter::filter_type,
          operator: String,
          webinar_id: String
        }

      class PublicWebinarFilter < HubspotSDK::Internal::Type::BaseModel
        attr_accessor filter_type: HubspotSDK::Models::Crm::PublicWebinarFilter::filter_type

        attr_accessor operator: String

        attr_reader webinar_id: String?

        def webinar_id=: (String) -> String

        def initialize: (
          filter_type: HubspotSDK::Models::Crm::PublicWebinarFilter::filter_type,
          operator: String,
          ?webinar_id: String
        ) -> void

        def to_hash: -> {
          filter_type: HubspotSDK::Models::Crm::PublicWebinarFilter::filter_type,
          operator: String,
          webinar_id: String
        }

        type filter_type = :WEBINAR

        module FilterType
          extend HubspotSDK::Internal::Type::Enum

          WEBINAR: :WEBINAR

          def self?.values: -> ::Array[HubspotSDK::Models::Crm::PublicWebinarFilter::filter_type]
        end
      end
    end
  end
end
