module HubSpotSDK
  module Models
    module Crm
      type public_unified_events_filter =
        {
          filter_lines: ::Array[HubSpotSDK::Crm::PublicEventFilterMetadata],
          filter_type: HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::filter_type,
          coalescing_refine_by: HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::coalescing_refine_by,
          event_type_id: String,
          pruning_refine_by: HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::pruning_refine_by
        }

      class PublicUnifiedEventsFilter < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor filter_lines: ::Array[HubSpotSDK::Crm::PublicEventFilterMetadata]

        attr_accessor filter_type: HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::filter_type

        attr_reader coalescing_refine_by: HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::coalescing_refine_by?

        def coalescing_refine_by=: (
          HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::coalescing_refine_by
        ) -> HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::coalescing_refine_by

        attr_reader event_type_id: String?

        def event_type_id=: (String) -> String

        attr_reader pruning_refine_by: HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::pruning_refine_by?

        def pruning_refine_by=: (
          HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::pruning_refine_by
        ) -> HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::pruning_refine_by

        def initialize: (
          filter_lines: ::Array[HubSpotSDK::Crm::PublicEventFilterMetadata],
          filter_type: HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::filter_type,
          ?coalescing_refine_by: HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::coalescing_refine_by,
          ?event_type_id: String,
          ?pruning_refine_by: HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::pruning_refine_by
        ) -> void

        def to_hash: -> {
          filter_lines: ::Array[HubSpotSDK::Crm::PublicEventFilterMetadata],
          filter_type: HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::filter_type,
          coalescing_refine_by: HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::coalescing_refine_by,
          event_type_id: String,
          pruning_refine_by: HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::pruning_refine_by
        }

        type filter_type = :UNIFIED_EVENTS

        module FilterType
          extend HubSpotSDK::Internal::Type::Enum

          UNIFIED_EVENTS: :UNIFIED_EVENTS

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::filter_type]
        end

        type coalescing_refine_by =
          HubSpotSDK::Crm::PublicNumOccurrencesRefineBy
          | HubSpotSDK::Crm::PublicSetOccurrencesRefineBy
          | HubSpotSDK::Crm::PublicRelativeComparativeTimestampRefineBy
          | HubSpotSDK::Crm::PublicRelativeRangedTimestampRefineBy
          | HubSpotSDK::Crm::PublicAbsoluteComparativeTimestampRefineBy
          | HubSpotSDK::Crm::PublicAbsoluteRangedTimestampRefineBy
          | HubSpotSDK::Crm::PublicAllHistoryRefineBy
          | HubSpotSDK::Crm::PublicTimePointOperation
          | HubSpotSDK::Crm::PublicRangedTimeOperation

        module CoalescingRefineBy
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::coalescing_refine_by]
        end

        type pruning_refine_by =
          HubSpotSDK::Crm::PublicNumOccurrencesRefineBy
          | HubSpotSDK::Crm::PublicSetOccurrencesRefineBy
          | HubSpotSDK::Crm::PublicRelativeComparativeTimestampRefineBy
          | HubSpotSDK::Crm::PublicRelativeRangedTimestampRefineBy
          | HubSpotSDK::Crm::PublicAbsoluteComparativeTimestampRefineBy
          | HubSpotSDK::Crm::PublicAbsoluteRangedTimestampRefineBy
          | HubSpotSDK::Crm::PublicAllHistoryRefineBy
          | HubSpotSDK::Crm::PublicTimePointOperation
          | HubSpotSDK::Crm::PublicRangedTimeOperation

        module PruningRefineBy
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Crm::PublicUnifiedEventsFilter::pruning_refine_by]
        end
      end
    end
  end
end
