module HubspotSDK
  module Models
    module Crm
      type public_quarter_reference =
        {
          day: Integer,
          month: Integer,
          reference_type: HubspotSDK::Models::Crm::PublicQuarterReference::reference_type,
          hour: Integer,
          millisecond: Integer,
          minute: Integer,
          second: Integer
        }

      class PublicQuarterReference < HubspotSDK::Internal::Type::BaseModel
        attr_accessor day: Integer

        attr_accessor month: Integer

        attr_accessor reference_type: HubspotSDK::Models::Crm::PublicQuarterReference::reference_type

        attr_reader hour: Integer?

        def hour=: (Integer) -> Integer

        attr_reader millisecond: Integer?

        def millisecond=: (Integer) -> Integer

        attr_reader minute: Integer?

        def minute=: (Integer) -> Integer

        attr_reader second: Integer?

        def second=: (Integer) -> Integer

        def initialize: (
          day: Integer,
          month: Integer,
          reference_type: HubspotSDK::Models::Crm::PublicQuarterReference::reference_type,
          ?hour: Integer,
          ?millisecond: Integer,
          ?minute: Integer,
          ?second: Integer
        ) -> void

        def to_hash: -> {
          day: Integer,
          month: Integer,
          reference_type: HubspotSDK::Models::Crm::PublicQuarterReference::reference_type,
          hour: Integer,
          millisecond: Integer,
          minute: Integer,
          second: Integer
        }

        type reference_type = :QUARTER

        module ReferenceType
          extend HubspotSDK::Internal::Type::Enum

          QUARTER: :QUARTER

          def self?.values: -> ::Array[HubspotSDK::Models::Crm::PublicQuarterReference::reference_type]
        end
      end
    end
  end
end
