module HubspotSDK
  module Models
    module Crm
      type public_unified_events_filter =
        {
          filter_lines: ::Array[HubspotSDK::Crm::PublicEventFilterMetadata],
          filter_type: HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::filter_type,
          coalescing_refine_by: HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::coalescing_refine_by,
          event_type_id: String,
          pruning_refine_by: HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::pruning_refine_by
        }

      class PublicUnifiedEventsFilter < HubspotSDK::Internal::Type::BaseModel
        attr_accessor filter_lines: ::Array[HubspotSDK::Crm::PublicEventFilterMetadata]

        attr_accessor filter_type: HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::filter_type

        attr_reader coalescing_refine_by: HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::coalescing_refine_by?

        def coalescing_refine_by=: (
          HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::coalescing_refine_by
        ) -> HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::coalescing_refine_by

        attr_reader event_type_id: String?

        def event_type_id=: (String) -> String

        attr_reader pruning_refine_by: HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::pruning_refine_by?

        def pruning_refine_by=: (
          HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::pruning_refine_by
        ) -> HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::pruning_refine_by

        def initialize: (
          filter_lines: ::Array[HubspotSDK::Crm::PublicEventFilterMetadata],
          filter_type: HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::filter_type,
          ?coalescing_refine_by: HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::coalescing_refine_by,
          ?event_type_id: String,
          ?pruning_refine_by: HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::pruning_refine_by
        ) -> void

        def to_hash: -> {
          filter_lines: ::Array[HubspotSDK::Crm::PublicEventFilterMetadata],
          filter_type: HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::filter_type,
          coalescing_refine_by: HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::coalescing_refine_by,
          event_type_id: String,
          pruning_refine_by: HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::pruning_refine_by
        }

        type filter_type = :UNIFIED_EVENTS

        module FilterType
          extend HubspotSDK::Internal::Type::Enum

          UNIFIED_EVENTS: :UNIFIED_EVENTS

          def self?.values: -> ::Array[HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::filter_type]
        end

        type coalescing_refine_by =
          HubspotSDK::Crm::PublicNumOccurrencesRefineBy
          | HubspotSDK::Crm::PublicSetOccurrencesRefineBy
          | HubspotSDK::Crm::PublicRelativeComparativeTimestampRefineBy
          | HubspotSDK::Crm::PublicRelativeRangedTimestampRefineBy
          | HubspotSDK::Crm::PublicAbsoluteComparativeTimestampRefineBy
          | HubspotSDK::Crm::PublicAbsoluteRangedTimestampRefineBy
          | HubspotSDK::Crm::PublicAllHistoryRefineBy
          | HubspotSDK::Crm::PublicTimePointOperation
          | HubspotSDK::Crm::PublicRangedTimeOperation

        module CoalescingRefineBy
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::coalescing_refine_by]
        end

        type pruning_refine_by =
          HubspotSDK::Crm::PublicNumOccurrencesRefineBy
          | HubspotSDK::Crm::PublicSetOccurrencesRefineBy
          | HubspotSDK::Crm::PublicRelativeComparativeTimestampRefineBy
          | HubspotSDK::Crm::PublicRelativeRangedTimestampRefineBy
          | HubspotSDK::Crm::PublicAbsoluteComparativeTimestampRefineBy
          | HubspotSDK::Crm::PublicAbsoluteRangedTimestampRefineBy
          | HubspotSDK::Crm::PublicAllHistoryRefineBy
          | HubspotSDK::Crm::PublicTimePointOperation
          | HubspotSDK::Crm::PublicRangedTimeOperation

        module PruningRefineBy
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Crm::PublicUnifiedEventsFilter::pruning_refine_by]
        end
      end
    end
  end
end
