module HubspotSDK
  module Models
    module CRM
      type public_owner =
        {
          id: String,
          archived: bool,
          created_at: Time,
          type: HubspotSDK::Models::CRM::PublicOwner::type_,
          updated_at: Time,
          email: String,
          first_name: String,
          last_name: String,
          teams: ::Array[HubspotSDK::Settings::PublicTeam],
          user_id: Integer,
          user_id_including_inactive: Integer
        }

      class PublicOwner < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor archived: bool

        attr_accessor created_at: Time

        attr_accessor type: HubspotSDK::Models::CRM::PublicOwner::type_

        attr_accessor updated_at: Time

        attr_reader email: String?

        def email=: (String) -> String

        attr_reader first_name: String?

        def first_name=: (String) -> String

        attr_reader last_name: String?

        def last_name=: (String) -> String

        attr_reader teams: ::Array[HubspotSDK::Settings::PublicTeam]?

        def teams=: (
          ::Array[HubspotSDK::Settings::PublicTeam]
        ) -> ::Array[HubspotSDK::Settings::PublicTeam]

        attr_reader user_id: Integer?

        def user_id=: (Integer) -> Integer

        attr_reader user_id_including_inactive: Integer?

        def user_id_including_inactive=: (Integer) -> Integer

        def initialize: (
          id: String,
          archived: bool,
          created_at: Time,
          type: HubspotSDK::Models::CRM::PublicOwner::type_,
          updated_at: Time,
          ?email: String,
          ?first_name: String,
          ?last_name: String,
          ?teams: ::Array[HubspotSDK::Settings::PublicTeam],
          ?user_id: Integer,
          ?user_id_including_inactive: Integer
        ) -> void

        def to_hash: -> {
          id: String,
          archived: bool,
          created_at: Time,
          type: HubspotSDK::Models::CRM::PublicOwner::type_,
          updated_at: Time,
          email: String,
          first_name: String,
          last_name: String,
          teams: ::Array[HubspotSDK::Settings::PublicTeam],
          user_id: Integer,
          user_id_including_inactive: Integer
        }

        type type_ = :PERSON | :QUEUE

        module Type
          extend HubspotSDK::Internal::Type::Enum

          PERSON: :PERSON
          QUEUE: :QUEUE

          def self?.values: -> ::Array[HubspotSDK::Models::CRM::PublicOwner::type_]
        end
      end
    end
  end
end
