module HubspotSDK
  module Models
    module Crm
      type public_cta_analytics_filter =
        {
          cta_name: String,
          filter_type: HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::filter_type,
          operator: String,
          coalescing_refine_by: HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::coalescing_refine_by,
          pruning_refine_by: HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::pruning_refine_by
        }

      class PublicCtaAnalyticsFilter < HubspotSDK::Internal::Type::BaseModel
        attr_accessor cta_name: String

        attr_accessor filter_type: HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::filter_type

        attr_accessor operator: String

        attr_reader coalescing_refine_by: HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::coalescing_refine_by?

        def coalescing_refine_by=: (
          HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::coalescing_refine_by
        ) -> HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::coalescing_refine_by

        attr_reader pruning_refine_by: HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::pruning_refine_by?

        def pruning_refine_by=: (
          HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::pruning_refine_by
        ) -> HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::pruning_refine_by

        def initialize: (
          cta_name: String,
          filter_type: HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::filter_type,
          operator: String,
          ?coalescing_refine_by: HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::coalescing_refine_by,
          ?pruning_refine_by: HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::pruning_refine_by
        ) -> void

        def to_hash: -> {
          cta_name: String,
          filter_type: HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::filter_type,
          operator: String,
          coalescing_refine_by: HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::coalescing_refine_by,
          pruning_refine_by: HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::pruning_refine_by
        }

        type filter_type = :CTA

        module FilterType
          extend HubspotSDK::Internal::Type::Enum

          CTA: :CTA

          def self?.values: -> ::Array[HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::filter_type]
        end

        type coalescing_refine_by =
          HubspotSDK::Crm::PublicNumOccurrencesRefineBy
          | HubspotSDK::Crm::PublicSetOccurrencesRefineBy
          | HubspotSDK::Crm::PublicRelativeComparativeTimestampRefineBy
          | HubspotSDK::Crm::PublicRelativeRangedTimestampRefineBy
          | HubspotSDK::Crm::PublicAbsoluteComparativeTimestampRefineBy
          | HubspotSDK::Crm::PublicAbsoluteRangedTimestampRefineBy
          | HubspotSDK::Crm::PublicAllHistoryRefineBy
          | HubspotSDK::Crm::PublicTimePointOperation
          | HubspotSDK::Crm::PublicRangedTimeOperation

        module CoalescingRefineBy
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::coalescing_refine_by]
        end

        type pruning_refine_by =
          HubspotSDK::Crm::PublicNumOccurrencesRefineBy
          | HubspotSDK::Crm::PublicSetOccurrencesRefineBy
          | HubspotSDK::Crm::PublicRelativeComparativeTimestampRefineBy
          | HubspotSDK::Crm::PublicRelativeRangedTimestampRefineBy
          | HubspotSDK::Crm::PublicAbsoluteComparativeTimestampRefineBy
          | HubspotSDK::Crm::PublicAbsoluteRangedTimestampRefineBy
          | HubspotSDK::Crm::PublicAllHistoryRefineBy
          | HubspotSDK::Crm::PublicTimePointOperation
          | HubspotSDK::Crm::PublicRangedTimeOperation

        module PruningRefineBy
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Crm::PublicCtaAnalyticsFilter::pruning_refine_by]
        end
      end
    end
  end
end
