module HubspotSDK
  module Models
    module Crm
      type public_crm_search_request =
        {
          filters: ::Array[HubspotSDK::Crm::Filter],
          query: String,
          sorts: ::Array[String]
        }

      class PublicCrmSearchRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor filters: ::Array[HubspotSDK::Crm::Filter]

        attr_accessor query: String

        attr_accessor sorts: ::Array[String]

        def initialize: (
          filters: ::Array[HubspotSDK::Crm::Filter],
          query: String,
          sorts: ::Array[String]
        ) -> void

        def to_hash: -> {
          filters: ::Array[HubspotSDK::Crm::Filter],
          query: String,
          sorts: ::Array[String]
        }
      end
    end
  end
end
