module HubSpotSDK
  module Models
    module Crm
      type public_survey_monkey_value_filter =
        {
          filter_type: HubSpotSDK::Models::Crm::PublicSurveyMonkeyValueFilter::filter_type,
          operator: String,
          survey_id: String,
          survey_question: String,
          value_comparison: HubSpotSDK::Models::Crm::PublicSurveyMonkeyValueFilter::value_comparison,
          survey_answer_col_id: String,
          survey_answer_row_id: String
        }

      class PublicSurveyMonkeyValueFilter < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor filter_type: HubSpotSDK::Models::Crm::PublicSurveyMonkeyValueFilter::filter_type

        attr_accessor operator: String

        attr_accessor survey_id: String

        attr_accessor survey_question: String

        attr_accessor value_comparison: HubSpotSDK::Models::Crm::PublicSurveyMonkeyValueFilter::value_comparison

        attr_reader survey_answer_col_id: String?

        def survey_answer_col_id=: (String) -> String

        attr_reader survey_answer_row_id: String?

        def survey_answer_row_id=: (String) -> String

        def initialize: (
          filter_type: HubSpotSDK::Models::Crm::PublicSurveyMonkeyValueFilter::filter_type,
          operator: String,
          survey_id: String,
          survey_question: String,
          value_comparison: HubSpotSDK::Models::Crm::PublicSurveyMonkeyValueFilter::value_comparison,
          ?survey_answer_col_id: String,
          ?survey_answer_row_id: String
        ) -> void

        def to_hash: -> {
          filter_type: HubSpotSDK::Models::Crm::PublicSurveyMonkeyValueFilter::filter_type,
          operator: String,
          survey_id: String,
          survey_question: String,
          value_comparison: HubSpotSDK::Models::Crm::PublicSurveyMonkeyValueFilter::value_comparison,
          survey_answer_col_id: String,
          survey_answer_row_id: String
        }

        type filter_type = :SURVEY_MONKEY_VALUE

        module FilterType
          extend HubSpotSDK::Internal::Type::Enum

          SURVEY_MONKEY_VALUE: :SURVEY_MONKEY_VALUE

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::PublicSurveyMonkeyValueFilter::filter_type]
        end

        type value_comparison =
          HubSpotSDK::Crm::PublicBoolPropertyOperation
          | HubSpotSDK::Crm::PublicNumberPropertyOperation
          | HubSpotSDK::Crm::PublicStringPropertyOperation
          | HubSpotSDK::Crm::PublicDateTimePropertyOperation
          | HubSpotSDK::Crm::PublicRangedDatePropertyOperation
          | HubSpotSDK::Crm::PublicComparativePropertyUpdatedOperation
          | HubSpotSDK::Crm::PublicComparativeDatePropertyOperation
          | HubSpotSDK::Crm::PublicRollingDateRangePropertyOperation
          | HubSpotSDK::Crm::PublicRollingPropertyUpdatedOperation
          | HubSpotSDK::Crm::PublicEnumerationPropertyOperation
          | HubSpotSDK::Crm::PublicAllPropertyTypesOperation
          | HubSpotSDK::Crm::PublicRangedNumberPropertyOperation
          | HubSpotSDK::Crm::PublicMultiStringPropertyOperation
          | HubSpotSDK::Crm::PublicDatePropertyOperation
          | HubSpotSDK::Crm::PublicCalendarDatePropertyOperation
          | HubSpotSDK::Crm::PublicTimePointOperation
          | HubSpotSDK::Crm::PublicRangedTimeOperation

        module ValueComparison
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Crm::PublicSurveyMonkeyValueFilter::value_comparison]
        end
      end
    end
  end
end
