module HubSpotSDK
  module Models
    module Crm
      type public_in_list_filter_metadata = { id: String, in_list_type: String }

      class PublicInListFilterMetadata < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor in_list_type: String

        def initialize: (id: String, in_list_type: String) -> void

        def to_hash: -> { id: String, in_list_type: String }
      end
    end
  end
end
