module HubspotSDK
  module Models
    module Crm
      type public_property_validation_rule_update =
        { rule_arguments: ::Array[String], should_apply_normalization: bool }

      class PublicPropertyValidationRuleUpdate < HubspotSDK::Internal::Type::BaseModel
        attr_accessor rule_arguments: ::Array[String]

        attr_reader should_apply_normalization: bool?

        def should_apply_normalization=: (bool) -> bool

        def initialize: (
          rule_arguments: ::Array[String],
          ?should_apply_normalization: bool
        ) -> void

        def to_hash: -> {
          rule_arguments: ::Array[String],
          should_apply_normalization: bool
        }
      end
    end
  end
end
