module HubspotSDK
  module Models
    module Crm
      type public_string_property_operation =
        {
          include_objects_with_no_value_set: bool,
          operation_type: HubspotSDK::Models::Crm::PublicStringPropertyOperation::operation_type,
          operator: String,
          value: String
        }

      class PublicStringPropertyOperation < HubspotSDK::Internal::Type::BaseModel
        attr_accessor include_objects_with_no_value_set: bool

        attr_accessor operation_type: HubspotSDK::Models::Crm::PublicStringPropertyOperation::operation_type

        attr_accessor operator: String

        attr_accessor value: String

        def initialize: (
          include_objects_with_no_value_set: bool,
          operation_type: HubspotSDK::Models::Crm::PublicStringPropertyOperation::operation_type,
          operator: String,
          value: String
        ) -> void

        def to_hash: -> {
          include_objects_with_no_value_set: bool,
          operation_type: HubspotSDK::Models::Crm::PublicStringPropertyOperation::operation_type,
          operator: String,
          value: String
        }

        type operation_type = :STRING

        module OperationType
          extend HubspotSDK::Internal::Type::Enum

          STRING: :STRING

          def self?.values: -> ::Array[HubspotSDK::Models::Crm::PublicStringPropertyOperation::operation_type]
        end
      end
    end
  end
end
