module HubspotSDK
  module Models
    module Crm
      type public_property_validation_rule =
        { rule_arguments: ::Array[String], rule_type: String }

      class PublicPropertyValidationRule < HubspotSDK::Internal::Type::BaseModel
        attr_accessor rule_arguments: ::Array[String]

        attr_accessor rule_type: String

        def initialize: (
          rule_arguments: ::Array[String],
          rule_type: String
        ) -> void

        def to_hash: -> { rule_arguments: ::Array[String], rule_type: String }
      end
    end
  end
end
