module HubSpotSDK
  module Models
    module Crm
      type public_association_multi_archive =
        {
          from: HubSpotSDK::PublicObjectID,
          to: ::Array[HubSpotSDK::PublicObjectID]
        }

      class PublicAssociationMultiArchive < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor from: HubSpotSDK::PublicObjectID

        attr_accessor to: ::Array[HubSpotSDK::PublicObjectID]

        def initialize: (
          from: HubSpotSDK::PublicObjectID,
          to: ::Array[HubSpotSDK::PublicObjectID]
        ) -> void

        def to_hash: -> {
          from: HubSpotSDK::PublicObjectID,
          to: ::Array[HubSpotSDK::PublicObjectID]
        }
      end
    end
  end
end
