module HubSpotSDK
  module Models
    module Crm
      type public_property_association_filter_branch =
        {
          filter_branches: ::Array[HubSpotSDK::Models::Crm::PublicPropertyAssociationFilterBranch::filter_branch],
          filter_branch_operator: String,
          filter_branch_type: HubSpotSDK::Models::Crm::PublicPropertyAssociationFilterBranch::filter_branch_type,
          filters: ::Array[HubSpotSDK::Models::Crm::PublicPropertyAssociationFilterBranch::filter],
          object_type_id: String,
          operator: String,
          property_with_object_id: String
        }

      class PublicPropertyAssociationFilterBranch < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor filter_branches: ::Array[HubSpotSDK::Models::Crm::PublicPropertyAssociationFilterBranch::filter_branch]

        attr_accessor filter_branch_operator: String

        attr_accessor filter_branch_type: HubSpotSDK::Models::Crm::PublicPropertyAssociationFilterBranch::filter_branch_type

        attr_accessor filters: ::Array[HubSpotSDK::Models::Crm::PublicPropertyAssociationFilterBranch::filter]

        attr_accessor object_type_id: String

        attr_accessor operator: String

        attr_accessor property_with_object_id: String

        def initialize: (
          filter_branches: ::Array[HubSpotSDK::Models::Crm::PublicPropertyAssociationFilterBranch::filter_branch],
          filter_branch_operator: String,
          filter_branch_type: HubSpotSDK::Models::Crm::PublicPropertyAssociationFilterBranch::filter_branch_type,
          filters: ::Array[HubSpotSDK::Models::Crm::PublicPropertyAssociationFilterBranch::filter],
          object_type_id: String,
          operator: String,
          property_with_object_id: String
        ) -> void

        def to_hash: -> {
          filter_branches: ::Array[HubSpotSDK::Models::Crm::PublicPropertyAssociationFilterBranch::filter_branch],
          filter_branch_operator: String,
          filter_branch_type: HubSpotSDK::Models::Crm::PublicPropertyAssociationFilterBranch::filter_branch_type,
          filters: ::Array[HubSpotSDK::Models::Crm::PublicPropertyAssociationFilterBranch::filter],
          object_type_id: String,
          operator: String,
          property_with_object_id: String
        }

        type filter_branch =
          HubSpotSDK::Crm::PublicOrFilterBranch
          | HubSpotSDK::Crm::PublicAndFilterBranch
          | HubSpotSDK::Crm::PublicNotAllFilterBranch
          | HubSpotSDK::Crm::PublicNotAnyFilterBranch
          | HubSpotSDK::Crm::PublicRestrictedFilterBranch
          | HubSpotSDK::Crm::PublicUnifiedEventsFilterBranch
          | HubSpotSDK::Crm::PublicPropertyAssociationFilterBranch
          | HubSpotSDK::Crm::PublicAssociationFilterBranch

        module FilterBranch
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Crm::PublicPropertyAssociationFilterBranch::filter_branch]
        end

        type filter_branch_type = :PROPERTY_ASSOCIATION

        module FilterBranchType
          extend HubSpotSDK::Internal::Type::Enum

          PROPERTY_ASSOCIATION: :PROPERTY_ASSOCIATION

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::PublicPropertyAssociationFilterBranch::filter_branch_type]
        end

        type filter =
          HubSpotSDK::Crm::PublicPropertyFilter
          | HubSpotSDK::Crm::PublicAssociationInListFilter
          | HubSpotSDK::Crm::PublicPageViewAnalyticsFilter
          | HubSpotSDK::Crm::PublicCtaAnalyticsFilter
          | HubSpotSDK::Crm::PublicEventAnalyticsFilter
          | HubSpotSDK::Crm::PublicFormSubmissionFilter
          | HubSpotSDK::Crm::PublicFormSubmissionOnPageFilter
          | HubSpotSDK::Crm::PublicIntegrationEventFilter
          | HubSpotSDK::Crm::PublicEmailSubscriptionFilter
          | HubSpotSDK::Crm::PublicCommunicationSubscriptionFilter
          | HubSpotSDK::Crm::PublicCampaignInfluencedFilter
          | HubSpotSDK::Crm::PublicSurveyMonkeyFilter
          | HubSpotSDK::Crm::PublicSurveyMonkeyValueFilter
          | HubSpotSDK::Crm::PublicWebinarFilter
          | HubSpotSDK::Crm::PublicEmailEventFilter
          | HubSpotSDK::Crm::PublicPrivacyAnalyticsFilter
          | HubSpotSDK::Crm::PublicAdsSearchFilter
          | HubSpotSDK::Crm::PublicAdsTimeFilter
          | HubSpotSDK::Crm::PublicInListFilter
          | HubSpotSDK::Crm::PublicNumAssociationsFilter
          | HubSpotSDK::Crm::PublicUnifiedEventsFilter
          | HubSpotSDK::Crm::PublicPropertyAssociationInListFilter
          | HubSpotSDK::Crm::PublicConstantFilter

        module Filter
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Crm::PublicPropertyAssociationFilterBranch::filter]
        end
      end
    end
  end
end
