module HubSpotSDK
  module Models
    module Crm
      type public_association_multi_with_label =
        {
          from: HubSpotSDK::PublicObjectID,
          to: ::Array[HubSpotSDK::Crm::MultiAssociatedObjectWithLabel],
          paging: HubSpotSDK::Paging
        }

      class PublicAssociationMultiWithLabel < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor from: HubSpotSDK::PublicObjectID

        attr_accessor to: ::Array[HubSpotSDK::Crm::MultiAssociatedObjectWithLabel]

        attr_reader paging: HubSpotSDK::Paging?

        def paging=: (HubSpotSDK::Paging) -> HubSpotSDK::Paging

        def initialize: (
          from: HubSpotSDK::PublicObjectID,
          to: ::Array[HubSpotSDK::Crm::MultiAssociatedObjectWithLabel],
          ?paging: HubSpotSDK::Paging
        ) -> void

        def to_hash: -> {
          from: HubSpotSDK::PublicObjectID,
          to: ::Array[HubSpotSDK::Crm::MultiAssociatedObjectWithLabel],
          paging: HubSpotSDK::Paging
        }
      end
    end
  end
end
