module HubspotSDK
  module Models
    module Crm
      type public_list_conversion_time =
        HubspotSDK::Crm::PublicListConversionDate
        | HubspotSDK::Crm::PublicListConversionInactivity

      module PublicListConversionTime
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::Crm::public_list_conversion_time]
      end
    end
  end
end
