module HubspotSDK
  module Models
    module Crm
      type public_export_request =
        HubspotSDK::Crm::PublicExportViewRequest
        | HubspotSDK::Crm::PublicExportListRequest

      module PublicExportRequest
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::Crm::public_export_request]
      end
    end
  end
end
