module HubSpotSDK
  module Models
    module Crm
      type public_num_occurrences_refine_by =
        {
          type: HubSpotSDK::Models::Crm::PublicNumOccurrencesRefineBy::type_,
          max_occurrences: Integer,
          min_occurrences: Integer
        }

      class PublicNumOccurrencesRefineBy < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor type: HubSpotSDK::Models::Crm::PublicNumOccurrencesRefineBy::type_

        attr_reader max_occurrences: Integer?

        def max_occurrences=: (Integer) -> Integer

        attr_reader min_occurrences: Integer?

        def min_occurrences=: (Integer) -> Integer

        def initialize: (
          type: HubSpotSDK::Models::Crm::PublicNumOccurrencesRefineBy::type_,
          ?max_occurrences: Integer,
          ?min_occurrences: Integer
        ) -> void

        def to_hash: -> {
          type: HubSpotSDK::Models::Crm::PublicNumOccurrencesRefineBy::type_,
          max_occurrences: Integer,
          min_occurrences: Integer
        }

        type type_ = :NUM_OCCURRENCES

        module Type
          extend HubSpotSDK::Internal::Type::Enum

          NUM_OCCURRENCES: :NUM_OCCURRENCES

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::PublicNumOccurrencesRefineBy::type_]
        end
      end
    end
  end
end
