module HubspotSDK
  module Models
    module Crm
      type public_ads_time_filter =
        {
          filter_type: HubspotSDK::Models::Crm::PublicAdsTimeFilter::filter_type,
          pruning_refine_by: HubspotSDK::Models::Crm::PublicAdsTimeFilter::pruning_refine_by
        }

      class PublicAdsTimeFilter < HubspotSDK::Internal::Type::BaseModel
        attr_accessor filter_type: HubspotSDK::Models::Crm::PublicAdsTimeFilter::filter_type

        attr_accessor pruning_refine_by: HubspotSDK::Models::Crm::PublicAdsTimeFilter::pruning_refine_by

        def initialize: (
          filter_type: HubspotSDK::Models::Crm::PublicAdsTimeFilter::filter_type,
          pruning_refine_by: HubspotSDK::Models::Crm::PublicAdsTimeFilter::pruning_refine_by
        ) -> void

        def to_hash: -> {
          filter_type: HubspotSDK::Models::Crm::PublicAdsTimeFilter::filter_type,
          pruning_refine_by: HubspotSDK::Models::Crm::PublicAdsTimeFilter::pruning_refine_by
        }

        type filter_type = :ADS_TIME

        module FilterType
          extend HubspotSDK::Internal::Type::Enum

          ADS_TIME: :ADS_TIME

          def self?.values: -> ::Array[HubspotSDK::Models::Crm::PublicAdsTimeFilter::filter_type]
        end

        type pruning_refine_by =
          HubspotSDK::Crm::PublicNumOccurrencesRefineBy
          | HubspotSDK::Crm::PublicSetOccurrencesRefineBy
          | HubspotSDK::Crm::PublicRelativeComparativeTimestampRefineBy
          | HubspotSDK::Crm::PublicRelativeRangedTimestampRefineBy
          | HubspotSDK::Crm::PublicAbsoluteComparativeTimestampRefineBy
          | HubspotSDK::Crm::PublicAbsoluteRangedTimestampRefineBy
          | HubspotSDK::Crm::PublicAllHistoryRefineBy
          | HubspotSDK::Crm::PublicTimePointOperation
          | HubspotSDK::Crm::PublicRangedTimeOperation

        module PruningRefineBy
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Crm::PublicAdsTimeFilter::pruning_refine_by]
        end
      end
    end
  end
end
