module HubSpotSDK
  module Models
    module Crm
      type public_survey_monkey_filter =
        {
          filter_type: HubSpotSDK::Models::Crm::PublicSurveyMonkeyFilter::filter_type,
          operator: String,
          survey_id: String
        }

      class PublicSurveyMonkeyFilter < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor filter_type: HubSpotSDK::Models::Crm::PublicSurveyMonkeyFilter::filter_type

        attr_accessor operator: String

        attr_accessor survey_id: String

        def initialize: (
          filter_type: HubSpotSDK::Models::Crm::PublicSurveyMonkeyFilter::filter_type,
          operator: String,
          survey_id: String
        ) -> void

        def to_hash: -> {
          filter_type: HubSpotSDK::Models::Crm::PublicSurveyMonkeyFilter::filter_type,
          operator: String,
          survey_id: String
        }

        type filter_type = :SURVEY_MONKEY

        module FilterType
          extend HubSpotSDK::Internal::Type::Enum

          SURVEY_MONKEY: :SURVEY_MONKEY

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::PublicSurveyMonkeyFilter::filter_type]
        end
      end
    end
  end
end
