module HubspotSDK
  module Models
    module Crm
      type public_property_validation_rule =
        {
          rule_arguments: ::Array[String],
          rule_type: HubspotSDK::Models::Crm::PublicPropertyValidationRule::rule_type,
          should_apply_normalization: bool
        }

      class PublicPropertyValidationRule < HubspotSDK::Internal::Type::BaseModel
        attr_accessor rule_arguments: ::Array[String]

        attr_accessor rule_type: HubspotSDK::Models::Crm::PublicPropertyValidationRule::rule_type

        attr_reader should_apply_normalization: bool?

        def should_apply_normalization=: (bool) -> bool

        def initialize: (
          rule_arguments: ::Array[String],
          rule_type: HubspotSDK::Models::Crm::PublicPropertyValidationRule::rule_type,
          ?should_apply_normalization: bool
        ) -> void

        def to_hash: -> {
          rule_arguments: ::Array[String],
          rule_type: HubspotSDK::Models::Crm::PublicPropertyValidationRule::rule_type,
          should_apply_normalization: bool
        }

        type rule_type =
          :AFTER_DATETIME_DURATION
          | :AFTER_DURATION
          | :ALPHANUMERIC
          | :BEFORE_DATETIME_DURATION
          | :BEFORE_DURATION
          | :DAYS_OF_WEEK
          | :DECIMAL
          | :DOMAIN
          | :EMAIL
          | :EMAIL_ALLOWED_DOMAINS
          | :EMAIL_BLOCKED_DOMAINS
          | :END_DATE
          | :END_DATETIME
          | :FORMAT
          | :MAX_LENGTH
          | :MAX_NUMBER
          | :MIN_LENGTH
          | :MIN_NUMBER
          | :PHONE_NUMBER_WITH_EXPLICIT_COUNTRY_CODE
          | :REGEX
          | :SPECIAL_CHARACTERS
          | :START_DATE
          | :START_DATETIME
          | :URL
          | :URL_ALLOWED_DOMAINS
          | :URL_BLOCKED_DOMAINS
          | :WHITESPACE

        module RuleType
          extend HubspotSDK::Internal::Type::Enum

          AFTER_DATETIME_DURATION: :AFTER_DATETIME_DURATION
          AFTER_DURATION: :AFTER_DURATION
          ALPHANUMERIC: :ALPHANUMERIC
          BEFORE_DATETIME_DURATION: :BEFORE_DATETIME_DURATION
          BEFORE_DURATION: :BEFORE_DURATION
          DAYS_OF_WEEK: :DAYS_OF_WEEK
          DECIMAL: :DECIMAL
          DOMAIN: :DOMAIN
          EMAIL: :EMAIL
          EMAIL_ALLOWED_DOMAINS: :EMAIL_ALLOWED_DOMAINS
          EMAIL_BLOCKED_DOMAINS: :EMAIL_BLOCKED_DOMAINS
          END_DATE: :END_DATE
          END_DATETIME: :END_DATETIME
          FORMAT: :FORMAT
          MAX_LENGTH: :MAX_LENGTH
          MAX_NUMBER: :MAX_NUMBER
          MIN_LENGTH: :MIN_LENGTH
          MIN_NUMBER: :MIN_NUMBER
          PHONE_NUMBER_WITH_EXPLICIT_COUNTRY_CODE: :PHONE_NUMBER_WITH_EXPLICIT_COUNTRY_CODE
          REGEX: :REGEX
          SPECIAL_CHARACTERS: :SPECIAL_CHARACTERS
          START_DATE: :START_DATE
          START_DATETIME: :START_DATETIME
          URL: :URL
          URL_ALLOWED_DOMAINS: :URL_ALLOWED_DOMAINS
          URL_BLOCKED_DOMAINS: :URL_BLOCKED_DOMAINS
          WHITESPACE: :WHITESPACE

          def self?.values: -> ::Array[HubspotSDK::Models::Crm::PublicPropertyValidationRule::rule_type]
        end
      end
    end
  end
end
