module HubspotSDK
  module Models
    module Crm
      type public_and_filter_branch =
        {
          filter_branches: ::Array[HubspotSDK::Models::Crm::PublicAndFilterBranch::filter_branch],
          filter_branch_operator: String,
          filter_branch_type: HubspotSDK::Models::Crm::PublicAndFilterBranch::filter_branch_type,
          filters: ::Array[HubspotSDK::Models::Crm::PublicAndFilterBranch::filter]
        }

      class PublicAndFilterBranch < HubspotSDK::Internal::Type::BaseModel
        attr_accessor filter_branches: ::Array[HubspotSDK::Models::Crm::PublicAndFilterBranch::filter_branch]

        attr_accessor filter_branch_operator: String

        attr_accessor filter_branch_type: HubspotSDK::Models::Crm::PublicAndFilterBranch::filter_branch_type

        attr_accessor filters: ::Array[HubspotSDK::Models::Crm::PublicAndFilterBranch::filter]

        def initialize: (
          filter_branches: ::Array[HubspotSDK::Models::Crm::PublicAndFilterBranch::filter_branch],
          filter_branch_operator: String,
          filter_branch_type: HubspotSDK::Models::Crm::PublicAndFilterBranch::filter_branch_type,
          filters: ::Array[HubspotSDK::Models::Crm::PublicAndFilterBranch::filter]
        ) -> void

        def to_hash: -> {
          filter_branches: ::Array[HubspotSDK::Models::Crm::PublicAndFilterBranch::filter_branch],
          filter_branch_operator: String,
          filter_branch_type: HubspotSDK::Models::Crm::PublicAndFilterBranch::filter_branch_type,
          filters: ::Array[HubspotSDK::Models::Crm::PublicAndFilterBranch::filter]
        }

        type filter_branch =
          HubspotSDK::Crm::PublicOrFilterBranch
          | HubspotSDK::Crm::PublicAndFilterBranch
          | HubspotSDK::Crm::PublicNotAllFilterBranch
          | HubspotSDK::Crm::PublicNotAnyFilterBranch
          | HubspotSDK::Crm::PublicRestrictedFilterBranch
          | HubspotSDK::Crm::PublicUnifiedEventsFilterBranch
          | HubspotSDK::Crm::PublicPropertyAssociationFilterBranch
          | HubspotSDK::Crm::PublicAssociationFilterBranch

        module FilterBranch
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Crm::PublicAndFilterBranch::filter_branch]
        end

        type filter_branch_type = :AND

        module FilterBranchType
          extend HubspotSDK::Internal::Type::Enum

          AND: :AND

          def self?.values: -> ::Array[HubspotSDK::Models::Crm::PublicAndFilterBranch::filter_branch_type]
        end

        type filter =
          HubspotSDK::Crm::PublicPropertyFilter
          | HubspotSDK::Crm::PublicAssociationInListFilter
          | HubspotSDK::Crm::PublicPageViewAnalyticsFilter
          | HubspotSDK::Crm::PublicCtaAnalyticsFilter
          | HubspotSDK::Crm::PublicEventAnalyticsFilter
          | HubspotSDK::Crm::PublicFormSubmissionFilter
          | HubspotSDK::Crm::PublicFormSubmissionOnPageFilter
          | HubspotSDK::Crm::PublicIntegrationEventFilter
          | HubspotSDK::Crm::PublicEmailSubscriptionFilter
          | HubspotSDK::Crm::PublicCommunicationSubscriptionFilter
          | HubspotSDK::Crm::PublicCampaignInfluencedFilter
          | HubspotSDK::Crm::PublicSurveyMonkeyFilter
          | HubspotSDK::Crm::PublicSurveyMonkeyValueFilter
          | HubspotSDK::Crm::PublicWebinarFilter
          | HubspotSDK::Crm::PublicEmailEventFilter
          | HubspotSDK::Crm::PublicPrivacyAnalyticsFilter
          | HubspotSDK::Crm::PublicAdsSearchFilter
          | HubspotSDK::Crm::PublicAdsTimeFilter
          | HubspotSDK::Crm::PublicInListFilter
          | HubspotSDK::Crm::PublicNumAssociationsFilter
          | HubspotSDK::Crm::PublicUnifiedEventsFilter
          | HubspotSDK::Crm::PublicPropertyAssociationInListFilter
          | HubspotSDK::Crm::PublicConstantFilter

        module Filter
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Crm::PublicAndFilterBranch::filter]
        end
      end
    end
  end
end
