module HubSpotSDK
  module Models
    module Crm
      type public_in_list_filter =
        {
          filter_type: HubSpotSDK::Models::Crm::PublicInListFilter::filter_type,
          list_id: String,
          operator: String,
          metadata: HubSpotSDK::Crm::PublicInListFilterMetadata
        }

      class PublicInListFilter < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor filter_type: HubSpotSDK::Models::Crm::PublicInListFilter::filter_type

        attr_accessor list_id: String

        attr_accessor operator: String

        attr_reader metadata: HubSpotSDK::Crm::PublicInListFilterMetadata?

        def metadata=: (
          HubSpotSDK::Crm::PublicInListFilterMetadata
        ) -> HubSpotSDK::Crm::PublicInListFilterMetadata

        def initialize: (
          filter_type: HubSpotSDK::Models::Crm::PublicInListFilter::filter_type,
          list_id: String,
          operator: String,
          ?metadata: HubSpotSDK::Crm::PublicInListFilterMetadata
        ) -> void

        def to_hash: -> {
          filter_type: HubSpotSDK::Models::Crm::PublicInListFilter::filter_type,
          list_id: String,
          operator: String,
          metadata: HubSpotSDK::Crm::PublicInListFilterMetadata
        }

        type filter_type = :IN_LIST

        module FilterType
          extend HubSpotSDK::Internal::Type::Enum

          IN_LIST: :IN_LIST

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::PublicInListFilter::filter_type]
        end
      end
    end
  end
end
