module HubspotSDK
  module Models
    module CRM
      type public_property_validation_rule_map =
        {
          property_name: String,
          property_validation_rules: ::Array[HubspotSDK::CRM::PublicPropertyValidationRule]
        }

      class PublicPropertyValidationRuleMap < HubspotSDK::Internal::Type::BaseModel
        attr_accessor property_name: String

        attr_accessor property_validation_rules: ::Array[HubspotSDK::CRM::PublicPropertyValidationRule]

        def initialize: (
          property_name: String,
          property_validation_rules: ::Array[HubspotSDK::CRM::PublicPropertyValidationRule]
        ) -> void

        def to_hash: -> {
          property_name: String,
          property_validation_rules: ::Array[HubspotSDK::CRM::PublicPropertyValidationRule]
        }
      end
    end
  end
end
