module HubSpotSDK
  module Models
    module Crm
      type public_list_conversion_inactivity =
        {
          conversion_type: HubSpotSDK::Models::Crm::PublicListConversionInactivity::conversion_type,
          offset: Integer,
          time_unit: HubSpotSDK::Models::Crm::PublicListConversionInactivity::time_unit
        }

      class PublicListConversionInactivity < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor conversion_type: HubSpotSDK::Models::Crm::PublicListConversionInactivity::conversion_type

        attr_accessor offset: Integer

        attr_accessor time_unit: HubSpotSDK::Models::Crm::PublicListConversionInactivity::time_unit

        def initialize: (
          conversion_type: HubSpotSDK::Models::Crm::PublicListConversionInactivity::conversion_type,
          offset: Integer,
          time_unit: HubSpotSDK::Models::Crm::PublicListConversionInactivity::time_unit
        ) -> void

        def to_hash: -> {
          conversion_type: HubSpotSDK::Models::Crm::PublicListConversionInactivity::conversion_type,
          offset: Integer,
          time_unit: HubSpotSDK::Models::Crm::PublicListConversionInactivity::time_unit
        }

        type conversion_type = :INACTIVITY

        module ConversionType
          extend HubSpotSDK::Internal::Type::Enum

          INACTIVITY: :INACTIVITY

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::PublicListConversionInactivity::conversion_type]
        end

        type time_unit = :DAY | :MONTH | :WEEK

        module TimeUnit
          extend HubSpotSDK::Internal::Type::Enum

          DAY: :DAY
          MONTH: :MONTH
          WEEK: :WEEK

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::PublicListConversionInactivity::time_unit]
        end
      end
    end
  end
end
