module HubspotSDK
  module Models
    module CRM
      type public_default_association =
        {
          association_spec: HubspotSDK::CRM::Associations::AssociationSpec1,
          from: HubspotSDK::PublicObjectID,
          to: HubspotSDK::PublicObjectID
        }

      class PublicDefaultAssociation < HubspotSDK::Internal::Type::BaseModel
        attr_accessor association_spec: HubspotSDK::CRM::Associations::AssociationSpec1

        attr_accessor from: HubspotSDK::PublicObjectID

        attr_accessor to: HubspotSDK::PublicObjectID

        def initialize: (
          association_spec: HubspotSDK::CRM::Associations::AssociationSpec1,
          from: HubspotSDK::PublicObjectID,
          to: HubspotSDK::PublicObjectID
        ) -> void

        def to_hash: -> {
          association_spec: HubspotSDK::CRM::Associations::AssociationSpec1,
          from: HubspotSDK::PublicObjectID,
          to: HubspotSDK::PublicObjectID
        }
      end
    end
  end
end
