module HubspotSDK
  module Models
    module Crm
      type public_team = { id: String, name: String, primary: bool }

      class PublicTeam < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String

        attr_accessor primary: bool

        def initialize: (id: String, name: String, primary: bool) -> void

        def to_hash: -> { id: String, name: String, primary: bool }
      end
    end
  end
end
