module HubSpotSDK
  module Models
    module Crm
      type public_ads_time_filter =
        {
          filter_type: HubSpotSDK::Models::Crm::PublicAdsTimeFilter::filter_type,
          pruning_refine_by: HubSpotSDK::Models::Crm::PublicAdsTimeFilter::pruning_refine_by
        }

      class PublicAdsTimeFilter < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor filter_type: HubSpotSDK::Models::Crm::PublicAdsTimeFilter::filter_type

        attr_accessor pruning_refine_by: HubSpotSDK::Models::Crm::PublicAdsTimeFilter::pruning_refine_by

        def initialize: (
          filter_type: HubSpotSDK::Models::Crm::PublicAdsTimeFilter::filter_type,
          pruning_refine_by: HubSpotSDK::Models::Crm::PublicAdsTimeFilter::pruning_refine_by
        ) -> void

        def to_hash: -> {
          filter_type: HubSpotSDK::Models::Crm::PublicAdsTimeFilter::filter_type,
          pruning_refine_by: HubSpotSDK::Models::Crm::PublicAdsTimeFilter::pruning_refine_by
        }

        type filter_type = :ADS_TIME

        module FilterType
          extend HubSpotSDK::Internal::Type::Enum

          ADS_TIME: :ADS_TIME

          def self?.values: -> ::Array[HubSpotSDK::Models::Crm::PublicAdsTimeFilter::filter_type]
        end

        type pruning_refine_by =
          HubSpotSDK::Crm::PublicNumOccurrencesRefineBy
          | HubSpotSDK::Crm::PublicSetOccurrencesRefineBy
          | HubSpotSDK::Crm::PublicRelativeComparativeTimestampRefineBy
          | HubSpotSDK::Crm::PublicRelativeRangedTimestampRefineBy
          | HubSpotSDK::Crm::PublicAbsoluteComparativeTimestampRefineBy
          | HubSpotSDK::Crm::PublicAbsoluteRangedTimestampRefineBy
          | HubSpotSDK::Crm::PublicAllHistoryRefineBy
          | HubSpotSDK::Crm::PublicTimePointOperation
          | HubSpotSDK::Crm::PublicRangedTimeOperation

        module PruningRefineBy
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Crm::PublicAdsTimeFilter::pruning_refine_by]
        end
      end
    end
  end
end
