module HubSpotSDK
  module Models
    module Crm
      type public_event_filter_metadata =
        {
          operation: HubSpotSDK::Models::Crm::PublicEventFilterMetadata::operation,
          property: String
        }

      class PublicEventFilterMetadata < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor operation: HubSpotSDK::Models::Crm::PublicEventFilterMetadata::operation

        attr_accessor property: String

        def initialize: (
          operation: HubSpotSDK::Models::Crm::PublicEventFilterMetadata::operation,
          property: String
        ) -> void

        def to_hash: -> {
          operation: HubSpotSDK::Models::Crm::PublicEventFilterMetadata::operation,
          property: String
        }

        type operation =
          HubSpotSDK::Crm::PublicBoolPropertyOperation
          | HubSpotSDK::Crm::PublicNumberPropertyOperation
          | HubSpotSDK::Crm::PublicStringPropertyOperation
          | HubSpotSDK::Crm::PublicDateTimePropertyOperation
          | HubSpotSDK::Crm::PublicRangedDatePropertyOperation
          | HubSpotSDK::Crm::PublicComparativePropertyUpdatedOperation
          | HubSpotSDK::Crm::PublicComparativeDatePropertyOperation
          | HubSpotSDK::Crm::PublicRollingDateRangePropertyOperation
          | HubSpotSDK::Crm::PublicRollingPropertyUpdatedOperation
          | HubSpotSDK::Crm::PublicEnumerationPropertyOperation
          | HubSpotSDK::Crm::PublicAllPropertyTypesOperation
          | HubSpotSDK::Crm::PublicRangedNumberPropertyOperation
          | HubSpotSDK::Crm::PublicMultiStringPropertyOperation
          | HubSpotSDK::Crm::PublicDatePropertyOperation
          | HubSpotSDK::Crm::PublicCalendarDatePropertyOperation
          | HubSpotSDK::Crm::PublicTimePointOperation
          | HubSpotSDK::Crm::PublicRangedTimeOperation

        module Operation
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Crm::PublicEventFilterMetadata::operation]
        end
      end
    end
  end
end
