module HubspotSDK
  module Models
    module Crm
      type record_list_membership =
        {
          list_id: String,
          list_version: Integer,
          first_added_timestamp: Time,
          is_public_list: bool,
          last_added_timestamp: Time
        }

      class RecordListMembership < HubspotSDK::Internal::Type::BaseModel
        attr_accessor list_id: String

        attr_accessor list_version: Integer

        attr_reader first_added_timestamp: Time?

        def first_added_timestamp=: (Time) -> Time

        attr_reader is_public_list: bool?

        def is_public_list=: (bool) -> bool

        attr_reader last_added_timestamp: Time?

        def last_added_timestamp=: (Time) -> Time

        def initialize: (
          list_id: String,
          list_version: Integer,
          ?first_added_timestamp: Time,
          ?is_public_list: bool,
          ?last_added_timestamp: Time
        ) -> void

        def to_hash: -> {
          list_id: String,
          list_version: Integer,
          first_added_timestamp: Time,
          is_public_list: bool,
          last_added_timestamp: Time
        }
      end
    end
  end
end
