module HubspotSDK
  module Models
    module Crm
      type record_limit_response =
        {
          custom_object_types: HubspotSDK::Crm::CustomObjectRecordLimitResponse,
          hubspot_defined_object_types: ::Array[HubspotSDK::Crm::LimitAndUsageForObjectType]
        }

      class RecordLimitResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor custom_object_types: HubspotSDK::Crm::CustomObjectRecordLimitResponse

        attr_accessor hubspot_defined_object_types: ::Array[HubspotSDK::Crm::LimitAndUsageForObjectType]

        def initialize: (
          custom_object_types: HubspotSDK::Crm::CustomObjectRecordLimitResponse,
          hubspot_defined_object_types: ::Array[HubspotSDK::Crm::LimitAndUsageForObjectType]
        ) -> void

        def to_hash: -> {
          custom_object_types: HubspotSDK::Crm::CustomObjectRecordLimitResponse,
          hubspot_defined_object_types: ::Array[HubspotSDK::Crm::LimitAndUsageForObjectType]
        }
      end
    end
  end
end
