module HubspotSDK
  module Models
    module Crm
      type simple_public_object_id = { id: String }

      class SimplePublicObjectID < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end
    end
  end
end
