module HubspotSDK
  module Models
    module Crm
      type subscription_unpause_params =
        {  } & HubspotSDK::Internal::Type::request_parameters

      class SubscriptionUnpauseParams < HubspotSDK::Models::Crm::UnpauseRequest
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        def initialize: (?request_options: HubspotSDK::request_opts) -> void

        def to_hash: -> { request_options: HubspotSDK::RequestOptions }
      end
    end
  end
end
