module HubspotSDK
  module Models
    module Crm
      type timeline_create_project_type_params =
        {  } & HubspotSDK::Internal::Type::request_parameters

      class TimelineCreateProjectTypeParams < HubspotSDK::Models::Crm::ExternalAppEventResolutionRequest
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        def initialize: (?request_options: HubspotSDK::request_opts) -> void

        def to_hash: -> { request_options: HubspotSDK::RequestOptions }
      end
    end
  end
end
