module HubspotSDK
  module Models
    module CRM
      type timeline_event_template_update_request =
        {
          id: String,
          name: String,
          tokens: ::Array[HubspotSDK::CRM::TimelineEventTemplateToken],
          detail_template: String,
          header_template: String
        }

      class TimelineEventTemplateUpdateRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String

        attr_accessor tokens: ::Array[HubspotSDK::CRM::TimelineEventTemplateToken]

        attr_reader detail_template: String?

        def detail_template=: (String) -> String

        attr_reader header_template: String?

        def header_template=: (String) -> String

        def initialize: (
          id: String,
          name: String,
          tokens: ::Array[HubspotSDK::CRM::TimelineEventTemplateToken],
          ?detail_template: String,
          ?header_template: String
        ) -> void

        def to_hash: -> {
          id: String,
          name: String,
          tokens: ::Array[HubspotSDK::CRM::TimelineEventTemplateToken],
          detail_template: String,
          header_template: String
        }
      end
    end
  end
end
