module HubspotSDK
  module Models
    module Crm
      type timeline_event_template_token_update_request =
        {
          label: String,
          object_property_name: String,
          options: ::Array[HubspotSDK::Crm::TimelineEventTemplateTokenOption]
        }

      class TimelineEventTemplateTokenUpdateRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor label: String

        attr_reader object_property_name: String?

        def object_property_name=: (String) -> String

        attr_reader options: ::Array[HubspotSDK::Crm::TimelineEventTemplateTokenOption]?

        def options=: (
          ::Array[HubspotSDK::Crm::TimelineEventTemplateTokenOption]
        ) -> ::Array[HubspotSDK::Crm::TimelineEventTemplateTokenOption]

        def initialize: (
          label: String,
          ?object_property_name: String,
          ?options: ::Array[HubspotSDK::Crm::TimelineEventTemplateTokenOption]
        ) -> void

        def to_hash: -> {
          label: String,
          object_property_name: String,
          options: ::Array[HubspotSDK::Crm::TimelineEventTemplateTokenOption]
        }
      end
    end
  end
end
