module HubspotSDK
  module Models
    module CRM
      type timeline_event =
        {
          event_template_id: String,
          tokens: ::Hash[Symbol, String],
          id: String,
          domain: String,
          email: String,
          extra_data: top,
          object_id_: String,
          timeline_i_frame: HubspotSDK::CRM::TimelineEventIFrame,
          timestamp: Time,
          utk: String
        }

      class TimelineEvent < HubspotSDK::Internal::Type::BaseModel
        attr_accessor event_template_id: String

        attr_accessor tokens: ::Hash[Symbol, String]

        attr_reader id: String?

        def id=: (String) -> String

        attr_reader domain: String?

        def domain=: (String) -> String

        attr_reader email: String?

        def email=: (String) -> String

        attr_reader extra_data: top?

        def extra_data=: (top) -> top

        attr_reader object_id_: String?

        def object_id_=: (String) -> String

        attr_reader timeline_i_frame: HubspotSDK::CRM::TimelineEventIFrame?

        def timeline_i_frame=: (
          HubspotSDK::CRM::TimelineEventIFrame
        ) -> HubspotSDK::CRM::TimelineEventIFrame

        attr_reader timestamp: Time?

        def timestamp=: (Time) -> Time

        attr_reader utk: String?

        def utk=: (String) -> String

        def initialize: (
          event_template_id: String,
          tokens: ::Hash[Symbol, String],
          ?id: String,
          ?domain: String,
          ?email: String,
          ?extra_data: top,
          ?object_id_: String,
          ?timeline_i_frame: HubspotSDK::CRM::TimelineEventIFrame,
          ?timestamp: Time,
          ?utk: String
        ) -> void

        def to_hash: -> {
          event_template_id: String,
          tokens: ::Hash[Symbol, String],
          id: String,
          domain: String,
          email: String,
          extra_data: top,
          object_id_: String,
          timeline_i_frame: HubspotSDK::CRM::TimelineEventIFrame,
          timestamp: Time,
          utk: String
        }
      end
    end
  end
end
