module HubspotSDK
  module Models
    module Crm
      type timeline_event_i_frame =
        {
          header_label: String,
          height: Integer,
          link_label: String,
          url: String,
          width: Integer
        }

      class TimelineEventIFrame < HubspotSDK::Internal::Type::BaseModel
        attr_accessor header_label: String

        attr_accessor height: Integer

        attr_accessor link_label: String

        attr_accessor url: String

        attr_accessor width: Integer

        def initialize: (
          header_label: String,
          height: Integer,
          link_label: String,
          url: String,
          width: Integer
        ) -> void

        def to_hash: -> {
          header_label: String,
          height: Integer,
          link_label: String,
          url: String,
          width: Integer
        }
      end
    end
  end
end
