module HubspotSDK
  module Models
    module Crm
      type unpause_request = { proposed_next_billing_date: Integer }

      class UnpauseRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor proposed_next_billing_date: Integer

        def initialize: (proposed_next_billing_date: Integer) -> void

        def to_hash: -> { proposed_next_billing_date: Integer }
      end
    end
  end
end
