# typed: strong

module HubspotSDK
  module Models
    module CRM
      class PipelineStage < HubspotSDK::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(HubspotSDK::CRM::PipelineStage, HubspotSDK::Internal::AnyHash)
          end

        # A unique identifier generated by HubSpot that can be used to retrieve and update
        # the pipeline stage.
        sig { returns(String) }
        attr_accessor :id

        # Whether the pipeline is archived.
        sig { returns(T::Boolean) }
        attr_accessor :archived

        # The date the pipeline stage was created. The stages on default pipelines will
        # have createdAt = 0.
        sig { returns(Time) }
        attr_accessor :created_at

        # The order for displaying this pipeline stage. If two pipeline stages have a
        # matching `displayOrder`, they will be sorted alphabetically by label.
        sig { returns(Integer) }
        attr_accessor :display_order

        # A label used to organize pipeline stages in HubSpot's UI. Each pipeline stage's
        # label must be unique within that pipeline.
        sig { returns(String) }
        attr_accessor :label

        # The date the pipeline stage was last updated.
        sig { returns(Time) }
        attr_accessor :updated_at

        # The date the pipeline was archived. `archivedAt` will only be present if the
        # pipeline is archived.
        sig { returns(T.nilable(Time)) }
        attr_reader :archived_at

        sig { params(archived_at: Time).void }
        attr_writer :archived_at

        # A JSON object containing properties that are not present on all object
        # pipelines.
        #
        # For `deals` pipelines, the `probability` field is required
        # (`{ "probability": 0.5 }`), and represents the likelihood a deal will close.
        # Possible values are between 0.0 and 1.0 in increments of 0.1.
        #
        # For `tickets` pipelines, the `ticketState` field is optional
        # (`{ "ticketState": "OPEN" }`), and represents whether the ticket remains open or
        # has been closed by a member of your Support team. Possible values are `OPEN` or
        # `CLOSED`.
        sig { returns(T.nilable(T::Hash[Symbol, String])) }
        attr_reader :metadata

        sig { params(metadata: T::Hash[Symbol, String]).void }
        attr_writer :metadata

        # Defines the level of write access for the pipeline stage, with possible values
        # being CRM_PERMISSIONS_ENFORCEMENT, READ_ONLY, or INTERNAL_ONLY.
        sig do
          returns(
            T.nilable(
              HubspotSDK::CRM::PipelineStage::WritePermissions::TaggedSymbol
            )
          )
        end
        attr_reader :write_permissions

        sig do
          params(
            write_permissions:
              HubspotSDK::CRM::PipelineStage::WritePermissions::OrSymbol
          ).void
        end
        attr_writer :write_permissions

        # A pipeline stage definition.
        sig do
          params(
            id: String,
            archived: T::Boolean,
            created_at: Time,
            display_order: Integer,
            label: String,
            updated_at: Time,
            archived_at: Time,
            metadata: T::Hash[Symbol, String],
            write_permissions:
              HubspotSDK::CRM::PipelineStage::WritePermissions::OrSymbol
          ).returns(T.attached_class)
        end
        def self.new(
          # A unique identifier generated by HubSpot that can be used to retrieve and update
          # the pipeline stage.
          id:,
          # Whether the pipeline is archived.
          archived:,
          # The date the pipeline stage was created. The stages on default pipelines will
          # have createdAt = 0.
          created_at:,
          # The order for displaying this pipeline stage. If two pipeline stages have a
          # matching `displayOrder`, they will be sorted alphabetically by label.
          display_order:,
          # A label used to organize pipeline stages in HubSpot's UI. Each pipeline stage's
          # label must be unique within that pipeline.
          label:,
          # The date the pipeline stage was last updated.
          updated_at:,
          # The date the pipeline was archived. `archivedAt` will only be present if the
          # pipeline is archived.
          archived_at: nil,
          # A JSON object containing properties that are not present on all object
          # pipelines.
          #
          # For `deals` pipelines, the `probability` field is required
          # (`{ "probability": 0.5 }`), and represents the likelihood a deal will close.
          # Possible values are between 0.0 and 1.0 in increments of 0.1.
          #
          # For `tickets` pipelines, the `ticketState` field is optional
          # (`{ "ticketState": "OPEN" }`), and represents whether the ticket remains open or
          # has been closed by a member of your Support team. Possible values are `OPEN` or
          # `CLOSED`.
          metadata: nil,
          # Defines the level of write access for the pipeline stage, with possible values
          # being CRM_PERMISSIONS_ENFORCEMENT, READ_ONLY, or INTERNAL_ONLY.
          write_permissions: nil
        )
        end

        sig do
          override.returns(
            {
              id: String,
              archived: T::Boolean,
              created_at: Time,
              display_order: Integer,
              label: String,
              updated_at: Time,
              archived_at: Time,
              metadata: T::Hash[Symbol, String],
              write_permissions:
                HubspotSDK::CRM::PipelineStage::WritePermissions::TaggedSymbol
            }
          )
        end
        def to_hash
        end

        # Defines the level of write access for the pipeline stage, with possible values
        # being CRM_PERMISSIONS_ENFORCEMENT, READ_ONLY, or INTERNAL_ONLY.
        module WritePermissions
          extend HubspotSDK::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, HubspotSDK::CRM::PipelineStage::WritePermissions)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          CRM_PERMISSIONS_ENFORCEMENT =
            T.let(
              :CRM_PERMISSIONS_ENFORCEMENT,
              HubspotSDK::CRM::PipelineStage::WritePermissions::TaggedSymbol
            )
          READ_ONLY =
            T.let(
              :READ_ONLY,
              HubspotSDK::CRM::PipelineStage::WritePermissions::TaggedSymbol
            )
          INTERNAL_ONLY =
            T.let(
              :INTERNAL_ONLY,
              HubspotSDK::CRM::PipelineStage::WritePermissions::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                HubspotSDK::CRM::PipelineStage::WritePermissions::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end
      end
    end
  end
end
