# typed: strong

module HubSpotSDK
  module Models
    module Crm
      class Pipeline < HubSpotSDK::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(HubSpotSDK::Crm::Pipeline, HubSpotSDK::Internal::AnyHash)
          end

        # A unique identifier generated by HubSpot that can be used to retrieve and update
        # the pipeline.
        sig { returns(String) }
        attr_accessor :id

        # Whether the pipeline is archived.
        sig { returns(T::Boolean) }
        attr_accessor :archived

        # The date the pipeline was created. The default pipelines will have createdAt
        # = 0.
        sig { returns(Time) }
        attr_accessor :created_at

        # The order for displaying this pipeline. If two pipelines have a matching
        # `displayOrder`, they will be sorted alphabetically by label.
        sig { returns(Integer) }
        attr_accessor :display_order

        # A unique label used to organize pipelines in HubSpot's UI
        sig { returns(String) }
        attr_accessor :label

        # The stages associated with the pipeline. They can be retrieved and updated via
        # the pipeline stages endpoints.
        sig { returns(T::Array[HubSpotSDK::Crm::PipelineStage]) }
        attr_accessor :stages

        # The date the pipeline was last updated.
        sig { returns(Time) }
        attr_accessor :updated_at

        # The date the pipeline was archived. `archivedAt` will only be present if the
        # pipeline is archived.
        sig { returns(T.nilable(Time)) }
        attr_reader :archived_at

        sig { params(archived_at: Time).void }
        attr_writer :archived_at

        sig do
          params(
            id: String,
            archived: T::Boolean,
            created_at: Time,
            display_order: Integer,
            label: String,
            stages: T::Array[HubSpotSDK::Crm::PipelineStage::OrHash],
            updated_at: Time,
            archived_at: Time
          ).returns(T.attached_class)
        end
        def self.new(
          # A unique identifier generated by HubSpot that can be used to retrieve and update
          # the pipeline.
          id:,
          # Whether the pipeline is archived.
          archived:,
          # The date the pipeline was created. The default pipelines will have createdAt
          # = 0.
          created_at:,
          # The order for displaying this pipeline. If two pipelines have a matching
          # `displayOrder`, they will be sorted alphabetically by label.
          display_order:,
          # A unique label used to organize pipelines in HubSpot's UI
          label:,
          # The stages associated with the pipeline. They can be retrieved and updated via
          # the pipeline stages endpoints.
          stages:,
          # The date the pipeline was last updated.
          updated_at:,
          # The date the pipeline was archived. `archivedAt` will only be present if the
          # pipeline is archived.
          archived_at: nil
        )
        end

        sig do
          override.returns(
            {
              id: String,
              archived: T::Boolean,
              created_at: Time,
              display_order: Integer,
              label: String,
              stages: T::Array[HubSpotSDK::Crm::PipelineStage],
              updated_at: Time,
              archived_at: Time
            }
          )
        end
        def to_hash
        end
      end
    end
  end
end
