module HubspotSDK
  module Models
    module CRM
      module Associations
        type batch_input_public_association_multi_post =
          {
            inputs: ::Array[HubspotSDK::CRM::Associations::PublicAssociationMultiPost]
          }

        class BatchInputPublicAssociationMultiPost < HubspotSDK::Internal::Type::BaseModel
          attr_accessor inputs: ::Array[HubspotSDK::CRM::Associations::PublicAssociationMultiPost]

          def initialize: (
            inputs: ::Array[HubspotSDK::CRM::Associations::PublicAssociationMultiPost]
          ) -> void

          def to_hash: -> {
            inputs: ::Array[HubspotSDK::CRM::Associations::PublicAssociationMultiPost]
          }
        end
      end
    end
  end
end
