module HubspotSDK
  module Models
    module CRM
      module Associations
        type batch_input_public_association_multi_archive =
          {
            inputs: ::Array[HubspotSDK::CRM::Associations::PublicAssociationMultiArchive]
          }

        class BatchInputPublicAssociationMultiArchive < HubspotSDK::Internal::Type::BaseModel
          attr_accessor inputs: ::Array[HubspotSDK::CRM::Associations::PublicAssociationMultiArchive]

          def initialize: (
            inputs: ::Array[HubspotSDK::CRM::Associations::PublicAssociationMultiArchive]
          ) -> void

          def to_hash: -> {
            inputs: ::Array[HubspotSDK::CRM::Associations::PublicAssociationMultiArchive]
          }
        end
      end
    end
  end
end
