module HubspotSDK
  module Models
    module CRM
      module Associations
        type batch_input_public_default_association_multi_post =
          {
            inputs: ::Array[HubspotSDK::CRM::Associations::PublicDefaultAssociationMultiPost]
          }

        class BatchInputPublicDefaultAssociationMultiPost < HubspotSDK::Internal::Type::BaseModel
          attr_accessor inputs: ::Array[HubspotSDK::CRM::Associations::PublicDefaultAssociationMultiPost]

          def initialize: (
            inputs: ::Array[HubspotSDK::CRM::Associations::PublicDefaultAssociationMultiPost]
          ) -> void

          def to_hash: -> {
            inputs: ::Array[HubspotSDK::CRM::Associations::PublicDefaultAssociationMultiPost]
          }
        end
      end
    end
  end
end
