module HubspotSDK
  module Models
    module CRM
      module Associations
        type next_page1 = { after: String, link: String }

        class NextPage1 < HubspotSDK::Internal::Type::BaseModel
          attr_accessor after: String

          attr_reader link: String?

          def link=: (String) -> String

          def initialize: (after: String, ?link: String) -> void

          def to_hash: -> { after: String, link: String }
        end
      end
    end
  end
end
