module HubspotSDK
  module Models
    module CRM
      module Associations
        type previous_page1 = { before: String, link: String }

        class PreviousPage1 < HubspotSDK::Internal::Type::BaseModel
          attr_accessor before: String

          attr_reader link: String?

          def link=: (String) -> String

          def initialize: (before: String, ?link: String) -> void

          def to_hash: -> { before: String, link: String }
        end
      end
    end
  end
end
