module HubspotSDK
  module Models
    module Crm
      module Associations
        type v4_delete_params =
          { object_type: String, object_id_: String, to_object_type: String }
          & HubspotSDK::Internal::Type::request_parameters

        class V4DeleteParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_accessor object_type: String

          attr_accessor object_id_: String

          attr_accessor to_object_type: String

          def initialize: (
            object_type: String,
            object_id_: String,
            to_object_type: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            object_type: String,
            object_id_: String,
            to_object_type: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
