module HubSpotSDK
  module Resources
    class Cms
      class Hubdb
        class Rows
          def create: (
            String table_id_or_name,
            child_table_id: Integer,
            display_index: Integer,
            values: ::Hash[Symbol, HubSpotSDK::Models::Cms::variant],
            ?name: String,
            ?path: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::HubDBTableRowV3

          def list: (
            String table_id_or_name,
            ?after: String,
            ?archived: bool,
            ?limit: Integer,
            ?offset: Integer,
            ?properties: ::Array[String],
            ?sort: ::Array[String],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Models::Cms::unified_collection_response_with_total_base_hub_db_table_row_v3

          def clone_batch: (
            String table_id_or_name,
            inputs: ::Array[HubSpotSDK::Cms::HubDBTableRowBatchCloneRequest],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::BatchResponseHubDBTableRowV3

          def clone_draft: (
            String row_id,
            table_id_or_name: String,
            ?name: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::HubDBTableRowV3

          def create_batch: (
            String table_id_or_name,
            inputs: ::Array[HubSpotSDK::Cms::HubDBTableRowV3Request],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::BatchResponseHubDBTableRowV3

          def delete_draft: (
            String row_id,
            table_id_or_name: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> nil

          def get: (
            String row_id,
            table_id_or_name: String,
            ?archived: bool,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::HubDBTableRowV3

          def get_batch: (
            String table_id_or_name,
            inputs: ::Array[String],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::BatchResponseHubDBTableRowV3

          def get_draft: (
            String row_id,
            table_id_or_name: String,
            ?archived: bool,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::HubDBTableRowV3

          def get_draft_batch: (
            String table_id_or_name,
            inputs: ::Array[String],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::BatchResponseHubDBTableRowV3

          def purge_batch: (
            String table_id_or_name,
            inputs: ::Array[String],
            ?request_options: HubSpotSDK::request_opts
          ) -> nil

          def replace_batch: (
            String table_id_or_name,
            inputs: ::Array[HubSpotSDK::Cms::HubDBTableRowV3BatchUpdateRequest],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::BatchResponseHubDBTableRowV3

          def replace_draft: (
            String row_id,
            table_id_or_name: String,
            child_table_id: Integer,
            display_index: Integer,
            values: ::Hash[Symbol, HubSpotSDK::Models::Cms::variant],
            ?name: String,
            ?path: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::HubDBTableRowV3

          def update_batch: (
            String table_id_or_name,
            inputs: ::Array[HubSpotSDK::Cms::HubDBTableRowV3BatchUpdateRequest],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::BatchResponseHubDBTableRowV3

          def update_draft: (
            String row_id,
            table_id_or_name: String,
            child_table_id: Integer,
            display_index: Integer,
            values: ::Hash[Symbol, HubSpotSDK::Models::Cms::variant],
            ?name: String,
            ?path: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::HubDBTableRowV3

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
