module HubspotSDK
  module Resources
    class Cms
      class Hubdb
        class Rows
          def create: (
            String table_id_or_name,
            child_table_id: Integer,
            display_index: Integer,
            values: ::Hash[Symbol, top],
            ?name: String,
            ?path: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::HubDBTableRowV3

          def list: (
            String table_id_or_name,
            ?after: String,
            ?archived: bool,
            ?limit: Integer,
            ?offset: Integer,
            ?properties: ::Array[String],
            ?sort: ::Array[String],
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Internal::Page[top]

          def clone_batch: (
            String table_id_or_name,
            inputs: ::Array[HubspotSDK::Cms::HubDBTableRowBatchCloneRequest],
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::BatchResponseHubDBTableRowV3

          def clone_draft: (
            String row_id,
            table_id_or_name: String,
            ?name: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::HubDBTableRowV3

          def create_batch: (
            String table_id_or_name,
            inputs: ::Array[HubspotSDK::Cms::HubDBTableRowV3Request],
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::BatchResponseHubDBTableRowV3

          def delete_draft: (
            String row_id,
            table_id_or_name: String,
            ?request_options: HubspotSDK::request_opts
          ) -> nil

          def get: (
            String row_id,
            table_id_or_name: String,
            ?archived: bool,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::HubDBTableRowV3

          def get_batch: (
            String table_id_or_name,
            inputs: ::Array[String],
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::BatchResponseHubDBTableRowV3

          def get_draft: (
            String row_id,
            table_id_or_name: String,
            ?archived: bool,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::HubDBTableRowV3

          def get_draft_batch: (
            String table_id_or_name,
            inputs: ::Array[String],
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::BatchResponseHubDBTableRowV3

          def purge_batch: (
            String table_id_or_name,
            inputs: ::Array[String],
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::BatchResponseHubDBTableRowV3

          def replace_batch: (
            String table_id_or_name,
            inputs: ::Array[HubspotSDK::Cms::HubDBTableRowV3BatchUpdateRequest],
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::BatchResponseHubDBTableRowV3

          def replace_draft: (
            String row_id,
            table_id_or_name: String,
            child_table_id: Integer,
            display_index: Integer,
            values: ::Hash[Symbol, top],
            ?name: String,
            ?path: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::HubDBTableRowV3

          def update_batch: (
            String table_id_or_name,
            inputs: ::Array[HubspotSDK::Cms::HubDBTableRowV3BatchUpdateRequest],
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::BatchResponseHubDBTableRowV3

          def update_draft: (
            String row_id,
            table_id_or_name: String,
            child_table_id: Integer,
            display_index: Integer,
            values: ::Hash[Symbol, top],
            ?name: String,
            ?path: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::HubDBTableRowV3

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
