module HubSpotSDK
  module Resources
    class Cms
      class Hubdb
        class Tables
          def create: (
            allow_child_tables: bool,
            allow_public_api_access: bool,
            columns: ::Array[HubSpotSDK::Cms::ColumnRequest],
            dynamic_meta_tags: ::Hash[Symbol, Integer],
            enable_child_table_pages: bool,
            label: String,
            name: String,
            use_for_pages: bool,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::HubDBTableV3

          def list: (
            ?after: String,
            ?archived: bool,
            ?content_type: String,
            ?created_after: Time,
            ?created_at: Time,
            ?created_before: Time,
            ?is_get_localized_schema: bool,
            ?limit: Integer,
            ?sort: ::Array[String],
            ?updated_after: Time,
            ?updated_at: Time,
            ?updated_before: Time,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Cms::HubDBTableV3]

          def delete: (
            String table_id_or_name,
            ?request_options: HubSpotSDK::request_opts
          ) -> nil

          def clone_draft: (
            String table_id_or_name,
            copy_rows: bool,
            is_hubspot_defined: bool,
            ?new_label: String,
            ?new_name: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::HubDBTableV3

          def delete_version: (
            Integer version_id,
            table_id_or_name: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> nil

          def export: (
            String table_id_or_name,
            ?format_: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> StringIO

          def export_draft: (
            String table_id_or_name,
            ?format_: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> StringIO

          def get: (
            String table_id_or_name,
            ?archived: bool,
            ?include_foreign_ids: bool,
            ?is_get_localized_schema: bool,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::HubDBTableV3

          def get_draft: (
            String table_id_or_name,
            ?archived: bool,
            ?include_foreign_ids: bool,
            ?is_get_localized_schema: bool,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::HubDBTableV3

          def import_draft: (
            String table_id_or_name,
            ?config: String,
            ?file: HubSpotSDK::Internal::file_input,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::ImportResult

          def list_draft: (
            ?after: String,
            ?archived: bool,
            ?content_type: String,
            ?created_after: Time,
            ?created_at: Time,
            ?created_before: Time,
            ?is_get_localized_schema: bool,
            ?limit: Integer,
            ?sort: ::Array[String],
            ?updated_after: Time,
            ?updated_at: Time,
            ?updated_before: Time,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Cms::HubDBTableV3]

          def publish_draft: (
            String table_id_or_name,
            ?include_foreign_ids: bool,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::HubDBTableV3

          def reset_draft: (
            String table_id_or_name,
            ?include_foreign_ids: bool,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::HubDBTableV3

          def unpublish: (
            String table_id_or_name,
            ?include_foreign_ids: bool,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::HubDBTableV3

          def update_draft: (
            String table_id_or_name,
            allow_child_tables: bool,
            allow_public_api_access: bool,
            columns: ::Array[HubSpotSDK::Cms::ColumnRequest],
            dynamic_meta_tags: ::Hash[Symbol, Integer],
            enable_child_table_pages: bool,
            label: String,
            name: String,
            use_for_pages: bool,
            ?archived: bool,
            ?include_foreign_ids: bool,
            ?is_get_localized_schema: bool,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::HubDBTableV3

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
