module HubSpotSDK
  module Models
    module Meta
      type collection_response_ip_range_no_paging =
        { results: ::Array[HubSpotSDK::Meta::IPRange] }

      class CollectionResponseIPRangeNoPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Meta::IPRange]

        def initialize: (results: ::Array[HubSpotSDK::Meta::IPRange]) -> void

        def to_hash: -> { results: ::Array[HubSpotSDK::Meta::IPRange] }
      end
    end
  end
end
