module HubSpotSDK
  module Models
    module Meta
      type ip_range =
        {
          cidr: String,
          description: String,
          direction: HubSpotSDK::Models::Meta::IPRange::direction,
          service: HubSpotSDK::Models::Meta::IPRange::service
        }

      class IPRange < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor cidr: String

        attr_accessor description: String

        attr_accessor direction: HubSpotSDK::Models::Meta::IPRange::direction

        attr_accessor service: HubSpotSDK::Models::Meta::IPRange::service

        def initialize: (
          cidr: String,
          description: String,
          direction: HubSpotSDK::Models::Meta::IPRange::direction,
          service: HubSpotSDK::Models::Meta::IPRange::service
        ) -> void

        def to_hash: -> {
          cidr: String,
          description: String,
          direction: HubSpotSDK::Models::Meta::IPRange::direction,
          service: HubSpotSDK::Models::Meta::IPRange::service
        }

        type direction = :EGRESS | :INGRESS

        module Direction
          extend HubSpotSDK::Internal::Type::Enum

          EGRESS: :EGRESS
          INGRESS: :INGRESS

          def self?.values: -> ::Array[HubSpotSDK::Models::Meta::IPRange::direction]
        end

        type service = :API | :DNS | :EMAIL | :TEST_SERVICE | :WEB_SCRAPING

        module Service
          extend HubSpotSDK::Internal::Type::Enum

          API: :API
          DNS: :DNS
          EMAIL: :EMAIL
          TEST_SERVICE: :TEST_SERVICE
          WEB_SCRAPING: :WEB_SCRAPING

          def self?.values: -> ::Array[HubSpotSDK::Models::Meta::IPRange::service]
        end
      end
    end
  end
end
