module HubSpotSDK
  module Models
    module Scheduler
      type collection_response_with_total_external_link_metadata =
        {
          results: ::Array[HubSpotSDK::Scheduler::ExternalLinkMetadata],
          total: Integer,
          paging: HubSpotSDK::Paging
        }

      class CollectionResponseWithTotalExternalLinkMetadata < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Scheduler::ExternalLinkMetadata]

        attr_accessor total: Integer

        attr_reader paging: HubSpotSDK::Paging?

        def paging=: (HubSpotSDK::Paging) -> HubSpotSDK::Paging

        def initialize: (
          results: ::Array[HubSpotSDK::Scheduler::ExternalLinkMetadata],
          total: Integer,
          ?paging: HubSpotSDK::Paging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Scheduler::ExternalLinkMetadata],
          total: Integer,
          paging: HubSpotSDK::Paging
        }
      end
    end
  end
end
