module HubSpotSDK
  module Models
    module Scheduler
      type external_meetings_welcome_screen_info =
        {
          description: String,
          logo_url: String,
          show_welcome_screen: bool,
          title: String,
          use_company_logo: bool
        }

      class ExternalMeetingsWelcomeScreenInfo < HubSpotSDK::Internal::Type::BaseModel
        attr_reader description: String?

        def description=: (String) -> String

        attr_reader logo_url: String?

        def logo_url=: (String) -> String

        attr_reader show_welcome_screen: bool?

        def show_welcome_screen=: (bool) -> bool

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader use_company_logo: bool?

        def use_company_logo=: (bool) -> bool

        def initialize: (
          ?description: String,
          ?logo_url: String,
          ?show_welcome_screen: bool,
          ?title: String,
          ?use_company_logo: bool
        ) -> void

        def to_hash: -> {
          description: String,
          logo_url: String,
          show_welcome_screen: bool,
          title: String,
          use_company_logo: bool
        }
      end
    end
  end
end
