module HubSpotSDK
  module Models
    module Scheduler
      type external_user_busy_times =
        {
          busy_times: ::Array[HubSpotSDK::Scheduler::ExternalTimeRange],
          is_offline: bool,
          meetings_user: HubSpotSDK::Scheduler::ExternalMeetingsUser
        }

      class ExternalUserBusyTimes < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor busy_times: ::Array[HubSpotSDK::Scheduler::ExternalTimeRange]

        attr_accessor is_offline: bool

        attr_accessor meetings_user: HubSpotSDK::Scheduler::ExternalMeetingsUser

        def initialize: (
          busy_times: ::Array[HubSpotSDK::Scheduler::ExternalTimeRange],
          is_offline: bool,
          meetings_user: HubSpotSDK::Scheduler::ExternalMeetingsUser
        ) -> void

        def to_hash: -> {
          busy_times: ::Array[HubSpotSDK::Scheduler::ExternalTimeRange],
          is_offline: bool,
          meetings_user: HubSpotSDK::Scheduler::ExternalMeetingsUser
        }
      end
    end
  end
end
