module HubspotSDK
  module Models
    module Scheduler
      type external_meeting_booking =
        {
          duration: Integer,
          email: String,
          first_name: String,
          form_fields: ::Array[HubspotSDK::Scheduler::ExternalBookingFormField],
          last_name: String,
          legal_consent_responses: ::Array[HubspotSDK::Scheduler::ExternalLegalConsentResponse],
          likely_available_user_ids: ::Array[String],
          slug: String,
          start_time: Time,
          locale: String,
          timezone: String
        }

      class ExternalMeetingBooking < HubspotSDK::Internal::Type::BaseModel
        attr_accessor duration: Integer

        attr_accessor email: String

        attr_accessor first_name: String

        attr_accessor form_fields: ::Array[HubspotSDK::Scheduler::ExternalBookingFormField]

        attr_accessor last_name: String

        attr_accessor legal_consent_responses: ::Array[HubspotSDK::Scheduler::ExternalLegalConsentResponse]

        attr_accessor likely_available_user_ids: ::Array[String]

        attr_accessor slug: String

        attr_accessor start_time: Time

        attr_reader locale: String?

        def locale=: (String) -> String

        attr_reader timezone: String?

        def timezone=: (String) -> String

        def initialize: (
          duration: Integer,
          email: String,
          first_name: String,
          form_fields: ::Array[HubspotSDK::Scheduler::ExternalBookingFormField],
          last_name: String,
          legal_consent_responses: ::Array[HubspotSDK::Scheduler::ExternalLegalConsentResponse],
          likely_available_user_ids: ::Array[String],
          slug: String,
          start_time: Time,
          ?locale: String,
          ?timezone: String
        ) -> void

        def to_hash: -> {
          duration: Integer,
          email: String,
          first_name: String,
          form_fields: ::Array[HubspotSDK::Scheduler::ExternalBookingFormField],
          last_name: String,
          legal_consent_responses: ::Array[HubspotSDK::Scheduler::ExternalLegalConsentResponse],
          likely_available_user_ids: ::Array[String],
          slug: String,
          start_time: Time,
          locale: String,
          timezone: String
        }
      end
    end
  end
end
