module HubSpotSDK
  module Models
    module Scheduler
      type external_legal_consent_options =
        {
          communication_consent_checkboxes: ::Array[HubSpotSDK::Scheduler::ExternalCommunicationConsentCheckbox],
          communication_consent_text: String,
          is_legitimate_interest: bool,
          legitimate_interest_subscription_types: ::Array[Integer],
          privacy_policy_text: String,
          processing_consent_checkbox_label: String,
          processing_consent_footer_text: String,
          processing_consent_text: String,
          processing_consent_type: HubSpotSDK::Models::Scheduler::ExternalLegalConsentOptions::processing_consent_type,
          legitimate_interest_legal_basis: HubSpotSDK::Models::Scheduler::ExternalLegalConsentOptions::legitimate_interest_legal_basis
        }

      class ExternalLegalConsentOptions < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor communication_consent_checkboxes: ::Array[HubSpotSDK::Scheduler::ExternalCommunicationConsentCheckbox]

        attr_accessor communication_consent_text: String

        attr_accessor is_legitimate_interest: bool

        attr_accessor legitimate_interest_subscription_types: ::Array[Integer]

        attr_accessor privacy_policy_text: String

        attr_accessor processing_consent_checkbox_label: String

        attr_accessor processing_consent_footer_text: String

        attr_accessor processing_consent_text: String

        attr_accessor processing_consent_type: HubSpotSDK::Models::Scheduler::ExternalLegalConsentOptions::processing_consent_type

        attr_reader legitimate_interest_legal_basis: HubSpotSDK::Models::Scheduler::ExternalLegalConsentOptions::legitimate_interest_legal_basis?

        def legitimate_interest_legal_basis=: (
          HubSpotSDK::Models::Scheduler::ExternalLegalConsentOptions::legitimate_interest_legal_basis
        ) -> HubSpotSDK::Models::Scheduler::ExternalLegalConsentOptions::legitimate_interest_legal_basis

        def initialize: (
          communication_consent_checkboxes: ::Array[HubSpotSDK::Scheduler::ExternalCommunicationConsentCheckbox],
          communication_consent_text: String,
          is_legitimate_interest: bool,
          legitimate_interest_subscription_types: ::Array[Integer],
          privacy_policy_text: String,
          processing_consent_checkbox_label: String,
          processing_consent_footer_text: String,
          processing_consent_text: String,
          processing_consent_type: HubSpotSDK::Models::Scheduler::ExternalLegalConsentOptions::processing_consent_type,
          ?legitimate_interest_legal_basis: HubSpotSDK::Models::Scheduler::ExternalLegalConsentOptions::legitimate_interest_legal_basis
        ) -> void

        def to_hash: -> {
          communication_consent_checkboxes: ::Array[HubSpotSDK::Scheduler::ExternalCommunicationConsentCheckbox],
          communication_consent_text: String,
          is_legitimate_interest: bool,
          legitimate_interest_subscription_types: ::Array[Integer],
          privacy_policy_text: String,
          processing_consent_checkbox_label: String,
          processing_consent_footer_text: String,
          processing_consent_text: String,
          processing_consent_type: HubSpotSDK::Models::Scheduler::ExternalLegalConsentOptions::processing_consent_type,
          legitimate_interest_legal_basis: HubSpotSDK::Models::Scheduler::ExternalLegalConsentOptions::legitimate_interest_legal_basis
        }

        type processing_consent_type = :IMPLICIT | :REQUIRED_CHECKBOX

        module ProcessingConsentType
          extend HubSpotSDK::Internal::Type::Enum

          IMPLICIT: :IMPLICIT
          REQUIRED_CHECKBOX: :REQUIRED_CHECKBOX

          def self?.values: -> ::Array[HubSpotSDK::Models::Scheduler::ExternalLegalConsentOptions::processing_consent_type]
        end

        type legitimate_interest_legal_basis =
          :CONSENT_WITH_NOTICE
          | :LEGITIMATE_INTEREST_CLIENT
          | :LEGITIMATE_INTEREST_OTHER
          | :LEGITIMATE_INTEREST_PQL
          | :NON_GDPR
          | :PERFORMANCE_OF_CONTRACT
          | :PROCESS_AND_STORE

        module LegitimateInterestLegalBasis
          extend HubSpotSDK::Internal::Type::Enum

          CONSENT_WITH_NOTICE: :CONSENT_WITH_NOTICE
          LEGITIMATE_INTEREST_CLIENT: :LEGITIMATE_INTEREST_CLIENT
          LEGITIMATE_INTEREST_OTHER: :LEGITIMATE_INTEREST_OTHER
          LEGITIMATE_INTEREST_PQL: :LEGITIMATE_INTEREST_PQL
          NON_GDPR: :NON_GDPR
          PERFORMANCE_OF_CONTRACT: :PERFORMANCE_OF_CONTRACT
          PROCESS_AND_STORE: :PROCESS_AND_STORE

          def self?.values: -> ::Array[HubSpotSDK::Models::Scheduler::ExternalLegalConsentOptions::legitimate_interest_legal_basis]
        end
      end
    end
  end
end
