module HubSpotSDK
  module Models
    module Scheduler
      type external_email_reminder_schedule =
        {
          reminders: ::Array[HubSpotSDK::Scheduler::ExternalReminder],
          should_include_invite_description: bool
        }

      class ExternalEmailReminderSchedule < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor reminders: ::Array[HubSpotSDK::Scheduler::ExternalReminder]

        attr_accessor should_include_invite_description: bool

        def initialize: (
          reminders: ::Array[HubSpotSDK::Scheduler::ExternalReminder],
          should_include_invite_description: bool
        ) -> void

        def to_hash: -> {
          reminders: ::Array[HubSpotSDK::Scheduler::ExternalReminder],
          should_include_invite_description: bool
        }
      end
    end
  end
end
