module HubSpotSDK
  module Models
    module Scheduler
      type external_communication_consent_checkbox =
        { communication_type_id: String, label: String, required: bool }

      class ExternalCommunicationConsentCheckbox < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor communication_type_id: String

        attr_accessor label: String

        attr_accessor required: bool

        def initialize: (
          communication_type_id: String,
          label: String,
          required: bool
        ) -> void

        def to_hash: -> {
          communication_type_id: String,
          label: String,
          required: bool
        }
      end
    end
  end
end
