module HubspotSDK
  module Models
    module Scheduler
      type external_calendar_meeting_event_response_properties =
        {
          hs_engagement_source: HubspotSDK::Models::Scheduler::ExternalCalendarMeetingEventResponseProperties::hs_engagement_source,
          hs_engagement_source_id: String,
          hs_meeting_end_time: Time,
          hs_meeting_outcome: String,
          hs_meeting_start_time: Time,
          hs_meeting_title: String,
          hs_timestamp: Time,
          hs_activity_type: String,
          hs_attachment_ids: ::Array[String],
          hs_attendee_owner_ids: ::Array[String],
          hs_include_description_in_reminder: String,
          hs_internal_meeting_notes: String,
          hs_meeting_body: String,
          hs_meeting_external_url: String,
          hs_meeting_location: String,
          hs_meeting_location_type: HubspotSDK::Models::Scheduler::ExternalCalendarMeetingEventResponseProperties::hs_meeting_location_type,
          hs_unique_id: String,
          hubspot_owner_id: String
        }

      class ExternalCalendarMeetingEventResponseProperties < HubspotSDK::Internal::Type::BaseModel
        attr_accessor hs_engagement_source: HubspotSDK::Models::Scheduler::ExternalCalendarMeetingEventResponseProperties::hs_engagement_source

        attr_accessor hs_engagement_source_id: String

        attr_accessor hs_meeting_end_time: Time

        attr_accessor hs_meeting_outcome: String

        attr_accessor hs_meeting_start_time: Time

        attr_accessor hs_meeting_title: String

        attr_accessor hs_timestamp: Time

        attr_reader hs_activity_type: String?

        def hs_activity_type=: (String) -> String

        attr_reader hs_attachment_ids: ::Array[String]?

        def hs_attachment_ids=: (::Array[String]) -> ::Array[String]

        attr_reader hs_attendee_owner_ids: ::Array[String]?

        def hs_attendee_owner_ids=: (::Array[String]) -> ::Array[String]

        attr_reader hs_include_description_in_reminder: String?

        def hs_include_description_in_reminder=: (String) -> String

        attr_reader hs_internal_meeting_notes: String?

        def hs_internal_meeting_notes=: (String) -> String

        attr_reader hs_meeting_body: String?

        def hs_meeting_body=: (String) -> String

        attr_reader hs_meeting_external_url: String?

        def hs_meeting_external_url=: (String) -> String

        attr_reader hs_meeting_location: String?

        def hs_meeting_location=: (String) -> String

        attr_reader hs_meeting_location_type: HubspotSDK::Models::Scheduler::ExternalCalendarMeetingEventResponseProperties::hs_meeting_location_type?

        def hs_meeting_location_type=: (
          HubspotSDK::Models::Scheduler::ExternalCalendarMeetingEventResponseProperties::hs_meeting_location_type
        ) -> HubspotSDK::Models::Scheduler::ExternalCalendarMeetingEventResponseProperties::hs_meeting_location_type

        attr_reader hs_unique_id: String?

        def hs_unique_id=: (String) -> String

        attr_reader hubspot_owner_id: String?

        def hubspot_owner_id=: (String) -> String

        def initialize: (
          hs_engagement_source: HubspotSDK::Models::Scheduler::ExternalCalendarMeetingEventResponseProperties::hs_engagement_source,
          hs_engagement_source_id: String,
          hs_meeting_end_time: Time,
          hs_meeting_outcome: String,
          hs_meeting_start_time: Time,
          hs_meeting_title: String,
          hs_timestamp: Time,
          ?hs_activity_type: String,
          ?hs_attachment_ids: ::Array[String],
          ?hs_attendee_owner_ids: ::Array[String],
          ?hs_include_description_in_reminder: String,
          ?hs_internal_meeting_notes: String,
          ?hs_meeting_body: String,
          ?hs_meeting_external_url: String,
          ?hs_meeting_location: String,
          ?hs_meeting_location_type: HubspotSDK::Models::Scheduler::ExternalCalendarMeetingEventResponseProperties::hs_meeting_location_type,
          ?hs_unique_id: String,
          ?hubspot_owner_id: String
        ) -> void

        def to_hash: -> {
          hs_engagement_source: HubspotSDK::Models::Scheduler::ExternalCalendarMeetingEventResponseProperties::hs_engagement_source,
          hs_engagement_source_id: String,
          hs_meeting_end_time: Time,
          hs_meeting_outcome: String,
          hs_meeting_start_time: Time,
          hs_meeting_title: String,
          hs_timestamp: Time,
          hs_activity_type: String,
          hs_attachment_ids: ::Array[String],
          hs_attendee_owner_ids: ::Array[String],
          hs_include_description_in_reminder: String,
          hs_internal_meeting_notes: String,
          hs_meeting_body: String,
          hs_meeting_external_url: String,
          hs_meeting_location: String,
          hs_meeting_location_type: HubspotSDK::Models::Scheduler::ExternalCalendarMeetingEventResponseProperties::hs_meeting_location_type,
          hs_unique_id: String,
          hubspot_owner_id: String
        }

        type hs_engagement_source =
          :UNKNOWN
          | :IMPORT
          | :API
          | :FORM
          | :ANALYTICS
          | :MIGRATION
          | :SALESFORCE
          | :INTEGRATION
          | :CONTACTS_WEB
          | :WAL_INCREMENTAL
          | :TASK
          | :EMAIL
          | :WORKFLOWS
          | :CALCULATED
          | :SOCIAL
          | :BATCH_UPDATE
          | :SIGNALS
          | :BIDEN
          | :DEFAULT
          | :COMPANIES
          | :DEALS
          | :ASSISTS
          | :PRESENTATIONS
          | :TALLY
          | :SIDEKICK
          | :CRM_UI
          | :MERGE_CONTACTS
          | :PORTAL_USER_ASSOCIATOR
          | :INTEGRATIONS_PLATFORM
          | :BCC_TO_CRM
          | :FORWARD_TO_CRM
          | :ENGAGEMENTS
          | :SALES
          | :HEISENBERG
          | :LEADIN
          | :GMAIL_INTEGRATION
          | :ACADEMY
          | :SALES_MESSAGES
          | :AVATARS_SERVICE
          | :MERGE_COMPANIES
          | :SEQUENCES
          | :COMPANY_FAMILIES
          | :MOBILE_IOS
          | :MOBILE_ANDROID
          | :CONTACTS
          | :ASSOCIATIONS
          | :EXTENSION
          | :SUCCESS
          | :BOT
          | :INTEGRATIONS_SYNC
          | :AUTOMATION_PLATFORM
          | :CONVERSATIONS
          | :EMAIL_INTEGRATION
          | :CONTENT_MEMBERSHIP
          | :QUOTES
          | :BET_ASSIGNMENT
          | :QUOTAS
          | :BET_CRM_CONNECTOR
          | :MEETINGS
          | :MERGE_OBJECTS
          | :RECYCLING_BIN
          | :ADS
          | :AI_GROUP
          | :COMMUNICATOR
          | :SETTINGS
          | :PROPERTY_SETTINGS
          | :PIPELINE_SETTINGS
          | :COMPANY_INSIGHTS
          | :BEHAVIORAL_EVENTS
          | :PAYMENTS
          | :GOALS
          | :PORTAL_OBJECT_SYNC
          | :APPROVALS
          | :FILE_MANAGER
          | :MARKETPLACE
          | :INTERNAL_PROCESSING
          | :FORECASTING
          | :SLACK_INTEGRATION
          | :CRM_UI_BULK_ACTION
          | :WORKFLOW_CONTACT_DELETE_ACTION
          | :ACCEPTANCE_TEST
          | :PLAYBOOKS
          | :CHATSPOT
          | :FLYWHEEL_PRODUCT_DATA_SYNC
          | :HELP_DESK
          | :BILLING
          | :DATA_ENRICHMENT
          | :AUTOMATION_JOURNEY
          | :MICROAPPS
          | :INTENT
          | :PROSPECTING_AGENT
          | :CENTRAL_EXCHANGE_RATES
          | :HELP_DESK_AI
          | :CONVERSATIONAL_ENRICHMENT
          | :CRM_PROCESSES_PLATFORM
          | :CLONE_OBJECTS
          | :MARKET_SOURCING
          | :DATASET
          | :PROPERTY_RESTORE
          | :EMAIL_INBOX_IMPORT
          | :CUSTOMER_AGENT
          | :LEGAL_BASIS_REMEDIATION
          | :AUTO_ASSOCIATE_BY_DOMAIN
          | :ACTIVITY_AUTO_ASSOCIATE
          | :PRIMARY_AUTOMATION
          | :DELETE_OBJECTS
          | :RESTORE_OBJECTS

        module HsEngagementSource
          extend HubspotSDK::Internal::Type::Enum

          UNKNOWN: :UNKNOWN
          IMPORT: :IMPORT
          API: :API
          FORM: :FORM
          ANALYTICS: :ANALYTICS
          MIGRATION: :MIGRATION
          SALESFORCE: :SALESFORCE
          INTEGRATION: :INTEGRATION
          CONTACTS_WEB: :CONTACTS_WEB
          WAL_INCREMENTAL: :WAL_INCREMENTAL
          TASK: :TASK
          EMAIL: :EMAIL
          WORKFLOWS: :WORKFLOWS
          CALCULATED: :CALCULATED
          SOCIAL: :SOCIAL
          BATCH_UPDATE: :BATCH_UPDATE
          SIGNALS: :SIGNALS
          BIDEN: :BIDEN
          DEFAULT: :DEFAULT
          COMPANIES: :COMPANIES
          DEALS: :DEALS
          ASSISTS: :ASSISTS
          PRESENTATIONS: :PRESENTATIONS
          TALLY: :TALLY
          SIDEKICK: :SIDEKICK
          CRM_UI: :CRM_UI
          MERGE_CONTACTS: :MERGE_CONTACTS
          PORTAL_USER_ASSOCIATOR: :PORTAL_USER_ASSOCIATOR
          INTEGRATIONS_PLATFORM: :INTEGRATIONS_PLATFORM
          BCC_TO_CRM: :BCC_TO_CRM
          FORWARD_TO_CRM: :FORWARD_TO_CRM
          ENGAGEMENTS: :ENGAGEMENTS
          SALES: :SALES
          HEISENBERG: :HEISENBERG
          LEADIN: :LEADIN
          GMAIL_INTEGRATION: :GMAIL_INTEGRATION
          ACADEMY: :ACADEMY
          SALES_MESSAGES: :SALES_MESSAGES
          AVATARS_SERVICE: :AVATARS_SERVICE
          MERGE_COMPANIES: :MERGE_COMPANIES
          SEQUENCES: :SEQUENCES
          COMPANY_FAMILIES: :COMPANY_FAMILIES
          MOBILE_IOS: :MOBILE_IOS
          MOBILE_ANDROID: :MOBILE_ANDROID
          CONTACTS: :CONTACTS
          ASSOCIATIONS: :ASSOCIATIONS
          EXTENSION: :EXTENSION
          SUCCESS: :SUCCESS
          BOT: :BOT
          INTEGRATIONS_SYNC: :INTEGRATIONS_SYNC
          AUTOMATION_PLATFORM: :AUTOMATION_PLATFORM
          CONVERSATIONS: :CONVERSATIONS
          EMAIL_INTEGRATION: :EMAIL_INTEGRATION
          CONTENT_MEMBERSHIP: :CONTENT_MEMBERSHIP
          QUOTES: :QUOTES
          BET_ASSIGNMENT: :BET_ASSIGNMENT
          QUOTAS: :QUOTAS
          BET_CRM_CONNECTOR: :BET_CRM_CONNECTOR
          MEETINGS: :MEETINGS
          MERGE_OBJECTS: :MERGE_OBJECTS
          RECYCLING_BIN: :RECYCLING_BIN
          ADS: :ADS
          AI_GROUP: :AI_GROUP
          COMMUNICATOR: :COMMUNICATOR
          SETTINGS: :SETTINGS
          PROPERTY_SETTINGS: :PROPERTY_SETTINGS
          PIPELINE_SETTINGS: :PIPELINE_SETTINGS
          COMPANY_INSIGHTS: :COMPANY_INSIGHTS
          BEHAVIORAL_EVENTS: :BEHAVIORAL_EVENTS
          PAYMENTS: :PAYMENTS
          GOALS: :GOALS
          PORTAL_OBJECT_SYNC: :PORTAL_OBJECT_SYNC
          APPROVALS: :APPROVALS
          FILE_MANAGER: :FILE_MANAGER
          MARKETPLACE: :MARKETPLACE
          INTERNAL_PROCESSING: :INTERNAL_PROCESSING
          FORECASTING: :FORECASTING
          SLACK_INTEGRATION: :SLACK_INTEGRATION
          CRM_UI_BULK_ACTION: :CRM_UI_BULK_ACTION
          WORKFLOW_CONTACT_DELETE_ACTION: :WORKFLOW_CONTACT_DELETE_ACTION
          ACCEPTANCE_TEST: :ACCEPTANCE_TEST
          PLAYBOOKS: :PLAYBOOKS
          CHATSPOT: :CHATSPOT
          FLYWHEEL_PRODUCT_DATA_SYNC: :FLYWHEEL_PRODUCT_DATA_SYNC
          HELP_DESK: :HELP_DESK
          BILLING: :BILLING
          DATA_ENRICHMENT: :DATA_ENRICHMENT
          AUTOMATION_JOURNEY: :AUTOMATION_JOURNEY
          MICROAPPS: :MICROAPPS
          INTENT: :INTENT
          PROSPECTING_AGENT: :PROSPECTING_AGENT
          CENTRAL_EXCHANGE_RATES: :CENTRAL_EXCHANGE_RATES
          HELP_DESK_AI: :HELP_DESK_AI
          CONVERSATIONAL_ENRICHMENT: :CONVERSATIONAL_ENRICHMENT
          CRM_PROCESSES_PLATFORM: :CRM_PROCESSES_PLATFORM
          CLONE_OBJECTS: :CLONE_OBJECTS
          MARKET_SOURCING: :MARKET_SOURCING
          DATASET: :DATASET
          PROPERTY_RESTORE: :PROPERTY_RESTORE
          EMAIL_INBOX_IMPORT: :EMAIL_INBOX_IMPORT
          CUSTOMER_AGENT: :CUSTOMER_AGENT
          LEGAL_BASIS_REMEDIATION: :LEGAL_BASIS_REMEDIATION
          AUTO_ASSOCIATE_BY_DOMAIN: :AUTO_ASSOCIATE_BY_DOMAIN
          ACTIVITY_AUTO_ASSOCIATE: :ACTIVITY_AUTO_ASSOCIATE
          PRIMARY_AUTOMATION: :PRIMARY_AUTOMATION
          DELETE_OBJECTS: :DELETE_OBJECTS
          RESTORE_OBJECTS: :RESTORE_OBJECTS

          def self?.values: -> ::Array[HubspotSDK::Models::Scheduler::ExternalCalendarMeetingEventResponseProperties::hs_engagement_source]
        end

        type hs_meeting_location_type = :PHONE | :ADDRESS | :CUSTOM

        module HsMeetingLocationType
          extend HubspotSDK::Internal::Type::Enum

          PHONE: :PHONE
          ADDRESS: :ADDRESS
          CUSTOM: :CUSTOM

          def self?.values: -> ::Array[HubspotSDK::Models::Scheduler::ExternalCalendarMeetingEventResponseProperties::hs_meeting_location_type]
        end
      end
    end
  end
end
