module HubspotSDK
  module Models
    module Scheduler
      type external_meetings_link_settings =
        {
          availability: ::Hash[Symbol, HubspotSDK::Scheduler::ExternalClosedRange],
          durations: ::Array[Integer],
          form_fields: ::Array[HubspotSDK::Scheduler::ExternalLinkFormField],
          legal_consent_enabled: bool,
          meeting_buffer_time: Integer,
          owner_prioritized: bool,
          start_time_increment_minutes: HubspotSDK::Models::Scheduler::ExternalMeetingsLinkSettings::start_time_increment_minutes,
          weeks_to_advertise: Integer,
          custom_availability_end_date: Integer,
          custom_availability_start_date: Integer,
          display_info: HubspotSDK::Scheduler::ExternalLinkDisplayInfo,
          guest_settings: HubspotSDK::Scheduler::ExternalGuestSettings,
          language: String,
          legal_consent_options: HubspotSDK::Scheduler::ExternalLegalConsentOptions,
          locale: String,
          location: String,
          redirect_url: String,
          welcome_screen_info: HubspotSDK::Scheduler::ExternalMeetingsWelcomeScreenInfo
        }

      class ExternalMeetingsLinkSettings < HubspotSDK::Internal::Type::BaseModel
        attr_accessor availability: ::Hash[Symbol, HubspotSDK::Scheduler::ExternalClosedRange]

        attr_accessor durations: ::Array[Integer]

        attr_accessor form_fields: ::Array[HubspotSDK::Scheduler::ExternalLinkFormField]

        attr_accessor legal_consent_enabled: bool

        attr_accessor meeting_buffer_time: Integer

        attr_accessor owner_prioritized: bool

        attr_accessor start_time_increment_minutes: HubspotSDK::Models::Scheduler::ExternalMeetingsLinkSettings::start_time_increment_minutes

        attr_accessor weeks_to_advertise: Integer

        attr_reader custom_availability_end_date: Integer?

        def custom_availability_end_date=: (Integer) -> Integer

        attr_reader custom_availability_start_date: Integer?

        def custom_availability_start_date=: (Integer) -> Integer

        attr_reader display_info: HubspotSDK::Scheduler::ExternalLinkDisplayInfo?

        def display_info=: (
          HubspotSDK::Scheduler::ExternalLinkDisplayInfo
        ) -> HubspotSDK::Scheduler::ExternalLinkDisplayInfo

        attr_reader guest_settings: HubspotSDK::Scheduler::ExternalGuestSettings?

        def guest_settings=: (
          HubspotSDK::Scheduler::ExternalGuestSettings
        ) -> HubspotSDK::Scheduler::ExternalGuestSettings

        attr_reader language: String?

        def language=: (String) -> String

        attr_reader legal_consent_options: HubspotSDK::Scheduler::ExternalLegalConsentOptions?

        def legal_consent_options=: (
          HubspotSDK::Scheduler::ExternalLegalConsentOptions
        ) -> HubspotSDK::Scheduler::ExternalLegalConsentOptions

        attr_reader locale: String?

        def locale=: (String) -> String

        attr_reader location: String?

        def location=: (String) -> String

        attr_reader redirect_url: String?

        def redirect_url=: (String) -> String

        attr_reader welcome_screen_info: HubspotSDK::Scheduler::ExternalMeetingsWelcomeScreenInfo?

        def welcome_screen_info=: (
          HubspotSDK::Scheduler::ExternalMeetingsWelcomeScreenInfo
        ) -> HubspotSDK::Scheduler::ExternalMeetingsWelcomeScreenInfo

        def initialize: (
          availability: ::Hash[Symbol, HubspotSDK::Scheduler::ExternalClosedRange],
          durations: ::Array[Integer],
          form_fields: ::Array[HubspotSDK::Scheduler::ExternalLinkFormField],
          legal_consent_enabled: bool,
          meeting_buffer_time: Integer,
          owner_prioritized: bool,
          start_time_increment_minutes: HubspotSDK::Models::Scheduler::ExternalMeetingsLinkSettings::start_time_increment_minutes,
          weeks_to_advertise: Integer,
          ?custom_availability_end_date: Integer,
          ?custom_availability_start_date: Integer,
          ?display_info: HubspotSDK::Scheduler::ExternalLinkDisplayInfo,
          ?guest_settings: HubspotSDK::Scheduler::ExternalGuestSettings,
          ?language: String,
          ?legal_consent_options: HubspotSDK::Scheduler::ExternalLegalConsentOptions,
          ?locale: String,
          ?location: String,
          ?redirect_url: String,
          ?welcome_screen_info: HubspotSDK::Scheduler::ExternalMeetingsWelcomeScreenInfo
        ) -> void

        def to_hash: -> {
          availability: ::Hash[Symbol, HubspotSDK::Scheduler::ExternalClosedRange],
          durations: ::Array[Integer],
          form_fields: ::Array[HubspotSDK::Scheduler::ExternalLinkFormField],
          legal_consent_enabled: bool,
          meeting_buffer_time: Integer,
          owner_prioritized: bool,
          start_time_increment_minutes: HubspotSDK::Models::Scheduler::ExternalMeetingsLinkSettings::start_time_increment_minutes,
          weeks_to_advertise: Integer,
          custom_availability_end_date: Integer,
          custom_availability_start_date: Integer,
          display_info: HubspotSDK::Scheduler::ExternalLinkDisplayInfo,
          guest_settings: HubspotSDK::Scheduler::ExternalGuestSettings,
          language: String,
          legal_consent_options: HubspotSDK::Scheduler::ExternalLegalConsentOptions,
          locale: String,
          location: String,
          redirect_url: String,
          welcome_screen_info: HubspotSDK::Scheduler::ExternalMeetingsWelcomeScreenInfo
        }

        type start_time_increment_minutes =
          :FIFTEEN
          | :FIVE
          | :FORTY_FIVE
          | :MEETING_DURATION
          | :NINETY
          | :ONE_HUNDRED_TWENTY
          | :SIXTY
          | :TEN
          | :THIRTY
          | :TWENTY

        module StartTimeIncrementMinutes
          extend HubspotSDK::Internal::Type::Enum

          FIFTEEN: :FIFTEEN
          FIVE: :FIVE
          FORTY_FIVE: :FORTY_FIVE
          MEETING_DURATION: :MEETING_DURATION
          NINETY: :NINETY
          ONE_HUNDRED_TWENTY: :ONE_HUNDRED_TWENTY
          SIXTY: :SIXTY
          TEN: :TEN
          THIRTY: :THIRTY
          TWENTY: :TWENTY

          def self?.values: -> ::Array[HubspotSDK::Models::Scheduler::ExternalMeetingsLinkSettings::start_time_increment_minutes]
        end
      end
    end
  end
end
