module HubSpotSDK
  module Models
    module Scheduler
      type external_link_display_info =
        {
          avatar: String,
          company_avatar: String,
          headline: String,
          public_display_avatar_option: HubSpotSDK::Models::Scheduler::ExternalLinkDisplayInfo::public_display_avatar_option
        }

      class ExternalLinkDisplayInfo < HubSpotSDK::Internal::Type::BaseModel
        attr_reader avatar: String?

        def avatar=: (String) -> String

        attr_reader company_avatar: String?

        def company_avatar=: (String) -> String

        attr_reader headline: String?

        def headline=: (String) -> String

        attr_reader public_display_avatar_option: HubSpotSDK::Models::Scheduler::ExternalLinkDisplayInfo::public_display_avatar_option?

        def public_display_avatar_option=: (
          HubSpotSDK::Models::Scheduler::ExternalLinkDisplayInfo::public_display_avatar_option
        ) -> HubSpotSDK::Models::Scheduler::ExternalLinkDisplayInfo::public_display_avatar_option

        def initialize: (
          ?avatar: String,
          ?company_avatar: String,
          ?headline: String,
          ?public_display_avatar_option: HubSpotSDK::Models::Scheduler::ExternalLinkDisplayInfo::public_display_avatar_option
        ) -> void

        def to_hash: -> {
          avatar: String,
          company_avatar: String,
          headline: String,
          public_display_avatar_option: HubSpotSDK::Models::Scheduler::ExternalLinkDisplayInfo::public_display_avatar_option
        }

        type public_display_avatar_option =
          :COMPANY_LOGO | :CUSTOM_AVATAR | :PROFILE_IMAGE

        module PublicDisplayAvatarOption
          extend HubSpotSDK::Internal::Type::Enum

          COMPANY_LOGO: :COMPANY_LOGO
          CUSTOM_AVATAR: :CUSTOM_AVATAR
          PROFILE_IMAGE: :PROFILE_IMAGE

          def self?.values: -> ::Array[HubSpotSDK::Models::Scheduler::ExternalLinkDisplayInfo::public_display_avatar_option]
        end
      end
    end
  end
end
