module HubSpotSDK
  module Models
    module Scheduler
      type external_calender_meeting_event_response =
        {
          id: String,
          created_at: Time,
          last_updated_at: Time,
          properties: HubSpotSDK::Scheduler::ExternalCalendarMeetingEventResponseProperties
        }

      class ExternalCalenderMeetingEventResponse < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor last_updated_at: Time

        attr_accessor properties: HubSpotSDK::Scheduler::ExternalCalendarMeetingEventResponseProperties

        def initialize: (
          id: String,
          created_at: Time,
          last_updated_at: Time,
          properties: HubSpotSDK::Scheduler::ExternalCalendarMeetingEventResponseProperties
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          last_updated_at: Time,
          properties: HubSpotSDK::Scheduler::ExternalCalendarMeetingEventResponseProperties
        }
      end
    end
  end
end
