module HubSpotSDK
  module Models
    module Scheduler
      type external_meeting_availability =
        { end_millis_utc: Integer, start_millis_utc: Integer }

      class ExternalMeetingAvailability < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor end_millis_utc: Integer

        attr_accessor start_millis_utc: Integer

        def initialize: (
          end_millis_utc: Integer,
          start_millis_utc: Integer
        ) -> void

        def to_hash: -> { end_millis_utc: Integer, start_millis_utc: Integer }
      end
    end
  end
end
