module HubspotSDK
  module Models
    module Scheduler
      type external_booking_info =
        {
          all_users_busy_times: ::Array[HubspotSDK::Scheduler::ExternalUserBusyTimes],
          custom_params: HubspotSDK::Scheduler::ExternalMeetingsLinkSettings,
          is_offline: bool,
          link_id: String,
          link_type: HubspotSDK::Models::Scheduler::ExternalBookingInfo::link_type,
          branding_metadata: HubspotSDK::Scheduler::ExternalBrandingMetadata,
          link_availability: HubspotSDK::Scheduler::ExternalLinkAvailability
        }

      class ExternalBookingInfo < HubspotSDK::Internal::Type::BaseModel
        attr_accessor all_users_busy_times: ::Array[HubspotSDK::Scheduler::ExternalUserBusyTimes]

        attr_accessor custom_params: HubspotSDK::Scheduler::ExternalMeetingsLinkSettings

        attr_accessor is_offline: bool

        attr_accessor link_id: String

        attr_accessor link_type: HubspotSDK::Models::Scheduler::ExternalBookingInfo::link_type

        attr_reader branding_metadata: HubspotSDK::Scheduler::ExternalBrandingMetadata?

        def branding_metadata=: (
          HubspotSDK::Scheduler::ExternalBrandingMetadata
        ) -> HubspotSDK::Scheduler::ExternalBrandingMetadata

        attr_reader link_availability: HubspotSDK::Scheduler::ExternalLinkAvailability?

        def link_availability=: (
          HubspotSDK::Scheduler::ExternalLinkAvailability
        ) -> HubspotSDK::Scheduler::ExternalLinkAvailability

        def initialize: (
          all_users_busy_times: ::Array[HubspotSDK::Scheduler::ExternalUserBusyTimes],
          custom_params: HubspotSDK::Scheduler::ExternalMeetingsLinkSettings,
          is_offline: bool,
          link_id: String,
          link_type: HubspotSDK::Models::Scheduler::ExternalBookingInfo::link_type,
          ?branding_metadata: HubspotSDK::Scheduler::ExternalBrandingMetadata,
          ?link_availability: HubspotSDK::Scheduler::ExternalLinkAvailability
        ) -> void

        def to_hash: -> {
          all_users_busy_times: ::Array[HubspotSDK::Scheduler::ExternalUserBusyTimes],
          custom_params: HubspotSDK::Scheduler::ExternalMeetingsLinkSettings,
          is_offline: bool,
          link_id: String,
          link_type: HubspotSDK::Models::Scheduler::ExternalBookingInfo::link_type,
          branding_metadata: HubspotSDK::Scheduler::ExternalBrandingMetadata,
          link_availability: HubspotSDK::Scheduler::ExternalLinkAvailability
        }

        type link_type =
          :PERSONAL_LINK | :GROUP_CALENDAR | :ROUND_ROBIN_CALENDAR

        module LinkType
          extend HubspotSDK::Internal::Type::Enum

          PERSONAL_LINK: :PERSONAL_LINK
          GROUP_CALENDAR: :GROUP_CALENDAR
          ROUND_ROBIN_CALENDAR: :ROUND_ROBIN_CALENDAR

          def self?.values: -> ::Array[HubspotSDK::Models::Scheduler::ExternalBookingInfo::link_type]
        end
      end
    end
  end
end
