module HubSpotSDK
  module Models
    module Scheduler
      type external_link_availability_and_busy_times =
        {
          all_users_busy_times: ::Array[HubSpotSDK::Scheduler::ExternalUserBusyTimes],
          link_availability: HubSpotSDK::Scheduler::ExternalLinkAvailability
        }

      class ExternalLinkAvailabilityAndBusyTimes < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor all_users_busy_times: ::Array[HubSpotSDK::Scheduler::ExternalUserBusyTimes]

        attr_reader link_availability: HubSpotSDK::Scheduler::ExternalLinkAvailability?

        def link_availability=: (
          HubSpotSDK::Scheduler::ExternalLinkAvailability
        ) -> HubSpotSDK::Scheduler::ExternalLinkAvailability

        def initialize: (
          all_users_busy_times: ::Array[HubSpotSDK::Scheduler::ExternalUserBusyTimes],
          ?link_availability: HubSpotSDK::Scheduler::ExternalLinkAvailability
        ) -> void

        def to_hash: -> {
          all_users_busy_times: ::Array[HubSpotSDK::Scheduler::ExternalUserBusyTimes],
          link_availability: HubSpotSDK::Scheduler::ExternalLinkAvailability
        }
      end
    end
  end
end
