module HubSpotSDK
  module Models
    module Scheduler
      type external_legal_consent_response =
        { communication_type_id: String, consented: bool }

      class ExternalLegalConsentResponse < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor communication_type_id: String

        attr_accessor consented: bool

        def initialize: (communication_type_id: String, consented: bool) -> void

        def to_hash: -> { communication_type_id: String, consented: bool }
      end
    end
  end
end
