module HubspotSDK
  module Models
    module Scheduler
      type external_link_metadata =
        {
          id: String,
          created_at: Time,
          default_link: bool,
          link: String,
          organizer_user_id: String,
          slug: String,
          type: HubspotSDK::Models::Scheduler::ExternalLinkMetadata::type_,
          user_ids_of_link_members: ::Array[String],
          name: String,
          updated_at: Time
        }

      class ExternalLinkMetadata < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor default_link: bool

        attr_accessor link: String

        attr_accessor organizer_user_id: String

        attr_accessor slug: String

        attr_accessor type: HubspotSDK::Models::Scheduler::ExternalLinkMetadata::type_

        attr_accessor user_ids_of_link_members: ::Array[String]

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader updated_at: Time?

        def updated_at=: (Time) -> Time

        def initialize: (
          id: String,
          created_at: Time,
          default_link: bool,
          link: String,
          organizer_user_id: String,
          slug: String,
          type: HubspotSDK::Models::Scheduler::ExternalLinkMetadata::type_,
          user_ids_of_link_members: ::Array[String],
          ?name: String,
          ?updated_at: Time
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          default_link: bool,
          link: String,
          organizer_user_id: String,
          slug: String,
          type: HubspotSDK::Models::Scheduler::ExternalLinkMetadata::type_,
          user_ids_of_link_members: ::Array[String],
          name: String,
          updated_at: Time
        }

        type type_ = :GROUP_CALENDAR | :PERSONAL_LINK | :ROUND_ROBIN_CALENDAR

        module Type
          extend HubspotSDK::Internal::Type::Enum

          GROUP_CALENDAR: :GROUP_CALENDAR
          PERSONAL_LINK: :PERSONAL_LINK
          ROUND_ROBIN_CALENDAR: :ROUND_ROBIN_CALENDAR

          def self?.values: -> ::Array[HubspotSDK::Models::Scheduler::ExternalLinkMetadata::type_]
        end
      end
    end
  end
end
