module HubSpotSDK
  module Models
    module Scheduler
      type external_booking_info =
        {
          all_users_busy_times: ::Array[HubSpotSDK::Scheduler::ExternalUserBusyTimes],
          custom_params: HubSpotSDK::Scheduler::ExternalMeetingsLinkSettings,
          is_offline: bool,
          link_id: String,
          link_type: HubSpotSDK::Models::Scheduler::ExternalBookingInfo::link_type,
          branding_metadata: HubSpotSDK::Scheduler::ExternalBrandingMetadata,
          link_availability: HubSpotSDK::Scheduler::ExternalLinkAvailability
        }

      class ExternalBookingInfo < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor all_users_busy_times: ::Array[HubSpotSDK::Scheduler::ExternalUserBusyTimes]

        attr_accessor custom_params: HubSpotSDK::Scheduler::ExternalMeetingsLinkSettings

        attr_accessor is_offline: bool

        attr_accessor link_id: String

        attr_accessor link_type: HubSpotSDK::Models::Scheduler::ExternalBookingInfo::link_type

        attr_reader branding_metadata: HubSpotSDK::Scheduler::ExternalBrandingMetadata?

        def branding_metadata=: (
          HubSpotSDK::Scheduler::ExternalBrandingMetadata
        ) -> HubSpotSDK::Scheduler::ExternalBrandingMetadata

        attr_reader link_availability: HubSpotSDK::Scheduler::ExternalLinkAvailability?

        def link_availability=: (
          HubSpotSDK::Scheduler::ExternalLinkAvailability
        ) -> HubSpotSDK::Scheduler::ExternalLinkAvailability

        def initialize: (
          all_users_busy_times: ::Array[HubSpotSDK::Scheduler::ExternalUserBusyTimes],
          custom_params: HubSpotSDK::Scheduler::ExternalMeetingsLinkSettings,
          is_offline: bool,
          link_id: String,
          link_type: HubSpotSDK::Models::Scheduler::ExternalBookingInfo::link_type,
          ?branding_metadata: HubSpotSDK::Scheduler::ExternalBrandingMetadata,
          ?link_availability: HubSpotSDK::Scheduler::ExternalLinkAvailability
        ) -> void

        def to_hash: -> {
          all_users_busy_times: ::Array[HubSpotSDK::Scheduler::ExternalUserBusyTimes],
          custom_params: HubSpotSDK::Scheduler::ExternalMeetingsLinkSettings,
          is_offline: bool,
          link_id: String,
          link_type: HubSpotSDK::Models::Scheduler::ExternalBookingInfo::link_type,
          branding_metadata: HubSpotSDK::Scheduler::ExternalBrandingMetadata,
          link_availability: HubSpotSDK::Scheduler::ExternalLinkAvailability
        }

        type link_type =
          :GROUP_CALENDAR | :PERSONAL_LINK | :ROUND_ROBIN_CALENDAR

        module LinkType
          extend HubSpotSDK::Internal::Type::Enum

          GROUP_CALENDAR: :GROUP_CALENDAR
          PERSONAL_LINK: :PERSONAL_LINK
          ROUND_ROBIN_CALENDAR: :ROUND_ROBIN_CALENDAR

          def self?.values: -> ::Array[HubSpotSDK::Models::Scheduler::ExternalBookingInfo::link_type]
        end
      end
    end
  end
end
