module HubspotSDK
  module Models
    module Scheduler
      type external_calendar_meeting_event_create_request =
        {
          associations: ::Array[HubspotSDK::Scheduler::ExternalAssociationCreateRequest],
          email_reminder_schedule: HubspotSDK::Scheduler::ExternalEmailReminderSchedule,
          properties: HubspotSDK::Scheduler::ExternalCalendarMeetingEventCreateProperties,
          timezone: String
        }

      class ExternalCalendarMeetingEventCreateRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor associations: ::Array[HubspotSDK::Scheduler::ExternalAssociationCreateRequest]

        attr_accessor email_reminder_schedule: HubspotSDK::Scheduler::ExternalEmailReminderSchedule

        attr_accessor properties: HubspotSDK::Scheduler::ExternalCalendarMeetingEventCreateProperties

        attr_accessor timezone: String

        def initialize: (
          associations: ::Array[HubspotSDK::Scheduler::ExternalAssociationCreateRequest],
          email_reminder_schedule: HubspotSDK::Scheduler::ExternalEmailReminderSchedule,
          properties: HubspotSDK::Scheduler::ExternalCalendarMeetingEventCreateProperties,
          timezone: String
        ) -> void

        def to_hash: -> {
          associations: ::Array[HubspotSDK::Scheduler::ExternalAssociationCreateRequest],
          email_reminder_schedule: HubspotSDK::Scheduler::ExternalEmailReminderSchedule,
          properties: HubspotSDK::Scheduler::ExternalCalendarMeetingEventCreateProperties,
          timezone: String
        }
      end
    end
  end
end
