module HubspotSDK
  module Models
    module Scheduler
      type external_association_create_request =
        {
          to: HubspotSDK::PublicObjectID,
          types: ::Array[HubspotSDK::AssociationSpec]
        }

      class ExternalAssociationCreateRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor to: HubspotSDK::PublicObjectID

        attr_accessor types: ::Array[HubspotSDK::AssociationSpec]

        def initialize: (
          to: HubspotSDK::PublicObjectID,
          types: ::Array[HubspotSDK::AssociationSpec]
        ) -> void

        def to_hash: -> {
          to: HubspotSDK::PublicObjectID,
          types: ::Array[HubspotSDK::AssociationSpec]
        }
      end
    end
  end
end
