module HubspotSDK
  module Models
    module Scheduler
      type external_meetings_user =
        {
          id: String,
          calendar_provider: String,
          is_sales_starter: bool,
          user_id: String,
          user_profile: HubspotSDK::Scheduler::ExternalUserProfile
        }

      class ExternalMeetingsUser < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor calendar_provider: String

        attr_accessor is_sales_starter: bool

        attr_accessor user_id: String

        attr_accessor user_profile: HubspotSDK::Scheduler::ExternalUserProfile

        def initialize: (
          id: String,
          calendar_provider: String,
          is_sales_starter: bool,
          user_id: String,
          user_profile: HubspotSDK::Scheduler::ExternalUserProfile
        ) -> void

        def to_hash: -> {
          id: String,
          calendar_provider: String,
          is_sales_starter: bool,
          user_id: String,
          user_profile: HubspotSDK::Scheduler::ExternalUserProfile
        }
      end
    end
  end
end
