module HubSpotSDK
  module Models
    module Scheduler
      type external_guest_settings =
        { can_add_guests: bool, max_guest_count: Integer }

      class ExternalGuestSettings < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor can_add_guests: bool

        attr_accessor max_guest_count: Integer

        def initialize: (can_add_guests: bool, max_guest_count: Integer) -> void

        def to_hash: -> { can_add_guests: bool, max_guest_count: Integer }
      end
    end
  end
end
