module HubSpotSDK
  module Models
    module Scheduler
      type external_association_create_request =
        {
          to: HubSpotSDK::PublicObjectID,
          types: ::Array[HubSpotSDK::AssociationSpec]
        }

      class ExternalAssociationCreateRequest < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor to: HubSpotSDK::PublicObjectID

        attr_accessor types: ::Array[HubSpotSDK::AssociationSpec]

        def initialize: (
          to: HubSpotSDK::PublicObjectID,
          types: ::Array[HubSpotSDK::AssociationSpec]
        ) -> void

        def to_hash: -> {
          to: HubSpotSDK::PublicObjectID,
          types: ::Array[HubSpotSDK::AssociationSpec]
        }
      end
    end
  end
end
