module HubSpotSDK
  module Models
    module Scheduler
      type external_link_availability_for_duration =
        {
          availabilities: ::Array[HubSpotSDK::Scheduler::ExternalMeetingAvailability],
          meeting_duration_millis: Integer
        }

      class ExternalLinkAvailabilityForDuration < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor availabilities: ::Array[HubSpotSDK::Scheduler::ExternalMeetingAvailability]

        attr_accessor meeting_duration_millis: Integer

        def initialize: (
          availabilities: ::Array[HubSpotSDK::Scheduler::ExternalMeetingAvailability],
          meeting_duration_millis: Integer
        ) -> void

        def to_hash: -> {
          availabilities: ::Array[HubSpotSDK::Scheduler::ExternalMeetingAvailability],
          meeting_duration_millis: Integer
        }
      end
    end
  end
end
