module HubspotSDK
  module Resources
    class Cms
      class Pages
        class Folders
          def create_folder: (
            id: String,
            category: Integer,
            created: Time,
            deleted_at: Time,
            name: String,
            parent_folder_id: Integer,
            updated: Time,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::ContentFolder

          def delete_folder: (
            String object_id_,
            ?archived: bool,
            ?request_options: HubspotSDK::request_opts
          ) -> nil

          def get_folder: (
            String object_id_,
            ?archived: bool,
            ?property: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::ContentFolder

          def get_folder_revision: (
            String revision_id,
            object_id_: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::ContentFolderVersion

          def get_folders_batch: (
            inputs: ::Array[String],
            ?archived: bool,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::BatchResponseContentFolder

          def list_folder_revisions: (
            String object_id_,
            ?after: String,
            ?before: String,
            ?limit: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Internal::Page[HubspotSDK::Cms::ContentFolderVersion]

          def list_folders: (
            ?after: String,
            ?archived: bool,
            ?created_after: Time,
            ?created_at: Time,
            ?created_before: Time,
            ?limit: Integer,
            ?property: String,
            ?sort: ::Array[String],
            ?updated_after: Time,
            ?updated_at: Time,
            ?updated_before: Time,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Internal::Page[HubspotSDK::Cms::ContentFolder]

          def restore_folder_revision: (
            String revision_id,
            object_id_: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::ContentFolder

          def update_folder: (
            String object_id_,
            id: String,
            category: Integer,
            created: Time,
            deleted_at: Time,
            name: String,
            parent_folder_id: Integer,
            updated: Time,
            ?archived: bool,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Cms::ContentFolder

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
