# typed: strong

module HubspotSDK
  module Models
    module Marketing
      class MetricsCounters < HubspotSDK::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              HubspotSDK::Marketing::MetricsCounters,
              HubspotSDK::Internal::AnyHash
            )
          end

        # The number of contacts influenced by the campaign.
        sig { returns(Integer) }
        attr_accessor :influenced_contacts

        # The number of new contacts attributed to the campaign as the first touchpoint.
        sig { returns(Integer) }
        attr_accessor :new_contacts_first_touch

        # The number of new contacts attributed to the campaign as the last touchpoint.
        sig { returns(Integer) }
        attr_accessor :new_contacts_last_touch

        # The total number of sessions generated by the campaign.
        sig { returns(Integer) }
        attr_accessor :sessions

        sig do
          params(
            influenced_contacts: Integer,
            new_contacts_first_touch: Integer,
            new_contacts_last_touch: Integer,
            sessions: Integer
          ).returns(T.attached_class)
        end
        def self.new(
          # The number of contacts influenced by the campaign.
          influenced_contacts:,
          # The number of new contacts attributed to the campaign as the first touchpoint.
          new_contacts_first_touch:,
          # The number of new contacts attributed to the campaign as the last touchpoint.
          new_contacts_last_touch:,
          # The total number of sessions generated by the campaign.
          sessions:
        )
        end

        sig do
          override.returns(
            {
              influenced_contacts: Integer,
              new_contacts_first_touch: Integer,
              new_contacts_last_touch: Integer,
              sessions: Integer
            }
          )
        end
        def to_hash
        end
      end
    end
  end
end
