module HubSpotSDK
  module Models
    module Files
      type collection_response_file =
        {
          results: ::Array[HubSpotSDK::Files::File],
          paging: HubSpotSDK::Paging
        }

      class CollectionResponseFile < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Files::File]

        attr_reader paging: HubSpotSDK::Paging?

        def paging=: (HubSpotSDK::Paging) -> HubSpotSDK::Paging

        def initialize: (
          results: ::Array[HubSpotSDK::Files::File],
          ?paging: HubSpotSDK::Paging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Files::File],
          paging: HubSpotSDK::Paging
        }
      end
    end
  end
end
