module HubSpotSDK
  module Models
    module Files
      type file_stat =
        { file: HubSpotSDK::Files::File, folder: HubSpotSDK::Files::Folder }

      class FileStat < HubSpotSDK::Internal::Type::BaseModel
        attr_reader file: HubSpotSDK::Files::File?

        def file=: (HubSpotSDK::Files::File) -> HubSpotSDK::Files::File

        attr_reader folder: HubSpotSDK::Files::Folder?

        def folder=: (HubSpotSDK::Files::Folder) -> HubSpotSDK::Files::Folder

        def initialize: (
          ?file: HubSpotSDK::Files::File,
          ?folder: HubSpotSDK::Files::Folder
        ) -> void

        def to_hash: -> {
          file: HubSpotSDK::Files::File,
          folder: HubSpotSDK::Files::Folder
        }
      end
    end
  end
end
