module HubSpotSDK
  module Models
    module Files
      type file_asset_get_params =
        { file_id: String, properties: ::Array[String] }
        & HubSpotSDK::Internal::Type::request_parameters

      class FileAssetGetParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor file_id: String

        attr_reader properties: ::Array[String]?

        def properties=: (::Array[String]) -> ::Array[String]

        def initialize: (
          file_id: String,
          ?properties: ::Array[String],
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          file_id: String,
          properties: ::Array[String],
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
