module HubSpotSDK
  module Models
    module Files
      type file_asset_get_signed_url_params =
        {
          file_id: String,
          expiration_seconds: Integer,
          size: HubSpotSDK::Models::Files::FileAssetGetSignedURLParams::size,
          upscale: bool
        }
        & HubSpotSDK::Internal::Type::request_parameters

      class FileAssetGetSignedURLParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor file_id: String

        attr_reader expiration_seconds: Integer?

        def expiration_seconds=: (Integer) -> Integer

        attr_reader size: HubSpotSDK::Models::Files::FileAssetGetSignedURLParams::size?

        def size=: (
          HubSpotSDK::Models::Files::FileAssetGetSignedURLParams::size
        ) -> HubSpotSDK::Models::Files::FileAssetGetSignedURLParams::size

        attr_reader upscale: bool?

        def upscale=: (bool) -> bool

        def initialize: (
          file_id: String,
          ?expiration_seconds: Integer,
          ?size: HubSpotSDK::Models::Files::FileAssetGetSignedURLParams::size,
          ?upscale: bool,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          file_id: String,
          expiration_seconds: Integer,
          size: HubSpotSDK::Models::Files::FileAssetGetSignedURLParams::size,
          upscale: bool,
          request_options: HubSpotSDK::RequestOptions
        }

        type size = :icon | :medium | :preview | :thumb

        module Size
          extend HubSpotSDK::Internal::Type::Enum

          ICON: :icon
          MEDIUM: :medium
          PREVIEW: :preview
          THUMB: :thumb

          def self?.values: -> ::Array[HubSpotSDK::Models::Files::FileAssetGetSignedURLParams::size]
        end
      end
    end
  end
end
