module HubspotSDK
  module Models
    module Files
      type file_operation_replace_params =
        {
          charset_hunch: String,
          file: HubspotSDK::Internal::file_input,
          options: String
        }
        & HubspotSDK::Internal::Type::request_parameters

      class FileOperationReplaceParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_reader charset_hunch: String?

        def charset_hunch=: (String) -> String

        attr_reader file: HubspotSDK::Internal::file_input?

        def file=: (
          HubspotSDK::Internal::file_input
        ) -> HubspotSDK::Internal::file_input

        attr_reader options: String?

        def options=: (String) -> String

        def initialize: (
          ?charset_hunch: String,
          ?file: HubspotSDK::Internal::file_input,
          ?options: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          charset_hunch: String,
          file: HubspotSDK::Internal::file_input,
          options: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
