module HubspotSDK
  module Models
    module Files
      type file_stat =
        { file: HubspotSDK::Files::File, folder: HubspotSDK::Files::Folder }

      class FileStat < HubspotSDK::Internal::Type::BaseModel
        attr_reader file: HubspotSDK::Files::File?

        def file=: (HubspotSDK::Files::File) -> HubspotSDK::Files::File

        attr_reader folder: HubspotSDK::Files::Folder?

        def folder=: (HubspotSDK::Files::Folder) -> HubspotSDK::Files::Folder

        def initialize: (
          ?file: HubspotSDK::Files::File,
          ?folder: HubspotSDK::Files::Folder
        ) -> void

        def to_hash: -> {
          file: HubspotSDK::Files::File,
          folder: HubspotSDK::Files::Folder
        }
      end
    end
  end
end
