module HubSpotSDK
  module Models
    module Files
      type file_update_input =
        {
          clear_expires: bool,
          access: HubSpotSDK::Models::Files::FileUpdateInput::access,
          expires_at: Time,
          is_usable_in_content: bool,
          name: String,
          parent_folder_id: String,
          parent_folder_path: String
        }

      class FileUpdateInput < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor clear_expires: bool

        attr_reader access: HubSpotSDK::Models::Files::FileUpdateInput::access?

        def access=: (
          HubSpotSDK::Models::Files::FileUpdateInput::access
        ) -> HubSpotSDK::Models::Files::FileUpdateInput::access

        attr_reader expires_at: Time?

        def expires_at=: (Time) -> Time

        attr_reader is_usable_in_content: bool?

        def is_usable_in_content=: (bool) -> bool

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader parent_folder_id: String?

        def parent_folder_id=: (String) -> String

        attr_reader parent_folder_path: String?

        def parent_folder_path=: (String) -> String

        def initialize: (
          clear_expires: bool,
          ?access: HubSpotSDK::Models::Files::FileUpdateInput::access,
          ?expires_at: Time,
          ?is_usable_in_content: bool,
          ?name: String,
          ?parent_folder_id: String,
          ?parent_folder_path: String
        ) -> void

        def to_hash: -> {
          clear_expires: bool,
          access: HubSpotSDK::Models::Files::FileUpdateInput::access,
          expires_at: Time,
          is_usable_in_content: bool,
          name: String,
          parent_folder_id: String,
          parent_folder_path: String
        }

        type access =
          :HIDDEN_INDEXABLE
          | :HIDDEN_NOT_INDEXABLE
          | :HIDDEN_PRIVATE
          | :HIDDEN_SENSITIVE
          | :PRIVATE
          | :PUBLIC_INDEXABLE
          | :PUBLIC_NOT_INDEXABLE
          | :SENSITIVE

        module Access
          extend HubSpotSDK::Internal::Type::Enum

          HIDDEN_INDEXABLE: :HIDDEN_INDEXABLE
          HIDDEN_NOT_INDEXABLE: :HIDDEN_NOT_INDEXABLE
          HIDDEN_PRIVATE: :HIDDEN_PRIVATE
          HIDDEN_SENSITIVE: :HIDDEN_SENSITIVE
          PRIVATE: :PRIVATE
          PUBLIC_INDEXABLE: :PUBLIC_INDEXABLE
          PUBLIC_NOT_INDEXABLE: :PUBLIC_NOT_INDEXABLE
          SENSITIVE: :SENSITIVE

          def self?.values: -> ::Array[HubSpotSDK::Models::Files::FileUpdateInput::access]
        end
      end
    end
  end
end
