module HubspotSDK
  module Models
    module Files
      type file_get_params =
        { properties: ::Array[String] }
        & HubspotSDK::Internal::Type::request_parameters

      class FileGetParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_reader properties: ::Array[String]?

        def properties=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?properties: ::Array[String],
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          properties: ::Array[String],
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
