module HubSpotSDK
  module Models
    module Files
      type folder =
        {
          id: String,
          archived: bool,
          created_at: Time,
          updated_at: Time,
          archived_at: Time,
          name: String,
          parent_folder_id: String,
          path: String
        }

      class Folder < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor archived: bool

        attr_accessor created_at: Time

        attr_accessor updated_at: Time

        attr_reader archived_at: Time?

        def archived_at=: (Time) -> Time

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader parent_folder_id: String?

        def parent_folder_id=: (String) -> String

        attr_reader path: String?

        def path=: (String) -> String

        def initialize: (
          id: String,
          archived: bool,
          created_at: Time,
          updated_at: Time,
          ?archived_at: Time,
          ?name: String,
          ?parent_folder_id: String,
          ?path: String
        ) -> void

        def to_hash: -> {
          id: String,
          archived: bool,
          created_at: Time,
          updated_at: Time,
          archived_at: Time,
          name: String,
          parent_folder_id: String,
          path: String
        }
      end
    end
  end
end
