module HubspotSDK
  module Models
    module Files
      type folder_get_by_id_params =
        { folder_id: String, properties: ::Array[String] }
        & HubspotSDK::Internal::Type::request_parameters

      class FolderGetByIDParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor folder_id: String

        attr_reader properties: ::Array[String]?

        def properties=: (::Array[String]) -> ::Array[String]

        def initialize: (
          folder_id: String,
          ?properties: ::Array[String],
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          folder_id: String,
          properties: ::Array[String],
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
