module HubSpotSDK
  module Models
    module Files
      type folder_delete_by_path_params =
        { folder_path: String } & HubSpotSDK::Internal::Type::request_parameters

      class FolderDeleteByPathParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor folder_path: String

        def initialize: (
          folder_path: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          folder_path: String,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
