module HubSpotSDK
  module Models
    module Files
      type folder_get_by_path_params =
        { folder_path: String, properties: ::Array[String] }
        & HubSpotSDK::Internal::Type::request_parameters

      class FolderGetByPathParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor folder_path: String

        attr_reader properties: ::Array[String]?

        def properties=: (::Array[String]) -> ::Array[String]

        def initialize: (
          folder_path: String,
          ?properties: ::Array[String],
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          folder_path: String,
          properties: ::Array[String],
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
