module HubSpotSDK
  module Models
    module Files
      type folder_action_response =
        {
          completed_at: Time,
          started_at: Time,
          status: HubSpotSDK::Models::Files::FolderActionResponse::status,
          task_id: String,
          errors: ::Array[HubSpotSDK::StandardError],
          links: ::Hash[Symbol, String],
          num_errors: Integer,
          requested_at: Time,
          result: HubSpotSDK::Files::Folder
        }

      class FolderActionResponse < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor completed_at: Time

        attr_accessor started_at: Time

        attr_accessor status: HubSpotSDK::Models::Files::FolderActionResponse::status

        attr_accessor task_id: String

        attr_reader errors: ::Array[HubSpotSDK::StandardError]?

        def errors=: (
          ::Array[HubSpotSDK::StandardError]
        ) -> ::Array[HubSpotSDK::StandardError]

        attr_reader links: ::Hash[Symbol, String]?

        def links=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader num_errors: Integer?

        def num_errors=: (Integer) -> Integer

        attr_reader requested_at: Time?

        def requested_at=: (Time) -> Time

        attr_reader result: HubSpotSDK::Files::Folder?

        def result=: (HubSpotSDK::Files::Folder) -> HubSpotSDK::Files::Folder

        def initialize: (
          completed_at: Time,
          started_at: Time,
          status: HubSpotSDK::Models::Files::FolderActionResponse::status,
          task_id: String,
          ?errors: ::Array[HubSpotSDK::StandardError],
          ?links: ::Hash[Symbol, String],
          ?num_errors: Integer,
          ?requested_at: Time,
          ?result: HubSpotSDK::Files::Folder
        ) -> void

        def to_hash: -> {
          completed_at: Time,
          started_at: Time,
          status: HubSpotSDK::Models::Files::FolderActionResponse::status,
          task_id: String,
          errors: ::Array[HubSpotSDK::StandardError],
          links: ::Hash[Symbol, String],
          num_errors: Integer,
          requested_at: Time,
          result: HubSpotSDK::Files::Folder
        }

        type status = :CANCELED | :COMPLETE | :PENDING | :PROCESSING

        module Status
          extend HubSpotSDK::Internal::Type::Enum

          CANCELED: :CANCELED
          COMPLETE: :COMPLETE
          PENDING: :PENDING
          PROCESSING: :PROCESSING

          def self?.values: -> ::Array[HubSpotSDK::Models::Files::FolderActionResponse::status]
        end
      end
    end
  end
end
