module HubspotSDK
  module Models
    module Files
      type folder_delete_by_path_params =
        { folder_path: String } & HubspotSDK::Internal::Type::request_parameters

      class FolderDeleteByPathParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor folder_path: String

        def initialize: (
          folder_path: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          folder_path: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
