module HubspotSDK
  module Models
    module Automation
      type action_create_or_replace_params =
        {
          app_id: Integer,
          definition_id: String,
          function_type: HubspotSDK::Models::Automation::ActionCreateOrReplaceParams::function_type,
          function_id: String,
          body: String
        }
        & HubspotSDK::Internal::Type::request_parameters

      class ActionCreateOrReplaceParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor app_id: Integer

        attr_accessor definition_id: String

        attr_accessor function_type: HubspotSDK::Models::Automation::ActionCreateOrReplaceParams::function_type

        attr_accessor function_id: String

        attr_accessor body: String

        def initialize: (
          app_id: Integer,
          definition_id: String,
          function_type: HubspotSDK::Models::Automation::ActionCreateOrReplaceParams::function_type,
          function_id: String,
          body: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          app_id: Integer,
          definition_id: String,
          function_type: HubspotSDK::Models::Automation::ActionCreateOrReplaceParams::function_type,
          function_id: String,
          body: String,
          request_options: HubspotSDK::RequestOptions
        }

        type function_type =
          :POST_ACTION_EXECUTION
          | :POST_FETCH_OPTIONS
          | :PRE_ACTION_EXECUTION
          | :PRE_FETCH_OPTIONS

        module FunctionType
          extend HubspotSDK::Internal::Type::Enum

          POST_ACTION_EXECUTION: :POST_ACTION_EXECUTION
          POST_FETCH_OPTIONS: :POST_FETCH_OPTIONS
          PRE_ACTION_EXECUTION: :PRE_ACTION_EXECUTION
          PRE_FETCH_OPTIONS: :PRE_FETCH_OPTIONS

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::ActionCreateOrReplaceParams::function_type]
        end
      end
    end
  end
end
