module HubSpotSDK
  module Models
    module Automation
      type agent_request_context =
        {
          agent_id: Integer,
          chirp_ai_context_object: HubSpotSDK::Automation::ChirpAIContextObject,
          source: HubSpotSDK::Models::Automation::AgentRequestContext::source,
          trajectory_id: String
        }

      class AgentRequestContext < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor agent_id: Integer

        attr_accessor chirp_ai_context_object: HubSpotSDK::Automation::ChirpAIContextObject

        attr_accessor source: HubSpotSDK::Models::Automation::AgentRequestContext::source

        attr_reader trajectory_id: String?

        def trajectory_id=: (String) -> String

        def initialize: (
          agent_id: Integer,
          chirp_ai_context_object: HubSpotSDK::Automation::ChirpAIContextObject,
          source: HubSpotSDK::Models::Automation::AgentRequestContext::source,
          ?trajectory_id: String
        ) -> void

        def to_hash: -> {
          agent_id: Integer,
          chirp_ai_context_object: HubSpotSDK::Automation::ChirpAIContextObject,
          source: HubSpotSDK::Models::Automation::AgentRequestContext::source,
          trajectory_id: String
        }

        type source = :AGENTS

        module Source
          extend HubSpotSDK::Internal::Type::Enum

          AGENTS: :AGENTS

          def self?.values: -> ::Array[HubSpotSDK::Models::Automation::AgentRequestContext::source]
        end
      end
    end
  end
end
