module HubspotSDK
  module Models
    module Automation
      type api_flow_batch_input =
        {
          inputs: ::Array[HubspotSDK::Automation::APIFlowBatchFetchFlowIDCoordinate]
        }

      class APIFlowBatchInput < HubspotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubspotSDK::Automation::APIFlowBatchFetchFlowIDCoordinate]

        def initialize: (
          inputs: ::Array[HubspotSDK::Automation::APIFlowBatchFetchFlowIDCoordinate]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubspotSDK::Automation::APIFlowBatchFetchFlowIDCoordinate]
        }
      end
    end
  end
end
