module HubspotSDK
  module Models
    module Automation
      type api_static_time_zone_strategy =
        {
          time_zone_id: String,
          type: HubspotSDK::Models::Automation::APIStaticTimeZoneStrategy::type_
        }

      class APIStaticTimeZoneStrategy < HubspotSDK::Internal::Type::BaseModel
        attr_accessor time_zone_id: String

        attr_accessor type: HubspotSDK::Models::Automation::APIStaticTimeZoneStrategy::type_

        def initialize: (
          time_zone_id: String,
          type: HubspotSDK::Models::Automation::APIStaticTimeZoneStrategy::type_
        ) -> void

        def to_hash: -> {
          time_zone_id: String,
          type: HubspotSDK::Models::Automation::APIStaticTimeZoneStrategy::type_
        }

        type type_ = :STATIC_TIME_ZONE

        module Type
          extend HubspotSDK::Internal::Type::Enum

          STATIC_TIME_ZONE: :STATIC_TIME_ZONE

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIStaticTimeZoneStrategy::type_]
        end
      end
    end
  end
end
