module HubspotSDK
  module Models
    module Automation
      type api_auth_key_webhook_auth_settings =
        {
          location: HubspotSDK::Models::Automation::APIAuthKeyWebhookAuthSettings::location,
          name: String,
          secret_name: String,
          type: HubspotSDK::Models::Automation::APIAuthKeyWebhookAuthSettings::type_
        }

      class APIAuthKeyWebhookAuthSettings < HubspotSDK::Internal::Type::BaseModel
        attr_accessor location: HubspotSDK::Models::Automation::APIAuthKeyWebhookAuthSettings::location

        attr_accessor name: String

        attr_accessor secret_name: String

        attr_accessor type: HubspotSDK::Models::Automation::APIAuthKeyWebhookAuthSettings::type_

        def initialize: (
          location: HubspotSDK::Models::Automation::APIAuthKeyWebhookAuthSettings::location,
          name: String,
          secret_name: String,
          type: HubspotSDK::Models::Automation::APIAuthKeyWebhookAuthSettings::type_
        ) -> void

        def to_hash: -> {
          location: HubspotSDK::Models::Automation::APIAuthKeyWebhookAuthSettings::location,
          name: String,
          secret_name: String,
          type: HubspotSDK::Models::Automation::APIAuthKeyWebhookAuthSettings::type_
        }

        type location = :HEADER | :QUERY_PARAM

        module Location
          extend HubspotSDK::Internal::Type::Enum

          HEADER: :HEADER
          QUERY_PARAM: :QUERY_PARAM

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIAuthKeyWebhookAuthSettings::location]
        end

        type type_ = :AUTH_KEY

        module Type
          extend HubspotSDK::Internal::Type::Enum

          AUTH_KEY: :AUTH_KEY

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIAuthKeyWebhookAuthSettings::type_]
        end
      end
    end
  end
end
