module HubspotSDK
  module Models
    module Automation
      type api_blocked_date =
        {
          day_of_month: Integer,
          month: HubspotSDK::Models::Automation::APIBlockedDate::month,
          year: Integer
        }

      class APIBlockedDate < HubspotSDK::Internal::Type::BaseModel
        attr_accessor day_of_month: Integer

        attr_accessor month: HubspotSDK::Models::Automation::APIBlockedDate::month

        attr_reader year: Integer?

        def year=: (Integer) -> Integer

        def initialize: (
          day_of_month: Integer,
          month: HubspotSDK::Models::Automation::APIBlockedDate::month,
          ?year: Integer
        ) -> void

        def to_hash: -> {
          day_of_month: Integer,
          month: HubspotSDK::Models::Automation::APIBlockedDate::month,
          year: Integer
        }

        type month =
          :APRIL
          | :AUGUST
          | :DECEMBER
          | :FEBRUARY
          | :JANUARY
          | :JULY
          | :JUNE
          | :MARCH
          | :MAY
          | :NOVEMBER
          | :OCTOBER
          | :SEPTEMBER

        module Month
          extend HubspotSDK::Internal::Type::Enum

          APRIL: :APRIL
          AUGUST: :AUGUST
          DECEMBER: :DECEMBER
          FEBRUARY: :FEBRUARY
          JANUARY: :JANUARY
          JULY: :JULY
          JUNE: :JUNE
          MARCH: :MARCH
          MAY: :MAY
          NOVEMBER: :NOVEMBER
          OCTOBER: :OCTOBER
          SEPTEMBER: :SEPTEMBER

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIBlockedDate::month]
        end
      end
    end
  end
end
