module HubspotSDK
  module Models
    module Automation
      type api_un_enrollment_setting =
        {
          flow_ids: ::Array[String],
          type: HubspotSDK::Models::Automation::APIUnEnrollmentSetting::type_
        }

      class APIUnEnrollmentSetting < HubspotSDK::Internal::Type::BaseModel
        attr_accessor flow_ids: ::Array[String]

        attr_accessor type: HubspotSDK::Models::Automation::APIUnEnrollmentSetting::type_

        def initialize: (
          flow_ids: ::Array[String],
          type: HubspotSDK::Models::Automation::APIUnEnrollmentSetting::type_
        ) -> void

        def to_hash: -> {
          flow_ids: ::Array[String],
          type: HubspotSDK::Models::Automation::APIUnEnrollmentSetting::type_
        }

        type type_ = :ALL | :SELECTIVE

        module Type
          extend HubspotSDK::Internal::Type::Enum

          ALL: :ALL
          SELECTIVE: :SELECTIVE

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIUnEnrollmentSetting::type_]
        end
      end
    end
  end
end
