module HubspotSDK
  module Models
    module Automation
      type api_list_based_enrollment_criteria =
        {
          list_filter_branch: HubspotSDK::Models::Automation::APIListBasedEnrollmentCriteria::list_filter_branch,
          re_enrollment_triggers_filter_branches: ::Array[HubspotSDK::Models::Automation::APIListBasedEnrollmentCriteria::re_enrollment_triggers_filter_branch],
          should_re_enroll: bool,
          type: HubspotSDK::Models::Automation::APIListBasedEnrollmentCriteria::type_,
          un_enroll_objects_not_meeting_criteria: bool
        }

      class APIListBasedEnrollmentCriteria < HubspotSDK::Internal::Type::BaseModel
        attr_accessor list_filter_branch: HubspotSDK::Models::Automation::APIListBasedEnrollmentCriteria::list_filter_branch

        attr_accessor re_enrollment_triggers_filter_branches: ::Array[HubspotSDK::Models::Automation::APIListBasedEnrollmentCriteria::re_enrollment_triggers_filter_branch]

        attr_accessor should_re_enroll: bool

        attr_accessor type: HubspotSDK::Models::Automation::APIListBasedEnrollmentCriteria::type_

        attr_accessor un_enroll_objects_not_meeting_criteria: bool

        def initialize: (
          list_filter_branch: HubspotSDK::Models::Automation::APIListBasedEnrollmentCriteria::list_filter_branch,
          re_enrollment_triggers_filter_branches: ::Array[HubspotSDK::Models::Automation::APIListBasedEnrollmentCriteria::re_enrollment_triggers_filter_branch],
          should_re_enroll: bool,
          type: HubspotSDK::Models::Automation::APIListBasedEnrollmentCriteria::type_,
          un_enroll_objects_not_meeting_criteria: bool
        ) -> void

        def to_hash: -> {
          list_filter_branch: HubspotSDK::Models::Automation::APIListBasedEnrollmentCriteria::list_filter_branch,
          re_enrollment_triggers_filter_branches: ::Array[HubspotSDK::Models::Automation::APIListBasedEnrollmentCriteria::re_enrollment_triggers_filter_branch],
          should_re_enroll: bool,
          type: HubspotSDK::Models::Automation::APIListBasedEnrollmentCriteria::type_,
          un_enroll_objects_not_meeting_criteria: bool
        }

        type list_filter_branch =
          HubspotSDK::PublicOrFilterBranch
          | HubspotSDK::PublicAndFilterBranch
          | HubspotSDK::PublicNotAllFilterBranch
          | HubspotSDK::PublicNotAnyFilterBranch
          | HubspotSDK::PublicRestrictedFilterBranch
          | HubspotSDK::PublicUnifiedEventsFilterBranch
          | HubspotSDK::PublicPropertyAssociationFilterBranch
          | HubspotSDK::PublicAssociationFilterBranch

        module ListFilterBranch
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Automation::APIListBasedEnrollmentCriteria::list_filter_branch]
        end

        type re_enrollment_triggers_filter_branch =
          HubspotSDK::PublicOrFilterBranch
          | HubspotSDK::PublicAndFilterBranch
          | HubspotSDK::PublicNotAllFilterBranch
          | HubspotSDK::PublicNotAnyFilterBranch
          | HubspotSDK::PublicRestrictedFilterBranch
          | HubspotSDK::PublicUnifiedEventsFilterBranch
          | HubspotSDK::PublicPropertyAssociationFilterBranch
          | HubspotSDK::PublicAssociationFilterBranch

        module ReEnrollmentTriggersFilterBranch
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Automation::APIListBasedEnrollmentCriteria::re_enrollment_triggers_filter_branch]
        end

        type type_ = :LIST_BASED

        module Type
          extend HubspotSDK::Internal::Type::Enum

          LIST_BASED: :LIST_BASED

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIListBasedEnrollmentCriteria::type_]
        end
      end
    end
  end
end
