module HubspotSDK
  module Models
    module Automation
      type api_single_connection_action =
        {
          action_id: String,
          action_type_id: String,
          action_type_version: Integer,
          fields: ::Hash[Symbol, top],
          type: HubspotSDK::Models::Automation::APISingleConnectionAction::type_,
          connection: HubspotSDK::Automation::APIConnection
        }

      class APISingleConnectionAction < HubspotSDK::Internal::Type::BaseModel
        attr_accessor action_id: String

        attr_accessor action_type_id: String

        attr_accessor action_type_version: Integer

        attr_accessor fields: ::Hash[Symbol, top]

        attr_accessor type: HubspotSDK::Models::Automation::APISingleConnectionAction::type_

        attr_reader connection: HubspotSDK::Automation::APIConnection?

        def connection=: (
          HubspotSDK::Automation::APIConnection
        ) -> HubspotSDK::Automation::APIConnection

        def initialize: (
          action_id: String,
          action_type_id: String,
          action_type_version: Integer,
          fields: ::Hash[Symbol, top],
          type: HubspotSDK::Models::Automation::APISingleConnectionAction::type_,
          ?connection: HubspotSDK::Automation::APIConnection
        ) -> void

        def to_hash: -> {
          action_id: String,
          action_type_id: String,
          action_type_version: Integer,
          fields: ::Hash[Symbol, top],
          type: HubspotSDK::Models::Automation::APISingleConnectionAction::type_,
          connection: HubspotSDK::Automation::APIConnection
        }

        type type_ = :SINGLE_CONNECTION

        module Type
          extend HubspotSDK::Internal::Type::Enum

          SINGLE_CONNECTION: :SINGLE_CONNECTION

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APISingleConnectionAction::type_]
        end
      end
    end
  end
end
