module HubspotSDK
  module Models
    module Automation
      type api_flow_listing =
        {
          id: String,
          created_at: Time,
          flow_type: String,
          is_enabled: bool,
          object_type_id: String,
          revision_id: String,
          updated_at: Time,
          name: String,
          uuid: String
        }

      class APIFlowListing < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor flow_type: String

        attr_accessor is_enabled: bool

        attr_accessor object_type_id: String

        attr_accessor revision_id: String

        attr_accessor updated_at: Time

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader uuid: String?

        def uuid=: (String) -> String

        def initialize: (
          id: String,
          created_at: Time,
          flow_type: String,
          is_enabled: bool,
          object_type_id: String,
          revision_id: String,
          updated_at: Time,
          ?name: String,
          ?uuid: String
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          flow_type: String,
          is_enabled: bool,
          object_type_id: String,
          revision_id: String,
          updated_at: Time,
          name: String,
          uuid: String
        }
      end
    end
  end
end
