module HubspotSDK
  module Models
    module Automation
      type api_enrolled_argument_property_filter_data_source =
        {
          argument_name: String,
          name: String,
          property_name: String,
          type: HubspotSDK::Models::Automation::APIEnrolledArgumentPropertyFilterDataSource::type_,
          sort_by: HubspotSDK::Automation::APISort
        }

      class APIEnrolledArgumentPropertyFilterDataSource < HubspotSDK::Internal::Type::BaseModel
        attr_accessor argument_name: String

        attr_accessor name: String

        attr_accessor property_name: String

        attr_accessor type: HubspotSDK::Models::Automation::APIEnrolledArgumentPropertyFilterDataSource::type_

        attr_reader sort_by: HubspotSDK::Automation::APISort?

        def sort_by=: (
          HubspotSDK::Automation::APISort
        ) -> HubspotSDK::Automation::APISort

        def initialize: (
          argument_name: String,
          name: String,
          property_name: String,
          type: HubspotSDK::Models::Automation::APIEnrolledArgumentPropertyFilterDataSource::type_,
          ?sort_by: HubspotSDK::Automation::APISort
        ) -> void

        def to_hash: -> {
          argument_name: String,
          name: String,
          property_name: String,
          type: HubspotSDK::Models::Automation::APIEnrolledArgumentPropertyFilterDataSource::type_,
          sort_by: HubspotSDK::Automation::APISort
        }

        type type_ = :ENROLLED_ARGUMENT_PROPERTY_FILTER

        module Type
          extend HubspotSDK::Internal::Type::Enum

          ENROLLED_ARGUMENT_PROPERTY_FILTER: :ENROLLED_ARGUMENT_PROPERTY_FILTER

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIEnrolledArgumentPropertyFilterDataSource::type_]
        end
      end
    end
  end
end
