module HubspotSDK
  module Models
    module Automation
      type api_flow_create_request =
        HubspotSDK::Automation::APIContactFlowCreateRequest
        | HubspotSDK::Automation::APIPlatformFlowCreateRequest

      module APIFlowCreateRequest
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::Automation::api_flow_create_request]
      end
    end
  end
end
