module HubspotSDK
  module Models
    module Automation
      type api_input_variable =
        {
          name: String,
          value: HubspotSDK::Models::Automation::APIInputVariable::value
        }

      class APIInputVariable < HubspotSDK::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor value: HubspotSDK::Models::Automation::APIInputVariable::value

        def initialize: (
          name: String,
          value: HubspotSDK::Models::Automation::APIInputVariable::value
        ) -> void

        def to_hash: -> {
          name: String,
          value: HubspotSDK::Models::Automation::APIInputVariable::value
        }

        type value =
          HubspotSDK::Automation::APIActionDataValue
          | HubspotSDK::Automation::APIObjectPropertyValue
          | HubspotSDK::Automation::APIStaticValue
          | HubspotSDK::Automation::APIRelativeDateTimeValue
          | HubspotSDK::Automation::APITimestampValue
          | HubspotSDK::Automation::APIIncrementValue
          | HubspotSDK::Automation::APIFetchedObjectPropertyValue
          | HubspotSDK::Automation::APIAppendObjectPropertyValue
          | HubspotSDK::Automation::APIStaticAppendValue
          | HubspotSDK::Automation::APIEnrollmentEventPropertyValue

        module Value
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Automation::APIInputVariable::value]
        end
      end
    end
  end
end
