module HubspotSDK
  module Models
    module Automation
      type api_fetched_object_property_value =
        {
          property_token: String,
          type: HubspotSDK::Models::Automation::APIFetchedObjectPropertyValue::type_
        }

      class APIFetchedObjectPropertyValue < HubspotSDK::Internal::Type::BaseModel
        attr_accessor property_token: String

        attr_accessor type: HubspotSDK::Models::Automation::APIFetchedObjectPropertyValue::type_

        def initialize: (
          property_token: String,
          type: HubspotSDK::Models::Automation::APIFetchedObjectPropertyValue::type_
        ) -> void

        def to_hash: -> {
          property_token: String,
          type: HubspotSDK::Models::Automation::APIFetchedObjectPropertyValue::type_
        }

        type type_ = :FETCHED_OBJECT_PROPERTY

        module Type
          extend HubspotSDK::Internal::Type::Enum

          FETCHED_OBJECT_PROPERTY: :FETCHED_OBJECT_PROPERTY

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIFetchedObjectPropertyValue::type_]
        end
      end
    end
  end
end
