module HubspotSDK
  module Models
    module Automation
      type api_relative_date_time_value =
        {
          time_delay: HubspotSDK::Automation::APITimeDelay,
          type: HubspotSDK::Models::Automation::APIRelativeDateTimeValue::type_
        }

      class APIRelativeDateTimeValue < HubspotSDK::Internal::Type::BaseModel
        attr_accessor time_delay: HubspotSDK::Automation::APITimeDelay

        attr_accessor type: HubspotSDK::Models::Automation::APIRelativeDateTimeValue::type_

        def initialize: (
          time_delay: HubspotSDK::Automation::APITimeDelay,
          type: HubspotSDK::Models::Automation::APIRelativeDateTimeValue::type_
        ) -> void

        def to_hash: -> {
          time_delay: HubspotSDK::Automation::APITimeDelay,
          type: HubspotSDK::Models::Automation::APIRelativeDateTimeValue::type_
        }

        type type_ = :RELATIVE_DATETIME

        module Type
          extend HubspotSDK::Internal::Type::Enum

          RELATIVE_DATETIME: :RELATIVE_DATETIME

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIRelativeDateTimeValue::type_]
        end
      end
    end
  end
end
