module HubspotSDK
  module Models
    module Automation
      type api_flow_put_request =
        HubspotSDK::Automation::APIContactFlowPutRequest
        | HubspotSDK::Automation::APIPlatformFlowPutRequest

      module APIFlowPutRequest
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::Automation::api_flow_put_request]
      end
    end
  end
end
