module HubspotSDK
  module Models
    module Automation
      type api_monthly_specific_days_enrollment_schedule =
        {
          days_of_month: ::Array[Integer],
          time_of_day: HubspotSDK::Automation::APITimeOfDay,
          type: HubspotSDK::Models::Automation::APIMonthlySpecificDaysEnrollmentSchedule::type_
        }

      class APIMonthlySpecificDaysEnrollmentSchedule < HubspotSDK::Internal::Type::BaseModel
        attr_accessor days_of_month: ::Array[Integer]

        attr_accessor time_of_day: HubspotSDK::Automation::APITimeOfDay

        attr_accessor type: HubspotSDK::Models::Automation::APIMonthlySpecificDaysEnrollmentSchedule::type_

        def initialize: (
          days_of_month: ::Array[Integer],
          time_of_day: HubspotSDK::Automation::APITimeOfDay,
          type: HubspotSDK::Models::Automation::APIMonthlySpecificDaysEnrollmentSchedule::type_
        ) -> void

        def to_hash: -> {
          days_of_month: ::Array[Integer],
          time_of_day: HubspotSDK::Automation::APITimeOfDay,
          type: HubspotSDK::Models::Automation::APIMonthlySpecificDaysEnrollmentSchedule::type_
        }

        type type_ = :MONTHLY_SPECIFIC_DAYS

        module Type
          extend HubspotSDK::Internal::Type::Enum

          MONTHLY_SPECIFIC_DAYS: :MONTHLY_SPECIFIC_DAYS

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIMonthlySpecificDaysEnrollmentSchedule::type_]
        end
      end
    end
  end
end
