module HubspotSDK
  module Models
    module Automation
      type api_daily_enrollment_schedule =
        {
          time_of_day: HubspotSDK::Automation::APITimeOfDay,
          type: HubspotSDK::Models::Automation::APIDailyEnrollmentSchedule::type_
        }

      class APIDailyEnrollmentSchedule < HubspotSDK::Internal::Type::BaseModel
        attr_accessor time_of_day: HubspotSDK::Automation::APITimeOfDay

        attr_accessor type: HubspotSDK::Models::Automation::APIDailyEnrollmentSchedule::type_

        def initialize: (
          time_of_day: HubspotSDK::Automation::APITimeOfDay,
          type: HubspotSDK::Models::Automation::APIDailyEnrollmentSchedule::type_
        ) -> void

        def to_hash: -> {
          time_of_day: HubspotSDK::Automation::APITimeOfDay,
          type: HubspotSDK::Models::Automation::APIDailyEnrollmentSchedule::type_
        }

        type type_ = :DAILY

        module Type
          extend HubspotSDK::Internal::Type::Enum

          DAILY: :DAILY

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIDailyEnrollmentSchedule::type_]
        end
      end
    end
  end
end
