module HubspotSDK
  module Models
    module Automation
      type api_association_timestamp_data_source =
        {
          association_category: HubspotSDK::Models::Automation::APIAssociationTimestampDataSource::association_category,
          association_type_id: Integer,
          name: String,
          object_type_id: String,
          type: HubspotSDK::Models::Automation::APIAssociationTimestampDataSource::type_
        }

      class APIAssociationTimestampDataSource < HubspotSDK::Internal::Type::BaseModel
        attr_accessor association_category: HubspotSDK::Models::Automation::APIAssociationTimestampDataSource::association_category

        attr_accessor association_type_id: Integer

        attr_accessor name: String

        attr_accessor object_type_id: String

        attr_accessor type: HubspotSDK::Models::Automation::APIAssociationTimestampDataSource::type_

        def initialize: (
          association_category: HubspotSDK::Models::Automation::APIAssociationTimestampDataSource::association_category,
          association_type_id: Integer,
          name: String,
          object_type_id: String,
          type: HubspotSDK::Models::Automation::APIAssociationTimestampDataSource::type_
        ) -> void

        def to_hash: -> {
          association_category: HubspotSDK::Models::Automation::APIAssociationTimestampDataSource::association_category,
          association_type_id: Integer,
          name: String,
          object_type_id: String,
          type: HubspotSDK::Models::Automation::APIAssociationTimestampDataSource::type_
        }

        type association_category =
          :HUBSPOT_DEFINED | :USER_DEFINED | :INTEGRATOR_DEFINED

        module AssociationCategory
          extend HubspotSDK::Internal::Type::Enum

          HUBSPOT_DEFINED: :HUBSPOT_DEFINED
          USER_DEFINED: :USER_DEFINED
          INTEGRATOR_DEFINED: :INTEGRATOR_DEFINED

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIAssociationTimestampDataSource::association_category]
        end

        type type_ = :ASSOCIATION_TIMESTAMP

        module Type
          extend HubspotSDK::Internal::Type::Enum

          ASSOCIATION_TIMESTAMP: :ASSOCIATION_TIMESTAMP

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIAssociationTimestampDataSource::type_]
        end
      end
    end
  end
end
