module HubspotSDK
  module Models
    module Automation
      type api_property_based_enrollment_schedule =
        {
          date_property: String,
          days_delta: Integer,
          time_of_day: HubspotSDK::Automation::APITimeOfDay,
          type: HubspotSDK::Models::Automation::APIPropertyBasedEnrollmentSchedule::type_,
          yearly: bool
        }

      class APIPropertyBasedEnrollmentSchedule < HubspotSDK::Internal::Type::BaseModel
        attr_accessor date_property: String

        attr_accessor days_delta: Integer

        attr_accessor time_of_day: HubspotSDK::Automation::APITimeOfDay

        attr_accessor type: HubspotSDK::Models::Automation::APIPropertyBasedEnrollmentSchedule::type_

        attr_accessor yearly: bool

        def initialize: (
          date_property: String,
          days_delta: Integer,
          time_of_day: HubspotSDK::Automation::APITimeOfDay,
          type: HubspotSDK::Models::Automation::APIPropertyBasedEnrollmentSchedule::type_,
          yearly: bool
        ) -> void

        def to_hash: -> {
          date_property: String,
          days_delta: Integer,
          time_of_day: HubspotSDK::Automation::APITimeOfDay,
          type: HubspotSDK::Models::Automation::APIPropertyBasedEnrollmentSchedule::type_,
          yearly: bool
        }

        type type_ = :PROPERTY_BASED

        module Type
          extend HubspotSDK::Internal::Type::Enum

          PROPERTY_BASED: :PROPERTY_BASED

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIPropertyBasedEnrollmentSchedule::type_]
        end
      end
    end
  end
end
