module HubspotSDK
  module Models
    module Automation
      type api_contact_flow_create_request =
        {
          actions: ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::action],
          blocked_dates: ::Array[HubspotSDK::Automation::APIBlockedDate],
          can_enroll_from_salesforce: bool,
          custom_properties: ::Hash[Symbol, String],
          data_sources: ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::data_source],
          flow_type: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::flow_type,
          is_enabled: bool,
          object_type_id: String,
          suppression_list_ids: ::Array[Integer],
          time_windows: ::Array[HubspotSDK::Automation::APITimeWindow],
          type: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::type_,
          description: String,
          enrollment_criteria: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::enrollment_criteria,
          enrollment_schedule: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::enrollment_schedule,
          event_anchor: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::event_anchor,
          goal_filter_branch: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::goal_filter_branch,
          name: String,
          start_action_id: String,
          un_enrollment_setting: HubspotSDK::Automation::APIUnEnrollmentSetting,
          uuid: String
        }

      class APIContactFlowCreateRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor actions: ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::action]

        attr_accessor blocked_dates: ::Array[HubspotSDK::Automation::APIBlockedDate]

        attr_accessor can_enroll_from_salesforce: bool

        attr_accessor custom_properties: ::Hash[Symbol, String]

        attr_accessor data_sources: ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::data_source]

        attr_accessor flow_type: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::flow_type

        attr_accessor is_enabled: bool

        attr_accessor object_type_id: String

        attr_accessor suppression_list_ids: ::Array[Integer]

        attr_accessor time_windows: ::Array[HubspotSDK::Automation::APITimeWindow]

        attr_accessor type: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::type_

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader enrollment_criteria: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::enrollment_criteria?

        def enrollment_criteria=: (
          HubspotSDK::Models::Automation::APIContactFlowCreateRequest::enrollment_criteria
        ) -> HubspotSDK::Models::Automation::APIContactFlowCreateRequest::enrollment_criteria

        attr_reader enrollment_schedule: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::enrollment_schedule?

        def enrollment_schedule=: (
          HubspotSDK::Models::Automation::APIContactFlowCreateRequest::enrollment_schedule
        ) -> HubspotSDK::Models::Automation::APIContactFlowCreateRequest::enrollment_schedule

        attr_reader event_anchor: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::event_anchor?

        def event_anchor=: (
          HubspotSDK::Models::Automation::APIContactFlowCreateRequest::event_anchor
        ) -> HubspotSDK::Models::Automation::APIContactFlowCreateRequest::event_anchor

        attr_reader goal_filter_branch: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::goal_filter_branch?

        def goal_filter_branch=: (
          HubspotSDK::Models::Automation::APIContactFlowCreateRequest::goal_filter_branch
        ) -> HubspotSDK::Models::Automation::APIContactFlowCreateRequest::goal_filter_branch

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader start_action_id: String?

        def start_action_id=: (String) -> String

        attr_reader un_enrollment_setting: HubspotSDK::Automation::APIUnEnrollmentSetting?

        def un_enrollment_setting=: (
          HubspotSDK::Automation::APIUnEnrollmentSetting
        ) -> HubspotSDK::Automation::APIUnEnrollmentSetting

        attr_reader uuid: String?

        def uuid=: (String) -> String

        def initialize: (
          actions: ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::action],
          blocked_dates: ::Array[HubspotSDK::Automation::APIBlockedDate],
          can_enroll_from_salesforce: bool,
          custom_properties: ::Hash[Symbol, String],
          data_sources: ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::data_source],
          flow_type: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::flow_type,
          is_enabled: bool,
          object_type_id: String,
          suppression_list_ids: ::Array[Integer],
          time_windows: ::Array[HubspotSDK::Automation::APITimeWindow],
          type: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::type_,
          ?description: String,
          ?enrollment_criteria: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::enrollment_criteria,
          ?enrollment_schedule: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::enrollment_schedule,
          ?event_anchor: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::event_anchor,
          ?goal_filter_branch: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::goal_filter_branch,
          ?name: String,
          ?start_action_id: String,
          ?un_enrollment_setting: HubspotSDK::Automation::APIUnEnrollmentSetting,
          ?uuid: String
        ) -> void

        def to_hash: -> {
          actions: ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::action],
          blocked_dates: ::Array[HubspotSDK::Automation::APIBlockedDate],
          can_enroll_from_salesforce: bool,
          custom_properties: ::Hash[Symbol, String],
          data_sources: ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::data_source],
          flow_type: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::flow_type,
          is_enabled: bool,
          object_type_id: String,
          suppression_list_ids: ::Array[Integer],
          time_windows: ::Array[HubspotSDK::Automation::APITimeWindow],
          type: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::type_,
          description: String,
          enrollment_criteria: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::enrollment_criteria,
          enrollment_schedule: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::enrollment_schedule,
          event_anchor: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::event_anchor,
          goal_filter_branch: HubspotSDK::Models::Automation::APIContactFlowCreateRequest::goal_filter_branch,
          name: String,
          start_action_id: String,
          un_enrollment_setting: HubspotSDK::Automation::APIUnEnrollmentSetting,
          uuid: String
        }

        type action =
          HubspotSDK::Automation::APIStaticBranchAction
          | HubspotSDK::Automation::APIListBranchAction
          | HubspotSDK::Automation::APIAbTestBranchAction
          | HubspotSDK::Automation::APICustomCodeAction
          | HubspotSDK::Automation::APIWebhookAction
          | HubspotSDK::Automation::APISingleConnectionAction

        module Action
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::action]
        end

        type data_source =
          HubspotSDK::Automation::APIAssociationDataSource
          | HubspotSDK::Automation::APIAssociationTimestampDataSource
          | HubspotSDK::Automation::APIStaticPropertyFilterDataSource
          | HubspotSDK::Automation::APIEnrolledRecordPropertyFilterDataSource
          | HubspotSDK::Automation::APIDatasetFieldPropertyFilterDataSource
          | HubspotSDK::Automation::APIEnrolledArgumentPropertyFilterDataSource

        module DataSource
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::data_source]
        end

        type flow_type = :WORKFLOW | :ACTION_SET | :UNKNOWN

        module FlowType
          extend HubspotSDK::Internal::Type::Enum

          WORKFLOW: :WORKFLOW
          ACTION_SET: :ACTION_SET
          UNKNOWN: :UNKNOWN

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::flow_type]
        end

        type type_ = :CONTACT_FLOW | :PLATFORM_FLOW

        module Type
          extend HubspotSDK::Internal::Type::Enum

          CONTACT_FLOW: :CONTACT_FLOW
          PLATFORM_FLOW: :PLATFORM_FLOW

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::type_]
        end

        type enrollment_criteria =
          HubspotSDK::Automation::APIListBasedEnrollmentCriteria
          | HubspotSDK::Automation::APIEventBasedEnrollmentCriteria
          | HubspotSDK::Automation::APIManualEnrollmentCriteria

        module EnrollmentCriteria
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::enrollment_criteria]
        end

        type enrollment_schedule =
          HubspotSDK::Automation::APIDailyEnrollmentSchedule
          | HubspotSDK::Automation::APIWeeklyEnrollmentSchedule
          | HubspotSDK::Automation::APIMonthlySpecificDaysEnrollmentSchedule
          | HubspotSDK::Automation::APIMonthlyRelativeDaysEnrollmentSchedule
          | HubspotSDK::Automation::APIYearlyEnrollmentSchedule
          | HubspotSDK::Automation::APIPropertyBasedEnrollmentSchedule

        module EnrollmentSchedule
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::enrollment_schedule]
        end

        type event_anchor =
          HubspotSDK::Automation::APIContactPropertyAnchor
          | HubspotSDK::Automation::APIStaticDateAnchor

        module EventAnchor
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::event_anchor]
        end

        type goal_filter_branch =
          HubspotSDK::PublicOrFilterBranch
          | HubspotSDK::PublicAndFilterBranch
          | HubspotSDK::PublicNotAllFilterBranch
          | HubspotSDK::PublicNotAnyFilterBranch
          | HubspotSDK::PublicRestrictedFilterBranch
          | HubspotSDK::PublicUnifiedEventsFilterBranch
          | HubspotSDK::PublicPropertyAssociationFilterBranch
          | HubspotSDK::PublicAssociationFilterBranch

        module GoalFilterBranch
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Automation::APIContactFlowCreateRequest::goal_filter_branch]
        end
      end
    end
  end
end
