module HubspotSDK
  module Models
    module Automation
      type api_manual_enrollment_criteria =
        {
          should_re_enroll: bool,
          type: HubspotSDK::Models::Automation::APIManualEnrollmentCriteria::type_
        }

      class APIManualEnrollmentCriteria < HubspotSDK::Internal::Type::BaseModel
        attr_accessor should_re_enroll: bool

        attr_accessor type: HubspotSDK::Models::Automation::APIManualEnrollmentCriteria::type_

        def initialize: (
          should_re_enroll: bool,
          type: HubspotSDK::Models::Automation::APIManualEnrollmentCriteria::type_
        ) -> void

        def to_hash: -> {
          should_re_enroll: bool,
          type: HubspotSDK::Models::Automation::APIManualEnrollmentCriteria::type_
        }

        type type_ = :MANUAL

        module Type
          extend HubspotSDK::Internal::Type::Enum

          MANUAL: :MANUAL

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIManualEnrollmentCriteria::type_]
        end
      end
    end
  end
end
