module HubspotSDK
  module Models
    module Automation
      type api_static_value =
        {
          static_value: String,
          type: HubspotSDK::Models::Automation::APIStaticValue::type_
        }

      class APIStaticValue < HubspotSDK::Internal::Type::BaseModel
        attr_accessor static_value: String

        attr_accessor type: HubspotSDK::Models::Automation::APIStaticValue::type_

        def initialize: (
          static_value: String,
          type: HubspotSDK::Models::Automation::APIStaticValue::type_
        ) -> void

        def to_hash: -> {
          static_value: String,
          type: HubspotSDK::Models::Automation::APIStaticValue::type_
        }

        type type_ = :STATIC_VALUE

        module Type
          extend HubspotSDK::Internal::Type::Enum

          STATIC_VALUE: :STATIC_VALUE

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIStaticValue::type_]
        end
      end
    end
  end
end
