module HubspotSDK
  module Models
    module Automation
      type api_object_property_value =
        {
          property_name: String,
          type: HubspotSDK::Models::Automation::APIObjectPropertyValue::type_
        }

      class APIObjectPropertyValue < HubspotSDK::Internal::Type::BaseModel
        attr_accessor property_name: String

        attr_accessor type: HubspotSDK::Models::Automation::APIObjectPropertyValue::type_

        def initialize: (
          property_name: String,
          type: HubspotSDK::Models::Automation::APIObjectPropertyValue::type_
        ) -> void

        def to_hash: -> {
          property_name: String,
          type: HubspotSDK::Models::Automation::APIObjectPropertyValue::type_
        }

        type type_ = :OBJECT_PROPERTY

        module Type
          extend HubspotSDK::Internal::Type::Enum

          OBJECT_PROPERTY: :OBJECT_PROPERTY

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::APIObjectPropertyValue::type_]
        end
      end
    end
  end
end
