module HubspotSDK
  module Models
    module Automation
      type api_flow =
        HubspotSDK::Automation::APIContactFlow
        | HubspotSDK::Automation::APIPlatformFlow

      module APIFlow
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::Automation::api_flow]
      end
    end
  end
end
