module HubSpotSDK
  module Models
    module Automation
      type array_field_schema =
        {
          items: top,
          type: HubSpotSDK::Models::Automation::ArrayFieldSchema::type_
        }

      class ArrayFieldSchema < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor items: top

        attr_accessor type: HubSpotSDK::Models::Automation::ArrayFieldSchema::type_

        def initialize: (
          items: top,
          type: HubSpotSDK::Models::Automation::ArrayFieldSchema::type_
        ) -> void

        def to_hash: -> {
          items: top,
          type: HubSpotSDK::Models::Automation::ArrayFieldSchema::type_
        }

        type type_ =
          :ARRAY | :BOOLEAN | :DOUBLE | :INTEGER | :LONG | :OBJECT | :STRING

        module Type
          extend HubSpotSDK::Internal::Type::Enum

          ARRAY: :ARRAY
          BOOLEAN: :BOOLEAN
          DOUBLE: :DOUBLE
          INTEGER: :INTEGER
          LONG: :LONG
          OBJECT: :OBJECT
          STRING: :STRING

          def self?.values: -> ::Array[HubSpotSDK::Models::Automation::ArrayFieldSchema::type_]
        end
      end
    end
  end
end
