module HubspotSDK
  module Models
    module Automation
      type batch_input_callback_completion_batch_request =
        {
          inputs: ::Array[HubspotSDK::Automation::CallbackCompletionBatchRequest]
        }

      class BatchInputCallbackCompletionBatchRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubspotSDK::Automation::CallbackCompletionBatchRequest]

        def initialize: (
          inputs: ::Array[HubspotSDK::Automation::CallbackCompletionBatchRequest]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubspotSDK::Automation::CallbackCompletionBatchRequest]
        }
      end
    end
  end
end
