module HubSpotSDK
  module Models
    module Automation
      type callback_completion_batch_request =
        {
          callback_id: String,
          output_fields: ::Hash[Symbol, String],
          typed_outputs: top,
          failure_reason_type: String,
          request_context: HubSpotSDK::Models::Automation::CallbackCompletionBatchRequest::request_context
        }

      class CallbackCompletionBatchRequest < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor callback_id: String

        attr_accessor output_fields: ::Hash[Symbol, String]

        attr_accessor typed_outputs: top

        attr_reader failure_reason_type: String?

        def failure_reason_type=: (String) -> String

        attr_reader request_context: HubSpotSDK::Models::Automation::CallbackCompletionBatchRequest::request_context?

        def request_context=: (
          HubSpotSDK::Models::Automation::CallbackCompletionBatchRequest::request_context
        ) -> HubSpotSDK::Models::Automation::CallbackCompletionBatchRequest::request_context

        def initialize: (
          callback_id: String,
          output_fields: ::Hash[Symbol, String],
          typed_outputs: top,
          ?failure_reason_type: String,
          ?request_context: HubSpotSDK::Models::Automation::CallbackCompletionBatchRequest::request_context
        ) -> void

        def to_hash: -> {
          callback_id: String,
          output_fields: ::Hash[Symbol, String],
          typed_outputs: top,
          failure_reason_type: String,
          request_context: HubSpotSDK::Models::Automation::CallbackCompletionBatchRequest::request_context
        }

        type request_context =
          HubSpotSDK::Automation::WorkflowsRequestContext
          | HubSpotSDK::Automation::AgentRequestContext
          | HubSpotSDK::Automation::CopilotRequestContext
          | HubSpotSDK::Automation::StandaloneRequestContext
          | HubSpotSDK::Automation::TestRequestContext

        module RequestContext
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Automation::CallbackCompletionBatchRequest::request_context]
        end
      end
    end
  end
end
