module HubSpotSDK
  module Models
    module Automation
      type collection_response_public_action_revision_forward_paging =
        {
          results: ::Array[HubSpotSDK::Automation::PublicActionRevision],
          paging: HubSpotSDK::ForwardPaging
        }

      class CollectionResponsePublicActionRevisionForwardPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Automation::PublicActionRevision]

        attr_reader paging: HubSpotSDK::ForwardPaging?

        def paging=: (HubSpotSDK::ForwardPaging) -> HubSpotSDK::ForwardPaging

        def initialize: (
          results: ::Array[HubSpotSDK::Automation::PublicActionRevision],
          ?paging: HubSpotSDK::ForwardPaging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Automation::PublicActionRevision],
          paging: HubSpotSDK::ForwardPaging
        }
      end
    end
  end
end
