module HubSpotSDK
  module Models
    module Automation
      type collection_response_public_action_definition_forward_paging =
        {
          results: ::Array[HubSpotSDK::Automation::PublicActionDefinition],
          paging: HubSpotSDK::ForwardPaging
        }

      class CollectionResponsePublicActionDefinitionForwardPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Automation::PublicActionDefinition]

        attr_reader paging: HubSpotSDK::ForwardPaging?

        def paging=: (HubSpotSDK::ForwardPaging) -> HubSpotSDK::ForwardPaging

        def initialize: (
          results: ::Array[HubSpotSDK::Automation::PublicActionDefinition],
          ?paging: HubSpotSDK::ForwardPaging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Automation::PublicActionDefinition],
          paging: HubSpotSDK::ForwardPaging
        }
      end
    end
  end
end
