module HubspotSDK
  module Models
    module Automation
      type collection_response_api_flow_email_campaign =
        {
          results: ::Array[HubspotSDK::Automation::APIFlowEmailCampaign],
          paging: HubspotSDK::Paging
        }

      class CollectionResponseAPIFlowEmailCampaign < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubspotSDK::Automation::APIFlowEmailCampaign]

        attr_reader paging: HubspotSDK::Paging?

        def paging=: (HubspotSDK::Paging) -> HubspotSDK::Paging

        def initialize: (
          results: ::Array[HubspotSDK::Automation::APIFlowEmailCampaign],
          ?paging: HubspotSDK::Paging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubspotSDK::Automation::APIFlowEmailCampaign],
          paging: HubspotSDK::Paging
        }
      end
    end
  end
end
