module HubSpotSDK
  module Models
    module Automation
      type collection_response_with_total_public_sequence_lite_response =
        {
          results: ::Array[HubSpotSDK::Automation::PublicSequenceLiteResponse],
          total: Integer,
          paging: HubSpotSDK::Paging
        }

      class CollectionResponseWithTotalPublicSequenceLiteResponse < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Automation::PublicSequenceLiteResponse]

        attr_accessor total: Integer

        attr_reader paging: HubSpotSDK::Paging?

        def paging=: (HubSpotSDK::Paging) -> HubSpotSDK::Paging

        def initialize: (
          results: ::Array[HubSpotSDK::Automation::PublicSequenceLiteResponse],
          total: Integer,
          ?paging: HubSpotSDK::Paging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Automation::PublicSequenceLiteResponse],
          total: Integer,
          paging: HubSpotSDK::Paging
        }
      end
    end
  end
end
