module HubSpotSDK
  module Models
    module Automation
      type copilot_request_context =
        {
          source: HubSpotSDK::Models::Automation::CopilotRequestContext::source,
          trajectory_id: String
        }

      class CopilotRequestContext < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor source: HubSpotSDK::Models::Automation::CopilotRequestContext::source

        attr_reader trajectory_id: String?

        def trajectory_id=: (String) -> String

        def initialize: (
          source: HubSpotSDK::Models::Automation::CopilotRequestContext::source,
          ?trajectory_id: String
        ) -> void

        def to_hash: -> {
          source: HubSpotSDK::Models::Automation::CopilotRequestContext::source,
          trajectory_id: String
        }

        type source = :COPILOT

        module Source
          extend HubSpotSDK::Internal::Type::Enum

          COPILOT: :COPILOT

          def self?.values: -> ::Array[HubSpotSDK::Models::Automation::CopilotRequestContext::source]
        end
      end
    end
  end
end
