module HubSpotSDK
  module Models
    module Automation
      type double_field_schema =
        {
          type: HubSpotSDK::Models::Automation::DoubleFieldSchema::type_,
          maximum: Float,
          minimum: Float
        }

      class DoubleFieldSchema < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor type: HubSpotSDK::Models::Automation::DoubleFieldSchema::type_

        attr_reader maximum: Float?

        def maximum=: (Float) -> Float

        attr_reader minimum: Float?

        def minimum=: (Float) -> Float

        def initialize: (
          type: HubSpotSDK::Models::Automation::DoubleFieldSchema::type_,
          ?maximum: Float,
          ?minimum: Float
        ) -> void

        def to_hash: -> {
          type: HubSpotSDK::Models::Automation::DoubleFieldSchema::type_,
          maximum: Float,
          minimum: Float
        }

        type type_ = :DOUBLE

        module Type
          extend HubSpotSDK::Internal::Type::Enum

          DOUBLE: :DOUBLE

          def self?.values: -> ::Array[HubSpotSDK::Models::Automation::DoubleFieldSchema::type_]
        end
      end
    end
  end
end
