module HubspotSDK
  module Models
    module Automation
      type email_settings_response =
        {
          criteria: HubspotSDK::Models::Automation::EmailSettingsResponse::criteria,
          selling_strategy: HubspotSDK::Models::Automation::EmailSettingsResponse::selling_strategy
        }

      class EmailSettingsResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor criteria: HubspotSDK::Models::Automation::EmailSettingsResponse::criteria

        attr_accessor selling_strategy: HubspotSDK::Models::Automation::EmailSettingsResponse::selling_strategy

        def initialize: (
          criteria: HubspotSDK::Models::Automation::EmailSettingsResponse::criteria,
          selling_strategy: HubspotSDK::Models::Automation::EmailSettingsResponse::selling_strategy
        ) -> void

        def to_hash: -> {
          criteria: HubspotSDK::Models::Automation::EmailSettingsResponse::criteria,
          selling_strategy: HubspotSDK::Models::Automation::EmailSettingsResponse::selling_strategy
        }

        type criteria = :ALL | :NONE

        module Criteria
          extend HubspotSDK::Internal::Type::Enum

          ALL: :ALL
          NONE: :NONE

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::EmailSettingsResponse::criteria]
        end

        type selling_strategy = :LEAD_BASED | :ACCOUNT_BASED

        module SellingStrategy
          extend HubspotSDK::Internal::Type::Enum

          LEAD_BASED: :LEAD_BASED
          ACCOUNT_BASED: :ACCOUNT_BASED

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::EmailSettingsResponse::selling_strategy]
        end
      end
    end
  end
end
