module HubSpotSDK
  module Models
    module Automation
      type field_type_definition =
        {
          external_options: bool,
          name: String,
          options: ::Array[HubSpotSDK::AutomationActionsOption],
          schema: HubSpotSDK::Models::Automation::FieldTypeDefinition::schema,
          type: HubSpotSDK::Models::Automation::FieldTypeDefinition::type_,
          use_chirp: bool,
          description: String,
          external_options_reference_type: String,
          field_type: HubSpotSDK::Models::Automation::FieldTypeDefinition::field_type,
          help_text: String,
          label: String,
          options_url: String,
          referenced_object_type: HubSpotSDK::Models::Automation::FieldTypeDefinition::referenced_object_type
        }

      class FieldTypeDefinition < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor external_options: bool

        attr_accessor name: String

        attr_accessor options: ::Array[HubSpotSDK::AutomationActionsOption]

        attr_accessor schema: HubSpotSDK::Models::Automation::FieldTypeDefinition::schema

        attr_accessor type: HubSpotSDK::Models::Automation::FieldTypeDefinition::type_

        attr_accessor use_chirp: bool

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader external_options_reference_type: String?

        def external_options_reference_type=: (String) -> String

        attr_reader field_type: HubSpotSDK::Models::Automation::FieldTypeDefinition::field_type?

        def field_type=: (
          HubSpotSDK::Models::Automation::FieldTypeDefinition::field_type
        ) -> HubSpotSDK::Models::Automation::FieldTypeDefinition::field_type

        attr_reader help_text: String?

        def help_text=: (String) -> String

        attr_reader label: String?

        def label=: (String) -> String

        attr_reader options_url: String?

        def options_url=: (String) -> String

        attr_reader referenced_object_type: HubSpotSDK::Models::Automation::FieldTypeDefinition::referenced_object_type?

        def referenced_object_type=: (
          HubSpotSDK::Models::Automation::FieldTypeDefinition::referenced_object_type
        ) -> HubSpotSDK::Models::Automation::FieldTypeDefinition::referenced_object_type

        def initialize: (
          external_options: bool,
          name: String,
          options: ::Array[HubSpotSDK::AutomationActionsOption],
          schema: HubSpotSDK::Models::Automation::FieldTypeDefinition::schema,
          type: HubSpotSDK::Models::Automation::FieldTypeDefinition::type_,
          use_chirp: bool,
          ?description: String,
          ?external_options_reference_type: String,
          ?field_type: HubSpotSDK::Models::Automation::FieldTypeDefinition::field_type,
          ?help_text: String,
          ?label: String,
          ?options_url: String,
          ?referenced_object_type: HubSpotSDK::Models::Automation::FieldTypeDefinition::referenced_object_type
        ) -> void

        def to_hash: -> {
          external_options: bool,
          name: String,
          options: ::Array[HubSpotSDK::AutomationActionsOption],
          schema: HubSpotSDK::Models::Automation::FieldTypeDefinition::schema,
          type: HubSpotSDK::Models::Automation::FieldTypeDefinition::type_,
          use_chirp: bool,
          description: String,
          external_options_reference_type: String,
          field_type: HubSpotSDK::Models::Automation::FieldTypeDefinition::field_type,
          help_text: String,
          label: String,
          options_url: String,
          referenced_object_type: HubSpotSDK::Models::Automation::FieldTypeDefinition::referenced_object_type
        }

        type schema =
          HubSpotSDK::Automation::IntegerFieldSchema
          | HubSpotSDK::Automation::LongFieldSchema
          | HubSpotSDK::Automation::DoubleFieldSchema
          | HubSpotSDK::Automation::StringFieldSchema
          | HubSpotSDK::Automation::BooleanFieldSchema
          | HubSpotSDK::Automation::ArrayFieldSchema
          | HubSpotSDK::Automation::ObjectFieldSchema

        module Schema
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Automation::FieldTypeDefinition::schema]
        end

        type type_ =
          :bool
          | :currency_number
          | :date
          | :datetime
          | :enumeration
          | :json
          | :number
          | :object_coordinates
          | :phone_number
          | :string

        module Type
          extend HubSpotSDK::Internal::Type::Enum

          BOOL: :bool
          CURRENCY_NUMBER: :currency_number
          DATE: :date
          DATETIME: :datetime
          ENUMERATION: :enumeration
          JSON: :json
          NUMBER: :number
          OBJECT_COORDINATES: :object_coordinates
          PHONE_NUMBER: :phone_number
          STRING: :string

          def self?.values: -> ::Array[HubSpotSDK::Models::Automation::FieldTypeDefinition::type_]
        end

        type field_type =
          :booleancheckbox
          | :calculation_equation
          | :calculation_read_time
          | :calculation_rollup
          | :calculation_score
          | :checkbox
          | :date
          | :file
          | :html
          | :number
          | :phonenumber
          | :radio
          | :select
          | :text
          | :textarea
          | :unknown

        module FieldType
          extend HubSpotSDK::Internal::Type::Enum

          BOOLEANCHECKBOX: :booleancheckbox
          CALCULATION_EQUATION: :calculation_equation
          CALCULATION_READ_TIME: :calculation_read_time
          CALCULATION_ROLLUP: :calculation_rollup
          CALCULATION_SCORE: :calculation_score
          CHECKBOX: :checkbox
          DATE: :date
          FILE: :file
          HTML: :html
          NUMBER: :number
          PHONENUMBER: :phonenumber
          RADIO: :radio
          SELECT: :select
          TEXT: :text
          TEXTAREA: :textarea
          UNKNOWN: :unknown

          def self?.values: -> ::Array[HubSpotSDK::Models::Automation::FieldTypeDefinition::field_type]
        end

        type referenced_object_type =
          :ABANDONED_CART
          | :ACCEPTANCE_TEST
          | :AD
          | :AD_ACCOUNT
          | :AD_CAMPAIGN
          | :AD_GROUP
          | :AI_FORECAST
          | :ALL_PAGES
          | :APPROVAL
          | :APPROVAL_STEP
          | :ATTRIBUTION
          | :AUDIENCE
          | :AUTOMATION_JOURNEY
          | :AUTOMATION_PLATFORM_FLOW
          | :AUTOMATION_PLATFORM_FLOW_ACTION
          | :BET_ALERT
          | :BET_DELIVERABLE_SERVICE
          | :BLOG_LISTING_PAGE
          | :BLOG_POST
          | :CALL
          | :CAMPAIGN
          | :CAMPAIGN_BUDGET_ITEM
          | :CAMPAIGN_SPEND_ITEM
          | :CAMPAIGN_STEP
          | :CAMPAIGN_TEMPLATE
          | :CAMPAIGN_TEMPLATE_STEP
          | :CART
          | :CASE_STUDY
          | :CHATFLOW
          | :CLIP
          | :CMS_URL
          | :COMBO_EVENT_CONFIGURATION
          | :COMMERCE_PAYMENT
          | :COMMUNICATION
          | :COMPANY
          | :CONTACT
          | :CONTACT_CREATE_ATTRIBUTION
          | :CONTENT
          | :CONTENT_AUDIT
          | :CONTENT_AUDIT_PAGE
          | :CONVERSATION
          | :CONVERSATION_INBOX
          | :CONVERSATION_SESSION
          | :CRM_OBJECTS_DUMMY_TYPE
          | :CRM_PIPELINES_DUMMY_TYPE
          | :CTA
          | :CTA_VARIANT
          | :DATA_PRIVACY_CONSENT
          | :DATA_SYNC_STATE
          | :DEAL
          | :DEAL_CREATE_ATTRIBUTION
          | :DEAL_REGISTRATION
          | :DEAL_SPLIT
          | :DISCOUNT
          | :DISCOUNT_CODE
          | :DISCOUNT_TEMPLATE
          | :EMAIL
          | :ENGAGEMENT
          | :EXPORT
          | :EXTERNAL_WEB_URL
          | :FEE
          | :FEEDBACK_SUBMISSION
          | :FEEDBACK_SURVEY
          | :FILE_MANAGER_FILE
          | :FILE_MANAGER_FOLDER
          | :FOLDER
          | :FORECAST
          | :FORM
          | :FORM_SUBMISSION_INBOUNDDB
          | :GOAL_TARGET
          | :GOAL_TARGET_GROUP
          | :GOAL_TEMPLATE
          | :GSC_PROPERTY
          | :HUB
          | :IMPORT
          | :INVOICE
          | :KEYWORD
          | :KNOWLEDGE_ARTICLE
          | :LANDING_PAGE
          | :LEAD
          | :LINE_ITEM
          | :MARKETING_CALENDAR
          | :MARKETING_CAMPAIGN_UTM
          | :MARKETING_EMAIL
          | :MARKETING_EVENT
          | :MARKETING_EVENT_ATTENDANCE
          | :MARKETING_SMS
          | :MEDIA_BRIDGE
          | :MEETING_EVENT
          | :MIC
          | :NOTE
          | :OBJECT_LIST
          | :ORDER
          | :OWNER
          | :PARTNER_ACCOUNT
          | :PARTNER_CLIENT
          | :PARTNER_CLIENT_REVENUE
          | :PARTNER_SERVICE
          | :PAYMENT_LINK
          | :PAYMENT_SCHEDULE
          | :PAYMENT_SCHEDULE_INSTALLMENT
          | :PERMISSIONS_TESTING
          | :PLAYBOOK
          | :PLAYBOOK_QUESTION
          | :PLAYBOOK_SUBMISSION
          | :PLAYBOOK_SUBMISSION_ANSWER
          | :PLAYLIST
          | :PLAYLIST_FOLDER
          | :PODCAST_EPISODE
          | :PORTAL
          | :PORTAL_OBJECT_SYNC_MESSAGE
          | :POSTAL_MAIL
          | :PRIVACY_SCANNER_COOKIE
          | :PRODUCT
          | :PRODUCT_OR_FOLDER
          | :PROPERTY_INFO
          | :PROSPECTING_AGENT_CONTACT_ASSIGNMENT
          | :PUBLISHING_TASK
          | :QUARANTINED_SUBMISSION
          | :QUOTA
          | :QUOTE
          | :QUOTE_FIELD
          | :QUOTE_MODULE
          | :QUOTE_MODULE_FIELD
          | :QUOTE_TEMPLATE
          | :RESTORABLE_CRM_OBJECT
          | :ROSTER
          | :ROSTER_MEMBER
          | :SALES_DOCUMENT
          | :SALES_TASK
          | :SALES_WORKLOAD
          | :SALESFORCE_SYNC_ERROR
          | :SCHEDULING_PAGE
          | :SCHEMAS_BACKEND_TEST
          | :SCORE_CONFIGURATION
          | :SEQUENCE
          | :SEQUENCE_ENROLLMENT
          | :SEQUENCE_STEP
          | :SEQUENCE_STEP_ENROLLMENT
          | :SERVICE
          | :SITE_PAGE
          | :SNIPPET
          | :SOCIAL_BROADCAST
          | :SOCIAL_CHANNEL
          | :SOCIAL_POST
          | :SOCIAL_PROFILE
          | :SOX_PROTECTED_DUMMY_TYPE
          | :SOX_PROTECTED_TEST_TYPE
          | :SUBMISSION_TAG
          | :SUBSCRIPTION
          | :TASK
          | :TASK_TEMPLATE
          | :TAX
          | :TEMPLATE
          | :TICKET
          | :UNKNOWN
          | :UNSUBSCRIBE
          | :USER
          | :VIEW
          | :VIEW_BLOCK
          | :WEB_INTERACTIVE

        module ReferencedObjectType
          extend HubSpotSDK::Internal::Type::Enum

          ABANDONED_CART: :ABANDONED_CART
          ACCEPTANCE_TEST: :ACCEPTANCE_TEST
          AD: :AD
          AD_ACCOUNT: :AD_ACCOUNT
          AD_CAMPAIGN: :AD_CAMPAIGN
          AD_GROUP: :AD_GROUP
          AI_FORECAST: :AI_FORECAST
          ALL_PAGES: :ALL_PAGES
          APPROVAL: :APPROVAL
          APPROVAL_STEP: :APPROVAL_STEP
          ATTRIBUTION: :ATTRIBUTION
          AUDIENCE: :AUDIENCE
          AUTOMATION_JOURNEY: :AUTOMATION_JOURNEY
          AUTOMATION_PLATFORM_FLOW: :AUTOMATION_PLATFORM_FLOW
          AUTOMATION_PLATFORM_FLOW_ACTION: :AUTOMATION_PLATFORM_FLOW_ACTION
          BET_ALERT: :BET_ALERT
          BET_DELIVERABLE_SERVICE: :BET_DELIVERABLE_SERVICE
          BLOG_LISTING_PAGE: :BLOG_LISTING_PAGE
          BLOG_POST: :BLOG_POST
          CALL: :CALL
          CAMPAIGN: :CAMPAIGN
          CAMPAIGN_BUDGET_ITEM: :CAMPAIGN_BUDGET_ITEM
          CAMPAIGN_SPEND_ITEM: :CAMPAIGN_SPEND_ITEM
          CAMPAIGN_STEP: :CAMPAIGN_STEP
          CAMPAIGN_TEMPLATE: :CAMPAIGN_TEMPLATE
          CAMPAIGN_TEMPLATE_STEP: :CAMPAIGN_TEMPLATE_STEP
          CART: :CART
          CASE_STUDY: :CASE_STUDY
          CHATFLOW: :CHATFLOW
          CLIP: :CLIP
          CMS_URL: :CMS_URL
          COMBO_EVENT_CONFIGURATION: :COMBO_EVENT_CONFIGURATION
          COMMERCE_PAYMENT: :COMMERCE_PAYMENT
          COMMUNICATION: :COMMUNICATION
          COMPANY: :COMPANY
          CONTACT: :CONTACT
          CONTACT_CREATE_ATTRIBUTION: :CONTACT_CREATE_ATTRIBUTION
          CONTENT: :CONTENT
          CONTENT_AUDIT: :CONTENT_AUDIT
          CONTENT_AUDIT_PAGE: :CONTENT_AUDIT_PAGE
          CONVERSATION: :CONVERSATION
          CONVERSATION_INBOX: :CONVERSATION_INBOX
          CONVERSATION_SESSION: :CONVERSATION_SESSION
          CRM_OBJECTS_DUMMY_TYPE: :CRM_OBJECTS_DUMMY_TYPE
          CRM_PIPELINES_DUMMY_TYPE: :CRM_PIPELINES_DUMMY_TYPE
          CTA: :CTA
          CTA_VARIANT: :CTA_VARIANT
          DATA_PRIVACY_CONSENT: :DATA_PRIVACY_CONSENT
          DATA_SYNC_STATE: :DATA_SYNC_STATE
          DEAL: :DEAL
          DEAL_CREATE_ATTRIBUTION: :DEAL_CREATE_ATTRIBUTION
          DEAL_REGISTRATION: :DEAL_REGISTRATION
          DEAL_SPLIT: :DEAL_SPLIT
          DISCOUNT: :DISCOUNT
          DISCOUNT_CODE: :DISCOUNT_CODE
          DISCOUNT_TEMPLATE: :DISCOUNT_TEMPLATE
          EMAIL: :EMAIL
          ENGAGEMENT: :ENGAGEMENT
          EXPORT: :EXPORT
          EXTERNAL_WEB_URL: :EXTERNAL_WEB_URL
          FEE: :FEE
          FEEDBACK_SUBMISSION: :FEEDBACK_SUBMISSION
          FEEDBACK_SURVEY: :FEEDBACK_SURVEY
          FILE_MANAGER_FILE: :FILE_MANAGER_FILE
          FILE_MANAGER_FOLDER: :FILE_MANAGER_FOLDER
          FOLDER: :FOLDER
          FORECAST: :FORECAST
          FORM: :FORM
          FORM_SUBMISSION_INBOUNDDB: :FORM_SUBMISSION_INBOUNDDB
          GOAL_TARGET: :GOAL_TARGET
          GOAL_TARGET_GROUP: :GOAL_TARGET_GROUP
          GOAL_TEMPLATE: :GOAL_TEMPLATE
          GSC_PROPERTY: :GSC_PROPERTY
          HUB: :HUB
          IMPORT: :IMPORT
          INVOICE: :INVOICE
          KEYWORD: :KEYWORD
          KNOWLEDGE_ARTICLE: :KNOWLEDGE_ARTICLE
          LANDING_PAGE: :LANDING_PAGE
          LEAD: :LEAD
          LINE_ITEM: :LINE_ITEM
          MARKETING_CALENDAR: :MARKETING_CALENDAR
          MARKETING_CAMPAIGN_UTM: :MARKETING_CAMPAIGN_UTM
          MARKETING_EMAIL: :MARKETING_EMAIL
          MARKETING_EVENT: :MARKETING_EVENT
          MARKETING_EVENT_ATTENDANCE: :MARKETING_EVENT_ATTENDANCE
          MARKETING_SMS: :MARKETING_SMS
          MEDIA_BRIDGE: :MEDIA_BRIDGE
          MEETING_EVENT: :MEETING_EVENT
          MIC: :MIC
          NOTE: :NOTE
          OBJECT_LIST: :OBJECT_LIST
          ORDER: :ORDER
          OWNER: :OWNER
          PARTNER_ACCOUNT: :PARTNER_ACCOUNT
          PARTNER_CLIENT: :PARTNER_CLIENT
          PARTNER_CLIENT_REVENUE: :PARTNER_CLIENT_REVENUE
          PARTNER_SERVICE: :PARTNER_SERVICE
          PAYMENT_LINK: :PAYMENT_LINK
          PAYMENT_SCHEDULE: :PAYMENT_SCHEDULE
          PAYMENT_SCHEDULE_INSTALLMENT: :PAYMENT_SCHEDULE_INSTALLMENT
          PERMISSIONS_TESTING: :PERMISSIONS_TESTING
          PLAYBOOK: :PLAYBOOK
          PLAYBOOK_QUESTION: :PLAYBOOK_QUESTION
          PLAYBOOK_SUBMISSION: :PLAYBOOK_SUBMISSION
          PLAYBOOK_SUBMISSION_ANSWER: :PLAYBOOK_SUBMISSION_ANSWER
          PLAYLIST: :PLAYLIST
          PLAYLIST_FOLDER: :PLAYLIST_FOLDER
          PODCAST_EPISODE: :PODCAST_EPISODE
          PORTAL: :PORTAL
          PORTAL_OBJECT_SYNC_MESSAGE: :PORTAL_OBJECT_SYNC_MESSAGE
          POSTAL_MAIL: :POSTAL_MAIL
          PRIVACY_SCANNER_COOKIE: :PRIVACY_SCANNER_COOKIE
          PRODUCT: :PRODUCT
          PRODUCT_OR_FOLDER: :PRODUCT_OR_FOLDER
          PROPERTY_INFO: :PROPERTY_INFO
          PROSPECTING_AGENT_CONTACT_ASSIGNMENT: :PROSPECTING_AGENT_CONTACT_ASSIGNMENT
          PUBLISHING_TASK: :PUBLISHING_TASK
          QUARANTINED_SUBMISSION: :QUARANTINED_SUBMISSION
          QUOTA: :QUOTA
          QUOTE: :QUOTE
          QUOTE_FIELD: :QUOTE_FIELD
          QUOTE_MODULE: :QUOTE_MODULE
          QUOTE_MODULE_FIELD: :QUOTE_MODULE_FIELD
          QUOTE_TEMPLATE: :QUOTE_TEMPLATE
          RESTORABLE_CRM_OBJECT: :RESTORABLE_CRM_OBJECT
          ROSTER: :ROSTER
          ROSTER_MEMBER: :ROSTER_MEMBER
          SALES_DOCUMENT: :SALES_DOCUMENT
          SALES_TASK: :SALES_TASK
          SALES_WORKLOAD: :SALES_WORKLOAD
          SALESFORCE_SYNC_ERROR: :SALESFORCE_SYNC_ERROR
          SCHEDULING_PAGE: :SCHEDULING_PAGE
          SCHEMAS_BACKEND_TEST: :SCHEMAS_BACKEND_TEST
          SCORE_CONFIGURATION: :SCORE_CONFIGURATION
          SEQUENCE: :SEQUENCE
          SEQUENCE_ENROLLMENT: :SEQUENCE_ENROLLMENT
          SEQUENCE_STEP: :SEQUENCE_STEP
          SEQUENCE_STEP_ENROLLMENT: :SEQUENCE_STEP_ENROLLMENT
          SERVICE: :SERVICE
          SITE_PAGE: :SITE_PAGE
          SNIPPET: :SNIPPET
          SOCIAL_BROADCAST: :SOCIAL_BROADCAST
          SOCIAL_CHANNEL: :SOCIAL_CHANNEL
          SOCIAL_POST: :SOCIAL_POST
          SOCIAL_PROFILE: :SOCIAL_PROFILE
          SOX_PROTECTED_DUMMY_TYPE: :SOX_PROTECTED_DUMMY_TYPE
          SOX_PROTECTED_TEST_TYPE: :SOX_PROTECTED_TEST_TYPE
          SUBMISSION_TAG: :SUBMISSION_TAG
          SUBSCRIPTION: :SUBSCRIPTION
          TASK: :TASK
          TASK_TEMPLATE: :TASK_TEMPLATE
          TAX: :TAX
          TEMPLATE: :TEMPLATE
          TICKET: :TICKET
          UNKNOWN: :UNKNOWN
          UNSUBSCRIBE: :UNSUBSCRIBE
          USER: :USER
          VIEW: :VIEW
          VIEW_BLOCK: :VIEW_BLOCK
          WEB_INTERACTIVE: :WEB_INTERACTIVE

          def self?.values: -> ::Array[HubSpotSDK::Models::Automation::FieldTypeDefinition::referenced_object_type]
        end
      end
    end
  end
end
