module HubSpotSDK
  module Models
    module Automation
      type integer_field_schema =
        {
          type: HubSpotSDK::Models::Automation::IntegerFieldSchema::type_,
          maximum: Integer,
          minimum: Integer
        }

      class IntegerFieldSchema < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor type: HubSpotSDK::Models::Automation::IntegerFieldSchema::type_

        attr_reader maximum: Integer?

        def maximum=: (Integer) -> Integer

        attr_reader minimum: Integer?

        def minimum=: (Integer) -> Integer

        def initialize: (
          type: HubSpotSDK::Models::Automation::IntegerFieldSchema::type_,
          ?maximum: Integer,
          ?minimum: Integer
        ) -> void

        def to_hash: -> {
          type: HubSpotSDK::Models::Automation::IntegerFieldSchema::type_,
          maximum: Integer,
          minimum: Integer
        }

        type type_ = :INTEGER

        module Type
          extend HubSpotSDK::Internal::Type::Enum

          INTEGER: :INTEGER

          def self?.values: -> ::Array[HubSpotSDK::Models::Automation::IntegerFieldSchema::type_]
        end
      end
    end
  end
end
