module HubspotSDK
  module Models
    module Automation
      type long_field_schema =
        {
          type: HubspotSDK::Models::Automation::LongFieldSchema::type_,
          maximum: Integer,
          minimum: Integer
        }

      class LongFieldSchema < HubspotSDK::Internal::Type::BaseModel
        attr_accessor type: HubspotSDK::Models::Automation::LongFieldSchema::type_

        attr_reader maximum: Integer?

        def maximum=: (Integer) -> Integer

        attr_reader minimum: Integer?

        def minimum=: (Integer) -> Integer

        def initialize: (
          type: HubspotSDK::Models::Automation::LongFieldSchema::type_,
          ?maximum: Integer,
          ?minimum: Integer
        ) -> void

        def to_hash: -> {
          type: HubspotSDK::Models::Automation::LongFieldSchema::type_,
          maximum: Integer,
          minimum: Integer
        }

        type type_ = :LONG

        module Type
          extend HubspotSDK::Internal::Type::Enum

          LONG: :LONG

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::LongFieldSchema::type_]
        end
      end
    end
  end
end
