module HubspotSDK
  module Models
    module Automation
      type public_sequence_response =
        {
          id: String,
          created_at: Time,
          dependencies: ::Array[HubspotSDK::Automation::PublicSequenceStepDependencyResponse],
          name: String,
          steps: ::Array[HubspotSDK::Automation::PublicSequenceStepResponse],
          updated_at: Time,
          user_id: String,
          folder_id: String,
          settings: HubspotSDK::Automation::PublicSequenceSettingsResponse
        }

      class PublicSequenceResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor dependencies: ::Array[HubspotSDK::Automation::PublicSequenceStepDependencyResponse]

        attr_accessor name: String

        attr_accessor steps: ::Array[HubspotSDK::Automation::PublicSequenceStepResponse]

        attr_accessor updated_at: Time

        attr_accessor user_id: String

        attr_reader folder_id: String?

        def folder_id=: (String) -> String

        attr_reader settings: HubspotSDK::Automation::PublicSequenceSettingsResponse?

        def settings=: (
          HubspotSDK::Automation::PublicSequenceSettingsResponse
        ) -> HubspotSDK::Automation::PublicSequenceSettingsResponse

        def initialize: (
          id: String,
          created_at: Time,
          dependencies: ::Array[HubspotSDK::Automation::PublicSequenceStepDependencyResponse],
          name: String,
          steps: ::Array[HubspotSDK::Automation::PublicSequenceStepResponse],
          updated_at: Time,
          user_id: String,
          ?folder_id: String,
          ?settings: HubspotSDK::Automation::PublicSequenceSettingsResponse
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          dependencies: ::Array[HubspotSDK::Automation::PublicSequenceStepDependencyResponse],
          name: String,
          steps: ::Array[HubspotSDK::Automation::PublicSequenceStepResponse],
          updated_at: Time,
          user_id: String,
          folder_id: String,
          settings: HubspotSDK::Automation::PublicSequenceSettingsResponse
        }
      end
    end
  end
end
