module HubSpotSDK
  module Models
    module Automation
      type public_object_request_options = { properties: ::Array[String] }

      class PublicObjectRequestOptions < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor properties: ::Array[String]

        def initialize: (properties: ::Array[String]) -> void

        def to_hash: -> { properties: ::Array[String] }
      end
    end
  end
end
