module HubspotSDK
  module Models
    module Automation
      type public_action_function_identifier =
        {
          function_type: HubspotSDK::Models::Automation::PublicActionFunctionIdentifier::function_type,
          id: String
        }

      class PublicActionFunctionIdentifier < HubspotSDK::Internal::Type::BaseModel
        attr_accessor function_type: HubspotSDK::Models::Automation::PublicActionFunctionIdentifier::function_type

        attr_reader id: String?

        def id=: (String) -> String

        def initialize: (
          function_type: HubspotSDK::Models::Automation::PublicActionFunctionIdentifier::function_type,
          ?id: String
        ) -> void

        def to_hash: -> {
          function_type: HubspotSDK::Models::Automation::PublicActionFunctionIdentifier::function_type,
          id: String
        }

        type function_type =
          :PRE_ACTION_EXECUTION
          | :PRE_FETCH_OPTIONS
          | :POST_FETCH_OPTIONS
          | :POST_ACTION_EXECUTION

        module FunctionType
          extend HubspotSDK::Internal::Type::Enum

          PRE_ACTION_EXECUTION: :PRE_ACTION_EXECUTION
          PRE_FETCH_OPTIONS: :PRE_FETCH_OPTIONS
          POST_FETCH_OPTIONS: :POST_FETCH_OPTIONS
          POST_ACTION_EXECUTION: :POST_ACTION_EXECUTION

          def self?.values: -> ::Array[HubspotSDK::Models::Automation::PublicActionFunctionIdentifier::function_type]
        end
      end
    end
  end
end
