module HubSpotSDK
  module Models
    module Automation
      type public_sequence_step_response =
        {
          id: String,
          action_type: HubSpotSDK::Models::Automation::PublicSequenceStepResponse::action_type,
          created_at: Time,
          delay_millis: Integer,
          step_order: Integer,
          updated_at: Time,
          email_pattern: HubSpotSDK::Automation::PublicEmailPatternResponse,
          task_pattern: HubSpotSDK::Automation::PublicTaskPatternResponse
        }

      class PublicSequenceStepResponse < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor action_type: HubSpotSDK::Models::Automation::PublicSequenceStepResponse::action_type

        attr_accessor created_at: Time

        attr_accessor delay_millis: Integer

        attr_accessor step_order: Integer

        attr_accessor updated_at: Time

        attr_reader email_pattern: HubSpotSDK::Automation::PublicEmailPatternResponse?

        def email_pattern=: (
          HubSpotSDK::Automation::PublicEmailPatternResponse
        ) -> HubSpotSDK::Automation::PublicEmailPatternResponse

        attr_reader task_pattern: HubSpotSDK::Automation::PublicTaskPatternResponse?

        def task_pattern=: (
          HubSpotSDK::Automation::PublicTaskPatternResponse
        ) -> HubSpotSDK::Automation::PublicTaskPatternResponse

        def initialize: (
          id: String,
          action_type: HubSpotSDK::Models::Automation::PublicSequenceStepResponse::action_type,
          created_at: Time,
          delay_millis: Integer,
          step_order: Integer,
          updated_at: Time,
          ?email_pattern: HubSpotSDK::Automation::PublicEmailPatternResponse,
          ?task_pattern: HubSpotSDK::Automation::PublicTaskPatternResponse
        ) -> void

        def to_hash: -> {
          id: String,
          action_type: HubSpotSDK::Models::Automation::PublicSequenceStepResponse::action_type,
          created_at: Time,
          delay_millis: Integer,
          step_order: Integer,
          updated_at: Time,
          email_pattern: HubSpotSDK::Automation::PublicEmailPatternResponse,
          task_pattern: HubSpotSDK::Automation::PublicTaskPatternResponse
        }

        type action_type = :EMAIL | :FINISH_ENROLLMENT | :TASK

        module ActionType
          extend HubSpotSDK::Internal::Type::Enum

          EMAIL: :EMAIL
          FINISH_ENROLLMENT: :FINISH_ENROLLMENT
          TASK: :TASK

          def self?.values: -> ::Array[HubSpotSDK::Models::Automation::PublicSequenceStepResponse::action_type]
        end
      end
    end
  end
end
