module HubspotSDK
  module Models
    module Automation
      type public_sequence_lite_response =
        {
          id: String,
          created_at: Time,
          name: String,
          updated_at: Time,
          user_id: String,
          folder_id: String
        }

      class PublicSequenceLiteResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor name: String

        attr_accessor updated_at: Time

        attr_accessor user_id: String

        attr_reader folder_id: String?

        def folder_id=: (String) -> String

        def initialize: (
          id: String,
          created_at: Time,
          name: String,
          updated_at: Time,
          user_id: String,
          ?folder_id: String
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          name: String,
          updated_at: Time,
          user_id: String,
          folder_id: String
        }
      end
    end
  end
end
