module HubspotSDK
  module Models
    module Automation
      type public_action_definition_patch =
        {
          action_url: String,
          execution_rules: ::Array[HubspotSDK::Automation::PublicExecutionTranslationRule],
          input_field_dependencies: ::Array[HubspotSDK::Models::Automation::PublicActionDefinitionPatch::input_field_dependency],
          input_fields: ::Array[HubspotSDK::Automation::InputFieldDefinition],
          labels: ::Hash[Symbol, HubspotSDK::Automation::PublicActionLabels],
          object_request_options: HubspotSDK::Automation::PublicObjectRequestOptions,
          object_types: ::Array[String],
          output_fields: ::Array[HubspotSDK::Automation::OutputFieldDefinition],
          published: bool
        }

      class PublicActionDefinitionPatch < HubspotSDK::Internal::Type::BaseModel
        attr_reader action_url: String?

        def action_url=: (String) -> String

        attr_reader execution_rules: ::Array[HubspotSDK::Automation::PublicExecutionTranslationRule]?

        def execution_rules=: (
          ::Array[HubspotSDK::Automation::PublicExecutionTranslationRule]
        ) -> ::Array[HubspotSDK::Automation::PublicExecutionTranslationRule]

        attr_reader input_field_dependencies: ::Array[HubspotSDK::Models::Automation::PublicActionDefinitionPatch::input_field_dependency]?

        def input_field_dependencies=: (
          ::Array[HubspotSDK::Models::Automation::PublicActionDefinitionPatch::input_field_dependency]
        ) -> ::Array[HubspotSDK::Models::Automation::PublicActionDefinitionPatch::input_field_dependency]

        attr_reader input_fields: ::Array[HubspotSDK::Automation::InputFieldDefinition]?

        def input_fields=: (
          ::Array[HubspotSDK::Automation::InputFieldDefinition]
        ) -> ::Array[HubspotSDK::Automation::InputFieldDefinition]

        attr_reader labels: ::Hash[Symbol, HubspotSDK::Automation::PublicActionLabels]?

        def labels=: (
          ::Hash[Symbol, HubspotSDK::Automation::PublicActionLabels]
        ) -> ::Hash[Symbol, HubspotSDK::Automation::PublicActionLabels]

        attr_reader object_request_options: HubspotSDK::Automation::PublicObjectRequestOptions?

        def object_request_options=: (
          HubspotSDK::Automation::PublicObjectRequestOptions
        ) -> HubspotSDK::Automation::PublicObjectRequestOptions

        attr_reader object_types: ::Array[String]?

        def object_types=: (::Array[String]) -> ::Array[String]

        attr_reader output_fields: ::Array[HubspotSDK::Automation::OutputFieldDefinition]?

        def output_fields=: (
          ::Array[HubspotSDK::Automation::OutputFieldDefinition]
        ) -> ::Array[HubspotSDK::Automation::OutputFieldDefinition]

        attr_reader published: bool?

        def published=: (bool) -> bool

        def initialize: (
          ?action_url: String,
          ?execution_rules: ::Array[HubspotSDK::Automation::PublicExecutionTranslationRule],
          ?input_field_dependencies: ::Array[HubspotSDK::Models::Automation::PublicActionDefinitionPatch::input_field_dependency],
          ?input_fields: ::Array[HubspotSDK::Automation::InputFieldDefinition],
          ?labels: ::Hash[Symbol, HubspotSDK::Automation::PublicActionLabels],
          ?object_request_options: HubspotSDK::Automation::PublicObjectRequestOptions,
          ?object_types: ::Array[String],
          ?output_fields: ::Array[HubspotSDK::Automation::OutputFieldDefinition],
          ?published: bool
        ) -> void

        def to_hash: -> {
          action_url: String,
          execution_rules: ::Array[HubspotSDK::Automation::PublicExecutionTranslationRule],
          input_field_dependencies: ::Array[HubspotSDK::Models::Automation::PublicActionDefinitionPatch::input_field_dependency],
          input_fields: ::Array[HubspotSDK::Automation::InputFieldDefinition],
          labels: ::Hash[Symbol, HubspotSDK::Automation::PublicActionLabels],
          object_request_options: HubspotSDK::Automation::PublicObjectRequestOptions,
          object_types: ::Array[String],
          output_fields: ::Array[HubspotSDK::Automation::OutputFieldDefinition],
          published: bool
        }

        type input_field_dependency =
          HubspotSDK::Automation::PublicSingleFieldDependency
          | HubspotSDK::Automation::PublicConditionalSingleFieldDependency

        module InputFieldDependency
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Automation::PublicActionDefinitionPatch::input_field_dependency]
        end
      end
    end
  end
end
