module HubSpotSDK
  module Models
    module Automation
      type public_sequence_enrollment_request =
        {
          contact_id: String,
          sender_email: String,
          sequence_id: String,
          sender_alias_address: String
        }

      class PublicSequenceEnrollmentRequest < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor contact_id: String

        attr_accessor sender_email: String

        attr_accessor sequence_id: String

        attr_reader sender_alias_address: String?

        def sender_alias_address=: (String) -> String

        def initialize: (
          contact_id: String,
          sender_email: String,
          sequence_id: String,
          ?sender_alias_address: String
        ) -> void

        def to_hash: -> {
          contact_id: String,
          sender_email: String,
          sequence_id: String,
          sender_alias_address: String
        }
      end
    end
  end
end
