module HubspotSDK
  module Models
    module Automation
      type public_sequence_step_dependency_response =
        {
          id: String,
          created_at: Time,
          dependency_type: String,
          relies_on_sequence_step_id: String,
          relies_on_step_order: Integer,
          required_by_sequence_step_id: String,
          required_by_step_order: Integer,
          updated_at: Time
        }

      class PublicSequenceStepDependencyResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor dependency_type: String

        attr_accessor relies_on_sequence_step_id: String

        attr_accessor relies_on_step_order: Integer

        attr_accessor required_by_sequence_step_id: String

        attr_accessor required_by_step_order: Integer

        attr_accessor updated_at: Time

        def initialize: (
          id: String,
          created_at: Time,
          dependency_type: String,
          relies_on_sequence_step_id: String,
          relies_on_step_order: Integer,
          required_by_sequence_step_id: String,
          required_by_step_order: Integer,
          updated_at: Time
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          dependency_type: String,
          relies_on_sequence_step_id: String,
          relies_on_step_order: Integer,
          required_by_sequence_step_id: String,
          required_by_step_order: Integer,
          updated_at: Time
        }
      end
    end
  end
end
