module HubSpotSDK
  module Models
    module Automation
      type public_action_definition =
        {
          id: String,
          action_url: String,
          functions: ::Array[HubSpotSDK::Automation::PublicActionFunctionIdentifier],
          input_fields: ::Array[HubSpotSDK::Automation::PublicInputFieldDefinition],
          labels: ::Hash[Symbol, HubSpotSDK::Automation::PublicActionLabels],
          object_types: ::Array[String],
          published: bool,
          revision_id: String,
          archived_at: Integer,
          execution_rules: ::Array[HubSpotSDK::Automation::PublicExecutionTranslationRule],
          input_field_dependencies: ::Array[HubSpotSDK::Models::Automation::PublicActionDefinition::input_field_dependency],
          object_request_options: HubSpotSDK::Automation::PublicObjectRequestOptions,
          output_fields: ::Array[HubSpotSDK::Automation::OutputFieldDefinition]
        }

      class PublicActionDefinition < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor action_url: String

        attr_accessor functions: ::Array[HubSpotSDK::Automation::PublicActionFunctionIdentifier]

        attr_accessor input_fields: ::Array[HubSpotSDK::Automation::PublicInputFieldDefinition]

        attr_accessor labels: ::Hash[Symbol, HubSpotSDK::Automation::PublicActionLabels]

        attr_accessor object_types: ::Array[String]

        attr_accessor published: bool

        attr_accessor revision_id: String

        attr_reader archived_at: Integer?

        def archived_at=: (Integer) -> Integer

        attr_reader execution_rules: ::Array[HubSpotSDK::Automation::PublicExecutionTranslationRule]?

        def execution_rules=: (
          ::Array[HubSpotSDK::Automation::PublicExecutionTranslationRule]
        ) -> ::Array[HubSpotSDK::Automation::PublicExecutionTranslationRule]

        attr_reader input_field_dependencies: ::Array[HubSpotSDK::Models::Automation::PublicActionDefinition::input_field_dependency]?

        def input_field_dependencies=: (
          ::Array[HubSpotSDK::Models::Automation::PublicActionDefinition::input_field_dependency]
        ) -> ::Array[HubSpotSDK::Models::Automation::PublicActionDefinition::input_field_dependency]

        attr_reader object_request_options: HubSpotSDK::Automation::PublicObjectRequestOptions?

        def object_request_options=: (
          HubSpotSDK::Automation::PublicObjectRequestOptions
        ) -> HubSpotSDK::Automation::PublicObjectRequestOptions

        attr_reader output_fields: ::Array[HubSpotSDK::Automation::OutputFieldDefinition]?

        def output_fields=: (
          ::Array[HubSpotSDK::Automation::OutputFieldDefinition]
        ) -> ::Array[HubSpotSDK::Automation::OutputFieldDefinition]

        def initialize: (
          id: String,
          action_url: String,
          functions: ::Array[HubSpotSDK::Automation::PublicActionFunctionIdentifier],
          input_fields: ::Array[HubSpotSDK::Automation::PublicInputFieldDefinition],
          labels: ::Hash[Symbol, HubSpotSDK::Automation::PublicActionLabels],
          object_types: ::Array[String],
          published: bool,
          revision_id: String,
          ?archived_at: Integer,
          ?execution_rules: ::Array[HubSpotSDK::Automation::PublicExecutionTranslationRule],
          ?input_field_dependencies: ::Array[HubSpotSDK::Models::Automation::PublicActionDefinition::input_field_dependency],
          ?object_request_options: HubSpotSDK::Automation::PublicObjectRequestOptions,
          ?output_fields: ::Array[HubSpotSDK::Automation::OutputFieldDefinition]
        ) -> void

        def to_hash: -> {
          id: String,
          action_url: String,
          functions: ::Array[HubSpotSDK::Automation::PublicActionFunctionIdentifier],
          input_fields: ::Array[HubSpotSDK::Automation::PublicInputFieldDefinition],
          labels: ::Hash[Symbol, HubSpotSDK::Automation::PublicActionLabels],
          object_types: ::Array[String],
          published: bool,
          revision_id: String,
          archived_at: Integer,
          execution_rules: ::Array[HubSpotSDK::Automation::PublicExecutionTranslationRule],
          input_field_dependencies: ::Array[HubSpotSDK::Models::Automation::PublicActionDefinition::input_field_dependency],
          object_request_options: HubSpotSDK::Automation::PublicObjectRequestOptions,
          output_fields: ::Array[HubSpotSDK::Automation::OutputFieldDefinition]
        }

        type input_field_dependency =
          HubSpotSDK::Automation::PublicSingleFieldDependency
          | HubSpotSDK::Automation::PublicConditionalSingleFieldDependency

        module InputFieldDependency
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Automation::PublicActionDefinition::input_field_dependency]
        end
      end
    end
  end
end
