module HubSpotSDK
  module Models
    module Automation
      type sequence_get_enrollment_by_contact_id_params =
        { contact_id: String } & HubSpotSDK::Internal::Type::request_parameters

      class SequenceGetEnrollmentByContactIDParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor contact_id: String

        def initialize: (
          contact_id: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          contact_id: String,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
