module HubSpotSDK
  module Models
    module Automation
      type sequence_create_enrollment_params =
        { user_id: String } & HubSpotSDK::Internal::Type::request_parameters

      class SequenceCreateEnrollmentParams < HubSpotSDK::Models::Automation::PublicSequenceEnrollmentRequest
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        def user_id: -> String

        def user_id=: (String _) -> String

        def initialize: (
          user_id: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          user_id: String,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
