module HubSpotSDK
  module Models
    module Automation
      type test_request_context =
        { source: HubSpotSDK::Models::Automation::TestRequestContext::source }

      class TestRequestContext < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor source: HubSpotSDK::Models::Automation::TestRequestContext::source

        def initialize: (
          source: HubSpotSDK::Models::Automation::TestRequestContext::source
        ) -> void

        def to_hash: -> {
          source: HubSpotSDK::Models::Automation::TestRequestContext::source
        }

        type source = :TEST

        module Source
          extend HubSpotSDK::Internal::Type::Enum

          TEST: :TEST

          def self?.values: -> ::Array[HubSpotSDK::Models::Automation::TestRequestContext::source]
        end
      end
    end
  end
end
