module HubSpotSDK
  module Models
    module CommunicationPreferences
      module Statuses
        type batch_get_unsubscribe_all_statuses_params =
          {
            channel: HubSpotSDK::Models::BatchInputString::channel,
            business_unit_id: Integer
          }
          & HubSpotSDK::Internal::Type::request_parameters

        class BatchGetUnsubscribeAllStatusesParams < HubSpotSDK::Models::BatchInputString
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def channel: -> HubSpotSDK::Models::BatchInputString::channel

          def channel=: (
            HubSpotSDK::Models::BatchInputString::channel _
          ) -> HubSpotSDK::Models::BatchInputString::channel

          def business_unit_id: -> Integer?

          def business_unit_id=: (Integer _) -> Integer

          def initialize: (
            channel: HubSpotSDK::Models::BatchInputString::channel,
            ?business_unit_id: Integer,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            channel: HubSpotSDK::Models::BatchInputString::channel,
            business_unit_id: Integer,
            request_options: HubSpotSDK::RequestOptions
          }

          type channel = :EMAIL

          module Channel
            extend HubSpotSDK::Internal::Type::Enum

            EMAIL: :EMAIL

            def self?.values: -> ::Array[HubSpotSDK::Models::BatchInputString::channel]
          end
        end
      end
    end
  end
end
