module HubSpotSDK
  module Resources
    class Crm
      class AssociationsSchema
        class Labels
          def batch_create: (
            String to_object_type,
            from_object_type: String,
            inputs: ::Array[HubSpotSDK::Crm::PublicAssociationDefinitionConfigurationCreateRequest],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::BatchResponsePublicAssociationDefinitionUserConfiguration

          def create_label: (
            String to_object_type,
            from_object_type: String,
            label: String,
            name: String,
            ?inverse_label: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::CollectionResponseAssociationSpecWithLabelNoPaging

          def delete_label: (
            Integer association_type_id,
            from_object_type: String,
            to_object_type: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> nil

          def list_labels: (
            String to_object_type,
            from_object_type: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::CollectionResponseAssociationSpecWithLabelNoPaging

          def update_label: (
            String to_object_type,
            from_object_type: String,
            association_type_id: Integer,
            label: String,
            ?inverse_label: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> nil

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
