module HubspotSDK
  module Resources
    class Webhooks
      class Settings
        def update: (
          Integer app_id,
          target_url: String,
          throttling: HubspotSDK::Webhooks::ThrottlingSettings,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Webhooks::SettingsResponse

        def list: (
          Integer app_id,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Webhooks::SettingsResponse

        def delete: (
          Integer app_id,
          ?request_options: HubspotSDK::request_opts
        ) -> nil

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
