module HubSpotSDK
  module Resources
    class CommunicationPreferences
      class Statuses
        class Batch
          def get_unsubscribe_all_statuses: (
            channel: HubSpotSDK::Models::BatchInputString::channel,
            inputs: ::Array[String],
            ?business_unit_id: Integer,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::CommunicationPreferences::BatchResponsePublicWideStatusBulkResponse

          def read: (
            channel: HubSpotSDK::Models::BatchInputString::channel,
            inputs: ::Array[String],
            ?business_unit_id: Integer,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::CommunicationPreferences::BatchResponsePublicStatusBulkResponse

          def unsubscribe_all: (
            channel: HubSpotSDK::Models::BatchInputString::channel,
            inputs: ::Array[String],
            ?business_unit_id: Integer,
            ?verbose: bool,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::CommunicationPreferences::BatchResponsePublicBulkOptOutFromAllResponse

          def update_statuses: (
            inputs: ::Array[HubSpotSDK::CommunicationPreferences::PublicStatusRequest],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::CommunicationPreferences::BatchResponsePublicStatus

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
