module HubSpotSDK
  module Models
    module Cms
      module Pages
        type ab_test_end_landing_page_test_params =
          {  } & HubSpotSDK::Internal::Type::request_parameters

        class ABTestEndLandingPageTestParams < HubSpotSDK::Models::Cms::AbTestEndRequestVNext
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def initialize: (?request_options: HubSpotSDK::request_opts) -> void

          def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
        end
      end
    end
  end
end
