module HubSpotSDK
  module Models
    module Cms
      module Pages
        type batch_create_site_pages_params =
          {  } & HubSpotSDK::Internal::Type::request_parameters

        class BatchCreateSitePagesParams < HubSpotSDK::Models::Cms::BatchInputPage
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def initialize: (?request_options: HubSpotSDK::request_opts) -> void

          def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
        end
      end
    end
  end
end
