module HubSpotSDK
  module Models
    module Cms
      module Pages
        type landing_page_create_params =
          {  } & HubSpotSDK::Internal::Type::request_parameters

        class LandingPageCreateParams < HubSpotSDK::Models::Cms::PageData
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def initialize: (?request_options: HubSpotSDK::request_opts) -> void

          def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
        end
      end
    end
  end
end
