module HubspotSDK
  module Models
    module Cms
      module Pages
        type landing_page_get_folder_params =
          { archived: bool, property: String }
          & HubspotSDK::Internal::Type::request_parameters

        class LandingPageGetFolderParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_reader archived: bool?

          def archived=: (bool) -> bool

          attr_reader property: String?

          def property=: (String) -> String

          def initialize: (
            ?archived: bool,
            ?property: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            archived: bool,
            property: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
