module HubspotSDK
  module Models
    module Cms
      module Pages
        type site_page_schedule_params =
          {  } & HubspotSDK::Internal::Type::request_parameters

        class SitePageScheduleParams < HubspotSDK::Models::Cms::ContentScheduleRequestVNext
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          def initialize: (?request_options: HubspotSDK::request_opts) -> void

          def to_hash: -> { request_options: HubspotSDK::RequestOptions }
        end
      end
    end
  end
end
