module HubSpotSDK
  module Models
    module Cms
      module Pages
        type website_page_update_params =
          { object_id_: String, archived: bool }
          & HubSpotSDK::Internal::Type::request_parameters

        class WebsitePageUpdateParams < HubSpotSDK::Models::Cms::PageData
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def object_id_: -> String

          def object_id_=: (String _) -> String

          def archived: -> bool?

          def archived=: (bool _) -> bool

          def initialize: (
            object_id_: String,
            ?archived: bool,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            object_id_: String,
            archived: bool,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
