module HubSpotSDK
  module Models
    module Cms
      module Pages
        type website_page_publish_draft_params =
          { object_id_: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class WebsitePagePublishDraftParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor object_id_: String

          def initialize: (
            object_id_: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            object_id_: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
