module HubspotSDK
  module Resources
    class Marketing
      class Campaigns
        attr_reader assets: HubspotSDK::Resources::Marketing::Campaigns::Assets

        attr_reader batch: HubspotSDK::Resources::Marketing::Campaigns::Batch

        attr_reader budget: HubspotSDK::Resources::Marketing::Campaigns::Budget

        attr_reader reports: HubspotSDK::Resources::Marketing::Campaigns::Reports

        attr_reader spend: HubspotSDK::Resources::Marketing::Campaigns::Spend

        def create: (
          properties: ::Hash[Symbol, String],
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Marketing::PublicCampaign

        def update: (
          String campaign_guid,
          properties: ::Hash[Symbol, String],
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Marketing::PublicCampaign

        def list: (
          ?after: String,
          ?limit: Integer,
          ?name: String,
          ?properties: ::Array[String],
          ?sort: String,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Internal::Page[HubspotSDK::Marketing::PublicCampaign]

        def delete: (
          String campaign_guid,
          ?request_options: HubspotSDK::request_opts
        ) -> nil

        def get: (
          String campaign_guid,
          ?end_date: String,
          ?properties: ::Array[String],
          ?start_date: String,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Marketing::PublicCampaignWithAssets

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
