module HubSpotSDK
  module Resources
    class Marketing
      class Campaigns
        attr_reader assets: HubSpotSDK::Resources::Marketing::Campaigns::Assets

        attr_reader batch: HubSpotSDK::Resources::Marketing::Campaigns::Batch

        attr_reader budget: HubSpotSDK::Resources::Marketing::Campaigns::Budget

        attr_reader metrics: HubSpotSDK::Resources::Marketing::Campaigns::Metrics

        attr_reader spend: HubSpotSDK::Resources::Marketing::Campaigns::Spend

        def create: (
          properties: ::Hash[Symbol, String],
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Marketing::PublicCampaign

        def update: (
          String campaign_guid,
          properties: ::Hash[Symbol, String],
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Marketing::PublicCampaign

        def list: (
          ?after: String,
          ?limit: Integer,
          ?name: String,
          ?properties: ::Array[String],
          ?sort: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Marketing::PublicCampaign]

        def delete: (
          String campaign_guid,
          ?request_options: HubSpotSDK::request_opts
        ) -> nil

        def get: (
          String campaign_guid,
          ?end_date: String,
          ?properties: ::Array[String],
          ?start_date: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Marketing::PublicCampaignWithAssets

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
