module HubspotSDK
  module Resources
    class Marketing
      class Forms
        def create: (
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Marketing::FormDefinitionBase

        def update: (
          String form_id,
          ?archived: bool,
          ?configuration: HubspotSDK::Marketing::HubSpotFormConfiguration,
          ?display_options: HubspotSDK::Marketing::FormDisplayOptions,
          ?field_groups: ::Array[HubspotSDK::Marketing::FieldGroup],
          ?legal_consent_options: HubspotSDK::Models::Marketing::HubSpotFormDefinitionPatchRequest::legal_consent_options,
          ?name: String,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Marketing::FormDefinitionBase

        def list: (
          ?after: String,
          ?archived: bool,
          ?form_types: ::Array[HubspotSDK::Models::Marketing::FormListParams::form_type],
          ?limit: Integer,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Internal::Page[HubspotSDK::Marketing::HubSpotFormDefinition]

        def delete: (
          String form_id,
          ?request_options: HubspotSDK::request_opts
        ) -> nil

        def get: (
          String form_id,
          ?archived: bool,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Marketing::FormDefinitionBase

        def replace: (
          String form_id,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Marketing::FormDefinitionBase

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
