module HubspotSDK
  module Resources
    class Marketing
      class Subscriptions
        attr_reader v4: HubspotSDK::Resources::Marketing::Subscriptions::V4

        def list: (
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Marketing::SubscriptionDefinitionsResponse

        def get_email_status: (
          String email_address,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Marketing::PublicSubscriptionStatusesResponse

        def subscribe: (
          email_address: String,
          subscription_id: String,
          ?legal_basis: HubspotSDK::Models::Marketing::PublicUpdateSubscriptionStatusRequest::legal_basis,
          ?legal_basis_explanation: String,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Marketing::PublicSubscriptionStatus

        def unsubscribe: (
          email_address: String,
          subscription_id: String,
          ?legal_basis: HubspotSDK::Models::Marketing::PublicUpdateSubscriptionStatusRequest::legal_basis,
          ?legal_basis_explanation: String,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Marketing::PublicSubscriptionStatus

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
