module HubSpotSDK
  module Resources
    class Marketing
      class Transactional
        attr_reader single_email: HubSpotSDK::Resources::Marketing::Transactional::SingleEmail

        attr_reader smtp_tokens: HubSpotSDK::Resources::Marketing::Transactional::SmtpTokens

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
