module HubspotSDK
  module Resources
    class Marketing
      class Transactional
        attr_reader single_email: HubspotSDK::Resources::Marketing::Transactional::SingleEmail

        attr_reader smtp_tokens: HubspotSDK::Resources::Marketing::Transactional::SmtpTokens

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
