module HubspotSDK
  module Resources
    class Cms
      class Blogs
        class Posts
          attr_reader batch: HubspotSDK::Resources::Cms::Blogs::Posts::Batch

          def create: (
            id: String,
            ab_status: HubspotSDK::Models::Cms::Blogs::BlogPost::ab_status,
            ab_test_id: String,
            archived_at: Integer,
            archived_in_dashboard: bool,
            attached_stylesheets: ::Array[::Hash[Symbol, top]],
            author_name: String,
            blog_author_id: String,
            campaign: String,
            category_id: Integer,
            content_group_id: String,
            content_type_category: HubspotSDK::Models::Cms::Blogs::BlogPost::content_type_category,
            created: Time,
            created_by_id: String,
            currently_published: bool,
            current_state: HubspotSDK::Models::Cms::Blogs::BlogPost::current_state,
            domain: String,
            dynamic_page_data_source_id: String,
            dynamic_page_data_source_type: Integer,
            dynamic_page_hub_db_table_id: String,
            enable_domain_stylesheets: bool,
            enable_google_amp_output_override: bool,
            enable_layout_stylesheets: bool,
            featured_image: String,
            featured_image_alt_text: String,
            folder_id: String,
            footer_html: String,
            head_html: String,
            html_title: String,
            include_default_custom_css: bool,
            language: HubspotSDK::Models::Cms::Blogs::BlogPost::language,
            layout_sections: ::Hash[Symbol, HubspotSDK::Cms::Blogs::LayoutSection],
            link_rel_canonical_url: String,
            mab_experiment_id: String,
            meta_description: String,
            name: String,
            page_expiry_date: Integer,
            page_expiry_enabled: bool,
            page_expiry_redirect_id: Integer,
            page_expiry_redirect_url: String,
            password: String,
            post_body: String,
            post_summary: String,
            public_access_rules: ::Array[top],
            public_access_rules_enabled: bool,
            publish_date: Time,
            publish_immediately: bool,
            rss_body: String,
            rss_summary: String,
            slug: String,
            state: String,
            tag_ids: ::Array[Integer],
            theme_settings_values: ::Hash[Symbol, top],
            translated_from_id: String,
            translations: ::Hash[Symbol, HubspotSDK::Cms::Blogs::ContentLanguageVariation],
            updated: Time,
            updated_by_id: String,
            url: String,
            use_featured_image: bool,
            widget_containers: ::Hash[Symbol, top],
            widgets: ::Hash[Symbol, top],
            ?request_options: HubspotSDK::request_opts
          ) -> StringIO

          def update: (
            String object_id_,
            id: String,
            ab_status: HubspotSDK::Models::Cms::Blogs::BlogPost::ab_status,
            ab_test_id: String,
            archived_at: Integer,
            archived_in_dashboard: bool,
            attached_stylesheets: ::Array[::Hash[Symbol, top]],
            author_name: String,
            blog_author_id: String,
            campaign: String,
            category_id: Integer,
            content_group_id: String,
            content_type_category: HubspotSDK::Models::Cms::Blogs::BlogPost::content_type_category,
            created: Time,
            created_by_id: String,
            currently_published: bool,
            current_state: HubspotSDK::Models::Cms::Blogs::BlogPost::current_state,
            domain: String,
            dynamic_page_data_source_id: String,
            dynamic_page_data_source_type: Integer,
            dynamic_page_hub_db_table_id: String,
            enable_domain_stylesheets: bool,
            enable_google_amp_output_override: bool,
            enable_layout_stylesheets: bool,
            featured_image: String,
            featured_image_alt_text: String,
            folder_id: String,
            footer_html: String,
            head_html: String,
            html_title: String,
            include_default_custom_css: bool,
            language: HubspotSDK::Models::Cms::Blogs::BlogPost::language,
            layout_sections: ::Hash[Symbol, HubspotSDK::Cms::Blogs::LayoutSection],
            link_rel_canonical_url: String,
            mab_experiment_id: String,
            meta_description: String,
            name: String,
            page_expiry_date: Integer,
            page_expiry_enabled: bool,
            page_expiry_redirect_id: Integer,
            page_expiry_redirect_url: String,
            password: String,
            post_body: String,
            post_summary: String,
            public_access_rules: ::Array[top],
            public_access_rules_enabled: bool,
            publish_date: Time,
            publish_immediately: bool,
            rss_body: String,
            rss_summary: String,
            slug: String,
            state: String,
            tag_ids: ::Array[Integer],
            theme_settings_values: ::Hash[Symbol, top],
            translated_from_id: String,
            translations: ::Hash[Symbol, HubspotSDK::Cms::Blogs::ContentLanguageVariation],
            updated: Time,
            updated_by_id: String,
            url: String,
            use_featured_image: bool,
            widget_containers: ::Hash[Symbol, top],
            widgets: ::Hash[Symbol, top],
            ?archived: bool,
            ?request_options: HubspotSDK::request_opts
          ) -> StringIO

          def list: (
            ?after: String,
            ?archived: bool,
            ?created_after: Time,
            ?created_at: Time,
            ?created_before: Time,
            ?limit: Integer,
            ?property: String,
            ?sort: ::Array[String],
            ?updated_after: Time,
            ?updated_at: Time,
            ?updated_before: Time,
            ?request_options: HubspotSDK::request_opts
          ) -> StringIO

          def delete: (
            String object_id_,
            ?archived: bool,
            ?request_options: HubspotSDK::request_opts
          ) -> nil

          def attach_to_lang_group: (
            id: String,
            language: HubspotSDK::Models::Cms::AttachToLangPrimaryRequestVNext::language,
            primary_id: String,
            ?primary_language: HubspotSDK::Models::Cms::AttachToLangPrimaryRequestVNext::primary_language,
            ?request_options: HubspotSDK::request_opts
          ) -> StringIO

          def clone_: (
            id: String,
            ?clone_name: String,
            ?request_options: HubspotSDK::request_opts
          ) -> StringIO

          def create_lang_variation: (
            id: String,
            ?language: String,
            ?request_options: HubspotSDK::request_opts
          ) -> StringIO

          def detach_from_lang_group: (
            id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> StringIO

          def get: (
            String object_id_,
            ?archived: bool,
            ?property: String,
            ?request_options: HubspotSDK::request_opts
          ) -> StringIO

          def get_draft_by_id: (
            String object_id_,
            ?request_options: HubspotSDK::request_opts
          ) -> StringIO

          def get_previous_version: (
            String revision_id,
            object_id_: String,
            ?request_options: HubspotSDK::request_opts
          ) -> StringIO

          def get_previous_versions: (
            String object_id_,
            ?after: String,
            ?before: String,
            ?limit: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> StringIO

          def push_live: (
            String object_id_,
            ?request_options: HubspotSDK::request_opts
          ) -> nil

          def reset_draft: (
            String object_id_,
            ?request_options: HubspotSDK::request_opts
          ) -> nil

          def restore_previous_version: (
            String revision_id,
            object_id_: String,
            ?request_options: HubspotSDK::request_opts
          ) -> StringIO

          def restore_previous_version_to_draft: (
            Integer revision_id,
            object_id_: String,
            ?request_options: HubspotSDK::request_opts
          ) -> StringIO

          def schedule: (
            id: String,
            publish_date: Time,
            ?request_options: HubspotSDK::request_opts
          ) -> nil

          def set_lang_primary: (
            id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> nil

          def update_draft: (
            String object_id_,
            id: String,
            ab_status: HubspotSDK::Models::Cms::Blogs::BlogPost::ab_status,
            ab_test_id: String,
            archived_at: Integer,
            archived_in_dashboard: bool,
            attached_stylesheets: ::Array[::Hash[Symbol, top]],
            author_name: String,
            blog_author_id: String,
            campaign: String,
            category_id: Integer,
            content_group_id: String,
            content_type_category: HubspotSDK::Models::Cms::Blogs::BlogPost::content_type_category,
            created: Time,
            created_by_id: String,
            currently_published: bool,
            current_state: HubspotSDK::Models::Cms::Blogs::BlogPost::current_state,
            domain: String,
            dynamic_page_data_source_id: String,
            dynamic_page_data_source_type: Integer,
            dynamic_page_hub_db_table_id: String,
            enable_domain_stylesheets: bool,
            enable_google_amp_output_override: bool,
            enable_layout_stylesheets: bool,
            featured_image: String,
            featured_image_alt_text: String,
            folder_id: String,
            footer_html: String,
            head_html: String,
            html_title: String,
            include_default_custom_css: bool,
            language: HubspotSDK::Models::Cms::Blogs::BlogPost::language,
            layout_sections: ::Hash[Symbol, HubspotSDK::Cms::Blogs::LayoutSection],
            link_rel_canonical_url: String,
            mab_experiment_id: String,
            meta_description: String,
            name: String,
            page_expiry_date: Integer,
            page_expiry_enabled: bool,
            page_expiry_redirect_id: Integer,
            page_expiry_redirect_url: String,
            password: String,
            post_body: String,
            post_summary: String,
            public_access_rules: ::Array[top],
            public_access_rules_enabled: bool,
            publish_date: Time,
            publish_immediately: bool,
            rss_body: String,
            rss_summary: String,
            slug: String,
            state: String,
            tag_ids: ::Array[Integer],
            theme_settings_values: ::Hash[Symbol, top],
            translated_from_id: String,
            translations: ::Hash[Symbol, HubspotSDK::Cms::Blogs::ContentLanguageVariation],
            updated: Time,
            updated_by_id: String,
            url: String,
            use_featured_image: bool,
            widget_containers: ::Hash[Symbol, top],
            widgets: ::Hash[Symbol, top],
            ?request_options: HubspotSDK::request_opts
          ) -> StringIO

          def update_langs: (
            languages: ::Hash[Symbol, HubspotSDK::Models::Cms::UpdateLanguagesRequestVNext::language],
            primary_id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> StringIO

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
