module HubSpotSDK
  module Resources
    class Cms
      class Blogs
        class Settings
          attr_reader multi_language: HubSpotSDK::Resources::Cms::Blogs::Settings::MultiLanguage

          def list: (
            ?after: String,
            ?archived: bool,
            ?created_after: Time,
            ?created_at: Time,
            ?created_before: Time,
            ?limit: Integer,
            ?sort: ::Array[String],
            ?updated_after: Time,
            ?updated_at: Time,
            ?updated_before: Time,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Cms::Blogs::Blog]

          def get: (
            String blog_id,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::Blogs::Blog

          def get_revision: (
            String revision_id,
            blog_id: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::Blogs::BlogVersion

          def list_revisions: (
            String blog_id,
            ?after: String,
            ?before: String,
            ?limit: Integer,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Cms::Blogs::VersionBlog]

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
