module HubspotSDK
  module Resources
    class Meta
      class Origins
        class IPRanges
          def list: (
            ?direction: ::Array[HubspotSDK::Models::Meta::Origins::IPRangeListParams::direction],
            ?service: ::Array[HubspotSDK::Models::Meta::Origins::IPRangeListParams::service],
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Meta::CollectionResponseIPRangeNoPaging

          def list_simple: (
            ?direction: ::Array[HubspotSDK::Models::Meta::Origins::IPRangeListSimpleParams::direction],
            ?service: ::Array[HubspotSDK::Models::Meta::Origins::IPRangeListSimpleParams::service],
            ?request_options: HubspotSDK::request_opts
          ) -> String

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
