module HubSpotSDK
  module Resources
    class Meta
      class Origins
        class IPRanges
          def list: (
            ?direction: ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::direction],
            ?service: ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::service],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Meta::CollectionResponseIPRangeNoPaging

          def list_simple: (
            ?direction: ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListSimpleParams::direction],
            ?service: ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListSimpleParams::service],
            ?request_options: HubSpotSDK::request_opts
          ) -> String

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
