module HubspotSDK
  module Models
    module Auth
      type access_token_info_response =
        {
          token: String,
          app_id: Integer,
          expires_in: Integer,
          hub_id: Integer,
          scopes: ::Array[String],
          token_type: String,
          user_id: Integer,
          hub_domain: String,
          is_private_distribution: bool,
          signed_access_token: HubspotSDK::Auth::SignedAccessToken,
          user: String
        }

      class AccessTokenInfoResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor token: String

        attr_accessor app_id: Integer

        attr_accessor expires_in: Integer

        attr_accessor hub_id: Integer

        attr_accessor scopes: ::Array[String]

        attr_accessor token_type: String

        attr_accessor user_id: Integer

        attr_reader hub_domain: String?

        def hub_domain=: (String) -> String

        attr_reader is_private_distribution: bool?

        def is_private_distribution=: (bool) -> bool

        attr_reader signed_access_token: HubspotSDK::Auth::SignedAccessToken?

        def signed_access_token=: (
          HubspotSDK::Auth::SignedAccessToken
        ) -> HubspotSDK::Auth::SignedAccessToken

        attr_reader user: String?

        def user=: (String) -> String

        def initialize: (
          token: String,
          app_id: Integer,
          expires_in: Integer,
          hub_id: Integer,
          scopes: ::Array[String],
          token_type: String,
          user_id: Integer,
          ?hub_domain: String,
          ?is_private_distribution: bool,
          ?signed_access_token: HubspotSDK::Auth::SignedAccessToken,
          ?user: String
        ) -> void

        def to_hash: -> {
          token: String,
          app_id: Integer,
          expires_in: Integer,
          hub_id: Integer,
          scopes: ::Array[String],
          token_type: String,
          user_id: Integer,
          hub_domain: String,
          is_private_distribution: bool,
          signed_access_token: HubspotSDK::Auth::SignedAccessToken,
          user: String
        }
      end
    end
  end
end
