module HubspotSDK
  module Models
    module Auth
      type refresh_token_info_response =
        {
          token: String,
          client_id: String,
          hub_id: Integer,
          scopes: ::Array[String],
          token_type: String,
          user_id: Integer,
          hub_domain: String,
          user: String
        }

      class RefreshTokenInfoResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor token: String

        attr_accessor client_id: String

        attr_accessor hub_id: Integer

        attr_accessor scopes: ::Array[String]

        attr_accessor token_type: String

        attr_accessor user_id: Integer

        attr_reader hub_domain: String?

        def hub_domain=: (String) -> String

        attr_reader user: String?

        def user=: (String) -> String

        def initialize: (
          token: String,
          client_id: String,
          hub_id: Integer,
          scopes: ::Array[String],
          token_type: String,
          user_id: Integer,
          ?hub_domain: String,
          ?user: String
        ) -> void

        def to_hash: -> {
          token: String,
          client_id: String,
          hub_id: Integer,
          scopes: ::Array[String],
          token_type: String,
          user_id: Integer,
          hub_domain: String,
          user: String
        }
      end
    end
  end
end
