module HubspotSDK
  module Models
    module Auth
      type token_response_if =
        {
          access_token: String,
          expires_in: Integer,
          hub_id: Integer,
          id_token: String,
          scopes: ::Array[String],
          token_type: String,
          user_id: Integer
        }

      class TokenResponseIf < HubspotSDK::Internal::Type::BaseModel
        attr_reader access_token: String?

        def access_token=: (String) -> String

        attr_reader expires_in: Integer?

        def expires_in=: (Integer) -> Integer

        attr_reader hub_id: Integer?

        def hub_id=: (Integer) -> Integer

        attr_reader id_token: String?

        def id_token=: (String) -> String

        attr_reader scopes: ::Array[String]?

        def scopes=: (::Array[String]) -> ::Array[String]

        attr_reader token_type: String?

        def token_type=: (String) -> String

        attr_reader user_id: Integer?

        def user_id=: (Integer) -> Integer

        def initialize: (
          ?access_token: String,
          ?expires_in: Integer,
          ?hub_id: Integer,
          ?id_token: String,
          ?scopes: ::Array[String],
          ?token_type: String,
          ?user_id: Integer
        ) -> void

        def to_hash: -> {
          access_token: String,
          expires_in: Integer,
          hub_id: Integer,
          id_token: String,
          scopes: ::Array[String],
          token_type: String,
          user_id: Integer
        }
      end
    end
  end
end
