module HubSpotSDK
  module Models
    module Auth
      type token_info_response_base_if =
        HubSpotSDK::Auth::PublicAccessTokenInfoResponse
        | HubSpotSDK::Auth::PublicRefreshTokenInfoResponse

      module TokenInfoResponseBaseIf
        extend HubSpotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubSpotSDK::Models::Auth::token_info_response_base_if]
      end
    end
  end
end
