module HubspotSDK
  module Models
    module Auth
      type token_info_response_base_if =
        HubspotSDK::Auth::PublicAccessTokenInfoResponse
        | HubspotSDK::Auth::PublicRefreshTokenInfoResponse

      module TokenInfoResponseBaseIf
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::Auth::token_info_response_base_if]
      end
    end
  end
end
