module HubSpotSDK
  module Resources
    class Cms
      class MediaBridge
        class Batch
          def create: (
            String object_type,
            app_id: Integer,
            inputs: ::Array[HubSpotSDK::Cms::PropertyCreate],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::BatchResponseProperty

          def delete: (
            String object_type,
            app_id: Integer,
            inputs: ::Array[HubSpotSDK::PropertyName],
            ?request_options: HubSpotSDK::request_opts
          ) -> nil

          def get: (
            String object_type,
            app_id: Integer,
            archived: bool,
            data_sensitivity: HubSpotSDK::Models::BatchReadInputPropertyName::data_sensitivity,
            inputs: ::Array[HubSpotSDK::PropertyName],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Cms::BatchResponseProperty

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
