module HubspotSDK
  module Resources
    class Cms
      class MediaBridge
        class Schemas
          def update: (
            String object_type,
            app_id: Integer,
            ?clear_description: bool,
            ?description: String,
            ?labels: HubspotSDK::ObjectTypeDefinitionLabels,
            ?primary_display_property: String,
            ?required_properties: ::Array[String],
            ?restorable: bool,
            ?searchable_properties: ::Array[String],
            ?secondary_display_properties: ::Array[String],
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Crm::Objects::ObjectsSchemasObjectTypeDefinition

          def list: (
            Integer app_id,
            ?archived: bool,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::CollectionResponseObjectSchemaNoPaging

          def create_association: (
            String object_type,
            app_id: Integer,
            from_object_type_id: String,
            to_object_type_id: String,
            ?name: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Events::AssociationDefinition

          def delete_association: (
            String association_id,
            app_id: Integer,
            object_type: String,
            ?request_options: HubspotSDK::request_opts
          ) -> nil

          def get: (
            String object_type,
            app_id: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Crm::Objects::ObjectSchema

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
