module HubspotSDK
  module Resources
    class BusinessUnits
      class BusinessUnits
        def get_by_user_id: (
          String user_id,
          ?name: ::Array[String],
          ?properties: ::Array[String],
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::BusinessUnits::CollectionResponsePublicBusinessUnitNoPaging

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
