module HubSpotSDK
  module Resources
    class BusinessUnits
      class BusinessUnitEntries
        def get_by_user_id: (
          String user_id,
          ?name: ::Array[String],
          ?properties: ::Array[String],
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::BusinessUnits::CollectionResponsePublicBusinessUnitNoPaging

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
