module HubspotSDK
  module Resources
    class Automation
      class Actions
        class Functions
          def list: (
            String definition_id,
            app_id: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Automation::CollectionResponsePublicActionFunctionIdentifierNoPaging

          def delete: (
            String function_id,
            app_id: Integer,
            definition_id: String,
            function_type: HubspotSDK::Models::Automation::Actions::FunctionDeleteParams::function_type,
            ?request_options: HubspotSDK::request_opts
          ) -> nil

          def create_or_replace: (
            String function_id,
            app_id: Integer,
            definition_id: String,
            function_type: HubspotSDK::Models::Automation::Actions::FunctionCreateOrReplaceParams::function_type,
            body: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Automation::PublicActionFunctionIdentifier

          def create_or_replace_by_function_type: (
            HubspotSDK::Models::Automation::Actions::FunctionCreateOrReplaceByFunctionTypeParams::function_type function_type,
            app_id: Integer,
            definition_id: String,
            body: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Automation::PublicActionFunctionIdentifier

          def delete_by_function_type: (
            HubspotSDK::Models::Automation::Actions::FunctionDeleteByFunctionTypeParams::function_type function_type,
            app_id: Integer,
            definition_id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> nil

          def get: (
            String function_id,
            app_id: Integer,
            definition_id: String,
            function_type: HubspotSDK::Models::Automation::Actions::FunctionGetParams::function_type,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Automation::PublicActionFunction

          def get_by_function_type: (
            HubspotSDK::Models::Automation::Actions::FunctionGetByFunctionTypeParams::function_type function_type,
            app_id: Integer,
            definition_id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Automation::PublicActionFunction

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
