module HubSpotSDK
  module Resources
    class Automation
      class Actions
        class Revisions
          def list: (
            String definition_id,
            app_id: Integer,
            ?after: String,
            ?limit: Integer,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Automation::PublicActionRevision]

          def get: (
            String revision_id,
            app_id: Integer,
            definition_id: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Automation::PublicActionRevision

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
