module HubSpotSDK
  module Models
    module Scheduler
      module Meetings
        type advanced_book_params =
          {  } & HubSpotSDK::Internal::Type::request_parameters

        class AdvancedBookParams < HubSpotSDK::Models::Scheduler::ExternalMeetingBooking
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def initialize: (?request_options: HubSpotSDK::request_opts) -> void

          def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
        end
      end
    end
  end
end
