module HubSpotSDK
  module Models
    module Scheduler
      module Meetings
        type basic_list_params =
          {
            after: String,
            limit: Integer,
            name: String,
            organizer_user_id: String,
            type: HubSpotSDK::Models::Scheduler::Meetings::BasicListParams::type_
          }
          & HubSpotSDK::Internal::Type::request_parameters

        class BasicListParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_reader after: String?

          def after=: (String) -> String

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          attr_reader name: String?

          def name=: (String) -> String

          attr_reader organizer_user_id: String?

          def organizer_user_id=: (String) -> String

          attr_reader type: HubSpotSDK::Models::Scheduler::Meetings::BasicListParams::type_?

          def type=: (
            HubSpotSDK::Models::Scheduler::Meetings::BasicListParams::type_
          ) -> HubSpotSDK::Models::Scheduler::Meetings::BasicListParams::type_

          def initialize: (
            ?after: String,
            ?limit: Integer,
            ?name: String,
            ?organizer_user_id: String,
            ?type: HubSpotSDK::Models::Scheduler::Meetings::BasicListParams::type_,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            after: String,
            limit: Integer,
            name: String,
            organizer_user_id: String,
            type: HubSpotSDK::Models::Scheduler::Meetings::BasicListParams::type_,
            request_options: HubSpotSDK::RequestOptions
          }

          type type_ = :GROUP_CALENDAR | :PERSONAL_LINK | :ROUND_ROBIN_CALENDAR

          module Type
            extend HubSpotSDK::Internal::Type::Enum

            GROUP_CALENDAR: :GROUP_CALENDAR
            PERSONAL_LINK: :PERSONAL_LINK
            ROUND_ROBIN_CALENDAR: :ROUND_ROBIN_CALENDAR

            def self?.values: -> ::Array[HubSpotSDK::Models::Scheduler::Meetings::BasicListParams::type_]
          end
        end
      end
    end
  end
end
