module HubspotSDK
  module Models
    module Scheduler
      module Meetings
        type meetings_link_get_booking_info_by_slug_params =
          { timezone: String } & HubspotSDK::Internal::Type::request_parameters

        class MeetingsLinkGetBookingInfoBySlugParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_accessor timezone: String

          def initialize: (
            timezone: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            timezone: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
