module HubspotSDK
  module Resources
    class DataStudio
      class Datasource
        def create: (
          body_parts: ::Array[HubspotSDK::DataStudio::BodyPart],
          content_disposition: HubspotSDK::DataStudio::ContentDisposition,
          entity: top,
          fields: ::Hash[Symbol, ::Array[HubspotSDK::DataStudio::FormDataBodyPart]],
          headers: ::Hash[Symbol, ::Array[String]],
          media_type: HubspotSDK::DataStudio::MediaType,
          message_body_workers: top,
          parameterized_headers: ::Hash[Symbol, ::Array[HubspotSDK::DataStudio::ParameterizedHeader]],
          providers: top,
          ?parent: HubspotSDK::DataStudio::MultiPart,
          ?request_options: HubspotSDK::request_opts
        ) -> StringIO

        def update: (
          Integer datasource_id,
          body_parts: ::Array[HubspotSDK::DataStudio::BodyPart],
          content_disposition: HubspotSDK::DataStudio::ContentDisposition,
          entity: top,
          fields: ::Hash[Symbol, ::Array[HubspotSDK::DataStudio::FormDataBodyPart]],
          headers: ::Hash[Symbol, ::Array[String]],
          media_type: HubspotSDK::DataStudio::MediaType,
          message_body_workers: top,
          parameterized_headers: ::Hash[Symbol, ::Array[HubspotSDK::DataStudio::ParameterizedHeader]],
          providers: top,
          ?parent: HubspotSDK::DataStudio::MultiPart,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::DataStudio::DataSourceUpdateResponse

        def delete: (
          Integer datasource_id,
          ?request_options: HubspotSDK::request_opts
        ) -> StringIO

        def get: (
          Integer datasource_id,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::DataStudio::DataSourceGetResponse

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
