module HubspotSDK
  module Models
    module Marketing
      module Emails
        type statistic_get_histogram_params =
          {
            email_ids: ::Array[Integer],
            end_timestamp: String,
            interval: HubspotSDK::Models::Marketing::Emails::StatisticGetHistogramParams::interval,
            start_timestamp: String
          }
          & HubspotSDK::Internal::Type::request_parameters

        class StatisticGetHistogramParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_reader email_ids: ::Array[Integer]?

          def email_ids=: (::Array[Integer]) -> ::Array[Integer]

          attr_reader end_timestamp: String?

          def end_timestamp=: (String) -> String

          attr_reader interval: HubspotSDK::Models::Marketing::Emails::StatisticGetHistogramParams::interval?

          def interval=: (
            HubspotSDK::Models::Marketing::Emails::StatisticGetHistogramParams::interval
          ) -> HubspotSDK::Models::Marketing::Emails::StatisticGetHistogramParams::interval

          attr_reader start_timestamp: String?

          def start_timestamp=: (String) -> String

          def initialize: (
            ?email_ids: ::Array[Integer],
            ?end_timestamp: String,
            ?interval: HubspotSDK::Models::Marketing::Emails::StatisticGetHistogramParams::interval,
            ?start_timestamp: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            email_ids: ::Array[Integer],
            end_timestamp: String,
            interval: HubspotSDK::Models::Marketing::Emails::StatisticGetHistogramParams::interval,
            start_timestamp: String,
            request_options: HubspotSDK::RequestOptions
          }

          type interval =
            :DAY
            | :HOUR
            | :MINUTE
            | :MONTH
            | :QUARTER
            | :QUARTER_HOUR
            | :SECOND
            | :WEEK
            | :YEAR

          module Interval
            extend HubspotSDK::Internal::Type::Enum

            DAY: :DAY
            HOUR: :HOUR
            MINUTE: :MINUTE
            MONTH: :MONTH
            QUARTER: :QUARTER
            QUARTER_HOUR: :QUARTER_HOUR
            SECOND: :SECOND
            WEEK: :WEEK
            YEAR: :YEAR

            def self?.values: -> ::Array[HubspotSDK::Models::Marketing::Emails::StatisticGetHistogramParams::interval]
          end
        end
      end
    end
  end
end
