module HubSpotSDK
  module Resources
    class Marketing
      class Campaigns
        class Batch
          def create: (
            inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignInput],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Marketing::BatchResponsePublicCampaign

          def update: (
            inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignBatchUpdateItem],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Marketing::BatchResponsePublicCampaign

          def delete: (
            inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignDeleteInput],
            ?request_options: HubSpotSDK::request_opts
          ) -> nil

          def get: (
            inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignReadInput],
            ?end_date: String,
            ?properties: ::Array[String],
            ?start_date: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Marketing::BatchResponsePublicCampaignWithAssets

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
