module HubSpotSDK
  module Resources
    class Marketing
      class Campaigns
        class Budget
          def create: (
            String campaign_guid,
            amount: Float,
            name: String,
            order: Integer,
            ?description: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Marketing::PublicBudgetItem

          def update: (
            Integer budget_id,
            campaign_guid: String,
            amount: Float,
            name: String,
            order: Integer,
            ?description: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Marketing::PublicBudgetItem

          def delete: (
            Integer budget_id,
            campaign_guid: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> nil

          def get: (
            Integer budget_id,
            campaign_guid: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Marketing::PublicBudgetItem

          def get_totals: (
            String campaign_guid,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Marketing::PublicBudgetTotals

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
