module HubSpotSDK
  module Resources
    class Marketing
      class Campaigns
        class Metrics
          def get_attribution_metrics: (
            String campaign_guid,
            ?end_date: String,
            ?start_date: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Marketing::MetricsCounters

          def get_revenue_attribution: (
            String campaign_guid,
            ?attribution_model: String,
            ?end_date: String,
            ?start_date: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Marketing::RevenueAttributionAggregate

          def list_contact_ids_by_type: (
            String contact_type,
            campaign_guid: String,
            ?after: String,
            ?end_date: String,
            ?limit: Integer,
            ?start_date: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Marketing::ContactReference]

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
