module HubspotSDK
  module Resources
    class Scheduler
      class Meetings
        attr_reader advanced: HubspotSDK::Resources::Scheduler::Meetings::Advanced

        attr_reader basic: HubspotSDK::Resources::Scheduler::Meetings::Basic

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
