module HubSpotSDK
  module Resources
    class Scheduler
      class Meetings
        attr_reader advanced: HubSpotSDK::Resources::Scheduler::Meetings::Advanced

        attr_reader basic: HubSpotSDK::Resources::Scheduler::Meetings::Basic

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
