module HubspotSDK
  module Resources
    class Scheduler
      class Meetings
        attr_reader calendar: HubspotSDK::Resources::Scheduler::Meetings::Calendar

        attr_reader meetings_links: HubspotSDK::Resources::Scheduler::Meetings::MeetingsLinks

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
