module HubspotSDK
  module Resources
    class CRM
      class Associations
        class Schema
          class V4
            class Configurations
              def list: (
                ?request_options: HubspotSDK::request_opts
              ) -> HubspotSDK::CRM::Associations::Schema::CollectionResponsePublicAssociationDefinitionUserConfigurationNoPaging

              def batch_create_by_object_types: (
                String to_object_type,
                from_object_type: String,
                inputs: ::Array[HubspotSDK::CRM::Associations::Schema::PublicAssociationDefinitionConfigurationCreateRequest],
                ?request_options: HubspotSDK::request_opts
              ) -> HubspotSDK::CRM::Associations::Schema::BatchResponsePublicAssociationDefinitionUserConfiguration

              def batch_delete_by_object_types: (
                String to_object_type,
                from_object_type: String,
                inputs: ::Array[HubspotSDK::CRM::Associations::Schema::PublicAssociationSpec],
                ?request_options: HubspotSDK::request_opts
              ) -> nil

              def batch_update_by_object_types: (
                String to_object_type,
                from_object_type: String,
                inputs: ::Array[HubspotSDK::CRM::Associations::Schema::PublicAssociationDefinitionConfigurationUpdateRequest],
                ?request_options: HubspotSDK::request_opts
              ) -> HubspotSDK::CRM::Associations::Schema::BatchResponsePublicAssociationDefinitionConfigurationUpdateResult

              def get_by_object_types: (
                String to_object_type,
                from_object_type: String,
                ?request_options: HubspotSDK::request_opts
              ) -> HubspotSDK::CRM::Associations::Schema::CollectionResponsePublicAssociationDefinitionUserConfigurationNoPaging

              def initialize: (client: HubspotSDK::Client) -> void
            end
          end
        end
      end
    end
  end
end
