module HubspotSDK
  module Resources
    class CRM
      class Associations
        class Schema
          class V4
            def initialize: (client: HubspotSDK::Client) -> void
          end
        end
      end
    end
  end
end
