module HubspotSDK
  module Models
    module Marketing
      module Subscriptions
        type public_bulk_opt_out_from_all_response =
          {
            subscriber_id_string: String,
            statuses: ::Array[HubspotSDK::Marketing::Subscriptions::PublicStatus]
          }

        class PublicBulkOptOutFromAllResponse < HubspotSDK::Internal::Type::BaseModel
          attr_accessor subscriber_id_string: String

          attr_reader statuses: ::Array[HubspotSDK::Marketing::Subscriptions::PublicStatus]?

          def statuses=: (
            ::Array[HubspotSDK::Marketing::Subscriptions::PublicStatus]
          ) -> ::Array[HubspotSDK::Marketing::Subscriptions::PublicStatus]

          def initialize: (
            subscriber_id_string: String,
            ?statuses: ::Array[HubspotSDK::Marketing::Subscriptions::PublicStatus]
          ) -> void

          def to_hash: -> {
            subscriber_id_string: String,
            statuses: ::Array[HubspotSDK::Marketing::Subscriptions::PublicStatus]
          }
        end
      end
    end
  end
end
