module HubspotSDK
  module Models
    module Marketing
      module Subscriptions
        type public_wide_status =
          {
            channel: HubspotSDK::Models::Marketing::Subscriptions::PublicWideStatus::channel,
            status: HubspotSDK::Models::Marketing::Subscriptions::PublicWideStatus::status,
            subscriber_id_string: String,
            timestamp: Time,
            wide_status_type: HubspotSDK::Models::Marketing::Subscriptions::PublicWideStatus::wide_status_type,
            business_unit_id: Integer
          }

        class PublicWideStatus < HubspotSDK::Internal::Type::BaseModel
          attr_accessor channel: HubspotSDK::Models::Marketing::Subscriptions::PublicWideStatus::channel

          attr_accessor status: HubspotSDK::Models::Marketing::Subscriptions::PublicWideStatus::status

          attr_accessor subscriber_id_string: String

          attr_accessor timestamp: Time

          attr_accessor wide_status_type: HubspotSDK::Models::Marketing::Subscriptions::PublicWideStatus::wide_status_type

          attr_reader business_unit_id: Integer?

          def business_unit_id=: (Integer) -> Integer

          def initialize: (
            channel: HubspotSDK::Models::Marketing::Subscriptions::PublicWideStatus::channel,
            status: HubspotSDK::Models::Marketing::Subscriptions::PublicWideStatus::status,
            subscriber_id_string: String,
            timestamp: Time,
            wide_status_type: HubspotSDK::Models::Marketing::Subscriptions::PublicWideStatus::wide_status_type,
            ?business_unit_id: Integer
          ) -> void

          def to_hash: -> {
            channel: HubspotSDK::Models::Marketing::Subscriptions::PublicWideStatus::channel,
            status: HubspotSDK::Models::Marketing::Subscriptions::PublicWideStatus::status,
            subscriber_id_string: String,
            timestamp: Time,
            wide_status_type: HubspotSDK::Models::Marketing::Subscriptions::PublicWideStatus::wide_status_type,
            business_unit_id: Integer
          }

          type channel = :EMAIL

          module Channel
            extend HubspotSDK::Internal::Type::Enum

            EMAIL: :EMAIL

            def self?.values: -> ::Array[HubspotSDK::Models::Marketing::Subscriptions::PublicWideStatus::channel]
          end

          type status = :SUBSCRIBED | :UNSUBSCRIBED | :NOT_SPECIFIED

          module Status
            extend HubspotSDK::Internal::Type::Enum

            SUBSCRIBED: :SUBSCRIBED
            UNSUBSCRIBED: :UNSUBSCRIBED
            NOT_SPECIFIED: :NOT_SPECIFIED

            def self?.values: -> ::Array[HubspotSDK::Models::Marketing::Subscriptions::PublicWideStatus::status]
          end

          type wide_status_type = :PORTAL_WIDE | :BUSINESS_UNIT_WIDE

          module WideStatusType
            extend HubspotSDK::Internal::Type::Enum

            PORTAL_WIDE: :PORTAL_WIDE
            BUSINESS_UNIT_WIDE: :BUSINESS_UNIT_WIDE

            def self?.values: -> ::Array[HubspotSDK::Models::Marketing::Subscriptions::PublicWideStatus::wide_status_type]
          end
        end
      end
    end
  end
end
