module HubspotSDK
  module Models
    module Marketing
      module Subscriptions
        type public_wide_status_bulk_response =
          {
            subscriber_id_string: String,
            wide_statuses: ::Array[HubspotSDK::Marketing::Subscriptions::PublicWideStatus]
          }

        class PublicWideStatusBulkResponse < HubspotSDK::Internal::Type::BaseModel
          attr_accessor subscriber_id_string: String

          attr_accessor wide_statuses: ::Array[HubspotSDK::Marketing::Subscriptions::PublicWideStatus]

          def initialize: (
            subscriber_id_string: String,
            wide_statuses: ::Array[HubspotSDK::Marketing::Subscriptions::PublicWideStatus]
          ) -> void

          def to_hash: -> {
            subscriber_id_string: String,
            wide_statuses: ::Array[HubspotSDK::Marketing::Subscriptions::PublicWideStatus]
          }
        end
      end
    end
  end
end
