module HubspotSDK
  module Models
    module Marketing
      module Subscriptions
        type public_status =
          {
            channel: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::channel,
            source: String,
            status: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::status,
            subscriber_id_string: String,
            subscription_id: Integer,
            timestamp: Time,
            business_unit_id: Integer,
            legal_basis: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::legal_basis,
            legal_basis_explanation: String,
            set_status_success_reason: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::set_status_success_reason,
            subscription_name: String
          }

        class PublicStatus < HubspotSDK::Internal::Type::BaseModel
          attr_accessor channel: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::channel

          attr_accessor source: String

          attr_accessor status: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::status

          attr_accessor subscriber_id_string: String

          attr_accessor subscription_id: Integer

          attr_accessor timestamp: Time

          attr_reader business_unit_id: Integer?

          def business_unit_id=: (Integer) -> Integer

          attr_reader legal_basis: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::legal_basis?

          def legal_basis=: (
            HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::legal_basis
          ) -> HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::legal_basis

          attr_reader legal_basis_explanation: String?

          def legal_basis_explanation=: (String) -> String

          attr_reader set_status_success_reason: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::set_status_success_reason?

          def set_status_success_reason=: (
            HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::set_status_success_reason
          ) -> HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::set_status_success_reason

          attr_reader subscription_name: String?

          def subscription_name=: (String) -> String

          def initialize: (
            channel: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::channel,
            source: String,
            status: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::status,
            subscriber_id_string: String,
            subscription_id: Integer,
            timestamp: Time,
            ?business_unit_id: Integer,
            ?legal_basis: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::legal_basis,
            ?legal_basis_explanation: String,
            ?set_status_success_reason: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::set_status_success_reason,
            ?subscription_name: String
          ) -> void

          def to_hash: -> {
            channel: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::channel,
            source: String,
            status: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::status,
            subscriber_id_string: String,
            subscription_id: Integer,
            timestamp: Time,
            business_unit_id: Integer,
            legal_basis: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::legal_basis,
            legal_basis_explanation: String,
            set_status_success_reason: HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::set_status_success_reason,
            subscription_name: String
          }

          type channel = :EMAIL

          module Channel
            extend HubspotSDK::Internal::Type::Enum

            EMAIL: :EMAIL

            def self?.values: -> ::Array[HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::channel]
          end

          type status = :NOT_SPECIFIED | :SUBSCRIBED | :UNSUBSCRIBED

          module Status
            extend HubspotSDK::Internal::Type::Enum

            NOT_SPECIFIED: :NOT_SPECIFIED
            SUBSCRIBED: :SUBSCRIBED
            UNSUBSCRIBED: :UNSUBSCRIBED

            def self?.values: -> ::Array[HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::status]
          end

          type legal_basis =
            :CONSENT_WITH_NOTICE
            | :LEGITIMATE_INTEREST_CLIENT
            | :LEGITIMATE_INTEREST_OTHER
            | :LEGITIMATE_INTEREST_PQL
            | :NON_GDPR
            | :PERFORMANCE_OF_CONTRACT
            | :PROCESS_AND_STORE

          module LegalBasis
            extend HubspotSDK::Internal::Type::Enum

            CONSENT_WITH_NOTICE: :CONSENT_WITH_NOTICE
            LEGITIMATE_INTEREST_CLIENT: :LEGITIMATE_INTEREST_CLIENT
            LEGITIMATE_INTEREST_OTHER: :LEGITIMATE_INTEREST_OTHER
            LEGITIMATE_INTEREST_PQL: :LEGITIMATE_INTEREST_PQL
            NON_GDPR: :NON_GDPR
            PERFORMANCE_OF_CONTRACT: :PERFORMANCE_OF_CONTRACT
            PROCESS_AND_STORE: :PROCESS_AND_STORE

            def self?.values: -> ::Array[HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::legal_basis]
          end

          type set_status_success_reason =
            :NO_STATUS_CHANGE
            | :REQUESTED_CHANGE_OCCURRED
            | :RESUBSCRIBE_OCCURRED
            | :UNSUBSCRIBE_FROM_ALL_OCCURRED

          module SetStatusSuccessReason
            extend HubspotSDK::Internal::Type::Enum

            NO_STATUS_CHANGE: :NO_STATUS_CHANGE
            REQUESTED_CHANGE_OCCURRED: :REQUESTED_CHANGE_OCCURRED
            RESUBSCRIBE_OCCURRED: :RESUBSCRIBE_OCCURRED
            UNSUBSCRIBE_FROM_ALL_OCCURRED: :UNSUBSCRIBE_FROM_ALL_OCCURRED

            def self?.values: -> ::Array[HubspotSDK::Models::Marketing::Subscriptions::PublicStatus::set_status_success_reason]
          end
        end
      end
    end
  end
end
