module HubspotSDK
  module Resources
    class CRM
      class ObjectLibrary
        class Enablement
          def list: (
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Models::CRM::ObjectLibrary::EnablementListResponse

          def get: (
            String object_type_id,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Models::CRM::ObjectLibrary::EnablementGetResponse

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
