module HubSpotSDK
  module Resources
    class Events
      class Definitions
        def create: (
          include_default_properties: bool,
          label: String,
          property_definitions: ::Array[HubSpotSDK::Events::ExternalBehavioralEventPropertyCreate],
          ?custom_matching_id: HubSpotSDK::Events::ExternalObjectResolutionMappingRequest,
          ?description: String,
          ?name: String,
          ?primary_object: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Events::ExternalBehavioralEventTypeDefinition

        def update: (
          String event_name,
          ?description: String,
          ?label: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Events::ExternalBehavioralEventTypeDefinition

        def list: (
          ?after: String,
          ?include_properties: bool,
          ?limit: Integer,
          ?search_string: String,
          ?sort_order: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Events::ExternalBehavioralEventTypeDefinition]

        def delete: (
          String event_name,
          ?request_options: HubSpotSDK::request_opts
        ) -> nil

        def create_property: (
          String event_name,
          label: String,
          type: String,
          ?description: String,
          ?name: String,
          ?options: ::Array[HubSpotSDK::OptionInput],
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::BaseProperty

        def delete_property: (
          String property_name,
          event_name: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> nil

        def get: (
          String event_name,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Events::ExternalBehavioralEventTypeDefinition

        def send_batch: (
          inputs: ::Array[HubSpotSDK::Events::BehavioralEventHTTPCompletionRequest],
          ?request_options: HubSpotSDK::request_opts
        ) -> nil

        def update_property: (
          String property_name,
          event_name: String,
          ?description: String,
          ?label: String,
          ?options: ::Array[HubSpotSDK::OptionInput],
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::BaseProperty

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
