module HubSpotSDK
  module Resources
    class Events
      class Occurrences
        def list: (
          ?id: ::Array[String],
          ?after: String,
          ?before: String,
          ?event_type: String,
          ?limit: Integer,
          ?object_id_: Integer,
          ?object_property: HubSpotSDK::Events::OccurrenceListParams::ObjectProperty,
          ?object_type: String,
          ?occurred_after: Time,
          ?occurred_before: Time,
          ?properties: ::Array[String],
          ?property: HubSpotSDK::Events::OccurrenceListParams::Property,
          ?sort: ::Array[String],
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Events::ExternalUnifiedEvent]

        def list_event_types: (
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Events::VisibleExternalEventTypeNames

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
