module HubspotSDK
  module Resources
    class Events
      class Occurrences
        def list: (
          ?id: ::Array[String],
          ?after: String,
          ?before: String,
          ?event_type: String,
          ?limit: Integer,
          ?object_id_: Integer,
          ?object_property: HubspotSDK::Events::OccurrenceListParams::ObjectProperty,
          ?object_type: String,
          ?occurred_after: Time,
          ?occurred_before: Time,
          ?properties: ::Array[String],
          ?property: HubspotSDK::Events::OccurrenceListParams::Property,
          ?sort: ::Array[String],
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Internal::Page[HubspotSDK::Events::ExternalUnifiedEvent]

        def list_event_types: (
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Events::VisibleExternalEventTypeNames

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
