module HubspotSDK
  module Resources
    class Events
      class Send
        def batch_send: (
          inputs: ::Array[HubspotSDK::Events::BehavioralEventHTTPCompletionRequest],
          ?request_options: HubspotSDK::request_opts
        ) -> nil

        def send_: (
          event_name: String,
          properties: ::Hash[Symbol, String],
          ?email: String,
          ?object_id_: String,
          ?occurred_at: Time,
          ?utk: String,
          ?uuid: String,
          ?request_options: HubspotSDK::request_opts
        ) -> nil

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
