module HubSpotSDK
  module Models
    module Cms
      module Hubdb
        type row_delete_draft_params =
          { table_id_or_name: String, row_id: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class RowDeleteDraftParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor table_id_or_name: String

          attr_accessor row_id: String

          def initialize: (
            table_id_or_name: String,
            row_id: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            table_id_or_name: String,
            row_id: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
