module HubspotSDK
  module Models
    module Cms
      module Hubdb
        type row_list_params =
          {
            table_id_or_name: String,
            after: String,
            archived: bool,
            limit: Integer,
            offset: Integer,
            properties: ::Array[String],
            sort: ::Array[String]
          }
          & HubspotSDK::Internal::Type::request_parameters

        class RowListParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_accessor table_id_or_name: String

          attr_reader after: String?

          def after=: (String) -> String

          attr_reader archived: bool?

          def archived=: (bool) -> bool

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          attr_reader offset: Integer?

          def offset=: (Integer) -> Integer

          attr_reader properties: ::Array[String]?

          def properties=: (::Array[String]) -> ::Array[String]

          attr_reader sort: ::Array[String]?

          def sort=: (::Array[String]) -> ::Array[String]

          def initialize: (
            table_id_or_name: String,
            ?after: String,
            ?archived: bool,
            ?limit: Integer,
            ?offset: Integer,
            ?properties: ::Array[String],
            ?sort: ::Array[String],
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            table_id_or_name: String,
            after: String,
            archived: bool,
            limit: Integer,
            offset: Integer,
            properties: ::Array[String],
            sort: ::Array[String],
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
