module HubSpotSDK
  module Models
    module Cms
      module Hubdb
        type row_update_batch_params =
          { table_id_or_name: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class RowUpdateBatchParams < HubSpotSDK::Models::Cms::BatchInputHubDBTableRowV3BatchUpdateRequest
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def table_id_or_name: -> String

          def table_id_or_name=: (String _) -> String

          def initialize: (
            table_id_or_name: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            table_id_or_name: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
