module HubspotSDK
  module Models
    module Cms
      module Hubdb
        type table_get_params =
          {
            archived: bool,
            include_foreign_ids: bool,
            is_get_localized_schema: bool
          }
          & HubspotSDK::Internal::Type::request_parameters

        class TableGetParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_reader archived: bool?

          def archived=: (bool) -> bool

          attr_reader include_foreign_ids: bool?

          def include_foreign_ids=: (bool) -> bool

          attr_reader is_get_localized_schema: bool?

          def is_get_localized_schema=: (bool) -> bool

          def initialize: (
            ?archived: bool,
            ?include_foreign_ids: bool,
            ?is_get_localized_schema: bool,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            archived: bool,
            include_foreign_ids: bool,
            is_get_localized_schema: bool,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
