module HubSpotSDK
  module Models
    module Cms
      module Hubdb
        type table_update_draft_params =
          {
            table_id_or_name: String,
            archived: bool,
            include_foreign_ids: bool,
            is_get_localized_schema: bool
          }
          & HubSpotSDK::Internal::Type::request_parameters

        class TableUpdateDraftParams < HubSpotSDK::Models::Cms::HubDBTableV3Request
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def table_id_or_name: -> String

          def table_id_or_name=: (String _) -> String

          def archived: -> bool?

          def archived=: (bool _) -> bool

          def include_foreign_ids: -> bool?

          def include_foreign_ids=: (bool _) -> bool

          def is_get_localized_schema: -> bool?

          def is_get_localized_schema=: (bool _) -> bool

          def initialize: (
            table_id_or_name: String,
            ?archived: bool,
            ?include_foreign_ids: bool,
            ?is_get_localized_schema: bool,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            table_id_or_name: String,
            archived: bool,
            include_foreign_ids: bool,
            is_get_localized_schema: bool,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
