module HubspotSDK
  module Models
    module Cms
      module Hubdb
        type table_update_draft_params =
          {
            archived: bool,
            include_foreign_ids: bool,
            is_get_localized_schema: bool
          }
          & HubspotSDK::Internal::Type::request_parameters

        class TableUpdateDraftParams < HubspotSDK::Models::Cms::HubDBTableV3Request
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          def archived: -> bool?

          def archived=: (bool _) -> bool

          def include_foreign_ids: -> bool?

          def include_foreign_ids=: (bool _) -> bool

          def is_get_localized_schema: -> bool?

          def is_get_localized_schema=: (bool _) -> bool

          def initialize: (
            ?archived: bool,
            ?include_foreign_ids: bool,
            ?is_get_localized_schema: bool,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            archived: bool,
            include_foreign_ids: bool,
            is_get_localized_schema: bool,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
