module HubspotSDK
  module Models
    module Cms
      module Hubdb
        type table_unpublish_params =
          { include_foreign_ids: bool }
          & HubspotSDK::Internal::Type::request_parameters

        class TableUnpublishParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_reader include_foreign_ids: bool?

          def include_foreign_ids=: (bool) -> bool

          def initialize: (
            ?include_foreign_ids: bool,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            include_foreign_ids: bool,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
