module HubSpotSDK
  module Models
    module Cms
      module Hubdb
        type table_import_draft_params =
          {
            table_id_or_name: String,
            config: String,
            file: HubSpotSDK::Internal::file_input
          }
          & HubSpotSDK::Internal::Type::request_parameters

        class TableImportDraftParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor table_id_or_name: String

          attr_reader config: String?

          def config=: (String) -> String

          attr_reader file: HubSpotSDK::Internal::file_input?

          def file=: (
            HubSpotSDK::Internal::file_input
          ) -> HubSpotSDK::Internal::file_input

          def initialize: (
            table_id_or_name: String,
            ?config: String,
            ?file: HubSpotSDK::Internal::file_input,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            table_id_or_name: String,
            config: String,
            file: HubSpotSDK::Internal::file_input,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
