module HubSpotSDK
  module Models
    module Cms
      module Hubdb
        type table_list_params =
          {
            after: String,
            archived: bool,
            content_type: String,
            created_after: Time,
            created_at: Time,
            created_before: Time,
            is_get_localized_schema: bool,
            limit: Integer,
            sort: ::Array[String],
            updated_after: Time,
            updated_at: Time,
            updated_before: Time
          }
          & HubSpotSDK::Internal::Type::request_parameters

        class TableListParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_reader after: String?

          def after=: (String) -> String

          attr_reader archived: bool?

          def archived=: (bool) -> bool

          attr_reader content_type: String?

          def content_type=: (String) -> String

          attr_reader created_after: Time?

          def created_after=: (Time) -> Time

          attr_reader created_at: Time?

          def created_at=: (Time) -> Time

          attr_reader created_before: Time?

          def created_before=: (Time) -> Time

          attr_reader is_get_localized_schema: bool?

          def is_get_localized_schema=: (bool) -> bool

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          attr_reader sort: ::Array[String]?

          def sort=: (::Array[String]) -> ::Array[String]

          attr_reader updated_after: Time?

          def updated_after=: (Time) -> Time

          attr_reader updated_at: Time?

          def updated_at=: (Time) -> Time

          attr_reader updated_before: Time?

          def updated_before=: (Time) -> Time

          def initialize: (
            ?after: String,
            ?archived: bool,
            ?content_type: String,
            ?created_after: Time,
            ?created_at: Time,
            ?created_before: Time,
            ?is_get_localized_schema: bool,
            ?limit: Integer,
            ?sort: ::Array[String],
            ?updated_after: Time,
            ?updated_at: Time,
            ?updated_before: Time,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            after: String,
            archived: bool,
            content_type: String,
            created_after: Time,
            created_at: Time,
            created_before: Time,
            is_get_localized_schema: bool,
            limit: Integer,
            sort: ::Array[String],
            updated_after: Time,
            updated_at: Time,
            updated_before: Time,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
