module HubSpotSDK
  module Models
    module Cms
      module Hubdb
        type table_delete_version_params =
          { table_id_or_name: String, version_id: Integer }
          & HubSpotSDK::Internal::Type::request_parameters

        class TableDeleteVersionParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor table_id_or_name: String

          attr_accessor version_id: Integer

          def initialize: (
            table_id_or_name: String,
            version_id: Integer,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            table_id_or_name: String,
            version_id: Integer,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
