module HubSpotSDK
  module Models
    module Cms
      module Hubdb
        type table_create_params =
          {  } & HubSpotSDK::Internal::Type::request_parameters

        class TableCreateParams < HubSpotSDK::Models::Cms::HubDBTableV3Request
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def initialize: (?request_options: HubSpotSDK::request_opts) -> void

          def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
        end
      end
    end
  end
end
