module HubspotSDK
  module Models
    module Cms
      module Hubdb
        type table_export_params =
          { format_: String } & HubspotSDK::Internal::Type::request_parameters

        class TableExportParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_reader format_: String?

          def format_=: (String) -> String

          def initialize: (
            ?format_: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            format_: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
