module HubspotSDK
  module Resources
    class CRM
      class Objects
        class FeedbackSubmissions
          class Batch
            def get: (
              inputs: ::Array[HubspotSDK::CRM::SimplePublicObjectID],
              properties: ::Array[String],
              properties_with_history: ::Array[String],
              ?archived: bool,
              ?id_property: String,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::CRM::BatchResponseSimplePublicObject

            def initialize: (client: HubspotSDK::Client) -> void
          end
        end
      end
    end
  end
end
