module HubspotSDK
  module Resources
    class Settings
      class Currencies
        class ExchangeRates
          class Batch
            def create: (
              inputs: ::Array[HubspotSDK::Settings::ExchangeRateCreateRequest],
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Settings::BatchResponseExchangeRate

            def update: (
              inputs: ::Array[HubspotSDK::Settings::ExchangeRateUpdateRequest],
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Settings::BatchResponseExchangeRate

            def get: (
              inputs: ::Array[HubspotSDK::PublicObjectID],
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Settings::BatchResponseExchangeRate

            def initialize: (client: HubspotSDK::Client) -> void
          end
        end
      end
    end
  end
end
