module HubSpotSDK
  module Models
    module Crm
      module Extensions
        type calling_create_channel_connection_settings_params =
          { app_id: Integer } & HubSpotSDK::Internal::Type::request_parameters

        class CallingCreateChannelConnectionSettingsParams < HubSpotSDK::Models::Crm::Extensions::ChannelConnectionSettingsRequest
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def app_id: -> Integer

          def app_id=: (Integer _) -> Integer

          def initialize: (
            app_id: Integer,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            app_id: Integer,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
