module HubSpotSDK
  module Models
    module Crm
      module Extensions
        type card_create_request =
          {
            actions: HubSpotSDK::Crm::Extensions::CardActions,
            display_: HubSpotSDK::Crm::Extensions::CardDisplayBody,
            fetch: HubSpotSDK::Crm::Extensions::CardFetchBody,
            title: String
          }

        class CardCreateRequest < HubSpotSDK::Internal::Type::BaseModel
          attr_accessor actions: HubSpotSDK::Crm::Extensions::CardActions

          attr_accessor display_: HubSpotSDK::Crm::Extensions::CardDisplayBody

          attr_accessor fetch: HubSpotSDK::Crm::Extensions::CardFetchBody

          attr_accessor title: String

          def initialize: (
            actions: HubSpotSDK::Crm::Extensions::CardActions,
            display_: HubSpotSDK::Crm::Extensions::CardDisplayBody,
            fetch: HubSpotSDK::Crm::Extensions::CardFetchBody,
            title: String
          ) -> void

          def to_hash: -> {
            actions: HubSpotSDK::Crm::Extensions::CardActions,
            display_: HubSpotSDK::Crm::Extensions::CardDisplayBody,
            fetch: HubSpotSDK::Crm::Extensions::CardFetchBody,
            title: String
          }
        end
      end
    end
  end
end
