module HubspotSDK
  module Models
    module Crm
      module Extensions
        type card_actions = { base_urls: ::Array[String] }

        class CardActions < HubspotSDK::Internal::Type::BaseModel
          attr_accessor base_urls: ::Array[String]

          def initialize: (base_urls: ::Array[String]) -> void

          def to_hash: -> { base_urls: ::Array[String] }
        end
      end
    end
  end
end
