module HubspotSDK
  module Models
    module CRM
      module Extensions
        type card_object_type_body =
          {
            name: HubspotSDK::Models::CRM::Extensions::CardObjectTypeBody::name_,
            properties_to_send: ::Array[String]
          }

        class CardObjectTypeBody < HubspotSDK::Internal::Type::BaseModel
          attr_accessor name: HubspotSDK::Models::CRM::Extensions::CardObjectTypeBody::name_

          attr_accessor properties_to_send: ::Array[String]

          def initialize: (
            name: HubspotSDK::Models::CRM::Extensions::CardObjectTypeBody::name_,
            properties_to_send: ::Array[String]
          ) -> void

          def to_hash: -> {
            name: HubspotSDK::Models::CRM::Extensions::CardObjectTypeBody::name_,
            properties_to_send: ::Array[String]
          }

          type name_ =
            :contacts | :deals | :companies | :tickets | :marketing_events

          module Name
            extend HubspotSDK::Internal::Type::Enum

            CONTACTS: :contacts
            DEALS: :deals
            COMPANIES: :companies
            TICKETS: :tickets
            MARKETING_EVENTS: :marketing_events

            def self?.values: -> ::Array[HubspotSDK::Models::CRM::Extensions::CardObjectTypeBody::name_]
          end
        end
      end
    end
  end
end
