module HubSpotSDK
  module Models
    module Crm
      module Extensions
        type card_display_body =
          {
            properties: ::Array[HubSpotSDK::Crm::Extensions::CardDisplayProperty]
          }

        class CardDisplayBody < HubSpotSDK::Internal::Type::BaseModel
          attr_accessor properties: ::Array[HubSpotSDK::Crm::Extensions::CardDisplayProperty]

          def initialize: (
            properties: ::Array[HubSpotSDK::Crm::Extensions::CardDisplayProperty]
          ) -> void

          def to_hash: -> {
            properties: ::Array[HubSpotSDK::Crm::Extensions::CardDisplayProperty]
          }
        end
      end
    end
  end
end
