module HubSpotSDK
  module Models
    module Crm
      module Extensions
        type card_patch_request =
          {
            actions: HubSpotSDK::Crm::Extensions::CardActions,
            display_: HubSpotSDK::Crm::Extensions::CardDisplayBody,
            fetch: HubSpotSDK::Crm::Extensions::CardFetchBodyPatch,
            title: String
          }

        class CardPatchRequest < HubSpotSDK::Internal::Type::BaseModel
          attr_reader actions: HubSpotSDK::Crm::Extensions::CardActions?

          def actions=: (
            HubSpotSDK::Crm::Extensions::CardActions
          ) -> HubSpotSDK::Crm::Extensions::CardActions

          attr_reader display_: HubSpotSDK::Crm::Extensions::CardDisplayBody?

          def display_=: (
            HubSpotSDK::Crm::Extensions::CardDisplayBody
          ) -> HubSpotSDK::Crm::Extensions::CardDisplayBody

          attr_reader fetch: HubSpotSDK::Crm::Extensions::CardFetchBodyPatch?

          def fetch=: (
            HubSpotSDK::Crm::Extensions::CardFetchBodyPatch
          ) -> HubSpotSDK::Crm::Extensions::CardFetchBodyPatch

          attr_reader title: String?

          def title=: (String) -> String

          def initialize: (
            ?actions: HubSpotSDK::Crm::Extensions::CardActions,
            ?display_: HubSpotSDK::Crm::Extensions::CardDisplayBody,
            ?fetch: HubSpotSDK::Crm::Extensions::CardFetchBodyPatch,
            ?title: String
          ) -> void

          def to_hash: -> {
            actions: HubSpotSDK::Crm::Extensions::CardActions,
            display_: HubSpotSDK::Crm::Extensions::CardDisplayBody,
            fetch: HubSpotSDK::Crm::Extensions::CardFetchBodyPatch,
            title: String
          }
        end
      end
    end
  end
end
