module HubspotSDK
  module Models
    module Crm
      module Extensions
        type card_fetch_body =
          {
            card_type: HubspotSDK::Models::Crm::Extensions::CardFetchBody::card_type,
            object_types: ::Array[HubspotSDK::Crm::Extensions::CardObjectTypeBody],
            target_url: String,
            serverless_function: String
          }

        class CardFetchBody < HubspotSDK::Internal::Type::BaseModel
          attr_accessor card_type: HubspotSDK::Models::Crm::Extensions::CardFetchBody::card_type

          attr_accessor object_types: ::Array[HubspotSDK::Crm::Extensions::CardObjectTypeBody]

          attr_accessor target_url: String

          attr_reader serverless_function: String?

          def serverless_function=: (String) -> String

          def initialize: (
            card_type: HubspotSDK::Models::Crm::Extensions::CardFetchBody::card_type,
            object_types: ::Array[HubspotSDK::Crm::Extensions::CardObjectTypeBody],
            target_url: String,
            ?serverless_function: String
          ) -> void

          def to_hash: -> {
            card_type: HubspotSDK::Models::Crm::Extensions::CardFetchBody::card_type,
            object_types: ::Array[HubspotSDK::Crm::Extensions::CardObjectTypeBody],
            target_url: String,
            serverless_function: String
          }

          type card_type = :EXTERNAL | :SERVERLESS

          module CardType
            extend HubspotSDK::Internal::Type::Enum

            EXTERNAL: :EXTERNAL
            SERVERLESS: :SERVERLESS

            def self?.values: -> ::Array[HubspotSDK::Models::Crm::Extensions::CardFetchBody::card_type]
          end
        end
      end
    end
  end
end
