module HubspotSDK
  module Models
    module Crm
      module Extensions
        type cards_dev_update_params =
          { app_id: Integer, card_id: String }
          & HubspotSDK::Internal::Type::request_parameters

        class CardsDevUpdateParams < HubspotSDK::Models::Crm::Extensions::CardPatchRequest
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          def app_id: -> Integer

          def app_id=: (Integer _) -> Integer

          def card_id: -> String

          def card_id=: (String _) -> String

          def initialize: (
            app_id: Integer,
            card_id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            app_id: Integer,
            card_id: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
