module HubspotSDK
  module Models
    module CRM
      module Extensions
        type card_create_request =
          {
            actions: HubspotSDK::CRM::Extensions::CardActions,
            display_: HubspotSDK::CRM::Extensions::CardDisplayBody,
            fetch: HubspotSDK::CRM::Extensions::CardFetchBody,
            title: String
          }

        class CardCreateRequest < HubspotSDK::Internal::Type::BaseModel
          attr_accessor actions: HubspotSDK::CRM::Extensions::CardActions

          attr_accessor display_: HubspotSDK::CRM::Extensions::CardDisplayBody

          attr_accessor fetch: HubspotSDK::CRM::Extensions::CardFetchBody

          attr_accessor title: String

          def initialize: (
            actions: HubspotSDK::CRM::Extensions::CardActions,
            display_: HubspotSDK::CRM::Extensions::CardDisplayBody,
            fetch: HubspotSDK::CRM::Extensions::CardFetchBody,
            title: String
          ) -> void

          def to_hash: -> {
            actions: HubspotSDK::CRM::Extensions::CardActions,
            display_: HubspotSDK::CRM::Extensions::CardDisplayBody,
            fetch: HubspotSDK::CRM::Extensions::CardFetchBody,
            title: String
          }
        end
      end
    end
  end
end
