module HubspotSDK
  module Models
    module Crm
      module Extensions
        type channel_connection_settings_response =
          { created_at: Time, is_ready: bool, updated_at: Time, url: String }

        class ChannelConnectionSettingsResponse < HubspotSDK::Internal::Type::BaseModel
          attr_accessor created_at: Time

          attr_accessor is_ready: bool

          attr_accessor updated_at: Time

          attr_accessor url: String

          def initialize: (
            created_at: Time,
            is_ready: bool,
            updated_at: Time,
            url: String
          ) -> void

          def to_hash: -> {
            created_at: Time,
            is_ready: bool,
            updated_at: Time,
            url: String
          }
        end
      end
    end
  end
end
