module HubSpotSDK
  module Models
    module Crm
      module Extensions
        type company_caller_id =
          {
            caller_id_type: HubSpotSDK::Models::Crm::Extensions::CompanyCallerID::caller_id_type,
            object_coordinates: HubSpotSDK::Crm::Extensions::ObjectCoordinates,
            name: String
          }

        class CompanyCallerID < HubSpotSDK::Internal::Type::BaseModel
          attr_accessor caller_id_type: HubSpotSDK::Models::Crm::Extensions::CompanyCallerID::caller_id_type

          attr_accessor object_coordinates: HubSpotSDK::Crm::Extensions::ObjectCoordinates

          attr_reader name: String?

          def name=: (String) -> String

          def initialize: (
            caller_id_type: HubSpotSDK::Models::Crm::Extensions::CompanyCallerID::caller_id_type,
            object_coordinates: HubSpotSDK::Crm::Extensions::ObjectCoordinates,
            ?name: String
          ) -> void

          def to_hash: -> {
            caller_id_type: HubSpotSDK::Models::Crm::Extensions::CompanyCallerID::caller_id_type,
            object_coordinates: HubSpotSDK::Crm::Extensions::ObjectCoordinates,
            name: String
          }

          type caller_id_type = :COMPANY

          module CallerIDType
            extend HubSpotSDK::Internal::Type::Enum

            COMPANY: :COMPANY

            def self?.values: -> ::Array[HubSpotSDK::Models::Crm::Extensions::CompanyCallerID::caller_id_type]
          end
        end
      end
    end
  end
end
