module HubspotSDK
  module Models
    module Crm
      module Extensions
        type contact_caller_id =
          {
            caller_id_type: HubspotSDK::Models::Crm::Extensions::ContactCallerID::caller_id_type,
            object_coordinates: HubspotSDK::Crm::Extensions::ObjectCoordinates,
            email: String,
            first_name: String,
            last_name: String
          }

        class ContactCallerID < HubspotSDK::Internal::Type::BaseModel
          attr_accessor caller_id_type: HubspotSDK::Models::Crm::Extensions::ContactCallerID::caller_id_type

          attr_accessor object_coordinates: HubspotSDK::Crm::Extensions::ObjectCoordinates

          attr_reader email: String?

          def email=: (String) -> String

          attr_reader first_name: String?

          def first_name=: (String) -> String

          attr_reader last_name: String?

          def last_name=: (String) -> String

          def initialize: (
            caller_id_type: HubspotSDK::Models::Crm::Extensions::ContactCallerID::caller_id_type,
            object_coordinates: HubspotSDK::Crm::Extensions::ObjectCoordinates,
            ?email: String,
            ?first_name: String,
            ?last_name: String
          ) -> void

          def to_hash: -> {
            caller_id_type: HubspotSDK::Models::Crm::Extensions::ContactCallerID::caller_id_type,
            object_coordinates: HubspotSDK::Crm::Extensions::ObjectCoordinates,
            email: String,
            first_name: String,
            last_name: String
          }

          type caller_id_type = :CONTACT

          module CallerIDType
            extend HubspotSDK::Internal::Type::Enum

            CONTACT: :CONTACT

            def self?.values: -> ::Array[HubspotSDK::Models::Crm::Extensions::ContactCallerID::caller_id_type]
          end
        end
      end
    end
  end
end
