module HubspotSDK
  module Models
    module CRM
      module Extensions
        type display_option =
          {
            label: String,
            name: String,
            type: HubspotSDK::Models::CRM::Extensions::DisplayOption::type_
          }

        class DisplayOption < HubspotSDK::Internal::Type::BaseModel
          attr_accessor label: String

          attr_accessor name: String

          attr_accessor type: HubspotSDK::Models::CRM::Extensions::DisplayOption::type_

          def initialize: (
            label: String,
            name: String,
            type: HubspotSDK::Models::CRM::Extensions::DisplayOption::type_
          ) -> void

          def to_hash: -> {
            label: String,
            name: String,
            type: HubspotSDK::Models::CRM::Extensions::DisplayOption::type_
          }

          type type_ = :DEFAULT | :SUCCESS | :WARNING | :DANGER | :INFO

          module Type
            extend HubspotSDK::Internal::Type::Enum

            DEFAULT: :DEFAULT
            SUCCESS: :SUCCESS
            WARNING: :WARNING
            DANGER: :DANGER
            INFO: :INFO

            def self?.values: -> ::Array[HubspotSDK::Models::CRM::Extensions::DisplayOption::type_]
          end
        end
      end
    end
  end
end
