module HubSpotSDK
  module Models
    module Crm
      module Extensions
        type display_option =
          {
            label: String,
            name: String,
            type: HubSpotSDK::Models::Crm::Extensions::DisplayOption::type_
          }

        class DisplayOption < HubSpotSDK::Internal::Type::BaseModel
          attr_accessor label: String

          attr_accessor name: String

          attr_accessor type: HubSpotSDK::Models::Crm::Extensions::DisplayOption::type_

          def initialize: (
            label: String,
            name: String,
            type: HubSpotSDK::Models::Crm::Extensions::DisplayOption::type_
          ) -> void

          def to_hash: -> {
            label: String,
            name: String,
            type: HubSpotSDK::Models::Crm::Extensions::DisplayOption::type_
          }

          type type_ = :DANGER | :DEFAULT | :INFO | :SUCCESS | :WARNING

          module Type
            extend HubSpotSDK::Internal::Type::Enum

            DANGER: :DANGER
            DEFAULT: :DEFAULT
            INFO: :INFO
            SUCCESS: :SUCCESS
            WARNING: :WARNING

            def self?.values: -> ::Array[HubSpotSDK::Models::Crm::Extensions::DisplayOption::type_]
          end
        end
      end
    end
  end
end
