module HubspotSDK
  module Models
    module CRM
      module Extensions
        type external_settings =
          {
            create_meeting_url: String,
            delete_meeting_url: String,
            fetch_accounts_uri: String,
            update_meeting_url: String,
            user_verify_url: String
          }

        class ExternalSettings < HubspotSDK::Internal::Type::BaseModel
          attr_accessor create_meeting_url: String

          attr_reader delete_meeting_url: String?

          def delete_meeting_url=: (String) -> String

          attr_reader fetch_accounts_uri: String?

          def fetch_accounts_uri=: (String) -> String

          attr_reader update_meeting_url: String?

          def update_meeting_url=: (String) -> String

          attr_reader user_verify_url: String?

          def user_verify_url=: (String) -> String

          def initialize: (
            create_meeting_url: String,
            ?delete_meeting_url: String,
            ?fetch_accounts_uri: String,
            ?update_meeting_url: String,
            ?user_verify_url: String
          ) -> void

          def to_hash: -> {
            create_meeting_url: String,
            delete_meeting_url: String,
            fetch_accounts_uri: String,
            update_meeting_url: String,
            user_verify_url: String
          }
        end
      end
    end
  end
end
