module HubSpotSDK
  module Models
    module Crm
      module Extensions
        type object_token =
          {
            value: String,
            data_type: HubSpotSDK::Models::Crm::Extensions::ObjectToken::data_type,
            label: String,
            name: String
          }

        class ObjectToken < HubSpotSDK::Internal::Type::BaseModel
          attr_accessor value: String

          attr_reader data_type: HubSpotSDK::Models::Crm::Extensions::ObjectToken::data_type?

          def data_type=: (
            HubSpotSDK::Models::Crm::Extensions::ObjectToken::data_type
          ) -> HubSpotSDK::Models::Crm::Extensions::ObjectToken::data_type

          attr_reader label: String?

          def label=: (String) -> String

          attr_reader name: String?

          def name=: (String) -> String

          def initialize: (
            value: String,
            ?data_type: HubSpotSDK::Models::Crm::Extensions::ObjectToken::data_type,
            ?label: String,
            ?name: String
          ) -> void

          def to_hash: -> {
            value: String,
            data_type: HubSpotSDK::Models::Crm::Extensions::ObjectToken::data_type,
            label: String,
            name: String
          }

          type data_type =
            :BOOLEAN
            | :CURRENCY
            | :DATE
            | :DATETIME
            | :EMAIL
            | :LINK
            | :NUMERIC
            | :STATUS
            | :STRING

          module DataType
            extend HubSpotSDK::Internal::Type::Enum

            BOOLEAN: :BOOLEAN
            CURRENCY: :CURRENCY
            DATE: :DATE
            DATETIME: :DATETIME
            EMAIL: :EMAIL
            LINK: :LINK
            NUMERIC: :NUMERIC
            STATUS: :STATUS
            STRING: :STRING

            def self?.values: -> ::Array[HubSpotSDK::Models::Crm::Extensions::ObjectToken::data_type]
          end
        end
      end
    end
  end
end
