module HubSpotSDK
  module Models
    module Crm
      module Extensions
        type public_card_response =
          {
            id: String,
            actions: HubSpotSDK::Crm::Extensions::CardActions,
            audit_history: ::Array[HubSpotSDK::Crm::Extensions::CardAuditResponse],
            display_: HubSpotSDK::Crm::Extensions::CardDisplayBody,
            fetch: HubSpotSDK::Crm::Extensions::PublicCardFetchBody,
            title: String,
            created_at: Time,
            updated_at: Time
          }

        class PublicCardResponse < HubSpotSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor actions: HubSpotSDK::Crm::Extensions::CardActions

          attr_accessor audit_history: ::Array[HubSpotSDK::Crm::Extensions::CardAuditResponse]

          attr_accessor display_: HubSpotSDK::Crm::Extensions::CardDisplayBody

          attr_accessor fetch: HubSpotSDK::Crm::Extensions::PublicCardFetchBody

          attr_accessor title: String

          attr_reader created_at: Time?

          def created_at=: (Time) -> Time

          attr_reader updated_at: Time?

          def updated_at=: (Time) -> Time

          def initialize: (
            id: String,
            actions: HubSpotSDK::Crm::Extensions::CardActions,
            audit_history: ::Array[HubSpotSDK::Crm::Extensions::CardAuditResponse],
            display_: HubSpotSDK::Crm::Extensions::CardDisplayBody,
            fetch: HubSpotSDK::Crm::Extensions::PublicCardFetchBody,
            title: String,
            ?created_at: Time,
            ?updated_at: Time
          ) -> void

          def to_hash: -> {
            id: String,
            actions: HubSpotSDK::Crm::Extensions::CardActions,
            audit_history: ::Array[HubSpotSDK::Crm::Extensions::CardAuditResponse],
            display_: HubSpotSDK::Crm::Extensions::CardDisplayBody,
            fetch: HubSpotSDK::Crm::Extensions::PublicCardFetchBody,
            title: String,
            created_at: Time,
            updated_at: Time
          }
        end
      end
    end
  end
end
