module HubSpotSDK
  module Models
    module Crm
      module Extensions
        type public_card_fetch_body =
          {
            object_types: ::Array[HubSpotSDK::Crm::Extensions::CardObjectTypeBody],
            target_url: String
          }

        class PublicCardFetchBody < HubSpotSDK::Internal::Type::BaseModel
          attr_accessor object_types: ::Array[HubSpotSDK::Crm::Extensions::CardObjectTypeBody]

          attr_accessor target_url: String

          def initialize: (
            object_types: ::Array[HubSpotSDK::Crm::Extensions::CardObjectTypeBody],
            target_url: String
          ) -> void

          def to_hash: -> {
            object_types: ::Array[HubSpotSDK::Crm::Extensions::CardObjectTypeBody],
            target_url: String
          }
        end
      end
    end
  end
end
