module HubSpotSDK
  module Models
    module Crm
      module Extensions
        type public_card_list_response =
          { results: ::Array[HubSpotSDK::Crm::Extensions::PublicCardResponse] }

        class PublicCardListResponse < HubSpotSDK::Internal::Type::BaseModel
          attr_accessor results: ::Array[HubSpotSDK::Crm::Extensions::PublicCardResponse]

          def initialize: (
            results: ::Array[HubSpotSDK::Crm::Extensions::PublicCardResponse]
          ) -> void

          def to_hash: -> {
            results: ::Array[HubSpotSDK::Crm::Extensions::PublicCardResponse]
          }
        end
      end
    end
  end
end
