module HubspotSDK
  module Models
    module CRM
      module Extensions
        type settings_patch_request =
          {
            height: Integer,
            is_ready: bool,
            name: String,
            supports_custom_objects: bool,
            supports_inbound_calling: bool,
            url: String,
            uses_calling_window: bool,
            uses_remote: bool,
            width: Integer
          }

        class SettingsPatchRequest < HubspotSDK::Internal::Type::BaseModel
          attr_reader height: Integer?

          def height=: (Integer) -> Integer

          attr_reader is_ready: bool?

          def is_ready=: (bool) -> bool

          attr_reader name: String?

          def name=: (String) -> String

          attr_reader supports_custom_objects: bool?

          def supports_custom_objects=: (bool) -> bool

          attr_reader supports_inbound_calling: bool?

          def supports_inbound_calling=: (bool) -> bool

          attr_reader url: String?

          def url=: (String) -> String

          attr_reader uses_calling_window: bool?

          def uses_calling_window=: (bool) -> bool

          attr_reader uses_remote: bool?

          def uses_remote=: (bool) -> bool

          attr_reader width: Integer?

          def width=: (Integer) -> Integer

          def initialize: (
            ?height: Integer,
            ?is_ready: bool,
            ?name: String,
            ?supports_custom_objects: bool,
            ?supports_inbound_calling: bool,
            ?url: String,
            ?uses_calling_window: bool,
            ?uses_remote: bool,
            ?width: Integer
          ) -> void

          def to_hash: -> {
            height: Integer,
            is_ready: bool,
            name: String,
            supports_custom_objects: bool,
            supports_inbound_calling: bool,
            url: String,
            uses_calling_window: bool,
            uses_remote: bool,
            width: Integer
          }
        end
      end
    end
  end
end
