module HubSpotSDK
  module Models
    module Crm
      module Extensions
        type settings_request =
          {
            height: Integer,
            is_ready: bool,
            name: String,
            supports_custom_objects: bool,
            supports_inbound_calling: bool,
            url: String,
            uses_calling_window: bool,
            uses_remote: bool,
            width: Integer
          }

        class SettingsRequest < HubSpotSDK::Internal::Type::BaseModel
          attr_accessor height: Integer

          attr_accessor is_ready: bool

          attr_accessor name: String

          attr_accessor supports_custom_objects: bool

          attr_accessor supports_inbound_calling: bool

          attr_accessor url: String

          attr_accessor uses_calling_window: bool

          attr_accessor uses_remote: bool

          attr_accessor width: Integer

          def initialize: (
            height: Integer,
            is_ready: bool,
            name: String,
            supports_custom_objects: bool,
            supports_inbound_calling: bool,
            url: String,
            uses_calling_window: bool,
            uses_remote: bool,
            width: Integer
          ) -> void

          def to_hash: -> {
            height: Integer,
            is_ready: bool,
            name: String,
            supports_custom_objects: bool,
            supports_inbound_calling: bool,
            url: String,
            uses_calling_window: bool,
            uses_remote: bool,
            width: Integer
          }
        end
      end
    end
  end
end
