module HubspotSDK
  module Models
    module CRM
      module Extensions
        type settings_response =
          {
            created_at: Time,
            height: Integer,
            is_ready: bool,
            name: String,
            supports_custom_objects: bool,
            supports_inbound_calling: bool,
            updated_at: Time,
            url: String,
            uses_calling_window: bool,
            uses_remote: bool,
            width: Integer
          }

        class SettingsResponse < HubspotSDK::Internal::Type::BaseModel
          attr_accessor created_at: Time

          attr_accessor height: Integer

          attr_accessor is_ready: bool

          attr_accessor name: String

          attr_accessor supports_custom_objects: bool

          attr_accessor supports_inbound_calling: bool

          attr_accessor updated_at: Time

          attr_accessor url: String

          attr_accessor uses_calling_window: bool

          attr_accessor uses_remote: bool

          attr_accessor width: Integer

          def initialize: (
            created_at: Time,
            height: Integer,
            is_ready: bool,
            name: String,
            supports_custom_objects: bool,
            supports_inbound_calling: bool,
            updated_at: Time,
            url: String,
            uses_calling_window: bool,
            uses_remote: bool,
            width: Integer
          ) -> void

          def to_hash: -> {
            created_at: Time,
            height: Integer,
            is_ready: bool,
            name: String,
            supports_custom_objects: bool,
            supports_inbound_calling: bool,
            updated_at: Time,
            url: String,
            uses_calling_window: bool,
            uses_remote: bool,
            width: Integer
          }
        end
      end
    end
  end
end
