module HubSpotSDK
  module Models
    module Crm
      module Extensions
        type top_level_actions =
          {
            secondary: ::Array[HubSpotSDK::Models::Crm::Extensions::TopLevelActions::secondary],
            primary: HubSpotSDK::Models::Crm::Extensions::TopLevelActions::primary,
            settings: HubSpotSDK::Crm::Extensions::IFrameActionBody
          }

        class TopLevelActions < HubSpotSDK::Internal::Type::BaseModel
          attr_accessor secondary: ::Array[HubSpotSDK::Models::Crm::Extensions::TopLevelActions::secondary]

          attr_reader primary: HubSpotSDK::Models::Crm::Extensions::TopLevelActions::primary?

          def primary=: (
            HubSpotSDK::Models::Crm::Extensions::TopLevelActions::primary
          ) -> HubSpotSDK::Models::Crm::Extensions::TopLevelActions::primary

          attr_reader settings: HubSpotSDK::Crm::Extensions::IFrameActionBody?

          def settings=: (
            HubSpotSDK::Crm::Extensions::IFrameActionBody
          ) -> HubSpotSDK::Crm::Extensions::IFrameActionBody

          def initialize: (
            secondary: ::Array[HubSpotSDK::Models::Crm::Extensions::TopLevelActions::secondary],
            ?primary: HubSpotSDK::Models::Crm::Extensions::TopLevelActions::primary,
            ?settings: HubSpotSDK::Crm::Extensions::IFrameActionBody
          ) -> void

          def to_hash: -> {
            secondary: ::Array[HubSpotSDK::Models::Crm::Extensions::TopLevelActions::secondary],
            primary: HubSpotSDK::Models::Crm::Extensions::TopLevelActions::primary,
            settings: HubSpotSDK::Crm::Extensions::IFrameActionBody
          }

          type secondary =
            HubSpotSDK::Crm::Extensions::ActionHookActionBody
            | HubSpotSDK::Crm::Extensions::IFrameActionBody

          module Secondary
            extend HubSpotSDK::Internal::Type::Union

            def self?.variants: -> ::Array[HubSpotSDK::Models::Crm::Extensions::TopLevelActions::secondary]
          end

          type primary =
            HubSpotSDK::Crm::Extensions::ActionHookActionBody
            | HubSpotSDK::Crm::Extensions::IFrameActionBody

          module Primary
            extend HubSpotSDK::Internal::Type::Union

            def self?.variants: -> ::Array[HubSpotSDK::Models::Crm::Extensions::TopLevelActions::primary]
          end
        end
      end
    end
  end
end
