module HubspotSDK
  module Resources
    class Marketing
      class Subscriptions
        class V4
          class Statuses
            def update: (
              String subscriber_id_string,
              channel: HubspotSDK::Models::Marketing::Subscriptions::PartialPublicStatusRequest::channel,
              status_state: HubspotSDK::Models::Marketing::Subscriptions::PartialPublicStatusRequest::status_state,
              subscription_id: Integer,
              ?legal_basis: HubspotSDK::Models::Marketing::Subscriptions::PartialPublicStatusRequest::legal_basis,
              ?legal_basis_explanation: String,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Marketing::Subscriptions::ActionResponseWithResultsPublicStatus

            def batch_get: (
              channel: HubspotSDK::Models::BatchInputString::channel,
              inputs: ::Array[String],
              ?business_unit_id: Integer,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Marketing::Subscriptions::BatchResponsePublicStatusBulkResponse

            def batch_get_unsubscribe_all_status: (
              channel: HubspotSDK::Models::BatchInputString::channel,
              inputs: ::Array[String],
              ?business_unit_id: Integer,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Marketing::Subscriptions::BatchResponsePublicWideStatusBulkResponse

            def batch_unsubscribe_all: (
              channel: HubspotSDK::Models::BatchInputString::channel,
              inputs: ::Array[String],
              ?business_unit_id: Integer,
              ?verbose: bool,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Marketing::Subscriptions::BatchResponsePublicBulkOptOutFromAllResponse

            def batch_update: (
              inputs: ::Array[HubspotSDK::Marketing::Subscriptions::PublicStatusRequest],
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Marketing::Subscriptions::BatchResponsePublicStatus

            def get: (
              String subscriber_id_string,
              channel: HubspotSDK::Models::Marketing::Subscriptions::V4::StatusGetParams::channel,
              ?business_unit_id: Integer,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Marketing::Subscriptions::ActionResponseWithResultsPublicStatus

            def get_unsubscribe_all_status: (
              String subscriber_id_string,
              channel: HubspotSDK::Models::Marketing::Subscriptions::V4::StatusGetUnsubscribeAllStatusParams::channel,
              ?business_unit_id: Integer,
              ?verbose: bool,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Marketing::Subscriptions::ActionResponseWithResultsPublicWideStatus

            def unsubscribe_all: (
              String subscriber_id_string,
              channel: HubspotSDK::Models::Marketing::Subscriptions::V4::StatusUnsubscribeAllParams::channel,
              ?business_unit_id: Integer,
              ?verbose: bool,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Marketing::Subscriptions::ActionResponseWithResultsPublicStatus

            def initialize: (client: HubspotSDK::Client) -> void
          end
        end
      end
    end
  end
end
