module HubSpotSDK
  module Models
    module Marketing
      module MarketingEvents
        type list_association_associate_by_external_account_params =
          {
            external_account_id: String,
            external_event_id: String,
            list_id: String
          }
          & HubSpotSDK::Internal::Type::request_parameters

        class ListAssociationAssociateByExternalAccountParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor external_account_id: String

          attr_accessor external_event_id: String

          attr_accessor list_id: String

          def initialize: (
            external_account_id: String,
            external_event_id: String,
            list_id: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            external_account_id: String,
            external_event_id: String,
            list_id: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
