module HubSpotSDK
  module Models
    module Meta
      module Origins
        type ip_range_list_params =
          {
            direction: ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::direction],
            service: ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::service]
          }
          & HubSpotSDK::Internal::Type::request_parameters

        class IPRangeListParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_reader direction: ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::direction]?

          def direction=: (
            ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::direction]
          ) -> ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::direction]

          attr_reader service: ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::service]?

          def service=: (
            ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::service]
          ) -> ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::service]

          def initialize: (
            ?direction: ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::direction],
            ?service: ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::service],
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            direction: ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::direction],
            service: ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::service],
            request_options: HubSpotSDK::RequestOptions
          }

          type direction = :INGRESS | :EGRESS

          module Direction
            extend HubSpotSDK::Internal::Type::Enum

            INGRESS: :INGRESS
            EGRESS: :EGRESS

            def self?.values: -> ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::direction]
          end

          type service = :EMAIL | :API | :DNS | :WEB_SCRAPING | :TEST_SERVICE

          module Service
            extend HubSpotSDK::Internal::Type::Enum

            EMAIL: :EMAIL
            API: :API
            DNS: :DNS
            WEB_SCRAPING: :WEB_SCRAPING
            TEST_SERVICE: :TEST_SERVICE

            def self?.values: -> ::Array[HubSpotSDK::Models::Meta::Origins::IPRangeListParams::service]
          end
        end
      end
    end
  end
end
