module HubspotSDK
  module Resources
    class Settings
      class Currencies
        class ExchangeRates
          attr_reader batch: HubspotSDK::Resources::Settings::Currencies::ExchangeRates::Batch

          def create_exchange_rate: (
            conversion_rate: Float,
            from_currency_code: HubspotSDK::Models::Settings::ExchangeRateCreateRequest::from_currency_code,
            ?effective_at: Time,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Settings::ExchangeRate

          def get_exchange_rate_by_id: (
            String exchange_rate_id,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Settings::ExchangeRate

          def list_current_exchange_rates: (
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Settings::CollectionResponseExchangeRateNoPaging

          def list_exchange_rates: (
            ?after: String,
            ?from_currency_code: HubspotSDK::Models::Settings::Currencies::ExchangeRateListExchangeRatesParams::from_currency_code,
            ?limit: Integer,
            ?to_currency_code: HubspotSDK::Models::Settings::Currencies::ExchangeRateListExchangeRatesParams::to_currency_code,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Internal::Page[HubspotSDK::Settings::ExchangeRate]

          def update_exchange_rate: (
            String exchange_rate_id,
            conversion_rate: Float,
            ?effective_at: Time,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Settings::ExchangeRate

          def update_visibility: (
            from_currency_code: HubspotSDK::Models::Settings::CurrencyPairUpdate::from_currency_code,
            to_currency_code: HubspotSDK::Models::Settings::CurrencyPairUpdate::to_currency_code,
            visible_in_ui: bool,
            ?request_options: HubspotSDK::request_opts
          ) -> nil

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
