module HubSpotSDK
  module Models
    type association_definition =
      {
        id: String,
        from_object_type_id: String,
        to_object_type_id: String,
        created_at: Time,
        name: String,
        updated_at: Time
      }

    class AssociationDefinition < HubSpotSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor from_object_type_id: String

      attr_accessor to_object_type_id: String

      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader updated_at: Time?

      def updated_at=: (Time) -> Time

      def initialize: (
        id: String,
        from_object_type_id: String,
        to_object_type_id: String,
        ?created_at: Time,
        ?name: String,
        ?updated_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        from_object_type_id: String,
        to_object_type_id: String,
        created_at: Time,
        name: String,
        updated_at: Time
      }
    end
  end
end
