module HubspotSDK
  module Models
    type association_definition_egg =
      { from_object_type_id: String, to_object_type_id: String, name: String }

    class AssociationDefinitionEgg < HubspotSDK::Internal::Type::BaseModel
      attr_accessor from_object_type_id: String

      attr_accessor to_object_type_id: String

      attr_reader name: String?

      def name=: (String) -> String

      def initialize: (
        from_object_type_id: String,
        to_object_type_id: String,
        ?name: String
      ) -> void

      def to_hash: -> {
        from_object_type_id: String,
        to_object_type_id: String,
        name: String
      }
    end
  end
end
