module HubspotSDK
  module Models
    type association_spec =
      {
        association_category: HubspotSDK::Models::AssociationSpec::association_category,
        association_type_id: Integer
      }

    class AssociationSpec < HubspotSDK::Internal::Type::BaseModel
      attr_accessor association_category: HubspotSDK::Models::AssociationSpec::association_category

      attr_accessor association_type_id: Integer

      def initialize: (
        association_category: HubspotSDK::Models::AssociationSpec::association_category,
        association_type_id: Integer
      ) -> void

      def to_hash: -> {
        association_category: HubspotSDK::Models::AssociationSpec::association_category,
        association_type_id: Integer
      }

      type association_category =
        :HUBSPOT_DEFINED | :USER_DEFINED | :INTEGRATOR_DEFINED

      module AssociationCategory
        extend HubspotSDK::Internal::Type::Enum

        HUBSPOT_DEFINED: :HUBSPOT_DEFINED
        USER_DEFINED: :USER_DEFINED
        INTEGRATOR_DEFINED: :INTEGRATOR_DEFINED

        def self?.values: -> ::Array[HubspotSDK::Models::AssociationSpec::association_category]
      end
    end
  end
end
