module HubSpotSDK
  module Models
    type base_object_type_definition =
      {
        id: String,
        allows_sensitive_properties: bool,
        archived: bool,
        fully_qualified_name: String,
        labels: HubSpotSDK::ObjectTypeDefinitionLabels,
        name: String,
        object_type_id: String,
        required_properties: ::Array[String],
        searchable_properties: ::Array[String],
        secondary_display_properties: ::Array[String],
        created_at: Time,
        description: String,
        portal_id: Integer,
        primary_display_property: String,
        updated_at: Time
      }

    class BaseObjectTypeDefinition < HubSpotSDK::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor allows_sensitive_properties: bool

      attr_accessor archived: bool

      attr_accessor fully_qualified_name: String

      attr_accessor labels: HubSpotSDK::ObjectTypeDefinitionLabels

      attr_accessor name: String

      attr_accessor object_type_id: String

      attr_accessor required_properties: ::Array[String]

      attr_accessor searchable_properties: ::Array[String]

      attr_accessor secondary_display_properties: ::Array[String]

      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader portal_id: Integer?

      def portal_id=: (Integer) -> Integer

      attr_reader primary_display_property: String?

      def primary_display_property=: (String) -> String

      attr_reader updated_at: Time?

      def updated_at=: (Time) -> Time

      def initialize: (
        id: String,
        allows_sensitive_properties: bool,
        archived: bool,
        fully_qualified_name: String,
        labels: HubSpotSDK::ObjectTypeDefinitionLabels,
        name: String,
        object_type_id: String,
        required_properties: ::Array[String],
        searchable_properties: ::Array[String],
        secondary_display_properties: ::Array[String],
        ?created_at: Time,
        ?description: String,
        ?portal_id: Integer,
        ?primary_display_property: String,
        ?updated_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        allows_sensitive_properties: bool,
        archived: bool,
        fully_qualified_name: String,
        labels: HubSpotSDK::ObjectTypeDefinitionLabels,
        name: String,
        object_type_id: String,
        required_properties: ::Array[String],
        searchable_properties: ::Array[String],
        secondary_display_properties: ::Array[String],
        created_at: Time,
        description: String,
        portal_id: Integer,
        primary_display_property: String,
        updated_at: Time
      }
    end
  end
end
