module HubspotSDK
  module Models
    type batch_input_property_name =
      { inputs: ::Array[HubspotSDK::PropertyName] }

    class BatchInputPropertyName < HubspotSDK::Internal::Type::BaseModel
      attr_accessor inputs: ::Array[HubspotSDK::PropertyName]

      def initialize: (inputs: ::Array[HubspotSDK::PropertyName]) -> void

      def to_hash: -> { inputs: ::Array[HubspotSDK::PropertyName] }
    end
  end
end
