module HubSpotSDK
  module Models
    type batch_input_public_object_id =
      { inputs: ::Array[HubSpotSDK::PublicObjectID] }

    class BatchInputPublicObjectID < HubSpotSDK::Internal::Type::BaseModel
      attr_accessor inputs: ::Array[HubSpotSDK::PublicObjectID]

      def initialize: (inputs: ::Array[HubSpotSDK::PublicObjectID]) -> void

      def to_hash: -> { inputs: ::Array[HubSpotSDK::PublicObjectID] }
    end
  end
end
