module HubSpotSDK
  module Models
    type batch_input_property_name =
      { inputs: ::Array[HubSpotSDK::PropertyName] }

    class BatchInputPropertyName < HubSpotSDK::Internal::Type::BaseModel
      attr_accessor inputs: ::Array[HubSpotSDK::PropertyName]

      def initialize: (inputs: ::Array[HubSpotSDK::PropertyName]) -> void

      def to_hash: -> { inputs: ::Array[HubSpotSDK::PropertyName] }
    end
  end
end
