module HubSpotSDK
  module Models
    type collection_response_property_group_no_paging =
      { results: ::Array[HubSpotSDK::PropertyGroup] }

    class CollectionResponsePropertyGroupNoPaging < HubSpotSDK::Internal::Type::BaseModel
      attr_accessor results: ::Array[HubSpotSDK::PropertyGroup]

      def initialize: (results: ::Array[HubSpotSDK::PropertyGroup]) -> void

      def to_hash: -> { results: ::Array[HubSpotSDK::PropertyGroup] }
    end
  end
end
