module HubspotSDK
  module Models
    type collection_response_object_schema_no_paging =
      { results: ::Array[HubspotSDK::ObjectSchema] }

    class CollectionResponseObjectSchemaNoPaging < HubspotSDK::Internal::Type::BaseModel
      attr_accessor results: ::Array[HubspotSDK::ObjectSchema]

      def initialize: (results: ::Array[HubspotSDK::ObjectSchema]) -> void

      def to_hash: -> { results: ::Array[HubspotSDK::ObjectSchema] }
    end
  end
end
