module HubspotSDK
  module Models
    type collection_response_property_group_no_paging =
      { results: ::Array[HubspotSDK::PropertyGroup] }

    class CollectionResponsePropertyGroupNoPaging < HubspotSDK::Internal::Type::BaseModel
      attr_accessor results: ::Array[HubspotSDK::PropertyGroup]

      def initialize: (results: ::Array[HubspotSDK::PropertyGroup]) -> void

      def to_hash: -> { results: ::Array[HubspotSDK::PropertyGroup] }
    end
  end
end
