module HubSpotSDK
  module Models
    type option_input =
      {
        display_order: Integer,
        hidden: bool,
        label: String,
        value: String,
        description: String
      }

    class OptionInput < HubSpotSDK::Internal::Type::BaseModel
      attr_accessor display_order: Integer

      attr_accessor hidden: bool

      attr_accessor label: String

      attr_accessor value: String

      attr_reader description: String?

      def description=: (String) -> String

      def initialize: (
        display_order: Integer,
        hidden: bool,
        label: String,
        value: String,
        ?description: String
      ) -> void

      def to_hash: -> {
        display_order: Integer,
        hidden: bool,
        label: String,
        value: String,
        description: String
      }
    end
  end
end
