module HubSpotSDK
  module Models
    type paging =
      { next_: HubSpotSDK::NextPage, prev: HubSpotSDK::PreviousPage }

    class Paging < HubSpotSDK::Internal::Type::BaseModel
      attr_reader next_: HubSpotSDK::NextPage?

      def next_=: (HubSpotSDK::NextPage) -> HubSpotSDK::NextPage

      attr_reader prev: HubSpotSDK::PreviousPage?

      def prev=: (HubSpotSDK::PreviousPage) -> HubSpotSDK::PreviousPage

      def initialize: (
        ?next_: HubSpotSDK::NextPage,
        ?prev: HubSpotSDK::PreviousPage
      ) -> void

      def to_hash: -> {
        next_: HubSpotSDK::NextPage,
        prev: HubSpotSDK::PreviousPage
      }
    end
  end
end
