module HubSpotSDK
  module Models
    type property =
      {
        description: String,
        field_type: String,
        group_name: String,
        label: String,
        name: String,
        options: ::Array[HubSpotSDK::Option],
        type: String,
        archived: bool,
        archived_at: Time,
        calculated: bool,
        calculation_formula: String,
        created_at: Time,
        created_user_id: String,
        currency_property_name: String,
        data_sensitivity: HubSpotSDK::Models::Property::data_sensitivity,
        date_display_hint: HubSpotSDK::Models::Property::date_display_hint,
        display_order: Integer,
        external_options: bool,
        form_field: bool,
        has_unique_value: bool,
        hidden: bool,
        hubspot_defined: bool,
        modification_metadata: HubSpotSDK::PropertyModificationMetadata,
        number_display_hint: HubSpotSDK::Models::Property::number_display_hint,
        referenced_object_type: String,
        sensitive_data_categories: ::Array[String],
        show_currency_symbol: bool,
        updated_at: Time,
        updated_user_id: String
      }

    class Property < HubSpotSDK::Internal::Type::BaseModel
      attr_accessor description: String

      attr_accessor field_type: String

      attr_accessor group_name: String

      attr_accessor label: String

      attr_accessor name: String

      attr_accessor options: ::Array[HubSpotSDK::Option]

      attr_accessor type: String

      attr_reader archived: bool?

      def archived=: (bool) -> bool

      attr_reader archived_at: Time?

      def archived_at=: (Time) -> Time

      attr_reader calculated: bool?

      def calculated=: (bool) -> bool

      attr_reader calculation_formula: String?

      def calculation_formula=: (String) -> String

      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_reader created_user_id: String?

      def created_user_id=: (String) -> String

      attr_reader currency_property_name: String?

      def currency_property_name=: (String) -> String

      attr_reader data_sensitivity: HubSpotSDK::Models::Property::data_sensitivity?

      def data_sensitivity=: (
        HubSpotSDK::Models::Property::data_sensitivity
      ) -> HubSpotSDK::Models::Property::data_sensitivity

      attr_reader date_display_hint: HubSpotSDK::Models::Property::date_display_hint?

      def date_display_hint=: (
        HubSpotSDK::Models::Property::date_display_hint
      ) -> HubSpotSDK::Models::Property::date_display_hint

      attr_reader display_order: Integer?

      def display_order=: (Integer) -> Integer

      attr_reader external_options: bool?

      def external_options=: (bool) -> bool

      attr_reader form_field: bool?

      def form_field=: (bool) -> bool

      attr_reader has_unique_value: bool?

      def has_unique_value=: (bool) -> bool

      attr_reader hidden: bool?

      def hidden=: (bool) -> bool

      attr_reader hubspot_defined: bool?

      def hubspot_defined=: (bool) -> bool

      attr_reader modification_metadata: HubSpotSDK::PropertyModificationMetadata?

      def modification_metadata=: (
        HubSpotSDK::PropertyModificationMetadata
      ) -> HubSpotSDK::PropertyModificationMetadata

      attr_reader number_display_hint: HubSpotSDK::Models::Property::number_display_hint?

      def number_display_hint=: (
        HubSpotSDK::Models::Property::number_display_hint
      ) -> HubSpotSDK::Models::Property::number_display_hint

      attr_reader referenced_object_type: String?

      def referenced_object_type=: (String) -> String

      attr_reader sensitive_data_categories: ::Array[String]?

      def sensitive_data_categories=: (::Array[String]) -> ::Array[String]

      attr_reader show_currency_symbol: bool?

      def show_currency_symbol=: (bool) -> bool

      attr_reader updated_at: Time?

      def updated_at=: (Time) -> Time

      attr_reader updated_user_id: String?

      def updated_user_id=: (String) -> String

      def initialize: (
        description: String,
        field_type: String,
        group_name: String,
        label: String,
        name: String,
        options: ::Array[HubSpotSDK::Option],
        type: String,
        ?archived: bool,
        ?archived_at: Time,
        ?calculated: bool,
        ?calculation_formula: String,
        ?created_at: Time,
        ?created_user_id: String,
        ?currency_property_name: String,
        ?data_sensitivity: HubSpotSDK::Models::Property::data_sensitivity,
        ?date_display_hint: HubSpotSDK::Models::Property::date_display_hint,
        ?display_order: Integer,
        ?external_options: bool,
        ?form_field: bool,
        ?has_unique_value: bool,
        ?hidden: bool,
        ?hubspot_defined: bool,
        ?modification_metadata: HubSpotSDK::PropertyModificationMetadata,
        ?number_display_hint: HubSpotSDK::Models::Property::number_display_hint,
        ?referenced_object_type: String,
        ?sensitive_data_categories: ::Array[String],
        ?show_currency_symbol: bool,
        ?updated_at: Time,
        ?updated_user_id: String
      ) -> void

      def to_hash: -> {
        description: String,
        field_type: String,
        group_name: String,
        label: String,
        name: String,
        options: ::Array[HubSpotSDK::Option],
        type: String,
        archived: bool,
        archived_at: Time,
        calculated: bool,
        calculation_formula: String,
        created_at: Time,
        created_user_id: String,
        currency_property_name: String,
        data_sensitivity: HubSpotSDK::Models::Property::data_sensitivity,
        date_display_hint: HubSpotSDK::Models::Property::date_display_hint,
        display_order: Integer,
        external_options: bool,
        form_field: bool,
        has_unique_value: bool,
        hidden: bool,
        hubspot_defined: bool,
        modification_metadata: HubSpotSDK::PropertyModificationMetadata,
        number_display_hint: HubSpotSDK::Models::Property::number_display_hint,
        referenced_object_type: String,
        sensitive_data_categories: ::Array[String],
        show_currency_symbol: bool,
        updated_at: Time,
        updated_user_id: String
      }

      type data_sensitivity = :highly_sensitive | :non_sensitive | :sensitive

      module DataSensitivity
        extend HubSpotSDK::Internal::Type::Enum

        HIGHLY_SENSITIVE: :highly_sensitive
        NON_SENSITIVE: :non_sensitive
        SENSITIVE: :sensitive

        def self?.values: -> ::Array[HubSpotSDK::Models::Property::data_sensitivity]
      end

      type date_display_hint =
        :absolute | :absolute_with_relative | :time_since | :time_until

      module DateDisplayHint
        extend HubSpotSDK::Internal::Type::Enum

        ABSOLUTE: :absolute
        ABSOLUTE_WITH_RELATIVE: :absolute_with_relative
        TIME_SINCE: :time_since
        TIME_UNTIL: :time_until

        def self?.values: -> ::Array[HubSpotSDK::Models::Property::date_display_hint]
      end

      type number_display_hint =
        :currency
        | :duration
        | :formatted
        | :percentage
        | :probability
        | :unformatted

      module NumberDisplayHint
        extend HubSpotSDK::Internal::Type::Enum

        CURRENCY: :currency
        DURATION: :duration
        FORMATTED: :formatted
        PERCENTAGE: :percentage
        PROBABILITY: :probability
        UNFORMATTED: :unformatted

        def self?.values: -> ::Array[HubSpotSDK::Models::Property::number_display_hint]
      end
    end
  end
end
