module HubspotSDK
  module Models
    type property_group_update = { display_order: Integer, label: String }

    class PropertyGroupUpdate < HubspotSDK::Internal::Type::BaseModel
      attr_reader display_order: Integer?

      def display_order=: (Integer) -> Integer

      attr_reader label: String?

      def label=: (String) -> String

      def initialize: (?display_order: Integer, ?label: String) -> void

      def to_hash: -> { display_order: Integer, label: String }
    end
  end
end
