module HubSpotSDK
  module Models
    type property_group_create =
      { label: String, name: String, display_order: Integer }

    class PropertyGroupCreate < HubSpotSDK::Internal::Type::BaseModel
      attr_accessor label: String

      attr_accessor name: String

      attr_reader display_order: Integer?

      def display_order=: (Integer) -> Integer

      def initialize: (
        label: String,
        name: String,
        ?display_order: Integer
      ) -> void

      def to_hash: -> { label: String, name: String, display_order: Integer }
    end
  end
end
