module HubspotSDK
  module Models
    type property_name = { name: String }

    class PropertyName < HubspotSDK::Internal::Type::BaseModel
      attr_accessor name: String

      def initialize: (name: String) -> void

      def to_hash: -> { name: String }
    end
  end
end
