module HubspotSDK
  module Models
    type public_time_offset =
      { amount: Integer, offset_direction: String, time_unit: String }

    class PublicTimeOffset < HubspotSDK::Internal::Type::BaseModel
      attr_accessor amount: Integer

      attr_accessor offset_direction: String

      attr_accessor time_unit: String

      def initialize: (
        amount: Integer,
        offset_direction: String,
        time_unit: String
      ) -> void

      def to_hash: -> {
        amount: Integer,
        offset_direction: String,
        time_unit: String
      }
    end
  end
end
