module HubspotSDK
  module Models
    type public_ads_time_filter =
      {
        filter_type: HubspotSDK::Models::PublicAdsTimeFilter::filter_type,
        pruning_refine_by: HubspotSDK::Models::PublicAdsTimeFilter::pruning_refine_by
      }

    class PublicAdsTimeFilter < HubspotSDK::Internal::Type::BaseModel
      attr_accessor filter_type: HubspotSDK::Models::PublicAdsTimeFilter::filter_type

      attr_accessor pruning_refine_by: HubspotSDK::Models::PublicAdsTimeFilter::pruning_refine_by

      def initialize: (
        filter_type: HubspotSDK::Models::PublicAdsTimeFilter::filter_type,
        pruning_refine_by: HubspotSDK::Models::PublicAdsTimeFilter::pruning_refine_by
      ) -> void

      def to_hash: -> {
        filter_type: HubspotSDK::Models::PublicAdsTimeFilter::filter_type,
        pruning_refine_by: HubspotSDK::Models::PublicAdsTimeFilter::pruning_refine_by
      }

      type filter_type = :ADS_TIME

      module FilterType
        extend HubspotSDK::Internal::Type::Enum

        ADS_TIME: :ADS_TIME

        def self?.values: -> ::Array[HubspotSDK::Models::PublicAdsTimeFilter::filter_type]
      end

      type pruning_refine_by =
        HubspotSDK::PublicNumOccurrencesRefineBy
        | HubspotSDK::PublicSetOccurrencesRefineBy
        | HubspotSDK::PublicRelativeComparativeTimestampRefineBy
        | HubspotSDK::PublicRelativeRangedTimestampRefineBy
        | HubspotSDK::PublicAbsoluteComparativeTimestampRefineBy
        | HubspotSDK::PublicAbsoluteRangedTimestampRefineBy
        | HubspotSDK::PublicAllHistoryRefineBy
        | HubspotSDK::PublicTimePointOperation
        | HubspotSDK::PublicRangedTimeOperation

      module PruningRefineBy
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::PublicAdsTimeFilter::pruning_refine_by]
      end
    end
  end
end
