module HubspotSDK
  module Models
    type public_form_submission_filter =
      {
        filter_type: HubspotSDK::Models::PublicFormSubmissionFilter::filter_type,
        operator: HubspotSDK::Models::PublicFormSubmissionFilter::operator,
        coalescing_refine_by: HubspotSDK::Models::PublicFormSubmissionFilter::coalescing_refine_by,
        form_id: String,
        pruning_refine_by: HubspotSDK::Models::PublicFormSubmissionFilter::pruning_refine_by
      }

    class PublicFormSubmissionFilter < HubspotSDK::Internal::Type::BaseModel
      attr_accessor filter_type: HubspotSDK::Models::PublicFormSubmissionFilter::filter_type

      attr_accessor operator: HubspotSDK::Models::PublicFormSubmissionFilter::operator

      attr_reader coalescing_refine_by: HubspotSDK::Models::PublicFormSubmissionFilter::coalescing_refine_by?

      def coalescing_refine_by=: (
        HubspotSDK::Models::PublicFormSubmissionFilter::coalescing_refine_by
      ) -> HubspotSDK::Models::PublicFormSubmissionFilter::coalescing_refine_by

      attr_reader form_id: String?

      def form_id=: (String) -> String

      attr_reader pruning_refine_by: HubspotSDK::Models::PublicFormSubmissionFilter::pruning_refine_by?

      def pruning_refine_by=: (
        HubspotSDK::Models::PublicFormSubmissionFilter::pruning_refine_by
      ) -> HubspotSDK::Models::PublicFormSubmissionFilter::pruning_refine_by

      def initialize: (
        filter_type: HubspotSDK::Models::PublicFormSubmissionFilter::filter_type,
        operator: HubspotSDK::Models::PublicFormSubmissionFilter::operator,
        ?coalescing_refine_by: HubspotSDK::Models::PublicFormSubmissionFilter::coalescing_refine_by,
        ?form_id: String,
        ?pruning_refine_by: HubspotSDK::Models::PublicFormSubmissionFilter::pruning_refine_by
      ) -> void

      def to_hash: -> {
        filter_type: HubspotSDK::Models::PublicFormSubmissionFilter::filter_type,
        operator: HubspotSDK::Models::PublicFormSubmissionFilter::operator,
        coalescing_refine_by: HubspotSDK::Models::PublicFormSubmissionFilter::coalescing_refine_by,
        form_id: String,
        pruning_refine_by: HubspotSDK::Models::PublicFormSubmissionFilter::pruning_refine_by
      }

      type filter_type = :FORM_SUBMISSION

      module FilterType
        extend HubspotSDK::Internal::Type::Enum

        FORM_SUBMISSION: :FORM_SUBMISSION

        def self?.values: -> ::Array[HubspotSDK::Models::PublicFormSubmissionFilter::filter_type]
      end

      type operator = :FILLED_OUT | :NOT_FILLED_OUT

      module Operator
        extend HubspotSDK::Internal::Type::Enum

        FILLED_OUT: :FILLED_OUT
        NOT_FILLED_OUT: :NOT_FILLED_OUT

        def self?.values: -> ::Array[HubspotSDK::Models::PublicFormSubmissionFilter::operator]
      end

      type coalescing_refine_by =
        HubspotSDK::PublicNumOccurrencesRefineBy
        | HubspotSDK::PublicSetOccurrencesRefineBy
        | HubspotSDK::PublicRelativeComparativeTimestampRefineBy
        | HubspotSDK::PublicRelativeRangedTimestampRefineBy
        | HubspotSDK::PublicAbsoluteComparativeTimestampRefineBy
        | HubspotSDK::PublicAbsoluteRangedTimestampRefineBy
        | HubspotSDK::PublicAllHistoryRefineBy
        | HubspotSDK::PublicTimePointOperation
        | HubspotSDK::PublicRangedTimeOperation

      module CoalescingRefineBy
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::PublicFormSubmissionFilter::coalescing_refine_by]
      end

      type pruning_refine_by =
        HubspotSDK::PublicNumOccurrencesRefineBy
        | HubspotSDK::PublicSetOccurrencesRefineBy
        | HubspotSDK::PublicRelativeComparativeTimestampRefineBy
        | HubspotSDK::PublicRelativeRangedTimestampRefineBy
        | HubspotSDK::PublicAbsoluteComparativeTimestampRefineBy
        | HubspotSDK::PublicAbsoluteRangedTimestampRefineBy
        | HubspotSDK::PublicAllHistoryRefineBy
        | HubspotSDK::PublicTimePointOperation
        | HubspotSDK::PublicRangedTimeOperation

      module PruningRefineBy
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::PublicFormSubmissionFilter::pruning_refine_by]
      end
    end
  end
end
