module HubspotSDK
  module Models
    type public_calendar_date_property_operation =
      {
        include_objects_with_no_value_set: bool,
        operation_type: HubspotSDK::Models::PublicCalendarDatePropertyOperation::operation_type,
        operator: String,
        time_unit: String,
        fiscal_year_start: HubspotSDK::Models::PublicCalendarDatePropertyOperation::fiscal_year_start,
        time_unit_count: Integer,
        use_fiscal_year: bool
      }

    class PublicCalendarDatePropertyOperation < HubspotSDK::Internal::Type::BaseModel
      attr_accessor include_objects_with_no_value_set: bool

      attr_accessor operation_type: HubspotSDK::Models::PublicCalendarDatePropertyOperation::operation_type

      attr_accessor operator: String

      attr_accessor time_unit: String

      attr_reader fiscal_year_start: HubspotSDK::Models::PublicCalendarDatePropertyOperation::fiscal_year_start?

      def fiscal_year_start=: (
        HubspotSDK::Models::PublicCalendarDatePropertyOperation::fiscal_year_start
      ) -> HubspotSDK::Models::PublicCalendarDatePropertyOperation::fiscal_year_start

      attr_reader time_unit_count: Integer?

      def time_unit_count=: (Integer) -> Integer

      attr_reader use_fiscal_year: bool?

      def use_fiscal_year=: (bool) -> bool

      def initialize: (
        include_objects_with_no_value_set: bool,
        operation_type: HubspotSDK::Models::PublicCalendarDatePropertyOperation::operation_type,
        operator: String,
        time_unit: String,
        ?fiscal_year_start: HubspotSDK::Models::PublicCalendarDatePropertyOperation::fiscal_year_start,
        ?time_unit_count: Integer,
        ?use_fiscal_year: bool
      ) -> void

      def to_hash: -> {
        include_objects_with_no_value_set: bool,
        operation_type: HubspotSDK::Models::PublicCalendarDatePropertyOperation::operation_type,
        operator: String,
        time_unit: String,
        fiscal_year_start: HubspotSDK::Models::PublicCalendarDatePropertyOperation::fiscal_year_start,
        time_unit_count: Integer,
        use_fiscal_year: bool
      }

      type operation_type = :CALENDAR_DATE

      module OperationType
        extend HubspotSDK::Internal::Type::Enum

        CALENDAR_DATE: :CALENDAR_DATE

        def self?.values: -> ::Array[HubspotSDK::Models::PublicCalendarDatePropertyOperation::operation_type]
      end

      type fiscal_year_start =
        :JANUARY
        | :FEBRUARY
        | :MARCH
        | :APRIL
        | :MAY
        | :JUNE
        | :JULY
        | :AUGUST
        | :SEPTEMBER
        | :OCTOBER
        | :NOVEMBER
        | :DECEMBER

      module FiscalYearStart
        extend HubspotSDK::Internal::Type::Enum

        JANUARY: :JANUARY
        FEBRUARY: :FEBRUARY
        MARCH: :MARCH
        APRIL: :APRIL
        MAY: :MAY
        JUNE: :JUNE
        JULY: :JULY
        AUGUST: :AUGUST
        SEPTEMBER: :SEPTEMBER
        OCTOBER: :OCTOBER
        NOVEMBER: :NOVEMBER
        DECEMBER: :DECEMBER

        def self?.values: -> ::Array[HubspotSDK::Models::PublicCalendarDatePropertyOperation::fiscal_year_start]
      end
    end
  end
end
