module HubspotSDK
  module Models
    type public_survey_monkey_filter =
      {
        filter_type: HubspotSDK::Models::PublicSurveyMonkeyFilter::filter_type,
        operator: String,
        survey_id: String
      }

    class PublicSurveyMonkeyFilter < HubspotSDK::Internal::Type::BaseModel
      attr_accessor filter_type: HubspotSDK::Models::PublicSurveyMonkeyFilter::filter_type

      attr_accessor operator: String

      attr_accessor survey_id: String

      def initialize: (
        filter_type: HubspotSDK::Models::PublicSurveyMonkeyFilter::filter_type,
        operator: String,
        survey_id: String
      ) -> void

      def to_hash: -> {
        filter_type: HubspotSDK::Models::PublicSurveyMonkeyFilter::filter_type,
        operator: String,
        survey_id: String
      }

      type filter_type = :SURVEY_MONKEY

      module FilterType
        extend HubspotSDK::Internal::Type::Enum

        SURVEY_MONKEY: :SURVEY_MONKEY

        def self?.values: -> ::Array[HubspotSDK::Models::PublicSurveyMonkeyFilter::filter_type]
      end
    end
  end
end
