module HubspotSDK
  module Models
    type public_year_reference =
      {
        day: Integer,
        month: Integer,
        reference_type: HubspotSDK::Models::PublicYearReference::reference_type,
        hour: Integer,
        millisecond: Integer,
        minute: Integer,
        second: Integer
      }

    class PublicYearReference < HubspotSDK::Internal::Type::BaseModel
      attr_accessor day: Integer

      attr_accessor month: Integer

      attr_accessor reference_type: HubspotSDK::Models::PublicYearReference::reference_type

      attr_reader hour: Integer?

      def hour=: (Integer) -> Integer

      attr_reader millisecond: Integer?

      def millisecond=: (Integer) -> Integer

      attr_reader minute: Integer?

      def minute=: (Integer) -> Integer

      attr_reader second: Integer?

      def second=: (Integer) -> Integer

      def initialize: (
        day: Integer,
        month: Integer,
        reference_type: HubspotSDK::Models::PublicYearReference::reference_type,
        ?hour: Integer,
        ?millisecond: Integer,
        ?minute: Integer,
        ?second: Integer
      ) -> void

      def to_hash: -> {
        day: Integer,
        month: Integer,
        reference_type: HubspotSDK::Models::PublicYearReference::reference_type,
        hour: Integer,
        millisecond: Integer,
        minute: Integer,
        second: Integer
      }

      type reference_type = :YEAR

      module ReferenceType
        extend HubspotSDK::Internal::Type::Enum

        YEAR: :YEAR

        def self?.values: -> ::Array[HubspotSDK::Models::PublicYearReference::reference_type]
      end
    end
  end
end
