module HubspotSDK
  module Models
    type public_event_analytics_filter =
      {
        event_id: String,
        filter_type: HubspotSDK::Models::PublicEventAnalyticsFilter::filter_type,
        operator: String,
        coalescing_refine_by: HubspotSDK::Models::PublicEventAnalyticsFilter::coalescing_refine_by,
        pruning_refine_by: HubspotSDK::Models::PublicEventAnalyticsFilter::pruning_refine_by
      }

    class PublicEventAnalyticsFilter < HubspotSDK::Internal::Type::BaseModel
      attr_accessor event_id: String

      attr_accessor filter_type: HubspotSDK::Models::PublicEventAnalyticsFilter::filter_type

      attr_accessor operator: String

      attr_reader coalescing_refine_by: HubspotSDK::Models::PublicEventAnalyticsFilter::coalescing_refine_by?

      def coalescing_refine_by=: (
        HubspotSDK::Models::PublicEventAnalyticsFilter::coalescing_refine_by
      ) -> HubspotSDK::Models::PublicEventAnalyticsFilter::coalescing_refine_by

      attr_reader pruning_refine_by: HubspotSDK::Models::PublicEventAnalyticsFilter::pruning_refine_by?

      def pruning_refine_by=: (
        HubspotSDK::Models::PublicEventAnalyticsFilter::pruning_refine_by
      ) -> HubspotSDK::Models::PublicEventAnalyticsFilter::pruning_refine_by

      def initialize: (
        event_id: String,
        filter_type: HubspotSDK::Models::PublicEventAnalyticsFilter::filter_type,
        operator: String,
        ?coalescing_refine_by: HubspotSDK::Models::PublicEventAnalyticsFilter::coalescing_refine_by,
        ?pruning_refine_by: HubspotSDK::Models::PublicEventAnalyticsFilter::pruning_refine_by
      ) -> void

      def to_hash: -> {
        event_id: String,
        filter_type: HubspotSDK::Models::PublicEventAnalyticsFilter::filter_type,
        operator: String,
        coalescing_refine_by: HubspotSDK::Models::PublicEventAnalyticsFilter::coalescing_refine_by,
        pruning_refine_by: HubspotSDK::Models::PublicEventAnalyticsFilter::pruning_refine_by
      }

      type filter_type = :EVENT

      module FilterType
        extend HubspotSDK::Internal::Type::Enum

        EVENT: :EVENT

        def self?.values: -> ::Array[HubspotSDK::Models::PublicEventAnalyticsFilter::filter_type]
      end

      type coalescing_refine_by =
        HubspotSDK::PublicNumOccurrencesRefineBy
        | HubspotSDK::PublicSetOccurrencesRefineBy
        | HubspotSDK::PublicRelativeComparativeTimestampRefineBy
        | HubspotSDK::PublicRelativeRangedTimestampRefineBy
        | HubspotSDK::PublicAbsoluteComparativeTimestampRefineBy
        | HubspotSDK::PublicAbsoluteRangedTimestampRefineBy
        | HubspotSDK::PublicAllHistoryRefineBy
        | HubspotSDK::PublicTimePointOperation
        | HubspotSDK::PublicRangedTimeOperation

      module CoalescingRefineBy
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::PublicEventAnalyticsFilter::coalescing_refine_by]
      end

      type pruning_refine_by =
        HubspotSDK::PublicNumOccurrencesRefineBy
        | HubspotSDK::PublicSetOccurrencesRefineBy
        | HubspotSDK::PublicRelativeComparativeTimestampRefineBy
        | HubspotSDK::PublicRelativeRangedTimestampRefineBy
        | HubspotSDK::PublicAbsoluteComparativeTimestampRefineBy
        | HubspotSDK::PublicAbsoluteRangedTimestampRefineBy
        | HubspotSDK::PublicAllHistoryRefineBy
        | HubspotSDK::PublicTimePointOperation
        | HubspotSDK::PublicRangedTimeOperation

      module PruningRefineBy
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::PublicEventAnalyticsFilter::pruning_refine_by]
      end
    end
  end
end
