module HubspotSDK
  module Models
    type public_survey_monkey_value_filter =
      {
        filter_type: HubspotSDK::Models::PublicSurveyMonkeyValueFilter::filter_type,
        operator: String,
        survey_id: String,
        survey_question: String,
        value_comparison: HubspotSDK::Models::PublicSurveyMonkeyValueFilter::value_comparison,
        survey_answer_col_id: String,
        survey_answer_row_id: String
      }

    class PublicSurveyMonkeyValueFilter < HubspotSDK::Internal::Type::BaseModel
      attr_accessor filter_type: HubspotSDK::Models::PublicSurveyMonkeyValueFilter::filter_type

      attr_accessor operator: String

      attr_accessor survey_id: String

      attr_accessor survey_question: String

      attr_accessor value_comparison: HubspotSDK::Models::PublicSurveyMonkeyValueFilter::value_comparison

      attr_reader survey_answer_col_id: String?

      def survey_answer_col_id=: (String) -> String

      attr_reader survey_answer_row_id: String?

      def survey_answer_row_id=: (String) -> String

      def initialize: (
        filter_type: HubspotSDK::Models::PublicSurveyMonkeyValueFilter::filter_type,
        operator: String,
        survey_id: String,
        survey_question: String,
        value_comparison: HubspotSDK::Models::PublicSurveyMonkeyValueFilter::value_comparison,
        ?survey_answer_col_id: String,
        ?survey_answer_row_id: String
      ) -> void

      def to_hash: -> {
        filter_type: HubspotSDK::Models::PublicSurveyMonkeyValueFilter::filter_type,
        operator: String,
        survey_id: String,
        survey_question: String,
        value_comparison: HubspotSDK::Models::PublicSurveyMonkeyValueFilter::value_comparison,
        survey_answer_col_id: String,
        survey_answer_row_id: String
      }

      type filter_type = :SURVEY_MONKEY_VALUE

      module FilterType
        extend HubspotSDK::Internal::Type::Enum

        SURVEY_MONKEY_VALUE: :SURVEY_MONKEY_VALUE

        def self?.values: -> ::Array[HubspotSDK::Models::PublicSurveyMonkeyValueFilter::filter_type]
      end

      type value_comparison =
        HubspotSDK::PublicBoolPropertyOperation
        | HubspotSDK::PublicNumberPropertyOperation
        | HubspotSDK::PublicStringPropertyOperation
        | HubspotSDK::PublicDateTimePropertyOperation
        | HubspotSDK::PublicRangedDatePropertyOperation
        | HubspotSDK::PublicComparativePropertyUpdatedOperation
        | HubspotSDK::PublicComparativeDatePropertyOperation
        | HubspotSDK::PublicRollingDateRangePropertyOperation
        | HubspotSDK::PublicRollingPropertyUpdatedOperation
        | HubspotSDK::PublicEnumerationPropertyOperation
        | HubspotSDK::PublicAllPropertyTypesOperation
        | HubspotSDK::PublicRangedNumberPropertyOperation
        | HubspotSDK::PublicMultiStringPropertyOperation
        | HubspotSDK::PublicDatePropertyOperation
        | HubspotSDK::PublicCalendarDatePropertyOperation
        | HubspotSDK::PublicTimePointOperation
        | HubspotSDK::PublicRangedTimeOperation

      module ValueComparison
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::PublicSurveyMonkeyValueFilter::value_comparison]
      end
    end
  end
end
