module HubspotSDK
  module Models
    type public_all_property_types_operation =
      {
        include_objects_with_no_value_set: bool,
        operation_type: HubspotSDK::Models::PublicAllPropertyTypesOperation::operation_type,
        operator: String
      }

    class PublicAllPropertyTypesOperation < HubspotSDK::Internal::Type::BaseModel
      attr_accessor include_objects_with_no_value_set: bool

      attr_accessor operation_type: HubspotSDK::Models::PublicAllPropertyTypesOperation::operation_type

      attr_accessor operator: String

      def initialize: (
        include_objects_with_no_value_set: bool,
        operation_type: HubspotSDK::Models::PublicAllPropertyTypesOperation::operation_type,
        operator: String
      ) -> void

      def to_hash: -> {
        include_objects_with_no_value_set: bool,
        operation_type: HubspotSDK::Models::PublicAllPropertyTypesOperation::operation_type,
        operator: String
      }

      type operation_type = :ALL_PROPERTY

      module OperationType
        extend HubspotSDK::Internal::Type::Enum

        ALL_PROPERTY: :ALL_PROPERTY

        def self?.values: -> ::Array[HubspotSDK::Models::PublicAllPropertyTypesOperation::operation_type]
      end
    end
  end
end
