module HubspotSDK
  module Models
    type public_page_view_analytics_filter =
      {
        filter_type: HubspotSDK::Models::PublicPageViewAnalyticsFilter::filter_type,
        operator: String,
        page_url: String,
        coalescing_refine_by: HubspotSDK::Models::PublicPageViewAnalyticsFilter::coalescing_refine_by,
        enable_tracking: bool,
        pruning_refine_by: HubspotSDK::Models::PublicPageViewAnalyticsFilter::pruning_refine_by
      }

    class PublicPageViewAnalyticsFilter < HubspotSDK::Internal::Type::BaseModel
      attr_accessor filter_type: HubspotSDK::Models::PublicPageViewAnalyticsFilter::filter_type

      attr_accessor operator: String

      attr_accessor page_url: String

      attr_reader coalescing_refine_by: HubspotSDK::Models::PublicPageViewAnalyticsFilter::coalescing_refine_by?

      def coalescing_refine_by=: (
        HubspotSDK::Models::PublicPageViewAnalyticsFilter::coalescing_refine_by
      ) -> HubspotSDK::Models::PublicPageViewAnalyticsFilter::coalescing_refine_by

      attr_reader enable_tracking: bool?

      def enable_tracking=: (bool) -> bool

      attr_reader pruning_refine_by: HubspotSDK::Models::PublicPageViewAnalyticsFilter::pruning_refine_by?

      def pruning_refine_by=: (
        HubspotSDK::Models::PublicPageViewAnalyticsFilter::pruning_refine_by
      ) -> HubspotSDK::Models::PublicPageViewAnalyticsFilter::pruning_refine_by

      def initialize: (
        filter_type: HubspotSDK::Models::PublicPageViewAnalyticsFilter::filter_type,
        operator: String,
        page_url: String,
        ?coalescing_refine_by: HubspotSDK::Models::PublicPageViewAnalyticsFilter::coalescing_refine_by,
        ?enable_tracking: bool,
        ?pruning_refine_by: HubspotSDK::Models::PublicPageViewAnalyticsFilter::pruning_refine_by
      ) -> void

      def to_hash: -> {
        filter_type: HubspotSDK::Models::PublicPageViewAnalyticsFilter::filter_type,
        operator: String,
        page_url: String,
        coalescing_refine_by: HubspotSDK::Models::PublicPageViewAnalyticsFilter::coalescing_refine_by,
        enable_tracking: bool,
        pruning_refine_by: HubspotSDK::Models::PublicPageViewAnalyticsFilter::pruning_refine_by
      }

      type filter_type = :PAGE_VIEW

      module FilterType
        extend HubspotSDK::Internal::Type::Enum

        PAGE_VIEW: :PAGE_VIEW

        def self?.values: -> ::Array[HubspotSDK::Models::PublicPageViewAnalyticsFilter::filter_type]
      end

      type coalescing_refine_by =
        HubspotSDK::PublicNumOccurrencesRefineBy
        | HubspotSDK::PublicSetOccurrencesRefineBy
        | HubspotSDK::PublicRelativeComparativeTimestampRefineBy
        | HubspotSDK::PublicRelativeRangedTimestampRefineBy
        | HubspotSDK::PublicAbsoluteComparativeTimestampRefineBy
        | HubspotSDK::PublicAbsoluteRangedTimestampRefineBy
        | HubspotSDK::PublicAllHistoryRefineBy
        | HubspotSDK::PublicTimePointOperation
        | HubspotSDK::PublicRangedTimeOperation

      module CoalescingRefineBy
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::PublicPageViewAnalyticsFilter::coalescing_refine_by]
      end

      type pruning_refine_by =
        HubspotSDK::PublicNumOccurrencesRefineBy
        | HubspotSDK::PublicSetOccurrencesRefineBy
        | HubspotSDK::PublicRelativeComparativeTimestampRefineBy
        | HubspotSDK::PublicRelativeRangedTimestampRefineBy
        | HubspotSDK::PublicAbsoluteComparativeTimestampRefineBy
        | HubspotSDK::PublicAbsoluteRangedTimestampRefineBy
        | HubspotSDK::PublicAllHistoryRefineBy
        | HubspotSDK::PublicTimePointOperation
        | HubspotSDK::PublicRangedTimeOperation

      module PruningRefineBy
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::PublicPageViewAnalyticsFilter::pruning_refine_by]
      end
    end
  end
end
