module HubspotSDK
  module Models
    type public_or_filter_branch =
      {
        filter_branches: ::Array[HubspotSDK::Models::PublicOrFilterBranch::filter_branch],
        filter_branch_operator: String,
        filter_branch_type: HubspotSDK::Models::PublicOrFilterBranch::filter_branch_type,
        filters: ::Array[HubspotSDK::Models::PublicOrFilterBranch::filter]
      }

    class PublicOrFilterBranch < HubspotSDK::Internal::Type::BaseModel
      attr_accessor filter_branches: ::Array[HubspotSDK::Models::PublicOrFilterBranch::filter_branch]

      attr_accessor filter_branch_operator: String

      attr_accessor filter_branch_type: HubspotSDK::Models::PublicOrFilterBranch::filter_branch_type

      attr_accessor filters: ::Array[HubspotSDK::Models::PublicOrFilterBranch::filter]

      def initialize: (
        filter_branches: ::Array[HubspotSDK::Models::PublicOrFilterBranch::filter_branch],
        filter_branch_operator: String,
        filter_branch_type: HubspotSDK::Models::PublicOrFilterBranch::filter_branch_type,
        filters: ::Array[HubspotSDK::Models::PublicOrFilterBranch::filter]
      ) -> void

      def to_hash: -> {
        filter_branches: ::Array[HubspotSDK::Models::PublicOrFilterBranch::filter_branch],
        filter_branch_operator: String,
        filter_branch_type: HubspotSDK::Models::PublicOrFilterBranch::filter_branch_type,
        filters: ::Array[HubspotSDK::Models::PublicOrFilterBranch::filter]
      }

      type filter_branch =
        HubspotSDK::PublicOrFilterBranch
        | HubspotSDK::PublicAndFilterBranch
        | HubspotSDK::PublicNotAllFilterBranch
        | HubspotSDK::PublicNotAnyFilterBranch
        | HubspotSDK::PublicRestrictedFilterBranch
        | HubspotSDK::PublicUnifiedEventsFilterBranch
        | HubspotSDK::PublicPropertyAssociationFilterBranch
        | HubspotSDK::PublicAssociationFilterBranch

      module FilterBranch
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::PublicOrFilterBranch::filter_branch]
      end

      type filter_branch_type = :OR

      module FilterBranchType
        extend HubspotSDK::Internal::Type::Enum

        OR: :OR

        def self?.values: -> ::Array[HubspotSDK::Models::PublicOrFilterBranch::filter_branch_type]
      end

      type filter =
        HubspotSDK::PublicPropertyFilter
        | HubspotSDK::PublicAssociationInListFilter
        | HubspotSDK::PublicPageViewAnalyticsFilter
        | HubspotSDK::PublicCtaAnalyticsFilter
        | HubspotSDK::PublicEventAnalyticsFilter
        | HubspotSDK::PublicFormSubmissionFilter
        | HubspotSDK::PublicFormSubmissionOnPageFilter
        | HubspotSDK::PublicIntegrationEventFilter
        | HubspotSDK::PublicEmailSubscriptionFilter
        | HubspotSDK::PublicCommunicationSubscriptionFilter
        | HubspotSDK::PublicCampaignInfluencedFilter
        | HubspotSDK::PublicSurveyMonkeyFilter
        | HubspotSDK::PublicSurveyMonkeyValueFilter
        | HubspotSDK::PublicWebinarFilter
        | HubspotSDK::PublicEmailEventFilter
        | HubspotSDK::PublicPrivacyAnalyticsFilter
        | HubspotSDK::PublicAdsSearchFilter
        | HubspotSDK::PublicAdsTimeFilter
        | HubspotSDK::PublicInListFilter
        | HubspotSDK::PublicNumAssociationsFilter
        | HubspotSDK::PublicUnifiedEventsFilter
        | HubspotSDK::PublicPropertyAssociationInListFilter
        | HubspotSDK::PublicConstantFilter

      module Filter
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::PublicOrFilterBranch::filter]
      end
    end
  end
end
