module HubspotSDK
  module Models
    module BusinessUnits
      type business_unit_get_by_user_id_response =
        { results: ::Array[HubspotSDK::Marketing::PublicBusinessUnit] }

      class BusinessUnitGetByUserIDResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubspotSDK::Marketing::PublicBusinessUnit]

        def initialize: (
          results: ::Array[HubspotSDK::Marketing::PublicBusinessUnit]
        ) -> void

        def to_hash: -> {
          results: ::Array[HubspotSDK::Marketing::PublicBusinessUnit]
        }
      end
    end
  end
end
