module HubspotSDK
  module Models
    module BusinessUnits
      type collection_response_public_business_unit_no_paging =
        { results: ::Array[HubspotSDK::BusinessUnits::PublicBusinessUnit] }

      class CollectionResponsePublicBusinessUnitNoPaging < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubspotSDK::BusinessUnits::PublicBusinessUnit]

        def initialize: (
          results: ::Array[HubspotSDK::BusinessUnits::PublicBusinessUnit]
        ) -> void

        def to_hash: -> {
          results: ::Array[HubspotSDK::BusinessUnits::PublicBusinessUnit]
        }
      end
    end
  end
end
