module HubSpotSDK
  module Models
    module BusinessUnits
      type public_business_unit =
        {
          id: String,
          name: String,
          logo_metadata: HubSpotSDK::BusinessUnits::PublicBusinessUnitLogoMetadata
        }

      class PublicBusinessUnit < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String

        attr_reader logo_metadata: HubSpotSDK::BusinessUnits::PublicBusinessUnitLogoMetadata?

        def logo_metadata=: (
          HubSpotSDK::BusinessUnits::PublicBusinessUnitLogoMetadata
        ) -> HubSpotSDK::BusinessUnits::PublicBusinessUnitLogoMetadata

        def initialize: (
          id: String,
          name: String,
          ?logo_metadata: HubSpotSDK::BusinessUnits::PublicBusinessUnitLogoMetadata
        ) -> void

        def to_hash: -> {
          id: String,
          name: String,
          logo_metadata: HubSpotSDK::BusinessUnits::PublicBusinessUnitLogoMetadata
        }
      end
    end
  end
end
