module HubspotSDK
  module Models
    module BusinessUnits
      type public_business_unit_logo_metadata =
        { logo_alt_text: String, logo_url: String, resized_url: String }

      class PublicBusinessUnitLogoMetadata < HubspotSDK::Internal::Type::BaseModel
        attr_reader logo_alt_text: String?

        def logo_alt_text=: (String) -> String

        attr_reader logo_url: String?

        def logo_url=: (String) -> String

        attr_reader resized_url: String?

        def resized_url=: (String) -> String

        def initialize: (
          ?logo_alt_text: String,
          ?logo_url: String,
          ?resized_url: String
        ) -> void

        def to_hash: -> {
          logo_alt_text: String,
          logo_url: String,
          resized_url: String
        }
      end
    end
  end
end
