module HubSpotSDK
  module Resources
    class Automation
      class Actions
        attr_reader callbacks: HubSpotSDK::Resources::Automation::Actions::Callbacks

        attr_reader definitions: HubSpotSDK::Resources::Automation::Actions::Definitions

        attr_reader functions: HubSpotSDK::Resources::Automation::Actions::Functions

        attr_reader revisions: HubSpotSDK::Resources::Automation::Actions::Revisions

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
