module HubspotSDK
  module Resources
    class Automation
      class Sequences
        attr_reader enrollments: HubspotSDK::Resources::Automation::Sequences::Enrollments

        def list: (
          user_id: String,
          ?after: String,
          ?limit: Integer,
          ?name: String,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Internal::Page[HubspotSDK::Automation::PublicSequenceLiteResponse]

        def get: (
          String sequence_id,
          user_id: String,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Automation::PublicSequenceResponse

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
