module HubSpotSDK
  module Resources
    class Automation
      class Sequences
        def list: (
          user_id: String,
          ?after: String,
          ?limit: Integer,
          ?name: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Automation::PublicSequenceLiteResponse]

        def create_enrollment: (
          user_id: String,
          contact_id: String,
          sender_email: String,
          sequence_id: String,
          ?sender_alias_address: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Automation::PublicSequenceEnrollmentLiteResponse

        def get: (
          String sequence_id,
          user_id: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Automation::PublicSequenceResponse

        def get_enrollment_by_contact_id: (
          String contact_id,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Automation::PublicSequenceEnrollmentResponse

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
