module HubspotSDK
  module Resources
    class Crm
      class Objects
        class Quotes
          class Batch
            def create: (
              inputs: ::Array[HubspotSDK::Crm::SimplePublicObjectBatchInputForCreate],
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Crm::BatchResponseSimplePublicObject

            def update: (
              inputs: ::Array[HubspotSDK::Crm::SimplePublicObjectBatchInput],
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Crm::BatchResponseSimplePublicObject

            def delete: (
              inputs: ::Array[HubspotSDK::Crm::SimplePublicObjectID],
              ?request_options: HubspotSDK::request_opts
            ) -> nil

            def get: (
              inputs: ::Array[HubspotSDK::Crm::SimplePublicObjectID],
              properties: ::Array[String],
              properties_with_history: ::Array[String],
              ?archived: bool,
              ?id_property: String,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Crm::BatchResponseSimplePublicObject

            def upsert: (
              inputs: ::Array[HubspotSDK::Crm::SimplePublicObjectBatchInputUpsert],
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Crm::BatchResponseSimplePublicUpsertObject

            def initialize: (client: HubspotSDK::Client) -> void
          end
        end
      end
    end
  end
end
