module HubspotSDK
  module Resources
    class CRM
      class FeatureFlags
        class Apps
          def update: (
            String flag_name,
            app_id: Integer,
            default_state: HubspotSDK::Models::CRM::FlagPutRequest::default_state,
            ?override_state: HubspotSDK::Models::CRM::FlagPutRequest::override_state,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::CRM::FlagResponse

          def delete: (
            String flag_name,
            app_id: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::CRM::FlagResponse

          def get: (
            String flag_name,
            app_id: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::CRM::FlagResponse

          def list_portals: (
            String flag_name,
            app_id: Integer,
            ?limit: Integer,
            ?start_portal_id: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::CRM::PortalFlagStateBatchResponse

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
