module HubSpotSDK
  module Resources
    class Crm
      class FeatureFlags
        class Batch
          def delete: (
            String flag_name,
            app_id: Integer,
            portal_ids: ::Array[Integer],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::PortalFlagStateBatchResponse

          def upsert: (
            String flag_name,
            app_id: Integer,
            portal_states: ::Array[HubSpotSDK::Crm::BatchPortalEntry],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::PortalFlagStateBatchResponse

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
