module HubspotSDK
  module Models
    module DataStudio
      type datasource_update_params =
        { datasource_id: Integer }
        & HubspotSDK::Internal::Type::request_parameters

      class DatasourceUpdateParams < HubspotSDK::Models::DataStudio::FormDataMultiPart
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        def datasource_id: -> Integer

        def datasource_id=: (Integer _) -> Integer

        def initialize: (
          datasource_id: Integer,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          datasource_id: Integer,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
