module HubspotSDK
  module Models
    module DataStudio
      type data_source_update_response =
        {
          datasource_id: Integer,
          datasource_name: String,
          preview_link: String
        }

      class DataSourceUpdateResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor datasource_id: Integer

        attr_accessor datasource_name: String

        attr_accessor preview_link: String

        def initialize: (
          datasource_id: Integer,
          datasource_name: String,
          preview_link: String
        ) -> void

        def to_hash: -> {
          datasource_id: Integer,
          datasource_name: String,
          preview_link: String
        }
      end
    end
  end
end
