module HubspotSDK
  module Models
    module DataStudio
      type datasource_create_params =
        {  } & HubspotSDK::Internal::Type::request_parameters

      class DatasourceCreateParams < HubspotSDK::Models::DataStudio::FormDataMultiPart
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        def initialize: (?request_options: HubspotSDK::request_opts) -> void

        def to_hash: -> { request_options: HubspotSDK::RequestOptions }
      end
    end
  end
end
