module HubspotSDK
  module Models
    module DataStudio
      type data_source_get_response =
        {
          columns: ::Array[HubspotSDK::DataStudio::FileColumn],
          created_at: String,
          datasource_id: Integer,
          datasource_name: String,
          datasource_type: HubspotSDK::Models::DataStudio::DataSourceGetResponse::datasource_type,
          last_ingestion_status: HubspotSDK::Models::DataStudio::DataSourceGetResponse::last_ingestion_status
        }

      class DataSourceGetResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor columns: ::Array[HubspotSDK::DataStudio::FileColumn]

        attr_accessor created_at: String

        attr_accessor datasource_id: Integer

        attr_accessor datasource_name: String

        attr_accessor datasource_type: HubspotSDK::Models::DataStudio::DataSourceGetResponse::datasource_type

        attr_accessor last_ingestion_status: HubspotSDK::Models::DataStudio::DataSourceGetResponse::last_ingestion_status

        def initialize: (
          columns: ::Array[HubspotSDK::DataStudio::FileColumn],
          created_at: String,
          datasource_id: Integer,
          datasource_name: String,
          datasource_type: HubspotSDK::Models::DataStudio::DataSourceGetResponse::datasource_type,
          last_ingestion_status: HubspotSDK::Models::DataStudio::DataSourceGetResponse::last_ingestion_status
        ) -> void

        def to_hash: -> {
          columns: ::Array[HubspotSDK::DataStudio::FileColumn],
          created_at: String,
          datasource_id: Integer,
          datasource_name: String,
          datasource_type: HubspotSDK::Models::DataStudio::DataSourceGetResponse::datasource_type,
          last_ingestion_status: HubspotSDK::Models::DataStudio::DataSourceGetResponse::last_ingestion_status
        }

        type datasource_type = :FILE

        module DatasourceType
          extend HubspotSDK::Internal::Type::Enum

          FILE: :FILE

          def self?.values: -> ::Array[HubspotSDK::Models::DataStudio::DataSourceGetResponse::datasource_type]
        end

        type last_ingestion_status = :FAILED | :IN_PROGRESS | :SUCCESSFUL

        module LastIngestionStatus
          extend HubspotSDK::Internal::Type::Enum

          FAILED: :FAILED
          IN_PROGRESS: :IN_PROGRESS
          SUCCESSFUL: :SUCCESSFUL

          def self?.values: -> ::Array[HubspotSDK::Models::DataStudio::DataSourceGetResponse::last_ingestion_status]
        end
      end
    end
  end
end
