module HubspotSDK
  module Models
    module DataStudio
      type file_column = { name: String, type: String }

      class FileColumn < HubspotSDK::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor type: String

        def initialize: (name: String, type: String) -> void

        def to_hash: -> { name: String, type: String }
      end
    end
  end
end
