module HubspotSDK
  module Models
    module DataStudio
      type form_data_content_disposition =
        {
          creation_date: Time,
          file_name: String,
          modification_date: Time,
          name: String,
          parameters: ::Hash[Symbol, String],
          read_date: Time,
          size: Integer,
          type: String
        }

      class FormDataContentDisposition < HubspotSDK::Internal::Type::BaseModel
        attr_accessor creation_date: Time

        attr_accessor file_name: String

        attr_accessor modification_date: Time

        attr_accessor name: String

        attr_accessor parameters: ::Hash[Symbol, String]

        attr_accessor read_date: Time

        attr_accessor size: Integer

        attr_accessor type: String

        def initialize: (
          creation_date: Time,
          file_name: String,
          modification_date: Time,
          name: String,
          parameters: ::Hash[Symbol, String],
          read_date: Time,
          size: Integer,
          type: String
        ) -> void

        def to_hash: -> {
          creation_date: Time,
          file_name: String,
          modification_date: Time,
          name: String,
          parameters: ::Hash[Symbol, String],
          read_date: Time,
          size: Integer,
          type: String
        }
      end
    end
  end
end
