module HubSpotSDK
  module Models
    module Crm
      module Objects
        module GoalTargets
          type batch_upsert_params =
            {  } & HubSpotSDK::Internal::Type::request_parameters

          class BatchUpsertParams < HubSpotSDK::Models::Crm::BatchInputSimplePublicObjectBatchInputUpsert
            extend HubSpotSDK::Internal::Type::RequestParameters::Converter
            include HubSpotSDK::Internal::Type::RequestParameters

            def initialize: (?request_options: HubSpotSDK::request_opts) -> void

            def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
          end
        end
      end
    end
  end
end
