module HubSpotSDK
  module Models
    module Settings
      module Currencies
        module ExchangeRates
          type batch_get_params =
            {  } & HubSpotSDK::Internal::Type::request_parameters

          class BatchGetParams < HubSpotSDK::Models::BatchInputPublicObjectID
            extend HubSpotSDK::Internal::Type::RequestParameters::Converter
            include HubSpotSDK::Internal::Type::RequestParameters

            def initialize: (?request_options: HubSpotSDK::request_opts) -> void

            def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
          end
        end
      end
    end
  end
end
