module HubspotSDK
  module Models
    module Settings
      type batch_input_exchange_rate_create_request =
        { inputs: ::Array[HubspotSDK::Settings::ExchangeRateCreateRequest] }

      class BatchInputExchangeRateCreateRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubspotSDK::Settings::ExchangeRateCreateRequest]

        def initialize: (
          inputs: ::Array[HubspotSDK::Settings::ExchangeRateCreateRequest]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubspotSDK::Settings::ExchangeRateCreateRequest]
        }
      end
    end
  end
end
