module HubSpotSDK
  module Models
    module Settings
      type collection_response_exchange_rate_no_paging =
        { results: ::Array[HubSpotSDK::Settings::ExchangeRate] }

      class CollectionResponseExchangeRateNoPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Settings::ExchangeRate]

        def initialize: (
          results: ::Array[HubSpotSDK::Settings::ExchangeRate]
        ) -> void

        def to_hash: -> { results: ::Array[HubSpotSDK::Settings::ExchangeRate] }
      end
    end
  end
end
