module HubSpotSDK
  module Models
    module Settings
      type collection_response_exchange_rate_forward_paging =
        {
          results: ::Array[HubSpotSDK::Settings::ExchangeRate],
          paging: HubSpotSDK::ForwardPaging
        }

      class CollectionResponseExchangeRateForwardPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Settings::ExchangeRate]

        attr_reader paging: HubSpotSDK::ForwardPaging?

        def paging=: (HubSpotSDK::ForwardPaging) -> HubSpotSDK::ForwardPaging

        def initialize: (
          results: ::Array[HubSpotSDK::Settings::ExchangeRate],
          ?paging: HubSpotSDK::ForwardPaging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Settings::ExchangeRate],
          paging: HubSpotSDK::ForwardPaging
        }
      end
    end
  end
end
