module HubSpotSDK
  module Models
    module Settings
      type company_currency = { id: String, created_at: Time }

      class CompanyCurrency < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        def initialize: (id: String, created_at: Time) -> void

        def to_hash: -> { id: String, created_at: Time }
      end
    end
  end
end
