module HubSpotSDK
  module Models
    module Settings
      type exchange_rate_update_request =
        { id: String, conversion_rate: Float, effective_at: Time }

      class ExchangeRateUpdateRequest < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor conversion_rate: Float

        attr_reader effective_at: Time?

        def effective_at=: (Time) -> Time

        def initialize: (
          id: String,
          conversion_rate: Float,
          ?effective_at: Time
        ) -> void

        def to_hash: -> {
          id: String,
          conversion_rate: Float,
          effective_at: Time
        }
      end
    end
  end
end
