module HubSpotSDK
  module Models
    module Settings
      type public_tax_rate_group =
        {
          id: String,
          active: bool,
          created_at: Time,
          label: String,
          name: String,
          percentage_rate: Float,
          updated_at: Time
        }

      class PublicTaxRateGroup < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor active: bool

        attr_accessor created_at: Time

        attr_accessor label: String

        attr_accessor name: String

        attr_accessor percentage_rate: Float

        attr_accessor updated_at: Time

        def initialize: (
          id: String,
          active: bool,
          created_at: Time,
          label: String,
          name: String,
          percentage_rate: Float,
          updated_at: Time
        ) -> void

        def to_hash: -> {
          id: String,
          active: bool,
          created_at: Time,
          label: String,
          name: String,
          percentage_rate: Float,
          updated_at: Time
        }
      end
    end
  end
end
