module HubspotSDK
  module Models
    module Settings
      type public_user_update =
        {
          first_name: String,
          last_name: String,
          primary_team_id: String,
          role_id: String,
          secondary_team_ids: ::Array[String]
        }

      class PublicUserUpdate < HubspotSDK::Internal::Type::BaseModel
        attr_reader first_name: String?

        def first_name=: (String) -> String

        attr_reader last_name: String?

        def last_name=: (String) -> String

        attr_reader primary_team_id: String?

        def primary_team_id=: (String) -> String

        attr_reader role_id: String?

        def role_id=: (String) -> String

        attr_reader secondary_team_ids: ::Array[String]?

        def secondary_team_ids=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?first_name: String,
          ?last_name: String,
          ?primary_team_id: String,
          ?role_id: String,
          ?secondary_team_ids: ::Array[String]
        ) -> void

        def to_hash: -> {
          first_name: String,
          last_name: String,
          primary_team_id: String,
          role_id: String,
          secondary_team_ids: ::Array[String]
        }
      end
    end
  end
end
