module HubspotSDK
  module Models
    module Settings
      type user_list_roles_params =
        {  } & HubspotSDK::Internal::Type::request_parameters

      class UserListRolesParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        def initialize: (?request_options: HubspotSDK::request_opts) -> void

        def to_hash: -> { request_options: HubspotSDK::RequestOptions }
      end
    end
  end
end
