module HubSpotSDK
  module Models
    module Settings
      type user_list_roles_params =
        {  } & HubSpotSDK::Internal::Type::request_parameters

      class UserListRolesParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        def initialize: (?request_options: HubSpotSDK::request_opts) -> void

        def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
      end
    end
  end
end
