module HubSpotSDK
  module Models
    module Settings
      type user_delete_params =
        {
          user_id: String,
          id_property: HubSpotSDK::Models::Settings::UserDeleteParams::id_property
        }
        & HubSpotSDK::Internal::Type::request_parameters

      class UserDeleteParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor user_id: String

        attr_reader id_property: HubSpotSDK::Models::Settings::UserDeleteParams::id_property?

        def id_property=: (
          HubSpotSDK::Models::Settings::UserDeleteParams::id_property
        ) -> HubSpotSDK::Models::Settings::UserDeleteParams::id_property

        def initialize: (
          user_id: String,
          ?id_property: HubSpotSDK::Models::Settings::UserDeleteParams::id_property,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          user_id: String,
          id_property: HubSpotSDK::Models::Settings::UserDeleteParams::id_property,
          request_options: HubSpotSDK::RequestOptions
        }

        type id_property = :EMAIL | :USER_ID

        module IDProperty
          extend HubSpotSDK::Internal::Type::Enum

          EMAIL: :EMAIL
          USER_ID: :USER_ID

          def self?.values: -> ::Array[HubSpotSDK::Models::Settings::UserDeleteParams::id_property]
        end
      end
    end
  end
end
