module HubspotSDK
  module Models
    module Settings
      type user_delete_params =
        {
          id_property: HubspotSDK::Models::Settings::UserDeleteParams::id_property
        }
        & HubspotSDK::Internal::Type::request_parameters

      class UserDeleteParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_reader id_property: HubspotSDK::Models::Settings::UserDeleteParams::id_property?

        def id_property=: (
          HubspotSDK::Models::Settings::UserDeleteParams::id_property
        ) -> HubspotSDK::Models::Settings::UserDeleteParams::id_property

        def initialize: (
          ?id_property: HubspotSDK::Models::Settings::UserDeleteParams::id_property,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          id_property: HubspotSDK::Models::Settings::UserDeleteParams::id_property,
          request_options: HubspotSDK::RequestOptions
        }

        type id_property = :EMAIL | :USER_ID

        module IDProperty
          extend HubspotSDK::Internal::Type::Enum

          EMAIL: :EMAIL
          USER_ID: :USER_ID

          def self?.values: -> ::Array[HubspotSDK::Models::Settings::UserDeleteParams::id_property]
        end
      end
    end
  end
end
