# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "hubspot_sdk/version"
require_relative "hubspot_sdk/internal/util"
require_relative "hubspot_sdk/internal/type/converter"
require_relative "hubspot_sdk/internal/type/unknown"
require_relative "hubspot_sdk/internal/type/boolean"
require_relative "hubspot_sdk/internal/type/file_input"
require_relative "hubspot_sdk/internal/type/enum"
require_relative "hubspot_sdk/internal/type/union"
require_relative "hubspot_sdk/internal/type/array_of"
require_relative "hubspot_sdk/internal/type/hash_of"
require_relative "hubspot_sdk/internal/type/base_model"
require_relative "hubspot_sdk/internal/type/base_page"
require_relative "hubspot_sdk/internal/type/request_parameters"
require_relative "hubspot_sdk/internal"
require_relative "hubspot_sdk/request_options"
require_relative "hubspot_sdk/file_part"
require_relative "hubspot_sdk/errors"
require_relative "hubspot_sdk/internal/transport/base_client"
require_relative "hubspot_sdk/internal/transport/pooled_net_requester"
require_relative "hubspot_sdk/client"
require_relative "hubspot_sdk/internal/page"
require_relative "hubspot_sdk/models/crm/simple_public_object_input_for_create"
require_relative "hubspot_sdk/models/crm/public_gdpr_delete_input"
require_relative "hubspot_sdk/models/crm/public_merge_input"
require_relative "hubspot_sdk/models/crm/public_object_search_request"
require_relative "hubspot_sdk/models/crm/simple_public_object_input"
require_relative "hubspot_sdk/models/crm/batch_input_simple_public_object_batch_input_for_create"
require_relative "hubspot_sdk/models/crm/batch_input_simple_public_object_id"
require_relative "hubspot_sdk/models/crm/batch_read_input_simple_public_object_id"
require_relative "hubspot_sdk/models/crm/batch_input_simple_public_object_batch_input"
require_relative "hubspot_sdk/models/crm/batch_input_simple_public_object_batch_input_upsert"
require_relative "hubspot_sdk/models/account/acting_user"
require_relative "hubspot_sdk/models/account/activity_list_audit_logs_params"
require_relative "hubspot_sdk/models/account/activity_list_login_activities_params"
require_relative "hubspot_sdk/models/account/activity_list_security_activities_params"
require_relative "hubspot_sdk/models/account/api_usage"
require_relative "hubspot_sdk/models/account/collection_response_api_usage_no_paging"
require_relative "hubspot_sdk/models/account/collection_response_hydrated_critical_action_forward_paging"
require_relative "hubspot_sdk/models/account/collection_response_public_api_user_action_event_forward_paging"
require_relative "hubspot_sdk/models/account/collection_response_public_login_audit_forward_paging"
require_relative "hubspot_sdk/models/account/hydrated_critical_action"
require_relative "hubspot_sdk/models/account/portal_information_response"
require_relative "hubspot_sdk/models/account/public_api_user_action_event"
require_relative "hubspot_sdk/models/account/public_login_audit"
require_relative "hubspot_sdk/models/crm/associated_id"
require_relative "hubspot_sdk/models/crm/association_spec"
require_relative "hubspot_sdk/models/crm/association_spec_with_label"
require_relative "hubspot_sdk/models/crm/batch_response_public_default_association"
require_relative "hubspot_sdk/models/crm/batch_response_simple_public_object"
require_relative "hubspot_sdk/models/crm/batch_response_simple_public_upsert_object"
require_relative "hubspot_sdk/models/crm/collection_response_associated_id"
require_relative "hubspot_sdk/models/crm/collection_response_multi_associated_object_with_label_forward_paging"
require_relative "hubspot_sdk/models/crm/collection_response_simple_public_object_with_associations_forward_paging"
require_relative "hubspot_sdk/models/crm/collection_response_with_total_simple_public_object"
require_relative "hubspot_sdk/models/crm/filter"
require_relative "hubspot_sdk/models/crm/filter_group"
require_relative "hubspot_sdk/models/crm/labels_between_object_pair"
require_relative "hubspot_sdk/models/crm/multi_associated_object_with_label"
require_relative "hubspot_sdk/models/crm/objects/contact_create_params"
require_relative "hubspot_sdk/models/crm/objects/contact_delete_params"
require_relative "hubspot_sdk/models/crm/objects/contact_gdpr_delete_params"
require_relative "hubspot_sdk/models/crm/objects/contact_get_params"
require_relative "hubspot_sdk/models/crm/objects/contact_list_params"
require_relative "hubspot_sdk/models/crm/objects/contact_merge_params"
require_relative "hubspot_sdk/models/crm/objects/contact_search_params"
require_relative "hubspot_sdk/models/crm/objects/contact_update_params"
require_relative "hubspot_sdk/models/crm/objects/custom_create_params"
require_relative "hubspot_sdk/models/crm/objects/custom_delete_params"
require_relative "hubspot_sdk/models/crm/objects/custom_get_params"
require_relative "hubspot_sdk/models/crm/objects/custom_list_params"
require_relative "hubspot_sdk/models/crm/objects/custom_merge_params"
require_relative "hubspot_sdk/models/crm/objects/custom_search_params"
require_relative "hubspot_sdk/models/crm/objects/custom_update_params"
require_relative "hubspot_sdk/models/crm/objects/custom_upsert_params"
require_relative "hubspot_sdk/models/crm/objects/task_delete_params"
require_relative "hubspot_sdk/models/crm/objects/tasks/batch_create_params"
require_relative "hubspot_sdk/models/crm/objects/tasks/batch_delete_params"
require_relative "hubspot_sdk/models/crm/objects/tasks/batch_get_params"
require_relative "hubspot_sdk/models/crm/objects/tasks/batch_update_params"
require_relative "hubspot_sdk/models/crm/objects/tasks/batch_upsert_params"
require_relative "hubspot_sdk/models/crm/paging"
require_relative "hubspot_sdk/models/crm/previous_page"
require_relative "hubspot_sdk/models/crm/public_associations_for_object"
require_relative "hubspot_sdk/models/crm/public_default_association"
require_relative "hubspot_sdk/models/crm/public_object_id"
require_relative "hubspot_sdk/models/crm/simple_public_object"
require_relative "hubspot_sdk/models/crm/simple_public_object_batch_input"
require_relative "hubspot_sdk/models/crm/simple_public_object_batch_input_for_create"
require_relative "hubspot_sdk/models/crm/simple_public_object_batch_input_upsert"
require_relative "hubspot_sdk/models/crm/simple_public_object_id"
require_relative "hubspot_sdk/models/crm/simple_public_object_with_associations"
require_relative "hubspot_sdk/models/crm/simple_public_upsert_object"
require_relative "hubspot_sdk/models/crm/standard_error"
require_relative "hubspot_sdk/models/crm/value_with_timestamp"
require_relative "hubspot_sdk/models/error"
require_relative "hubspot_sdk/models/error_detail"
require_relative "hubspot_sdk/models/forward_paging"
require_relative "hubspot_sdk/models/next_page"
require_relative "hubspot_sdk/models"
require_relative "hubspot_sdk/resources/account"
require_relative "hubspot_sdk/resources/account/activity"
require_relative "hubspot_sdk/resources/crm"
require_relative "hubspot_sdk/resources/crm/objects"
require_relative "hubspot_sdk/resources/crm/objects/contacts"
require_relative "hubspot_sdk/resources/crm/objects/custom"
require_relative "hubspot_sdk/resources/crm/objects/tasks"
require_relative "hubspot_sdk/resources/crm/objects/tasks/batch"
