module HubspotSDK
  module Models
    module CRM
      module FeatureFlags
        type portal_batch_delete_response =
          {
            portal_flag_states: ::Array[HubspotSDK::Models::CRM::FeatureFlags::PortalBatchDeleteResponse::PortalFlagState]
          }

        class PortalBatchDeleteResponse < HubspotSDK::Internal::Type::BaseModel
          attr_accessor portal_flag_states: ::Array[HubspotSDK::Models::CRM::FeatureFlags::PortalBatchDeleteResponse::PortalFlagState]

          def initialize: (
            portal_flag_states: ::Array[HubspotSDK::Models::CRM::FeatureFlags::PortalBatchDeleteResponse::PortalFlagState]
          ) -> void

          def to_hash: -> {
            portal_flag_states: ::Array[HubspotSDK::Models::CRM::FeatureFlags::PortalBatchDeleteResponse::PortalFlagState]
          }

          type portal_flag_state =
            {
              app_id: Integer,
              flag_name: String,
              flag_state: HubspotSDK::Models::CRM::FeatureFlags::PortalBatchDeleteResponse::PortalFlagState::flag_state,
              portal_id: Integer
            }

          class PortalFlagState < HubspotSDK::Internal::Type::BaseModel
            attr_accessor app_id: Integer

            attr_accessor flag_name: String

            attr_accessor flag_state: HubspotSDK::Models::CRM::FeatureFlags::PortalBatchDeleteResponse::PortalFlagState::flag_state

            attr_accessor portal_id: Integer

            def initialize: (
              app_id: Integer,
              flag_name: String,
              flag_state: HubspotSDK::Models::CRM::FeatureFlags::PortalBatchDeleteResponse::PortalFlagState::flag_state,
              portal_id: Integer
            ) -> void

            def to_hash: -> {
              app_id: Integer,
              flag_name: String,
              flag_state: HubspotSDK::Models::CRM::FeatureFlags::PortalBatchDeleteResponse::PortalFlagState::flag_state,
              portal_id: Integer
            }

            type flag_state = :OFF | :ON | :ABSENT

            module FlagState
              extend HubspotSDK::Internal::Type::Enum

              OFF: :OFF
              ON: :ON
              ABSENT: :ABSENT

              def self?.values: -> ::Array[HubspotSDK::Models::CRM::FeatureFlags::PortalBatchDeleteResponse::PortalFlagState::flag_state]
            end
          end
        end
      end
    end
  end
end
