module HubspotSDK
  module Resources
    class Crm
      class Extensions
        class VideoConferencing
          class Settings
            def update: (
              Integer app_id,
              create_meeting_url: String,
              ?delete_meeting_url: String,
              ?fetch_accounts_uri: String,
              ?update_meeting_url: String,
              ?user_verify_url: String,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Crm::Extensions::ExternalSettings

            def delete: (
              Integer app_id,
              ?request_options: HubspotSDK::request_opts
            ) -> nil

            def get: (
              Integer app_id,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Crm::Extensions::ExternalSettings

            def initialize: (client: HubspotSDK::Client) -> void
          end
        end
      end
    end
  end
end
