# frozen_string_literal: true

module HubSpotSDK
  module Models
    module Marketing
      class MetricsCounters < HubSpotSDK::Internal::Type::BaseModel
        # @!attribute influenced_contacts
        #   The number of contacts influenced by the campaign.
        #
        #   @return [Integer]
        required :influenced_contacts, Integer, api_name: :influencedContacts

        # @!attribute new_contacts_first_touch
        #   The number of new contacts attributed to the campaign as the first touchpoint.
        #
        #   @return [Integer]
        required :new_contacts_first_touch, Integer, api_name: :newContactsFirstTouch

        # @!attribute new_contacts_last_touch
        #   The number of new contacts attributed to the campaign as the last touchpoint.
        #
        #   @return [Integer]
        required :new_contacts_last_touch, Integer, api_name: :newContactsLastTouch

        # @!attribute sessions
        #   The total number of sessions generated by the campaign.
        #
        #   @return [Integer]
        required :sessions, Integer

        # @!method initialize(influenced_contacts:, new_contacts_first_touch:, new_contacts_last_touch:, sessions:)
        #   @param influenced_contacts [Integer] The number of contacts influenced by the campaign.
        #
        #   @param new_contacts_first_touch [Integer] The number of new contacts attributed to the campaign as the first touchpoint.
        #
        #   @param new_contacts_last_touch [Integer] The number of new contacts attributed to the campaign as the last touchpoint.
        #
        #   @param sessions [Integer] The total number of sessions generated by the campaign.
      end
    end
  end
end
