module HubspotSDK
  module Models
    module CRM
      module Associations
        module Schema
          module V4
            type configuration_batch_update_by_object_types_params =
              { from_object_type: String }
              & HubspotSDK::Internal::Type::request_parameters

            class ConfigurationBatchUpdateByObjectTypesParams < HubspotSDK::Models::CRM::Associations::Schema::BatchInputPublicAssociationDefinitionConfigurationUpdateRequest
              extend HubspotSDK::Internal::Type::RequestParameters::Converter
              include HubspotSDK::Internal::Type::RequestParameters

              def from_object_type: -> String

              def from_object_type=: (String _) -> String

              def initialize: (
                from_object_type: String,
                ?request_options: HubspotSDK::request_opts
              ) -> void

              def to_hash: -> {
                from_object_type: String,
                request_options: HubspotSDK::RequestOptions
              }
            end
          end
        end
      end
    end
  end
end
