module HubSpotSDK
  module Resources
    class Account
      class Activity
        def list_audit_logs: (
          ?acting_user_id: ::Array[Integer],
          ?after: String,
          ?fill_final_timestamp: bool,
          ?limit: Integer,
          ?occurred_after: Time,
          ?occurred_before: Time,
          ?sort: ::Array[String],
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Account::PublicAPIUserActionEvent]

        def list_login_activities: (
          ?after: String,
          ?limit: Integer,
          ?user_id: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Account::PublicLoginAudit]

        def list_security_activities: (
          ?after: String,
          ?from_timestamp: Integer,
          ?limit: Integer,
          ?to_timestamp: Integer,
          ?user_id: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Account::HydratedCriticalAction]

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
