module HubspotSDK
  module Models
    module Marketing
      module Events
        type event_complete_by_external_event_id_params =
          { external_event_id: String, external_account_id: String }
          & HubspotSDK::Internal::Type::request_parameters

        class EventCompleteByExternalEventIDParams < HubspotSDK::Models::Marketing::MarketingEventCompleteRequestParams
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          def external_event_id: -> String

          def external_event_id=: (String _) -> String

          def external_account_id: -> String

          def external_account_id=: (String _) -> String

          def initialize: (
            external_event_id: String,
            external_account_id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            external_event_id: String,
            external_account_id: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
