module HubspotSDK
  module Models
    module Cms
      type ab_test_rerun_request_v_next =
        { ab_test_id: String, variation_id: String }

      class AbTestRerunRequestVNext < HubspotSDK::Internal::Type::BaseModel
        attr_accessor ab_test_id: String

        attr_accessor variation_id: String

        def initialize: (ab_test_id: String, variation_id: String) -> void

        def to_hash: -> { ab_test_id: String, variation_id: String }
      end
    end
  end
end
