module HubspotSDK
  module Models
    module Cms
      type ab_test_end_request_v_next =
        { ab_test_id: String, winner_id: String }

      class AbTestEndRequestVNext < HubspotSDK::Internal::Type::BaseModel
        attr_accessor ab_test_id: String

        attr_accessor winner_id: String

        def initialize: (ab_test_id: String, winner_id: String) -> void

        def to_hash: -> { ab_test_id: String, winner_id: String }
      end
    end
  end
end
