module HubSpotSDK
  module Models
    module Cms
      type angle =
        { units: HubSpotSDK::Models::Cms::Angle::units, value: Float }

      class Angle < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor units: HubSpotSDK::Models::Cms::Angle::units

        attr_accessor value: Float

        def initialize: (
          units: HubSpotSDK::Models::Cms::Angle::units,
          value: Float
        ) -> void

        def to_hash: -> {
          units: HubSpotSDK::Models::Cms::Angle::units,
          value: Float
        }

        type units = :DEGREES | :GRADIANS | :RADIANS | :TURNS

        module Units
          extend HubSpotSDK::Internal::Type::Enum

          DEGREES: :DEGREES
          GRADIANS: :GRADIANS
          RADIANS: :RADIANS
          TURNS: :TURNS

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::Angle::units]
        end
      end
    end
  end
end
