module HubSpotSDK
  module Models
    module Cms
      type angle =
        { units: HubSpotSDK::Models::Cms::Angle::units, value: Float }

      class Angle < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor units: HubSpotSDK::Models::Cms::Angle::units

        attr_accessor value: Float

        def initialize: (
          units: HubSpotSDK::Models::Cms::Angle::units,
          value: Float
        ) -> void

        def to_hash: -> {
          units: HubSpotSDK::Models::Cms::Angle::units,
          value: Float
        }

        type units = :deg | :grad | :rad | :turn

        module Units
          extend HubSpotSDK::Internal::Type::Enum

          DEG: :deg
          GRAD: :grad
          RAD: :rad
          TURN: :turn

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::Angle::units]
        end
      end
    end
  end
end
