module HubspotSDK
  module Models
    module Cms
      type asset_file_metadata =
        {
          id: String,
          created_at: Integer,
          folder: bool,
          name: String,
          updated_at: Integer,
          archived_at: Integer,
          children: ::Array[String],
          hash_: String
        }

      class AssetFileMetadata < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Integer

        attr_accessor folder: bool

        attr_accessor name: String

        attr_accessor updated_at: Integer

        attr_reader archived_at: Integer?

        def archived_at=: (Integer) -> Integer

        attr_reader children: ::Array[String]?

        def children=: (::Array[String]) -> ::Array[String]

        attr_reader hash_: String?

        def hash_=: (String) -> String

        def initialize: (
          id: String,
          created_at: Integer,
          folder: bool,
          name: String,
          updated_at: Integer,
          ?archived_at: Integer,
          ?children: ::Array[String],
          ?hash_: String
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Integer,
          folder: bool,
          name: String,
          updated_at: Integer,
          archived_at: Integer,
          children: ::Array[String],
          hash_: String
        }
      end
    end
  end
end
