module HubspotSDK
  module Models
    module Cms
      type attach_to_lang_primary_request_v_next =
        {
          id: String,
          language: String,
          primary_id: String,
          primary_language: String
        }

      class AttachToLangPrimaryRequestVNext < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor language: String

        attr_accessor primary_id: String

        attr_reader primary_language: String?

        def primary_language=: (String) -> String

        def initialize: (
          id: String,
          language: String,
          primary_id: String,
          ?primary_language: String
        ) -> void

        def to_hash: -> {
          id: String,
          language: String,
          primary_id: String,
          primary_language: String
        }
      end
    end
  end
end
