module HubSpotSDK
  module Models
    module Cms
      type attention_span_calculated_values =
        { total_percent_played: Float, total_seconds_played: Integer }

      class AttentionSpanCalculatedValues < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor total_percent_played: Float

        attr_accessor total_seconds_played: Integer

        def initialize: (
          total_percent_played: Float,
          total_seconds_played: Integer
        ) -> void

        def to_hash: -> {
          total_percent_played: Float,
          total_seconds_played: Integer
        }
      end
    end
  end
end
