module HubspotSDK
  module Models
    module Cms
      type audit_log_list_params =
        {
          after: String,
          before: String,
          event_type: ::Array[String],
          limit: Integer,
          object_id_: ::Array[String],
          object_type: ::Array[String],
          sort: ::Array[String],
          user_id: ::Array[String]
        }
        & HubspotSDK::Internal::Type::request_parameters

      class AuditLogListParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_reader after: String?

        def after=: (String) -> String

        attr_reader before: String?

        def before=: (String) -> String

        attr_reader event_type: ::Array[String]?

        def event_type=: (::Array[String]) -> ::Array[String]

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader object_id_: ::Array[String]?

        def object_id_=: (::Array[String]) -> ::Array[String]

        attr_reader object_type: ::Array[String]?

        def object_type=: (::Array[String]) -> ::Array[String]

        attr_reader sort: ::Array[String]?

        def sort=: (::Array[String]) -> ::Array[String]

        attr_reader user_id: ::Array[String]?

        def user_id=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?after: String,
          ?before: String,
          ?event_type: ::Array[String],
          ?limit: Integer,
          ?object_id_: ::Array[String],
          ?object_type: ::Array[String],
          ?sort: ::Array[String],
          ?user_id: ::Array[String],
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          after: String,
          before: String,
          event_type: ::Array[String],
          limit: Integer,
          object_id_: ::Array[String],
          object_type: ::Array[String],
          sort: ::Array[String],
          user_id: ::Array[String],
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
