module HubspotSDK
  module Models
    module Cms
      type batch_input_page = { inputs: ::Array[HubspotSDK::Cms::Page] }

      class BatchInputPage < HubspotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubspotSDK::Cms::Page]

        def initialize: (inputs: ::Array[HubspotSDK::Cms::Page]) -> void

        def to_hash: -> { inputs: ::Array[HubspotSDK::Cms::Page] }
      end
    end
  end
end
