module HubSpotSDK
  module Models
    module Cms
      type batch_input_hub_db_table_row_batch_clone_request =
        { inputs: ::Array[HubSpotSDK::Cms::HubDBTableRowBatchCloneRequest] }

      class BatchInputHubDBTableRowBatchCloneRequest < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubSpotSDK::Cms::HubDBTableRowBatchCloneRequest]

        def initialize: (
          inputs: ::Array[HubSpotSDK::Cms::HubDBTableRowBatchCloneRequest]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubSpotSDK::Cms::HubDBTableRowBatchCloneRequest]
        }
      end
    end
  end
end
