module HubspotSDK
  module Models
    module Cms
      type begins_with =
        {
          operator: HubspotSDK::Models::Cms::BeginsWith::operator,
          string_to_check: ::Hash[Symbol, top],
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: bool
        }

      class BeginsWith < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::BeginsWith::operator

        attr_accessor string_to_check: ::Hash[Symbol, top]

        attr_reader inputs: ::Array[::Hash[Symbol, top]]?

        def inputs=: (
          ::Array[::Hash[Symbol, top]]
        ) -> ::Array[::Hash[Symbol, top]]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: bool?

        def value=: (bool) -> bool

        def initialize: (
          operator: HubspotSDK::Models::Cms::BeginsWith::operator,
          string_to_check: ::Hash[Symbol, top],
          ?inputs: ::Array[::Hash[Symbol, top]],
          ?property_name: String,
          ?value: bool
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::BeginsWith::operator,
          string_to_check: ::Hash[Symbol, top],
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: bool
        }

        type operator = :BEGINS_WITH

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          BEGINS_WITH: :BEGINS_WITH

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::BeginsWith::operator]
        end
      end
    end
  end
end
