module HubSpotSDK
  module Models
    module Cms
      type boolean_target_property_variable =
        {
          operator: HubSpotSDK::Models::Cms::BooleanTargetPropertyVariable::operator,
          property_name: String,
          value: bool
        }

      class BooleanTargetPropertyVariable < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubSpotSDK::Models::Cms::BooleanTargetPropertyVariable::operator

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: bool?

        def value=: (bool) -> bool

        def initialize: (
          operator: HubSpotSDK::Models::Cms::BooleanTargetPropertyVariable::operator,
          ?property_name: String,
          ?value: bool
        ) -> void

        def to_hash: -> {
          operator: HubSpotSDK::Models::Cms::BooleanTargetPropertyVariable::operator,
          property_name: String,
          value: bool
        }

        type operator = :BOOLEAN_TARGET_PROPERTY_VARIABLE

        module Operator
          extend HubSpotSDK::Internal::Type::Enum

          BOOLEAN_TARGET_PROPERTY_VARIABLE: :BOOLEAN_TARGET_PROPERTY_VARIABLE

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::BooleanTargetPropertyVariable::operator]
        end
      end
    end
  end
end
