module HubspotSDK
  module Models
    module Cms
      type boolean_property_variable =
        {
          operator: HubspotSDK::Models::Cms::BooleanPropertyVariable::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: bool
        }

      class BooleanPropertyVariable < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::BooleanPropertyVariable::operator

        attr_reader inputs: ::Array[HubspotSDK::Models::Cms::expression]?

        def inputs=: (
          ::Array[HubspotSDK::Models::Cms::expression]
        ) -> ::Array[HubspotSDK::Models::Cms::expression]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: bool?

        def value=: (bool) -> bool

        def initialize: (
          operator: HubspotSDK::Models::Cms::BooleanPropertyVariable::operator,
          ?inputs: ::Array[HubspotSDK::Models::Cms::expression],
          ?property_name: String,
          ?value: bool
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::BooleanPropertyVariable::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: bool
        }

        type operator = :BOOLEAN_PROPERTY_VARIABLE

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          BOOLEAN_PROPERTY_VARIABLE: :BOOLEAN_PROPERTY_VARIABLE

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::BooleanPropertyVariable::operator]
        end
      end
    end
  end
end
