module HubSpotSDK
  module Models
    module Cms
      type bounded_next_page = { offset: Integer, link: String }

      class BoundedNextPage < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor offset: Integer

        attr_reader link: String?

        def link=: (String) -> String

        def initialize: (offset: Integer, ?link: String) -> void

        def to_hash: -> { offset: Integer, link: String }
      end
    end
  end
end
