module HubspotSDK
  module Models
    module Cms
      type bounded_paging = { next_: HubspotSDK::Cms::BoundedNextPage }

      class BoundedPaging < HubspotSDK::Internal::Type::BaseModel
        attr_reader next_: HubspotSDK::Cms::BoundedNextPage?

        def next_=: (
          HubspotSDK::Cms::BoundedNextPage
        ) -> HubspotSDK::Cms::BoundedNextPage

        def initialize: (?next_: HubspotSDK::Cms::BoundedNextPage) -> void

        def to_hash: -> { next_: HubspotSDK::Cms::BoundedNextPage }
      end
    end
  end
end
