module HubSpotSDK
  module Models
    module Cms
      type collection_response_with_total_url_mapping_forward_paging =
        {
          results: ::Array[HubSpotSDK::Cms::URLMapping],
          total: Integer,
          paging: HubSpotSDK::ForwardPaging
        }

      class CollectionResponseWithTotalURLMappingForwardPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Cms::URLMapping]

        attr_accessor total: Integer

        attr_reader paging: HubSpotSDK::ForwardPaging?

        def paging=: (HubSpotSDK::ForwardPaging) -> HubSpotSDK::ForwardPaging

        def initialize: (
          results: ::Array[HubSpotSDK::Cms::URLMapping],
          total: Integer,
          ?paging: HubSpotSDK::ForwardPaging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Cms::URLMapping],
          total: Integer,
          paging: HubSpotSDK::ForwardPaging
        }
      end
    end
  end
end
