module HubSpotSDK
  module Models
    module Cms
      type collection_response_property_no_paging =
        { results: ::Array[HubSpotSDK::Cms::Property1] }

      class CollectionResponsePropertyNoPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Cms::Property1]

        def initialize: (results: ::Array[HubSpotSDK::Cms::Property1]) -> void

        def to_hash: -> { results: ::Array[HubSpotSDK::Cms::Property1] }
      end
    end
  end
end
