module HubspotSDK
  module Models
    module Cms
      type concat_strings =
        {
          operator: HubspotSDK::Models::Cms::ConcatStrings::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: String
        }

      class ConcatStrings < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::ConcatStrings::operator

        attr_reader inputs: ::Array[HubspotSDK::Models::Cms::expression]?

        def inputs=: (
          ::Array[HubspotSDK::Models::Cms::expression]
        ) -> ::Array[HubspotSDK::Models::Cms::expression]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: String?

        def value=: (String) -> String

        def initialize: (
          operator: HubspotSDK::Models::Cms::ConcatStrings::operator,
          ?inputs: ::Array[HubspotSDK::Models::Cms::expression],
          ?property_name: String,
          ?value: String
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::ConcatStrings::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: String
        }

        type operator = :CONCAT_STRINGS

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          CONCAT_STRINGS: :CONCAT_STRINGS

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::ConcatStrings::operator]
        end
      end
    end
  end
end
