module HubSpotSDK
  module Models
    module Cms
      type content_folder_version =
        {
          id: String,
          object: HubSpotSDK::Cms::ContentFolder,
          updated_at: Time,
          user: HubSpotSDK::VersionUser
        }

      class ContentFolderVersion < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor object: HubSpotSDK::Cms::ContentFolder

        attr_accessor updated_at: Time

        attr_accessor user: HubSpotSDK::VersionUser

        def initialize: (
          id: String,
          object: HubSpotSDK::Cms::ContentFolder,
          updated_at: Time,
          user: HubSpotSDK::VersionUser
        ) -> void

        def to_hash: -> {
          id: String,
          object: HubSpotSDK::Cms::ContentFolder,
          updated_at: Time,
          user: HubSpotSDK::VersionUser
        }
      end
    end
  end
end
