module HubspotSDK
  module Models
    module Cms
      type content_schedule_request_v_next = { id: String, publish_date: Time }

      class ContentScheduleRequestVNext < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor publish_date: Time

        def initialize: (id: String, publish_date: Time) -> void

        def to_hash: -> { id: String, publish_date: Time }
      end
    end
  end
end
