module HubspotSDK
  module Models
    module Cms
      type create_mb_object_request =
        HubspotSDK::Cms::CreateVideoObjectRequest
        | HubspotSDK::Cms::CreateOtherObjectRequest
        | HubspotSDK::Cms::CreateAudioObjectRequest
        | HubspotSDK::Cms::CreateImageObjectRequest
        | HubspotSDK::Cms::CreateDocumentObjectRequest

      module CreateMBObjectRequest
        extend HubspotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubspotSDK::Models::Cms::create_mb_object_request]
      end
    end
  end
end
