module HubSpotSDK
  module Models
    module Cms
      type default_requirements =
        {
          gates: ::Array[String],
          operator: HubSpotSDK::Models::Cms::DefaultRequirements::operator,
          scope_names: ::Array[String],
          settings: ::Array[String]
        }

      class DefaultRequirements < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor gates: ::Array[String]

        attr_accessor operator: HubSpotSDK::Models::Cms::DefaultRequirements::operator

        attr_accessor scope_names: ::Array[String]

        attr_accessor settings: ::Array[String]

        def initialize: (
          gates: ::Array[String],
          operator: HubSpotSDK::Models::Cms::DefaultRequirements::operator,
          scope_names: ::Array[String],
          settings: ::Array[String]
        ) -> void

        def to_hash: -> {
          gates: ::Array[String],
          operator: HubSpotSDK::Models::Cms::DefaultRequirements::operator,
          scope_names: ::Array[String],
          settings: ::Array[String]
        }

        type operator = :AND | :OR

        module Operator
          extend HubSpotSDK::Internal::Type::Enum

          AND: :AND
          OR: :OR

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::DefaultRequirements::operator]
        end
      end
    end
  end
end
