module HubspotSDK
  module Models
    module Cms
      type divide_numbers =
        {
          enclosed_in_parentheses: bool,
          operator: HubspotSDK::Models::Cms::DivideNumbers::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: Float
        }

      class DivideNumbers < HubspotSDK::Internal::Type::BaseModel
        attr_accessor enclosed_in_parentheses: bool

        attr_accessor operator: HubspotSDK::Models::Cms::DivideNumbers::operator

        attr_reader inputs: ::Array[HubspotSDK::Models::Cms::expression]?

        def inputs=: (
          ::Array[HubspotSDK::Models::Cms::expression]
        ) -> ::Array[HubspotSDK::Models::Cms::expression]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: Float?

        def value=: (Float) -> Float

        def initialize: (
          enclosed_in_parentheses: bool,
          operator: HubspotSDK::Models::Cms::DivideNumbers::operator,
          ?inputs: ::Array[HubspotSDK::Models::Cms::expression],
          ?property_name: String,
          ?value: Float
        ) -> void

        def to_hash: -> {
          enclosed_in_parentheses: bool,
          operator: HubspotSDK::Models::Cms::DivideNumbers::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: Float
        }

        type operator = :DIVIDE_NUMBERS

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          DIVIDE_NUMBERS: :DIVIDE_NUMBERS

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::DivideNumbers::operator]
        end
      end
    end
  end
end
