module HubspotSDK
  module Models
    module Cms
      type domain_get_params =
        { domain_id: String } & HubspotSDK::Internal::Type::request_parameters

      class DomainGetParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor domain_id: String

        def initialize: (
          domain_id: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          domain_id: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
