module HubspotSDK
  module Models
    module Cms
      type euler =
        {
          operator: HubspotSDK::Models::Cms::Euler::operator,
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: Float
        }

      class Euler < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::Euler::operator

        attr_reader inputs: ::Array[::Hash[Symbol, top]]?

        def inputs=: (
          ::Array[::Hash[Symbol, top]]
        ) -> ::Array[::Hash[Symbol, top]]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: Float?

        def value=: (Float) -> Float

        def initialize: (
          operator: HubspotSDK::Models::Cms::Euler::operator,
          ?inputs: ::Array[::Hash[Symbol, top]],
          ?property_name: String,
          ?value: Float
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::Euler::operator,
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: Float
        }

        type operator = :EULER

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          EULER: :EULER

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::Euler::operator]
        end
      end
    end
  end
end
