module HubSpotSDK
  module Models
    module Cms
      type euler =
        {
          operator: HubSpotSDK::Models::Cms::Euler::operator,
          property_name: String,
          value: Float
        }

      class Euler < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubSpotSDK::Models::Cms::Euler::operator

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: Float?

        def value=: (Float) -> Float

        def initialize: (
          operator: HubSpotSDK::Models::Cms::Euler::operator,
          ?property_name: String,
          ?value: Float
        ) -> void

        def to_hash: -> {
          operator: HubSpotSDK::Models::Cms::Euler::operator,
          property_name: String,
          value: Float
        }

        type operator = :EULER

        module Operator
          extend HubSpotSDK::Internal::Type::Enum

          EULER: :EULER

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::Euler::operator]
        end
      end
    end
  end
end
