module HubSpotSDK
  module Models
    module Cms
      type event_visibility_change =
        {
          event_type: HubSpotSDK::Models::Cms::EventVisibilityChange::event_type,
          updated_at: Integer,
          show_in_reporting: bool,
          show_in_timeline: bool,
          show_in_workflows: bool
        }

      class EventVisibilityChange < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor event_type: HubSpotSDK::Models::Cms::EventVisibilityChange::event_type

        attr_accessor updated_at: Integer

        attr_reader show_in_reporting: bool?

        def show_in_reporting=: (bool) -> bool

        attr_reader show_in_timeline: bool?

        def show_in_timeline=: (bool) -> bool

        attr_reader show_in_workflows: bool?

        def show_in_workflows=: (bool) -> bool

        def initialize: (
          event_type: HubSpotSDK::Models::Cms::EventVisibilityChange::event_type,
          updated_at: Integer,
          ?show_in_reporting: bool,
          ?show_in_timeline: bool,
          ?show_in_workflows: bool
        ) -> void

        def to_hash: -> {
          event_type: HubSpotSDK::Models::Cms::EventVisibilityChange::event_type,
          updated_at: Integer,
          show_in_reporting: bool,
          show_in_timeline: bool,
          show_in_workflows: bool
        }

        type event_type =
          :ALL | :ATTENTION_SPAN | :MEDIA_PLAYS | :MEDIA_PLAYS_PERCENT

        module EventType
          extend HubSpotSDK::Internal::Type::Enum

          ALL: :ALL
          ATTENTION_SPAN: :ATTENTION_SPAN
          MEDIA_PLAYS: :MEDIA_PLAYS
          MEDIA_PLAYS_PERCENT: :MEDIA_PLAYS_PERCENT

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::EventVisibilityChange::event_type]
        end
      end
    end
  end
end
