module HubSpotSDK
  module Models
    module Cms
      type extension_data =
        {
          extension_status_map: ::Hash[Symbol, HubSpotSDK::Models::Cms::ExtensionData::extension_status_map],
          tags: ::Array[String],
          case_change_test_extension_data: HubSpotSDK::Cms::CaseChangeTestExtensionData,
          option_decorators_extension_data: HubSpotSDK::Cms::OptionDecoratorsExtensionData,
          required_properties_extension_data: HubSpotSDK::Cms::RequiredPropertiesExtensionData,
          soft_required_properties_extension_data: HubSpotSDK::Cms::SoftRequiredPropertiesExtensionData
        }

      class ExtensionData < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor extension_status_map: ::Hash[Symbol, HubSpotSDK::Models::Cms::ExtensionData::extension_status_map]

        attr_accessor tags: ::Array[String]

        attr_reader case_change_test_extension_data: HubSpotSDK::Cms::CaseChangeTestExtensionData?

        def case_change_test_extension_data=: (
          HubSpotSDK::Cms::CaseChangeTestExtensionData
        ) -> HubSpotSDK::Cms::CaseChangeTestExtensionData

        attr_reader option_decorators_extension_data: HubSpotSDK::Cms::OptionDecoratorsExtensionData?

        def option_decorators_extension_data=: (
          HubSpotSDK::Cms::OptionDecoratorsExtensionData
        ) -> HubSpotSDK::Cms::OptionDecoratorsExtensionData

        attr_reader required_properties_extension_data: HubSpotSDK::Cms::RequiredPropertiesExtensionData?

        def required_properties_extension_data=: (
          HubSpotSDK::Cms::RequiredPropertiesExtensionData
        ) -> HubSpotSDK::Cms::RequiredPropertiesExtensionData

        attr_reader soft_required_properties_extension_data: HubSpotSDK::Cms::SoftRequiredPropertiesExtensionData?

        def soft_required_properties_extension_data=: (
          HubSpotSDK::Cms::SoftRequiredPropertiesExtensionData
        ) -> HubSpotSDK::Cms::SoftRequiredPropertiesExtensionData

        def initialize: (
          extension_status_map: ::Hash[Symbol, HubSpotSDK::Models::Cms::ExtensionData::extension_status_map],
          tags: ::Array[String],
          ?case_change_test_extension_data: HubSpotSDK::Cms::CaseChangeTestExtensionData,
          ?option_decorators_extension_data: HubSpotSDK::Cms::OptionDecoratorsExtensionData,
          ?required_properties_extension_data: HubSpotSDK::Cms::RequiredPropertiesExtensionData,
          ?soft_required_properties_extension_data: HubSpotSDK::Cms::SoftRequiredPropertiesExtensionData
        ) -> void

        def to_hash: -> {
          extension_status_map: ::Hash[Symbol, HubSpotSDK::Models::Cms::ExtensionData::extension_status_map],
          tags: ::Array[String],
          case_change_test_extension_data: HubSpotSDK::Cms::CaseChangeTestExtensionData,
          option_decorators_extension_data: HubSpotSDK::Cms::OptionDecoratorsExtensionData,
          required_properties_extension_data: HubSpotSDK::Cms::RequiredPropertiesExtensionData,
          soft_required_properties_extension_data: HubSpotSDK::Cms::SoftRequiredPropertiesExtensionData
        }

        type extension_status_map = :OK | :ERROR | :TIMEOUT

        module ExtensionStatusMap
          extend HubSpotSDK::Internal::Type::Enum

          OK: :OK
          ERROR: :ERROR
          TIMEOUT: :TIMEOUT

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::ExtensionData::extension_status_map]
        end
      end
    end
  end
end
