module HubspotSDK
  module Models
    module Cms
      type extract_most_recent_email_reply_html =
        {
          operator: HubspotSDK::Models::Cms::ExtractMostRecentEmailReplyHTML::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: String
        }

      class ExtractMostRecentEmailReplyHTML < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::ExtractMostRecentEmailReplyHTML::operator

        attr_reader inputs: ::Array[HubspotSDK::Models::Cms::expression]?

        def inputs=: (
          ::Array[HubspotSDK::Models::Cms::expression]
        ) -> ::Array[HubspotSDK::Models::Cms::expression]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: String?

        def value=: (String) -> String

        def initialize: (
          operator: HubspotSDK::Models::Cms::ExtractMostRecentEmailReplyHTML::operator,
          ?inputs: ::Array[HubspotSDK::Models::Cms::expression],
          ?property_name: String,
          ?value: String
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::ExtractMostRecentEmailReplyHTML::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: String
        }

        type operator = :EXTRACT_MOST_RECENT_EMAIL_REPLY_HTML

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          EXTRACT_MOST_RECENT_EMAIL_REPLY_HTML: :EXTRACT_MOST_RECENT_EMAIL_REPLY_HTML

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::ExtractMostRecentEmailReplyHTML::operator]
        end
      end
    end
  end
end
