module HubspotSDK
  module Models
    module Cms
      type fetch_single_currency_portal_currency =
        {
          operator: HubspotSDK::Models::Cms::FetchSingleCurrencyPortalCurrency::operator,
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: String
        }

      class FetchSingleCurrencyPortalCurrency < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::FetchSingleCurrencyPortalCurrency::operator

        attr_reader inputs: ::Array[::Hash[Symbol, top]]?

        def inputs=: (
          ::Array[::Hash[Symbol, top]]
        ) -> ::Array[::Hash[Symbol, top]]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: String?

        def value=: (String) -> String

        def initialize: (
          operator: HubspotSDK::Models::Cms::FetchSingleCurrencyPortalCurrency::operator,
          ?inputs: ::Array[::Hash[Symbol, top]],
          ?property_name: String,
          ?value: String
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::FetchSingleCurrencyPortalCurrency::operator,
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: String
        }

        type operator = :FETCH_SINGLE_CURRENCY_PORTAL_CURRENCY

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          FETCH_SINGLE_CURRENCY_PORTAL_CURRENCY: :FETCH_SINGLE_CURRENCY_PORTAL_CURRENCY

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::FetchSingleCurrencyPortalCurrency::operator]
        end
      end
    end
  end
end
