module HubSpotSDK
  module Models
    module Cms
      type fetch_single_currency_portal_currency =
        {
          operator: HubSpotSDK::Models::Cms::FetchSingleCurrencyPortalCurrency::operator,
          property_name: String,
          value: String
        }

      class FetchSingleCurrencyPortalCurrency < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubSpotSDK::Models::Cms::FetchSingleCurrencyPortalCurrency::operator

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: String?

        def value=: (String) -> String

        def initialize: (
          operator: HubSpotSDK::Models::Cms::FetchSingleCurrencyPortalCurrency::operator,
          ?property_name: String,
          ?value: String
        ) -> void

        def to_hash: -> {
          operator: HubSpotSDK::Models::Cms::FetchSingleCurrencyPortalCurrency::operator,
          property_name: String,
          value: String
        }

        type operator = :FETCH_SINGLE_CURRENCY_PORTAL_CURRENCY

        module Operator
          extend HubSpotSDK::Internal::Type::Enum

          FETCH_SINGLE_CURRENCY_PORTAL_CURRENCY: :FETCH_SINGLE_CURRENCY_PORTAL_CURRENCY

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::FetchSingleCurrencyPortalCurrency::operator]
        end
      end
    end
  end
end
