module HubspotSDK
  module Models
    module Cms
      type fetch_currency_decimal_places =
        {
          operator: HubspotSDK::Models::Cms::FetchCurrencyDecimalPlaces::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::FetchCurrencyDecimalPlaces::input],
          property_name: String,
          value: Float
        }

      class FetchCurrencyDecimalPlaces < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::FetchCurrencyDecimalPlaces::operator

        attr_reader inputs: ::Array[HubspotSDK::Models::Cms::FetchCurrencyDecimalPlaces::input]?

        def inputs=: (
          ::Array[HubspotSDK::Models::Cms::FetchCurrencyDecimalPlaces::input]
        ) -> ::Array[HubspotSDK::Models::Cms::FetchCurrencyDecimalPlaces::input]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: Float?

        def value=: (Float) -> Float

        def initialize: (
          operator: HubspotSDK::Models::Cms::FetchCurrencyDecimalPlaces::operator,
          ?inputs: ::Array[HubspotSDK::Models::Cms::FetchCurrencyDecimalPlaces::input],
          ?property_name: String,
          ?value: Float
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::FetchCurrencyDecimalPlaces::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::FetchCurrencyDecimalPlaces::input],
          property_name: String,
          value: Float
        }

        type operator = :FETCH_CURRENCY_DECIMAL_PLACES

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          FETCH_CURRENCY_DECIMAL_PLACES: :FETCH_CURRENCY_DECIMAL_PLACES

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::FetchCurrencyDecimalPlaces::operator]
        end

        type input =
          HubspotSDK::Cms::ConstantBoolean
          | HubspotSDK::Cms::ConstantNumber
          | HubspotSDK::Cms::ConstantString
          | HubspotSDK::Cms::BooleanPropertyVariable
          | HubspotSDK::Cms::StringPropertyVariable
          | HubspotSDK::Cms::NumberPropertyVariable
          | HubspotSDK::Cms::TimestampOfPropertyVariable
          | HubspotSDK::Cms::BooleanTargetPropertyVariable
          | HubspotSDK::Cms::StringTargetPropertyVariable
          | HubspotSDK::Cms::NumberTargetPropertyVariable
          | HubspotSDK::Cms::TimestampOfTargetPropertyVariable
          | HubspotSDK::Cms::AddNumbers
          | HubspotSDK::Cms::SubtractNumbers
          | HubspotSDK::Cms::MultiplyNumbers
          | HubspotSDK::Cms::DivideNumbers
          | HubspotSDK::Cms::RoundDownNumbers
          | HubspotSDK::Cms::RoundUpNumbers
          | HubspotSDK::Cms::RoundNearestNumbers
          | HubspotSDK::Cms::UpperCase
          | HubspotSDK::Cms::LowerCase
          | HubspotSDK::Cms::ConcatStrings
          | HubspotSDK::Cms::Contains
          | HubspotSDK::Cms::BeginsWith
          | HubspotSDK::Cms::NumberToString
          | HubspotSDK::Cms::ParseNumber
          | HubspotSDK::Cms::FetchExchangeRate
          | HubspotSDK::Cms::FetchCurrencyDecimalPlaces
          | HubspotSDK::Cms::FetchSingleCurrencyPortalCurrency
          | HubspotSDK::Cms::DatedExchangeRate
          | HubspotSDK::Cms::PipelineProbability
          | HubspotSDK::Cms::MaxNumbers
          | HubspotSDK::Cms::MinNumbers
          | HubspotSDK::Cms::LessThan
          | HubspotSDK::Cms::LessThanOrEqual
          | HubspotSDK::Cms::MoreThan
          | HubspotSDK::Cms::MoreThanOrEqual
          | HubspotSDK::Cms::NumberEquals
          | HubspotSDK::Cms::StringEquals
          | HubspotSDK::Cms::IsPipelineStageClosed
          | HubspotSDK::Cms::Not
          | HubspotSDK::Cms::Date
          | HubspotSDK::Cms::Month
          | HubspotSDK::Cms::Year
          | HubspotSDK::Cms::Now
          | HubspotSDK::Cms::TimeBetween
          | HubspotSDK::Cms::TimeBetweenSkipWeekends
          | HubspotSDK::Cms::PeriodToMonths
          | HubspotSDK::Cms::PeriodToWeeks
          | HubspotSDK::Cms::And
          | HubspotSDK::Cms::Or
          | HubspotSDK::Cms::Xor
          | HubspotSDK::Cms::IfString
          | HubspotSDK::Cms::IfNumber
          | HubspotSDK::Cms::IfBoolean
          | HubspotSDK::Cms::IsPresent
          | HubspotSDK::Cms::HasEmailReply
          | HubspotSDK::Cms::HasPlainTextEmailReply
          | HubspotSDK::Cms::ExtractMostRecentEmailReplyHTML
          | HubspotSDK::Cms::ExtractMostRecentEmailReplyText
          | HubspotSDK::Cms::ExtractMostRecentPlainTextEmailReply
          | HubspotSDK::Cms::SetContainsString
          | HubspotSDK::Cms::IsEngagementType
          | HubspotSDK::Cms::FormatFullName
          | HubspotSDK::Cms::FormatPhoneNumber
          | HubspotSDK::Cms::FormatSearchablePhoneNumber
          | HubspotSDK::Cms::AbsoluteValue
          | HubspotSDK::Cms::SquareRoot
          | HubspotSDK::Cms::Power
          | HubspotSDK::Cms::Substring
          | HubspotSDK::Cms::Euler
          | HubspotSDK::Cms::StringLength
          | HubspotSDK::Cms::AddTime
          | HubspotSDK::Cms::SubtractTime

        module Input
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Cms::FetchCurrencyDecimalPlaces::input]
        end
      end
    end
  end
end
