module HubspotSDK
  module Models
    module Cms
      type file_extract_request = { path: String }

      class FileExtractRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor path: String

        def initialize: (path: String) -> void

        def to_hash: -> { path: String }
      end
    end
  end
end
