module HubspotSDK
  module Models
    module Cms
      type format_full_name =
        {
          operator: HubspotSDK::Models::Cms::FormatFullName::operator,
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: String
        }

      class FormatFullName < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::FormatFullName::operator

        attr_reader inputs: ::Array[::Hash[Symbol, top]]?

        def inputs=: (
          ::Array[::Hash[Symbol, top]]
        ) -> ::Array[::Hash[Symbol, top]]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: String?

        def value=: (String) -> String

        def initialize: (
          operator: HubspotSDK::Models::Cms::FormatFullName::operator,
          ?inputs: ::Array[::Hash[Symbol, top]],
          ?property_name: String,
          ?value: String
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::FormatFullName::operator,
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: String
        }

        type operator = :FORMAT_FULL_NAME

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          FORMAT_FULL_NAME: :FORMAT_FULL_NAME

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::FormatFullName::operator]
        end
      end
    end
  end
end
