module HubSpotSDK
  module Models
    module Cms
      type gradient =
        {
          angle: HubSpotSDK::Cms::Angle,
          colors: ::Array[HubSpotSDK::Cms::ColorStop],
          side_or_corner: HubSpotSDK::Cms::SideOrCorner
        }

      class Gradient < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor angle: HubSpotSDK::Cms::Angle

        attr_accessor colors: ::Array[HubSpotSDK::Cms::ColorStop]

        attr_accessor side_or_corner: HubSpotSDK::Cms::SideOrCorner

        def initialize: (
          angle: HubSpotSDK::Cms::Angle,
          colors: ::Array[HubSpotSDK::Cms::ColorStop],
          side_or_corner: HubSpotSDK::Cms::SideOrCorner
        ) -> void

        def to_hash: -> {
          angle: HubSpotSDK::Cms::Angle,
          colors: ::Array[HubSpotSDK::Cms::ColorStop],
          side_or_corner: HubSpotSDK::Cms::SideOrCorner
        }
      end
    end
  end
end
