module HubSpotSDK
  module Models
    module Cms
      type group =
        {
          deleted: bool,
          display_name: String,
          display_order: Integer,
          fulcrum_portal_id: Integer,
          fulcrum_timestamp: Integer,
          hubspot_defined: bool,
          name: String,
          portal_id: Integer
        }

      class Group < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor deleted: bool

        attr_accessor display_name: String

        attr_accessor display_order: Integer

        attr_accessor fulcrum_portal_id: Integer

        attr_accessor fulcrum_timestamp: Integer

        attr_accessor hubspot_defined: bool

        attr_accessor name: String

        attr_accessor portal_id: Integer

        def initialize: (
          deleted: bool,
          display_name: String,
          display_order: Integer,
          fulcrum_portal_id: Integer,
          fulcrum_timestamp: Integer,
          hubspot_defined: bool,
          name: String,
          portal_id: Integer
        ) -> void

        def to_hash: -> {
          deleted: bool,
          display_name: String,
          display_order: Integer,
          fulcrum_portal_id: Integer,
          fulcrum_timestamp: Integer,
          hubspot_defined: bool,
          name: String,
          portal_id: Integer
        }
      end
    end
  end
end
