module HubspotSDK
  module Models
    module Cms
      type hub_db_table_clone_request =
        {
          copy_rows: bool,
          is_hubspot_defined: bool,
          new_label: String,
          new_name: String
        }

      class HubDBTableCloneRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor copy_rows: bool

        attr_accessor is_hubspot_defined: bool

        attr_reader new_label: String?

        def new_label=: (String) -> String

        attr_reader new_name: String?

        def new_name=: (String) -> String

        def initialize: (
          copy_rows: bool,
          is_hubspot_defined: bool,
          ?new_label: String,
          ?new_name: String
        ) -> void

        def to_hash: -> {
          copy_rows: bool,
          is_hubspot_defined: bool,
          new_label: String,
          new_name: String
        }
      end
    end
  end
end
