module HubSpotSDK
  module Models
    module Cms
      type hub_db_table_v3_request =
        {
          allow_child_tables: bool,
          allow_public_api_access: bool,
          columns: ::Array[HubSpotSDK::Cms::ColumnRequest],
          dynamic_meta_tags: ::Hash[Symbol, Integer],
          enable_child_table_pages: bool,
          label: String,
          name: String,
          use_for_pages: bool
        }

      class HubDBTableV3Request < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor allow_child_tables: bool

        attr_accessor allow_public_api_access: bool

        attr_accessor columns: ::Array[HubSpotSDK::Cms::ColumnRequest]

        attr_accessor dynamic_meta_tags: ::Hash[Symbol, Integer]

        attr_accessor enable_child_table_pages: bool

        attr_accessor label: String

        attr_accessor name: String

        attr_accessor use_for_pages: bool

        def initialize: (
          allow_child_tables: bool,
          allow_public_api_access: bool,
          columns: ::Array[HubSpotSDK::Cms::ColumnRequest],
          dynamic_meta_tags: ::Hash[Symbol, Integer],
          enable_child_table_pages: bool,
          label: String,
          name: String,
          use_for_pages: bool
        ) -> void

        def to_hash: -> {
          allow_child_tables: bool,
          allow_public_api_access: bool,
          columns: ::Array[HubSpotSDK::Cms::ColumnRequest],
          dynamic_meta_tags: ::Hash[Symbol, Integer],
          enable_child_table_pages: bool,
          label: String,
          name: String,
          use_for_pages: bool
        }
      end
    end
  end
end
