module HubspotSDK
  module Models
    module Cms
      type if_string =
        {
          enclosed_in_parentheses: bool,
          if_expression: HubspotSDK::Models::Cms::expression,
          operator: HubspotSDK::Models::Cms::IfString::operator,
          else_expression: HubspotSDK::Models::Cms::expression,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: String
        }

      class IfString < HubspotSDK::Internal::Type::BaseModel
        attr_accessor enclosed_in_parentheses: bool

        attr_accessor if_expression: HubspotSDK::Models::Cms::expression

        attr_accessor operator: HubspotSDK::Models::Cms::IfString::operator

        attr_reader else_expression: HubspotSDK::Models::Cms::expression?

        def else_expression=: (
          HubspotSDK::Models::Cms::expression
        ) -> HubspotSDK::Models::Cms::expression

        attr_reader inputs: ::Array[HubspotSDK::Models::Cms::expression]?

        def inputs=: (
          ::Array[HubspotSDK::Models::Cms::expression]
        ) -> ::Array[HubspotSDK::Models::Cms::expression]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: String?

        def value=: (String) -> String

        def initialize: (
          enclosed_in_parentheses: bool,
          if_expression: HubspotSDK::Models::Cms::expression,
          operator: HubspotSDK::Models::Cms::IfString::operator,
          ?else_expression: HubspotSDK::Models::Cms::expression,
          ?inputs: ::Array[HubspotSDK::Models::Cms::expression],
          ?property_name: String,
          ?value: String
        ) -> void

        def to_hash: -> {
          enclosed_in_parentheses: bool,
          if_expression: HubspotSDK::Models::Cms::expression,
          operator: HubspotSDK::Models::Cms::IfString::operator,
          else_expression: HubspotSDK::Models::Cms::expression,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: String
        }

        type operator = :IF_STRING

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          IF_STRING: :IF_STRING

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::IfString::operator]
        end
      end
    end
  end
end
