module HubSpotSDK
  module Models
    module Cms
      type inbound_db_object_type =
        {
          id: Integer,
          allows_sensitive_properties: bool,
          create_date_property_name: String,
          default_search_property_names: ::Array[String],
          deleted: bool,
          fully_qualified_name: String,
          has_custom_properties: bool,
          has_default_properties: bool,
          has_external_object_ids: bool,
          has_owners: bool,
          has_pipelines: bool,
          indexed_for_filters_and_reports: bool,
          last_modified_property_name: String,
          meta_type: HubSpotSDK::Models::Cms::InboundDBObjectType::meta_type,
          meta_type_id: Integer,
          name: String,
          object_type_id: String,
          object_type_id_string: String,
          permissioning_type: HubSpotSDK::Models::Cms::InboundDBObjectType::permissioning_type,
          pipeline_property_name: String,
          pipeline_stage_property_name: String,
          required_properties: ::Array[String],
          restorable: bool,
          scope_mappings: ::Array[HubSpotSDK::Cms::ScopeMapping],
          secondary_display_label_property_names: ::Array[String],
          access_scope_name: String,
          created_at: Integer,
          description: String,
          integration_app_id: Integer,
          janus_group: String,
          owner_portal_id: Integer,
          pipeline_close_date_property_name: String,
          pipeline_time_to_close_property_name: String,
          plural_form: String,
          primary_display_label_property_name: String,
          read_scope_name: String,
          singular_form: String,
          status: HubSpotSDK::Models::Cms::InboundDBObjectType::status,
          visibility: HubSpotSDK::Models::Cms::InboundDBObjectType::visibility,
          write_scope_name: String
        }

      class InboundDBObjectType < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: Integer

        attr_accessor allows_sensitive_properties: bool

        attr_accessor create_date_property_name: String

        attr_accessor default_search_property_names: ::Array[String]

        attr_accessor deleted: bool

        attr_accessor fully_qualified_name: String

        attr_accessor has_custom_properties: bool

        attr_accessor has_default_properties: bool

        attr_accessor has_external_object_ids: bool

        attr_accessor has_owners: bool

        attr_accessor has_pipelines: bool

        attr_accessor indexed_for_filters_and_reports: bool

        attr_accessor last_modified_property_name: String

        attr_accessor meta_type: HubSpotSDK::Models::Cms::InboundDBObjectType::meta_type

        attr_accessor meta_type_id: Integer

        attr_accessor name: String

        attr_accessor object_type_id: String

        attr_accessor object_type_id_string: String

        attr_accessor permissioning_type: HubSpotSDK::Models::Cms::InboundDBObjectType::permissioning_type

        attr_accessor pipeline_property_name: String

        attr_accessor pipeline_stage_property_name: String

        attr_accessor required_properties: ::Array[String]

        attr_accessor restorable: bool

        attr_accessor scope_mappings: ::Array[HubSpotSDK::Cms::ScopeMapping]

        attr_accessor secondary_display_label_property_names: ::Array[String]

        attr_reader access_scope_name: String?

        def access_scope_name=: (String) -> String

        attr_reader created_at: Integer?

        def created_at=: (Integer) -> Integer

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader integration_app_id: Integer?

        def integration_app_id=: (Integer) -> Integer

        attr_reader janus_group: String?

        def janus_group=: (String) -> String

        attr_reader owner_portal_id: Integer?

        def owner_portal_id=: (Integer) -> Integer

        attr_reader pipeline_close_date_property_name: String?

        def pipeline_close_date_property_name=: (String) -> String

        attr_reader pipeline_time_to_close_property_name: String?

        def pipeline_time_to_close_property_name=: (String) -> String

        attr_reader plural_form: String?

        def plural_form=: (String) -> String

        attr_reader primary_display_label_property_name: String?

        def primary_display_label_property_name=: (String) -> String

        attr_reader read_scope_name: String?

        def read_scope_name=: (String) -> String

        attr_reader singular_form: String?

        def singular_form=: (String) -> String

        attr_reader status: HubSpotSDK::Models::Cms::InboundDBObjectType::status?

        def status=: (
          HubSpotSDK::Models::Cms::InboundDBObjectType::status
        ) -> HubSpotSDK::Models::Cms::InboundDBObjectType::status

        attr_reader visibility: HubSpotSDK::Models::Cms::InboundDBObjectType::visibility?

        def visibility=: (
          HubSpotSDK::Models::Cms::InboundDBObjectType::visibility
        ) -> HubSpotSDK::Models::Cms::InboundDBObjectType::visibility

        attr_reader write_scope_name: String?

        def write_scope_name=: (String) -> String

        def initialize: (
          id: Integer,
          allows_sensitive_properties: bool,
          create_date_property_name: String,
          default_search_property_names: ::Array[String],
          deleted: bool,
          fully_qualified_name: String,
          has_custom_properties: bool,
          has_default_properties: bool,
          has_external_object_ids: bool,
          has_owners: bool,
          has_pipelines: bool,
          indexed_for_filters_and_reports: bool,
          last_modified_property_name: String,
          meta_type: HubSpotSDK::Models::Cms::InboundDBObjectType::meta_type,
          meta_type_id: Integer,
          name: String,
          object_type_id: String,
          object_type_id_string: String,
          permissioning_type: HubSpotSDK::Models::Cms::InboundDBObjectType::permissioning_type,
          pipeline_property_name: String,
          pipeline_stage_property_name: String,
          required_properties: ::Array[String],
          restorable: bool,
          scope_mappings: ::Array[HubSpotSDK::Cms::ScopeMapping],
          secondary_display_label_property_names: ::Array[String],
          ?access_scope_name: String,
          ?created_at: Integer,
          ?description: String,
          ?integration_app_id: Integer,
          ?janus_group: String,
          ?owner_portal_id: Integer,
          ?pipeline_close_date_property_name: String,
          ?pipeline_time_to_close_property_name: String,
          ?plural_form: String,
          ?primary_display_label_property_name: String,
          ?read_scope_name: String,
          ?singular_form: String,
          ?status: HubSpotSDK::Models::Cms::InboundDBObjectType::status,
          ?visibility: HubSpotSDK::Models::Cms::InboundDBObjectType::visibility,
          ?write_scope_name: String
        ) -> void

        def to_hash: -> {
          id: Integer,
          allows_sensitive_properties: bool,
          create_date_property_name: String,
          default_search_property_names: ::Array[String],
          deleted: bool,
          fully_qualified_name: String,
          has_custom_properties: bool,
          has_default_properties: bool,
          has_external_object_ids: bool,
          has_owners: bool,
          has_pipelines: bool,
          indexed_for_filters_and_reports: bool,
          last_modified_property_name: String,
          meta_type: HubSpotSDK::Models::Cms::InboundDBObjectType::meta_type,
          meta_type_id: Integer,
          name: String,
          object_type_id: String,
          object_type_id_string: String,
          permissioning_type: HubSpotSDK::Models::Cms::InboundDBObjectType::permissioning_type,
          pipeline_property_name: String,
          pipeline_stage_property_name: String,
          required_properties: ::Array[String],
          restorable: bool,
          scope_mappings: ::Array[HubSpotSDK::Cms::ScopeMapping],
          secondary_display_label_property_names: ::Array[String],
          access_scope_name: String,
          created_at: Integer,
          description: String,
          integration_app_id: Integer,
          janus_group: String,
          owner_portal_id: Integer,
          pipeline_close_date_property_name: String,
          pipeline_time_to_close_property_name: String,
          plural_form: String,
          primary_display_label_property_name: String,
          read_scope_name: String,
          singular_form: String,
          status: HubSpotSDK::Models::Cms::InboundDBObjectType::status,
          visibility: HubSpotSDK::Models::Cms::InboundDBObjectType::visibility,
          write_scope_name: String
        }

        type meta_type =
          :CMS_HUBDB
          | :HUBSPOT
          | :HUBSPOT_EVENT
          | :INTEGRATION
          | :INTEGRATION_EVENT
          | :PORTAL_SPECIFIC
          | :PORTAL_SPECIFIC_EVENT
          | :WORK
          | :WORK_SUB

        module MetaType
          extend HubSpotSDK::Internal::Type::Enum

          CMS_HUBDB: :CMS_HUBDB
          HUBSPOT: :HUBSPOT
          HUBSPOT_EVENT: :HUBSPOT_EVENT
          INTEGRATION: :INTEGRATION
          INTEGRATION_EVENT: :INTEGRATION_EVENT
          PORTAL_SPECIFIC: :PORTAL_SPECIFIC
          PORTAL_SPECIFIC_EVENT: :PORTAL_SPECIFIC_EVENT
          WORK: :WORK
          WORK_SUB: :WORK_SUB

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::InboundDBObjectType::meta_type]
        end

        type permissioning_type =
          :ALL_OR_NONE
          | :DO_NOT_CHECK_PERMISSIONS
          | :EXPLICIT
          | :OWNER_BASED
          | :TEAM_BASED

        module PermissioningType
          extend HubSpotSDK::Internal::Type::Enum

          ALL_OR_NONE: :ALL_OR_NONE
          DO_NOT_CHECK_PERMISSIONS: :DO_NOT_CHECK_PERMISSIONS
          EXPLICIT: :EXPLICIT
          OWNER_BASED: :OWNER_BASED
          TEAM_BASED: :TEAM_BASED

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::InboundDBObjectType::permissioning_type]
        end

        type status = :Deprecated | :"In development" | :Live

        module Status
          extend HubSpotSDK::Internal::Type::Enum

          DEPRECATED: :Deprecated
          IN_DEVELOPMENT: :"In development"
          LIVE: :Live

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::InboundDBObjectType::status]
        end

        type visibility =
          :"Customer-facing"
          | :"Customer-facing public API"
          | :"Customer-facing UI"
          | :"Internal only"

        module Visibility
          extend HubSpotSDK::Internal::Type::Enum

          CUSTOMER_FACING: :"Customer-facing"
          CUSTOMER_FACING_PUBLIC_API: :"Customer-facing public API"
          CUSTOMER_FACING_UI: :"Customer-facing UI"
          INTERNAL_ONLY: :"Internal only"

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::InboundDBObjectType::visibility]
        end
      end
    end
  end
end
