module HubSpotSDK
  module Models
    module Cms
      type indexed_field =
        { metadata_field: bool, name: String, value: top, values: ::Array[top] }

      class IndexedField < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor metadata_field: bool

        attr_accessor name: String

        attr_accessor value: top

        attr_accessor values: ::Array[top]

        def initialize: (
          metadata_field: bool,
          name: String,
          value: top,
          values: ::Array[top]
        ) -> void

        def to_hash: -> {
          metadata_field: bool,
          name: String,
          value: top,
          values: ::Array[top]
        }
      end
    end
  end
end
