module HubSpotSDK
  module Models
    module Cms
      type indexed_data =
        {
          id: String,
          fields: ::Hash[Symbol, HubSpotSDK::Cms::IndexedField],
          type: HubSpotSDK::Models::Cms::IndexedData::type_
        }

      class IndexedData < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor fields: ::Hash[Symbol, HubSpotSDK::Cms::IndexedField]

        attr_accessor type: HubSpotSDK::Models::Cms::IndexedData::type_

        def initialize: (
          id: String,
          fields: ::Hash[Symbol, HubSpotSDK::Cms::IndexedField],
          type: HubSpotSDK::Models::Cms::IndexedData::type_
        ) -> void

        def to_hash: -> {
          id: String,
          fields: ::Hash[Symbol, HubSpotSDK::Cms::IndexedField],
          type: HubSpotSDK::Models::Cms::IndexedData::type_
        }

        type type_ =
          :BLOG_POST
          | :KNOWLEDGE_ARTICLE
          | :LANDING_PAGE
          | :LISTING_PAGE
          | :SITE_PAGE
          | :STRUCTURED_CONTENT

        module Type
          extend HubSpotSDK::Internal::Type::Enum

          BLOG_POST: :BLOG_POST
          KNOWLEDGE_ARTICLE: :KNOWLEDGE_ARTICLE
          LANDING_PAGE: :LANDING_PAGE
          LISTING_PAGE: :LISTING_PAGE
          SITE_PAGE: :SITE_PAGE
          STRUCTURED_CONTENT: :STRUCTURED_CONTENT

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::IndexedData::type_]
        end
      end
    end
  end
end
