module HubSpotSDK
  module Models
    module Cms
      type integrator_o_embed_domain_request =
        { endpoints: HubSpotSDK::Cms::Endpoints, portal_id: Integer }

      class IntegratorOEmbedDomainRequest < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor endpoints: HubSpotSDK::Cms::Endpoints

        attr_reader portal_id: Integer?

        def portal_id=: (Integer) -> Integer

        def initialize: (
          endpoints: HubSpotSDK::Cms::Endpoints,
          ?portal_id: Integer
        ) -> void

        def to_hash: -> {
          endpoints: HubSpotSDK::Cms::Endpoints,
          portal_id: Integer
        }
      end
    end
  end
end
