module HubSpotSDK
  module Models
    module Cms
      type integrator_object_creation_response =
        {
          object_type: HubSpotSDK::Cms::InboundDBObjectType,
          properties: ::Array[HubSpotSDK::Cms::PropertyDefinition],
          property_groups: ::Array[HubSpotSDK::Cms::Group]
        }

      class IntegratorObjectCreationResponse < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor object_type: HubSpotSDK::Cms::InboundDBObjectType

        attr_accessor properties: ::Array[HubSpotSDK::Cms::PropertyDefinition]

        attr_accessor property_groups: ::Array[HubSpotSDK::Cms::Group]

        def initialize: (
          object_type: HubSpotSDK::Cms::InboundDBObjectType,
          properties: ::Array[HubSpotSDK::Cms::PropertyDefinition],
          property_groups: ::Array[HubSpotSDK::Cms::Group]
        ) -> void

        def to_hash: -> {
          object_type: HubSpotSDK::Cms::InboundDBObjectType,
          properties: ::Array[HubSpotSDK::Cms::PropertyDefinition],
          property_groups: ::Array[HubSpotSDK::Cms::Group]
        }
      end
    end
  end
end
