module HubspotSDK
  module Models
    module Cms
      type integrator_o_embed_domain_model =
        {
          id: Integer,
          app_id: Integer,
          created_at: Integer,
          deleted_at: Integer,
          endpoints: HubspotSDK::Cms::Endpoints,
          portal_id: Integer,
          updated_at: Integer
        }

      class IntegratorOEmbedDomainModel < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: Integer

        attr_accessor app_id: Integer

        attr_accessor created_at: Integer

        attr_accessor deleted_at: Integer

        attr_accessor endpoints: HubspotSDK::Cms::Endpoints

        attr_accessor portal_id: Integer

        attr_accessor updated_at: Integer

        def initialize: (
          id: Integer,
          app_id: Integer,
          created_at: Integer,
          deleted_at: Integer,
          endpoints: HubspotSDK::Cms::Endpoints,
          portal_id: Integer,
          updated_at: Integer
        ) -> void

        def to_hash: -> {
          id: Integer,
          app_id: Integer,
          created_at: Integer,
          deleted_at: Integer,
          endpoints: HubspotSDK::Cms::Endpoints,
          portal_id: Integer,
          updated_at: Integer
        }
      end
    end
  end
end
