module HubspotSDK
  module Models
    module Cms
      type is_engagement_type =
        {
          operator: HubspotSDK::Models::Cms::IsEngagementType::operator,
          property_name: String,
          value: bool
        }

      class IsEngagementType < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::IsEngagementType::operator

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: bool?

        def value=: (bool) -> bool

        def initialize: (
          operator: HubspotSDK::Models::Cms::IsEngagementType::operator,
          ?property_name: String,
          ?value: bool
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::IsEngagementType::operator,
          property_name: String,
          value: bool
        }

        type operator = :IS_ENGAGEMENT_TYPE

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          IS_ENGAGEMENT_TYPE: :IS_ENGAGEMENT_TYPE

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::IsEngagementType::operator]
        end
      end
    end
  end
end
