module HubspotSDK
  module Models
    module Cms
      type is_present =
        {
          expression_to_evaluate: HubspotSDK::Models::Cms::expression,
          operator: HubspotSDK::Models::Cms::IsPresent::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: bool
        }

      class IsPresent < HubspotSDK::Internal::Type::BaseModel
        attr_accessor expression_to_evaluate: HubspotSDK::Models::Cms::expression

        attr_accessor operator: HubspotSDK::Models::Cms::IsPresent::operator

        attr_reader inputs: ::Array[HubspotSDK::Models::Cms::expression]?

        def inputs=: (
          ::Array[HubspotSDK::Models::Cms::expression]
        ) -> ::Array[HubspotSDK::Models::Cms::expression]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: bool?

        def value=: (bool) -> bool

        def initialize: (
          expression_to_evaluate: HubspotSDK::Models::Cms::expression,
          operator: HubspotSDK::Models::Cms::IsPresent::operator,
          ?inputs: ::Array[HubspotSDK::Models::Cms::expression],
          ?property_name: String,
          ?value: bool
        ) -> void

        def to_hash: -> {
          expression_to_evaluate: HubspotSDK::Models::Cms::expression,
          operator: HubspotSDK::Models::Cms::IsPresent::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: bool
        }

        type operator = :IS_PRESENT

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          IS_PRESENT: :IS_PRESENT

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::IsPresent::operator]
        end
      end
    end
  end
end
