module HubSpotSDK
  module Models
    module Cms
      type is_portal_enabled_currency =
        {
          operator: HubSpotSDK::Models::Cms::IsPortalEnabledCurrency::operator,
          inputs: ::Array[top],
          property_name: String,
          value: bool
        }

      class IsPortalEnabledCurrency < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubSpotSDK::Models::Cms::IsPortalEnabledCurrency::operator

        attr_reader inputs: ::Array[top]?

        def inputs=: (::Array[top]) -> ::Array[top]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: bool?

        def value=: (bool) -> bool

        def initialize: (
          operator: HubSpotSDK::Models::Cms::IsPortalEnabledCurrency::operator,
          ?inputs: ::Array[top],
          ?property_name: String,
          ?value: bool
        ) -> void

        def to_hash: -> {
          operator: HubSpotSDK::Models::Cms::IsPortalEnabledCurrency::operator,
          inputs: ::Array[top],
          property_name: String,
          value: bool
        }

        type operator = :IS_PORTAL_ENABLED_CURRENCY

        module Operator
          extend HubSpotSDK::Internal::Type::Enum

          IS_PORTAL_ENABLED_CURRENCY: :IS_PORTAL_ENABLED_CURRENCY

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::IsPortalEnabledCurrency::operator]
        end
      end
    end
  end
end
