module HubspotSDK
  module Models
    module Cms
      type is_pipeline_stage_closed =
        {
          operator: HubspotSDK::Models::Cms::IsPipelineStageClosed::operator,
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: bool
        }

      class IsPipelineStageClosed < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::IsPipelineStageClosed::operator

        attr_reader inputs: ::Array[::Hash[Symbol, top]]?

        def inputs=: (
          ::Array[::Hash[Symbol, top]]
        ) -> ::Array[::Hash[Symbol, top]]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: bool?

        def value=: (bool) -> bool

        def initialize: (
          operator: HubspotSDK::Models::Cms::IsPipelineStageClosed::operator,
          ?inputs: ::Array[::Hash[Symbol, top]],
          ?property_name: String,
          ?value: bool
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::IsPipelineStageClosed::operator,
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: bool
        }

        type operator = :IS_PIPELINE_STAGE_CLOSED

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          IS_PIPELINE_STAGE_CLOSED: :IS_PIPELINE_STAGE_CLOSED

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::IsPipelineStageClosed::operator]
        end
      end
    end
  end
end
