module HubSpotSDK
  module Models
    module Cms
      type is_present =
        {
          expression_to_evaluate: top,
          operator: HubSpotSDK::Models::Cms::IsPresent::operator,
          property_name: String,
          value: bool
        }

      class IsPresent < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor expression_to_evaluate: top

        attr_accessor operator: HubSpotSDK::Models::Cms::IsPresent::operator

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: bool?

        def value=: (bool) -> bool

        def initialize: (
          expression_to_evaluate: top,
          operator: HubSpotSDK::Models::Cms::IsPresent::operator,
          ?property_name: String,
          ?value: bool
        ) -> void

        def to_hash: -> {
          expression_to_evaluate: top,
          operator: HubSpotSDK::Models::Cms::IsPresent::operator,
          property_name: String,
          value: bool
        }

        type operator = :IS_PRESENT

        module Operator
          extend HubSpotSDK::Internal::Type::Enum

          IS_PRESENT: :IS_PRESENT

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::IsPresent::operator]
        end
      end
    end
  end
end
