module HubSpotSDK
  module Models
    module Cms
      type layout_section =
        {
          cells: ::Array[HubSpotSDK::Cms::LayoutSection],
          css_class: String,
          css_id: String,
          css_style: String,
          label: String,
          name: String,
          params: ::Hash[Symbol, top],
          row_meta_data: ::Array[HubSpotSDK::Cms::RowMetaData],
          rows: ::Array[::Hash[Symbol, HubSpotSDK::Cms::LayoutSection]],
          styles: HubSpotSDK::Cms::Styles,
          type: String,
          w: Integer,
          x: Integer
        }

      class LayoutSection < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor cells: ::Array[HubSpotSDK::Cms::LayoutSection]

        attr_accessor css_class: String

        attr_accessor css_id: String

        attr_accessor css_style: String

        attr_accessor label: String

        attr_accessor name: String

        attr_accessor params: ::Hash[Symbol, top]

        attr_accessor row_meta_data: ::Array[HubSpotSDK::Cms::RowMetaData]

        attr_accessor rows: ::Array[::Hash[Symbol, HubSpotSDK::Cms::LayoutSection]]

        attr_accessor styles: HubSpotSDK::Cms::Styles

        attr_accessor type: String

        attr_accessor w: Integer

        attr_accessor x: Integer

        def initialize: (
          cells: ::Array[HubSpotSDK::Cms::LayoutSection],
          css_class: String,
          css_id: String,
          css_style: String,
          label: String,
          name: String,
          params: ::Hash[Symbol, top],
          row_meta_data: ::Array[HubSpotSDK::Cms::RowMetaData],
          rows: ::Array[::Hash[Symbol, HubSpotSDK::Cms::LayoutSection]],
          styles: HubSpotSDK::Cms::Styles,
          type: String,
          w: Integer,
          x: Integer
        ) -> void

        def to_hash: -> {
          cells: ::Array[HubSpotSDK::Cms::LayoutSection],
          css_class: String,
          css_id: String,
          css_style: String,
          label: String,
          name: String,
          params: ::Hash[Symbol, top],
          row_meta_data: ::Array[HubSpotSDK::Cms::RowMetaData],
          rows: ::Array[::Hash[Symbol, HubSpotSDK::Cms::LayoutSection]],
          styles: HubSpotSDK::Cms::Styles,
          type: String,
          w: Integer,
          x: Integer
        }
      end
    end
  end
end
