module HubSpotSDK
  module Models
    module Cms
      type less_than =
        {
          operator: HubSpotSDK::Models::Cms::LessThan::operator,
          inputs: ::Array[top],
          property_name: String,
          value: bool
        }

      class LessThan < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubSpotSDK::Models::Cms::LessThan::operator

        attr_reader inputs: ::Array[top]?

        def inputs=: (::Array[top]) -> ::Array[top]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: bool?

        def value=: (bool) -> bool

        def initialize: (
          operator: HubSpotSDK::Models::Cms::LessThan::operator,
          ?inputs: ::Array[top],
          ?property_name: String,
          ?value: bool
        ) -> void

        def to_hash: -> {
          operator: HubSpotSDK::Models::Cms::LessThan::operator,
          inputs: ::Array[top],
          property_name: String,
          value: bool
        }

        type operator = :LESS_THAN

        module Operator
          extend HubSpotSDK::Internal::Type::Enum

          LESS_THAN: :LESS_THAN

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::LessThan::operator]
        end
      end
    end
  end
end
