module HubspotSDK
  module Models
    module Cms
      type less_than_or_equal =
        {
          operator: HubspotSDK::Models::Cms::LessThanOrEqual::operator,
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: bool
        }

      class LessThanOrEqual < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::LessThanOrEqual::operator

        attr_reader inputs: ::Array[::Hash[Symbol, top]]?

        def inputs=: (
          ::Array[::Hash[Symbol, top]]
        ) -> ::Array[::Hash[Symbol, top]]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: bool?

        def value=: (bool) -> bool

        def initialize: (
          operator: HubspotSDK::Models::Cms::LessThanOrEqual::operator,
          ?inputs: ::Array[::Hash[Symbol, top]],
          ?property_name: String,
          ?value: bool
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::LessThanOrEqual::operator,
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: bool
        }

        type operator = :LESS_THAN_OR_EQUAL

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          LESS_THAN_OR_EQUAL: :LESS_THAN_OR_EQUAL

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::LessThanOrEqual::operator]
        end
      end
    end
  end
end
