module HubspotSDK
  module Models
    module Cms
      type less_than =
        {
          operator: HubspotSDK::Models::Cms::LessThan::operator,
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: bool
        }

      class LessThan < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::LessThan::operator

        attr_reader inputs: ::Array[::Hash[Symbol, top]]?

        def inputs=: (
          ::Array[::Hash[Symbol, top]]
        ) -> ::Array[::Hash[Symbol, top]]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: bool?

        def value=: (bool) -> bool

        def initialize: (
          operator: HubspotSDK::Models::Cms::LessThan::operator,
          ?inputs: ::Array[::Hash[Symbol, top]],
          ?property_name: String,
          ?value: bool
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::LessThan::operator,
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: bool
        }

        type operator = :LESS_THAN

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          LESS_THAN: :LESS_THAN

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::LessThan::operator]
        end
      end
    end
  end
end
