module HubSpotSDK
  module Models
    module Cms
      type margin =
        { bottom: HubSpotSDK::Cms::Size, top: HubSpotSDK::Cms::Size }

      class Margin < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor bottom: HubSpotSDK::Cms::Size

        attr_accessor top: HubSpotSDK::Cms::Size

        def initialize: (
          bottom: HubSpotSDK::Cms::Size,
          top: HubSpotSDK::Cms::Size
        ) -> void

        def to_hash: -> {
          bottom: HubSpotSDK::Cms::Size,
          top: HubSpotSDK::Cms::Size
        }
      end
    end
  end
end
