module HubspotSDK
  module Models
    module Cms
      type media_bridge_delete_params =
        {
          media_type: HubspotSDK::Models::Cms::MediaBridgeDeleteParams::media_type,
          object_id_: Integer
        }
        & HubspotSDK::Internal::Type::request_parameters

      class MediaBridgeDeleteParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor media_type: HubspotSDK::Models::Cms::MediaBridgeDeleteParams::media_type

        attr_accessor object_id_: Integer

        def initialize: (
          media_type: HubspotSDK::Models::Cms::MediaBridgeDeleteParams::media_type,
          object_id_: Integer,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          media_type: HubspotSDK::Models::Cms::MediaBridgeDeleteParams::media_type,
          object_id_: Integer,
          request_options: HubspotSDK::RequestOptions
        }

        type media_type = :AUDIO | :DOCUMENT | :IMAGE | :OTHER | :VIDEO

        module MediaType
          extend HubspotSDK::Internal::Type::Enum

          AUDIO: :AUDIO
          DOCUMENT: :DOCUMENT
          IMAGE: :IMAGE
          OTHER: :OTHER
          VIDEO: :VIDEO

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::MediaBridgeDeleteParams::media_type]
        end
      end
    end
  end
end
