module HubSpotSDK
  module Models
    module Cms
      type media_bridge_register_app_name_params =
        { app_id: Integer } & HubSpotSDK::Internal::Type::request_parameters

      class MediaBridgeRegisterAppNameParams < HubSpotSDK::Models::Cms::MediaBridgeProviderPartial
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        def app_id: -> Integer

        def app_id=: (Integer _) -> Integer

        def initialize: (
          app_id: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          app_id: Integer,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
