module HubSpotSDK
  module Models
    module Cms
      type media_bridge_delete_association_params =
        { app_id: Integer, object_type: String, association_id: String }
        & HubSpotSDK::Internal::Type::request_parameters

      class MediaBridgeDeleteAssociationParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor app_id: Integer

        attr_accessor object_type: String

        attr_accessor association_id: String

        def initialize: (
          app_id: Integer,
          object_type: String,
          association_id: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          app_id: Integer,
          object_type: String,
          association_id: String,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
