module HubspotSDK
  module Models
    module Cms
      type media_bridge_update_params =
        { object_id_: Integer } & HubspotSDK::Internal::Type::request_parameters

      class MediaBridgeUpdateParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor object_id_: Integer

        def initialize: (
          object_id_: Integer,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          object_id_: Integer,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
