module HubspotSDK
  module Models
    module Cms
      type media_bridge_object =
        {
          id: String,
          created_at: Time,
          media_type: HubspotSDK::Models::Cms::MediaBridgeObject::media_type,
          title: String,
          updated_at: Time,
          details_page_link: String,
          duration: Integer,
          external_id: String,
          file_url: String,
          oembed_url: String,
          poster_url: String,
          thumbnail_url: String,
          video: HubspotSDK::Cms::VideoObject
        }

      class MediaBridgeObject < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor media_type: HubspotSDK::Models::Cms::MediaBridgeObject::media_type

        attr_accessor title: String

        attr_accessor updated_at: Time

        attr_reader details_page_link: String?

        def details_page_link=: (String) -> String

        attr_reader duration: Integer?

        def duration=: (Integer) -> Integer

        attr_reader external_id: String?

        def external_id=: (String) -> String

        attr_reader file_url: String?

        def file_url=: (String) -> String

        attr_reader oembed_url: String?

        def oembed_url=: (String) -> String

        attr_reader poster_url: String?

        def poster_url=: (String) -> String

        attr_reader thumbnail_url: String?

        def thumbnail_url=: (String) -> String

        attr_reader video: HubspotSDK::Cms::VideoObject?

        def video=: (
          HubspotSDK::Cms::VideoObject
        ) -> HubspotSDK::Cms::VideoObject

        def initialize: (
          id: String,
          created_at: Time,
          media_type: HubspotSDK::Models::Cms::MediaBridgeObject::media_type,
          title: String,
          updated_at: Time,
          ?details_page_link: String,
          ?duration: Integer,
          ?external_id: String,
          ?file_url: String,
          ?oembed_url: String,
          ?poster_url: String,
          ?thumbnail_url: String,
          ?video: HubspotSDK::Cms::VideoObject
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          media_type: HubspotSDK::Models::Cms::MediaBridgeObject::media_type,
          title: String,
          updated_at: Time,
          details_page_link: String,
          duration: Integer,
          external_id: String,
          file_url: String,
          oembed_url: String,
          poster_url: String,
          thumbnail_url: String,
          video: HubspotSDK::Cms::VideoObject
        }

        type media_type = :AUDIO | :DOCUMENT | :IMAGE | :OTHER | :VIDEO

        module MediaType
          extend HubspotSDK::Internal::Type::Enum

          AUDIO: :AUDIO
          DOCUMENT: :DOCUMENT
          IMAGE: :IMAGE
          OTHER: :OTHER
          VIDEO: :VIDEO

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::MediaBridgeObject::media_type]
        end
      end
    end
  end
end
