module HubspotSDK
  module Models
    module Cms
      type media_bridge_get_schema_params =
        { app_id: String, object_type: String }
        & HubspotSDK::Internal::Type::request_parameters

      class MediaBridgeGetSchemaParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor app_id: String

        attr_accessor object_type: String

        def initialize: (
          app_id: String,
          object_type: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          app_id: String,
          object_type: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
