module HubspotSDK
  module Models
    module Cms
      type media_bridge_provider_partial = { updated_at: Integer, name: String }

      class MediaBridgeProviderPartial < HubspotSDK::Internal::Type::BaseModel
        attr_accessor updated_at: Integer

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (updated_at: Integer, ?name: String) -> void

        def to_hash: -> { updated_at: Integer, name: String }
      end
    end
  end
end
