module HubspotSDK
  module Models
    module Cms
      type media_bridge_create_oembed_domain_params =
        { app_id: String } & HubspotSDK::Internal::Type::request_parameters

      class MediaBridgeCreateOembedDomainParams < HubspotSDK::Models::Cms::IntegratorOEmbedDomainRequest
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        def app_id: -> String

        def app_id=: (String _) -> String

        def initialize: (
          app_id: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          app_id: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
