module HubSpotSDK
  module Models
    module Cms
      type media_bridge_list_schemas_params =
        { app_id: Integer, archived: bool }
        & HubSpotSDK::Internal::Type::request_parameters

      class MediaBridgeListSchemasParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor app_id: Integer

        attr_reader archived: bool?

        def archived=: (bool) -> bool

        def initialize: (
          app_id: Integer,
          ?archived: bool,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          app_id: Integer,
          archived: bool,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
