module HubspotSDK
  module Models
    module Cms
      type not_ =
        {
          operator: HubspotSDK::Models::Cms::Not::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: bool
        }

      class Not < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::Not::operator

        attr_reader inputs: ::Array[HubspotSDK::Models::Cms::expression]?

        def inputs=: (
          ::Array[HubspotSDK::Models::Cms::expression]
        ) -> ::Array[HubspotSDK::Models::Cms::expression]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: bool?

        def value=: (bool) -> bool

        def initialize: (
          operator: HubspotSDK::Models::Cms::Not::operator,
          ?inputs: ::Array[HubspotSDK::Models::Cms::expression],
          ?property_name: String,
          ?value: bool
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::Not::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: bool
        }

        type operator = :NOT

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          NOT: :NOT

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::Not::operator]
        end
      end
    end
  end
end
