module HubSpotSDK
  module Models
    module Cms
      type number_property_variable =
        {
          operator: HubSpotSDK::Models::Cms::NumberPropertyVariable::operator,
          property_name: String,
          value: Float
        }

      class NumberPropertyVariable < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubSpotSDK::Models::Cms::NumberPropertyVariable::operator

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: Float?

        def value=: (Float) -> Float

        def initialize: (
          operator: HubSpotSDK::Models::Cms::NumberPropertyVariable::operator,
          ?property_name: String,
          ?value: Float
        ) -> void

        def to_hash: -> {
          operator: HubSpotSDK::Models::Cms::NumberPropertyVariable::operator,
          property_name: String,
          value: Float
        }

        type operator = :NUMBER_PROPERTY_VARIABLE

        module Operator
          extend HubSpotSDK::Internal::Type::Enum

          NUMBER_PROPERTY_VARIABLE: :NUMBER_PROPERTY_VARIABLE

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::NumberPropertyVariable::operator]
        end
      end
    end
  end
end
