module HubSpotSDK
  module Models
    module Cms
      type o_embed_domains_collection_response =
        {
          results: ::Array[HubSpotSDK::Cms::IntegratorOEmbedDomainModel],
          total_count: Integer
        }

      class OEmbedDomainsCollectionResponse < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Cms::IntegratorOEmbedDomainModel]

        attr_reader total_count: Integer?

        def total_count=: (Integer) -> Integer

        def initialize: (
          results: ::Array[HubSpotSDK::Cms::IntegratorOEmbedDomainModel],
          ?total_count: Integer
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Cms::IntegratorOEmbedDomainModel],
          total_count: Integer
        }
      end
    end
  end
end
