module HubspotSDK
  module Models
    module Cms
      type or_ =
        {
          enclosed_in_parentheses: bool,
          operator: HubspotSDK::Models::Cms::Or::operator,
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: bool
        }

      class Or < HubspotSDK::Internal::Type::BaseModel
        attr_accessor enclosed_in_parentheses: bool

        attr_accessor operator: HubspotSDK::Models::Cms::Or::operator

        attr_reader inputs: ::Array[::Hash[Symbol, top]]?

        def inputs=: (
          ::Array[::Hash[Symbol, top]]
        ) -> ::Array[::Hash[Symbol, top]]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: bool?

        def value=: (bool) -> bool

        def initialize: (
          enclosed_in_parentheses: bool,
          operator: HubspotSDK::Models::Cms::Or::operator,
          ?inputs: ::Array[::Hash[Symbol, top]],
          ?property_name: String,
          ?value: bool
        ) -> void

        def to_hash: -> {
          enclosed_in_parentheses: bool,
          operator: HubspotSDK::Models::Cms::Or::operator,
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: bool
        }

        type operator = :OR

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          OR: :OR

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::Or::operator]
        end
      end
    end
  end
end
