module HubSpotSDK
  module Models
    module Cms
      type padding =
        {
          bottom: HubSpotSDK::Cms::Size,
          left: HubSpotSDK::Cms::Size,
          right: HubSpotSDK::Cms::Size,
          top: HubSpotSDK::Cms::Size
        }

      class Padding < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor bottom: HubSpotSDK::Cms::Size

        attr_accessor left: HubSpotSDK::Cms::Size

        attr_accessor right: HubSpotSDK::Cms::Size

        attr_accessor top: HubSpotSDK::Cms::Size

        def initialize: (
          bottom: HubSpotSDK::Cms::Size,
          left: HubSpotSDK::Cms::Size,
          right: HubSpotSDK::Cms::Size,
          top: HubSpotSDK::Cms::Size
        ) -> void

        def to_hash: -> {
          bottom: HubSpotSDK::Cms::Size,
          left: HubSpotSDK::Cms::Size,
          right: HubSpotSDK::Cms::Size,
          top: HubSpotSDK::Cms::Size
        }
      end
    end
  end
end
