module HubSpotSDK
  module Models
    module Cms
      type page_version =
        {
          id: String,
          object: HubSpotSDK::Cms::PagesPage,
          updated_at: Time,
          user: HubSpotSDK::VersionUser
        }

      class PageVersion < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor object: HubSpotSDK::Cms::PagesPage

        attr_accessor updated_at: Time

        attr_accessor user: HubSpotSDK::VersionUser

        def initialize: (
          id: String,
          object: HubSpotSDK::Cms::PagesPage,
          updated_at: Time,
          user: HubSpotSDK::VersionUser
        ) -> void

        def to_hash: -> {
          id: String,
          object: HubSpotSDK::Cms::PagesPage,
          updated_at: Time,
          user: HubSpotSDK::VersionUser
        }
      end
    end
  end
end
