module HubspotSDK
  module Models
    module Cms
      type page_list_landing_page_folders_params =
        {
          after: String,
          archived: bool,
          created_after: Time,
          created_at: Time,
          created_before: Time,
          limit: Integer,
          property: String,
          sort: ::Array[String],
          updated_after: Time,
          updated_at: Time,
          updated_before: Time
        }
        & HubspotSDK::Internal::Type::request_parameters

      class PageListLandingPageFoldersParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_reader after: String?

        def after=: (String) -> String

        attr_reader archived: bool?

        def archived=: (bool) -> bool

        attr_reader created_after: Time?

        def created_after=: (Time) -> Time

        attr_reader created_at: Time?

        def created_at=: (Time) -> Time

        attr_reader created_before: Time?

        def created_before=: (Time) -> Time

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader property: String?

        def property=: (String) -> String

        attr_reader sort: ::Array[String]?

        def sort=: (::Array[String]) -> ::Array[String]

        attr_reader updated_after: Time?

        def updated_after=: (Time) -> Time

        attr_reader updated_at: Time?

        def updated_at=: (Time) -> Time

        attr_reader updated_before: Time?

        def updated_before=: (Time) -> Time

        def initialize: (
          ?after: String,
          ?archived: bool,
          ?created_after: Time,
          ?created_at: Time,
          ?created_before: Time,
          ?limit: Integer,
          ?property: String,
          ?sort: ::Array[String],
          ?updated_after: Time,
          ?updated_at: Time,
          ?updated_before: Time,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          after: String,
          archived: bool,
          created_after: Time,
          created_at: Time,
          created_before: Time,
          limit: Integer,
          property: String,
          sort: ::Array[String],
          updated_after: Time,
          updated_at: Time,
          updated_before: Time,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
