module HubspotSDK
  module Models
    module Cms
      type parse_number =
        {
          operator: HubspotSDK::Models::Cms::ParseNumber::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: Float
        }

      class ParseNumber < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::ParseNumber::operator

        attr_reader inputs: ::Array[HubspotSDK::Models::Cms::expression]?

        def inputs=: (
          ::Array[HubspotSDK::Models::Cms::expression]
        ) -> ::Array[HubspotSDK::Models::Cms::expression]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: Float?

        def value=: (Float) -> Float

        def initialize: (
          operator: HubspotSDK::Models::Cms::ParseNumber::operator,
          ?inputs: ::Array[HubspotSDK::Models::Cms::expression],
          ?property_name: String,
          ?value: Float
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::ParseNumber::operator,
          inputs: ::Array[HubspotSDK::Models::Cms::expression],
          property_name: String,
          value: Float
        }

        type operator = :PARSE_NUMBER

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          PARSE_NUMBER: :PARSE_NUMBER

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::ParseNumber::operator]
        end
      end
    end
  end
end
