module HubSpotSDK
  module Models
    module Cms
      type period_to_weeks =
        {
          operator: HubSpotSDK::Models::Cms::PeriodToWeeks::operator,
          inputs: ::Array[top],
          property_name: String,
          value: Float
        }

      class PeriodToWeeks < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubSpotSDK::Models::Cms::PeriodToWeeks::operator

        attr_reader inputs: ::Array[top]?

        def inputs=: (::Array[top]) -> ::Array[top]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: Float?

        def value=: (Float) -> Float

        def initialize: (
          operator: HubSpotSDK::Models::Cms::PeriodToWeeks::operator,
          ?inputs: ::Array[top],
          ?property_name: String,
          ?value: Float
        ) -> void

        def to_hash: -> {
          operator: HubSpotSDK::Models::Cms::PeriodToWeeks::operator,
          inputs: ::Array[top],
          property_name: String,
          value: Float
        }

        type operator = :PERIOD_TO_WEEKS

        module Operator
          extend HubSpotSDK::Internal::Type::Enum

          PERIOD_TO_WEEKS: :PERIOD_TO_WEEKS

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::PeriodToWeeks::operator]
        end
      end
    end
  end
end
