module HubSpotSDK
  module Models
    module Cms
      type property_definition =
        {
          object_type_id: String,
          property: HubSpotSDK::Cms::MediaBridgeProperty,
          calculation_expression: top,
          calculation_formula: String,
          definition_source: HubSpotSDK::Cms::PropertyDefinitionSource,
          extension_data: HubSpotSDK::Cms::ExtensionData,
          external_options_meta_data: HubSpotSDK::Cms::ExternalOptionsMetaData,
          fulcrum_portal_id: Integer,
          fulcrum_timestamp: Integer,
          janus_group: String,
          lookup_association_spec: HubSpotSDK::Cms::LookupAssociationSpec,
          permission: HubSpotSDK::Cms::FieldLevelPermission,
          property_definition_source: HubSpotSDK::Cms::DefinitionSource,
          property_requirements: HubSpotSDK::Cms::DefaultRequirements,
          rollup_expression: HubSpotSDK::Cms::RollupExpression
        }

      class PropertyDefinition < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor object_type_id: String

        attr_accessor property: HubSpotSDK::Cms::MediaBridgeProperty

        attr_reader calculation_expression: top?

        def calculation_expression=: (top) -> top

        attr_reader calculation_formula: String?

        def calculation_formula=: (String) -> String

        attr_reader definition_source: HubSpotSDK::Cms::PropertyDefinitionSource?

        def definition_source=: (
          HubSpotSDK::Cms::PropertyDefinitionSource
        ) -> HubSpotSDK::Cms::PropertyDefinitionSource

        attr_reader extension_data: HubSpotSDK::Cms::ExtensionData?

        def extension_data=: (
          HubSpotSDK::Cms::ExtensionData
        ) -> HubSpotSDK::Cms::ExtensionData

        attr_reader external_options_meta_data: HubSpotSDK::Cms::ExternalOptionsMetaData?

        def external_options_meta_data=: (
          HubSpotSDK::Cms::ExternalOptionsMetaData
        ) -> HubSpotSDK::Cms::ExternalOptionsMetaData

        attr_reader fulcrum_portal_id: Integer?

        def fulcrum_portal_id=: (Integer) -> Integer

        attr_reader fulcrum_timestamp: Integer?

        def fulcrum_timestamp=: (Integer) -> Integer

        attr_reader janus_group: String?

        def janus_group=: (String) -> String

        attr_reader lookup_association_spec: HubSpotSDK::Cms::LookupAssociationSpec?

        def lookup_association_spec=: (
          HubSpotSDK::Cms::LookupAssociationSpec
        ) -> HubSpotSDK::Cms::LookupAssociationSpec

        attr_reader permission: HubSpotSDK::Cms::FieldLevelPermission?

        def permission=: (
          HubSpotSDK::Cms::FieldLevelPermission
        ) -> HubSpotSDK::Cms::FieldLevelPermission

        attr_reader property_definition_source: HubSpotSDK::Cms::DefinitionSource?

        def property_definition_source=: (
          HubSpotSDK::Cms::DefinitionSource
        ) -> HubSpotSDK::Cms::DefinitionSource

        attr_reader property_requirements: HubSpotSDK::Cms::DefaultRequirements?

        def property_requirements=: (
          HubSpotSDK::Cms::DefaultRequirements
        ) -> HubSpotSDK::Cms::DefaultRequirements

        attr_reader rollup_expression: HubSpotSDK::Cms::RollupExpression?

        def rollup_expression=: (
          HubSpotSDK::Cms::RollupExpression
        ) -> HubSpotSDK::Cms::RollupExpression

        def initialize: (
          object_type_id: String,
          property: HubSpotSDK::Cms::MediaBridgeProperty,
          ?calculation_expression: top,
          ?calculation_formula: String,
          ?definition_source: HubSpotSDK::Cms::PropertyDefinitionSource,
          ?extension_data: HubSpotSDK::Cms::ExtensionData,
          ?external_options_meta_data: HubSpotSDK::Cms::ExternalOptionsMetaData,
          ?fulcrum_portal_id: Integer,
          ?fulcrum_timestamp: Integer,
          ?janus_group: String,
          ?lookup_association_spec: HubSpotSDK::Cms::LookupAssociationSpec,
          ?permission: HubSpotSDK::Cms::FieldLevelPermission,
          ?property_definition_source: HubSpotSDK::Cms::DefinitionSource,
          ?property_requirements: HubSpotSDK::Cms::DefaultRequirements,
          ?rollup_expression: HubSpotSDK::Cms::RollupExpression
        ) -> void

        def to_hash: -> {
          object_type_id: String,
          property: HubSpotSDK::Cms::MediaBridgeProperty,
          calculation_expression: top,
          calculation_formula: String,
          definition_source: HubSpotSDK::Cms::PropertyDefinitionSource,
          extension_data: HubSpotSDK::Cms::ExtensionData,
          external_options_meta_data: HubSpotSDK::Cms::ExternalOptionsMetaData,
          fulcrum_portal_id: Integer,
          fulcrum_timestamp: Integer,
          janus_group: String,
          lookup_association_spec: HubSpotSDK::Cms::LookupAssociationSpec,
          permission: HubSpotSDK::Cms::FieldLevelPermission,
          property_definition_source: HubSpotSDK::Cms::DefinitionSource,
          property_requirements: HubSpotSDK::Cms::DefaultRequirements,
          rollup_expression: HubSpotSDK::Cms::RollupExpression
        }
      end
    end
  end
end
