module HubspotSDK
  module Models
    module Cms
      type property_definition_source =
        {
          type: HubspotSDK::Models::Cms::PropertyDefinitionSource::type_,
          name: String
        }

      class PropertyDefinitionSource < HubspotSDK::Internal::Type::BaseModel
        attr_accessor type: HubspotSDK::Models::Cms::PropertyDefinitionSource::type_

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (
          type: HubspotSDK::Models::Cms::PropertyDefinitionSource::type_,
          ?name: String
        ) -> void

        def to_hash: -> {
          type: HubspotSDK::Models::Cms::PropertyDefinitionSource::type_,
          name: String
        }

        type type_ = :GLOBAL | :OBJECT_TYPE | :HAVEN_BRANCH | :PORTAL

        module Type
          extend HubspotSDK::Internal::Type::Enum

          GLOBAL: :GLOBAL
          OBJECT_TYPE: :OBJECT_TYPE
          HAVEN_BRANCH: :HAVEN_BRANCH
          PORTAL: :PORTAL

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::PropertyDefinitionSource::type_]
        end
      end
    end
  end
end
