module HubSpotSDK
  module Models
    module Cms
      type rollup_expression =
        {
          association_types: ::Array[HubSpotSDK::AssociationSpec],
          rollup_operator: HubSpotSDK::Models::Cms::RollupExpression::rollup_operator,
          source_object_type_id: String,
          source_property_name: String,
          conditional_expression: top,
          conditional_formula: String,
          empty_rollup_value: String,
          source_compare_by_property_name: String
        }

      class RollupExpression < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor association_types: ::Array[HubSpotSDK::AssociationSpec]

        attr_accessor rollup_operator: HubSpotSDK::Models::Cms::RollupExpression::rollup_operator

        attr_accessor source_object_type_id: String

        attr_accessor source_property_name: String

        attr_reader conditional_expression: top?

        def conditional_expression=: (top) -> top

        attr_reader conditional_formula: String?

        def conditional_formula=: (String) -> String

        attr_reader empty_rollup_value: String?

        def empty_rollup_value=: (String) -> String

        attr_reader source_compare_by_property_name: String?

        def source_compare_by_property_name=: (String) -> String

        def initialize: (
          association_types: ::Array[HubSpotSDK::AssociationSpec],
          rollup_operator: HubSpotSDK::Models::Cms::RollupExpression::rollup_operator,
          source_object_type_id: String,
          source_property_name: String,
          ?conditional_expression: top,
          ?conditional_formula: String,
          ?empty_rollup_value: String,
          ?source_compare_by_property_name: String
        ) -> void

        def to_hash: -> {
          association_types: ::Array[HubSpotSDK::AssociationSpec],
          rollup_operator: HubSpotSDK::Models::Cms::RollupExpression::rollup_operator,
          source_object_type_id: String,
          source_property_name: String,
          conditional_expression: top,
          conditional_formula: String,
          empty_rollup_value: String,
          source_compare_by_property_name: String
        }

        type rollup_operator =
          :AVERAGE
          | :COUNT
          | :EARLIEST_VALUE
          | :LATEST_VALUE
          | :MAX
          | :MAX_BY
          | :MIN
          | :MIN_BY
          | :REFERENCED_ID_SET
          | :REFERENCED_STRING_SET
          | :REFERENCED_STRING_SET_INTERSECTION
          | :SUM
          | :SYNC_MAX_BY
          | :SYNC_MIN_BY
          | :SYNC_VALUE
          | :UNKNOWN_ROLLUP_OPERATOR

        module RollupOperator
          extend HubSpotSDK::Internal::Type::Enum

          AVERAGE: :AVERAGE
          COUNT: :COUNT
          EARLIEST_VALUE: :EARLIEST_VALUE
          LATEST_VALUE: :LATEST_VALUE
          MAX: :MAX
          MAX_BY: :MAX_BY
          MIN: :MIN
          MIN_BY: :MIN_BY
          REFERENCED_ID_SET: :REFERENCED_ID_SET
          REFERENCED_STRING_SET: :REFERENCED_STRING_SET
          REFERENCED_STRING_SET_INTERSECTION: :REFERENCED_STRING_SET_INTERSECTION
          SUM: :SUM
          SYNC_MAX_BY: :SYNC_MAX_BY
          SYNC_MIN_BY: :SYNC_MIN_BY
          SYNC_VALUE: :SYNC_VALUE
          UNKNOWN_ROLLUP_OPERATOR: :UNKNOWN_ROLLUP_OPERATOR

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::RollupExpression::rollup_operator]
        end
      end
    end
  end
end
