module HubSpotSDK
  module Models
    module Cms
      type rollup_expression =
        {
          association_types: ::Array[HubSpotSDK::AssociationSpec],
          rollup_operator: HubSpotSDK::Models::Cms::RollupExpression::rollup_operator,
          source_object_type_id: String,
          source_property_name: String,
          conditional_expression: HubSpotSDK::Models::Cms::RollupExpression::conditional_expression,
          conditional_formula: String,
          empty_rollup_value: String,
          source_compare_by_property_name: String
        }

      class RollupExpression < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor association_types: ::Array[HubSpotSDK::AssociationSpec]

        attr_accessor rollup_operator: HubSpotSDK::Models::Cms::RollupExpression::rollup_operator

        attr_accessor source_object_type_id: String

        attr_accessor source_property_name: String

        attr_reader conditional_expression: HubSpotSDK::Models::Cms::RollupExpression::conditional_expression?

        def conditional_expression=: (
          HubSpotSDK::Models::Cms::RollupExpression::conditional_expression
        ) -> HubSpotSDK::Models::Cms::RollupExpression::conditional_expression

        attr_reader conditional_formula: String?

        def conditional_formula=: (String) -> String

        attr_reader empty_rollup_value: String?

        def empty_rollup_value=: (String) -> String

        attr_reader source_compare_by_property_name: String?

        def source_compare_by_property_name=: (String) -> String

        def initialize: (
          association_types: ::Array[HubSpotSDK::AssociationSpec],
          rollup_operator: HubSpotSDK::Models::Cms::RollupExpression::rollup_operator,
          source_object_type_id: String,
          source_property_name: String,
          ?conditional_expression: HubSpotSDK::Models::Cms::RollupExpression::conditional_expression,
          ?conditional_formula: String,
          ?empty_rollup_value: String,
          ?source_compare_by_property_name: String
        ) -> void

        def to_hash: -> {
          association_types: ::Array[HubSpotSDK::AssociationSpec],
          rollup_operator: HubSpotSDK::Models::Cms::RollupExpression::rollup_operator,
          source_object_type_id: String,
          source_property_name: String,
          conditional_expression: HubSpotSDK::Models::Cms::RollupExpression::conditional_expression,
          conditional_formula: String,
          empty_rollup_value: String,
          source_compare_by_property_name: String
        }

        type rollup_operator =
          :AVERAGE
          | :COUNT
          | :EARLIEST_VALUE
          | :LATEST_VALUE
          | :MAX
          | :MAX_BY
          | :MIN
          | :MIN_BY
          | :REFERENCED_ID_SET
          | :REFERENCED_STRING_SET
          | :REFERENCED_STRING_SET_INTERSECTION
          | :SUM
          | :SYNC_MAX_BY
          | :SYNC_MIN_BY
          | :SYNC_VALUE
          | :UNKNOWN_ROLLUP_OPERATOR

        module RollupOperator
          extend HubSpotSDK::Internal::Type::Enum

          AVERAGE: :AVERAGE
          COUNT: :COUNT
          EARLIEST_VALUE: :EARLIEST_VALUE
          LATEST_VALUE: :LATEST_VALUE
          MAX: :MAX
          MAX_BY: :MAX_BY
          MIN: :MIN
          MIN_BY: :MIN_BY
          REFERENCED_ID_SET: :REFERENCED_ID_SET
          REFERENCED_STRING_SET: :REFERENCED_STRING_SET
          REFERENCED_STRING_SET_INTERSECTION: :REFERENCED_STRING_SET_INTERSECTION
          SUM: :SUM
          SYNC_MAX_BY: :SYNC_MAX_BY
          SYNC_MIN_BY: :SYNC_MIN_BY
          SYNC_VALUE: :SYNC_VALUE
          UNKNOWN_ROLLUP_OPERATOR: :UNKNOWN_ROLLUP_OPERATOR

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::RollupExpression::rollup_operator]
        end

        type conditional_expression =
          HubSpotSDK::Cms::ConstantBoolean
          | HubSpotSDK::Cms::ConstantNumber
          | HubSpotSDK::Cms::ConstantString
          | HubSpotSDK::Cms::BooleanPropertyVariable
          | HubSpotSDK::Cms::StringPropertyVariable
          | HubSpotSDK::Cms::NumberPropertyVariable
          | HubSpotSDK::Cms::TimestampOfPropertyVariable
          | HubSpotSDK::Cms::BooleanTargetPropertyVariable
          | HubSpotSDK::Cms::StringTargetPropertyVariable
          | HubSpotSDK::Cms::NumberTargetPropertyVariable
          | HubSpotSDK::Cms::TimestampOfTargetPropertyVariable
          | HubSpotSDK::Cms::AddNumbers
          | HubSpotSDK::Cms::SubtractNumbers
          | HubSpotSDK::Cms::MultiplyNumbers
          | HubSpotSDK::Cms::DivideNumbers
          | HubSpotSDK::Cms::RoundDownNumbers
          | HubSpotSDK::Cms::RoundUpNumbers
          | HubSpotSDK::Cms::RoundNearestNumbers
          | HubSpotSDK::Cms::UpperCase
          | HubSpotSDK::Cms::LowerCase
          | HubSpotSDK::Cms::ConcatStrings
          | HubSpotSDK::Cms::Contains
          | HubSpotSDK::Cms::BeginsWith
          | HubSpotSDK::Cms::NumberToString
          | HubSpotSDK::Cms::ParseNumber
          | HubSpotSDK::Cms::FetchExchangeRate
          | HubSpotSDK::Cms::FetchCurrencyDecimalPlaces
          | HubSpotSDK::Cms::FetchSingleCurrencyPortalCurrency
          | HubSpotSDK::Cms::DatedExchangeRate
          | HubSpotSDK::Cms::PipelineProbability
          | HubSpotSDK::Cms::MaxNumbers
          | HubSpotSDK::Cms::MinNumbers
          | HubSpotSDK::Cms::LessThan
          | HubSpotSDK::Cms::LessThanOrEqual
          | HubSpotSDK::Cms::MoreThan
          | HubSpotSDK::Cms::MoreThanOrEqual
          | HubSpotSDK::Cms::NumberEquals
          | HubSpotSDK::Cms::StringEquals
          | HubSpotSDK::Cms::IsPipelineStageClosed
          | HubSpotSDK::Cms::Not
          | HubSpotSDK::Cms::Date
          | HubSpotSDK::Cms::Month
          | HubSpotSDK::Cms::Year
          | HubSpotSDK::Cms::Now
          | HubSpotSDK::Cms::TimeBetween
          | HubSpotSDK::Cms::TimeBetweenSkipWeekends
          | HubSpotSDK::Cms::PeriodToMonths
          | HubSpotSDK::Cms::PeriodToWeeks
          | HubSpotSDK::Cms::And
          | HubSpotSDK::Cms::Or
          | HubSpotSDK::Cms::Xor
          | HubSpotSDK::Cms::IfString
          | HubSpotSDK::Cms::IfNumber
          | HubSpotSDK::Cms::IfBoolean
          | HubSpotSDK::Cms::IsPresent
          | HubSpotSDK::Cms::HasEmailReply
          | HubSpotSDK::Cms::HasPlainTextEmailReply
          | HubSpotSDK::Cms::ExtractMostRecentEmailReplyHTML
          | HubSpotSDK::Cms::ExtractMostRecentEmailReplyText
          | HubSpotSDK::Cms::ExtractMostRecentPlainTextEmailReply
          | HubSpotSDK::Cms::SetContainsString
          | HubSpotSDK::Cms::IsEngagementType
          | HubSpotSDK::Cms::FormatFullName
          | HubSpotSDK::Cms::FormatPhoneNumber
          | HubSpotSDK::Cms::FormatSearchablePhoneNumber
          | HubSpotSDK::Cms::AbsoluteValue
          | HubSpotSDK::Cms::SquareRoot
          | HubSpotSDK::Cms::Power
          | HubSpotSDK::Cms::Substring
          | HubSpotSDK::Cms::Euler
          | HubSpotSDK::Cms::StringLength
          | HubSpotSDK::Cms::AddTime
          | HubSpotSDK::Cms::SubtractTime

        module ConditionalExpression
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Cms::RollupExpression::conditional_expression]
        end
      end
    end
  end
end
