module HubspotSDK
  module Models
    module Cms
      type rollup_expression =
        {
          association_types: ::Array[HubspotSDK::AssociationSpec],
          rollup_operator: String,
          source_object_type_id: String,
          source_property_name: String,
          conditional_expression: HubspotSDK::Models::Cms::expression,
          conditional_formula: String,
          empty_rollup_value: String,
          source_compare_by_property_name: String
        }

      class RollupExpression < HubspotSDK::Internal::Type::BaseModel
        attr_accessor association_types: ::Array[HubspotSDK::AssociationSpec]

        attr_accessor rollup_operator: String

        attr_accessor source_object_type_id: String

        attr_accessor source_property_name: String

        attr_reader conditional_expression: HubspotSDK::Models::Cms::expression?

        def conditional_expression=: (
          HubspotSDK::Models::Cms::expression
        ) -> HubspotSDK::Models::Cms::expression

        attr_reader conditional_formula: String?

        def conditional_formula=: (String) -> String

        attr_reader empty_rollup_value: String?

        def empty_rollup_value=: (String) -> String

        attr_reader source_compare_by_property_name: String?

        def source_compare_by_property_name=: (String) -> String

        def initialize: (
          association_types: ::Array[HubspotSDK::AssociationSpec],
          rollup_operator: String,
          source_object_type_id: String,
          source_property_name: String,
          ?conditional_expression: HubspotSDK::Models::Cms::expression,
          ?conditional_formula: String,
          ?empty_rollup_value: String,
          ?source_compare_by_property_name: String
        ) -> void

        def to_hash: -> {
          association_types: ::Array[HubspotSDK::AssociationSpec],
          rollup_operator: String,
          source_object_type_id: String,
          source_property_name: String,
          conditional_expression: HubspotSDK::Models::Cms::expression,
          conditional_formula: String,
          empty_rollup_value: String,
          source_compare_by_property_name: String
        }
      end
    end
  end
end
