module HubspotSDK
  module Models
    module Cms
      type round_down_numbers =
        {
          operator: HubspotSDK::Models::Cms::RoundDownNumbers::operator,
          inputs: ::Array[top],
          property_name: String,
          value: Float
        }

      class RoundDownNumbers < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::RoundDownNumbers::operator

        attr_reader inputs: ::Array[top]?

        def inputs=: (::Array[top]) -> ::Array[top]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: Float?

        def value=: (Float) -> Float

        def initialize: (
          operator: HubspotSDK::Models::Cms::RoundDownNumbers::operator,
          ?inputs: ::Array[top],
          ?property_name: String,
          ?value: Float
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::RoundDownNumbers::operator,
          inputs: ::Array[top],
          property_name: String,
          value: Float
        }

        type operator = :ROUND_DOWN

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          ROUND_DOWN: :ROUND_DOWN

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::RoundDownNumbers::operator]
        end
      end
    end
  end
end
