module HubspotSDK
  module Models
    module Cms
      type set_contains_string =
        {
          operator: HubspotSDK::Models::Cms::SetContainsString::operator,
          string_to_check: ::Hash[Symbol, top],
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: bool
        }

      class SetContainsString < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::SetContainsString::operator

        attr_accessor string_to_check: ::Hash[Symbol, top]

        attr_reader inputs: ::Array[::Hash[Symbol, top]]?

        def inputs=: (
          ::Array[::Hash[Symbol, top]]
        ) -> ::Array[::Hash[Symbol, top]]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: bool?

        def value=: (bool) -> bool

        def initialize: (
          operator: HubspotSDK::Models::Cms::SetContainsString::operator,
          string_to_check: ::Hash[Symbol, top],
          ?inputs: ::Array[::Hash[Symbol, top]],
          ?property_name: String,
          ?value: bool
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::SetContainsString::operator,
          string_to_check: ::Hash[Symbol, top],
          inputs: ::Array[::Hash[Symbol, top]],
          property_name: String,
          value: bool
        }

        type operator = :SET_CONTAINS_STRING

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          SET_CONTAINS_STRING: :SET_CONTAINS_STRING

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::SetContainsString::operator]
        end
      end
    end
  end
end
