module HubspotSDK
  module Models
    module Cms
      type site_search_get_indexed_data_params =
        { type: HubspotSDK::Models::Cms::SiteSearchGetIndexedDataParams::type_ }
        & HubspotSDK::Internal::Type::request_parameters

      class SiteSearchGetIndexedDataParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_reader type: HubspotSDK::Models::Cms::SiteSearchGetIndexedDataParams::type_?

        def type=: (
          HubspotSDK::Models::Cms::SiteSearchGetIndexedDataParams::type_
        ) -> HubspotSDK::Models::Cms::SiteSearchGetIndexedDataParams::type_

        def initialize: (
          ?type: HubspotSDK::Models::Cms::SiteSearchGetIndexedDataParams::type_,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          type: HubspotSDK::Models::Cms::SiteSearchGetIndexedDataParams::type_,
          request_options: HubspotSDK::RequestOptions
        }

        type type_ =
          :LANDING_PAGE
          | :BLOG_POST
          | :SITE_PAGE
          | :KNOWLEDGE_ARTICLE
          | :LISTING_PAGE

        module Type
          extend HubspotSDK::Internal::Type::Enum

          LANDING_PAGE: :LANDING_PAGE
          BLOG_POST: :BLOG_POST
          SITE_PAGE: :SITE_PAGE
          KNOWLEDGE_ARTICLE: :KNOWLEDGE_ARTICLE
          LISTING_PAGE: :LISTING_PAGE

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::SiteSearchGetIndexedDataParams::type_]
        end
      end
    end
  end
end
