module HubSpotSDK
  module Models
    module Cms
      type size = { units: HubSpotSDK::Models::Cms::Size::units, value: Float }

      class Size < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor units: HubSpotSDK::Models::Cms::Size::units

        attr_accessor value: Float

        def initialize: (
          units: HubSpotSDK::Models::Cms::Size::units,
          value: Float
        ) -> void

        def to_hash: -> {
          units: HubSpotSDK::Models::Cms::Size::units,
          value: Float
        }

        type units =
          :CH
          | :CM
          | :EM
          | :EX
          | :IN
          | :LH
          | :MM
          | :PC
          | :PERCENTAGE
          | :PT
          | :PX
          | :Q
          | :REM
          | :VH
          | :VMAX
          | :VMIN
          | :VW

        module Units
          extend HubSpotSDK::Internal::Type::Enum

          CH: :CH
          CM: :CM
          EM: :EM
          EX: :EX
          IN: :IN
          LH: :LH
          MM: :MM
          PC: :PC
          PERCENTAGE: :PERCENTAGE
          PT: :PT
          PX: :PX
          Q: :Q
          REM: :REM
          VH: :VH
          VMAX: :VMAX
          VMIN: :VMIN
          VW: :VW

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::Size::units]
        end
      end
    end
  end
end
