module HubspotSDK
  module Models
    module Cms
      type source_code_extract_async_params =
        { path: String } & HubspotSDK::Internal::Type::request_parameters

      class SourceCodeExtractAsyncParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor path: String

        def initialize: (
          path: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          path: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
