module HubspotSDK
  module Models
    module Cms
      type source_code_create_params =
        {
          environment: String,
          path: String,
          file: HubspotSDK::Internal::file_input
        }
        & HubspotSDK::Internal::Type::request_parameters

      class SourceCodeCreateParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor environment: String

        attr_accessor path: String

        attr_reader file: HubspotSDK::Internal::file_input?

        def file=: (
          HubspotSDK::Internal::file_input
        ) -> HubspotSDK::Internal::file_input

        def initialize: (
          environment: String,
          path: String,
          ?file: HubspotSDK::Internal::file_input,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          environment: String,
          path: String,
          file: HubspotSDK::Internal::file_input,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
