module HubspotSDK
  module Models
    module Cms
      type source_code_get_metadata_params =
        { environment: String, path: String, properties: String }
        & HubspotSDK::Internal::Type::request_parameters

      class SourceCodeGetMetadataParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor environment: String

        attr_accessor path: String

        attr_reader properties: String?

        def properties=: (String) -> String

        def initialize: (
          environment: String,
          path: String,
          ?properties: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          environment: String,
          path: String,
          properties: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
