module HubspotSDK
  module Models
    module Cms
      type streaming_collection_response_with_total_hub_db_table_row_v3 =
        {
          results: ::Array[top],
          total: Integer,
          type: HubspotSDK::Models::Cms::StreamingCollectionResponseWithTotalHubDBTableRowV3::type_,
          paging: HubspotSDK::Marketing::EmailsPaging
        }

      class StreamingCollectionResponseWithTotalHubDBTableRowV3 < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[top]

        attr_accessor total: Integer

        attr_accessor type: HubspotSDK::Models::Cms::StreamingCollectionResponseWithTotalHubDBTableRowV3::type_

        attr_reader paging: HubspotSDK::Marketing::EmailsPaging?

        def paging=: (
          HubspotSDK::Marketing::EmailsPaging
        ) -> HubspotSDK::Marketing::EmailsPaging

        def initialize: (
          results: ::Array[top],
          total: Integer,
          type: HubspotSDK::Models::Cms::StreamingCollectionResponseWithTotalHubDBTableRowV3::type_,
          ?paging: HubspotSDK::Marketing::EmailsPaging
        ) -> void

        def to_hash: -> {
          results: ::Array[top],
          total: Integer,
          type: HubspotSDK::Models::Cms::StreamingCollectionResponseWithTotalHubDBTableRowV3::type_,
          paging: HubspotSDK::Marketing::EmailsPaging
        }

        type type_ = :STREAMING

        module Type
          extend HubspotSDK::Internal::Type::Enum

          STREAMING: :STREAMING

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::StreamingCollectionResponseWithTotalHubDBTableRowV3::type_]
        end
      end
    end
  end
end
