module HubspotSDK
  module Models
    module Cms
      type string_target_property_variable =
        {
          operator: HubspotSDK::Models::Cms::StringTargetPropertyVariable::operator,
          property_name: String,
          value: String
        }

      class StringTargetPropertyVariable < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::StringTargetPropertyVariable::operator

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: String?

        def value=: (String) -> String

        def initialize: (
          operator: HubspotSDK::Models::Cms::StringTargetPropertyVariable::operator,
          ?property_name: String,
          ?value: String
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::StringTargetPropertyVariable::operator,
          property_name: String,
          value: String
        }

        type operator = :STRING_TARGET_PROPERTY_VARIABLE

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          STRING_TARGET_PROPERTY_VARIABLE: :STRING_TARGET_PROPERTY_VARIABLE

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::StringTargetPropertyVariable::operator]
        end
      end
    end
  end
end
