module HubspotSDK
  module Models
    module Cms
      type substring =
        {
          operator: HubspotSDK::Models::Cms::Substring::operator,
          string_to_check: top,
          inputs: ::Array[top],
          property_name: String,
          value: String
        }

      class Substring < HubspotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubspotSDK::Models::Cms::Substring::operator

        attr_accessor string_to_check: top

        attr_reader inputs: ::Array[top]?

        def inputs=: (::Array[top]) -> ::Array[top]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: String?

        def value=: (String) -> String

        def initialize: (
          operator: HubspotSDK::Models::Cms::Substring::operator,
          string_to_check: top,
          ?inputs: ::Array[top],
          ?property_name: String,
          ?value: String
        ) -> void

        def to_hash: -> {
          operator: HubspotSDK::Models::Cms::Substring::operator,
          string_to_check: top,
          inputs: ::Array[top],
          property_name: String,
          value: String
        }

        type operator = :SUBSTRING

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          SUBSTRING: :SUBSTRING

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::Substring::operator]
        end
      end
    end
  end
end
