module HubSpotSDK
  module Models
    module Cms
      type time_between =
        {
          operator: HubSpotSDK::Models::Cms::TimeBetween::operator,
          inputs: ::Array[top],
          property_name: String,
          value: Float
        }

      class TimeBetween < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor operator: HubSpotSDK::Models::Cms::TimeBetween::operator

        attr_reader inputs: ::Array[top]?

        def inputs=: (::Array[top]) -> ::Array[top]

        attr_reader property_name: String?

        def property_name=: (String) -> String

        attr_reader value: Float?

        def value=: (Float) -> Float

        def initialize: (
          operator: HubSpotSDK::Models::Cms::TimeBetween::operator,
          ?inputs: ::Array[top],
          ?property_name: String,
          ?value: Float
        ) -> void

        def to_hash: -> {
          operator: HubSpotSDK::Models::Cms::TimeBetween::operator,
          inputs: ::Array[top],
          property_name: String,
          value: Float
        }

        type operator = :TIME_BETWEEN

        module Operator
          extend HubSpotSDK::Internal::Type::Enum

          TIME_BETWEEN: :TIME_BETWEEN

          def self?.values: -> ::Array[HubSpotSDK::Models::Cms::TimeBetween::operator]
        end
      end
    end
  end
end
