module HubSpotSDK
  module Models
    module Cms
      type unified_collection_response_with_total_base_hub_db_table_row_v3 =
        HubSpotSDK::Cms::RandomAccessCollectionResponseWithTotalHubDBTableRowV3
        | HubSpotSDK::Cms::StreamingCollectionResponseWithTotalHubDBTableRowV3

      module UnifiedCollectionResponseWithTotalBaseHubDBTableRowV3
        extend HubSpotSDK::Internal::Type::Union

        def self?.variants: -> ::Array[HubSpotSDK::Models::Cms::unified_collection_response_with_total_base_hub_db_table_row_v3]
      end
    end
  end
end
