module HubspotSDK
  module Models
    module Cms
      type update_video_object_request =
        {
          media_type: HubspotSDK::Models::Cms::UpdateVideoObjectRequest::media_type,
          bearer_token: String,
          details_page_link: String,
          duration: Integer,
          external_id: String,
          file_url: String,
          oembed_url: String,
          poster_url: String,
          thumbnail_url: String,
          title: String,
          transcript_url: String
        }

      class UpdateVideoObjectRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor media_type: HubspotSDK::Models::Cms::UpdateVideoObjectRequest::media_type

        attr_reader bearer_token: String?

        def bearer_token=: (String) -> String

        attr_reader details_page_link: String?

        def details_page_link=: (String) -> String

        attr_reader duration: Integer?

        def duration=: (Integer) -> Integer

        attr_reader external_id: String?

        def external_id=: (String) -> String

        attr_reader file_url: String?

        def file_url=: (String) -> String

        attr_reader oembed_url: String?

        def oembed_url=: (String) -> String

        attr_reader poster_url: String?

        def poster_url=: (String) -> String

        attr_reader thumbnail_url: String?

        def thumbnail_url=: (String) -> String

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader transcript_url: String?

        def transcript_url=: (String) -> String

        def initialize: (
          media_type: HubspotSDK::Models::Cms::UpdateVideoObjectRequest::media_type,
          ?bearer_token: String,
          ?details_page_link: String,
          ?duration: Integer,
          ?external_id: String,
          ?file_url: String,
          ?oembed_url: String,
          ?poster_url: String,
          ?thumbnail_url: String,
          ?title: String,
          ?transcript_url: String
        ) -> void

        def to_hash: -> {
          media_type: HubspotSDK::Models::Cms::UpdateVideoObjectRequest::media_type,
          bearer_token: String,
          details_page_link: String,
          duration: Integer,
          external_id: String,
          file_url: String,
          oembed_url: String,
          poster_url: String,
          thumbnail_url: String,
          title: String,
          transcript_url: String
        }

        type media_type = :VIDEO

        module MediaType
          extend HubspotSDK::Internal::Type::Enum

          VIDEO: :VIDEO

          def self?.values: -> ::Array[HubspotSDK::Models::Cms::UpdateVideoObjectRequest::media_type]
        end
      end
    end
  end
end
