module HubspotSDK
  module Models
    module Cms
      type update_languages_request_v_next =
        { languages: ::Hash[Symbol, String], primary_id: String }

      class UpdateLanguagesRequestVNext < HubspotSDK::Internal::Type::BaseModel
        attr_accessor languages: ::Hash[Symbol, String]

        attr_accessor primary_id: String

        def initialize: (
          languages: ::Hash[Symbol, String],
          primary_id: String
        ) -> void

        def to_hash: -> {
          languages: ::Hash[Symbol, String],
          primary_id: String
        }
      end
    end
  end
end
