module HubspotSDK
  module Models
    module Cms
      type variant = {  }

      class Variant < HubspotSDK::Internal::Type::BaseModel
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
