module HubSpotSDK
  module Resources
    class Marketing
      class Transactional
        class SingleEmail
          def send_: (
            contact_properties: ::Hash[Symbol, String],
            custom_properties: ::Hash[Symbol, top],
            email_id: Integer,
            message: HubSpotSDK::Marketing::PublicSingleSendEmail,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Marketing::EmailSendStatusView

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
