module HubspotSDK
  module Resources
    class Marketing
      class Transactional
        class SingleEmail
          def send_: (
            email_id: Integer,
            message: HubspotSDK::Marketing::PublicSingleSendEmail,
            ?contact_properties: ::Hash[Symbol, String],
            ?custom_properties: ::Hash[Symbol, top],
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Marketing::EmailSendStatusView

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
