module HubSpotSDK
  module Models
    module CommunicationPreferences
      type communication_preference_get_statuses_params =
        {
          subscriber_id_string: String,
          channel: HubSpotSDK::Models::CommunicationPreferences::CommunicationPreferenceGetStatusesParams::channel,
          business_unit_id: Integer
        }
        & HubSpotSDK::Internal::Type::request_parameters

      class CommunicationPreferenceGetStatusesParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor subscriber_id_string: String

        attr_accessor channel: HubSpotSDK::Models::CommunicationPreferences::CommunicationPreferenceGetStatusesParams::channel

        attr_reader business_unit_id: Integer?

        def business_unit_id=: (Integer) -> Integer

        def initialize: (
          subscriber_id_string: String,
          channel: HubSpotSDK::Models::CommunicationPreferences::CommunicationPreferenceGetStatusesParams::channel,
          ?business_unit_id: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          subscriber_id_string: String,
          channel: HubSpotSDK::Models::CommunicationPreferences::CommunicationPreferenceGetStatusesParams::channel,
          business_unit_id: Integer,
          request_options: HubSpotSDK::RequestOptions
        }

        type channel = :EMAIL

        module Channel
          extend HubSpotSDK::Internal::Type::Enum

          EMAIL: :EMAIL

          def self?.values: -> ::Array[HubSpotSDK::Models::CommunicationPreferences::CommunicationPreferenceGetStatusesParams::channel]
        end
      end
    end
  end
end
