module HubspotSDK
  module Models
    module CommunicationPreferences
      type communication_preference_unsubscribe_params =
        {  } & HubspotSDK::Internal::Type::request_parameters

      class CommunicationPreferenceUnsubscribeParams < HubspotSDK::Models::CommunicationPreferences::PublicUpdateSubscriptionStatusRequest
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        def initialize: (?request_options: HubspotSDK::request_opts) -> void

        def to_hash: -> { request_options: HubspotSDK::RequestOptions }
      end
    end
  end
end
