module HubSpotSDK
  module Models
    module CommunicationPreferences
      type communication_preference_generate_links_params =
        {
          channel: HubSpotSDK::Models::CommunicationPreferences::LinkGenerationRequest::channel,
          business_unit_id: Integer
        }
        & HubSpotSDK::Internal::Type::request_parameters

      class CommunicationPreferenceGenerateLinksParams < HubSpotSDK::Models::CommunicationPreferences::LinkGenerationRequest
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        def channel: -> HubSpotSDK::Models::CommunicationPreferences::LinkGenerationRequest::channel

        def channel=: (
          HubSpotSDK::Models::CommunicationPreferences::LinkGenerationRequest::channel _
        ) -> HubSpotSDK::Models::CommunicationPreferences::LinkGenerationRequest::channel

        def business_unit_id: -> Integer?

        def business_unit_id=: (Integer _) -> Integer

        def initialize: (
          channel: HubSpotSDK::Models::CommunicationPreferences::LinkGenerationRequest::channel,
          ?business_unit_id: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          channel: HubSpotSDK::Models::CommunicationPreferences::LinkGenerationRequest::channel,
          business_unit_id: Integer,
          request_options: HubSpotSDK::RequestOptions
        }

        type channel = :EMAIL

        module Channel
          extend HubSpotSDK::Internal::Type::Enum

          EMAIL: :EMAIL

          def self?.values: -> ::Array[HubSpotSDK::Models::CommunicationPreferences::LinkGenerationRequest::channel]
        end
      end
    end
  end
end
