module HubspotSDK
  module Models
    module CommunicationPreferences
      type definition_list_params =
        { business_unit_id: Integer, include_translations: bool }
        & HubspotSDK::Internal::Type::request_parameters

      class DefinitionListParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_reader business_unit_id: Integer?

        def business_unit_id=: (Integer) -> Integer

        attr_reader include_translations: bool?

        def include_translations=: (bool) -> bool

        def initialize: (
          ?business_unit_id: Integer,
          ?include_translations: bool,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          business_unit_id: Integer,
          include_translations: bool,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
