module HubSpotSDK
  module Models
    module CommunicationPreferences
      type link_generation_request =
        {
          subscriber_id_string: String,
          language: String,
          subscription_id: Integer
        }

      class LinkGenerationRequest < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor subscriber_id_string: String

        attr_reader language: String?

        def language=: (String) -> String

        attr_reader subscription_id: Integer?

        def subscription_id=: (Integer) -> Integer

        def initialize: (
          subscriber_id_string: String,
          ?language: String,
          ?subscription_id: Integer
        ) -> void

        def to_hash: -> {
          subscriber_id_string: String,
          language: String,
          subscription_id: Integer
        }
      end
    end
  end
end
