module HubspotSDK
  module Models
    module CommunicationPreferences
      type public_subscription_statuses_response =
        {
          recipient: String,
          subscription_statuses: ::Array[HubspotSDK::CommunicationPreferences::PublicSubscriptionStatus]
        }

      class PublicSubscriptionStatusesResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor recipient: String

        attr_accessor subscription_statuses: ::Array[HubspotSDK::CommunicationPreferences::PublicSubscriptionStatus]

        def initialize: (
          recipient: String,
          subscription_statuses: ::Array[HubspotSDK::CommunicationPreferences::PublicSubscriptionStatus]
        ) -> void

        def to_hash: -> {
          recipient: String,
          subscription_statuses: ::Array[HubspotSDK::CommunicationPreferences::PublicSubscriptionStatus]
        }
      end
    end
  end
end
