module HubspotSDK
  module Resources
    class Crm
      class Extensions
        class Calling
          class ChannelConnectionSettings
            def create: (
              Integer app_id,
              is_ready: bool,
              url: String,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Crm::Extensions::ChannelConnectionSettingsResponse

            def update: (
              Integer app_id,
              ?is_ready: bool,
              ?url: String,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Crm::Extensions::ChannelConnectionSettingsResponse

            def delete: (
              Integer app_id,
              ?request_options: HubspotSDK::request_opts
            ) -> nil

            def get: (
              Integer app_id,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Crm::Extensions::ChannelConnectionSettingsResponse

            def initialize: (client: HubspotSDK::Client) -> void
          end
        end
      end
    end
  end
end
