module HubspotSDK
  module Resources
    class Crm
      class Extensions
        class Calling
          class Settings
            def create: (
              Integer app_id,
              name: String,
              url: String,
              ?height: Integer,
              ?is_ready: bool,
              ?supports_custom_objects: bool,
              ?supports_inbound_calling: bool,
              ?uses_calling_window: bool,
              ?uses_remote: bool,
              ?width: Integer,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Webhooks::SettingsResponse

            def update: (
              Integer app_id,
              ?height: Integer,
              ?is_ready: bool,
              ?name: String,
              ?supports_custom_objects: bool,
              ?supports_inbound_calling: bool,
              ?url: String,
              ?uses_calling_window: bool,
              ?uses_remote: bool,
              ?width: Integer,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Webhooks::SettingsResponse

            def delete: (
              Integer app_id,
              ?request_options: HubspotSDK::request_opts
            ) -> nil

            def get: (
              Integer app_id,
              ?request_options: HubspotSDK::request_opts
            ) -> HubspotSDK::Webhooks::SettingsResponse

            def initialize: (client: HubspotSDK::Client) -> void
          end
        end
      end
    end
  end
end
