module HubspotSDK
  class Client < HubspotSDK::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader access_token: String?

    attr_reader developer_api_key: String?

    attr_reader account: HubspotSDK::Resources::Account

    attr_reader automation: HubspotSDK::Resources::Automation

    attr_reader cms: HubspotSDK::Resources::Cms

    attr_reader crm: HubspotSDK::Resources::Crm

    attr_reader data_studio: HubspotSDK::Resources::DataStudio

    attr_reader events: HubspotSDK::Resources::Events

    attr_reader files: HubspotSDK::Resources::Files

    attr_reader marketing: HubspotSDK::Resources::Marketing

    attr_reader meta: HubspotSDK::Resources::Meta

    attr_reader scheduler: HubspotSDK::Resources::Scheduler

    attr_reader settings: HubspotSDK::Resources::Settings

    private def auth_headers: -> ::Hash[String, String]

    private def auth_query: -> ::Hash[String, String]

    def initialize: (
      ?access_token: String?,
      ?developer_api_key: String?,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
