module HubSpotSDK
  module Internal
    extend HubSpotSDK::Internal::Util::SorbetRuntimeSupport

    type file_input = Pathname | StringIO | IO | String | HubSpotSDK::FilePart

    OMIT: Object
  end
end
