module HubspotSDK
  class AbTestCreateRequestVNext = HubspotSDK::Models::AbTestCreateRequestVNext

  module Account = HubspotSDK::Models::Account

  class ActionResponse = HubspotSDK::Models::ActionResponse

  class AssociationDefinition = HubspotSDK::Models::AssociationDefinition

  class AssociationDefinitionEgg = HubspotSDK::Models::AssociationDefinitionEgg

  class AssociationSpec = HubspotSDK::Models::AssociationSpec

  module Auth = HubspotSDK::Models::Auth

  module Automation = HubspotSDK::Models::Automation

  class AutomationActionsOption = HubspotSDK::Models::AutomationActionsOption

  class BatchInputPropertyName = HubspotSDK::Models::BatchInputPropertyName

  class BatchInputPublicObjectID = HubspotSDK::Models::BatchInputPublicObjectID

  class BatchInputString = HubspotSDK::Models::BatchInputString

  class BatchReadInputPropertyName = HubspotSDK::Models::BatchReadInputPropertyName

  module BusinessUnits = HubspotSDK::Models::BusinessUnits

  module Cms = HubspotSDK::Models::Cms

  class CollectionResponsePropertyGroupNoPaging = HubspotSDK::Models::CollectionResponsePropertyGroupNoPaging

  module CommunicationPreferences = HubspotSDK::Models::CommunicationPreferences

  module Conversations = HubspotSDK::Models::Conversations

  module Crm = HubspotSDK::Models::Crm

  class Error = HubspotSDK::Models::Error

  class ErrorDetail = HubspotSDK::Models::ErrorDetail

  module Events = HubspotSDK::Models::Events

  module Files = HubspotSDK::Models::Files

  class ForwardPaging = HubspotSDK::Models::ForwardPaging

  module Marketing = HubspotSDK::Models::Marketing

  module Meta = HubspotSDK::Models::Meta

  class NextPage = HubspotSDK::Models::NextPage

  class ObjectTypeDefinition = HubspotSDK::Models::ObjectTypeDefinition

  class ObjectTypeDefinitionLabels = HubspotSDK::Models::ObjectTypeDefinitionLabels

  class ObjectTypeDefinitionPatch = HubspotSDK::Models::ObjectTypeDefinitionPatch

  class Option = HubspotSDK::Models::Option

  class OptionInput = HubspotSDK::Models::OptionInput

  class Paging = HubspotSDK::Models::Paging

  class PreviousPage = HubspotSDK::Models::PreviousPage

  class Property = HubspotSDK::Models::Property

  class PropertyGroup = HubspotSDK::Models::PropertyGroup

  class PropertyGroupCreate = HubspotSDK::Models::PropertyGroupCreate

  class PropertyGroupUpdate = HubspotSDK::Models::PropertyGroupUpdate

  class PropertyModificationMetadata = HubspotSDK::Models::PropertyModificationMetadata

  class PropertyName = HubspotSDK::Models::PropertyName

  class PropertyValue = HubspotSDK::Models::PropertyValue

  class PublicObjectID = HubspotSDK::Models::PublicObjectID

  module Scheduler = HubspotSDK::Models::Scheduler

  module Settings = HubspotSDK::Models::Settings

  class StandardError = HubspotSDK::Models::StandardError

  class TaskLocator = HubspotSDK::Models::TaskLocator

  class VersionUser = HubspotSDK::Models::VersionUser

  module Webhooks = HubspotSDK::Models::Webhooks
end
