module HubspotSDK
  module Account = HubspotSDK::Models::Account

  module Crm = HubspotSDK::Models::Crm

  class Error = HubspotSDK::Models::Error

  class ErrorDetail = HubspotSDK::Models::ErrorDetail

  class ForwardPaging = HubspotSDK::Models::ForwardPaging

  class NextPage = HubspotSDK::Models::NextPage
end
