module HubSpotSDK
  class AbTestCreateRequestVNext = HubSpotSDK::Models::AbTestCreateRequestVNext

  module Account = HubSpotSDK::Models::Account

  class ActionResponse = HubSpotSDK::Models::ActionResponse

  class AssociationDefinition = HubSpotSDK::Models::AssociationDefinition

  class AssociationDefinitionEgg = HubSpotSDK::Models::AssociationDefinitionEgg

  class AssociationSpec = HubSpotSDK::Models::AssociationSpec

  module Auth = HubSpotSDK::Models::Auth

  module Automation = HubSpotSDK::Models::Automation

  class AutomationActionsOption = HubSpotSDK::Models::AutomationActionsOption

  class BatchInputPropertyCreate = HubSpotSDK::Models::BatchInputPropertyCreate

  class BatchInputPropertyName = HubSpotSDK::Models::BatchInputPropertyName

  class BatchInputPublicObjectID = HubSpotSDK::Models::BatchInputPublicObjectID

  class BatchInputString = HubSpotSDK::Models::BatchInputString

  class BatchReadInputPropertyName = HubSpotSDK::Models::BatchReadInputPropertyName

  module BusinessUnits = HubSpotSDK::Models::BusinessUnits

  module Cms = HubSpotSDK::Models::Cms

  class CollectionResponsePropertyGroupNoPaging = HubSpotSDK::Models::CollectionResponsePropertyGroupNoPaging

  module CommunicationPreferences = HubSpotSDK::Models::CommunicationPreferences

  module Conversations = HubSpotSDK::Models::Conversations

  module Crm = HubSpotSDK::Models::Crm

  class Error = HubSpotSDK::Models::Error

  class ErrorDetail = HubSpotSDK::Models::ErrorDetail

  module Events = HubSpotSDK::Models::Events

  module Files = HubSpotSDK::Models::Files

  class ForwardPaging = HubSpotSDK::Models::ForwardPaging

  module Marketing = HubSpotSDK::Models::Marketing

  module Meta = HubSpotSDK::Models::Meta

  class NextPage = HubSpotSDK::Models::NextPage

  class ObjectTypeDefinition = HubSpotSDK::Models::ObjectTypeDefinition

  class ObjectTypeDefinitionLabels = HubSpotSDK::Models::ObjectTypeDefinitionLabels

  class ObjectTypeDefinitionPatch = HubSpotSDK::Models::ObjectTypeDefinitionPatch

  class Option = HubSpotSDK::Models::Option

  class OptionInput = HubSpotSDK::Models::OptionInput

  class Paging = HubSpotSDK::Models::Paging

  class PreviousPage = HubSpotSDK::Models::PreviousPage

  class Property = HubSpotSDK::Models::Property

  class PropertyCreate = HubSpotSDK::Models::PropertyCreate

  class PropertyGroup = HubSpotSDK::Models::PropertyGroup

  class PropertyGroupCreate = HubSpotSDK::Models::PropertyGroupCreate

  class PropertyGroupUpdate = HubSpotSDK::Models::PropertyGroupUpdate

  class PropertyModificationMetadata = HubSpotSDK::Models::PropertyModificationMetadata

  class PropertyName = HubSpotSDK::Models::PropertyName

  class PropertyValue = HubSpotSDK::Models::PropertyValue

  class PublicObjectID = HubSpotSDK::Models::PublicObjectID

  module Scheduler = HubSpotSDK::Models::Scheduler

  module Settings = HubSpotSDK::Models::Settings

  class StandardError = HubSpotSDK::Models::StandardError

  class TaskLocator = HubSpotSDK::Models::TaskLocator

  class VersionUser = HubSpotSDK::Models::VersionUser

  module Webhooks = HubSpotSDK::Models::Webhooks
end
