module HubSpotSDK
  module Resources
    class Crm
      class Associations
        class Batch
          def create: (
            String to_object_id,
            from_object_type: String,
            from_object_id: String,
            to_object_type: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::BatchResponsePublicDefaultAssociation

          def delete: (
            String to_object_type,
            from_object_type: String,
            inputs: ::Array[HubSpotSDK::Crm::PublicAssociationMultiArchive],
            ?request_options: HubSpotSDK::request_opts
          ) -> nil

          def create_default: (
            String to_object_type,
            from_object_type: String,
            inputs: ::Array[HubSpotSDK::Crm::PublicDefaultAssociationMultiPost],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::BatchResponsePublicDefaultAssociation

          def delete_labels: (
            String to_object_type,
            from_object_type: String,
            inputs: ::Array[HubSpotSDK::Crm::PublicAssociationMultiPost],
            ?request_options: HubSpotSDK::request_opts
          ) -> nil

          def get: (
            String to_object_type,
            from_object_type: String,
            inputs: ::Array[HubSpotSDK::Crm::PublicFetchAssociationsBatchRequest],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::BatchResponsePublicAssociationMultiWithLabel

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
