module HubspotSDK
  module Resources
    class Crm
      class Associations
        class Schema
          attr_reader v4: HubspotSDK::Resources::Crm::Associations::Schema::V4

          def list: (
            String to_object_type,
            from_object_type: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Crm::Associations::CollectionResponsePublicAssociationDefinitionNoPaging

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
