module HubSpotSDK
  module Resources
    class CommunicationPreferences
      class Definitions
        def list: (
          ?business_unit_id: Integer,
          ?include_translations: bool,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::CommunicationPreferences::ActionResponseWithResultsSubscriptionDefinition

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
