module HubSpotSDK
  module Resources
    class CommunicationPreferences
      class Statuses
        attr_reader batch: HubSpotSDK::Resources::CommunicationPreferences::Statuses::Batch

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
