module HubSpotSDK
  module Models
    module Settings
      module Currencies
        type exchange_rate_update_exchange_rate_params =
          { exchange_rate_id: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class ExchangeRateUpdateExchangeRateParams < HubSpotSDK::Models::Settings::ExchangeRateMultiplier
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def exchange_rate_id: -> String

          def exchange_rate_id=: (String _) -> String

          def initialize: (
            exchange_rate_id: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            exchange_rate_id: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
