module HubSpotSDK
  module Models
    module Settings
      module Currencies
        type exchange_rate_get_exchange_rate_by_id_params =
          { exchange_rate_id: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class ExchangeRateGetExchangeRateByIDParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor exchange_rate_id: String

          def initialize: (
            exchange_rate_id: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            exchange_rate_id: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
