module HubspotSDK
  module Resources
    class Marketing
      class Emails
        class Statistics
          def get: (
            ?email_ids: ::Array[Integer],
            ?end_timestamp: String,
            ?property: String,
            ?start_timestamp: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Marketing::AggregateEmailStatistics

          def get_histogram: (
            ?email_ids: ::Array[Integer],
            ?end_timestamp: String,
            ?interval: HubspotSDK::Models::Marketing::Emails::StatisticGetHistogramParams::interval,
            ?start_timestamp: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Marketing::CollectionResponseWithTotalEmailStatisticIntervalNoPaging

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
