module HubSpotSDK
  module Models
    module Webhooks
      type app_lifecycle_event_subscription_upsert_request =
        {
          event_type_id: String,
          properties: ::Array[String],
          subscription_type: HubSpotSDK::Models::Webhooks::AppLifecycleEventSubscriptionUpsertRequest::subscription_type
        }

      class AppLifecycleEventSubscriptionUpsertRequest < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor event_type_id: String

        attr_accessor properties: ::Array[String]

        attr_accessor subscription_type: HubSpotSDK::Models::Webhooks::AppLifecycleEventSubscriptionUpsertRequest::subscription_type

        def initialize: (
          event_type_id: String,
          properties: ::Array[String],
          subscription_type: HubSpotSDK::Models::Webhooks::AppLifecycleEventSubscriptionUpsertRequest::subscription_type
        ) -> void

        def to_hash: -> {
          event_type_id: String,
          properties: ::Array[String],
          subscription_type: HubSpotSDK::Models::Webhooks::AppLifecycleEventSubscriptionUpsertRequest::subscription_type
        }

        type subscription_type =
          :OBJECT
          | :ASSOCIATION
          | :EVENT
          | :APP_LIFECYCLE_EVENT
          | :LIST_MEMBERSHIP
          | :GDPR_PRIVACY_DELETION

        module SubscriptionType
          extend HubSpotSDK::Internal::Type::Enum

          OBJECT: :OBJECT
          ASSOCIATION: :ASSOCIATION
          EVENT: :EVENT
          APP_LIFECYCLE_EVENT: :APP_LIFECYCLE_EVENT
          LIST_MEMBERSHIP: :LIST_MEMBERSHIP
          GDPR_PRIVACY_DELETION: :GDPR_PRIVACY_DELETION

          def self?.values: -> ::Array[HubSpotSDK::Models::Webhooks::AppLifecycleEventSubscriptionUpsertRequest::subscription_type]
        end
      end
    end
  end
end
