module HubSpotSDK
  module Models
    module Webhooks
      type collection_response_subscription_response_no_paging =
        { results: ::Array[HubSpotSDK::Webhooks::SubscriptionResponse1] }

      class CollectionResponseSubscriptionResponseNoPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Webhooks::SubscriptionResponse1]

        def initialize: (
          results: ::Array[HubSpotSDK::Webhooks::SubscriptionResponse1]
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Webhooks::SubscriptionResponse1]
        }
      end
    end
  end
end
