module HubSpotSDK
  module Models
    module Webhooks
      type filter_response =
        {
          id: Integer,
          created_at: Integer,
          filter: HubSpotSDK::Webhooks::Filter
        }

      class FilterResponse < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: Integer

        attr_accessor created_at: Integer

        attr_accessor filter: HubSpotSDK::Webhooks::Filter

        def initialize: (
          id: Integer,
          created_at: Integer,
          filter: HubSpotSDK::Webhooks::Filter
        ) -> void

        def to_hash: -> {
          id: Integer,
          created_at: Integer,
          filter: HubSpotSDK::Webhooks::Filter
        }
      end
    end
  end
end
