module HubSpotSDK
  module Models
    module Webhooks
      type filter_create_request =
        { filter: HubSpotSDK::Webhooks::Filter, subscription_id: Integer }

      class FilterCreateRequest < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor filter: HubSpotSDK::Webhooks::Filter

        attr_accessor subscription_id: Integer

        def initialize: (
          filter: HubSpotSDK::Webhooks::Filter,
          subscription_id: Integer
        ) -> void

        def to_hash: -> {
          filter: HubSpotSDK::Webhooks::Filter,
          subscription_id: Integer
        }
      end
    end
  end
end
