module HubspotSDK
  module Models
    module Webhooks
      type settings_change_request =
        {
          target_url: String,
          throttling: HubspotSDK::Webhooks::ThrottlingSettings
        }

      class SettingsChangeRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor target_url: String

        attr_accessor throttling: HubspotSDK::Webhooks::ThrottlingSettings

        def initialize: (
          target_url: String,
          throttling: HubspotSDK::Webhooks::ThrottlingSettings
        ) -> void

        def to_hash: -> {
          target_url: String,
          throttling: HubspotSDK::Webhooks::ThrottlingSettings
        }
      end
    end
  end
end
