module HubSpotSDK
  module Models
    module Webhooks
      type snapshot_status_response =
        {
          id: String,
          initiated_at: Integer,
          status: HubSpotSDK::Models::Webhooks::SnapshotStatusResponse::status,
          completed_at: Integer,
          error_code: HubSpotSDK::Models::Webhooks::SnapshotStatusResponse::error_code,
          message: String
        }

      class SnapshotStatusResponse < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor initiated_at: Integer

        attr_accessor status: HubSpotSDK::Models::Webhooks::SnapshotStatusResponse::status

        attr_reader completed_at: Integer?

        def completed_at=: (Integer) -> Integer

        attr_reader error_code: HubSpotSDK::Models::Webhooks::SnapshotStatusResponse::error_code?

        def error_code=: (
          HubSpotSDK::Models::Webhooks::SnapshotStatusResponse::error_code
        ) -> HubSpotSDK::Models::Webhooks::SnapshotStatusResponse::error_code

        attr_reader message: String?

        def message=: (String) -> String

        def initialize: (
          id: String,
          initiated_at: Integer,
          status: HubSpotSDK::Models::Webhooks::SnapshotStatusResponse::status,
          ?completed_at: Integer,
          ?error_code: HubSpotSDK::Models::Webhooks::SnapshotStatusResponse::error_code,
          ?message: String
        ) -> void

        def to_hash: -> {
          id: String,
          initiated_at: Integer,
          status: HubSpotSDK::Models::Webhooks::SnapshotStatusResponse::status,
          completed_at: Integer,
          error_code: HubSpotSDK::Models::Webhooks::SnapshotStatusResponse::error_code,
          message: String
        }

        type status = :COMPLETED | :EXPIRED | :FAILED | :IN_PROGRESS | :PENDING

        module Status
          extend HubSpotSDK::Internal::Type::Enum

          COMPLETED: :COMPLETED
          EXPIRED: :EXPIRED
          FAILED: :FAILED
          IN_PROGRESS: :IN_PROGRESS
          PENDING: :PENDING

          def self?.values: -> ::Array[HubSpotSDK::Models::Webhooks::SnapshotStatusResponse::status]
        end

        type error_code =
          :INTERNAL_ERROR | :PERMISSION_DENIED | :TIMEOUT | :VALIDATION_ERROR

        module ErrorCode
          extend HubSpotSDK::Internal::Type::Enum

          INTERNAL_ERROR: :INTERNAL_ERROR
          PERMISSION_DENIED: :PERMISSION_DENIED
          TIMEOUT: :TIMEOUT
          VALIDATION_ERROR: :VALIDATION_ERROR

          def self?.values: -> ::Array[HubSpotSDK::Models::Webhooks::SnapshotStatusResponse::error_code]
        end
      end
    end
  end
end
