module HubspotSDK
  module Models
    module Webhooks
      type subscription_list_response =
        { results: ::Array[HubspotSDK::Webhooks::SubscriptionResponse] }

      class SubscriptionListResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubspotSDK::Webhooks::SubscriptionResponse]

        def initialize: (
          results: ::Array[HubspotSDK::Webhooks::SubscriptionResponse]
        ) -> void

        def to_hash: -> {
          results: ::Array[HubspotSDK::Webhooks::SubscriptionResponse]
        }
      end
    end
  end
end
