module HubspotSDK
  module Models
    module Webhooks
      type subscription_batch_update_request = { id: Integer, active: bool }

      class SubscriptionBatchUpdateRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: Integer

        attr_accessor active: bool

        def initialize: (id: Integer, active: bool) -> void

        def to_hash: -> { id: Integer, active: bool }
      end
    end
  end
end
