module HubspotSDK
  module Models
    module Webhooks
      type throttling_settings = { max_concurrent_requests: Integer }

      class ThrottlingSettings < HubspotSDK::Internal::Type::BaseModel
        attr_accessor max_concurrent_requests: Integer

        def initialize: (max_concurrent_requests: Integer) -> void

        def to_hash: -> { max_concurrent_requests: Integer }
      end
    end
  end
end
