module HubspotSDK
  module Models
    module Webhooks
      type webhook_get_subscription_params =
        { app_id: Integer, subscription_id: Integer }
        & HubspotSDK::Internal::Type::request_parameters

      class WebhookGetSubscriptionParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor app_id: Integer

        attr_accessor subscription_id: Integer

        def initialize: (
          app_id: Integer,
          subscription_id: Integer,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          app_id: Integer,
          subscription_id: Integer,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
