module HubSpotSDK
  module Models
    module Webhooks
      type webhook_delete_subscription_params =
        { app_id: Integer, subscription_id: Integer }
        & HubSpotSDK::Internal::Type::request_parameters

      class WebhookDeleteSubscriptionParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor app_id: Integer

        attr_accessor subscription_id: Integer

        def initialize: (
          app_id: Integer,
          subscription_id: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          app_id: Integer,
          subscription_id: Integer,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
