module HubSpotSDK
  module Models
    module Webhooks
      type webhook_delete_subscription_filter_params =
        { filter_id: Integer } & HubSpotSDK::Internal::Type::request_parameters

      class WebhookDeleteSubscriptionFilterParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor filter_id: Integer

        def initialize: (
          filter_id: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          filter_id: Integer,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
