module HubspotSDK
  module Models
    module Webhooks
      type webhook_subscription_get_local_journal_status_params =
        { status_id: String } & HubspotSDK::Internal::Type::request_parameters

      class WebhookSubscriptionGetLocalJournalStatusParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor status_id: String

        def initialize: (
          status_id: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          status_id: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
