module HubspotSDK
  module Models
    module Webhooks
      type webhook_get_latest_journal_batch_params =
        { count: Integer, install_portal_id: Integer }
        & HubspotSDK::Internal::Type::request_parameters

      class WebhookGetLatestJournalBatchParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor count: Integer

        attr_reader install_portal_id: Integer?

        def install_portal_id=: (Integer) -> Integer

        def initialize: (
          count: Integer,
          ?install_portal_id: Integer,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          count: Integer,
          install_portal_id: Integer,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
