module HubspotSDK
  module Models
    module Webhooks
      type webhook_subscription_get_subscription_filter_for_subscription_response =
        ::Array[HubspotSDK::Webhooks::FilterResponse]

      WebhookSubscriptionGetSubscriptionFilterForSubscriptionResponse: HubspotSDK::Internal::Type::Converter
    end
  end
end
