module HubSpotSDK
  module Models
    module Webhooks
      type webhook_get_local_journal_batch_from_offset_params =
        { offset: String, count: Integer, install_portal_id: Integer }
        & HubSpotSDK::Internal::Type::request_parameters

      class WebhookGetLocalJournalBatchFromOffsetParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor offset: String

        attr_accessor count: Integer

        attr_reader install_portal_id: Integer?

        def install_portal_id=: (Integer) -> Integer

        def initialize: (
          offset: String,
          count: Integer,
          ?install_portal_id: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          offset: String,
          count: Integer,
          install_portal_id: Integer,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
