module HubspotSDK
  module Models
    module AppWebhooks
      type subscription_patch_request = { active: bool }

      class SubscriptionPatchRequest < HubspotSDK::Internal::Type::BaseModel
        attr_reader active: bool?

        def active=: (bool) -> bool

        def initialize: (?active: bool) -> void

        def to_hash: -> { active: bool }
      end
    end
  end
end
