# frozen_string_literal: true

module HubSpotSDK
  module Models
    module Crm
      # @see HubSpotSDK::Resources::Crm::Pipelines#create
      class Pipeline < HubSpotSDK::Internal::Type::BaseModel
        # @!attribute id
        #   A unique identifier generated by HubSpot that can be used to retrieve and update
        #   the pipeline.
        #
        #   @return [String]
        required :id, String

        # @!attribute archived
        #   Whether the pipeline is archived.
        #
        #   @return [Boolean]
        required :archived, HubSpotSDK::Internal::Type::Boolean

        # @!attribute created_at
        #   The date the pipeline was created. The default pipelines will have createdAt
        #   = 0.
        #
        #   @return [Time]
        required :created_at, Time, api_name: :createdAt

        # @!attribute display_order
        #   The order for displaying this pipeline. If two pipelines have a matching
        #   `displayOrder`, they will be sorted alphabetically by label.
        #
        #   @return [Integer]
        required :display_order, Integer, api_name: :displayOrder

        # @!attribute label
        #   A unique label used to organize pipelines in HubSpot's UI
        #
        #   @return [String]
        required :label, String

        # @!attribute stages
        #   The stages associated with the pipeline. They can be retrieved and updated via
        #   the pipeline stages endpoints.
        #
        #   @return [Array<HubSpotSDK::Models::Crm::PipelineStage>]
        required :stages, -> { HubSpotSDK::Internal::Type::ArrayOf[HubSpotSDK::Crm::PipelineStage] }

        # @!attribute updated_at
        #   The date the pipeline was last updated.
        #
        #   @return [Time]
        required :updated_at, Time, api_name: :updatedAt

        # @!attribute archived_at
        #   The date the pipeline was archived. `archivedAt` will only be present if the
        #   pipeline is archived.
        #
        #   @return [Time, nil]
        optional :archived_at, Time, api_name: :archivedAt

        # @!method initialize(id:, archived:, created_at:, display_order:, label:, stages:, updated_at:, archived_at: nil)
        #   Some parameter documentations has been truncated, see
        #   {HubSpotSDK::Models::Crm::Pipeline} for more details.
        #
        #   @param id [String] A unique identifier generated by HubSpot that can be used to retrieve and update
        #
        #   @param archived [Boolean] Whether the pipeline is archived.
        #
        #   @param created_at [Time] The date the pipeline was created. The default pipelines will have createdAt = 0
        #
        #   @param display_order [Integer] The order for displaying this pipeline. If two pipelines have a matching `displa
        #
        #   @param label [String] A unique label used to organize pipelines in HubSpot's UI
        #
        #   @param stages [Array<HubSpotSDK::Models::Crm::PipelineStage>] The stages associated with the pipeline. They can be retrieved and updated via t
        #
        #   @param updated_at [Time] The date the pipeline was last updated.
        #
        #   @param archived_at [Time] The date the pipeline was archived. `archivedAt` will only be present if the pip
      end
    end
  end
end
