# frozen_string_literal: true

module HubspotSDK
  module Models
    module Crm
      class PipelineStage < HubspotSDK::Internal::Type::BaseModel
        # @!attribute id
        #   A unique identifier generated by HubSpot that can be used to retrieve and update
        #   the pipeline stage.
        #
        #   @return [String]
        required :id, String

        # @!attribute archived
        #   Whether the pipeline is archived.
        #
        #   @return [Boolean]
        required :archived, HubspotSDK::Internal::Type::Boolean

        # @!attribute created_at
        #   The date the pipeline stage was created. The stages on default pipelines will
        #   have createdAt = 0.
        #
        #   @return [Time]
        required :created_at, Time, api_name: :createdAt

        # @!attribute display_order
        #   The order for displaying this pipeline stage. If two pipeline stages have a
        #   matching `displayOrder`, they will be sorted alphabetically by label.
        #
        #   @return [Integer]
        required :display_order, Integer, api_name: :displayOrder

        # @!attribute label
        #   A label used to organize pipeline stages in HubSpot's UI. Each pipeline stage's
        #   label must be unique within that pipeline.
        #
        #   @return [String]
        required :label, String

        # @!attribute metadata
        #   A JSON object containing properties that are not present on all object
        #   pipelines.
        #
        #   For `deals` pipelines, the `probability` field is required
        #   (`{ "probability": 0.5 }`), and represents the likelihood a deal will close.
        #   Possible values are between 0.0 and 1.0 in increments of 0.1.
        #
        #   For `tickets` pipelines, the `ticketState` field is optional
        #   (`{ "ticketState": "OPEN" }`), and represents whether the ticket remains open or
        #   has been closed by a member of your Support team. Possible values are `OPEN` or
        #   `CLOSED`.
        #
        #   @return [Hash{Symbol=>String}]
        required :metadata, HubspotSDK::Internal::Type::HashOf[String]

        # @!attribute updated_at
        #   The date the pipeline stage was last updated.
        #
        #   @return [Time]
        required :updated_at, Time, api_name: :updatedAt

        # @!attribute archived_at
        #   The date the pipeline was archived. `archivedAt` will only be present if the
        #   pipeline is archived.
        #
        #   @return [Time, nil]
        optional :archived_at, Time, api_name: :archivedAt

        # @!attribute write_permissions
        #   Defines the level of write access for the pipeline stage, with possible values
        #   being CRM_PERMISSIONS_ENFORCEMENT, READ_ONLY, or INTERNAL_ONLY.
        #
        #   @return [Symbol, HubspotSDK::Models::Crm::PipelineStage::WritePermissions, nil]
        optional :write_permissions,
                 enum: -> { HubspotSDK::Crm::PipelineStage::WritePermissions },
                 api_name: :writePermissions

        # @!method initialize(id:, archived:, created_at:, display_order:, label:, metadata:, updated_at:, archived_at: nil, write_permissions: nil)
        #   Some parameter documentations has been truncated, see
        #   {HubspotSDK::Models::Crm::PipelineStage} for more details.
        #
        #   A pipeline stage definition.
        #
        #   @param id [String] A unique identifier generated by HubSpot that can be used to retrieve and update
        #
        #   @param archived [Boolean] Whether the pipeline is archived.
        #
        #   @param created_at [Time] The date the pipeline stage was created. The stages on default pipelines will ha
        #
        #   @param display_order [Integer] The order for displaying this pipeline stage. If two pipeline stages have a matc
        #
        #   @param label [String] A label used to organize pipeline stages in HubSpot's UI. Each pipeline stage's
        #
        #   @param metadata [Hash{Symbol=>String}] A JSON object containing properties that are not present on all object pipelines
        #
        #   @param updated_at [Time] The date the pipeline stage was last updated.
        #
        #   @param archived_at [Time] The date the pipeline was archived. `archivedAt` will only be present if the pip
        #
        #   @param write_permissions [Symbol, HubspotSDK::Models::Crm::PipelineStage::WritePermissions] Defines the level of write access for the pipeline stage, with possible values b

        # Defines the level of write access for the pipeline stage, with possible values
        # being CRM_PERMISSIONS_ENFORCEMENT, READ_ONLY, or INTERNAL_ONLY.
        #
        # @see HubspotSDK::Models::Crm::PipelineStage#write_permissions
        module WritePermissions
          extend HubspotSDK::Internal::Type::Enum

          CRM_PERMISSIONS_ENFORCEMENT = :CRM_PERMISSIONS_ENFORCEMENT
          INTERNAL_ONLY = :INTERNAL_ONLY
          READ_ONLY = :READ_ONLY

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
