module HubspotSDK
  module Resources
    class Crm
      class Pipelines
        class Stages
          def create: (
            String pipeline_id,
            object_type: String,
            display_order: Integer,
            label: String,
            ?metadata: ::Hash[Symbol, String],
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Crm::PipelineStage

          def update: (
            String stage_id,
            object_type: String,
            pipeline_id: String,
            ?archived: bool,
            ?display_order: Integer,
            ?label: String,
            ?metadata: ::Hash[Symbol, String],
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Crm::PipelineStage

          def list: (
            String pipeline_id,
            object_type: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Crm::CollectionResponsePipelineStageNoPaging

          def delete: (
            String stage_id,
            object_type: String,
            pipeline_id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> nil

          def get: (
            String stage_id,
            object_type: String,
            pipeline_id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Crm::PipelineStage

          def get_audit: (
            String stage_id,
            object_type: String,
            pipeline_id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Crm::CollectionResponsePublicAuditInfoNoPaging

          def replace: (
            String stage_id,
            object_type: String,
            pipeline_id: String,
            display_order: Integer,
            label: String,
            ?metadata: ::Hash[Symbol, String],
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Crm::PipelineStage

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
