module HubSpotSDK
  module Resources
    class Crm
      class DealSplits
        class Batch
          def read: (
            inputs: ::Array[HubSpotSDK::PublicObjectID],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::BatchResponseDealToDealSplits

          def upsert: (
            inputs: ::Array[HubSpotSDK::Crm::PublicDealSplitsCreateRequest],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::BatchResponseDealToDealSplits

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
