module HubSpotSDK
  module Models
    module Crm
      module AssociationsSchema
        type limit_get_by_object_types_params =
          { from_object_type: String, to_object_type: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class LimitGetByObjectTypesParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor from_object_type: String

          attr_accessor to_object_type: String

          def initialize: (
            from_object_type: String,
            to_object_type: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            from_object_type: String,
            to_object_type: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
