module HubSpotSDK
  module Models
    module Crm
      module Objects
        type call_search_params =
          {  } & HubSpotSDK::Internal::Type::request_parameters

        class CallSearchParams < HubSpotSDK::Models::Crm::PublicObjectSearchRequest
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def initialize: (?request_options: HubSpotSDK::request_opts) -> void

          def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
        end
      end
    end
  end
end
