module HubSpotSDK
  module Models
    module Crm
      module Objects
        type commerce_payment_delete_params =
          { commerce_payment_id: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class CommercePaymentDeleteParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor commerce_payment_id: String

          def initialize: (
            commerce_payment_id: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            commerce_payment_id: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
