module HubSpotSDK
  module Models
    module Crm
      module Objects
        type course_delete_params =
          { course_id: String } & HubSpotSDK::Internal::Type::request_parameters

        class CourseDeleteParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor course_id: String

          def initialize: (
            course_id: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            course_id: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
