module HubspotSDK
  module Models
    module Crm
      module Objects
        type course_delete_params =
          { course_id: String } & HubspotSDK::Internal::Type::request_parameters

        class CourseDeleteParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_accessor course_id: String

          def initialize: (
            course_id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            course_id: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
