module HubSpotSDK
  module Models
    module Crm
      module Objects
        type custom_merge_params =
          { object_type: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class CustomMergeParams < HubSpotSDK::Models::Crm::PublicMergeInput
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def object_type: -> String

          def object_type=: (String _) -> String

          def initialize: (
            object_type: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            object_type: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
