module HubSpotSDK
  module Models
    module Crm
      module Objects
        type deal_merge_params =
          {  } & HubSpotSDK::Internal::Type::request_parameters

        class DealMergeParams < HubSpotSDK::Models::Crm::PublicMergeInput
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def initialize: (?request_options: HubSpotSDK::request_opts) -> void

          def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
        end
      end
    end
  end
end
