module HubspotSDK
  module Models
    module CRM
      module Objects
        type deal_split_batch_upsert_params =
          {  } & HubspotSDK::Internal::Type::request_parameters

        class DealSplitBatchUpsertParams < HubspotSDK::Models::CRM::Objects::PublicDealSplitsBatchCreateRequest
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          def initialize: (?request_options: HubspotSDK::request_opts) -> void

          def to_hash: -> { request_options: HubspotSDK::RequestOptions }
        end
      end
    end
  end
end
