module HubspotSDK
  module Models
    module Crm
      module Objects
        type deal_delete_params =
          { deal_id: String } & HubspotSDK::Internal::Type::request_parameters

        class DealDeleteParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_accessor deal_id: String

          def initialize: (
            deal_id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            deal_id: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
