module HubspotSDK
  module Models
    module CRM
      module Objects
        type deal_split_batch_upsert_response =
          {
            completed_at: Time,
            results: ::Array[HubspotSDK::Models::CRM::Objects::DealSplitBatchUpsertResponse::Result],
            started_at: Time,
            status: HubspotSDK::Models::CRM::Objects::DealSplitBatchUpsertResponse::status,
            links: ::Hash[Symbol, String],
            requested_at: Time
          }

        class DealSplitBatchUpsertResponse < HubspotSDK::Internal::Type::BaseModel
          attr_accessor completed_at: Time

          attr_accessor results: ::Array[HubspotSDK::Models::CRM::Objects::DealSplitBatchUpsertResponse::Result]

          attr_accessor started_at: Time

          attr_accessor status: HubspotSDK::Models::CRM::Objects::DealSplitBatchUpsertResponse::status

          attr_reader links: ::Hash[Symbol, String]?

          def links=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

          attr_reader requested_at: Time?

          def requested_at=: (Time) -> Time

          def initialize: (
            completed_at: Time,
            results: ::Array[HubspotSDK::Models::CRM::Objects::DealSplitBatchUpsertResponse::Result],
            started_at: Time,
            status: HubspotSDK::Models::CRM::Objects::DealSplitBatchUpsertResponse::status,
            ?links: ::Hash[Symbol, String],
            ?requested_at: Time
          ) -> void

          def to_hash: -> {
            completed_at: Time,
            results: ::Array[HubspotSDK::Models::CRM::Objects::DealSplitBatchUpsertResponse::Result],
            started_at: Time,
            status: HubspotSDK::Models::CRM::Objects::DealSplitBatchUpsertResponse::status,
            links: ::Hash[Symbol, String],
            requested_at: Time
          }

          type result =
            { id: String, splits: ::Array[HubspotSDK::CRM::SimplePublicObject] }

          class Result < HubspotSDK::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor splits: ::Array[HubspotSDK::CRM::SimplePublicObject]

            def initialize: (
              id: String,
              splits: ::Array[HubspotSDK::CRM::SimplePublicObject]
            ) -> void

            def to_hash: -> {
              id: String,
              splits: ::Array[HubspotSDK::CRM::SimplePublicObject]
            }
          end

          type status = :PENDING | :PROCESSING | :CANCELED | :COMPLETE

          module Status
            extend HubspotSDK::Internal::Type::Enum

            PENDING: :PENDING
            PROCESSING: :PROCESSING
            CANCELED: :CANCELED
            COMPLETE: :COMPLETE

            def self?.values: -> ::Array[HubspotSDK::Models::CRM::Objects::DealSplitBatchUpsertResponse::status]
          end
        end
      end
    end
  end
end
