module HubspotSDK
  module Models
    module Crm
      module Objects
        type fee_delete_params =
          { fee_id: String } & HubspotSDK::Internal::Type::request_parameters

        class FeeDeleteParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_accessor fee_id: String

          def initialize: (
            fee_id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            fee_id: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
