module HubSpotSDK
  module Models
    module Crm
      module Objects
        type fee_delete_params =
          { fee_id: String } & HubSpotSDK::Internal::Type::request_parameters

        class FeeDeleteParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor fee_id: String

          def initialize: (
            fee_id: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            fee_id: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
