module HubSpotSDK
  module Models
    module Crm
      module Objects
        type generic_object_delete_params =
          { object_type: String, object_id_: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class GenericObjectDeleteParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor object_type: String

          attr_accessor object_id_: String

          def initialize: (
            object_type: String,
            object_id_: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            object_type: String,
            object_id_: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
