module HubSpotSDK
  module Models
    module Crm
      module Objects
        type goal_target_delete_params =
          { goal_target_id: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class GoalTargetDeleteParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor goal_target_id: String

          def initialize: (
            goal_target_id: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            goal_target_id: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
