module HubSpotSDK
  module Models
    module Crm
      module Objects
        type invoice_update_params =
          { invoice_id: String, id_property: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class InvoiceUpdateParams < HubSpotSDK::Models::Crm::SimplePublicObjectInput
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def invoice_id: -> String

          def invoice_id=: (String _) -> String

          def id_property: -> String?

          def id_property=: (String _) -> String

          def initialize: (
            invoice_id: String,
            ?id_property: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            invoice_id: String,
            id_property: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
