module HubspotSDK
  module Models
    module Crm
      class ObjectTypePropertyCreate = Objects::ObjectTypePropertyCreate

      module Objects
        type object_type_property_create =
          {
            field_type: String,
            label: String,
            name: String,
            type: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::type_,
            description: String,
            display_order: Integer,
            form_field: bool,
            group_name: String,
            has_unique_value: bool,
            hidden: bool,
            number_display_hint: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::number_display_hint,
            options: ::Array[HubspotSDK::OptionInput],
            option_sort_strategy: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::option_sort_strategy,
            referenced_object_type: String,
            searchable_in_global_search: bool,
            show_currency_symbol: bool,
            text_display_hint: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::text_display_hint
          }

        class ObjectTypePropertyCreate < HubspotSDK::Internal::Type::BaseModel
          attr_accessor field_type: String

          attr_accessor label: String

          attr_accessor name: String

          attr_accessor type: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::type_

          attr_reader description: String?

          def description=: (String) -> String

          attr_reader display_order: Integer?

          def display_order=: (Integer) -> Integer

          attr_reader form_field: bool?

          def form_field=: (bool) -> bool

          attr_reader group_name: String?

          def group_name=: (String) -> String

          attr_reader has_unique_value: bool?

          def has_unique_value=: (bool) -> bool

          attr_reader hidden: bool?

          def hidden=: (bool) -> bool

          attr_reader number_display_hint: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::number_display_hint?

          def number_display_hint=: (
            HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::number_display_hint
          ) -> HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::number_display_hint

          attr_reader options: ::Array[HubspotSDK::OptionInput]?

          def options=: (
            ::Array[HubspotSDK::OptionInput]
          ) -> ::Array[HubspotSDK::OptionInput]

          attr_reader option_sort_strategy: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::option_sort_strategy?

          def option_sort_strategy=: (
            HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::option_sort_strategy
          ) -> HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::option_sort_strategy

          attr_reader referenced_object_type: String?

          def referenced_object_type=: (String) -> String

          attr_reader searchable_in_global_search: bool?

          def searchable_in_global_search=: (bool) -> bool

          attr_reader show_currency_symbol: bool?

          def show_currency_symbol=: (bool) -> bool

          attr_reader text_display_hint: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::text_display_hint?

          def text_display_hint=: (
            HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::text_display_hint
          ) -> HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::text_display_hint

          def initialize: (
            field_type: String,
            label: String,
            name: String,
            type: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::type_,
            ?description: String,
            ?display_order: Integer,
            ?form_field: bool,
            ?group_name: String,
            ?has_unique_value: bool,
            ?hidden: bool,
            ?number_display_hint: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::number_display_hint,
            ?options: ::Array[HubspotSDK::OptionInput],
            ?option_sort_strategy: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::option_sort_strategy,
            ?referenced_object_type: String,
            ?searchable_in_global_search: bool,
            ?show_currency_symbol: bool,
            ?text_display_hint: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::text_display_hint
          ) -> void

          def to_hash: -> {
            field_type: String,
            label: String,
            name: String,
            type: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::type_,
            description: String,
            display_order: Integer,
            form_field: bool,
            group_name: String,
            has_unique_value: bool,
            hidden: bool,
            number_display_hint: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::number_display_hint,
            options: ::Array[HubspotSDK::OptionInput],
            option_sort_strategy: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::option_sort_strategy,
            referenced_object_type: String,
            searchable_in_global_search: bool,
            show_currency_symbol: bool,
            text_display_hint: HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::text_display_hint
          }

          type type_ =
            :string | :number | :date | :datetime | :enumeration | :bool

          module Type
            extend HubspotSDK::Internal::Type::Enum

            STRING: :string
            NUMBER: :number
            DATE: :date
            DATETIME: :datetime
            ENUMERATION: :enumeration
            BOOL: :bool

            def self?.values: -> ::Array[HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::type_]
          end

          type number_display_hint =
            :unformatted
            | :formatted
            | :currency
            | :percentage
            | :duration
            | :probability

          module NumberDisplayHint
            extend HubspotSDK::Internal::Type::Enum

            UNFORMATTED: :unformatted
            FORMATTED: :formatted
            CURRENCY: :currency
            PERCENTAGE: :percentage
            DURATION: :duration
            PROBABILITY: :probability

            def self?.values: -> ::Array[HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::number_display_hint]
          end

          type option_sort_strategy = :DISPLAY_ORDER | :ALPHABETICAL

          module OptionSortStrategy
            extend HubspotSDK::Internal::Type::Enum

            DISPLAY_ORDER: :DISPLAY_ORDER
            ALPHABETICAL: :ALPHABETICAL

            def self?.values: -> ::Array[HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::option_sort_strategy]
          end

          type text_display_hint =
            :unformatted_single_line
            | :multi_line
            | :email
            | :phone_number
            | :domain_name
            | :ip_address
            | :physical_address
            | :postal_code

          module TextDisplayHint
            extend HubspotSDK::Internal::Type::Enum

            UNFORMATTED_SINGLE_LINE: :unformatted_single_line
            MULTI_LINE: :multi_line
            EMAIL: :email
            PHONE_NUMBER: :phone_number
            DOMAIN_NAME: :domain_name
            IP_ADDRESS: :ip_address
            PHYSICAL_ADDRESS: :physical_address
            POSTAL_CODE: :postal_code

            def self?.values: -> ::Array[HubspotSDK::Models::Crm::Objects::ObjectTypePropertyCreate::text_display_hint]
          end
        end
      end
    end
  end
end
