module HubspotSDK
  module Models
    module Crm
      module Objects
        type object_schema =
          {
            id: String,
            associations: ::Array[HubspotSDK::Events::AssociationDefinition],
            labels: HubspotSDK::ObjectTypeDefinitionLabels,
            name: String,
            properties: ::Array[HubspotSDK::Property],
            required_properties: ::Array[String],
            archived: bool,
            created_at: Time,
            created_by_user_id: Integer,
            description: String,
            fully_qualified_name: String,
            object_type_id: String,
            primary_display_property: String,
            searchable_properties: ::Array[String],
            secondary_display_properties: ::Array[String],
            updated_at: Time,
            updated_by_user_id: Integer
          }

        class ObjectSchema < HubspotSDK::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor associations: ::Array[HubspotSDK::Events::AssociationDefinition]

          attr_accessor labels: HubspotSDK::ObjectTypeDefinitionLabels

          attr_accessor name: String

          attr_accessor properties: ::Array[HubspotSDK::Property]

          attr_accessor required_properties: ::Array[String]

          attr_reader archived: bool?

          def archived=: (bool) -> bool

          attr_reader created_at: Time?

          def created_at=: (Time) -> Time

          attr_reader created_by_user_id: Integer?

          def created_by_user_id=: (Integer) -> Integer

          attr_reader description: String?

          def description=: (String) -> String

          attr_reader fully_qualified_name: String?

          def fully_qualified_name=: (String) -> String

          attr_reader object_type_id: String?

          def object_type_id=: (String) -> String

          attr_reader primary_display_property: String?

          def primary_display_property=: (String) -> String

          attr_reader searchable_properties: ::Array[String]?

          def searchable_properties=: (::Array[String]) -> ::Array[String]

          attr_reader secondary_display_properties: ::Array[String]?

          def secondary_display_properties=: (
            ::Array[String]
          ) -> ::Array[String]

          attr_reader updated_at: Time?

          def updated_at=: (Time) -> Time

          attr_reader updated_by_user_id: Integer?

          def updated_by_user_id=: (Integer) -> Integer

          def initialize: (
            id: String,
            associations: ::Array[HubspotSDK::Events::AssociationDefinition],
            labels: HubspotSDK::ObjectTypeDefinitionLabels,
            name: String,
            properties: ::Array[HubspotSDK::Property],
            required_properties: ::Array[String],
            ?archived: bool,
            ?created_at: Time,
            ?created_by_user_id: Integer,
            ?description: String,
            ?fully_qualified_name: String,
            ?object_type_id: String,
            ?primary_display_property: String,
            ?searchable_properties: ::Array[String],
            ?secondary_display_properties: ::Array[String],
            ?updated_at: Time,
            ?updated_by_user_id: Integer
          ) -> void

          def to_hash: -> {
            id: String,
            associations: ::Array[HubspotSDK::Events::AssociationDefinition],
            labels: HubspotSDK::ObjectTypeDefinitionLabels,
            name: String,
            properties: ::Array[HubspotSDK::Property],
            required_properties: ::Array[String],
            archived: bool,
            created_at: Time,
            created_by_user_id: Integer,
            description: String,
            fully_qualified_name: String,
            object_type_id: String,
            primary_display_property: String,
            searchable_properties: ::Array[String],
            secondary_display_properties: ::Array[String],
            updated_at: Time,
            updated_by_user_id: Integer
          }
        end
      end
    end
  end
end
