module HubspotSDK
  module Models
    module Crm
      module Objects
        type partner_client_update_params =
          { partner_client_id: String, id_property: String }
          & HubspotSDK::Internal::Type::request_parameters

        class PartnerClientUpdateParams < HubspotSDK::Models::Crm::SimplePublicObjectInput
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          def partner_client_id: -> String

          def partner_client_id=: (String _) -> String

          def id_property: -> String?

          def id_property=: (String _) -> String

          def initialize: (
            partner_client_id: String,
            ?id_property: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            partner_client_id: String,
            id_property: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
