module HubSpotSDK
  module Models
    module Crm
      module Objects
        type partner_service_update_params =
          { partner_service_id: String, id_property: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class PartnerServiceUpdateParams < HubSpotSDK::Models::Crm::SimplePublicObjectInput
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def partner_service_id: -> String

          def partner_service_id=: (String _) -> String

          def id_property: -> String?

          def id_property=: (String _) -> String

          def initialize: (
            partner_service_id: String,
            ?id_property: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            partner_service_id: String,
            id_property: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
