module HubspotSDK
  module Models
    module Crm
      module Objects
        type postal_mail_delete_params =
          { postal_mail_id: String }
          & HubspotSDK::Internal::Type::request_parameters

        class PostalMailDeleteParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_accessor postal_mail_id: String

          def initialize: (
            postal_mail_id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            postal_mail_id: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
