module HubspotSDK
  module Models
    module CRM
      module Objects
        type public_object_search_request =
          {
            after: String,
            filter_groups: ::Array[HubspotSDK::CRM::FilterGroup],
            limit: Integer,
            properties: ::Array[String],
            sorts: ::Array[String],
            query: String
          }

        class PublicObjectSearchRequest < HubspotSDK::Internal::Type::BaseModel
          attr_accessor after: String

          attr_accessor filter_groups: ::Array[HubspotSDK::CRM::FilterGroup]

          attr_accessor limit: Integer

          attr_accessor properties: ::Array[String]

          attr_accessor sorts: ::Array[String]

          attr_reader query: String?

          def query=: (String) -> String

          def initialize: (
            after: String,
            filter_groups: ::Array[HubspotSDK::CRM::FilterGroup],
            limit: Integer,
            properties: ::Array[String],
            sorts: ::Array[String],
            ?query: String
          ) -> void

          def to_hash: -> {
            after: String,
            filter_groups: ::Array[HubspotSDK::CRM::FilterGroup],
            limit: Integer,
            properties: ::Array[String],
            sorts: ::Array[String],
            query: String
          }
        end
      end
    end
  end
end
