module HubspotSDK
  module Models
    module CRM
      module Objects
        type public_deal_split_input = { owner_id: Integer, percentage: Float }

        class PublicDealSplitInput < HubspotSDK::Internal::Type::BaseModel
          attr_accessor owner_id: Integer

          attr_accessor percentage: Float

          def initialize: (owner_id: Integer, percentage: Float) -> void

          def to_hash: -> { owner_id: Integer, percentage: Float }
        end
      end
    end
  end
end
