module HubspotSDK
  module Models
    module Crm
      module Objects
        type public_deal_splits_batch_create_request =
          {
            inputs: ::Array[HubspotSDK::Crm::Objects::PublicDealSplitsCreateRequest]
          }

        class PublicDealSplitsBatchCreateRequest < HubspotSDK::Internal::Type::BaseModel
          attr_accessor inputs: ::Array[HubspotSDK::Crm::Objects::PublicDealSplitsCreateRequest]

          def initialize: (
            inputs: ::Array[HubspotSDK::Crm::Objects::PublicDealSplitsCreateRequest]
          ) -> void

          def to_hash: -> {
            inputs: ::Array[HubspotSDK::Crm::Objects::PublicDealSplitsCreateRequest]
          }
        end
      end
    end
  end
end
