module HubSpotSDK
  module Models
    module Crm
      module Objects
        type service_update_params =
          { service_id: String, id_property: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class ServiceUpdateParams < HubSpotSDK::Models::Crm::SimplePublicObjectInput
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def service_id: -> String

          def service_id=: (String _) -> String

          def id_property: -> String?

          def id_property=: (String _) -> String

          def initialize: (
            service_id: String,
            ?id_property: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            service_id: String,
            id_property: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
