module HubspotSDK
  module Models
    module Crm
      module Objects
        type subscription_delete_params =
          { subscription_id: String }
          & HubspotSDK::Internal::Type::request_parameters

        class SubscriptionDeleteParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_accessor subscription_id: String

          def initialize: (
            subscription_id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            subscription_id: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
