module HubSpotSDK
  module Models
    module Crm
      module Objects
        type subscription_delete_params =
          { subscription_id: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class SubscriptionDeleteParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor subscription_id: String

          def initialize: (
            subscription_id: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            subscription_id: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
