module HubspotSDK
  module Resources
    class Webhooks
      class WebhookSubscriptions
        class Batch
          def get: (
            inputs: ::Array[String],
            ?install_portal_id: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Webhooks::BatchResponseJournalFetchResponse

          def get_earliest: (
            Integer count,
            ?install_portal_id: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Webhooks::BatchResponseJournalFetchResponse

          def get_latest: (
            Integer count,
            ?install_portal_id: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Webhooks::BatchResponseJournalFetchResponse

          def get_local: (
            inputs: ::Array[String],
            ?install_portal_id: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Webhooks::BatchResponseJournalFetchResponse

          def get_local_earliest: (
            Integer count,
            ?install_portal_id: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Webhooks::BatchResponseJournalFetchResponse

          def get_local_latest: (
            Integer count,
            ?install_portal_id: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Webhooks::BatchResponseJournalFetchResponse

          def get_local_next: (
            Integer count,
            offset: String,
            ?install_portal_id: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Webhooks::BatchResponseJournalFetchResponse

          def get_next: (
            Integer count,
            offset: String,
            ?install_portal_id: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Webhooks::BatchResponseJournalFetchResponse

          def update_subscriptions: (
            Integer app_id,
            inputs: ::Array[HubspotSDK::Webhooks::SubscriptionBatchUpdateRequest],
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Webhooks::BatchResponseSubscriptionResponse

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
