module HubSpotSDK
  module Resources
    class Auth
      class OAuth
        def create_token: (
          ?client_id: String,
          ?client_secret: String,
          ?code: String,
          ?code_verifier: String,
          ?grant_type: HubSpotSDK::Models::Auth::OAuthCreateTokenParams::grant_type,
          ?redirect_uri: String,
          ?refresh_token: String,
          ?scope: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> StringIO

        def introspect_token: (
          ?token: String,
          ?client_id: String,
          ?client_secret: String,
          ?token_type_hint: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Auth::TokenInfoResponseBaseIf

        def revoke_token: (
          ?token: String,
          ?client_id: String,
          ?client_secret: String,
          ?token_type_hint: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> StringIO

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
