module HubSpotSDK
  module Resources
    class Marketing
      class MarketingEvents
        class SubscriberState
          def record_by_email: (
            String subscriber_state,
            external_event_id: String,
            external_account_id: String,
            inputs: ::Array[HubSpotSDK::Marketing::MarketingEventEmailSubscriber],
            ?request_options: HubSpotSDK::request_opts
          ) -> StringIO

          def record_by_id: (
            String subscriber_state,
            external_event_id: String,
            external_account_id: String,
            inputs: ::Array[HubSpotSDK::Marketing::MarketingEventSubscriber],
            ?request_options: HubSpotSDK::request_opts
          ) -> StringIO

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
