module HubSpotSDK
  module Models
    module Marketing
      type aggregate_email_statistics =
        {
          aggregate: HubSpotSDK::Marketing::EmailStatisticsData,
          campaign_aggregations: ::Hash[Symbol, HubSpotSDK::Marketing::EmailStatisticsData],
          emails: ::Array[Integer]
        }

      class AggregateEmailStatistics < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor aggregate: HubSpotSDK::Marketing::EmailStatisticsData

        attr_accessor campaign_aggregations: ::Hash[Symbol, HubSpotSDK::Marketing::EmailStatisticsData]

        attr_accessor emails: ::Array[Integer]

        def initialize: (
          aggregate: HubSpotSDK::Marketing::EmailStatisticsData,
          campaign_aggregations: ::Hash[Symbol, HubSpotSDK::Marketing::EmailStatisticsData],
          emails: ::Array[Integer]
        ) -> void

        def to_hash: -> {
          aggregate: HubSpotSDK::Marketing::EmailStatisticsData,
          campaign_aggregations: ::Hash[Symbol, HubSpotSDK::Marketing::EmailStatisticsData],
          emails: ::Array[Integer]
        }
      end
    end
  end
end
