module HubspotSDK
  module Models
    module Marketing
      type app_info = { id: String, name: String }

      class AppInfo < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String

        def initialize: (id: String, name: String) -> void

        def to_hash: -> { id: String, name: String }
      end
    end
  end
end
