module HubSpotSDK
  module Models
    module Marketing
      type attendance_counters =
        {
          attended: Integer,
          cancelled: Integer,
          no_shows: Integer,
          registered: Integer
        }

      class AttendanceCounters < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor attended: Integer

        attr_accessor cancelled: Integer

        attr_accessor no_shows: Integer

        attr_accessor registered: Integer

        def initialize: (
          attended: Integer,
          cancelled: Integer,
          no_shows: Integer,
          registered: Integer
        ) -> void

        def to_hash: -> {
          attended: Integer,
          cancelled: Integer,
          no_shows: Integer,
          registered: Integer
        }
      end
    end
  end
end
