module HubSpotSDK
  module Models
    module Marketing
      type batch_input_marketing_event_public_object_id_delete_request =
        {
          inputs: ::Array[HubSpotSDK::Marketing::MarketingEventPublicObjectIDDeleteRequest]
        }

      class BatchInputMarketingEventPublicObjectIDDeleteRequest < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubSpotSDK::Marketing::MarketingEventPublicObjectIDDeleteRequest]

        def initialize: (
          inputs: ::Array[HubSpotSDK::Marketing::MarketingEventPublicObjectIDDeleteRequest]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubSpotSDK::Marketing::MarketingEventPublicObjectIDDeleteRequest]
        }
      end
    end
  end
end
