module HubSpotSDK
  module Models
    module Marketing
      type batch_input_public_campaign_read_input =
        { inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignReadInput] }

      class BatchInputPublicCampaignReadInput < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignReadInput]

        def initialize: (
          inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignReadInput]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignReadInput]
        }
      end
    end
  end
end
