module HubSpotSDK
  module Models
    module Marketing
      type batch_input_marketing_event_subscriber =
        { inputs: ::Array[HubSpotSDK::Marketing::MarketingEventSubscriber] }

      class BatchInputMarketingEventSubscriber < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubSpotSDK::Marketing::MarketingEventSubscriber]

        def initialize: (
          inputs: ::Array[HubSpotSDK::Marketing::MarketingEventSubscriber]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubSpotSDK::Marketing::MarketingEventSubscriber]
        }
      end
    end
  end
end
