module HubSpotSDK
  module Models
    module Marketing
      type batch_input_public_campaign_input =
        { inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignInput] }

      class BatchInputPublicCampaignInput < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignInput]

        def initialize: (
          inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignInput]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignInput]
        }
      end
    end
  end
end
