module HubSpotSDK
  module Models
    module Marketing
      type batch_input_marketing_event_create_request_params =
        {
          inputs: ::Array[HubSpotSDK::Marketing::MarketingEventCreateRequestParams]
        }

      class BatchInputMarketingEventCreateRequestParams < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubSpotSDK::Marketing::MarketingEventCreateRequestParams]

        def initialize: (
          inputs: ::Array[HubSpotSDK::Marketing::MarketingEventCreateRequestParams]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubSpotSDK::Marketing::MarketingEventCreateRequestParams]
        }
      end
    end
  end
end
