module HubSpotSDK
  module Models
    module Marketing
      type batch_input_marketing_event_email_subscriber =
        {
          inputs: ::Array[HubSpotSDK::Marketing::MarketingEventEmailSubscriber]
        }

      class BatchInputMarketingEventEmailSubscriber < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubSpotSDK::Marketing::MarketingEventEmailSubscriber]

        def initialize: (
          inputs: ::Array[HubSpotSDK::Marketing::MarketingEventEmailSubscriber]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubSpotSDK::Marketing::MarketingEventEmailSubscriber]
        }
      end
    end
  end
end
