module HubSpotSDK
  module Models
    module Marketing
      type batch_response_public_campaign_with_assets_with_errors =
        {
          completed_at: Time,
          results: ::Array[HubSpotSDK::Marketing::PublicCampaignWithAssets],
          started_at: Time,
          status: HubSpotSDK::Models::Marketing::BatchResponsePublicCampaignWithAssetsWithErrors::status,
          errors: ::Array[HubSpotSDK::StandardError],
          links: ::Hash[Symbol, String],
          num_errors: Integer,
          requested_at: Time
        }

      class BatchResponsePublicCampaignWithAssetsWithErrors < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor completed_at: Time

        attr_accessor results: ::Array[HubSpotSDK::Marketing::PublicCampaignWithAssets]

        attr_accessor started_at: Time

        attr_accessor status: HubSpotSDK::Models::Marketing::BatchResponsePublicCampaignWithAssetsWithErrors::status

        attr_reader errors: ::Array[HubSpotSDK::StandardError]?

        def errors=: (
          ::Array[HubSpotSDK::StandardError]
        ) -> ::Array[HubSpotSDK::StandardError]

        attr_reader links: ::Hash[Symbol, String]?

        def links=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader num_errors: Integer?

        def num_errors=: (Integer) -> Integer

        attr_reader requested_at: Time?

        def requested_at=: (Time) -> Time

        def initialize: (
          completed_at: Time,
          results: ::Array[HubSpotSDK::Marketing::PublicCampaignWithAssets],
          started_at: Time,
          status: HubSpotSDK::Models::Marketing::BatchResponsePublicCampaignWithAssetsWithErrors::status,
          ?errors: ::Array[HubSpotSDK::StandardError],
          ?links: ::Hash[Symbol, String],
          ?num_errors: Integer,
          ?requested_at: Time
        ) -> void

        def to_hash: -> {
          completed_at: Time,
          results: ::Array[HubSpotSDK::Marketing::PublicCampaignWithAssets],
          started_at: Time,
          status: HubSpotSDK::Models::Marketing::BatchResponsePublicCampaignWithAssetsWithErrors::status,
          errors: ::Array[HubSpotSDK::StandardError],
          links: ::Hash[Symbol, String],
          num_errors: Integer,
          requested_at: Time
        }

        type status = :CANCELED | :COMPLETE | :PENDING | :PROCESSING

        module Status
          extend HubSpotSDK::Internal::Type::Enum

          CANCELED: :CANCELED
          COMPLETE: :COMPLETE
          PENDING: :PENDING
          PROCESSING: :PROCESSING

          def self?.values: -> ::Array[HubSpotSDK::Models::Marketing::BatchResponsePublicCampaignWithAssetsWithErrors::status]
        end
      end
    end
  end
end
