module HubSpotSDK
  module Models
    module Marketing
      type batch_input_public_campaign_batch_update_item =
        {
          inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignBatchUpdateItem]
        }

      class BatchInputPublicCampaignBatchUpdateItem < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignBatchUpdateItem]

        def initialize: (
          inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignBatchUpdateItem]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubSpotSDK::Marketing::PublicCampaignBatchUpdateItem]
        }
      end
    end
  end
end
