module HubspotSDK
  module Models
    module Marketing
      type campaign_list_params =
        {
          after: String,
          limit: Integer,
          name: String,
          properties: ::Array[String],
          sort: String
        }
        & HubspotSDK::Internal::Type::request_parameters

      class CampaignListParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_reader after: String?

        def after=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader properties: ::Array[String]?

        def properties=: (::Array[String]) -> ::Array[String]

        attr_reader sort: String?

        def sort=: (String) -> String

        def initialize: (
          ?after: String,
          ?limit: Integer,
          ?name: String,
          ?properties: ::Array[String],
          ?sort: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          after: String,
          limit: Integer,
          name: String,
          properties: ::Array[String],
          sort: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
