module HubSpotSDK
  module Models
    module Marketing
      type collection_response_marketing_event_public_read_response_v2_forward_paging =
        {
          results: ::Array[HubSpotSDK::Marketing::MarketingEventPublicReadResponseV2],
          paging: HubSpotSDK::ForwardPaging
        }

      class CollectionResponseMarketingEventPublicReadResponseV2ForwardPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Marketing::MarketingEventPublicReadResponseV2]

        attr_reader paging: HubSpotSDK::ForwardPaging?

        def paging=: (HubSpotSDK::ForwardPaging) -> HubSpotSDK::ForwardPaging

        def initialize: (
          results: ::Array[HubSpotSDK::Marketing::MarketingEventPublicReadResponseV2],
          ?paging: HubSpotSDK::ForwardPaging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Marketing::MarketingEventPublicReadResponseV2],
          paging: HubSpotSDK::ForwardPaging
        }
      end
    end
  end
end
