module HubSpotSDK
  module Models
    module Marketing
      type collection_response_contact_reference_forward_paging =
        {
          results: ::Array[HubSpotSDK::Marketing::ContactReference],
          paging: HubSpotSDK::ForwardPaging
        }

      class CollectionResponseContactReferenceForwardPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Marketing::ContactReference]

        attr_reader paging: HubSpotSDK::ForwardPaging?

        def paging=: (HubSpotSDK::ForwardPaging) -> HubSpotSDK::ForwardPaging

        def initialize: (
          results: ::Array[HubSpotSDK::Marketing::ContactReference],
          ?paging: HubSpotSDK::ForwardPaging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Marketing::ContactReference],
          paging: HubSpotSDK::ForwardPaging
        }
      end
    end
  end
end
