module HubspotSDK
  module Models
    module Marketing
      type collection_response_with_total_public_campaign =
        {
          results: ::Array[HubspotSDK::Marketing::PublicCampaign],
          total: Integer,
          paging: HubspotSDK::Paging
        }

      class CollectionResponseWithTotalPublicCampaign < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubspotSDK::Marketing::PublicCampaign]

        attr_accessor total: Integer

        attr_reader paging: HubspotSDK::Paging?

        def paging=: (HubspotSDK::Paging) -> HubspotSDK::Paging

        def initialize: (
          results: ::Array[HubspotSDK::Marketing::PublicCampaign],
          total: Integer,
          ?paging: HubspotSDK::Paging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubspotSDK::Marketing::PublicCampaign],
          total: Integer,
          paging: HubspotSDK::Paging
        }
      end
    end
  end
end
