module HubspotSDK
  module Models
    module Marketing
      type contact_reference = { id: String }

      class ContactReference < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end
    end
  end
end
