module HubspotSDK
  module Models
    module Marketing
      type dependent_field =
        {
          dependent_condition: HubspotSDK::Marketing::DependentFieldFilter,
          dependent_field: HubspotSDK::Models::Marketing::DependentField::dependent_field
        }

      class DependentField < HubspotSDK::Internal::Type::BaseModel
        attr_accessor dependent_condition: HubspotSDK::Marketing::DependentFieldFilter

        attr_accessor dependent_field: HubspotSDK::Models::Marketing::DependentField::dependent_field

        def initialize: (
          dependent_condition: HubspotSDK::Marketing::DependentFieldFilter,
          dependent_field: HubspotSDK::Models::Marketing::DependentField::dependent_field
        ) -> void

        def to_hash: -> {
          dependent_condition: HubspotSDK::Marketing::DependentFieldFilter,
          dependent_field: HubspotSDK::Models::Marketing::DependentField::dependent_field
        }

        type dependent_field =
          HubspotSDK::Marketing::EmailField
          | HubspotSDK::Marketing::PhoneField
          | HubspotSDK::Marketing::MobilePhoneField
          | HubspotSDK::Marketing::SingleLineTextField
          | HubspotSDK::Marketing::MultiLineTextField
          | HubspotSDK::Marketing::NumberField
          | HubspotSDK::Marketing::SingleCheckboxField
          | HubspotSDK::Marketing::MultipleCheckboxesField
          | HubspotSDK::Marketing::DropdownField
          | HubspotSDK::Marketing::RadioField
          | HubspotSDK::Marketing::DatepickerField
          | HubspotSDK::Marketing::FileField
          | HubspotSDK::Marketing::PaymentLinkRadioField

        module DependentField
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Marketing::DependentField::dependent_field]
        end
      end
    end
  end
end
