module HubSpotSDK
  module Models
    module Marketing
      type email_statistic_interval =
        {
          aggregations: HubSpotSDK::Marketing::EmailStatisticsData,
          interval: HubSpotSDK::Marketing::Interval
        }

      class EmailStatisticInterval < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor aggregations: HubSpotSDK::Marketing::EmailStatisticsData

        attr_accessor interval: HubSpotSDK::Marketing::Interval

        def initialize: (
          aggregations: HubSpotSDK::Marketing::EmailStatisticsData,
          interval: HubSpotSDK::Marketing::Interval
        ) -> void

        def to_hash: -> {
          aggregations: HubSpotSDK::Marketing::EmailStatisticsData,
          interval: HubSpotSDK::Marketing::Interval
        }
      end
    end
  end
end
