module HubspotSDK
  module Models
    module Marketing
      type email_list_revisions_params =
        { email_id: String, after: String, before: String, limit: Integer }
        & HubspotSDK::Internal::Type::request_parameters

      class EmailListRevisionsParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor email_id: String

        attr_reader after: String?

        def after=: (String) -> String

        attr_reader before: String?

        def before=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        def initialize: (
          email_id: String,
          ?after: String,
          ?before: String,
          ?limit: Integer,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          email_id: String,
          after: String,
          before: String,
          limit: Integer,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
