module HubSpotSDK
  module Models
    module Marketing
      type email_get_histogram_params =
        {
          email_ids: ::Array[Integer],
          end_timestamp: String,
          interval: HubSpotSDK::Models::Marketing::EmailGetHistogramParams::interval,
          start_timestamp: String
        }
        & HubSpotSDK::Internal::Type::request_parameters

      class EmailGetHistogramParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_reader email_ids: ::Array[Integer]?

        def email_ids=: (::Array[Integer]) -> ::Array[Integer]

        attr_reader end_timestamp: String?

        def end_timestamp=: (String) -> String

        attr_reader interval: HubSpotSDK::Models::Marketing::EmailGetHistogramParams::interval?

        def interval=: (
          HubSpotSDK::Models::Marketing::EmailGetHistogramParams::interval
        ) -> HubSpotSDK::Models::Marketing::EmailGetHistogramParams::interval

        attr_reader start_timestamp: String?

        def start_timestamp=: (String) -> String

        def initialize: (
          ?email_ids: ::Array[Integer],
          ?end_timestamp: String,
          ?interval: HubSpotSDK::Models::Marketing::EmailGetHistogramParams::interval,
          ?start_timestamp: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          email_ids: ::Array[Integer],
          end_timestamp: String,
          interval: HubSpotSDK::Models::Marketing::EmailGetHistogramParams::interval,
          start_timestamp: String,
          request_options: HubSpotSDK::RequestOptions
        }

        type interval =
          :DAY
          | :HOUR
          | :MINUTE
          | :MONTH
          | :QUARTER
          | :QUARTER_HOUR
          | :SECOND
          | :WEEK
          | :YEAR

        module Interval
          extend HubSpotSDK::Internal::Type::Enum

          DAY: :DAY
          HOUR: :HOUR
          MINUTE: :MINUTE
          MONTH: :MONTH
          QUARTER: :QUARTER
          QUARTER_HOUR: :QUARTER_HOUR
          SECOND: :SECOND
          WEEK: :WEEK
          YEAR: :YEAR

          def self?.values: -> ::Array[HubSpotSDK::Models::Marketing::EmailGetHistogramParams::interval]
        end
      end
    end
  end
end
