module HubspotSDK
  module Models
    module Marketing
      type email_statistics_data =
        {
          counters: ::Hash[Symbol, Integer],
          device_breakdown: ::Hash[Symbol, ::Hash[Symbol, Integer]],
          qualifier_stats: ::Hash[Symbol, ::Hash[Symbol, Integer]],
          ratios: ::Hash[Symbol, Float]
        }

      class EmailStatisticsData < HubspotSDK::Internal::Type::BaseModel
        attr_accessor counters: ::Hash[Symbol, Integer]

        attr_accessor device_breakdown: ::Hash[Symbol, ::Hash[Symbol, Integer]]

        attr_accessor qualifier_stats: ::Hash[Symbol, ::Hash[Symbol, Integer]]

        attr_accessor ratios: ::Hash[Symbol, Float]

        def initialize: (
          counters: ::Hash[Symbol, Integer],
          device_breakdown: ::Hash[Symbol, ::Hash[Symbol, Integer]],
          qualifier_stats: ::Hash[Symbol, ::Hash[Symbol, Integer]],
          ratios: ::Hash[Symbol, Float]
        ) -> void

        def to_hash: -> {
          counters: ::Hash[Symbol, Integer],
          device_breakdown: ::Hash[Symbol, ::Hash[Symbol, Integer]],
          qualifier_stats: ::Hash[Symbol, ::Hash[Symbol, Integer]],
          ratios: ::Hash[Symbol, Float]
        }
      end
    end
  end
end
