module HubspotSDK
  module Models
    module Marketing
      type email_statistic_interval =
        {
          aggregations: HubspotSDK::Marketing::EmailStatisticsData,
          interval: HubspotSDK::Marketing::Interval
        }

      class EmailStatisticInterval < HubspotSDK::Internal::Type::BaseModel
        attr_accessor aggregations: HubspotSDK::Marketing::EmailStatisticsData

        attr_accessor interval: HubspotSDK::Marketing::Interval

        def initialize: (
          aggregations: HubspotSDK::Marketing::EmailStatisticsData,
          interval: HubspotSDK::Marketing::Interval
        ) -> void

        def to_hash: -> {
          aggregations: HubspotSDK::Marketing::EmailStatisticsData,
          interval: HubspotSDK::Marketing::Interval
        }
      end
    end
  end
end
