module HubSpotSDK
  module Models
    module Marketing
      type email_get_ab_test_variation_params =
        {
          email_id: String,
          archived: bool,
          included_properties: ::Array[String],
          include_stats: bool,
          marketing_campaign_names: bool,
          variant_stats: bool,
          workflow_names: bool
        }
        & HubSpotSDK::Internal::Type::request_parameters

      class EmailGetAbTestVariationParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor email_id: String

        attr_reader archived: bool?

        def archived=: (bool) -> bool

        attr_reader included_properties: ::Array[String]?

        def included_properties=: (::Array[String]) -> ::Array[String]

        attr_reader include_stats: bool?

        def include_stats=: (bool) -> bool

        attr_reader marketing_campaign_names: bool?

        def marketing_campaign_names=: (bool) -> bool

        attr_reader variant_stats: bool?

        def variant_stats=: (bool) -> bool

        attr_reader workflow_names: bool?

        def workflow_names=: (bool) -> bool

        def initialize: (
          email_id: String,
          ?archived: bool,
          ?included_properties: ::Array[String],
          ?include_stats: bool,
          ?marketing_campaign_names: bool,
          ?variant_stats: bool,
          ?workflow_names: bool,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          email_id: String,
          archived: bool,
          included_properties: ::Array[String],
          include_stats: bool,
          marketing_campaign_names: bool,
          variant_stats: bool,
          workflow_names: bool,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
