module HubSpotSDK
  module Models
    module Marketing
      type email_restore_revision_params =
        { email_id: String, revision_id: String }
        & HubSpotSDK::Internal::Type::request_parameters

      class EmailRestoreRevisionParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor email_id: String

        attr_accessor revision_id: String

        def initialize: (
          email_id: String,
          revision_id: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          email_id: String,
          revision_id: String,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
