module HubspotSDK
  module Models
    module Marketing
      type email_send_status_view =
        {
          status: HubspotSDK::Models::Marketing::EmailSendStatusView::status,
          status_id: String,
          completed_at: Time,
          event_id: HubspotSDK::Marketing::EventIDView,
          message: String,
          requested_at: Time,
          send_result: HubspotSDK::Models::Marketing::EmailSendStatusView::send_result,
          started_at: Time
        }

      class EmailSendStatusView < HubspotSDK::Internal::Type::BaseModel
        attr_accessor status: HubspotSDK::Models::Marketing::EmailSendStatusView::status

        attr_accessor status_id: String

        attr_reader completed_at: Time?

        def completed_at=: (Time) -> Time

        attr_reader event_id: HubspotSDK::Marketing::EventIDView?

        def event_id=: (
          HubspotSDK::Marketing::EventIDView
        ) -> HubspotSDK::Marketing::EventIDView

        attr_reader message: String?

        def message=: (String) -> String

        attr_reader requested_at: Time?

        def requested_at=: (Time) -> Time

        attr_reader send_result: HubspotSDK::Models::Marketing::EmailSendStatusView::send_result?

        def send_result=: (
          HubspotSDK::Models::Marketing::EmailSendStatusView::send_result
        ) -> HubspotSDK::Models::Marketing::EmailSendStatusView::send_result

        attr_reader started_at: Time?

        def started_at=: (Time) -> Time

        def initialize: (
          status: HubspotSDK::Models::Marketing::EmailSendStatusView::status,
          status_id: String,
          ?completed_at: Time,
          ?event_id: HubspotSDK::Marketing::EventIDView,
          ?message: String,
          ?requested_at: Time,
          ?send_result: HubspotSDK::Models::Marketing::EmailSendStatusView::send_result,
          ?started_at: Time
        ) -> void

        def to_hash: -> {
          status: HubspotSDK::Models::Marketing::EmailSendStatusView::status,
          status_id: String,
          completed_at: Time,
          event_id: HubspotSDK::Marketing::EventIDView,
          message: String,
          requested_at: Time,
          send_result: HubspotSDK::Models::Marketing::EmailSendStatusView::send_result,
          started_at: Time
        }

        type status = :PENDING | :PROCESSING | :CANCELED | :COMPLETE

        module Status
          extend HubspotSDK::Internal::Type::Enum

          PENDING: :PENDING
          PROCESSING: :PROCESSING
          CANCELED: :CANCELED
          COMPLETE: :COMPLETE

          def self?.values: -> ::Array[HubspotSDK::Models::Marketing::EmailSendStatusView::status]
        end

        type send_result =
          :SENT
          | :IDEMPOTENT_IGNORE
          | :QUEUED
          | :IDEMPOTENT_FAIL
          | :THROTTLED
          | :EMAIL_DISABLED
          | :PORTAL_SUSPENDED
          | :INVALID_TO_ADDRESS
          | :BLOCKED_DOMAIN
          | :PREVIOUSLY_BOUNCED
          | :EMAIL_UNCONFIRMED
          | :PREVIOUS_SPAM
          | :PREVIOUSLY_UNSUBSCRIBED_MESSAGE
          | :PREVIOUSLY_UNSUBSCRIBED_PORTAL
          | :INVALID_FROM_ADDRESS
          | :CAMPAIGN_CANCELLED
          | :VALIDATION_FAILED
          | :MTA_IGNORE
          | :BLOCKED_ADDRESS
          | :PORTAL_OVER_LIMIT
          | :PORTAL_EXPIRED
          | :PORTAL_MISSING_MARKETING_SCOPE
          | :MISSING_TEMPLATE_PROPERTIES
          | :MISSING_REQUIRED_PARAMETER
          | :PORTAL_AUTHENTICATION_FAILURE
          | :MISSING_CONTENT
          | :CORRUPT_INPUT
          | :TEMPLATE_RENDER_EXCEPTION
          | :GRAYMAIL_SUPPRESSED
          | :UNCONFIGURED_SENDING_DOMAIN
          | :UNDELIVERABLE
          | :CANCELLED_ABUSE
          | :QUARANTINED_ADDRESS
          | :ADDRESS_ONLY_ACCEPTED_ON_PROD
          | :PORTAL_NOT_AUTHORIZED_FOR_APPLICATION
          | :ADDRESS_LIST_BOMBED
          | :ADDRESS_OPTED_OUT
          | :RECIPIENT_FATIGUE_SUPPRESSED
          | :TOO_MANY_RECIPIENTS
          | :PREVIOUSLY_UNSUBSCRIBED_BRAND
          | :NON_MARKETABLE_CONTACT
          | :PREVIOUSLY_UNSUBSCRIBED_BUSINESS_UNIT
          | :GDPR_DOI_ENABLED
          | :HUBL_LIMIT_EXCEEDED
          | :LOW_CONTACT_QUALITY_SCORE

        module SendResult
          extend HubspotSDK::Internal::Type::Enum

          SENT: :SENT
          IDEMPOTENT_IGNORE: :IDEMPOTENT_IGNORE
          QUEUED: :QUEUED
          IDEMPOTENT_FAIL: :IDEMPOTENT_FAIL
          THROTTLED: :THROTTLED
          EMAIL_DISABLED: :EMAIL_DISABLED
          PORTAL_SUSPENDED: :PORTAL_SUSPENDED
          INVALID_TO_ADDRESS: :INVALID_TO_ADDRESS
          BLOCKED_DOMAIN: :BLOCKED_DOMAIN
          PREVIOUSLY_BOUNCED: :PREVIOUSLY_BOUNCED
          EMAIL_UNCONFIRMED: :EMAIL_UNCONFIRMED
          PREVIOUS_SPAM: :PREVIOUS_SPAM
          PREVIOUSLY_UNSUBSCRIBED_MESSAGE: :PREVIOUSLY_UNSUBSCRIBED_MESSAGE
          PREVIOUSLY_UNSUBSCRIBED_PORTAL: :PREVIOUSLY_UNSUBSCRIBED_PORTAL
          INVALID_FROM_ADDRESS: :INVALID_FROM_ADDRESS
          CAMPAIGN_CANCELLED: :CAMPAIGN_CANCELLED
          VALIDATION_FAILED: :VALIDATION_FAILED
          MTA_IGNORE: :MTA_IGNORE
          BLOCKED_ADDRESS: :BLOCKED_ADDRESS
          PORTAL_OVER_LIMIT: :PORTAL_OVER_LIMIT
          PORTAL_EXPIRED: :PORTAL_EXPIRED
          PORTAL_MISSING_MARKETING_SCOPE: :PORTAL_MISSING_MARKETING_SCOPE
          MISSING_TEMPLATE_PROPERTIES: :MISSING_TEMPLATE_PROPERTIES
          MISSING_REQUIRED_PARAMETER: :MISSING_REQUIRED_PARAMETER
          PORTAL_AUTHENTICATION_FAILURE: :PORTAL_AUTHENTICATION_FAILURE
          MISSING_CONTENT: :MISSING_CONTENT
          CORRUPT_INPUT: :CORRUPT_INPUT
          TEMPLATE_RENDER_EXCEPTION: :TEMPLATE_RENDER_EXCEPTION
          GRAYMAIL_SUPPRESSED: :GRAYMAIL_SUPPRESSED
          UNCONFIGURED_SENDING_DOMAIN: :UNCONFIGURED_SENDING_DOMAIN
          UNDELIVERABLE: :UNDELIVERABLE
          CANCELLED_ABUSE: :CANCELLED_ABUSE
          QUARANTINED_ADDRESS: :QUARANTINED_ADDRESS
          ADDRESS_ONLY_ACCEPTED_ON_PROD: :ADDRESS_ONLY_ACCEPTED_ON_PROD
          PORTAL_NOT_AUTHORIZED_FOR_APPLICATION: :PORTAL_NOT_AUTHORIZED_FOR_APPLICATION
          ADDRESS_LIST_BOMBED: :ADDRESS_LIST_BOMBED
          ADDRESS_OPTED_OUT: :ADDRESS_OPTED_OUT
          RECIPIENT_FATIGUE_SUPPRESSED: :RECIPIENT_FATIGUE_SUPPRESSED
          TOO_MANY_RECIPIENTS: :TOO_MANY_RECIPIENTS
          PREVIOUSLY_UNSUBSCRIBED_BRAND: :PREVIOUSLY_UNSUBSCRIBED_BRAND
          NON_MARKETABLE_CONTACT: :NON_MARKETABLE_CONTACT
          PREVIOUSLY_UNSUBSCRIBED_BUSINESS_UNIT: :PREVIOUSLY_UNSUBSCRIBED_BUSINESS_UNIT
          GDPR_DOI_ENABLED: :GDPR_DOI_ENABLED
          HUBL_LIMIT_EXCEEDED: :HUBL_LIMIT_EXCEEDED
          LOW_CONTACT_QUALITY_SCORE: :LOW_CONTACT_QUALITY_SCORE

          def self?.values: -> ::Array[HubspotSDK::Models::Marketing::EmailSendStatusView::send_result]
        end
      end
    end
  end
end
