module HubSpotSDK
  module Models
    module Marketing
      type email_send_status_view =
        {
          status: HubSpotSDK::Models::Marketing::EmailSendStatusView::status,
          status_id: String,
          completed_at: Time,
          event_id: HubSpotSDK::Marketing::EventIDView,
          message: String,
          requested_at: Time,
          send_result: HubSpotSDK::Models::Marketing::EmailSendStatusView::send_result,
          started_at: Time
        }

      class EmailSendStatusView < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor status: HubSpotSDK::Models::Marketing::EmailSendStatusView::status

        attr_accessor status_id: String

        attr_reader completed_at: Time?

        def completed_at=: (Time) -> Time

        attr_reader event_id: HubSpotSDK::Marketing::EventIDView?

        def event_id=: (
          HubSpotSDK::Marketing::EventIDView
        ) -> HubSpotSDK::Marketing::EventIDView

        attr_reader message: String?

        def message=: (String) -> String

        attr_reader requested_at: Time?

        def requested_at=: (Time) -> Time

        attr_reader send_result: HubSpotSDK::Models::Marketing::EmailSendStatusView::send_result?

        def send_result=: (
          HubSpotSDK::Models::Marketing::EmailSendStatusView::send_result
        ) -> HubSpotSDK::Models::Marketing::EmailSendStatusView::send_result

        attr_reader started_at: Time?

        def started_at=: (Time) -> Time

        def initialize: (
          status: HubSpotSDK::Models::Marketing::EmailSendStatusView::status,
          status_id: String,
          ?completed_at: Time,
          ?event_id: HubSpotSDK::Marketing::EventIDView,
          ?message: String,
          ?requested_at: Time,
          ?send_result: HubSpotSDK::Models::Marketing::EmailSendStatusView::send_result,
          ?started_at: Time
        ) -> void

        def to_hash: -> {
          status: HubSpotSDK::Models::Marketing::EmailSendStatusView::status,
          status_id: String,
          completed_at: Time,
          event_id: HubSpotSDK::Marketing::EventIDView,
          message: String,
          requested_at: Time,
          send_result: HubSpotSDK::Models::Marketing::EmailSendStatusView::send_result,
          started_at: Time
        }

        type status = :CANCELED | :COMPLETE | :PENDING | :PROCESSING

        module Status
          extend HubSpotSDK::Internal::Type::Enum

          CANCELED: :CANCELED
          COMPLETE: :COMPLETE
          PENDING: :PENDING
          PROCESSING: :PROCESSING

          def self?.values: -> ::Array[HubSpotSDK::Models::Marketing::EmailSendStatusView::status]
        end

        type send_result =
          :ADDRESS_LIST_BOMBED
          | :ADDRESS_ONLY_ACCEPTED_ON_PROD
          | :ADDRESS_OPTED_OUT
          | :ATTACHMENT_DOWNLOAD_QUEUE_FULL
          | :BLOCKED_ADDRESS
          | :BLOCKED_DOMAIN
          | :BRAND_RECIPIENT_FATIGUE_SUPPRESSED
          | :CAMPAIGN_CANCELLED
          | :CANCELLED_ABUSE
          | :CORRUPT_INPUT
          | :EMAIL_DISABLED
          | :EMAIL_UNCONFIRMED
          | :GDPR_DOI_ENABLED
          | :GRAYMAIL_SUPPRESSED
          | :HUBL_LIMIT_EXCEEDED
          | :IDEMPOTENT_FAIL
          | :IDEMPOTENT_IGNORE
          | :INVALID_APP_ID_ATTRIBUTION
          | :INVALID_FROM_ADDRESS
          | :INVALID_TO_ADDRESS
          | :LOW_CONTACT_QUALITY_SCORE
          | :MISSING_CONTENT
          | :MISSING_REQUIRED_PARAMETER
          | :MISSING_TEMPLATE_PROPERTIES
          | :MTA_IGNORE
          | :NON_MARKETABLE_CONTACT
          | :PORTAL_AUTHENTICATION_FAILURE
          | :PORTAL_EXPIRED
          | :PORTAL_MISSING_MARKETING_SCOPE
          | :PORTAL_NOT_AUTHORIZED_FOR_APPLICATION
          | :PORTAL_OVER_LIMIT
          | :PORTAL_SUSPENDED
          | :PREVIOUS_SPAM
          | :PREVIOUSLY_BOUNCED
          | :PREVIOUSLY_UNSUBSCRIBED_BRAND
          | :PREVIOUSLY_UNSUBSCRIBED_BUSINESS_UNIT
          | :PREVIOUSLY_UNSUBSCRIBED_MESSAGE
          | :PREVIOUSLY_UNSUBSCRIBED_PORTAL
          | :QUARANTINED_ADDRESS
          | :QUEUED
          | :RECIPIENT_FATIGUE_SUPPRESSED
          | :SENT
          | :TEMPLATE_RENDER_EXCEPTION
          | :THROTTLED
          | :TOO_MANY_RECIPIENTS
          | :UBB_GOVERNANCE_MISSING
          | :UNCONFIGURED_SENDING_DOMAIN
          | :UNDELIVERABLE
          | :VALIDATION_FAILED

        module SendResult
          extend HubSpotSDK::Internal::Type::Enum

          ADDRESS_LIST_BOMBED: :ADDRESS_LIST_BOMBED
          ADDRESS_ONLY_ACCEPTED_ON_PROD: :ADDRESS_ONLY_ACCEPTED_ON_PROD
          ADDRESS_OPTED_OUT: :ADDRESS_OPTED_OUT
          ATTACHMENT_DOWNLOAD_QUEUE_FULL: :ATTACHMENT_DOWNLOAD_QUEUE_FULL
          BLOCKED_ADDRESS: :BLOCKED_ADDRESS
          BLOCKED_DOMAIN: :BLOCKED_DOMAIN
          BRAND_RECIPIENT_FATIGUE_SUPPRESSED: :BRAND_RECIPIENT_FATIGUE_SUPPRESSED
          CAMPAIGN_CANCELLED: :CAMPAIGN_CANCELLED
          CANCELLED_ABUSE: :CANCELLED_ABUSE
          CORRUPT_INPUT: :CORRUPT_INPUT
          EMAIL_DISABLED: :EMAIL_DISABLED
          EMAIL_UNCONFIRMED: :EMAIL_UNCONFIRMED
          GDPR_DOI_ENABLED: :GDPR_DOI_ENABLED
          GRAYMAIL_SUPPRESSED: :GRAYMAIL_SUPPRESSED
          HUBL_LIMIT_EXCEEDED: :HUBL_LIMIT_EXCEEDED
          IDEMPOTENT_FAIL: :IDEMPOTENT_FAIL
          IDEMPOTENT_IGNORE: :IDEMPOTENT_IGNORE
          INVALID_APP_ID_ATTRIBUTION: :INVALID_APP_ID_ATTRIBUTION
          INVALID_FROM_ADDRESS: :INVALID_FROM_ADDRESS
          INVALID_TO_ADDRESS: :INVALID_TO_ADDRESS
          LOW_CONTACT_QUALITY_SCORE: :LOW_CONTACT_QUALITY_SCORE
          MISSING_CONTENT: :MISSING_CONTENT
          MISSING_REQUIRED_PARAMETER: :MISSING_REQUIRED_PARAMETER
          MISSING_TEMPLATE_PROPERTIES: :MISSING_TEMPLATE_PROPERTIES
          MTA_IGNORE: :MTA_IGNORE
          NON_MARKETABLE_CONTACT: :NON_MARKETABLE_CONTACT
          PORTAL_AUTHENTICATION_FAILURE: :PORTAL_AUTHENTICATION_FAILURE
          PORTAL_EXPIRED: :PORTAL_EXPIRED
          PORTAL_MISSING_MARKETING_SCOPE: :PORTAL_MISSING_MARKETING_SCOPE
          PORTAL_NOT_AUTHORIZED_FOR_APPLICATION: :PORTAL_NOT_AUTHORIZED_FOR_APPLICATION
          PORTAL_OVER_LIMIT: :PORTAL_OVER_LIMIT
          PORTAL_SUSPENDED: :PORTAL_SUSPENDED
          PREVIOUS_SPAM: :PREVIOUS_SPAM
          PREVIOUSLY_BOUNCED: :PREVIOUSLY_BOUNCED
          PREVIOUSLY_UNSUBSCRIBED_BRAND: :PREVIOUSLY_UNSUBSCRIBED_BRAND
          PREVIOUSLY_UNSUBSCRIBED_BUSINESS_UNIT: :PREVIOUSLY_UNSUBSCRIBED_BUSINESS_UNIT
          PREVIOUSLY_UNSUBSCRIBED_MESSAGE: :PREVIOUSLY_UNSUBSCRIBED_MESSAGE
          PREVIOUSLY_UNSUBSCRIBED_PORTAL: :PREVIOUSLY_UNSUBSCRIBED_PORTAL
          QUARANTINED_ADDRESS: :QUARANTINED_ADDRESS
          QUEUED: :QUEUED
          RECIPIENT_FATIGUE_SUPPRESSED: :RECIPIENT_FATIGUE_SUPPRESSED
          SENT: :SENT
          TEMPLATE_RENDER_EXCEPTION: :TEMPLATE_RENDER_EXCEPTION
          THROTTLED: :THROTTLED
          TOO_MANY_RECIPIENTS: :TOO_MANY_RECIPIENTS
          UBB_GOVERNANCE_MISSING: :UBB_GOVERNANCE_MISSING
          UNCONFIGURED_SENDING_DOMAIN: :UNCONFIGURED_SENDING_DOMAIN
          UNDELIVERABLE: :UNDELIVERABLE
          VALIDATION_FAILED: :VALIDATION_FAILED

          def self?.values: -> ::Array[HubSpotSDK::Models::Marketing::EmailSendStatusView::send_result]
        end
      end
    end
  end
end
