module HubSpotSDK
  module Models
    module Marketing
      type email_update_params =
        { email_id: String, query_archived: bool }
        & HubSpotSDK::Internal::Type::request_parameters

      class EmailUpdateParams < HubSpotSDK::Models::Marketing::EmailUpdateRequest
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        def email_id: -> String

        def email_id=: (String _) -> String

        def query_archived: -> bool?

        def query_archived=: (bool _) -> bool

        def initialize: (
          email_id: String,
          ?query_archived: bool,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          email_id: String,
          query_archived: bool,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
