module HubspotSDK
  module Models
    module Marketing
      type event_detail_settings =
        { app_id: Integer, event_details_url: String }

      class EventDetailSettings < HubspotSDK::Internal::Type::BaseModel
        attr_accessor app_id: Integer

        attr_accessor event_details_url: String

        def initialize: (app_id: Integer, event_details_url: String) -> void

        def to_hash: -> { app_id: Integer, event_details_url: String }
      end
    end
  end
end
