module HubspotSDK
  module Models
    module Marketing
      type event_update_by_external_event_id_params =
        { external_account_id: String }
        & HubspotSDK::Internal::Type::request_parameters

      class EventUpdateByExternalEventIDParams < HubspotSDK::Models::Marketing::MarketingEventUpdateRequestParams
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        def external_account_id: -> String

        def external_account_id=: (String _) -> String

        def initialize: (
          external_account_id: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          external_account_id: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
