module HubspotSDK
  module Models
    module Marketing
      type event_id_view = { id: String, created: Time }

      class EventIDView < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created: Time

        def initialize: (id: String, created: Time) -> void

        def to_hash: -> { id: String, created: Time }
      end
    end
  end
end
