module HubspotSDK
  module Models
    module Marketing
      type form_post_submit_action =
        {
          type: HubspotSDK::Models::Marketing::FormPostSubmitAction::type_,
          value: String
        }

      class FormPostSubmitAction < HubspotSDK::Internal::Type::BaseModel
        attr_accessor type: HubspotSDK::Models::Marketing::FormPostSubmitAction::type_

        attr_accessor value: String

        def initialize: (
          type: HubspotSDK::Models::Marketing::FormPostSubmitAction::type_,
          value: String
        ) -> void

        def to_hash: -> {
          type: HubspotSDK::Models::Marketing::FormPostSubmitAction::type_,
          value: String
        }

        type type_ = :redirect_url | :thank_you

        module Type
          extend HubspotSDK::Internal::Type::Enum

          REDIRECT_URL: :redirect_url
          THANK_YOU: :thank_you

          def self?.values: -> ::Array[HubspotSDK::Models::Marketing::FormPostSubmitAction::type_]
        end
      end
    end
  end
end
