module HubspotSDK
  module Models
    module Marketing
      type form_list_params =
        {
          after: String,
          archived: bool,
          form_types: ::Array[HubspotSDK::Models::Marketing::FormListParams::form_type],
          limit: Integer
        }
        & HubspotSDK::Internal::Type::request_parameters

      class FormListParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_reader after: String?

        def after=: (String) -> String

        attr_reader archived: bool?

        def archived=: (bool) -> bool

        attr_reader form_types: ::Array[HubspotSDK::Models::Marketing::FormListParams::form_type]?

        def form_types=: (
          ::Array[HubspotSDK::Models::Marketing::FormListParams::form_type]
        ) -> ::Array[HubspotSDK::Models::Marketing::FormListParams::form_type]

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        def initialize: (
          ?after: String,
          ?archived: bool,
          ?form_types: ::Array[HubspotSDK::Models::Marketing::FormListParams::form_type],
          ?limit: Integer,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          after: String,
          archived: bool,
          form_types: ::Array[HubspotSDK::Models::Marketing::FormListParams::form_type],
          limit: Integer,
          request_options: HubspotSDK::RequestOptions
        }

        type form_type = :hubspot | :captured | :flow | :blog_comment | :all

        module FormType
          extend HubspotSDK::Internal::Type::Enum

          HUBSPOT: :hubspot
          CAPTURED: :captured
          FLOW: :flow
          BLOG_COMMENT: :blog_comment
          ALL: :all

          def self?.values: -> ::Array[HubspotSDK::Models::Marketing::FormListParams::form_type]
        end
      end
    end
  end
end
