module HubspotSDK
  module Models
    module Marketing
      type hub_spot_form_definition_patch_request =
        {
          archived: bool,
          configuration: HubspotSDK::Marketing::HubSpotFormConfiguration,
          display_options: HubspotSDK::Marketing::FormDisplayOptions,
          field_groups: ::Array[HubspotSDK::Marketing::FieldGroup],
          legal_consent_options: HubspotSDK::Models::Marketing::HubSpotFormDefinitionPatchRequest::legal_consent_options,
          name: String
        }

      class HubSpotFormDefinitionPatchRequest < HubspotSDK::Internal::Type::BaseModel
        attr_reader archived: bool?

        def archived=: (bool) -> bool

        attr_reader configuration: HubspotSDK::Marketing::HubSpotFormConfiguration?

        def configuration=: (
          HubspotSDK::Marketing::HubSpotFormConfiguration
        ) -> HubspotSDK::Marketing::HubSpotFormConfiguration

        attr_reader display_options: HubspotSDK::Marketing::FormDisplayOptions?

        def display_options=: (
          HubspotSDK::Marketing::FormDisplayOptions
        ) -> HubspotSDK::Marketing::FormDisplayOptions

        attr_reader field_groups: ::Array[HubspotSDK::Marketing::FieldGroup]?

        def field_groups=: (
          ::Array[HubspotSDK::Marketing::FieldGroup]
        ) -> ::Array[HubspotSDK::Marketing::FieldGroup]

        attr_reader legal_consent_options: HubspotSDK::Models::Marketing::HubSpotFormDefinitionPatchRequest::legal_consent_options?

        def legal_consent_options=: (
          HubspotSDK::Models::Marketing::HubSpotFormDefinitionPatchRequest::legal_consent_options
        ) -> HubspotSDK::Models::Marketing::HubSpotFormDefinitionPatchRequest::legal_consent_options

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (
          ?archived: bool,
          ?configuration: HubspotSDK::Marketing::HubSpotFormConfiguration,
          ?display_options: HubspotSDK::Marketing::FormDisplayOptions,
          ?field_groups: ::Array[HubspotSDK::Marketing::FieldGroup],
          ?legal_consent_options: HubspotSDK::Models::Marketing::HubSpotFormDefinitionPatchRequest::legal_consent_options,
          ?name: String
        ) -> void

        def to_hash: -> {
          archived: bool,
          configuration: HubspotSDK::Marketing::HubSpotFormConfiguration,
          display_options: HubspotSDK::Marketing::FormDisplayOptions,
          field_groups: ::Array[HubspotSDK::Marketing::FieldGroup],
          legal_consent_options: HubspotSDK::Models::Marketing::HubSpotFormDefinitionPatchRequest::legal_consent_options,
          name: String
        }

        type legal_consent_options =
          HubspotSDK::Marketing::LegalConsentOptionsNone
          | HubspotSDK::Marketing::LegalConsentOptionsLegitimateInterest
          | HubspotSDK::Marketing::LegalConsentOptionsExplicitConsentToProcess
          | HubspotSDK::Marketing::LegalConsentOptionsImplicitConsentToProcess

        module LegalConsentOptions
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Marketing::HubSpotFormDefinitionPatchRequest::legal_consent_options]
        end
      end
    end
  end
end
