module HubspotSDK
  module Models
    module Marketing
      type hub_spot_form_definition_create_request =
        {
          archived: bool,
          configuration: HubspotSDK::Marketing::HubSpotFormConfiguration,
          created_at: Time,
          display_options: HubspotSDK::Marketing::FormDisplayOptions,
          field_groups: ::Array[HubspotSDK::Marketing::FieldGroup],
          form_type: HubspotSDK::Models::Marketing::HubSpotFormDefinitionCreateRequest::form_type,
          legal_consent_options: HubspotSDK::Models::Marketing::HubSpotFormDefinitionCreateRequest::legal_consent_options,
          name: String,
          updated_at: Time,
          archived_at: Time
        }

      class HubSpotFormDefinitionCreateRequest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor archived: bool

        attr_accessor configuration: HubspotSDK::Marketing::HubSpotFormConfiguration

        attr_accessor created_at: Time

        attr_accessor display_options: HubspotSDK::Marketing::FormDisplayOptions

        attr_accessor field_groups: ::Array[HubspotSDK::Marketing::FieldGroup]

        attr_accessor form_type: HubspotSDK::Models::Marketing::HubSpotFormDefinitionCreateRequest::form_type

        attr_accessor legal_consent_options: HubspotSDK::Models::Marketing::HubSpotFormDefinitionCreateRequest::legal_consent_options

        attr_accessor name: String

        attr_accessor updated_at: Time

        attr_reader archived_at: Time?

        def archived_at=: (Time) -> Time

        def initialize: (
          archived: bool,
          configuration: HubspotSDK::Marketing::HubSpotFormConfiguration,
          created_at: Time,
          display_options: HubspotSDK::Marketing::FormDisplayOptions,
          field_groups: ::Array[HubspotSDK::Marketing::FieldGroup],
          form_type: HubspotSDK::Models::Marketing::HubSpotFormDefinitionCreateRequest::form_type,
          legal_consent_options: HubspotSDK::Models::Marketing::HubSpotFormDefinitionCreateRequest::legal_consent_options,
          name: String,
          updated_at: Time,
          ?archived_at: Time
        ) -> void

        def to_hash: -> {
          archived: bool,
          configuration: HubspotSDK::Marketing::HubSpotFormConfiguration,
          created_at: Time,
          display_options: HubspotSDK::Marketing::FormDisplayOptions,
          field_groups: ::Array[HubspotSDK::Marketing::FieldGroup],
          form_type: HubspotSDK::Models::Marketing::HubSpotFormDefinitionCreateRequest::form_type,
          legal_consent_options: HubspotSDK::Models::Marketing::HubSpotFormDefinitionCreateRequest::legal_consent_options,
          name: String,
          updated_at: Time,
          archived_at: Time
        }

        type form_type = :hubspot

        module FormType
          extend HubspotSDK::Internal::Type::Enum

          HUBSPOT: :hubspot

          def self?.values: -> ::Array[HubspotSDK::Models::Marketing::HubSpotFormDefinitionCreateRequest::form_type]
        end

        type legal_consent_options =
          HubspotSDK::Marketing::LegalConsentOptionsNone
          | HubspotSDK::Marketing::LegalConsentOptionsLegitimateInterest
          | HubspotSDK::Marketing::LegalConsentOptionsExplicitConsentToProcess
          | HubspotSDK::Marketing::LegalConsentOptionsImplicitConsentToProcess

        module LegalConsentOptions
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Marketing::HubSpotFormDefinitionCreateRequest::legal_consent_options]
        end
      end
    end
  end
end
