module HubspotSDK
  module Models
    module Marketing
      type interval = { end_: Time, start: Time }

      class Interval < HubspotSDK::Internal::Type::BaseModel
        attr_accessor end_: Time

        attr_accessor start: Time

        def initialize: (end_: Time, start: Time) -> void

        def to_hash: -> { end_: Time, start: Time }
      end
    end
  end
end
