module HubspotSDK
  module Models
    module Marketing
      type legal_consent_options_legitimate_interest =
        {
          lawful_basis: HubspotSDK::Models::Marketing::LegalConsentOptionsLegitimateInterest::lawful_basis,
          privacy_text: String,
          subscription_type_ids: ::Array[Integer],
          type: HubspotSDK::Models::Marketing::LegalConsentOptionsLegitimateInterest::type_
        }

      class LegalConsentOptionsLegitimateInterest < HubspotSDK::Internal::Type::BaseModel
        attr_accessor lawful_basis: HubspotSDK::Models::Marketing::LegalConsentOptionsLegitimateInterest::lawful_basis

        attr_accessor privacy_text: String

        attr_accessor subscription_type_ids: ::Array[Integer]

        attr_accessor type: HubspotSDK::Models::Marketing::LegalConsentOptionsLegitimateInterest::type_

        def initialize: (
          lawful_basis: HubspotSDK::Models::Marketing::LegalConsentOptionsLegitimateInterest::lawful_basis,
          privacy_text: String,
          subscription_type_ids: ::Array[Integer],
          type: HubspotSDK::Models::Marketing::LegalConsentOptionsLegitimateInterest::type_
        ) -> void

        def to_hash: -> {
          lawful_basis: HubspotSDK::Models::Marketing::LegalConsentOptionsLegitimateInterest::lawful_basis,
          privacy_text: String,
          subscription_type_ids: ::Array[Integer],
          type: HubspotSDK::Models::Marketing::LegalConsentOptionsLegitimateInterest::type_
        }

        type lawful_basis = :client | :lead | :other

        module LawfulBasis
          extend HubspotSDK::Internal::Type::Enum

          CLIENT: :client
          LEAD: :lead
          OTHER: :other

          def self?.values: -> ::Array[HubspotSDK::Models::Marketing::LegalConsentOptionsLegitimateInterest::lawful_basis]
        end

        type type_ = :legitimate_interest

        module Type
          extend HubspotSDK::Internal::Type::Enum

          LEGITIMATE_INTEREST: :legitimate_interest

          def self?.values: -> ::Array[HubspotSDK::Models::Marketing::LegalConsentOptionsLegitimateInterest::type_]
        end
      end
    end
  end
end
