module HubspotSDK
  module Models
    module Marketing
      type legal_consent_options_explicit_consent_to_process =
        {
          communications_checkboxes: ::Array[HubspotSDK::Marketing::LegalConsentCheckbox],
          privacy_text: String,
          type: HubspotSDK::Models::Marketing::LegalConsentOptionsExplicitConsentToProcess::type_,
          communication_consent_text: String,
          consent_to_process_checkbox_label: String,
          consent_to_process_footer_text: String,
          consent_to_process_text: String
        }

      class LegalConsentOptionsExplicitConsentToProcess < HubspotSDK::Internal::Type::BaseModel
        attr_accessor communications_checkboxes: ::Array[HubspotSDK::Marketing::LegalConsentCheckbox]

        attr_accessor privacy_text: String

        attr_accessor type: HubspotSDK::Models::Marketing::LegalConsentOptionsExplicitConsentToProcess::type_

        attr_reader communication_consent_text: String?

        def communication_consent_text=: (String) -> String

        attr_reader consent_to_process_checkbox_label: String?

        def consent_to_process_checkbox_label=: (String) -> String

        attr_reader consent_to_process_footer_text: String?

        def consent_to_process_footer_text=: (String) -> String

        attr_reader consent_to_process_text: String?

        def consent_to_process_text=: (String) -> String

        def initialize: (
          communications_checkboxes: ::Array[HubspotSDK::Marketing::LegalConsentCheckbox],
          privacy_text: String,
          type: HubspotSDK::Models::Marketing::LegalConsentOptionsExplicitConsentToProcess::type_,
          ?communication_consent_text: String,
          ?consent_to_process_checkbox_label: String,
          ?consent_to_process_footer_text: String,
          ?consent_to_process_text: String
        ) -> void

        def to_hash: -> {
          communications_checkboxes: ::Array[HubspotSDK::Marketing::LegalConsentCheckbox],
          privacy_text: String,
          type: HubspotSDK::Models::Marketing::LegalConsentOptionsExplicitConsentToProcess::type_,
          communication_consent_text: String,
          consent_to_process_checkbox_label: String,
          consent_to_process_footer_text: String,
          consent_to_process_text: String
        }

        type type_ = :explicit_consent_to_process

        module Type
          extend HubspotSDK::Internal::Type::Enum

          EXPLICIT_CONSENT_TO_PROCESS: :explicit_consent_to_process

          def self?.values: -> ::Array[HubspotSDK::Models::Marketing::LegalConsentOptionsExplicitConsentToProcess::type_]
        end
      end
    end
  end
end
