module HubSpotSDK
  module Models
    module Marketing
      type marketing_event_delete_batch_params =
        {  } & HubSpotSDK::Internal::Type::request_parameters

      class MarketingEventDeleteBatchParams < HubSpotSDK::Models::Marketing::BatchInputMarketingEventPublicObjectIDDeleteRequest
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        def initialize: (?request_options: HubSpotSDK::request_opts) -> void

        def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
      end
    end
  end
end
