module HubspotSDK
  module Models
    module Marketing
      type marketing_event_default_response =
        {
          event_name: String,
          event_organizer: String,
          custom_properties: ::Array[HubspotSDK::Marketing::PropertyValue],
          end_date_time: Time,
          event_cancelled: bool,
          event_completed: bool,
          event_description: String,
          event_type: String,
          event_url: String,
          object_id_: String,
          start_date_time: Time
        }

      class MarketingEventDefaultResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor event_name: String

        attr_accessor event_organizer: String

        attr_reader custom_properties: ::Array[HubspotSDK::Marketing::PropertyValue]?

        def custom_properties=: (
          ::Array[HubspotSDK::Marketing::PropertyValue]
        ) -> ::Array[HubspotSDK::Marketing::PropertyValue]

        attr_reader end_date_time: Time?

        def end_date_time=: (Time) -> Time

        attr_reader event_cancelled: bool?

        def event_cancelled=: (bool) -> bool

        attr_reader event_completed: bool?

        def event_completed=: (bool) -> bool

        attr_reader event_description: String?

        def event_description=: (String) -> String

        attr_reader event_type: String?

        def event_type=: (String) -> String

        attr_reader event_url: String?

        def event_url=: (String) -> String

        attr_reader object_id_: String?

        def object_id_=: (String) -> String

        attr_reader start_date_time: Time?

        def start_date_time=: (Time) -> Time

        def initialize: (
          event_name: String,
          event_organizer: String,
          ?custom_properties: ::Array[HubspotSDK::Marketing::PropertyValue],
          ?end_date_time: Time,
          ?event_cancelled: bool,
          ?event_completed: bool,
          ?event_description: String,
          ?event_type: String,
          ?event_url: String,
          ?object_id_: String,
          ?start_date_time: Time
        ) -> void

        def to_hash: -> {
          event_name: String,
          event_organizer: String,
          custom_properties: ::Array[HubspotSDK::Marketing::PropertyValue],
          end_date_time: Time,
          event_cancelled: bool,
          event_completed: bool,
          event_description: String,
          event_type: String,
          event_url: String,
          object_id_: String,
          start_date_time: Time
        }
      end
    end
  end
end
