module HubspotSDK
  module Models
    module Marketing
      type marketing_event_search_identifiers_by_external_event_id_params =
        { external_event_id: String }
        & HubspotSDK::Internal::Type::request_parameters

      class MarketingEventSearchIdentifiersByExternalEventIDParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor external_event_id: String

        def initialize: (
          external_event_id: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          external_event_id: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
