module HubSpotSDK
  module Models
    module Marketing
      type marketing_event_search_by_external_event_id_params =
        { q: String } & HubSpotSDK::Internal::Type::request_parameters

      class MarketingEventSearchByExternalEventIDParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor q: String

        def initialize: (
          q: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          q: String,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
