module HubSpotSDK
  module Models
    module Marketing
      type marketing_event_delete_by_external_event_id_params =
        { external_event_id: String, external_account_id: String }
        & HubSpotSDK::Internal::Type::request_parameters

      class MarketingEventDeleteByExternalEventIDParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_accessor external_event_id: String

        attr_accessor external_account_id: String

        def initialize: (
          external_event_id: String,
          external_account_id: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          external_event_id: String,
          external_account_id: String,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
