module HubSpotSDK
  module Models
    module Marketing
      type marketing_event_upsert_by_external_event_id_params =
        { path_external_event_id: String }
        & HubSpotSDK::Internal::Type::request_parameters

      class MarketingEventUpsertByExternalEventIDParams < HubSpotSDK::Models::Marketing::MarketingEventCreateRequestParams
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        def path_external_event_id: -> String

        def path_external_event_id=: (String _) -> String

        def initialize: (
          path_external_event_id: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          path_external_event_id: String,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
