module HubSpotSDK
  module Models
    class MarketingEventPublicDefaultResponse = Marketing::MarketingEventPublicDefaultResponse

    module Marketing
      type marketing_event_public_default_response =
        {
          id: String,
          created_at: Time,
          custom_properties: ::Array[HubSpotSDK::PropertyValue],
          event_name: String,
          event_organizer: String,
          updated_at: Time,
          end_date_time: Time,
          event_cancelled: bool,
          event_completed: bool,
          event_description: String,
          event_type: String,
          event_url: String,
          object_id_: String,
          start_date_time: Time
        }

      class MarketingEventPublicDefaultResponse < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor custom_properties: ::Array[HubSpotSDK::PropertyValue]

        attr_accessor event_name: String

        attr_accessor event_organizer: String

        attr_accessor updated_at: Time

        attr_reader end_date_time: Time?

        def end_date_time=: (Time) -> Time

        attr_reader event_cancelled: bool?

        def event_cancelled=: (bool) -> bool

        attr_reader event_completed: bool?

        def event_completed=: (bool) -> bool

        attr_reader event_description: String?

        def event_description=: (String) -> String

        attr_reader event_type: String?

        def event_type=: (String) -> String

        attr_reader event_url: String?

        def event_url=: (String) -> String

        attr_reader object_id_: String?

        def object_id_=: (String) -> String

        attr_reader start_date_time: Time?

        def start_date_time=: (Time) -> Time

        def initialize: (
          id: String,
          created_at: Time,
          custom_properties: ::Array[HubSpotSDK::PropertyValue],
          event_name: String,
          event_organizer: String,
          updated_at: Time,
          ?end_date_time: Time,
          ?event_cancelled: bool,
          ?event_completed: bool,
          ?event_description: String,
          ?event_type: String,
          ?event_url: String,
          ?object_id_: String,
          ?start_date_time: Time
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          custom_properties: ::Array[HubSpotSDK::PropertyValue],
          event_name: String,
          event_organizer: String,
          updated_at: Time,
          end_date_time: Time,
          event_cancelled: bool,
          event_completed: bool,
          event_description: String,
          event_type: String,
          event_url: String,
          object_id_: String,
          start_date_time: Time
        }
      end
    end
  end
end
