module HubSpotSDK
  module Models
    class MarketingEventEmailSubscriber = Marketing::MarketingEventEmailSubscriber

    module Marketing
      type marketing_event_email_subscriber =
        {
          contact_properties: ::Hash[Symbol, String],
          email: String,
          interaction_date_time: Integer,
          properties: ::Hash[Symbol, String]
        }

      class MarketingEventEmailSubscriber < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor contact_properties: ::Hash[Symbol, String]

        attr_accessor email: String

        attr_accessor interaction_date_time: Integer

        attr_accessor properties: ::Hash[Symbol, String]

        def initialize: (
          contact_properties: ::Hash[Symbol, String],
          email: String,
          interaction_date_time: Integer,
          properties: ::Hash[Symbol, String]
        ) -> void

        def to_hash: -> {
          contact_properties: ::Hash[Symbol, String],
          email: String,
          interaction_date_time: Integer,
          properties: ::Hash[Symbol, String]
        }
      end
    end
  end
end
