module HubSpotSDK
  module Models
    class MarketingEventCompleteRequestParams = Marketing::MarketingEventCompleteRequestParams

    module Marketing
      type marketing_event_complete_request_params =
        { end_date_time: Time, start_date_time: Time }

      class MarketingEventCompleteRequestParams < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor end_date_time: Time

        attr_accessor start_date_time: Time

        def initialize: (end_date_time: Time, start_date_time: Time) -> void

        def to_hash: -> { end_date_time: Time, start_date_time: Time }
      end
    end
  end
end
