module HubSpotSDK
  module Models
    module Marketing
      type marketing_event_delete_batch_by_external_event_id_params =
        {  } & HubSpotSDK::Internal::Type::request_parameters

      class MarketingEventDeleteBatchByExternalEventIDParams < HubSpotSDK::Models::Marketing::BatchInputMarketingEventExternalUniqueIdentifier
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        def initialize: (?request_options: HubSpotSDK::request_opts) -> void

        def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
      end
    end
  end
end
