module HubspotSDK
  module Models
    module Marketing
      type marketing_event_search_by_external_event_id_params =
        { q: String } & HubspotSDK::Internal::Type::request_parameters

      class MarketingEventSearchByExternalEventIDParams < HubspotSDK::Internal::Type::BaseModel
        extend HubspotSDK::Internal::Type::RequestParameters::Converter
        include HubspotSDK::Internal::Type::RequestParameters

        attr_accessor q: String

        def initialize: (
          q: String,
          ?request_options: HubspotSDK::request_opts
        ) -> void

        def to_hash: -> {
          q: String,
          request_options: HubspotSDK::RequestOptions
        }
      end
    end
  end
end
