module HubspotSDK
  module Models
    module Marketing
      type participation_associations =
        {
          contact: HubspotSDK::Marketing::ContactAssociation,
          marketing_event: HubspotSDK::Marketing::MarketingEventAssociation
        }

      class ParticipationAssociations < HubspotSDK::Internal::Type::BaseModel
        attr_accessor contact: HubspotSDK::Marketing::ContactAssociation

        attr_accessor marketing_event: HubspotSDK::Marketing::MarketingEventAssociation

        def initialize: (
          contact: HubspotSDK::Marketing::ContactAssociation,
          marketing_event: HubspotSDK::Marketing::MarketingEventAssociation
        ) -> void

        def to_hash: -> {
          contact: HubspotSDK::Marketing::ContactAssociation,
          marketing_event: HubspotSDK::Marketing::MarketingEventAssociation
        }
      end
    end
  end
end
