module HubSpotSDK
  module Models
    module Marketing
      type participation_properties =
        {
          attendance_state: HubSpotSDK::Models::Marketing::ParticipationProperties::attendance_state,
          occurred_at: Integer,
          attendance_duration_seconds: Integer,
          attendance_percentage: String
        }

      class ParticipationProperties < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor attendance_state: HubSpotSDK::Models::Marketing::ParticipationProperties::attendance_state

        attr_accessor occurred_at: Integer

        attr_reader attendance_duration_seconds: Integer?

        def attendance_duration_seconds=: (Integer) -> Integer

        attr_reader attendance_percentage: String?

        def attendance_percentage=: (String) -> String

        def initialize: (
          attendance_state: HubSpotSDK::Models::Marketing::ParticipationProperties::attendance_state,
          occurred_at: Integer,
          ?attendance_duration_seconds: Integer,
          ?attendance_percentage: String
        ) -> void

        def to_hash: -> {
          attendance_state: HubSpotSDK::Models::Marketing::ParticipationProperties::attendance_state,
          occurred_at: Integer,
          attendance_duration_seconds: Integer,
          attendance_percentage: String
        }

        type attendance_state =
          :ATTENDED | :CANCELLED | :EMPTY | :NO_SHOW | :REGISTERED

        module AttendanceState
          extend HubSpotSDK::Internal::Type::Enum

          ATTENDED: :ATTENDED
          CANCELLED: :CANCELLED
          EMPTY: :EMPTY
          NO_SHOW: :NO_SHOW
          REGISTERED: :REGISTERED

          def self?.values: -> ::Array[HubSpotSDK::Models::Marketing::ParticipationProperties::attendance_state]
        end
      end
    end
  end
end
