module HubSpotSDK
  module Models
    module Marketing
      type participation_breakdown =
        {
          id: String,
          associations: HubSpotSDK::Marketing::ParticipationAssociations,
          created_at: Time,
          properties: HubSpotSDK::Marketing::ParticipationProperties
        }

      class ParticipationBreakdown < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor associations: HubSpotSDK::Marketing::ParticipationAssociations

        attr_accessor created_at: Time

        attr_accessor properties: HubSpotSDK::Marketing::ParticipationProperties

        def initialize: (
          id: String,
          associations: HubSpotSDK::Marketing::ParticipationAssociations,
          created_at: Time,
          properties: HubSpotSDK::Marketing::ParticipationProperties
        ) -> void

        def to_hash: -> {
          id: String,
          associations: HubSpotSDK::Marketing::ParticipationAssociations,
          created_at: Time,
          properties: HubSpotSDK::Marketing::ParticipationProperties
        }
      end
    end
  end
end
