module HubSpotSDK
  module Models
    module Marketing
      type public_email_version =
        {
          id: String,
          object: HubSpotSDK::Marketing::PublicEmail,
          updated_at: Time,
          user: HubSpotSDK::VersionUser
        }

      class PublicEmailVersion < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor object: HubSpotSDK::Marketing::PublicEmail

        attr_accessor updated_at: Time

        attr_accessor user: HubSpotSDK::VersionUser

        def initialize: (
          id: String,
          object: HubSpotSDK::Marketing::PublicEmail,
          updated_at: Time,
          user: HubSpotSDK::VersionUser
        ) -> void

        def to_hash: -> {
          id: String,
          object: HubSpotSDK::Marketing::PublicEmail,
          updated_at: Time,
          user: HubSpotSDK::VersionUser
        }
      end
    end
  end
end
