module HubspotSDK
  module Models
    module Marketing
      type public_button_style_settings =
        {
          background_color: top,
          corner_radius: Integer,
          font_style: HubspotSDK::Marketing::PublicFontStyle
        }

      class PublicButtonStyleSettings < HubspotSDK::Internal::Type::BaseModel
        attr_reader background_color: top?

        def background_color=: (top) -> top

        attr_reader corner_radius: Integer?

        def corner_radius=: (Integer) -> Integer

        attr_reader font_style: HubspotSDK::Marketing::PublicFontStyle?

        def font_style=: (
          HubspotSDK::Marketing::PublicFontStyle
        ) -> HubspotSDK::Marketing::PublicFontStyle

        def initialize: (
          ?background_color: top,
          ?corner_radius: Integer,
          ?font_style: HubspotSDK::Marketing::PublicFontStyle
        ) -> void

        def to_hash: -> {
          background_color: top,
          corner_radius: Integer,
          font_style: HubspotSDK::Marketing::PublicFontStyle
        }
      end
    end
  end
end
