module HubspotSDK
  module Models
    module Marketing
      type public_email_style_settings =
        {
          background_color: String,
          background_image: String,
          background_image_type: HubspotSDK::Models::Marketing::PublicEmailStyleSettings::background_image_type,
          body_border_color: String,
          body_border_color_choice: String,
          body_border_width: Float,
          body_color: String,
          button_style_settings: HubspotSDK::Marketing::PublicButtonStyleSettings,
          :color_picker_favorite1 => String,
          :color_picker_favorite2 => String,
          :color_picker_favorite3 => String,
          :color_picker_favorite4 => String,
          :color_picker_favorite5 => String,
          :color_picker_favorite6 => String,
          divider_style_settings: HubspotSDK::Marketing::PublicDividerStyleSettings,
          email_body_padding: String,
          email_body_width: String,
          heading_one_font: HubspotSDK::Marketing::PublicFontStyle,
          heading_two_font: HubspotSDK::Marketing::PublicFontStyle,
          links_font: HubspotSDK::Marketing::PublicFontStyle,
          primary_accent_color: String,
          primary_font: String,
          primary_font_color: String,
          primary_font_line_height: String,
          primary_font_size: Float,
          secondary_accent_color: String,
          secondary_font: String,
          secondary_font_color: String,
          secondary_font_line_height: String,
          secondary_font_size: Float
        }

      class PublicEmailStyleSettings < HubspotSDK::Internal::Type::BaseModel
        attr_reader background_color: String?

        def background_color=: (String) -> String

        attr_reader background_image: String?

        def background_image=: (String) -> String

        attr_reader background_image_type: HubspotSDK::Models::Marketing::PublicEmailStyleSettings::background_image_type?

        def background_image_type=: (
          HubspotSDK::Models::Marketing::PublicEmailStyleSettings::background_image_type
        ) -> HubspotSDK::Models::Marketing::PublicEmailStyleSettings::background_image_type

        attr_reader body_border_color: String?

        def body_border_color=: (String) -> String

        attr_reader body_border_color_choice: String?

        def body_border_color_choice=: (String) -> String

        attr_reader body_border_width: Float?

        def body_border_width=: (Float) -> Float

        attr_reader body_color: String?

        def body_color=: (String) -> String

        attr_reader button_style_settings: HubspotSDK::Marketing::PublicButtonStyleSettings?

        def button_style_settings=: (
          HubspotSDK::Marketing::PublicButtonStyleSettings
        ) -> HubspotSDK::Marketing::PublicButtonStyleSettings

        attr_reader color_picker_favorite1: String?

        def color_picker_favorite1=: (String) -> String

        attr_reader color_picker_favorite2: String?

        def color_picker_favorite2=: (String) -> String

        attr_reader color_picker_favorite3: String?

        def color_picker_favorite3=: (String) -> String

        attr_reader color_picker_favorite4: String?

        def color_picker_favorite4=: (String) -> String

        attr_reader color_picker_favorite5: String?

        def color_picker_favorite5=: (String) -> String

        attr_reader color_picker_favorite6: String?

        def color_picker_favorite6=: (String) -> String

        attr_reader divider_style_settings: HubspotSDK::Marketing::PublicDividerStyleSettings?

        def divider_style_settings=: (
          HubspotSDK::Marketing::PublicDividerStyleSettings
        ) -> HubspotSDK::Marketing::PublicDividerStyleSettings

        attr_reader email_body_padding: String?

        def email_body_padding=: (String) -> String

        attr_reader email_body_width: String?

        def email_body_width=: (String) -> String

        attr_reader heading_one_font: HubspotSDK::Marketing::PublicFontStyle?

        def heading_one_font=: (
          HubspotSDK::Marketing::PublicFontStyle
        ) -> HubspotSDK::Marketing::PublicFontStyle

        attr_reader heading_two_font: HubspotSDK::Marketing::PublicFontStyle?

        def heading_two_font=: (
          HubspotSDK::Marketing::PublicFontStyle
        ) -> HubspotSDK::Marketing::PublicFontStyle

        attr_reader links_font: HubspotSDK::Marketing::PublicFontStyle?

        def links_font=: (
          HubspotSDK::Marketing::PublicFontStyle
        ) -> HubspotSDK::Marketing::PublicFontStyle

        attr_reader primary_accent_color: String?

        def primary_accent_color=: (String) -> String

        attr_reader primary_font: String?

        def primary_font=: (String) -> String

        attr_reader primary_font_color: String?

        def primary_font_color=: (String) -> String

        attr_reader primary_font_line_height: String?

        def primary_font_line_height=: (String) -> String

        attr_reader primary_font_size: Float?

        def primary_font_size=: (Float) -> Float

        attr_reader secondary_accent_color: String?

        def secondary_accent_color=: (String) -> String

        attr_reader secondary_font: String?

        def secondary_font=: (String) -> String

        attr_reader secondary_font_color: String?

        def secondary_font_color=: (String) -> String

        attr_reader secondary_font_line_height: String?

        def secondary_font_line_height=: (String) -> String

        attr_reader secondary_font_size: Float?

        def secondary_font_size=: (Float) -> Float

        def initialize: (
          ?background_color: String,
          ?background_image: String,
          ?background_image_type: HubspotSDK::Models::Marketing::PublicEmailStyleSettings::background_image_type,
          ?body_border_color: String,
          ?body_border_color_choice: String,
          ?body_border_width: Float,
          ?body_color: String,
          ?button_style_settings: HubspotSDK::Marketing::PublicButtonStyleSettings,
          ?color_picker_favorite1: String,
          ?color_picker_favorite2: String,
          ?color_picker_favorite3: String,
          ?color_picker_favorite4: String,
          ?color_picker_favorite5: String,
          ?color_picker_favorite6: String,
          ?divider_style_settings: HubspotSDK::Marketing::PublicDividerStyleSettings,
          ?email_body_padding: String,
          ?email_body_width: String,
          ?heading_one_font: HubspotSDK::Marketing::PublicFontStyle,
          ?heading_two_font: HubspotSDK::Marketing::PublicFontStyle,
          ?links_font: HubspotSDK::Marketing::PublicFontStyle,
          ?primary_accent_color: String,
          ?primary_font: String,
          ?primary_font_color: String,
          ?primary_font_line_height: String,
          ?primary_font_size: Float,
          ?secondary_accent_color: String,
          ?secondary_font: String,
          ?secondary_font_color: String,
          ?secondary_font_line_height: String,
          ?secondary_font_size: Float
        ) -> void

        def to_hash: -> {
          background_color: String,
          background_image: String,
          background_image_type: HubspotSDK::Models::Marketing::PublicEmailStyleSettings::background_image_type,
          body_border_color: String,
          body_border_color_choice: String,
          body_border_width: Float,
          body_color: String,
          button_style_settings: HubspotSDK::Marketing::PublicButtonStyleSettings,
          :color_picker_favorite1 => String,
          :color_picker_favorite2 => String,
          :color_picker_favorite3 => String,
          :color_picker_favorite4 => String,
          :color_picker_favorite5 => String,
          :color_picker_favorite6 => String,
          divider_style_settings: HubspotSDK::Marketing::PublicDividerStyleSettings,
          email_body_padding: String,
          email_body_width: String,
          heading_one_font: HubspotSDK::Marketing::PublicFontStyle,
          heading_two_font: HubspotSDK::Marketing::PublicFontStyle,
          links_font: HubspotSDK::Marketing::PublicFontStyle,
          primary_accent_color: String,
          primary_font: String,
          primary_font_color: String,
          primary_font_line_height: String,
          primary_font_size: Float,
          secondary_accent_color: String,
          secondary_font: String,
          secondary_font_color: String,
          secondary_font_line_height: String,
          secondary_font_size: Float
        }

        type background_image_type = :REPEAT | :SINGLE | :STRETCH

        module BackgroundImageType
          extend HubspotSDK::Internal::Type::Enum

          REPEAT: :REPEAT
          SINGLE: :SINGLE
          STRETCH: :STRETCH

          def self?.values: -> ::Array[HubspotSDK::Models::Marketing::PublicEmailStyleSettings::background_image_type]
        end
      end
    end
  end
end
