module HubspotSDK
  module Models
    module Marketing
      type public_campaign_batch_update_item =
        { id: String, properties: ::Hash[Symbol, String] }

      class PublicCampaignBatchUpdateItem < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor properties: ::Hash[Symbol, String]

        def initialize: (id: String, properties: ::Hash[Symbol, String]) -> void

        def to_hash: -> { id: String, properties: ::Hash[Symbol, String] }
      end
    end
  end
end
