module HubSpotSDK
  module Models
    module Marketing
      type public_campaign_asset =
        { id: String, metrics: ::Hash[Symbol, Float], name: String }

      class PublicCampaignAsset < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_reader metrics: ::Hash[Symbol, Float]?

        def metrics=: (::Hash[Symbol, Float]) -> ::Hash[Symbol, Float]

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (
          id: String,
          ?metrics: ::Hash[Symbol, Float],
          ?name: String
        ) -> void

        def to_hash: -> {
          id: String,
          metrics: ::Hash[Symbol, Float],
          name: String
        }
      end
    end
  end
end
