module HubspotSDK
  module Models
    module Marketing
      type public_business_unit = { id: Integer }

      class PublicBusinessUnit < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: Integer

        def initialize: (id: Integer) -> void

        def to_hash: -> { id: Integer }
      end
    end
  end
end
