module HubSpotSDK
  module Models
    module Marketing
      type public_email_to_details =
        {
          contact_ids: HubSpotSDK::Marketing::PublicEmailRecipients,
          contact_ils_lists: HubSpotSDK::Marketing::PublicEmailRecipients,
          contact_lists: HubSpotSDK::Marketing::PublicEmailRecipients,
          limit_send_frequency: bool,
          suppress_graymail: bool
        }

      class PublicEmailToDetails < HubSpotSDK::Internal::Type::BaseModel
        attr_reader contact_ids: HubSpotSDK::Marketing::PublicEmailRecipients?

        def contact_ids=: (
          HubSpotSDK::Marketing::PublicEmailRecipients
        ) -> HubSpotSDK::Marketing::PublicEmailRecipients

        attr_reader contact_ils_lists: HubSpotSDK::Marketing::PublicEmailRecipients?

        def contact_ils_lists=: (
          HubSpotSDK::Marketing::PublicEmailRecipients
        ) -> HubSpotSDK::Marketing::PublicEmailRecipients

        attr_reader contact_lists: HubSpotSDK::Marketing::PublicEmailRecipients?

        def contact_lists=: (
          HubSpotSDK::Marketing::PublicEmailRecipients
        ) -> HubSpotSDK::Marketing::PublicEmailRecipients

        attr_reader limit_send_frequency: bool?

        def limit_send_frequency=: (bool) -> bool

        attr_reader suppress_graymail: bool?

        def suppress_graymail=: (bool) -> bool

        def initialize: (
          ?contact_ids: HubSpotSDK::Marketing::PublicEmailRecipients,
          ?contact_ils_lists: HubSpotSDK::Marketing::PublicEmailRecipients,
          ?contact_lists: HubSpotSDK::Marketing::PublicEmailRecipients,
          ?limit_send_frequency: bool,
          ?suppress_graymail: bool
        ) -> void

        def to_hash: -> {
          contact_ids: HubSpotSDK::Marketing::PublicEmailRecipients,
          contact_ils_lists: HubSpotSDK::Marketing::PublicEmailRecipients,
          contact_lists: HubSpotSDK::Marketing::PublicEmailRecipients,
          limit_send_frequency: bool,
          suppress_graymail: bool
        }
      end
    end
  end
end
