module HubspotSDK
  module Models
    module Marketing
      type public_campaign_delete_input = { id: String }

      class PublicCampaignDeleteInput < HubspotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end
    end
  end
end
