module HubSpotSDK
  module Models
    module Marketing
      type public_budget_item =
        {
          id: String,
          amount: Float,
          created_at: Integer,
          name: String,
          order: Integer,
          updated_at: Integer,
          description: String
        }

      class PublicBudgetItem < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor amount: Float

        attr_accessor created_at: Integer

        attr_accessor name: String

        attr_accessor order: Integer

        attr_accessor updated_at: Integer

        attr_reader description: String?

        def description=: (String) -> String

        def initialize: (
          id: String,
          amount: Float,
          created_at: Integer,
          name: String,
          order: Integer,
          updated_at: Integer,
          ?description: String
        ) -> void

        def to_hash: -> {
          id: String,
          amount: Float,
          created_at: Integer,
          name: String,
          order: Integer,
          updated_at: Integer,
          description: String
        }
      end
    end
  end
end
