module HubSpotSDK
  module Models
    module Marketing
      type public_webversion_details =
        {
          domain: String,
          enabled: bool,
          expires_at: Time,
          is_page_redirected: bool,
          meta_description: String,
          page_expiry_enabled: bool,
          redirect_to_page_id: String,
          redirect_to_url: String,
          slug: String,
          title: String,
          url: String
        }

      class PublicWebversionDetails < HubSpotSDK::Internal::Type::BaseModel
        attr_reader domain: String?

        def domain=: (String) -> String

        attr_reader enabled: bool?

        def enabled=: (bool) -> bool

        attr_reader expires_at: Time?

        def expires_at=: (Time) -> Time

        attr_reader is_page_redirected: bool?

        def is_page_redirected=: (bool) -> bool

        attr_reader meta_description: String?

        def meta_description=: (String) -> String

        attr_reader page_expiry_enabled: bool?

        def page_expiry_enabled=: (bool) -> bool

        attr_reader redirect_to_page_id: String?

        def redirect_to_page_id=: (String) -> String

        attr_reader redirect_to_url: String?

        def redirect_to_url=: (String) -> String

        attr_reader slug: String?

        def slug=: (String) -> String

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader url: String?

        def url=: (String) -> String

        def initialize: (
          ?domain: String,
          ?enabled: bool,
          ?expires_at: Time,
          ?is_page_redirected: bool,
          ?meta_description: String,
          ?page_expiry_enabled: bool,
          ?redirect_to_page_id: String,
          ?redirect_to_url: String,
          ?slug: String,
          ?title: String,
          ?url: String
        ) -> void

        def to_hash: -> {
          domain: String,
          enabled: bool,
          expires_at: Time,
          is_page_redirected: bool,
          meta_description: String,
          page_expiry_enabled: bool,
          redirect_to_page_id: String,
          redirect_to_url: String,
          slug: String,
          title: String,
          url: String
        }
      end
    end
  end
end
