module HubspotSDK
  module Models
    module Marketing
      type public_rss_email_details =
        {
          blog_email_type: String,
          blog_image_max_width: Integer,
          blog_layout: String,
          hubspot_blog_id: String,
          max_entries: Integer,
          rss_entry_template: String,
          timing: ::Hash[Symbol, top],
          url: String,
          use_headline_as_subject: bool
        }

      class PublicRssEmailDetails < HubspotSDK::Internal::Type::BaseModel
        attr_reader blog_email_type: String?

        def blog_email_type=: (String) -> String

        attr_reader blog_image_max_width: Integer?

        def blog_image_max_width=: (Integer) -> Integer

        attr_reader blog_layout: String?

        def blog_layout=: (String) -> String

        attr_reader hubspot_blog_id: String?

        def hubspot_blog_id=: (String) -> String

        attr_reader max_entries: Integer?

        def max_entries=: (Integer) -> Integer

        attr_reader rss_entry_template: String?

        def rss_entry_template=: (String) -> String

        attr_reader timing: ::Hash[Symbol, top]?

        def timing=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

        attr_reader url: String?

        def url=: (String) -> String

        attr_reader use_headline_as_subject: bool?

        def use_headline_as_subject=: (bool) -> bool

        def initialize: (
          ?blog_email_type: String,
          ?blog_image_max_width: Integer,
          ?blog_layout: String,
          ?hubspot_blog_id: String,
          ?max_entries: Integer,
          ?rss_entry_template: String,
          ?timing: ::Hash[Symbol, top],
          ?url: String,
          ?use_headline_as_subject: bool
        ) -> void

        def to_hash: -> {
          blog_email_type: String,
          blog_image_max_width: Integer,
          blog_layout: String,
          hubspot_blog_id: String,
          max_entries: Integer,
          rss_entry_template: String,
          timing: ::Hash[Symbol, top],
          url: String,
          use_headline_as_subject: bool
        }
      end
    end
  end
end
