module HubSpotSDK
  module Models
    module Marketing
      type search_public_response_wrapper =
        {
          app_id: Integer,
          external_account_id: String,
          external_event_id: String,
          object_id_: String
        }

      class SearchPublicResponseWrapper < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor app_id: Integer

        attr_accessor external_account_id: String

        attr_accessor external_event_id: String

        attr_accessor object_id_: String

        def initialize: (
          app_id: Integer,
          external_account_id: String,
          external_event_id: String,
          object_id_: String
        ) -> void

        def to_hash: -> {
          app_id: Integer,
          external_account_id: String,
          external_event_id: String,
          object_id_: String
        }
      end
    end
  end
end
