module HubSpotSDK
  module Models
    module Marketing
      type subscriber_email_response = { email: String, vid: Integer }

      class SubscriberEmailResponse < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor email: String

        attr_accessor vid: Integer

        def initialize: (email: String, vid: Integer) -> void

        def to_hash: -> { email: String, vid: Integer }
      end
    end
  end
end
