module HubSpotSDK
  module Models
    module Marketing
      type subscriber_vid_response = { vid: Integer }

      class SubscriberVidResponse < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor vid: Integer

        def initialize: (vid: Integer) -> void

        def to_hash: -> { vid: Integer }
      end
    end
  end
end
