module HubspotSDK
  module Models
    module Marketing
      type subscription_definitions_response =
        {
          subscription_definitions: ::Array[HubspotSDK::Marketing::SubscriptionDefinition]
        }

      class SubscriptionDefinitionsResponse < HubspotSDK::Internal::Type::BaseModel
        attr_accessor subscription_definitions: ::Array[HubspotSDK::Marketing::SubscriptionDefinition]

        def initialize: (
          subscription_definitions: ::Array[HubspotSDK::Marketing::SubscriptionDefinition]
        ) -> void

        def to_hash: -> {
          subscription_definitions: ::Array[HubspotSDK::Marketing::SubscriptionDefinition]
        }
      end
    end
  end
end
