module HubSpotSDK
  module Models
    module Account
      type activity_list_security_activities_params =
        {
          after: String,
          from_timestamp: Integer,
          limit: Integer,
          to_timestamp: Integer,
          user_id: Integer
        }
        & HubSpotSDK::Internal::Type::request_parameters

      class ActivityListSecurityActivitiesParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_reader after: String?

        def after=: (String) -> String

        attr_reader from_timestamp: Integer?

        def from_timestamp=: (Integer) -> Integer

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader to_timestamp: Integer?

        def to_timestamp=: (Integer) -> Integer

        attr_reader user_id: Integer?

        def user_id=: (Integer) -> Integer

        def initialize: (
          ?after: String,
          ?from_timestamp: Integer,
          ?limit: Integer,
          ?to_timestamp: Integer,
          ?user_id: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          after: String,
          from_timestamp: Integer,
          limit: Integer,
          to_timestamp: Integer,
          user_id: Integer,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
