module HubSpotSDK
  module Models
    module Account
      type collection_response_hydrated_critical_action_forward_paging =
        {
          results: ::Array[HubSpotSDK::Account::HydratedCriticalAction],
          paging: HubSpotSDK::ForwardPaging
        }

      class CollectionResponseHydratedCriticalActionForwardPaging < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubSpotSDK::Account::HydratedCriticalAction]

        attr_reader paging: HubSpotSDK::ForwardPaging?

        def paging=: (HubSpotSDK::ForwardPaging) -> HubSpotSDK::ForwardPaging

        def initialize: (
          results: ::Array[HubSpotSDK::Account::HydratedCriticalAction],
          ?paging: HubSpotSDK::ForwardPaging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubSpotSDK::Account::HydratedCriticalAction],
          paging: HubSpotSDK::ForwardPaging
        }
      end
    end
  end
end
