module HubspotSDK
  module Models
    module Account
      type collection_response_api_usage =
        {
          results: ::Array[HubspotSDK::Account::APIUsage],
          paging: HubspotSDK::Marketing::Paging
        }

      class CollectionResponseAPIUsage < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubspotSDK::Account::APIUsage]

        attr_reader paging: HubspotSDK::Marketing::Paging?

        def paging=: (
          HubspotSDK::Marketing::Paging
        ) -> HubspotSDK::Marketing::Paging

        def initialize: (
          results: ::Array[HubspotSDK::Account::APIUsage],
          ?paging: HubspotSDK::Marketing::Paging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubspotSDK::Account::APIUsage],
          paging: HubspotSDK::Marketing::Paging
        }
      end
    end
  end
end
