module HubspotSDK
  module Models
    module Account
      type collection_response_api_usage_no_paging =
        { results: ::Array[HubspotSDK::Account::APIUsage] }

      class CollectionResponseAPIUsageNoPaging < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubspotSDK::Account::APIUsage]

        def initialize: (
          results: ::Array[HubspotSDK::Account::APIUsage]
        ) -> void

        def to_hash: -> { results: ::Array[HubspotSDK::Account::APIUsage] }
      end
    end
  end
end
