module HubspotSDK
  module Models
    module Account
      type collection_response_api_usage =
        {
          results: ::Array[HubspotSDK::Account::APIUsage],
          paging: HubspotSDK::Paging
        }

      class CollectionResponseAPIUsage < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubspotSDK::Account::APIUsage]

        attr_reader paging: HubspotSDK::Paging?

        def paging=: (HubspotSDK::Paging) -> HubspotSDK::Paging

        def initialize: (
          results: ::Array[HubspotSDK::Account::APIUsage],
          ?paging: HubspotSDK::Paging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubspotSDK::Account::APIUsage],
          paging: HubspotSDK::Paging
        }
      end
    end
  end
end
