module HubSpotSDK
  module Models
    module Cms
      module Blogs
        module Posts
          type multi_language_attach_to_lang_group_params =
            {  } & HubSpotSDK::Internal::Type::request_parameters

          class MultiLanguageAttachToLangGroupParams < HubSpotSDK::Models::Cms::AttachToLangPrimaryRequestVNext
            extend HubSpotSDK::Internal::Type::RequestParameters::Converter
            include HubSpotSDK::Internal::Type::RequestParameters

            def initialize: (?request_options: HubSpotSDK::request_opts) -> void

            def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
          end
        end
      end
    end
  end
end
