module HubSpotSDK
  module Models
    module Marketing
      module Campaigns
        type asset_delete_params =
          { campaign_guid: String, asset_type: String, asset_id: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class AssetDeleteParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor campaign_guid: String

          attr_accessor asset_type: String

          attr_accessor asset_id: String

          def initialize: (
            campaign_guid: String,
            asset_type: String,
            asset_id: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            campaign_guid: String,
            asset_type: String,
            asset_id: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
