module HubspotSDK
  module Models
    module Marketing
      module Campaigns
        type asset_update_params =
          { campaign_guid: String, asset_type: String, asset_id: String }
          & HubspotSDK::Internal::Type::request_parameters

        class AssetUpdateParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_accessor campaign_guid: String

          attr_accessor asset_type: String

          attr_accessor asset_id: String

          def initialize: (
            campaign_guid: String,
            asset_type: String,
            asset_id: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            campaign_guid: String,
            asset_type: String,
            asset_id: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
