module HubspotSDK
  module Models
    module Marketing
      module Campaigns
        type budget_get_totals_params =
          { campaign_guid: String }
          & HubspotSDK::Internal::Type::request_parameters

        class BudgetGetTotalsParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_accessor campaign_guid: String

          def initialize: (
            campaign_guid: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            campaign_guid: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
