module HubspotSDK
  module Models
    module Marketing
      module Campaigns
        type metric_get_attribution_metrics_params =
          { campaign_guid: String, end_date: String, start_date: String }
          & HubspotSDK::Internal::Type::request_parameters

        class MetricGetAttributionMetricsParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_accessor campaign_guid: String

          attr_reader end_date: String?

          def end_date=: (String) -> String

          attr_reader start_date: String?

          def start_date=: (String) -> String

          def initialize: (
            campaign_guid: String,
            ?end_date: String,
            ?start_date: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            campaign_guid: String,
            end_date: String,
            start_date: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
