module HubspotSDK
  module Resources
    class Cms
      class AuditLogs
        def list: (
          ?after: String,
          ?before: String,
          ?event_type: ::Array[String],
          ?limit: Integer,
          ?object_id_: ::Array[String],
          ?object_type: ::Array[String],
          ?sort: ::Array[String],
          ?user_id: ::Array[String],
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Internal::Page[HubspotSDK::Cms::PublicAuditLog]

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
