module HubSpotSDK
  module Resources
    class Cms
      class Blogs
        attr_reader authors: HubSpotSDK::Resources::Cms::Blogs::Authors

        attr_reader posts: HubSpotSDK::Resources::Cms::Blogs::Posts

        attr_reader settings: HubSpotSDK::Resources::Cms::Blogs::Settings

        attr_reader tags: HubSpotSDK::Resources::Cms::Blogs::Tags

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
