module HubSpotSDK
  module Resources
    class Cms
      class Hubdb
        attr_reader rows: HubSpotSDK::Resources::Cms::Hubdb::Rows

        attr_reader tables: HubSpotSDK::Resources::Cms::Hubdb::Tables

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
