module HubspotSDK
  module Resources
    class Cms
      class MediaBridge
        attr_reader events: HubspotSDK::Resources::Cms::MediaBridge::Events

        attr_reader groups: HubspotSDK::Resources::Cms::MediaBridge::Groups

        attr_reader integrator_settings: HubspotSDK::Resources::Cms::MediaBridge::IntegratorSettings

        attr_reader properties: HubspotSDK::Resources::Cms::MediaBridge::Properties

        attr_reader schemas: HubspotSDK::Resources::Cms::MediaBridge::Schemas

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
