module HubSpotSDK
  module Resources
    class Cms
      class Pages
        attr_reader landing_pages: HubSpotSDK::Resources::Cms::Pages::LandingPages

        attr_reader site_pages: HubSpotSDK::Resources::Cms::Pages::SitePages

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
