module HubspotSDK
  module Resources
    class Cms
      class SourceCode
        def create: (
          String path,
          environment: String,
          ?file: HubspotSDK::Internal::file_input,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Cms::AssetFileMetadata

        def delete: (
          String path,
          environment: String,
          ?request_options: HubspotSDK::request_opts
        ) -> nil

        def extract_async: (
          path: String,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::TaskLocator

        def get: (
          String path,
          environment: String,
          ?request_options: HubspotSDK::request_opts
        ) -> StringIO

        def get_extraction_status: (
          Integer task_id,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::ActionResponse

        def get_metadata: (
          String path,
          environment: String,
          ?properties: String,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Cms::AssetFileMetadata

        def upsert: (
          String path,
          environment: String,
          ?file: HubspotSDK::Internal::file_input,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Cms::AssetFileMetadata

        def validate: (
          String path,
          environment: String,
          ?file: HubspotSDK::Internal::file_input,
          ?request_options: HubspotSDK::request_opts
        ) -> StringIO

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
