module HubSpotSDK
  module Resources
    class Cms
      class SourceCode
        def extract_async: (
          path: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::TaskLocator

        def get_extraction_status: (
          Integer task_id,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::ActionResponse

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
