module HubspotSDK
  module Models
    module Cms
      module MediaBridge
        type batch_create_params =
          { app_id: Integer, object_type: String }
          & HubspotSDK::Internal::Type::request_parameters

        class BatchCreateParams < HubspotSDK::Models::Cms::BatchInputPropertyCreate
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          def app_id: -> Integer

          def app_id=: (Integer _) -> Integer

          def object_type: -> String

          def object_type=: (String _) -> String

          def initialize: (
            app_id: Integer,
            object_type: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            app_id: Integer,
            object_type: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
