module HubSpotSDK
  module Models
    module Cms
      module MediaBridge
        type batch_create_params =
          { app_id: Integer, object_type: String }
          & HubSpotSDK::Internal::Type::request_parameters

        class BatchCreateParams < HubSpotSDK::Models::Cms::BatchInputPropertyCreate
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def app_id: -> Integer

          def app_id=: (Integer _) -> Integer

          def object_type: -> String

          def object_type=: (String _) -> String

          def initialize: (
            app_id: Integer,
            object_type: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            app_id: Integer,
            object_type: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
