module HubspotSDK
  module Models
    module Cms
      module MediaBridge
        type integrator_setting_create_oembed_domain_params =
          {  } & HubspotSDK::Internal::Type::request_parameters

        class IntegratorSettingCreateOembedDomainParams < HubspotSDK::Models::Cms::IntegratorOEmbedDomainRequest
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          def initialize: (?request_options: HubspotSDK::request_opts) -> void

          def to_hash: -> { request_options: HubspotSDK::RequestOptions }
        end
      end
    end
  end
end
