module HubspotSDK
  module Models
    module Cms
      module MediaBridge
        type integrator_setting_update_app_name_params =
          { updated_at: Integer, name: String }
          & HubspotSDK::Internal::Type::request_parameters

        class IntegratorSettingUpdateAppNameParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_accessor updated_at: Integer

          attr_reader name: String?

          def name=: (String) -> String

          def initialize: (
            updated_at: Integer,
            ?name: String,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            updated_at: Integer,
            name: String,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
