module HubspotSDK
  module Models
    module Cms
      module MediaBridge
        type integrator_setting_create_oembed_domain_params =
          {
            endpoints: HubspotSDK::Cms::MediaBridge::IntegratorSettingCreateOembedDomainParams::Endpoints,
            portal_id: Integer
          }
          & HubspotSDK::Internal::Type::request_parameters

        class IntegratorSettingCreateOembedDomainParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_accessor endpoints: HubspotSDK::Cms::MediaBridge::IntegratorSettingCreateOembedDomainParams::Endpoints

          attr_reader portal_id: Integer?

          def portal_id=: (Integer) -> Integer

          def initialize: (
            endpoints: HubspotSDK::Cms::MediaBridge::IntegratorSettingCreateOembedDomainParams::Endpoints,
            ?portal_id: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            endpoints: HubspotSDK::Cms::MediaBridge::IntegratorSettingCreateOembedDomainParams::Endpoints,
            portal_id: Integer,
            request_options: HubspotSDK::RequestOptions
          }

          type endpoints =
            { discovery: bool, schemes: ::Array[String], url: String }

          class Endpoints < HubspotSDK::Internal::Type::BaseModel
            attr_accessor discovery: bool

            attr_accessor schemes: ::Array[String]

            attr_accessor url: String

            def initialize: (
              discovery: bool,
              schemes: ::Array[String],
              url: String
            ) -> void

            def to_hash: -> {
              discovery: bool,
              schemes: ::Array[String],
              url: String
            }
          end
        end
      end
    end
  end
end
