module HubspotSDK
  module Models
    module Cms
      module MediaBridge
        type integrator_setting_update_oembed_domain_response =
          {
            id: Integer,
            app_id: Integer,
            created_at: Integer,
            deleted_at: Integer,
            endpoints: HubspotSDK::Models::Cms::MediaBridge::IntegratorSettingUpdateOembedDomainResponse::Endpoints,
            portal_id: Integer,
            updated_at: Integer
          }

        class IntegratorSettingUpdateOembedDomainResponse < HubspotSDK::Internal::Type::BaseModel
          attr_accessor id: Integer

          attr_accessor app_id: Integer

          attr_accessor created_at: Integer

          attr_accessor deleted_at: Integer

          attr_accessor endpoints: HubspotSDK::Models::Cms::MediaBridge::IntegratorSettingUpdateOembedDomainResponse::Endpoints

          attr_accessor portal_id: Integer

          attr_accessor updated_at: Integer

          def initialize: (
            id: Integer,
            app_id: Integer,
            created_at: Integer,
            deleted_at: Integer,
            endpoints: HubspotSDK::Models::Cms::MediaBridge::IntegratorSettingUpdateOembedDomainResponse::Endpoints,
            portal_id: Integer,
            updated_at: Integer
          ) -> void

          def to_hash: -> {
            id: Integer,
            app_id: Integer,
            created_at: Integer,
            deleted_at: Integer,
            endpoints: HubspotSDK::Models::Cms::MediaBridge::IntegratorSettingUpdateOembedDomainResponse::Endpoints,
            portal_id: Integer,
            updated_at: Integer
          }

          type endpoints =
            { discovery: bool, schemes: ::Array[String], url: String }

          class Endpoints < HubspotSDK::Internal::Type::BaseModel
            attr_accessor discovery: bool

            attr_accessor schemes: ::Array[String]

            attr_accessor url: String

            def initialize: (
              discovery: bool,
              schemes: ::Array[String],
              url: String
            ) -> void

            def to_hash: -> {
              discovery: bool,
              schemes: ::Array[String],
              url: String
            }
          end
        end
      end
    end
  end
end
