module HubspotSDK
  module Models
    module Cms
      module MediaBridge
        type integrator_setting_get_event_visibility_settings_response =
          {
            created_at: Time,
            visibility_settings: ::Array[HubspotSDK::Models::Cms::MediaBridge::IntegratorSettingGetEventVisibilitySettingsResponse::VisibilitySetting]
          }

        class IntegratorSettingGetEventVisibilitySettingsResponse < HubspotSDK::Internal::Type::BaseModel
          attr_accessor created_at: Time

          attr_accessor visibility_settings: ::Array[HubspotSDK::Models::Cms::MediaBridge::IntegratorSettingGetEventVisibilitySettingsResponse::VisibilitySetting]

          def initialize: (
            created_at: Time,
            visibility_settings: ::Array[HubspotSDK::Models::Cms::MediaBridge::IntegratorSettingGetEventVisibilitySettingsResponse::VisibilitySetting]
          ) -> void

          def to_hash: -> {
            created_at: Time,
            visibility_settings: ::Array[HubspotSDK::Models::Cms::MediaBridge::IntegratorSettingGetEventVisibilitySettingsResponse::VisibilitySetting]
          }

          type visibility_setting =
            {
              event_type: HubspotSDK::Models::Cms::MediaBridge::IntegratorSettingGetEventVisibilitySettingsResponse::VisibilitySetting::event_type,
              updated_at: Integer,
              show_in_reporting: bool,
              show_in_timeline: bool,
              show_in_workflows: bool
            }

          class VisibilitySetting < HubspotSDK::Internal::Type::BaseModel
            attr_accessor event_type: HubspotSDK::Models::Cms::MediaBridge::IntegratorSettingGetEventVisibilitySettingsResponse::VisibilitySetting::event_type

            attr_accessor updated_at: Integer

            attr_reader show_in_reporting: bool?

            def show_in_reporting=: (bool) -> bool

            attr_reader show_in_timeline: bool?

            def show_in_timeline=: (bool) -> bool

            attr_reader show_in_workflows: bool?

            def show_in_workflows=: (bool) -> bool

            def initialize: (
              event_type: HubspotSDK::Models::Cms::MediaBridge::IntegratorSettingGetEventVisibilitySettingsResponse::VisibilitySetting::event_type,
              updated_at: Integer,
              ?show_in_reporting: bool,
              ?show_in_timeline: bool,
              ?show_in_workflows: bool
            ) -> void

            def to_hash: -> {
              event_type: HubspotSDK::Models::Cms::MediaBridge::IntegratorSettingGetEventVisibilitySettingsResponse::VisibilitySetting::event_type,
              updated_at: Integer,
              show_in_reporting: bool,
              show_in_timeline: bool,
              show_in_workflows: bool
            }

            type event_type =
              :ALL | :MEDIA_PLAYS | :MEDIA_PLAYS_PERCENT | :ATTENTION_SPAN

            module EventType
              extend HubspotSDK::Internal::Type::Enum

              ALL: :ALL
              MEDIA_PLAYS: :MEDIA_PLAYS
              MEDIA_PLAYS_PERCENT: :MEDIA_PLAYS_PERCENT
              ATTENTION_SPAN: :ATTENTION_SPAN

              def self?.values: -> ::Array[HubspotSDK::Models::Cms::MediaBridge::IntegratorSettingGetEventVisibilitySettingsResponse::VisibilitySetting::event_type]
            end
          end
        end
      end
    end
  end
end
