module HubspotSDK
  module Resources
    class Automation
      attr_reader actions: HubspotSDK::Resources::Automation::Actions

      def initialize: (client: HubspotSDK::Client) -> void
    end
  end
end
