module HubSpotSDK
  module Resources
    class Automation
      attr_reader actions: HubSpotSDK::Resources::Automation::Actions

      attr_reader sequences: HubSpotSDK::Resources::Automation::Sequences

      def initialize: (client: HubSpotSDK::Client) -> void
    end
  end
end
