module HubSpotSDK
  module Resources
    class CommunicationPreferences
      attr_reader definitions: HubSpotSDK::Resources::CommunicationPreferences::Definitions

      attr_reader statuses: HubSpotSDK::Resources::CommunicationPreferences::Statuses

      def generate_links: (
        channel: HubSpotSDK::Models::CommunicationPreferences::LinkGenerationRequest::channel,
        subscriber_id_string: String,
        ?business_unit_id: Integer,
        ?language: String,
        ?subscription_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::CommunicationPreferences::LinkGenerationResponse

      def get_statuses: (
        String subscriber_id_string,
        channel: HubSpotSDK::Models::CommunicationPreferences::CommunicationPreferenceGetStatusesParams::channel,
        ?business_unit_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::CommunicationPreferences::ActionResponseWithResultsPublicStatus

      def get_unsubscribe_all_status: (
        String subscriber_id_string,
        channel: HubSpotSDK::Models::CommunicationPreferences::CommunicationPreferenceGetUnsubscribeAllStatusParams::channel,
        ?business_unit_id: Integer,
        ?verbose: bool,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::CommunicationPreferences::ActionResponseWithResultsPublicWideStatus

      def unsubscribe_all: (
        String subscriber_id_string,
        channel: HubSpotSDK::Models::CommunicationPreferences::CommunicationPreferenceUnsubscribeAllParams::channel,
        ?business_unit_id: Integer,
        ?verbose: bool,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::CommunicationPreferences::ActionResponseWithResultsPublicStatus

      def update_status: (
        String subscriber_id_string,
        channel: HubSpotSDK::Models::CommunicationPreferences::PartialPublicStatusRequest::channel,
        status_state: HubSpotSDK::Models::CommunicationPreferences::PartialPublicStatusRequest::status_state,
        subscription_id: Integer,
        ?legal_basis: HubSpotSDK::Models::CommunicationPreferences::PartialPublicStatusRequest::legal_basis,
        ?legal_basis_explanation: String,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::CommunicationPreferences::ActionResponseWithResultsPublicStatus

      def initialize: (client: HubSpotSDK::Client) -> void
    end
  end
end
