module HubspotSDK
  module Resources
    class CommunicationPreferences
      attr_reader definitions: HubspotSDK::Resources::CommunicationPreferences::Definitions

      attr_reader statuses: HubspotSDK::Resources::CommunicationPreferences::Statuses

      def generate_links: (
        channel: HubspotSDK::Models::CommunicationPreferences::LinkGenerationRequest::channel,
        subscriber_id_string: String,
        ?business_unit_id: Integer,
        ?language: String,
        ?subscription_id: Integer,
        ?request_options: HubspotSDK::request_opts
      ) -> HubspotSDK::CommunicationPreferences::LinkGenerationResponse

      def get_status_by_email: (
        String email_address,
        ?request_options: HubspotSDK::request_opts
      ) -> HubspotSDK::CommunicationPreferences::PublicSubscriptionStatusesResponse

      def get_statuses: (
        String subscriber_id_string,
        channel: HubspotSDK::Models::CommunicationPreferences::CommunicationPreferenceGetStatusesParams::channel,
        ?business_unit_id: Integer,
        ?request_options: HubspotSDK::request_opts
      ) -> HubspotSDK::CommunicationPreferences::ActionResponseWithResultsPublicStatus

      def get_unsubscribe_all_status: (
        String subscriber_id_string,
        channel: HubspotSDK::Models::CommunicationPreferences::CommunicationPreferenceGetUnsubscribeAllStatusParams::channel,
        ?business_unit_id: Integer,
        ?verbose: bool,
        ?request_options: HubspotSDK::request_opts
      ) -> HubspotSDK::CommunicationPreferences::ActionResponseWithResultsPublicWideStatus

      def subscribe: (
        email_address: String,
        subscription_id: String,
        ?legal_basis: HubspotSDK::Models::CommunicationPreferences::PublicUpdateSubscriptionStatusRequest::legal_basis,
        ?legal_basis_explanation: String,
        ?request_options: HubspotSDK::request_opts
      ) -> HubspotSDK::CommunicationPreferences::PublicSubscriptionStatus

      def unsubscribe: (
        email_address: String,
        subscription_id: String,
        ?legal_basis: HubspotSDK::Models::CommunicationPreferences::PublicUpdateSubscriptionStatusRequest::legal_basis,
        ?legal_basis_explanation: String,
        ?request_options: HubspotSDK::request_opts
      ) -> HubspotSDK::CommunicationPreferences::PublicSubscriptionStatus

      def unsubscribe_all: (
        String subscriber_id_string,
        channel: HubspotSDK::Models::CommunicationPreferences::CommunicationPreferenceUnsubscribeAllParams::channel,
        ?business_unit_id: Integer,
        ?verbose: bool,
        ?request_options: HubspotSDK::request_opts
      ) -> HubspotSDK::CommunicationPreferences::ActionResponseWithResultsPublicStatus

      def update_status: (
        String subscriber_id_string,
        channel: HubspotSDK::Models::CommunicationPreferences::PartialPublicStatusRequest::channel,
        status_state: HubspotSDK::Models::CommunicationPreferences::PartialPublicStatusRequest::status_state,
        subscription_id: Integer,
        ?legal_basis: HubspotSDK::Models::CommunicationPreferences::PartialPublicStatusRequest::legal_basis,
        ?legal_basis_explanation: String,
        ?request_options: HubspotSDK::request_opts
      ) -> HubspotSDK::CommunicationPreferences::ActionResponseWithResultsPublicStatus

      def initialize: (client: HubspotSDK::Client) -> void
    end
  end
end
