module HubspotSDK
  module Resources
    class Crm
      attr_reader app_uninstalls: HubspotSDK::Resources::Crm::AppUninstalls

      attr_reader associations: HubspotSDK::Resources::Crm::Associations

      attr_reader exports: HubspotSDK::Resources::Crm::Exports

      attr_reader extensions: HubspotSDK::Resources::Crm::Extensions

      attr_reader feature_flags: HubspotSDK::Resources::Crm::FeatureFlags

      attr_reader imports: HubspotSDK::Resources::Crm::Imports

      attr_reader limits: HubspotSDK::Resources::Crm::Limits

      attr_reader lists: HubspotSDK::Resources::Crm::Lists

      attr_reader object_library: HubspotSDK::Resources::Crm::ObjectLibrary

      attr_reader objects: HubspotSDK::Resources::Crm::Objects

      attr_reader owners: HubspotSDK::Resources::Crm::Owners

      attr_reader pipelines: HubspotSDK::Resources::Crm::Pipelines

      attr_reader properties: HubspotSDK::Resources::Crm::Properties

      attr_reader property_validations: HubspotSDK::Resources::Crm::PropertyValidations

      attr_reader timeline: HubspotSDK::Resources::Crm::Timeline

      attr_reader users: HubspotSDK::Resources::Crm::Users

      def initialize: (client: HubspotSDK::Client) -> void
    end
  end
end
