module HubSpotSDK
  module Resources
    class Events
      attr_reader definitions: HubSpotSDK::Resources::Events::Definitions

      attr_reader occurrences: HubSpotSDK::Resources::Events::Occurrences

      attr_reader send_: HubSpotSDK::Resources::Events::Send

      def initialize: (client: HubSpotSDK::Client) -> void
    end
  end
end
