module HubSpotSDK
  module Resources
    class Files
      attr_reader file_assets: HubSpotSDK::Resources::Files::FileAssets

      attr_reader folders: HubSpotSDK::Resources::Files::Folders

      def initialize: (client: HubSpotSDK::Client) -> void
    end
  end
end
