module HubspotSDK
  module Resources
    class Files
      attr_reader file_operations: HubspotSDK::Resources::Files::FileOperations

      attr_reader folders: HubspotSDK::Resources::Files::Folders

      def initialize: (client: HubspotSDK::Client) -> void
    end
  end
end
