module HubSpotSDK
  module Resources
    class Marketing
      attr_reader campaigns: HubSpotSDK::Resources::Marketing::Campaigns

      attr_reader emails: HubSpotSDK::Resources::Marketing::Emails

      attr_reader marketing_events: HubSpotSDK::Resources::Marketing::MarketingEvents

      attr_reader single_send: HubSpotSDK::Resources::Marketing::SingleSend

      attr_reader transactional: HubSpotSDK::Resources::Marketing::Transactional

      def initialize: (client: HubSpotSDK::Client) -> void
    end
  end
end
