module HubspotSDK
  module Resources
    class Scheduler
      attr_reader meetings: HubspotSDK::Resources::Scheduler::Meetings

      def initialize: (client: HubspotSDK::Client) -> void
    end
  end
end
