module HubSpotSDK
  module Resources
    class Scheduler
      attr_reader meetings: HubSpotSDK::Resources::Scheduler::Meetings

      def initialize: (client: HubSpotSDK::Client) -> void
    end
  end
end
