module HubSpotSDK
  module Resources
    class Settings
      attr_reader currencies: HubSpotSDK::Resources::Settings::Currencies

      attr_reader tax_rates: HubSpotSDK::Resources::Settings::TaxRates

      attr_reader users: HubSpotSDK::Resources::Settings::Users

      def initialize: (client: HubSpotSDK::Client) -> void
    end
  end
end
