module HubspotSDK
  module Resources
    class Settings
      attr_reader currencies: HubspotSDK::Resources::Settings::Currencies

      attr_reader tax_rates: HubspotSDK::Resources::Settings::TaxRates

      def initialize: (client: HubspotSDK::Client) -> void
    end
  end
end
