module HubSpotSDK
  module Resources
    class Webhooks
      def create_crm_snapshot: (
        snapshot_requests: ::Array[HubSpotSDK::Webhooks::CrmObjectSnapshotRequest],
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::CrmObjectSnapshotBatchResponse

      def create_journal_subscription: (
        subscription_upsert_request: HubSpotSDK::Models::Webhooks::subscription_upsert_request,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::SubscriptionResponse1

      def create_subscription: (
        Integer app_id,
        active: bool,
        event_type: HubSpotSDK::Models::Webhooks::SubscriptionCreateRequest::event_type,
        ?event_type_name: String,
        ?object_type_id: String,
        ?property_name: String,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::SubscriptionResponse

      def create_subscription_filter: (
        filter: HubSpotSDK::Webhooks::Filter,
        subscription_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::FilterCreateResponse

      def create_subscriptions_batch: (
        Integer app_id,
        inputs: ::Array[HubSpotSDK::Webhooks::SubscriptionBatchUpdateRequest],
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::BatchResponseSubscriptionResponse

      def delete_journal_subscription: (
        Integer subscription_id,
        ?request_options: HubSpotSDK::request_opts
      ) -> nil

      def delete_portal_subscriptions: (
        Integer portal_id,
        ?request_options: HubSpotSDK::request_opts
      ) -> nil

      def delete_settings: (
        Integer app_id,
        ?request_options: HubSpotSDK::request_opts
      ) -> nil

      def delete_subscription: (
        Integer subscription_id,
        app_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> nil

      def delete_subscription_filter: (
        Integer filter_id,
        ?request_options: HubSpotSDK::request_opts
      ) -> nil

      def get_earliest_journal: (
        ?install_portal_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> StringIO

      def get_earliest_journal_batch: (
        Integer count,
        ?install_portal_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::BatchResponseJournalFetchResponse

      def get_earliest_local_journal: (
        ?install_portal_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> StringIO

      def get_earliest_local_journal_batch: (
        Integer count,
        ?install_portal_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::BatchResponseJournalFetchResponse

      def get_journal_batch: (
        inputs: ::Array[String],
        ?install_portal_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::BatchResponseJournalFetchResponse

      def get_journal_batch_after_offset: (
        Integer count,
        offset: String,
        ?install_portal_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::BatchResponseJournalFetchResponse

      def get_journal_status: (
        String status_id,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::SnapshotStatusResponse

      def get_latest_journal: (
        ?install_portal_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> StringIO

      def get_latest_journal_batch: (
        Integer count,
        ?install_portal_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::BatchResponseJournalFetchResponse

      def get_latest_local_journal: (
        ?install_portal_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> StringIO

      def get_latest_local_journal_batch: (
        Integer count,
        ?install_portal_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::BatchResponseJournalFetchResponse

      def get_local_journal_batch: (
        inputs: ::Array[String],
        ?install_portal_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::BatchResponseJournalFetchResponse

      def get_local_journal_batch_after_offset: (
        Integer count,
        offset: String,
        ?install_portal_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::BatchResponseJournalFetchResponse

      def get_local_journal_status: (
        String status_id,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::SnapshotStatusResponse

      def get_next_journal_after_offset: (
        String offset,
        ?install_portal_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> StringIO

      def get_next_local_journal_after_offset: (
        String offset,
        ?install_portal_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> StringIO

      def get_settings: (
        Integer app_id,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::SettingsResponse

      def get_subscription: (
        Integer subscription_id,
        app_id: Integer,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::SubscriptionResponse

      def get_subscription_filter: (
        Integer filter_id,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::FilterResponse

      def get_subscription_filters: (
        Integer subscription_id,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Models::Webhooks::webhook_get_subscription_filters_response

      def list_journal_subscriptions: (
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::CollectionResponseSubscriptionResponseNoPaging

      def list_subscriptions: (
        Integer app_id,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::SubscriptionListResponse

      def update_settings: (
        Integer app_id,
        target_url: String,
        throttling: HubSpotSDK::Webhooks::ThrottlingSettings,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::SettingsResponse

      def update_subscription: (
        Integer subscription_id,
        app_id: Integer,
        ?active: bool,
        ?request_options: HubSpotSDK::request_opts
      ) -> HubSpotSDK::Webhooks::SubscriptionResponse

      def initialize: (client: HubSpotSDK::Client) -> void
    end
  end
end
