module HubspotSDK
  module Resources
    class Webhooks
      attr_reader settings: HubspotSDK::Resources::Webhooks::Settings

      attr_reader subscriptions: HubspotSDK::Resources::Webhooks::Subscriptions

      def initialize: (client: HubspotSDK::Client) -> void
    end
  end
end
