module HubSpotSDK
  module Resources
    class Crm
      class Timeline
        class Batch
          def create: (
            inputs: ::Array[HubSpotSDK::Crm::AppEventOccurrence],
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Crm::BatchResponseAppEventOccurrence

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
