module HubSpotSDK
  module Models
    module Marketing
      module Transactional
        type single_email_send_params =
          {  } & HubSpotSDK::Internal::Type::request_parameters

        class SingleEmailSendParams < HubSpotSDK::Models::Marketing::PublicSingleSendRequestEgg
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          def initialize: (?request_options: HubSpotSDK::request_opts) -> void

          def to_hash: -> { request_options: HubSpotSDK::RequestOptions }
        end
      end
    end
  end
end
