module HubspotSDK
  module Models
    module Marketing
      module Transactional
        type smtp_token_list_params =
          {
            after: String,
            campaign_name: String,
            email_campaign_id: String,
            limit: Integer
          }
          & HubspotSDK::Internal::Type::request_parameters

        class SmtpTokenListParams < HubspotSDK::Internal::Type::BaseModel
          extend HubspotSDK::Internal::Type::RequestParameters::Converter
          include HubspotSDK::Internal::Type::RequestParameters

          attr_reader after: String?

          def after=: (String) -> String

          attr_reader campaign_name: String?

          def campaign_name=: (String) -> String

          attr_reader email_campaign_id: String?

          def email_campaign_id=: (String) -> String

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          def initialize: (
            ?after: String,
            ?campaign_name: String,
            ?email_campaign_id: String,
            ?limit: Integer,
            ?request_options: HubspotSDK::request_opts
          ) -> void

          def to_hash: -> {
            after: String,
            campaign_name: String,
            email_campaign_id: String,
            limit: Integer,
            request_options: HubspotSDK::RequestOptions
          }
        end
      end
    end
  end
end
