module HubSpotSDK
  module Models
    module Marketing
      module Transactional
        type smtp_token_delete_params =
          { token_id: String } & HubSpotSDK::Internal::Type::request_parameters

        class SmtpTokenDeleteParams < HubSpotSDK::Internal::Type::BaseModel
          extend HubSpotSDK::Internal::Type::RequestParameters::Converter
          include HubSpotSDK::Internal::Type::RequestParameters

          attr_accessor token_id: String

          def initialize: (
            token_id: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> void

          def to_hash: -> {
            token_id: String,
            request_options: HubSpotSDK::RequestOptions
          }
        end
      end
    end
  end
end
