module HubspotSDK
  module Models
    module Crm
      module Associations
        module Schema
          type batch_input_public_association_definition_configuration_create_request =
            {
              inputs: ::Array[HubspotSDK::Crm::Associations::Schema::PublicAssociationDefinitionConfigurationCreateRequest]
            }

          class BatchInputPublicAssociationDefinitionConfigurationCreateRequest < HubspotSDK::Internal::Type::BaseModel
            attr_accessor inputs: ::Array[HubspotSDK::Crm::Associations::Schema::PublicAssociationDefinitionConfigurationCreateRequest]

            def initialize: (
              inputs: ::Array[HubspotSDK::Crm::Associations::Schema::PublicAssociationDefinitionConfigurationCreateRequest]
            ) -> void

            def to_hash: -> {
              inputs: ::Array[HubspotSDK::Crm::Associations::Schema::PublicAssociationDefinitionConfigurationCreateRequest]
            }
          end
        end
      end
    end
  end
end
