module HubspotSDK
  module Models
    module Crm
      module Associations
        module Schema
          type collection_response_public_association_definition_user_configuration =
            {
              results: ::Array[HubspotSDK::Crm::Associations::Schema::PublicAssociationDefinitionUserConfiguration],
              paging: HubspotSDK::Marketing::Paging
            }

          class CollectionResponsePublicAssociationDefinitionUserConfiguration < HubspotSDK::Internal::Type::BaseModel
            attr_accessor results: ::Array[HubspotSDK::Crm::Associations::Schema::PublicAssociationDefinitionUserConfiguration]

            attr_reader paging: HubspotSDK::Marketing::Paging?

            def paging=: (
              HubspotSDK::Marketing::Paging
            ) -> HubspotSDK::Marketing::Paging

            def initialize: (
              results: ::Array[HubspotSDK::Crm::Associations::Schema::PublicAssociationDefinitionUserConfiguration],
              ?paging: HubspotSDK::Marketing::Paging
            ) -> void

            def to_hash: -> {
              results: ::Array[HubspotSDK::Crm::Associations::Schema::PublicAssociationDefinitionUserConfiguration],
              paging: HubspotSDK::Marketing::Paging
            }
          end
        end
      end
    end
  end
end
