module HubSpotSDK
  module Models
    module Events
      type batched_behavioral_event_http_completion_request =
        {
          inputs: ::Array[HubSpotSDK::Events::BehavioralEventHTTPCompletionRequest]
        }

      class BatchedBehavioralEventHTTPCompletionRequest < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor inputs: ::Array[HubSpotSDK::Events::BehavioralEventHTTPCompletionRequest]

        def initialize: (
          inputs: ::Array[HubSpotSDK::Events::BehavioralEventHTTPCompletionRequest]
        ) -> void

        def to_hash: -> {
          inputs: ::Array[HubSpotSDK::Events::BehavioralEventHTTPCompletionRequest]
        }
      end
    end
  end
end
