module HubspotSDK
  module Models
    module Events
      type behavioral_event_type_definition_labels =
        { singular: String, plural: String }

      class BehavioralEventTypeDefinitionLabels < HubspotSDK::Internal::Type::BaseModel
        attr_accessor singular: String

        attr_reader plural: String?

        def plural=: (String) -> String

        def initialize: (singular: String, ?plural: String) -> void

        def to_hash: -> { singular: String, plural: String }
      end
    end
  end
end
