module HubspotSDK
  module Models
    module Events
      type bool_property_operation =
        {
          include_objects_with_no_value_set: bool,
          operation_type: String,
          operator: HubspotSDK::Models::Events::BoolPropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::BoolPropertyOperation::property_type,
          value: bool,
          default_value: String
        }

      class BoolPropertyOperation < HubspotSDK::Internal::Type::BaseModel
        attr_accessor include_objects_with_no_value_set: bool

        attr_accessor operation_type: String

        attr_accessor operator: HubspotSDK::Models::Events::BoolPropertyOperation::operator

        attr_accessor operator_name: String

        attr_accessor property_type: HubspotSDK::Models::Events::BoolPropertyOperation::property_type

        attr_accessor value: bool

        attr_reader default_value: String?

        def default_value=: (String) -> String

        def initialize: (
          include_objects_with_no_value_set: bool,
          operation_type: String,
          operator: HubspotSDK::Models::Events::BoolPropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::BoolPropertyOperation::property_type,
          value: bool,
          ?default_value: String
        ) -> void

        def to_hash: -> {
          include_objects_with_no_value_set: bool,
          operation_type: String,
          operator: HubspotSDK::Models::Events::BoolPropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::BoolPropertyOperation::property_type,
          value: bool,
          default_value: String
        }

        type operator =
          :IS_EQUAL_TO
          | :IS_NOT_EQUAL_TO
          | :HAS_EVER_BEEN_EQUAL_TO
          | :HAS_NEVER_BEEN_EQUAL_TO

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          IS_EQUAL_TO: :IS_EQUAL_TO
          IS_NOT_EQUAL_TO: :IS_NOT_EQUAL_TO
          HAS_EVER_BEEN_EQUAL_TO: :HAS_EVER_BEEN_EQUAL_TO
          HAS_NEVER_BEEN_EQUAL_TO: :HAS_NEVER_BEEN_EQUAL_TO

          def self?.values: -> ::Array[HubspotSDK::Models::Events::BoolPropertyOperation::operator]
        end

        type property_type = :bool

        module PropertyType
          extend HubspotSDK::Internal::Type::Enum

          BOOL: :bool

          def self?.values: -> ::Array[HubspotSDK::Models::Events::BoolPropertyOperation::property_type]
        end
      end
    end
  end
end
