module HubspotSDK
  module Models
    module Events
      type calendar_date_property_operation =
        {
          include_objects_with_no_value_set: bool,
          operation_type: String,
          operator: HubspotSDK::Models::Events::CalendarDatePropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::CalendarDatePropertyOperation::property_type,
          time_unit: HubspotSDK::Models::Events::CalendarDatePropertyOperation::time_unit,
          time_unit_count: Integer,
          use_fiscal_year: bool,
          default_value: String,
          fiscal_year_start: HubspotSDK::Models::Events::CalendarDatePropertyOperation::fiscal_year_start
        }

      class CalendarDatePropertyOperation < HubspotSDK::Internal::Type::BaseModel
        attr_accessor include_objects_with_no_value_set: bool

        attr_accessor operation_type: String

        attr_accessor operator: HubspotSDK::Models::Events::CalendarDatePropertyOperation::operator

        attr_accessor operator_name: String

        attr_accessor property_type: HubspotSDK::Models::Events::CalendarDatePropertyOperation::property_type

        attr_accessor time_unit: HubspotSDK::Models::Events::CalendarDatePropertyOperation::time_unit

        attr_accessor time_unit_count: Integer

        attr_accessor use_fiscal_year: bool

        attr_reader default_value: String?

        def default_value=: (String) -> String

        attr_reader fiscal_year_start: HubspotSDK::Models::Events::CalendarDatePropertyOperation::fiscal_year_start?

        def fiscal_year_start=: (
          HubspotSDK::Models::Events::CalendarDatePropertyOperation::fiscal_year_start
        ) -> HubspotSDK::Models::Events::CalendarDatePropertyOperation::fiscal_year_start

        def initialize: (
          include_objects_with_no_value_set: bool,
          operation_type: String,
          operator: HubspotSDK::Models::Events::CalendarDatePropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::CalendarDatePropertyOperation::property_type,
          time_unit: HubspotSDK::Models::Events::CalendarDatePropertyOperation::time_unit,
          time_unit_count: Integer,
          use_fiscal_year: bool,
          ?default_value: String,
          ?fiscal_year_start: HubspotSDK::Models::Events::CalendarDatePropertyOperation::fiscal_year_start
        ) -> void

        def to_hash: -> {
          include_objects_with_no_value_set: bool,
          operation_type: String,
          operator: HubspotSDK::Models::Events::CalendarDatePropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::CalendarDatePropertyOperation::property_type,
          time_unit: HubspotSDK::Models::Events::CalendarDatePropertyOperation::time_unit,
          time_unit_count: Integer,
          use_fiscal_year: bool,
          default_value: String,
          fiscal_year_start: HubspotSDK::Models::Events::CalendarDatePropertyOperation::fiscal_year_start
        }

        type operator =
          :IN_LAST_TIME_UNIT
          | :IN_NEXT_TIME_UNIT
          | :IN_THIS_TIME_UNIT
          | :IN_THIS_TIME_UNIT_SO_FAR

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          IN_LAST_TIME_UNIT: :IN_LAST_TIME_UNIT
          IN_NEXT_TIME_UNIT: :IN_NEXT_TIME_UNIT
          IN_THIS_TIME_UNIT: :IN_THIS_TIME_UNIT
          IN_THIS_TIME_UNIT_SO_FAR: :IN_THIS_TIME_UNIT_SO_FAR

          def self?.values: -> ::Array[HubspotSDK::Models::Events::CalendarDatePropertyOperation::operator]
        end

        type property_type = :"calendar-date"

        module PropertyType
          extend HubspotSDK::Internal::Type::Enum

          CALENDAR_DATE: :"calendar-date"

          def self?.values: -> ::Array[HubspotSDK::Models::Events::CalendarDatePropertyOperation::property_type]
        end

        type time_unit = :DAY | :MONTH | :QUARTER | :WEEK | :YEAR

        module TimeUnit
          extend HubspotSDK::Internal::Type::Enum

          DAY: :DAY
          MONTH: :MONTH
          QUARTER: :QUARTER
          WEEK: :WEEK
          YEAR: :YEAR

          def self?.values: -> ::Array[HubspotSDK::Models::Events::CalendarDatePropertyOperation::time_unit]
        end

        type fiscal_year_start =
          :APRIL
          | :AUGUST
          | :DECEMBER
          | :FEBRUARY
          | :JANUARY
          | :JULY
          | :JUNE
          | :MARCH
          | :MAY
          | :NOVEMBER
          | :OCTOBER
          | :SEPTEMBER

        module FiscalYearStart
          extend HubspotSDK::Internal::Type::Enum

          APRIL: :APRIL
          AUGUST: :AUGUST
          DECEMBER: :DECEMBER
          FEBRUARY: :FEBRUARY
          JANUARY: :JANUARY
          JULY: :JULY
          JUNE: :JUNE
          MARCH: :MARCH
          MAY: :MAY
          NOVEMBER: :NOVEMBER
          OCTOBER: :OCTOBER
          SEPTEMBER: :SEPTEMBER

          def self?.values: -> ::Array[HubspotSDK::Models::Events::CalendarDatePropertyOperation::fiscal_year_start]
        end
      end
    end
  end
end
