module HubspotSDK
  module Models
    module Events
      type collection_response_external_unified_event =
        {
          results: ::Array[HubspotSDK::Events::ExternalUnifiedEvent],
          paging: HubspotSDK::Marketing::Paging
        }

      class CollectionResponseExternalUnifiedEvent < HubspotSDK::Internal::Type::BaseModel
        attr_accessor results: ::Array[HubspotSDK::Events::ExternalUnifiedEvent]

        attr_reader paging: HubspotSDK::Marketing::Paging?

        def paging=: (
          HubspotSDK::Marketing::Paging
        ) -> HubspotSDK::Marketing::Paging

        def initialize: (
          results: ::Array[HubspotSDK::Events::ExternalUnifiedEvent],
          ?paging: HubspotSDK::Marketing::Paging
        ) -> void

        def to_hash: -> {
          results: ::Array[HubspotSDK::Events::ExternalUnifiedEvent],
          paging: HubspotSDK::Marketing::Paging
        }
      end
    end
  end
end
