module HubspotSDK
  module Models
    module Events
      type date_point =
        {
          day: Integer,
          month: Integer,
          time_type: HubspotSDK::Models::Events::DatePoint::time_type,
          timezone_source: HubspotSDK::Models::Events::DatePoint::timezone_source,
          year: Integer,
          zone_id: String,
          hour: Integer,
          millisecond: Integer,
          minute: Integer,
          second: Integer
        }

      class DatePoint < HubspotSDK::Internal::Type::BaseModel
        attr_accessor day: Integer

        attr_accessor month: Integer

        attr_accessor time_type: HubspotSDK::Models::Events::DatePoint::time_type

        attr_accessor timezone_source: HubspotSDK::Models::Events::DatePoint::timezone_source

        attr_accessor year: Integer

        attr_accessor zone_id: String

        attr_reader hour: Integer?

        def hour=: (Integer) -> Integer

        attr_reader millisecond: Integer?

        def millisecond=: (Integer) -> Integer

        attr_reader minute: Integer?

        def minute=: (Integer) -> Integer

        attr_reader second: Integer?

        def second=: (Integer) -> Integer

        def initialize: (
          day: Integer,
          month: Integer,
          time_type: HubspotSDK::Models::Events::DatePoint::time_type,
          timezone_source: HubspotSDK::Models::Events::DatePoint::timezone_source,
          year: Integer,
          zone_id: String,
          ?hour: Integer,
          ?millisecond: Integer,
          ?minute: Integer,
          ?second: Integer
        ) -> void

        def to_hash: -> {
          day: Integer,
          month: Integer,
          time_type: HubspotSDK::Models::Events::DatePoint::time_type,
          timezone_source: HubspotSDK::Models::Events::DatePoint::timezone_source,
          year: Integer,
          zone_id: String,
          hour: Integer,
          millisecond: Integer,
          minute: Integer,
          second: Integer
        }

        type time_type = :DATE

        module TimeType
          extend HubspotSDK::Internal::Type::Enum

          DATE: :DATE

          def self?.values: -> ::Array[HubspotSDK::Models::Events::DatePoint::time_type]
        end

        type timezone_source = :CUSTOM | :USER | :PORTAL

        module TimezoneSource
          extend HubspotSDK::Internal::Type::Enum

          CUSTOM: :CUSTOM
          USER: :USER
          PORTAL: :PORTAL

          def self?.values: -> ::Array[HubspotSDK::Models::Events::DatePoint::timezone_source]
        end
      end
    end
  end
end
