module HubspotSDK
  module Models
    module Events
      type date_property_operation =
        {
          day: Integer,
          include_objects_with_no_value_set: bool,
          month: HubspotSDK::Models::Events::DatePropertyOperation::month,
          operation_type: String,
          operator: HubspotSDK::Models::Events::DatePropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::DatePropertyOperation::property_type,
          year: Integer,
          default_value: String
        }

      class DatePropertyOperation < HubspotSDK::Internal::Type::BaseModel
        attr_accessor day: Integer

        attr_accessor include_objects_with_no_value_set: bool

        attr_accessor month: HubspotSDK::Models::Events::DatePropertyOperation::month

        attr_accessor operation_type: String

        attr_accessor operator: HubspotSDK::Models::Events::DatePropertyOperation::operator

        attr_accessor operator_name: String

        attr_accessor property_type: HubspotSDK::Models::Events::DatePropertyOperation::property_type

        attr_accessor year: Integer

        attr_reader default_value: String?

        def default_value=: (String) -> String

        def initialize: (
          day: Integer,
          include_objects_with_no_value_set: bool,
          month: HubspotSDK::Models::Events::DatePropertyOperation::month,
          operation_type: String,
          operator: HubspotSDK::Models::Events::DatePropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::DatePropertyOperation::property_type,
          year: Integer,
          ?default_value: String
        ) -> void

        def to_hash: -> {
          day: Integer,
          include_objects_with_no_value_set: bool,
          month: HubspotSDK::Models::Events::DatePropertyOperation::month,
          operation_type: String,
          operator: HubspotSDK::Models::Events::DatePropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::DatePropertyOperation::property_type,
          year: Integer,
          default_value: String
        }

        type month =
          :JAN
          | :FEB
          | :MAR
          | :APR
          | :MAY
          | :JUN
          | :JUL
          | :AUG
          | :SEP
          | :OCT
          | :NOV
          | :DEC

        module Month
          extend HubspotSDK::Internal::Type::Enum

          JAN: :JAN
          FEB: :FEB
          MAR: :MAR
          APR: :APR
          MAY: :MAY
          JUN: :JUN
          JUL: :JUL
          AUG: :AUG
          SEP: :SEP
          OCT: :OCT
          NOV: :NOV
          DEC: :DEC

          def self?.values: -> ::Array[HubspotSDK::Models::Events::DatePropertyOperation::month]
        end

        type operator = :EQUAL | :BEFORE | :AFTER

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          EQUAL: :EQUAL
          BEFORE: :BEFORE
          AFTER: :AFTER

          def self?.values: -> ::Array[HubspotSDK::Models::Events::DatePropertyOperation::operator]
        end

        type property_type = :date

        module PropertyType
          extend HubspotSDK::Internal::Type::Enum

          DATE: :date

          def self?.values: -> ::Array[HubspotSDK::Models::Events::DatePropertyOperation::property_type]
        end
      end
    end
  end
end
