module HubSpotSDK
  module Models
    module Events
      type definition_create_property_params =
        { event_name: String } & HubSpotSDK::Internal::Type::request_parameters

      class DefinitionCreatePropertyParams < HubSpotSDK::Models::Events::ExternalBehavioralEventPropertyCreate
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        def event_name: -> String

        def event_name=: (String _) -> String

        def initialize: (
          event_name: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          event_name: String,
          request_options: HubSpotSDK::RequestOptions
        }
      end
    end
  end
end
