module HubSpotSDK
  module Models
    module Events
      type external_behavioral_event_type_definition =
        {
          id: String,
          archived: bool,
          associations: ::Array[HubSpotSDK::Events::AssociationDefinition],
          fully_qualified_name: String,
          labels: HubSpotSDK::Events::BehavioralEventTypeDefinitionLabels,
          name: String,
          object_type_id: String,
          properties: ::Array[HubSpotSDK::Events::Property],
          combo_event_rules: HubSpotSDK::Events::ComboEventRuleBranch,
          created_at: Time,
          created_user_id: Integer,
          custom_matching_id: HubSpotSDK::Events::ExternalObjectResolutionMappingResponse,
          description: String,
          primary_object: String,
          primary_object_id: String,
          tracking_type: HubSpotSDK::Models::Events::ExternalBehavioralEventTypeDefinition::tracking_type,
          updated_at: Time,
          updated_user_id: Integer
        }

      class ExternalBehavioralEventTypeDefinition < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor archived: bool

        attr_accessor associations: ::Array[HubSpotSDK::Events::AssociationDefinition]

        attr_accessor fully_qualified_name: String

        attr_accessor labels: HubSpotSDK::Events::BehavioralEventTypeDefinitionLabels

        attr_accessor name: String

        attr_accessor object_type_id: String

        attr_accessor properties: ::Array[HubSpotSDK::Events::Property]

        attr_reader combo_event_rules: HubSpotSDK::Events::ComboEventRuleBranch?

        def combo_event_rules=: (
          HubSpotSDK::Events::ComboEventRuleBranch
        ) -> HubSpotSDK::Events::ComboEventRuleBranch

        attr_reader created_at: Time?

        def created_at=: (Time) -> Time

        attr_reader created_user_id: Integer?

        def created_user_id=: (Integer) -> Integer

        attr_reader custom_matching_id: HubSpotSDK::Events::ExternalObjectResolutionMappingResponse?

        def custom_matching_id=: (
          HubSpotSDK::Events::ExternalObjectResolutionMappingResponse
        ) -> HubSpotSDK::Events::ExternalObjectResolutionMappingResponse

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader primary_object: String?

        def primary_object=: (String) -> String

        attr_reader primary_object_id: String?

        def primary_object_id=: (String) -> String

        attr_reader tracking_type: HubSpotSDK::Models::Events::ExternalBehavioralEventTypeDefinition::tracking_type?

        def tracking_type=: (
          HubSpotSDK::Models::Events::ExternalBehavioralEventTypeDefinition::tracking_type
        ) -> HubSpotSDK::Models::Events::ExternalBehavioralEventTypeDefinition::tracking_type

        attr_reader updated_at: Time?

        def updated_at=: (Time) -> Time

        attr_reader updated_user_id: Integer?

        def updated_user_id=: (Integer) -> Integer

        def initialize: (
          id: String,
          archived: bool,
          associations: ::Array[HubSpotSDK::Events::AssociationDefinition],
          fully_qualified_name: String,
          labels: HubSpotSDK::Events::BehavioralEventTypeDefinitionLabels,
          name: String,
          object_type_id: String,
          properties: ::Array[HubSpotSDK::Events::Property],
          ?combo_event_rules: HubSpotSDK::Events::ComboEventRuleBranch,
          ?created_at: Time,
          ?created_user_id: Integer,
          ?custom_matching_id: HubSpotSDK::Events::ExternalObjectResolutionMappingResponse,
          ?description: String,
          ?primary_object: String,
          ?primary_object_id: String,
          ?tracking_type: HubSpotSDK::Models::Events::ExternalBehavioralEventTypeDefinition::tracking_type,
          ?updated_at: Time,
          ?updated_user_id: Integer
        ) -> void

        def to_hash: -> {
          id: String,
          archived: bool,
          associations: ::Array[HubSpotSDK::Events::AssociationDefinition],
          fully_qualified_name: String,
          labels: HubSpotSDK::Events::BehavioralEventTypeDefinitionLabels,
          name: String,
          object_type_id: String,
          properties: ::Array[HubSpotSDK::Events::Property],
          combo_event_rules: HubSpotSDK::Events::ComboEventRuleBranch,
          created_at: Time,
          created_user_id: Integer,
          custom_matching_id: HubSpotSDK::Events::ExternalObjectResolutionMappingResponse,
          description: String,
          primary_object: String,
          primary_object_id: String,
          tracking_type: HubSpotSDK::Models::Events::ExternalBehavioralEventTypeDefinition::tracking_type,
          updated_at: Time,
          updated_user_id: Integer
        }

        type tracking_type =
          :APP_EVENT
          | :AUTOCAPTURE_EVENT
          | :CLICKED_ELEMENT
          | :COMBO_EVENT
          | :CUSTOM_SCRIPT
          | :CUSTOM_SIGNAL
          | :IMPORT
          | :MANUAL
          | :PROPERTY_CHANGE
          | :VISITED_URL
          | :WEBHOOK

        module TrackingType
          extend HubSpotSDK::Internal::Type::Enum

          APP_EVENT: :APP_EVENT
          AUTOCAPTURE_EVENT: :AUTOCAPTURE_EVENT
          CLICKED_ELEMENT: :CLICKED_ELEMENT
          COMBO_EVENT: :COMBO_EVENT
          CUSTOM_SCRIPT: :CUSTOM_SCRIPT
          CUSTOM_SIGNAL: :CUSTOM_SIGNAL
          IMPORT: :IMPORT
          MANUAL: :MANUAL
          PROPERTY_CHANGE: :PROPERTY_CHANGE
          VISITED_URL: :VISITED_URL
          WEBHOOK: :WEBHOOK

          def self?.values: -> ::Array[HubSpotSDK::Models::Events::ExternalBehavioralEventTypeDefinition::tracking_type]
        end
      end
    end
  end
end
