module HubSpotSDK
  module Models
    module Events
      type external_behavioral_event_property_definition_patch =
        {
          description: String,
          label: String,
          options: ::Array[HubSpotSDK::OptionInput]
        }

      class ExternalBehavioralEventPropertyDefinitionPatch < HubSpotSDK::Internal::Type::BaseModel
        attr_reader description: String?

        def description=: (String) -> String

        attr_reader label: String?

        def label=: (String) -> String

        attr_reader options: ::Array[HubSpotSDK::OptionInput]?

        def options=: (
          ::Array[HubSpotSDK::OptionInput]
        ) -> ::Array[HubSpotSDK::OptionInput]

        def initialize: (
          ?description: String,
          ?label: String,
          ?options: ::Array[HubSpotSDK::OptionInput]
        ) -> void

        def to_hash: -> {
          description: String,
          label: String,
          options: ::Array[HubSpotSDK::OptionInput]
        }
      end
    end
  end
end
