module HubspotSDK
  module Models
    module Events
      type external_behavioral_event_type_definition_egg =
        {
          label: String,
          property_definitions: ::Array[HubspotSDK::Events::ExternalBehavioralEventPropertyCreate],
          description: String,
          name: String,
          primary_object: String
        }

      class ExternalBehavioralEventTypeDefinitionEgg < HubspotSDK::Internal::Type::BaseModel
        attr_accessor label: String

        attr_accessor property_definitions: ::Array[HubspotSDK::Events::ExternalBehavioralEventPropertyCreate]

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader primary_object: String?

        def primary_object=: (String) -> String

        def initialize: (
          label: String,
          property_definitions: ::Array[HubspotSDK::Events::ExternalBehavioralEventPropertyCreate],
          ?description: String,
          ?name: String,
          ?primary_object: String
        ) -> void

        def to_hash: -> {
          label: String,
          property_definitions: ::Array[HubspotSDK::Events::ExternalBehavioralEventPropertyCreate],
          description: String,
          name: String,
          primary_object: String
        }
      end
    end
  end
end
