module HubSpotSDK
  module Models
    module Events
      type indexed_time_point =
        {
          index_reference: HubSpotSDK::Models::Events::IndexedTimePoint::index_reference,
          time_type: HubSpotSDK::Models::Events::IndexedTimePoint::time_type,
          timezone_source: HubSpotSDK::Models::Events::IndexedTimePoint::timezone_source,
          zone_id: String,
          offset: HubSpotSDK::Events::IndexOffset,
          should_generate_refresh_time: bool
        }

      class IndexedTimePoint < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor index_reference: HubSpotSDK::Models::Events::IndexedTimePoint::index_reference

        attr_accessor time_type: HubSpotSDK::Models::Events::IndexedTimePoint::time_type

        attr_accessor timezone_source: HubSpotSDK::Models::Events::IndexedTimePoint::timezone_source

        attr_accessor zone_id: String

        attr_reader offset: HubSpotSDK::Events::IndexOffset?

        def offset=: (
          HubSpotSDK::Events::IndexOffset
        ) -> HubSpotSDK::Events::IndexOffset

        attr_reader should_generate_refresh_time: bool?

        def should_generate_refresh_time=: (bool) -> bool

        def initialize: (
          index_reference: HubSpotSDK::Models::Events::IndexedTimePoint::index_reference,
          time_type: HubSpotSDK::Models::Events::IndexedTimePoint::time_type,
          timezone_source: HubSpotSDK::Models::Events::IndexedTimePoint::timezone_source,
          zone_id: String,
          ?offset: HubSpotSDK::Events::IndexOffset,
          ?should_generate_refresh_time: bool
        ) -> void

        def to_hash: -> {
          index_reference: HubSpotSDK::Models::Events::IndexedTimePoint::index_reference,
          time_type: HubSpotSDK::Models::Events::IndexedTimePoint::time_type,
          timezone_source: HubSpotSDK::Models::Events::IndexedTimePoint::timezone_source,
          zone_id: String,
          offset: HubSpotSDK::Events::IndexOffset,
          should_generate_refresh_time: bool
        }

        type index_reference =
          HubSpotSDK::Events::NowReference
          | HubSpotSDK::Events::TodayReference
          | HubSpotSDK::Events::WeekReference
          | HubSpotSDK::Events::MonthReference
          | HubSpotSDK::Events::QuarterReference
          | HubSpotSDK::Events::FiscalQuarter
          | HubSpotSDK::Events::YearReference
          | HubSpotSDK::Events::FiscalYear

        module IndexReference
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Events::IndexedTimePoint::index_reference]
        end

        type time_type = :INDEXED

        module TimeType
          extend HubSpotSDK::Internal::Type::Enum

          INDEXED: :INDEXED

          def self?.values: -> ::Array[HubSpotSDK::Models::Events::IndexedTimePoint::time_type]
        end

        type timezone_source = :CUSTOM | :PORTAL | :USER

        module TimezoneSource
          extend HubSpotSDK::Internal::Type::Enum

          CUSTOM: :CUSTOM
          PORTAL: :PORTAL
          USER: :USER

          def self?.values: -> ::Array[HubSpotSDK::Models::Events::IndexedTimePoint::timezone_source]
        end
      end
    end
  end
end
