module HubSpotSDK
  module Models
    module Events
      type multi_string_property_operation =
        {
          coalescing_refine_by: HubSpotSDK::Models::Events::MultiStringPropertyOperation::coalescing_refine_by,
          include_objects_with_no_value_set: bool,
          operation_type: String,
          operator: HubSpotSDK::Models::Events::MultiStringPropertyOperation::operator,
          operator_name: String,
          property_type: HubSpotSDK::Models::Events::MultiStringPropertyOperation::property_type,
          values: ::Array[String],
          default_value: String,
          pruning_refine_by: HubSpotSDK::Models::Events::MultiStringPropertyOperation::pruning_refine_by,
          render_spec: String
        }

      class MultiStringPropertyOperation < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor coalescing_refine_by: HubSpotSDK::Models::Events::MultiStringPropertyOperation::coalescing_refine_by

        attr_accessor include_objects_with_no_value_set: bool

        attr_accessor operation_type: String

        attr_accessor operator: HubSpotSDK::Models::Events::MultiStringPropertyOperation::operator

        attr_accessor operator_name: String

        attr_accessor property_type: HubSpotSDK::Models::Events::MultiStringPropertyOperation::property_type

        attr_accessor values: ::Array[String]

        attr_reader default_value: String?

        def default_value=: (String) -> String

        attr_reader pruning_refine_by: HubSpotSDK::Models::Events::MultiStringPropertyOperation::pruning_refine_by?

        def pruning_refine_by=: (
          HubSpotSDK::Models::Events::MultiStringPropertyOperation::pruning_refine_by
        ) -> HubSpotSDK::Models::Events::MultiStringPropertyOperation::pruning_refine_by

        attr_reader render_spec: String?

        def render_spec=: (String) -> String

        def initialize: (
          coalescing_refine_by: HubSpotSDK::Models::Events::MultiStringPropertyOperation::coalescing_refine_by,
          include_objects_with_no_value_set: bool,
          operation_type: String,
          operator: HubSpotSDK::Models::Events::MultiStringPropertyOperation::operator,
          operator_name: String,
          property_type: HubSpotSDK::Models::Events::MultiStringPropertyOperation::property_type,
          values: ::Array[String],
          ?default_value: String,
          ?pruning_refine_by: HubSpotSDK::Models::Events::MultiStringPropertyOperation::pruning_refine_by,
          ?render_spec: String
        ) -> void

        def to_hash: -> {
          coalescing_refine_by: HubSpotSDK::Models::Events::MultiStringPropertyOperation::coalescing_refine_by,
          include_objects_with_no_value_set: bool,
          operation_type: String,
          operator: HubSpotSDK::Models::Events::MultiStringPropertyOperation::operator,
          operator_name: String,
          property_type: HubSpotSDK::Models::Events::MultiStringPropertyOperation::property_type,
          values: ::Array[String],
          default_value: String,
          pruning_refine_by: HubSpotSDK::Models::Events::MultiStringPropertyOperation::pruning_refine_by,
          render_spec: String
        }

        type coalescing_refine_by =
          HubSpotSDK::Events::NumOccurrencesRefineBy
          | HubSpotSDK::Events::SetOccurrencesRefineBy

        module CoalescingRefineBy
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Events::MultiStringPropertyOperation::coalescing_refine_by]
        end

        type operator =
          :CONTAINS
          | :CONTAINS_EXACTLY
          | :DOES_NOT_CONTAIN
          | :DOES_NOT_CONTAIN_EXACTLY
          | :ENDS_WITH
          | :IS_EQUAL_TO
          | :IS_NOT_EQUAL_TO
          | :STARTS_WITH

        module Operator
          extend HubSpotSDK::Internal::Type::Enum

          CONTAINS: :CONTAINS
          CONTAINS_EXACTLY: :CONTAINS_EXACTLY
          DOES_NOT_CONTAIN: :DOES_NOT_CONTAIN
          DOES_NOT_CONTAIN_EXACTLY: :DOES_NOT_CONTAIN_EXACTLY
          ENDS_WITH: :ENDS_WITH
          IS_EQUAL_TO: :IS_EQUAL_TO
          IS_NOT_EQUAL_TO: :IS_NOT_EQUAL_TO
          STARTS_WITH: :STARTS_WITH

          def self?.values: -> ::Array[HubSpotSDK::Models::Events::MultiStringPropertyOperation::operator]
        end

        type property_type = :multistring

        module PropertyType
          extend HubSpotSDK::Internal::Type::Enum

          MULTISTRING: :multistring

          def self?.values: -> ::Array[HubSpotSDK::Models::Events::MultiStringPropertyOperation::property_type]
        end

        type pruning_refine_by =
          HubSpotSDK::Events::RelativeComparativeTimestampRefineBy
          | HubSpotSDK::Events::RelativeRangedTimestampRefineBy
          | HubSpotSDK::Events::AbsoluteComparativeTimestampRefineBy
          | HubSpotSDK::Events::AbsoluteRangedTimestampRefineBy
          | HubSpotSDK::Events::AllHistoryRefineBy
          | HubSpotSDK::Events::TimePointOperation
          | HubSpotSDK::Events::RangedTimeOperation

        module PruningRefineBy
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Events::MultiStringPropertyOperation::pruning_refine_by]
        end
      end
    end
  end
end
