module HubspotSDK
  module Models
    module Events
      type number_property_operation =
        {
          include_objects_with_no_value_set: bool,
          operation_type: String,
          operator: HubspotSDK::Models::Events::NumberPropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::NumberPropertyOperation::property_type,
          value: Float,
          default_value: String
        }

      class NumberPropertyOperation < HubspotSDK::Internal::Type::BaseModel
        attr_accessor include_objects_with_no_value_set: bool

        attr_accessor operation_type: String

        attr_accessor operator: HubspotSDK::Models::Events::NumberPropertyOperation::operator

        attr_accessor operator_name: String

        attr_accessor property_type: HubspotSDK::Models::Events::NumberPropertyOperation::property_type

        attr_accessor value: Float

        attr_reader default_value: String?

        def default_value=: (String) -> String

        def initialize: (
          include_objects_with_no_value_set: bool,
          operation_type: String,
          operator: HubspotSDK::Models::Events::NumberPropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::NumberPropertyOperation::property_type,
          value: Float,
          ?default_value: String
        ) -> void

        def to_hash: -> {
          include_objects_with_no_value_set: bool,
          operation_type: String,
          operator: HubspotSDK::Models::Events::NumberPropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::NumberPropertyOperation::property_type,
          value: Float,
          default_value: String
        }

        type operator =
          :HAS_EVER_BEEN_EQUAL_TO
          | :HAS_NEVER_BEEN_EQUAL_TO
          | :IS_EQUAL_TO
          | :IS_GREATER_THAN
          | :IS_GREATER_THAN_OR_EQUAL_TO
          | :IS_LESS_THAN
          | :IS_LESS_THAN_OR_EQUAL_TO
          | :IS_NOT_EQUAL_TO

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          HAS_EVER_BEEN_EQUAL_TO: :HAS_EVER_BEEN_EQUAL_TO
          HAS_NEVER_BEEN_EQUAL_TO: :HAS_NEVER_BEEN_EQUAL_TO
          IS_EQUAL_TO: :IS_EQUAL_TO
          IS_GREATER_THAN: :IS_GREATER_THAN
          IS_GREATER_THAN_OR_EQUAL_TO: :IS_GREATER_THAN_OR_EQUAL_TO
          IS_LESS_THAN: :IS_LESS_THAN
          IS_LESS_THAN_OR_EQUAL_TO: :IS_LESS_THAN_OR_EQUAL_TO
          IS_NOT_EQUAL_TO: :IS_NOT_EQUAL_TO

          def self?.values: -> ::Array[HubspotSDK::Models::Events::NumberPropertyOperation::operator]
        end

        type property_type = :number

        module PropertyType
          extend HubspotSDK::Internal::Type::Enum

          NUMBER: :number

          def self?.values: -> ::Array[HubspotSDK::Models::Events::NumberPropertyOperation::property_type]
        end
      end
    end
  end
end
