module HubSpotSDK
  module Models
    module Events
      type occurrence_list_params =
        {
          id: ::Array[String],
          after: String,
          before: String,
          event_type: String,
          limit: Integer,
          object_id_: Integer,
          object_property: HubSpotSDK::Events::OccurrenceListParams::ObjectProperty,
          object_type: String,
          occurred_after: Time,
          occurred_before: Time,
          properties: ::Array[String],
          property: HubSpotSDK::Events::OccurrenceListParams::Property,
          sort: ::Array[String]
        }
        & HubSpotSDK::Internal::Type::request_parameters

      class OccurrenceListParams < HubSpotSDK::Internal::Type::BaseModel
        extend HubSpotSDK::Internal::Type::RequestParameters::Converter
        include HubSpotSDK::Internal::Type::RequestParameters

        attr_reader id: ::Array[String]?

        def id=: (::Array[String]) -> ::Array[String]

        attr_reader after: String?

        def after=: (String) -> String

        attr_reader before: String?

        def before=: (String) -> String

        attr_reader event_type: String?

        def event_type=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader object_id_: Integer?

        def object_id_=: (Integer) -> Integer

        attr_reader object_property: HubSpotSDK::Events::OccurrenceListParams::ObjectProperty?

        def object_property=: (
          HubSpotSDK::Events::OccurrenceListParams::ObjectProperty
        ) -> HubSpotSDK::Events::OccurrenceListParams::ObjectProperty

        attr_reader object_type: String?

        def object_type=: (String) -> String

        attr_reader occurred_after: Time?

        def occurred_after=: (Time) -> Time

        attr_reader occurred_before: Time?

        def occurred_before=: (Time) -> Time

        attr_reader properties: ::Array[String]?

        def properties=: (::Array[String]) -> ::Array[String]

        attr_reader property: HubSpotSDK::Events::OccurrenceListParams::Property?

        def property=: (
          HubSpotSDK::Events::OccurrenceListParams::Property
        ) -> HubSpotSDK::Events::OccurrenceListParams::Property

        attr_reader sort: ::Array[String]?

        def sort=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?id: ::Array[String],
          ?after: String,
          ?before: String,
          ?event_type: String,
          ?limit: Integer,
          ?object_id_: Integer,
          ?object_property: HubSpotSDK::Events::OccurrenceListParams::ObjectProperty,
          ?object_type: String,
          ?occurred_after: Time,
          ?occurred_before: Time,
          ?properties: ::Array[String],
          ?property: HubSpotSDK::Events::OccurrenceListParams::Property,
          ?sort: ::Array[String],
          ?request_options: HubSpotSDK::request_opts
        ) -> void

        def to_hash: -> {
          id: ::Array[String],
          after: String,
          before: String,
          event_type: String,
          limit: Integer,
          object_id_: Integer,
          object_property: HubSpotSDK::Events::OccurrenceListParams::ObjectProperty,
          object_type: String,
          occurred_after: Time,
          occurred_before: Time,
          properties: ::Array[String],
          property: HubSpotSDK::Events::OccurrenceListParams::Property,
          sort: ::Array[String],
          request_options: HubSpotSDK::RequestOptions
        }

        type object_property = { propname: top }

        class ObjectProperty < HubSpotSDK::Internal::Type::BaseModel
          attr_reader propname: top?

          def propname=: (top) -> top

          def initialize: (?propname: top) -> void

          def to_hash: -> { propname: top }
        end

        type property = { propname: top }

        class Property < HubSpotSDK::Internal::Type::BaseModel
          attr_reader propname: top?

          def propname=: (top) -> top

          def initialize: (?propname: top) -> void

          def to_hash: -> { propname: top }
        end
      end
    end
  end
end
