module HubSpotSDK
  module Models
    module Events
      type property_referenced_time =
        {
          property: String,
          reference_type: HubSpotSDK::Models::Events::PropertyReferencedTime::reference_type,
          time_type: HubSpotSDK::Models::Events::PropertyReferencedTime::time_type,
          timezone_source: HubSpotSDK::Models::Events::PropertyReferencedTime::timezone_source,
          zone_id: String
        }

      class PropertyReferencedTime < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor property: String

        attr_accessor reference_type: HubSpotSDK::Models::Events::PropertyReferencedTime::reference_type

        attr_accessor time_type: HubSpotSDK::Models::Events::PropertyReferencedTime::time_type

        attr_accessor timezone_source: HubSpotSDK::Models::Events::PropertyReferencedTime::timezone_source

        attr_accessor zone_id: String

        def initialize: (
          property: String,
          reference_type: HubSpotSDK::Models::Events::PropertyReferencedTime::reference_type,
          time_type: HubSpotSDK::Models::Events::PropertyReferencedTime::time_type,
          timezone_source: HubSpotSDK::Models::Events::PropertyReferencedTime::timezone_source,
          zone_id: String
        ) -> void

        def to_hash: -> {
          property: String,
          reference_type: HubSpotSDK::Models::Events::PropertyReferencedTime::reference_type,
          time_type: HubSpotSDK::Models::Events::PropertyReferencedTime::time_type,
          timezone_source: HubSpotSDK::Models::Events::PropertyReferencedTime::timezone_source,
          zone_id: String
        }

        type reference_type =
          :ANNIVERSARY
          | :ANNIVERSARY_WITH_ZONE_SAME_LOCAL_CONVERSION
          | :UPDATED_AT
          | :VALUE
          | :VALUE_WITH_ZONE_SAME_LOCAL_CONVERSION

        module ReferenceType
          extend HubSpotSDK::Internal::Type::Enum

          ANNIVERSARY: :ANNIVERSARY
          ANNIVERSARY_WITH_ZONE_SAME_LOCAL_CONVERSION: :ANNIVERSARY_WITH_ZONE_SAME_LOCAL_CONVERSION
          UPDATED_AT: :UPDATED_AT
          VALUE: :VALUE
          VALUE_WITH_ZONE_SAME_LOCAL_CONVERSION: :VALUE_WITH_ZONE_SAME_LOCAL_CONVERSION

          def self?.values: -> ::Array[HubSpotSDK::Models::Events::PropertyReferencedTime::reference_type]
        end

        type time_type = :PROPERTY_REFERENCED

        module TimeType
          extend HubSpotSDK::Internal::Type::Enum

          PROPERTY_REFERENCED: :PROPERTY_REFERENCED

          def self?.values: -> ::Array[HubSpotSDK::Models::Events::PropertyReferencedTime::time_type]
        end

        type timezone_source = :CUSTOM | :PORTAL | :USER

        module TimezoneSource
          extend HubSpotSDK::Internal::Type::Enum

          CUSTOM: :CUSTOM
          PORTAL: :PORTAL
          USER: :USER

          def self?.values: -> ::Array[HubSpotSDK::Models::Events::PropertyReferencedTime::timezone_source]
        end
      end
    end
  end
end
