module HubspotSDK
  module Models
    module Events
      type property_filter =
        {
          filter_type: HubspotSDK::Models::Events::PropertyFilter::filter_type,
          operation: HubspotSDK::Models::Events::PropertyFilter::operation,
          property: String,
          context: HubspotSDK::Events::PropertyFilterContext,
          filter_insights_id: Integer,
          framework_filter_id: Integer
        }

      class PropertyFilter < HubspotSDK::Internal::Type::BaseModel
        attr_accessor filter_type: HubspotSDK::Models::Events::PropertyFilter::filter_type

        attr_accessor operation: HubspotSDK::Models::Events::PropertyFilter::operation

        attr_accessor property: String

        attr_reader context: HubspotSDK::Events::PropertyFilterContext?

        def context=: (
          HubspotSDK::Events::PropertyFilterContext
        ) -> HubspotSDK::Events::PropertyFilterContext

        attr_reader filter_insights_id: Integer?

        def filter_insights_id=: (Integer) -> Integer

        attr_reader framework_filter_id: Integer?

        def framework_filter_id=: (Integer) -> Integer

        def initialize: (
          filter_type: HubspotSDK::Models::Events::PropertyFilter::filter_type,
          operation: HubspotSDK::Models::Events::PropertyFilter::operation,
          property: String,
          ?context: HubspotSDK::Events::PropertyFilterContext,
          ?filter_insights_id: Integer,
          ?framework_filter_id: Integer
        ) -> void

        def to_hash: -> {
          filter_type: HubspotSDK::Models::Events::PropertyFilter::filter_type,
          operation: HubspotSDK::Models::Events::PropertyFilter::operation,
          property: String,
          context: HubspotSDK::Events::PropertyFilterContext,
          filter_insights_id: Integer,
          framework_filter_id: Integer
        }

        type filter_type = :PROPERTY

        module FilterType
          extend HubspotSDK::Internal::Type::Enum

          PROPERTY: :PROPERTY

          def self?.values: -> ::Array[HubspotSDK::Models::Events::PropertyFilter::filter_type]
        end

        type operation =
          HubspotSDK::Events::BoolPropertyOperation
          | HubspotSDK::Events::NumberPropertyOperation
          | HubspotSDK::Events::StringPropertyOperation
          | HubspotSDK::Events::DateTimePropertyOperation
          | HubspotSDK::Events::RangedDatePropertyOperation
          | HubspotSDK::Events::ComparativeDatePropertyOperation
          | HubspotSDK::Events::ComparativeBoolPropertyOperation
          | HubspotSDK::Events::ComparativeNumberPropertyOperation
          | HubspotSDK::Events::ComparativeStringPropertyOperation
          | HubspotSDK::Events::ComparativePropertyUpdatedOperation
          | HubspotSDK::Events::RollingDateRangePropertyOperation
          | HubspotSDK::Events::RollingPropertyUpdatedOperation
          | HubspotSDK::Events::EnumerationPropertyOperation
          | HubspotSDK::Events::AllPropertyTypesOperation
          | HubspotSDK::Events::RangedNumberPropertyOperation
          | HubspotSDK::Events::MultiStringPropertyOperation
          | HubspotSDK::Events::DatePropertyOperation
          | HubspotSDK::Events::CalendarDatePropertyOperation
          | HubspotSDK::Events::TimePointOperation
          | HubspotSDK::Events::RangedTimeOperation
          | HubspotSDK::Events::RegexPropertyOperation

        module Operation
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Events::PropertyFilter::operation]
        end
      end
    end
  end
end
