module HubSpotSDK
  module Models
    module Events
      type property_filter =
        {
          filter_type: HubSpotSDK::Models::Events::PropertyFilter::filter_type,
          operation: HubSpotSDK::Models::Events::PropertyFilter::operation,
          property: String,
          context: HubSpotSDK::Events::PropertyFilterContext,
          filter_insights_id: Integer,
          framework_filter_id: Integer
        }

      class PropertyFilter < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor filter_type: HubSpotSDK::Models::Events::PropertyFilter::filter_type

        attr_accessor operation: HubSpotSDK::Models::Events::PropertyFilter::operation

        attr_accessor property: String

        attr_reader context: HubSpotSDK::Events::PropertyFilterContext?

        def context=: (
          HubSpotSDK::Events::PropertyFilterContext
        ) -> HubSpotSDK::Events::PropertyFilterContext

        attr_reader filter_insights_id: Integer?

        def filter_insights_id=: (Integer) -> Integer

        attr_reader framework_filter_id: Integer?

        def framework_filter_id=: (Integer) -> Integer

        def initialize: (
          filter_type: HubSpotSDK::Models::Events::PropertyFilter::filter_type,
          operation: HubSpotSDK::Models::Events::PropertyFilter::operation,
          property: String,
          ?context: HubSpotSDK::Events::PropertyFilterContext,
          ?filter_insights_id: Integer,
          ?framework_filter_id: Integer
        ) -> void

        def to_hash: -> {
          filter_type: HubSpotSDK::Models::Events::PropertyFilter::filter_type,
          operation: HubSpotSDK::Models::Events::PropertyFilter::operation,
          property: String,
          context: HubSpotSDK::Events::PropertyFilterContext,
          filter_insights_id: Integer,
          framework_filter_id: Integer
        }

        type filter_type = :PROPERTY

        module FilterType
          extend HubSpotSDK::Internal::Type::Enum

          PROPERTY: :PROPERTY

          def self?.values: -> ::Array[HubSpotSDK::Models::Events::PropertyFilter::filter_type]
        end

        type operation =
          HubSpotSDK::Events::BoolPropertyOperation
          | HubSpotSDK::Events::NumberPropertyOperation
          | HubSpotSDK::Events::StringPropertyOperation
          | HubSpotSDK::Events::DateTimePropertyOperation
          | HubSpotSDK::Events::RangedDatePropertyOperation
          | HubSpotSDK::Events::ComparativeDatePropertyOperation
          | HubSpotSDK::Events::ComparativeBoolPropertyOperation
          | HubSpotSDK::Events::ComparativeNumberPropertyOperation
          | HubSpotSDK::Events::ComparativeStringPropertyOperation
          | HubSpotSDK::Events::ComparativePropertyUpdatedOperation
          | HubSpotSDK::Events::RollingDateRangePropertyOperation
          | HubSpotSDK::Events::RollingPropertyUpdatedOperation
          | HubSpotSDK::Events::EnumerationPropertyOperation
          | HubSpotSDK::Events::AllPropertyTypesOperation
          | HubSpotSDK::Events::RangedNumberPropertyOperation
          | HubSpotSDK::Events::MultiStringPropertyOperation
          | HubSpotSDK::Events::DatePropertyOperation
          | HubSpotSDK::Events::CalendarDatePropertyOperation
          | HubSpotSDK::Events::TimePointOperation
          | HubSpotSDK::Events::RangedTimeOperation
          | HubSpotSDK::Events::RegexPropertyOperation

        module Operation
          extend HubSpotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubSpotSDK::Models::Events::PropertyFilter::operation]
        end
      end
    end
  end
end
