module HubspotSDK
  module Models
    module Events
      type ranged_date_property_operation =
        {
          include_objects_with_no_value_set: bool,
          lower_bound_timestamp: Integer,
          operation_type: String,
          operator: HubspotSDK::Models::Events::RangedDatePropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::RangedDatePropertyOperation::property_type,
          requires_time_zone_conversion: bool,
          upper_bound_timestamp: Integer,
          default_value: String
        }

      class RangedDatePropertyOperation < HubspotSDK::Internal::Type::BaseModel
        attr_accessor include_objects_with_no_value_set: bool

        attr_accessor lower_bound_timestamp: Integer

        attr_accessor operation_type: String

        attr_accessor operator: HubspotSDK::Models::Events::RangedDatePropertyOperation::operator

        attr_accessor operator_name: String

        attr_accessor property_type: HubspotSDK::Models::Events::RangedDatePropertyOperation::property_type

        attr_accessor requires_time_zone_conversion: bool

        attr_accessor upper_bound_timestamp: Integer

        attr_reader default_value: String?

        def default_value=: (String) -> String

        def initialize: (
          include_objects_with_no_value_set: bool,
          lower_bound_timestamp: Integer,
          operation_type: String,
          operator: HubspotSDK::Models::Events::RangedDatePropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::RangedDatePropertyOperation::property_type,
          requires_time_zone_conversion: bool,
          upper_bound_timestamp: Integer,
          ?default_value: String
        ) -> void

        def to_hash: -> {
          include_objects_with_no_value_set: bool,
          lower_bound_timestamp: Integer,
          operation_type: String,
          operator: HubspotSDK::Models::Events::RangedDatePropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::RangedDatePropertyOperation::property_type,
          requires_time_zone_conversion: bool,
          upper_bound_timestamp: Integer,
          default_value: String
        }

        type operator = :IS_BETWEEN | :IS_NOT_BETWEEN

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          IS_BETWEEN: :IS_BETWEEN
          IS_NOT_BETWEEN: :IS_NOT_BETWEEN

          def self?.values: -> ::Array[HubspotSDK::Models::Events::RangedDatePropertyOperation::operator]
        end

        type property_type = :"datetime-ranged"

        module PropertyType
          extend HubspotSDK::Internal::Type::Enum

          DATETIME_RANGED: :"datetime-ranged"

          def self?.values: -> ::Array[HubspotSDK::Models::Events::RangedDatePropertyOperation::property_type]
        end
      end
    end
  end
end
