module HubspotSDK
  module Models
    module Events
      type ranged_number_property_operation =
        {
          include_objects_with_no_value_set: bool,
          lower_bound: Float,
          operation_type: String,
          operator: HubspotSDK::Models::Events::RangedNumberPropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::RangedNumberPropertyOperation::property_type,
          upper_bound: Float,
          default_value: String,
          render_spec: String
        }

      class RangedNumberPropertyOperation < HubspotSDK::Internal::Type::BaseModel
        attr_accessor include_objects_with_no_value_set: bool

        attr_accessor lower_bound: Float

        attr_accessor operation_type: String

        attr_accessor operator: HubspotSDK::Models::Events::RangedNumberPropertyOperation::operator

        attr_accessor operator_name: String

        attr_accessor property_type: HubspotSDK::Models::Events::RangedNumberPropertyOperation::property_type

        attr_accessor upper_bound: Float

        attr_reader default_value: String?

        def default_value=: (String) -> String

        attr_reader render_spec: String?

        def render_spec=: (String) -> String

        def initialize: (
          include_objects_with_no_value_set: bool,
          lower_bound: Float,
          operation_type: String,
          operator: HubspotSDK::Models::Events::RangedNumberPropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::RangedNumberPropertyOperation::property_type,
          upper_bound: Float,
          ?default_value: String,
          ?render_spec: String
        ) -> void

        def to_hash: -> {
          include_objects_with_no_value_set: bool,
          lower_bound: Float,
          operation_type: String,
          operator: HubspotSDK::Models::Events::RangedNumberPropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::RangedNumberPropertyOperation::property_type,
          upper_bound: Float,
          default_value: String,
          render_spec: String
        }

        type operator = :IS_BETWEEN | :IS_NOT_BETWEEN

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          IS_BETWEEN: :IS_BETWEEN
          IS_NOT_BETWEEN: :IS_NOT_BETWEEN

          def self?.values: -> ::Array[HubspotSDK::Models::Events::RangedNumberPropertyOperation::operator]
        end

        type property_type = :"number-ranged"

        module PropertyType
          extend HubspotSDK::Internal::Type::Enum

          NUMBER_RANGED: :"number-ranged"

          def self?.values: -> ::Array[HubspotSDK::Models::Events::RangedNumberPropertyOperation::property_type]
        end
      end
    end
  end
end
