module HubSpotSDK
  module Models
    module Events
      type relative_ranged_timestamp_refine_by =
        {
          lower_bound_offset: HubSpotSDK::Events::TimeOffset,
          range_type: HubSpotSDK::Models::Events::RelativeRangedTimestampRefineBy::range_type,
          type: HubSpotSDK::Models::Events::RelativeRangedTimestampRefineBy::type_,
          upper_bound_offset: HubSpotSDK::Events::TimeOffset
        }

      class RelativeRangedTimestampRefineBy < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor lower_bound_offset: HubSpotSDK::Events::TimeOffset

        attr_accessor range_type: HubSpotSDK::Models::Events::RelativeRangedTimestampRefineBy::range_type

        attr_accessor type: HubSpotSDK::Models::Events::RelativeRangedTimestampRefineBy::type_

        attr_accessor upper_bound_offset: HubSpotSDK::Events::TimeOffset

        def initialize: (
          lower_bound_offset: HubSpotSDK::Events::TimeOffset,
          range_type: HubSpotSDK::Models::Events::RelativeRangedTimestampRefineBy::range_type,
          type: HubSpotSDK::Models::Events::RelativeRangedTimestampRefineBy::type_,
          upper_bound_offset: HubSpotSDK::Events::TimeOffset
        ) -> void

        def to_hash: -> {
          lower_bound_offset: HubSpotSDK::Events::TimeOffset,
          range_type: HubSpotSDK::Models::Events::RelativeRangedTimestampRefineBy::range_type,
          type: HubSpotSDK::Models::Events::RelativeRangedTimestampRefineBy::type_,
          upper_bound_offset: HubSpotSDK::Events::TimeOffset
        }

        type range_type = :BETWEEN | :NOT_BETWEEN

        module RangeType
          extend HubSpotSDK::Internal::Type::Enum

          BETWEEN: :BETWEEN
          NOT_BETWEEN: :NOT_BETWEEN

          def self?.values: -> ::Array[HubSpotSDK::Models::Events::RelativeRangedTimestampRefineBy::range_type]
        end

        type type_ = :RelativeRangedTimestampRefineBy

        module Type
          extend HubSpotSDK::Internal::Type::Enum

          RELATIVE_RANGED_TIMESTAMP_REFINE_BY: :RelativeRangedTimestampRefineBy

          def self?.values: -> ::Array[HubSpotSDK::Models::Events::RelativeRangedTimestampRefineBy::type_]
        end
      end
    end
  end
end
