module HubSpotSDK
  module Models
    module Events
      type relative_comparative_timestamp_refine_by =
        {
          comparison: HubSpotSDK::Models::Events::RelativeComparativeTimestampRefineBy::comparison,
          time_offset: HubSpotSDK::Events::TimeOffset,
          type: HubSpotSDK::Models::Events::RelativeComparativeTimestampRefineBy::type_
        }

      class RelativeComparativeTimestampRefineBy < HubSpotSDK::Internal::Type::BaseModel
        attr_accessor comparison: HubSpotSDK::Models::Events::RelativeComparativeTimestampRefineBy::comparison

        attr_accessor time_offset: HubSpotSDK::Events::TimeOffset

        attr_accessor type: HubSpotSDK::Models::Events::RelativeComparativeTimestampRefineBy::type_

        def initialize: (
          comparison: HubSpotSDK::Models::Events::RelativeComparativeTimestampRefineBy::comparison,
          time_offset: HubSpotSDK::Events::TimeOffset,
          type: HubSpotSDK::Models::Events::RelativeComparativeTimestampRefineBy::type_
        ) -> void

        def to_hash: -> {
          comparison: HubSpotSDK::Models::Events::RelativeComparativeTimestampRefineBy::comparison,
          time_offset: HubSpotSDK::Events::TimeOffset,
          type: HubSpotSDK::Models::Events::RelativeComparativeTimestampRefineBy::type_
        }

        type comparison = :AFTER | :BEFORE

        module Comparison
          extend HubSpotSDK::Internal::Type::Enum

          AFTER: :AFTER
          BEFORE: :BEFORE

          def self?.values: -> ::Array[HubSpotSDK::Models::Events::RelativeComparativeTimestampRefineBy::comparison]
        end

        type type_ = :RelativeComparativeTimestampRefineBy

        module Type
          extend HubSpotSDK::Internal::Type::Enum

          RELATIVE_COMPARATIVE_TIMESTAMP_REFINE_BY: :RelativeComparativeTimestampRefineBy

          def self?.values: -> ::Array[HubSpotSDK::Models::Events::RelativeComparativeTimestampRefineBy::type_]
        end
      end
    end
  end
end
