module HubspotSDK
  module Models
    module Events
      type relative_comparative_timestamp_refine_by =
        {
          comparison: HubspotSDK::Models::Events::RelativeComparativeTimestampRefineBy::comparison,
          time_offset: HubspotSDK::Events::TimeOffset,
          type: HubspotSDK::Models::Events::RelativeComparativeTimestampRefineBy::type_
        }

      class RelativeComparativeTimestampRefineBy < HubspotSDK::Internal::Type::BaseModel
        attr_accessor comparison: HubspotSDK::Models::Events::RelativeComparativeTimestampRefineBy::comparison

        attr_accessor time_offset: HubspotSDK::Events::TimeOffset

        attr_accessor type: HubspotSDK::Models::Events::RelativeComparativeTimestampRefineBy::type_

        def initialize: (
          comparison: HubspotSDK::Models::Events::RelativeComparativeTimestampRefineBy::comparison,
          time_offset: HubspotSDK::Events::TimeOffset,
          type: HubspotSDK::Models::Events::RelativeComparativeTimestampRefineBy::type_
        ) -> void

        def to_hash: -> {
          comparison: HubspotSDK::Models::Events::RelativeComparativeTimestampRefineBy::comparison,
          time_offset: HubspotSDK::Events::TimeOffset,
          type: HubspotSDK::Models::Events::RelativeComparativeTimestampRefineBy::type_
        }

        type comparison = :BEFORE | :AFTER

        module Comparison
          extend HubspotSDK::Internal::Type::Enum

          BEFORE: :BEFORE
          AFTER: :AFTER

          def self?.values: -> ::Array[HubspotSDK::Models::Events::RelativeComparativeTimestampRefineBy::comparison]
        end

        type type_ = :RelativeComparativeTimestampRefineBy

        module Type
          extend HubspotSDK::Internal::Type::Enum

          RELATIVE_COMPARATIVE_TIMESTAMP_REFINE_BY: :RelativeComparativeTimestampRefineBy

          def self?.values: -> ::Array[HubspotSDK::Models::Events::RelativeComparativeTimestampRefineBy::type_]
        end
      end
    end
  end
end
