module HubspotSDK
  module Models
    module Events
      type rolling_property_updated_operation =
        {
          include_objects_with_no_value_set: bool,
          number_of_days: Integer,
          operation_type: String,
          operator: HubspotSDK::Models::Events::RollingPropertyUpdatedOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::RollingPropertyUpdatedOperation::property_type,
          default_value: String
        }

      class RollingPropertyUpdatedOperation < HubspotSDK::Internal::Type::BaseModel
        attr_accessor include_objects_with_no_value_set: bool

        attr_accessor number_of_days: Integer

        attr_accessor operation_type: String

        attr_accessor operator: HubspotSDK::Models::Events::RollingPropertyUpdatedOperation::operator

        attr_accessor operator_name: String

        attr_accessor property_type: HubspotSDK::Models::Events::RollingPropertyUpdatedOperation::property_type

        attr_reader default_value: String?

        def default_value=: (String) -> String

        def initialize: (
          include_objects_with_no_value_set: bool,
          number_of_days: Integer,
          operation_type: String,
          operator: HubspotSDK::Models::Events::RollingPropertyUpdatedOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::RollingPropertyUpdatedOperation::property_type,
          ?default_value: String
        ) -> void

        def to_hash: -> {
          include_objects_with_no_value_set: bool,
          number_of_days: Integer,
          operation_type: String,
          operator: HubspotSDK::Models::Events::RollingPropertyUpdatedOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::RollingPropertyUpdatedOperation::property_type,
          default_value: String
        }

        type operator = :NOT_UPDATED_IN_LAST_X_DAYS | :UPDATED_IN_LAST_X_DAYS

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          NOT_UPDATED_IN_LAST_X_DAYS: :NOT_UPDATED_IN_LAST_X_DAYS
          UPDATED_IN_LAST_X_DAYS: :UPDATED_IN_LAST_X_DAYS

          def self?.values: -> ::Array[HubspotSDK::Models::Events::RollingPropertyUpdatedOperation::operator]
        end

        type property_type = :"rolling-property-updated"

        module PropertyType
          extend HubspotSDK::Internal::Type::Enum

          ROLLING_PROPERTY_UPDATED: :"rolling-property-updated"

          def self?.values: -> ::Array[HubspotSDK::Models::Events::RollingPropertyUpdatedOperation::property_type]
        end
      end
    end
  end
end
