module HubspotSDK
  module Models
    module Events
      type rolling_date_range_property_operation =
        {
          include_objects_with_no_value_set: bool,
          number_of_days: Integer,
          operation_type: String,
          operator: HubspotSDK::Models::Events::RollingDateRangePropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::RollingDateRangePropertyOperation::property_type,
          requires_time_zone_conversion: bool,
          default_value: String
        }

      class RollingDateRangePropertyOperation < HubspotSDK::Internal::Type::BaseModel
        attr_accessor include_objects_with_no_value_set: bool

        attr_accessor number_of_days: Integer

        attr_accessor operation_type: String

        attr_accessor operator: HubspotSDK::Models::Events::RollingDateRangePropertyOperation::operator

        attr_accessor operator_name: String

        attr_accessor property_type: HubspotSDK::Models::Events::RollingDateRangePropertyOperation::property_type

        attr_accessor requires_time_zone_conversion: bool

        attr_reader default_value: String?

        def default_value=: (String) -> String

        def initialize: (
          include_objects_with_no_value_set: bool,
          number_of_days: Integer,
          operation_type: String,
          operator: HubspotSDK::Models::Events::RollingDateRangePropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::RollingDateRangePropertyOperation::property_type,
          requires_time_zone_conversion: bool,
          ?default_value: String
        ) -> void

        def to_hash: -> {
          include_objects_with_no_value_set: bool,
          number_of_days: Integer,
          operation_type: String,
          operator: HubspotSDK::Models::Events::RollingDateRangePropertyOperation::operator,
          operator_name: String,
          property_type: HubspotSDK::Models::Events::RollingDateRangePropertyOperation::property_type,
          requires_time_zone_conversion: bool,
          default_value: String
        }

        type operator =
          :IS_LESS_THAN_X_DAYS_AGO
          | :IS_MORE_THAN_X_DAYS_AGO
          | :IS_LESS_THAN_X_DAYS_FROM_NOW
          | :IS_MORE_THAN_X_DAYS_FROM_NOW

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          IS_LESS_THAN_X_DAYS_AGO: :IS_LESS_THAN_X_DAYS_AGO
          IS_MORE_THAN_X_DAYS_AGO: :IS_MORE_THAN_X_DAYS_AGO
          IS_LESS_THAN_X_DAYS_FROM_NOW: :IS_LESS_THAN_X_DAYS_FROM_NOW
          IS_MORE_THAN_X_DAYS_FROM_NOW: :IS_MORE_THAN_X_DAYS_FROM_NOW

          def self?.values: -> ::Array[HubspotSDK::Models::Events::RollingDateRangePropertyOperation::operator]
        end

        type property_type = :"datetime-rolling"

        module PropertyType
          extend HubspotSDK::Internal::Type::Enum

          DATETIME_ROLLING: :"datetime-rolling"

          def self?.values: -> ::Array[HubspotSDK::Models::Events::RollingDateRangePropertyOperation::property_type]
        end
      end
    end
  end
end
