module HubspotSDK
  module Models
    module Events
      type set_occurrences_refine_by =
        {
          set_type: HubspotSDK::Models::Events::SetOccurrencesRefineBy::set_type,
          type: HubspotSDK::Models::Events::SetOccurrencesRefineBy::type_
        }

      class SetOccurrencesRefineBy < HubspotSDK::Internal::Type::BaseModel
        attr_accessor set_type: HubspotSDK::Models::Events::SetOccurrencesRefineBy::set_type

        attr_accessor type: HubspotSDK::Models::Events::SetOccurrencesRefineBy::type_

        def initialize: (
          set_type: HubspotSDK::Models::Events::SetOccurrencesRefineBy::set_type,
          type: HubspotSDK::Models::Events::SetOccurrencesRefineBy::type_
        ) -> void

        def to_hash: -> {
          set_type: HubspotSDK::Models::Events::SetOccurrencesRefineBy::set_type,
          type: HubspotSDK::Models::Events::SetOccurrencesRefineBy::type_
        }

        type set_type =
          :ALL
          | :ALL_INCLUDE_EMPTY
          | :ANY
          | :NONE
          | :NONE_EXCLUDE_EMPTY
          | :ANY_INCLUDE_EMPTY

        module SetType
          extend HubspotSDK::Internal::Type::Enum

          ALL: :ALL
          ALL_INCLUDE_EMPTY: :ALL_INCLUDE_EMPTY
          ANY: :ANY
          NONE: :NONE
          NONE_EXCLUDE_EMPTY: :NONE_EXCLUDE_EMPTY
          ANY_INCLUDE_EMPTY: :ANY_INCLUDE_EMPTY

          def self?.values: -> ::Array[HubspotSDK::Models::Events::SetOccurrencesRefineBy::set_type]
        end

        type type_ = :SetOccurrencesRefineBy

        module Type
          extend HubspotSDK::Internal::Type::Enum

          SET_OCCURRENCES_REFINE_BY: :SetOccurrencesRefineBy

          def self?.values: -> ::Array[HubspotSDK::Models::Events::SetOccurrencesRefineBy::type_]
        end
      end
    end
  end
end
