module HubspotSDK
  module Models
    module Events
      type time_point_operation =
        {
          endpoint_behavior: HubspotSDK::Models::Events::TimePointOperation::endpoint_behavior,
          include_objects_with_no_value_set: bool,
          operation_type: String,
          operator: HubspotSDK::Models::Events::TimePointOperation::operator,
          operator_name: String,
          property_parser: HubspotSDK::Models::Events::TimePointOperation::property_parser,
          property_type: HubspotSDK::Models::Events::TimePointOperation::property_type,
          time_point: HubspotSDK::Models::Events::TimePointOperation::time_point,
          type: String,
          default_value: String
        }

      class TimePointOperation < HubspotSDK::Internal::Type::BaseModel
        attr_accessor endpoint_behavior: HubspotSDK::Models::Events::TimePointOperation::endpoint_behavior

        attr_accessor include_objects_with_no_value_set: bool

        attr_accessor operation_type: String

        attr_accessor operator: HubspotSDK::Models::Events::TimePointOperation::operator

        attr_accessor operator_name: String

        attr_accessor property_parser: HubspotSDK::Models::Events::TimePointOperation::property_parser

        attr_accessor property_type: HubspotSDK::Models::Events::TimePointOperation::property_type

        attr_accessor time_point: HubspotSDK::Models::Events::TimePointOperation::time_point

        attr_accessor type: String

        attr_reader default_value: String?

        def default_value=: (String) -> String

        def initialize: (
          endpoint_behavior: HubspotSDK::Models::Events::TimePointOperation::endpoint_behavior,
          include_objects_with_no_value_set: bool,
          operation_type: String,
          operator: HubspotSDK::Models::Events::TimePointOperation::operator,
          operator_name: String,
          property_parser: HubspotSDK::Models::Events::TimePointOperation::property_parser,
          property_type: HubspotSDK::Models::Events::TimePointOperation::property_type,
          time_point: HubspotSDK::Models::Events::TimePointOperation::time_point,
          type: String,
          ?default_value: String
        ) -> void

        def to_hash: -> {
          endpoint_behavior: HubspotSDK::Models::Events::TimePointOperation::endpoint_behavior,
          include_objects_with_no_value_set: bool,
          operation_type: String,
          operator: HubspotSDK::Models::Events::TimePointOperation::operator,
          operator_name: String,
          property_parser: HubspotSDK::Models::Events::TimePointOperation::property_parser,
          property_type: HubspotSDK::Models::Events::TimePointOperation::property_type,
          time_point: HubspotSDK::Models::Events::TimePointOperation::time_point,
          type: String,
          default_value: String
        }

        type endpoint_behavior = :EXCLUSIVE | :INCLUSIVE

        module EndpointBehavior
          extend HubspotSDK::Internal::Type::Enum

          EXCLUSIVE: :EXCLUSIVE
          INCLUSIVE: :INCLUSIVE

          def self?.values: -> ::Array[HubspotSDK::Models::Events::TimePointOperation::endpoint_behavior]
        end

        type operator = :IS_AFTER | :IS_BEFORE

        module Operator
          extend HubspotSDK::Internal::Type::Enum

          IS_AFTER: :IS_AFTER
          IS_BEFORE: :IS_BEFORE

          def self?.values: -> ::Array[HubspotSDK::Models::Events::TimePointOperation::operator]
        end

        type property_parser =
          :ANNIVERSARY
          | :ANNIVERSARY_WITH_ZONE_SAME_LOCAL_CONVERSION
          | :UPDATED_AT
          | :VALUE
          | :VALUE_WITH_ZONE_SAME_LOCAL_CONVERSION

        module PropertyParser
          extend HubspotSDK::Internal::Type::Enum

          ANNIVERSARY: :ANNIVERSARY
          ANNIVERSARY_WITH_ZONE_SAME_LOCAL_CONVERSION: :ANNIVERSARY_WITH_ZONE_SAME_LOCAL_CONVERSION
          UPDATED_AT: :UPDATED_AT
          VALUE: :VALUE
          VALUE_WITH_ZONE_SAME_LOCAL_CONVERSION: :VALUE_WITH_ZONE_SAME_LOCAL_CONVERSION

          def self?.values: -> ::Array[HubspotSDK::Models::Events::TimePointOperation::property_parser]
        end

        type property_type = :timepoint

        module PropertyType
          extend HubspotSDK::Internal::Type::Enum

          TIMEPOINT: :timepoint

          def self?.values: -> ::Array[HubspotSDK::Models::Events::TimePointOperation::property_type]
        end

        type time_point =
          HubspotSDK::Events::DatePoint
          | HubspotSDK::Events::IndexedTimePoint
          | HubspotSDK::Events::PropertyReferencedTime

        module TimePoint
          extend HubspotSDK::Internal::Type::Union

          def self?.variants: -> ::Array[HubspotSDK::Models::Events::TimePointOperation::time_point]
        end
      end
    end
  end
end
