module HubspotSDK
  module Models
    module Events
      type week_reference =
        {
          day_of_week: HubspotSDK::Models::Events::WeekReference::day_of_week,
          reference_type: HubspotSDK::Models::Events::WeekReference::reference_type,
          hour: Integer,
          millisecond: Integer,
          minute: Integer,
          second: Integer
        }

      class WeekReference < HubspotSDK::Internal::Type::BaseModel
        attr_accessor day_of_week: HubspotSDK::Models::Events::WeekReference::day_of_week

        attr_accessor reference_type: HubspotSDK::Models::Events::WeekReference::reference_type

        attr_reader hour: Integer?

        def hour=: (Integer) -> Integer

        attr_reader millisecond: Integer?

        def millisecond=: (Integer) -> Integer

        attr_reader minute: Integer?

        def minute=: (Integer) -> Integer

        attr_reader second: Integer?

        def second=: (Integer) -> Integer

        def initialize: (
          day_of_week: HubspotSDK::Models::Events::WeekReference::day_of_week,
          reference_type: HubspotSDK::Models::Events::WeekReference::reference_type,
          ?hour: Integer,
          ?millisecond: Integer,
          ?minute: Integer,
          ?second: Integer
        ) -> void

        def to_hash: -> {
          day_of_week: HubspotSDK::Models::Events::WeekReference::day_of_week,
          reference_type: HubspotSDK::Models::Events::WeekReference::reference_type,
          hour: Integer,
          millisecond: Integer,
          minute: Integer,
          second: Integer
        }

        type day_of_week =
          :FRIDAY
          | :MONDAY
          | :SATURDAY
          | :SUNDAY
          | :THURSDAY
          | :TUESDAY
          | :WEDNESDAY

        module DayOfWeek
          extend HubspotSDK::Internal::Type::Enum

          FRIDAY: :FRIDAY
          MONDAY: :MONDAY
          SATURDAY: :SATURDAY
          SUNDAY: :SUNDAY
          THURSDAY: :THURSDAY
          TUESDAY: :TUESDAY
          WEDNESDAY: :WEDNESDAY

          def self?.values: -> ::Array[HubspotSDK::Models::Events::WeekReference::day_of_week]
        end

        type reference_type = :WEEK

        module ReferenceType
          extend HubspotSDK::Internal::Type::Enum

          WEEK: :WEEK

          def self?.values: -> ::Array[HubspotSDK::Models::Events::WeekReference::reference_type]
        end
      end
    end
  end
end
