module HubSpotSDK
  module Resources
    class Crm
      class AppUninstalls
        def uninstall: (?request_options: HubSpotSDK::request_opts) -> nil

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
