module HubSpotSDK
  module Resources
    class Crm
      class AssociationsSchema
        attr_reader labels: HubSpotSDK::Resources::Crm::AssociationsSchema::Labels

        attr_reader limits: HubSpotSDK::Resources::Crm::AssociationsSchema::Limits

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
