module HubSpotSDK
  module Resources
    class Crm
      class DealSplits
        attr_reader batch: HubSpotSDK::Resources::Crm::DealSplits::Batch

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
