module HubSpotSDK
  module Resources
    class Crm
      class Exports
        def create_async: (
          public_export_request: HubSpotSDK::Models::Crm::public_export_request,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::TaskLocator

        def get: (
          Integer export_id,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::PublicExportResponse

        def get_status: (
          Integer task_id,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::ActionResponseWithSingleResultUri

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
