module HubspotSDK
  module Resources
    class Crm
      class Extensions
        attr_reader calling: HubspotSDK::Resources::Crm::Extensions::Calling

        attr_reader cards_dev: HubspotSDK::Resources::Crm::Extensions::CardsDev

        attr_reader video_conferencing: HubspotSDK::Resources::Crm::Extensions::VideoConferencing

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
