module HubSpotSDK
  module Resources
    class Crm
      class FeatureFlags
        attr_reader batch: HubSpotSDK::Resources::Crm::FeatureFlags::Batch

        def update: (
          String flag_name,
          app_id: Integer,
          default_state: HubSpotSDK::Models::Crm::FlagPutRequest::default_state,
          ?override_state: HubSpotSDK::Models::Crm::FlagPutRequest::override_state,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::FlagResponse

        def delete: (
          String flag_name,
          app_id: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::FlagResponse

        def delete_portal_state: (
          Integer portal_id,
          app_id: Integer,
          flag_name: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::PortalFlagStateResponse

        def get: (
          String flag_name,
          app_id: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::FlagResponse

        def get_portal_state: (
          Integer portal_id,
          app_id: Integer,
          flag_name: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::PortalFlagStateResponse

        def list_all: (
          Integer app_id,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::FlagsForAppResponse

        def list_portals: (
          String flag_name,
          app_id: Integer,
          ?limit: Integer,
          ?start_portal_id: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::PortalFlagStateBatchResponse

        def update_portal_state: (
          Integer portal_id,
          app_id: Integer,
          flag_name: String,
          flag_state: HubSpotSDK::Models::Crm::PortalFlagStatePutRequest::flag_state,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::PortalFlagStateResponse

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
