module HubSpotSDK
  module Resources
    class Crm
      class Imports
        def create: (
          ?files: HubSpotSDK::Internal::file_input,
          ?import_request: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::PublicImportResponse

        def list: (
          ?after: String,
          ?limit: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Crm::PublicImportResponse]

        def cancel: (
          Integer import_id,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::ActionResponse

        def get: (
          Integer import_id,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::PublicImportResponse

        def list_errors: (
          Integer import_id,
          ?after: String,
          ?include_error_message: bool,
          ?include_row_data: bool,
          ?limit: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Crm::PublicImportError]

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
