module HubspotSDK
  module Resources
    class Crm
      class Imports
        def create: (
          ?files: HubspotSDK::Internal::file_input,
          ?import_request: String,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::PublicImportResponse

        def list: (
          ?after: String,
          ?limit: Integer,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Internal::Page[HubspotSDK::Crm::PublicImportResponse]

        def cancel: (
          Integer import_id,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::ActionResponse

        def get: (
          Integer import_id,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::PublicImportResponse

        def list_errors: (
          Integer import_id,
          ?after: String,
          ?include_error_message: bool,
          ?include_row_data: bool,
          ?limit: Integer,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Internal::Page[HubspotSDK::Crm::PublicImportError]

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
