module HubSpotSDK
  module Resources
    class Crm
      class Limits
        def get_association_label_limits: (
          ?from_object_type_id: String,
          ?to_object_type_id: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::CollectionResponseAssociationLabelLimitResponseNoPaging

        def get_association_records_limits_by_object_type: (
          String to_object_type_id,
          from_object_type_id: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::AssociationRecordLimitResponse

        def get_association_records_limits_from_objects: (
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::CollectionResponseObjectTypeNearOrAtAssociationLimitNoPaging

        def get_association_records_limits_to_objects: (
          String from_object_type_id,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::CollectionResponseObjectTypeNearOrAtAssociationLimitNoPaging

        def get_calculated_property_limits: (
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::CalculatedPropertyLimitResponse

        def get_custom_object_type_limits: (
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::CustomObjectLimitResponse

        def get_custom_property_limits: (
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::CustomPropertyLimitResponse

        def get_pipeline_limits: (
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::PipelineLimitResponse

        def get_record_limits: (
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::RecordLimitResponse

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
