module HubspotSDK
  module Resources
    class Crm
      class Lists
        attr_reader folders: HubspotSDK::Resources::Crm::Lists::Folders

        attr_reader mapping: HubspotSDK::Resources::Crm::Lists::Mapping

        attr_reader memberships: HubspotSDK::Resources::Crm::Lists::Memberships

        def create: (
          name: String,
          object_type_id: String,
          processing_type: String,
          ?custom_properties: ::Hash[Symbol, String],
          ?filter_branch: HubspotSDK::Models::Crm::ListCreateRequest::filter_branch,
          ?list_folder_id: Integer,
          ?list_permissions: HubspotSDK::Crm::PublicListPermissions,
          ?membership_settings: HubspotSDK::Crm::PublicMembershipSettings,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::ListCreateResponse

        def list: (
          ?include_filters: bool,
          ?list_ids: ::Array[String],
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::ListsByIDResponse

        def delete: (
          String list_id,
          ?request_options: HubspotSDK::request_opts
        ) -> nil

        def delete_schedule_conversion: (
          String list_id,
          ?request_options: HubspotSDK::request_opts
        ) -> nil

        def get: (
          String list_id,
          ?include_filters: bool,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::ListFetchResponse

        def get_by_object_type_id_and_name: (
          String list_name,
          object_type_id: String,
          ?include_filters: bool,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::ListFetchResponse

        def get_schedule_conversion: (
          String list_id,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::PublicListConversionResponse

        def restore: (
          String list_id,
          ?request_options: HubspotSDK::request_opts
        ) -> nil

        def schedule_conversion: (
          String list_id,
          public_list_conversion_time: HubspotSDK::Models::Crm::PublicListConversionTime,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::PublicListConversionResponse

        def search: (
          additional_properties: ::Array[String],
          offset: Integer,
          ?count: Integer,
          ?list_ids: ::Array[String],
          ?processing_types: ::Array[String],
          ?query: String,
          ?sort: String,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::ListSearchResponse

        def update_filters: (
          String list_id,
          filter_branch: HubspotSDK::Models::Crm::ListFilterUpdateRequest::filter_branch,
          ?enroll_objects_in_workflows: bool,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::ListUpdateResponse

        def update_name: (
          String list_id,
          ?include_filters: bool,
          ?list_name: String,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::ListUpdateResponse

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
