module HubspotSDK
  module Resources
    class Crm
      class ObjectLibrary
        attr_reader enablement: HubspotSDK::Resources::Crm::ObjectLibrary::Enablement

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
