module HubSpotSDK
  module Resources
    class Crm
      class ObjectLibrary
        attr_reader enablement: HubSpotSDK::Resources::Crm::ObjectLibrary::Enablement

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
