module HubSpotSDK
  module Resources
    class Crm
      class Owners
        def list: (
          ?after: String,
          ?archived: bool,
          ?email: String,
          ?limit: Integer,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Crm::PublicOwner]

        def get: (
          Integer owner_id,
          ?archived: bool,
          ?id_property: HubSpotSDK::Models::Crm::OwnerGetParams::id_property,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::PublicOwner

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
