module HubSpotSDK
  module Resources
    class Crm
      class Properties
        attr_reader batch: HubSpotSDK::Resources::Crm::Properties::Batch

        attr_reader groups: HubSpotSDK::Resources::Crm::Properties::Groups

        def create: (
          String object_type,
          field_type: HubSpotSDK::Models::PropertyCreate::field_type,
          group_name: String,
          label: String,
          name: String,
          type: HubSpotSDK::Models::PropertyCreate::type_,
          ?calculation_formula: String,
          ?currency_property_name: String,
          ?data_sensitivity: HubSpotSDK::Models::PropertyCreate::data_sensitivity,
          ?description: String,
          ?display_order: Integer,
          ?external_options: bool,
          ?form_field: bool,
          ?has_unique_value: bool,
          ?hidden: bool,
          ?number_display_hint: HubSpotSDK::Models::PropertyCreate::number_display_hint,
          ?options: ::Array[HubSpotSDK::OptionInput],
          ?referenced_object_type: String,
          ?show_currency_symbol: bool,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::BaseProperty

        def update: (
          String property_name,
          object_type: String,
          ?calculation_formula: String,
          ?currency_property_name: String,
          ?description: String,
          ?display_order: Integer,
          ?field_type: HubSpotSDK::Models::Crm::PropertyUpdate::field_type,
          ?form_field: bool,
          ?group_name: String,
          ?hidden: bool,
          ?label: String,
          ?number_display_hint: HubSpotSDK::Models::Crm::PropertyUpdate::number_display_hint,
          ?options: ::Array[HubSpotSDK::OptionInput],
          ?show_currency_symbol: bool,
          ?type: HubSpotSDK::Models::Crm::PropertyUpdate::type_,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::BaseProperty

        def list: (
          String object_type,
          ?archived: bool,
          ?data_sensitivity: HubSpotSDK::Models::Crm::PropertyListParams::data_sensitivity,
          ?locale: String,
          ?properties: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::Crm::CollectionResponsePropertyNoPaging

        def delete: (
          String property_name,
          object_type: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> nil

        def get: (
          String property_name,
          object_type: String,
          ?archived: bool,
          ?data_sensitivity: HubSpotSDK::Models::Crm::PropertyGetParams::data_sensitivity,
          ?locale: String,
          ?properties: String,
          ?request_options: HubSpotSDK::request_opts
        ) -> HubSpotSDK::BaseProperty

        def initialize: (client: HubSpotSDK::Client) -> void
      end
    end
  end
end
