module HubspotSDK
  module Resources
    class Crm
      class Properties
        attr_reader batch: HubspotSDK::Resources::Crm::Properties::Batch

        attr_reader groups: HubspotSDK::Resources::Crm::Properties::Groups

        def create: (
          String object_type,
          field_type: HubspotSDK::Models::Crm::PropertyCreate::field_type,
          group_name: String,
          label: String,
          name: String,
          type: HubspotSDK::Models::Crm::PropertyCreate::type_,
          ?calculation_formula: String,
          ?currency_property_name: String,
          ?data_sensitivity: HubspotSDK::Models::Crm::PropertyCreate::data_sensitivity,
          ?description: String,
          ?display_order: Integer,
          ?external_options: bool,
          ?form_field: bool,
          ?has_unique_value: bool,
          ?hidden: bool,
          ?options: ::Array[HubspotSDK::OptionInput],
          ?referenced_object_type: String,
          ?show_currency_symbol: bool,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::Property

        def update: (
          String property_name,
          object_type: String,
          ?calculation_formula: String,
          ?currency_property_name: String,
          ?description: String,
          ?display_order: Integer,
          ?field_type: HubspotSDK::Models::Crm::PropertyUpdate::field_type,
          ?form_field: bool,
          ?group_name: String,
          ?hidden: bool,
          ?label: String,
          ?options: ::Array[HubspotSDK::OptionInput],
          ?show_currency_symbol: bool,
          ?type: HubspotSDK::Models::Crm::PropertyUpdate::type_,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::Property

        def list: (
          String object_type,
          ?archived: bool,
          ?data_sensitivity: HubspotSDK::Models::Crm::PropertyListParams::data_sensitivity,
          ?locale: String,
          ?properties: String,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::CollectionResponsePropertyNoPaging

        def delete: (
          String property_name,
          object_type: String,
          ?request_options: HubspotSDK::request_opts
        ) -> nil

        def get: (
          String property_name,
          object_type: String,
          ?archived: bool,
          ?data_sensitivity: HubspotSDK::Models::Crm::PropertyGetParams::data_sensitivity,
          ?locale: String,
          ?properties: String,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::Property

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
