module HubspotSDK
  module Resources
    class Crm
      class Timeline
        attr_reader batch: HubspotSDK::Resources::Crm::Timeline::Batch

        def create_event: (
          id: String,
          event_type_name: String,
          properties: ::Hash[Symbol, String],
          ?domain: String,
          ?email: String,
          ?extra_data: top,
          ?object_id_: String,
          ?object_type_fully_qualified_name: String,
          ?timeline_i_frame: HubspotSDK::Crm::TimelineEventIFrame,
          ?timestamp: Time,
          ?utk: String,
          ?request_options: HubspotSDK::request_opts
        ) -> nil

        def create_project_type: (
          developer_symbol: String,
          project_name: String,
          ?request_options: HubspotSDK::request_opts
        ) -> HubspotSDK::Crm::AppEventResolutionResponse

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
