module HubspotSDK
  module Resources
    class Crm
      class Timeline
        attr_reader events: HubspotSDK::Resources::Crm::Timeline::Events

        attr_reader templates: HubspotSDK::Resources::Crm::Timeline::Templates

        attr_reader tokens: HubspotSDK::Resources::Crm::Timeline::Tokens

        def initialize: (client: HubspotSDK::Client) -> void
      end
    end
  end
end
