module HubSpotSDK
  module Models
    module Crm
      module Objects
        module Companies
          type batch_get_params =
            { archived: bool } & HubSpotSDK::Internal::Type::request_parameters

          class BatchGetParams < HubSpotSDK::Models::Crm::BatchReadInputSimplePublicObjectID
            extend HubSpotSDK::Internal::Type::RequestParameters::Converter
            include HubSpotSDK::Internal::Type::RequestParameters

            def archived: -> bool?

            def archived=: (bool _) -> bool

            def initialize: (
              ?archived: bool,
              ?request_options: HubSpotSDK::request_opts
            ) -> void

            def to_hash: -> {
              archived: bool,
              request_options: HubSpotSDK::RequestOptions
            }
          end
        end
      end
    end
  end
end
