module HubspotSDK
  module Resources
    class Cms
      class Blogs
        class Tags
          class Batch
            def delete: (
              inputs: ::Array[String],
              ?request_options: HubspotSDK::request_opts
            ) -> nil

            def create_batch: (
              inputs: ::Array[HubspotSDK::Cms::Blogs::Tag],
              ?request_options: HubspotSDK::request_opts
            ) -> StringIO

            def get_batch: (
              inputs: ::Array[String],
              ?archived: bool,
              ?request_options: HubspotSDK::request_opts
            ) -> StringIO

            def update_batch: (
              inputs: ::Array[top],
              ?archived: bool,
              ?request_options: HubspotSDK::request_opts
            ) -> StringIO

            def initialize: (client: HubspotSDK::Client) -> void
          end
        end
      end
    end
  end
end
