module HubSpotSDK
  module Resources
    class Scheduler
      class Meetings
        class Advanced
          def create: (
            organizer_user_id: String,
            associations: ::Array[HubSpotSDK::Scheduler::ExternalAssociationCreateRequest],
            email_reminder_schedule: HubSpotSDK::Scheduler::ExternalEmailReminderSchedule,
            properties: HubSpotSDK::Scheduler::ExternalCalendarMeetingEventCreateProperties,
            timezone: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Scheduler::ExternalCalenderMeetingEventResponse

          def book: (
            duration: Integer,
            email: String,
            first_name: String,
            form_fields: ::Array[HubSpotSDK::Scheduler::ExternalBookingFormField],
            last_name: String,
            legal_consent_responses: ::Array[HubSpotSDK::Scheduler::ExternalLegalConsentResponse],
            likely_available_user_ids: ::Array[String],
            slug: String,
            start_time: Time,
            ?locale: String,
            ?timezone: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Scheduler::ExternalMeetingBookingResponse

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
