module HubSpotSDK
  module Resources
    class Scheduler
      class Meetings
        class Basic
          def list: (
            ?after: String,
            ?limit: Integer,
            ?name: String,
            ?organizer_user_id: String,
            ?type: HubSpotSDK::Models::Scheduler::Meetings::BasicListParams::type_,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Internal::Page[HubSpotSDK::Scheduler::ExternalLinkMetadata]

          def get_availability_by_slug: (
            String slug,
            timezone: String,
            ?month_offset: Integer,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Scheduler::ExternalLinkAvailabilityAndBusyTimes

          def get_booking_info_by_slug: (
            String slug,
            timezone: String,
            ?request_options: HubSpotSDK::request_opts
          ) -> HubSpotSDK::Scheduler::ExternalBookingInfo

          def initialize: (client: HubSpotSDK::Client) -> void
        end
      end
    end
  end
end
