module HubspotSDK
  module Resources
    class Scheduler
      class Meetings
        class Calendar
          def create: (
            associations: ::Array[HubspotSDK::Scheduler::ExternalAssociationCreateRequest],
            email_reminder_schedule: HubspotSDK::Scheduler::ExternalEmailReminderSchedule,
            properties: HubspotSDK::Scheduler::ExternalCalendarMeetingEventCreateProperties,
            timezone: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Scheduler::ExternalCalenderMeetingEventResponse

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
