module HubspotSDK
  module Resources
    class Scheduler
      class Meetings
        class MeetingsLinks
          def list: (
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Scheduler::CollectionResponseWithTotalExternalLinkMetadataForwardPaging

          def book: (
            duration: Integer,
            email: String,
            first_name: String,
            form_fields: ::Array[HubspotSDK::Scheduler::ExternalBookingFormField],
            last_name: String,
            legal_consent_responses: ::Array[HubspotSDK::Scheduler::ExternalLegalConsentResponse],
            likely_available_user_ids: ::Array[String],
            slug: String,
            start_time: Time,
            ?locale: String,
            ?timezone: String,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Scheduler::ExternalMeetingBookingResponse

          def get_availability_by_slug: (
            String slug,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Scheduler::ExternalLinkAvailabilityAndBusyTimes

          def get_booking_info_by_slug: (
            String slug,
            ?request_options: HubspotSDK::request_opts
          ) -> HubspotSDK::Scheduler::ExternalBookingInfo

          def initialize: (client: HubspotSDK::Client) -> void
        end
      end
    end
  end
end
